import type { Metadata } from "next";
import GuideLayout from "../components/GuideLayout";

export const metadata: Metadata = { title: "Hipobuy Listing Verification & Product Index Checks", description: "Verify whether Hipobuy source listings are live, compare current variants and use category discovery without relying on stale spreadsheet rows.", alternates: { canonical: "/spreadsheet" } };

const categoryLinks = [
  ["Shoes", "https://cnfanssp.com/shoes/"], ["Hoodies", "https://cnfanssp.com/hoodies-sweaters/"], ["T-Shirts", "https://cnfanssp.com/t-shirts/"], ["Jackets", "https://cnfanssp.com/jackets/"], ["Pants & Shorts", "https://cnfanssp.com/pants-shorts/"], ["Headwear", "https://cnfanssp.com/headwear/"], ["Accessories", "https://cnfanssp.com/accessories/"], ["Jerseys", "https://cnfanssp.com/Jersey/"], ["Electronics", "https://cnfanssp.com/electronics/"]
];

export default function SpreadsheetPage() { return <GuideLayout kicker="Product discovery" title="How to use a Hipobuy spreadsheet without buying blind." intro="A spreadsheet is a discovery index, not proof of quality. Use it to find a source listing quickly, then verify the live page and warehouse evidence before making the next decision.">
  <section className="content-split"><div className="sticky-title"><span>01</span><h2>Start with the source</h2><p>The displayed card is only a snapshot. Product variants, price, availability and seller terms can change.</p></div><div className="prose"><h3>The four checks that matter</h3><ol><li><strong>Open the exact listing.</strong> Confirm that the title, photos and available variants still describe the item you intended to find.</li><li><strong>Read the options carefully.</strong> A low headline price may represent the cheapest color, size or accessory—not the version shown in the main image.</li><li><strong>Check domestic delivery.</strong> Seller-to-warehouse shipping and dispatch time affect both cost and how quickly QC photos become available.</li><li><strong>Save the source reference.</strong> Keep the listing URL and your chosen variant together so you can compare them with the warehouse record.</li></ol><div className="callout"><b>Directory rule</b><p>A product row is a lead to investigate, not an endorsement of the seller or item.</p></div></div></section>
  <section className="category-directory"><div className="section-heading"><div><p className="section-kicker">Browse routes</p><h2>Explore by category</h2></div><p>Every category opens the matching collection on the main product index.</p></div><div className="route-grid">{categoryLinks.map(([name,url],index)=><a href={url} key={name}><span>{String(index+1).padStart(2,"0")}</span><strong>{name}</strong><b>↗</b></a>)}</div></section>
  <section className="content-split reverse"><div className="sticky-title"><span>02</span><h2>Move from find to QC</h2><p>The most useful spreadsheet workflow continues after the warehouse receives the item.</p></div><div className="prose"><h3>A practical decision sequence</h3><div className="timeline"><div><b>Find</b><p>Use search and category filters to locate relevant source pages.</p></div><div><b>Verify</b><p>Confirm listing details, variants, seller photos and current terms.</p></div><div><b>Order</b><p>Submit the source page through the shopping-agent workflow.</p></div><div><b>Inspect</b><p>Compare warehouse QC photos with the listing and your order details.</p></div><div><b>Ship</b><p>Choose a line only after checking restrictions, parcel data and landed cost.</p></div></div><a className="solid-button" href="https://cnfanssp.com/AllProducts/">Browse product finds ↗</a></div></section>
  </GuideLayout>; }
