export const localizedDepth = {
  es: {
    category: {
      label: "Registro de comparación",
      title: "Guarda pruebas útiles antes de elegir.",
      intro: (name) => `Para comparar ${name.toLowerCase()} de forma responsable, anota la opción exacta, usa el mismo método de medida y relaciona cada foto con la variante seleccionada. Estas comprobaciones reducen errores sin sustituir la información actual del anuncio.`,
      reviewed: "Ruta de categoría revisada el 26 de agosto de 2026. La disponibilidad, las opciones y las condiciones externas pueden cambiar.",
      productLabel: "Producto actual", productTitle: "Una ficha real, comprobada directamente.", openListing: "Abrir ficha verificada", fallback: "Búsqueda alternativa",
      tableLabel: "Tabla de talla y QC", tableTitle: "Registra pruebas, no impresiones.", tableHeaders: ["Comprobación", "Qué anotar", "Prueba útil"], tableRecord: "Anota el valor o la opción exacta.", tableEvidence: "Foto, tabla o texto de la ficha actual.",
      faqTitle: "Preguntas de comprobación", updateLabel: "Registro de cambios", updateTitle: "Producto y guía actualizados", updateText: "Se verificó la ficha, se añadió una búsqueda alternativa y se actualizó la tabla de talla/QC.", disclosure: "La inclusión no verifica stock, calidad, autenticidad ni idoneidad. Confirma la opción actual.",
    },
    guide: {
      label: "Comprobación práctica",
      title: "Convierte la lectura en una revisión repetible.",
      intro: "Usa estos puntos como registro breve. Si un dato no aparece o dos fuentes no coinciden, detén la comparación y confirma la información en la página actual.",
    },
    indexes: {
      categoriesTitle: "Cómo usar el directorio",
      categoriesText: "Elige primero el tipo de producto. Después aplica la lista específica de esa categoría y abre el destino únicamente para confirmar datos actuales.",
      guidesTitle: "Lee según la decisión que necesitas tomar",
      guidesText: "La guía de uso explica el proceso completo; las guías de talla, fotos QC y envío resuelven comprobaciones concretas. Guarda el anuncio actual como referencia final.",
    },
    about: {
      title: "Cómo revisamos una ruta",
      intro: "Cada ruta se separa en tres capas para que la orientación editorial no se confunda con los datos cambiantes de un anuncio externo.",
      steps: [["Contexto", "Explicamos qué información sirve para comparar ese tipo de producto."], ["Comprobación", "Revisamos que la ruta externa abra y corresponda a la categoría indicada."], ["Límite", "Marcamos qué datos deben volver a confirmarse antes de cualquier decisión."]],
    },
    faqExtra: [["¿Cuándo se revisan los enlaces?", "Las rutas se comprueban periódicamente y muestran una fecha de revisión cuando procede. Un enlace válido no garantiza que todas las opciones sigan disponibles."], ["¿Qué hago si faltan medidas o fotos?", "No completes los huecos con suposiciones. Busca otra opción con datos comparables o espera a que el destino publique información suficiente."]],
    categoryChecks: {
      shoes: ["Compara la longitud del pie y la longitud interior, no solo la talla impresa.", "Revisa puntera, talón, suela y ambos lados desde ángulos equivalentes.", "Confirma color, talla, stock y posible volumen de la caja en el anuncio actual."],
      headwear: ["Compara el contorno de la cabeza con el rango de ajuste indicado.", "Comprueba profundidad de copa, tipo de cierre y forma de la visera.", "Revisa costuras y bordado en el color exacto que has seleccionado."],
      "hoodies-sweaters": ["Compara pecho, hombros, manga y largo con una prenda propia.", "Confirma composición, peso del tejido y acabado interior cuando estén disponibles.", "Relaciona puños, bajo y gráficos con la talla y el color seleccionados."],
      "t-shirts": ["Mide hombros, pecho y largo con la prenda colocada en plano.", "Comprueba composición, gramaje disponible y construcción del cuello.", "Revisa posición y acabado del estampado en la opción exacta."],
      jackets: ["Usa como referencia una chaqueta que deje espacio para tus capas habituales.", "Examina cremalleras, bolsillos, forro y uniones de costuras.", "Confirma talla, peso y volumen embalado antes de planificar el envío."],
      "pants-shorts": ["Compara cintura, tiro, entrepierna, muslo y abertura de pierna.", "Aclara si la cintura se indica en plano, como contorno o como rango elástico.", "Relaciona las medidas con el corte exacto y la opción seleccionada."],
      accessories: ["Anota largo, ancho y profundidad reales en lugar de estimarlos por la foto.", "Revisa cierres, bordes, bisagras y otras piezas móviles.", "Confirma material, piezas incluidas y dimensiones en el anuncio actual."],
      electronics: ["Compara el número de modelo y la revisión completos.", "Comprueba voltaje, enchufe, conectores y compatibilidad regional.", "Confirma accesorios incluidos, garantía y condiciones para artículos restringidos."],
    },
    guideChecks: {
      "what-is-a-hacoo-spreadsheet": ["Distingue un índice editorial de una tienda o servicio oficial.", "Comprueba que cada enlace lleve a una página actual y pertinente.", "No interpretes una inclusión como garantía de calidad o disponibilidad."],
      "how-to-use-hacoo-spreadsheet": ["Empieza por una categoría concreta, no por una lista interminable.", "Compara las mismas medidas y opciones en todos los candidatos.", "Termina en el anuncio actual y vuelve a verificar sus condiciones."],
      "hacoo-reviews-explained": ["Separa opiniones sobre la aplicación, el pedido, el producto y el transporte.", "Comprueba fecha, país, variante y pruebas antes de usar una experiencia como referencia.", "Contrasta los temas de las reseñas con la política oficial actual."],
      "qc-photo-checklist": ["Busca vistas frontal, posterior, lateral y de detalles equivalentes.", "Relaciona todas las fotos con la misma talla, color y variante.", "Pide claridad cuando una medida o una zona importante no sea visible."],
      "size-guide": ["Mide una prenda propia con el mismo método de la tabla.", "Compara medidas de la prenda, no solo letras de talla.", "Deja margen según el corte, las capas previstas y la tolerancia indicada."],
      "shipping-planning": ["Registra peso y dimensiones cuando el destino los publique.", "Comprueba restricciones, impuestos y métodos para tu país.", "Usa la cotización actual; no conviertas una estimación antigua en promesa."],
      "hacoo-returns-refunds": ["Confirma elegibilidad y plazo antes de preparar una devolución.", "Guarda fotos del paquete, la opción y el problema exacto.", "Usa Refund/Exchange dentro del pedido y conserva la cronología del caso."],
    },
  },
  fr: {
    category: {
      label: "Fiche de comparaison",
      title: "Conservez des éléments utiles avant de choisir.",
      intro: (name) => `Pour comparer les ${name.toLowerCase()} de façon responsable, notez l’option exacte, utilisez la même méthode de mesure et associez chaque photo à la variante sélectionnée. Ces contrôles réduisent les erreurs sans remplacer l’annonce actuelle.`,
      reviewed: "Parcours de catégorie vérifié le 26 août 2026. Disponibilité, options et conditions externes peuvent changer.",
      productLabel: "Produit actuel", productTitle: "Une annonce réelle, vérifiée directement.", openListing: "Ouvrir l’annonce vérifiée", fallback: "Recherche de secours",
      tableLabel: "Tableau taille et QC", tableTitle: "Notez des preuves, pas des impressions.", tableHeaders: ["Contrôle", "À noter", "Preuve utile"], tableRecord: "Notez la valeur ou l’option exacte.", tableEvidence: "Photo, tableau ou texte de l’annonce actuelle.",
      faqTitle: "Questions de vérification", updateLabel: "Journal des mises à jour", updateTitle: "Produit et guide actualisés", updateText: "L’annonce a été vérifiée, une recherche de secours a été ajoutée et le tableau taille/QC a été actualisé.", disclosure: "L’inclusion ne confirme ni stock, qualité, authenticité ni adéquation. Vérifiez l’option actuelle.",
    },
    guide: {
      label: "Contrôle pratique",
      title: "Transformez la lecture en vérification reproductible.",
      intro: "Utilisez ces points comme une courte fiche. Si une donnée manque ou si deux sources se contredisent, interrompez la comparaison et confirmez l’information sur la page actuelle.",
    },
    indexes: {
      categoriesTitle: "Comment utiliser le répertoire",
      categoriesText: "Choisissez d’abord le type de produit. Appliquez ensuite la liste propre à cette catégorie et ouvrez la destination uniquement pour confirmer les données actuelles.",
      guidesTitle: "Lisez selon la décision à prendre",
      guidesText: "Le guide d’utilisation présente le parcours complet ; les guides de tailles, photos QC et livraison répondent à des contrôles précis. L’annonce actuelle reste la référence finale.",
    },
    about: {
      title: "Comment nous vérifions un parcours",
      intro: "Chaque parcours est séparé en trois niveaux afin de ne pas confondre les conseils éditoriaux avec les données changeantes d’une annonce externe.",
      steps: [["Contexte", "Nous expliquons quelles informations permettent de comparer ce type de produit."], ["Vérification", "Nous contrôlons que la destination s’ouvre et correspond à la catégorie annoncée."], ["Limite", "Nous indiquons les données qui doivent être confirmées avant toute décision."]],
    },
    faqExtra: [["Quand les liens sont-ils vérifiés ?", "Les parcours sont contrôlés périodiquement et affichent une date de révision lorsque cela est utile. Un lien valide ne garantit pas que chaque option reste disponible."], ["Que faire si des mesures ou des photos manquent ?", "Ne comblez pas les lacunes par des suppositions. Choisissez une autre option comparable ou attendez que la destination fournisse assez d’informations."]],
    categoryChecks: {
      shoes: ["Comparez la longueur du pied et la longueur intérieure, pas seulement la pointure.", "Examinez bout, talon, semelle et deux côtés sous des angles comparables.", "Confirmez couleur, taille, stock et volume éventuel de la boîte sur l’annonce actuelle."],
      headwear: ["Comparez le tour de tête avec la plage d’ajustement indiquée.", "Vérifiez profondeur de calotte, fermeture et forme de visière.", "Contrôlez coutures et broderie sur la couleur exacte sélectionnée."],
      "hoodies-sweaters": ["Comparez poitrine, épaules, manches et longueur avec un vêtement que vous possédez.", "Confirmez composition, poids du tissu et finition intérieure lorsqu’ils sont indiqués.", "Associez poignets, ourlet et motifs à la taille et à la couleur choisies."],
      "t-shirts": ["Mesurez épaules, poitrine et longueur avec le vêtement posé à plat.", "Vérifiez composition, grammage disponible et construction du col.", "Examinez placement et finition du motif sur l’option exacte."],
      jackets: ["Utilisez une veste qui laisse de la place à vos couches habituelles comme référence.", "Examinez fermetures, poches, doublure et raccords de couture.", "Confirmez taille, poids et volume emballé avant de planifier l’expédition."],
      "pants-shorts": ["Comparez taille, fourche, entrejambe, cuisse et ouverture de jambe.", "Déterminez si la taille est donnée à plat, en circonférence ou en plage élastique.", "Associez les mesures à la coupe et à l’option exactes."],
      accessories: ["Notez longueur, largeur et profondeur réelles au lieu de les deviner sur une photo.", "Examinez fermetures, bords, charnières et autres pièces mobiles.", "Confirmez matière, pièces incluses et dimensions sur l’annonce actuelle."],
      electronics: ["Faites correspondre le numéro de modèle et la révision complets.", "Vérifiez tension, prise, connecteurs et compatibilité régionale.", "Confirmez accessoires inclus, garantie et règles concernant les articles restreints."],
    },
    guideChecks: {
      "what-is-a-hacoo-spreadsheet": ["Distinguez un index éditorial d’une boutique ou d’un service officiel.", "Vérifiez que chaque lien mène à une page actuelle et pertinente.", "Ne considérez pas une inclusion comme une garantie de qualité ou de disponibilité."],
      "how-to-use-hacoo-spreadsheet": ["Commencez par une catégorie précise plutôt que par une liste interminable.", "Comparez les mêmes mesures et options pour chaque candidat.", "Terminez sur l’annonce actuelle et vérifiez de nouveau ses conditions."],
      "hacoo-reviews-explained": ["Distinguez les avis sur l’application, la commande, le produit et le transport.", "Vérifiez date, pays, variante et preuves avant d’utiliser une expérience.", "Comparez les thèmes des avis avec la politique officielle actuelle."],
      "qc-photo-checklist": ["Cherchez des vues avant, arrière, côté et détail comparables.", "Associez toutes les photos à la même taille, couleur et variante.", "Demandez des précisions lorsqu’une mesure ou une zone importante n’est pas visible."],
      "size-guide": ["Mesurez un vêtement que vous possédez avec la même méthode que le tableau.", "Comparez les mesures du vêtement, pas seulement les lettres de taille.", "Prévoyez une marge selon la coupe, les couches et la tolérance indiquée."],
      "shipping-planning": ["Notez poids et dimensions lorsque la destination les publie.", "Vérifiez restrictions, taxes et méthodes pour votre pays.", "Utilisez le devis actuel ; ne transformez pas une ancienne estimation en promesse."],
      "hacoo-returns-refunds": ["Confirmez l’éligibilité et le délai avant de préparer un retour.", "Conservez des photos du colis, de la variante et du problème précis.", "Utilisez Refund/Exchange dans la commande et gardez la chronologie du dossier."],
    },
  },
  de: {
    category: {
      label: "Vergleichsprotokoll",
      title: "Halte nützliche Nachweise vor der Auswahl fest.",
      intro: (name) => `Um ${name.toLowerCase()} verlässlich zu vergleichen, notiere die genaue Variante, nutze dieselbe Messmethode und ordne jedes Foto der ausgewählten Option zu. Diese Prüfungen verringern Fehler, ersetzen aber nicht die Angaben im aktuellen Angebot.`,
      reviewed: "Kategorieroute geprüft am 26. August 2026. Verfügbarkeit, Varianten und externe Bedingungen können sich ändern.",
      productLabel: "Aktuelles Produkt", productTitle: "Ein echtes Angebot, direkt geprüft.", openListing: "Geprüftes Angebot öffnen", fallback: "Ersatzsuche",
      tableLabel: "Größen- und QC-Tabelle", tableTitle: "Nachweise statt Eindrücke festhalten.", tableHeaders: ["Prüfung", "Zu notieren", "Nützlicher Nachweis"], tableRecord: "Notiere den genauen Wert oder die Variante.", tableEvidence: "Foto, Tabelle oder Text des aktuellen Angebots.",
      faqTitle: "Prüffragen", updateLabel: "Änderungsprotokoll", updateTitle: "Produkt und Ratgeber aktualisiert", updateText: "Das Angebot wurde geprüft, eine Ersatzsuche ergänzt und die Größen-/QC-Tabelle aktualisiert.", disclosure: "Die Aufnahme bestätigt weder Bestand, Qualität, Echtheit noch Eignung. Prüfe die aktuelle Variante.",
    },
    guide: {
      label: "Praktische Prüfung",
      title: "Mache aus dem Lesen einen wiederholbaren Ablauf.",
      intro: "Nutze diese Punkte als kurzes Protokoll. Fehlt eine Angabe oder widersprechen sich zwei Quellen, unterbrich den Vergleich und bestätige die Information auf der aktuellen Seite.",
    },
    indexes: {
      categoriesTitle: "So nutzt du das Verzeichnis",
      categoriesText: "Wähle zuerst die Produktart. Nutze danach die passende Checkliste und öffne das Ziel nur, um aktuelle Angaben zu bestätigen.",
      guidesTitle: "Lies passend zu deiner Entscheidung",
      guidesText: "Der Nutzungsratgeber erklärt den gesamten Ablauf; Größen-, QC-Foto- und Versandratgeber lösen einzelne Prüfaufgaben. Notiere für jede Auswahl vergleichbare Angaben, prüfe fehlende Informationen sorgfältig und behandle das aktuelle Angebot immer als letzte Referenz.",
    },
    about: {
      title: "So prüfen wir eine Route",
      intro: "Jede Route wird in drei Ebenen getrennt, damit redaktionelle Hinweise nicht mit veränderlichen Daten eines externen Angebots verwechselt werden.",
      steps: [["Kontext", "Wir erklären, welche Angaben sich zum Vergleich dieser Produktart eignen."], ["Prüfung", "Wir kontrollieren, ob das externe Ziel erreichbar ist und zur genannten Kategorie passt."], ["Grenze", "Wir kennzeichnen Angaben, die vor einer Entscheidung erneut bestätigt werden müssen."]],
    },
    faqExtra: [["Wann werden die Links geprüft?", "Routen werden regelmäßig kontrolliert und zeigen bei Bedarf ein Prüfdatum. Ein gültiger Link garantiert nicht, dass jede Variante verfügbar bleibt."], ["Was tue ich bei fehlenden Maßen oder Fotos?", "Fülle Lücken nicht mit Vermutungen. Wähle eine vergleichbare Option mit besseren Angaben oder warte auf ausreichende Informationen am Ziel."]],
    categoryChecks: {
      shoes: ["Vergleiche Fußlänge und Innenlänge, nicht nur die aufgedruckte Größe.", "Prüfe Zehenform, Ferse, Sohle und beide Seiten aus vergleichbaren Winkeln.", "Bestätige Farbe, Größe, Bestand und mögliches Kartonvolumen im aktuellen Angebot."],
      headwear: ["Vergleiche den Kopfumfang mit dem angegebenen Einstellbereich.", "Prüfe Kronentiefe, Verschlussart und Schirmform.", "Kontrolliere Nähte und Stickerei an der genau ausgewählten Farbe."],
      "hoodies-sweaters": ["Vergleiche Brust, Schulter, Ärmel und Länge mit einem eigenen Kleidungsstück.", "Bestätige Material, Stoffgewicht und Innenverarbeitung, soweit angegeben.", "Ordne Bündchen, Saum und Grafiken der gewählten Größe und Farbe zu."],
      "t-shirts": ["Miss Schulter, Brust und Länge am flach liegenden Kleidungsstück.", "Prüfe Material, verfügbares Stoffgewicht und Kragenkonstruktion.", "Kontrolliere Position und Ausführung des Motivs an der genauen Option."],
      jackets: ["Nutze eine Jacke mit Platz für deine üblichen Schichten als Referenz.", "Prüfe Reißverschlüsse, Taschen, Futter und Nahtverbindungen.", "Bestätige Größe, Gewicht und Packvolumen vor der Versandplanung."],
      "pants-shorts": ["Vergleiche Bund, Leibhöhe, Innenbein, Oberschenkel und Beinöffnung.", "Kläre, ob der Bund flach, als Umfang oder als Dehnungsbereich angegeben wird.", "Ordne die Maße dem genauen Schnitt und der gewählten Option zu."],
      accessories: ["Notiere echte Länge, Breite und Tiefe statt die Größe vom Foto zu schätzen.", "Prüfe Verschlüsse, Kanten, Scharniere und andere bewegliche Teile.", "Bestätige Material, enthaltene Teile und Maße im aktuellen Angebot."],
      electronics: ["Gleiche vollständige Modellnummer und Revision ab.", "Prüfe Spannung, Stecker, Anschlüsse und regionale Kompatibilität.", "Bestätige Zubehör, Garantie und Bedingungen für eingeschränkte Artikel."],
    },
    guideChecks: {
      "what-is-a-hacoo-spreadsheet": ["Unterscheide einen redaktionellen Index von einem Shop oder offiziellen Dienst.", "Prüfe, ob jeder Link zu einer aktuellen, passenden Seite führt.", "Verstehe die Aufnahme nicht als Qualitäts- oder Verfügbarkeitsgarantie."],
      "how-to-use-hacoo-spreadsheet": ["Beginne mit einer klaren Kategorie statt mit einer endlosen Liste.", "Vergleiche bei allen Kandidaten dieselben Maße und Varianten.", "Beende den Ablauf im aktuellen Angebot und prüfe dessen Bedingungen erneut."],
      "hacoo-reviews-explained": ["Trenne Bewertungen zu App, Bestellung, Produkt und Versand.", "Prüfe Datum, Land, Variante und Belege, bevor du einen Bericht nutzt.", "Vergleiche Bewertungsthemen mit der aktuellen offiziellen Richtlinie."],
      "qc-photo-checklist": ["Suche vergleichbare Vorder-, Rück-, Seiten- und Detailansichten.", "Ordne alle Fotos derselben Größe, Farbe und Variante zu.", "Bitte um Klarheit, wenn ein Maß oder wichtiger Bereich nicht sichtbar ist."],
      "size-guide": ["Miss ein eigenes Kleidungsstück mit derselben Methode wie die Tabelle.", "Vergleiche Kleidungsmaße, nicht nur Größenbuchstaben.", "Plane Spielraum für Schnitt, Schichten und angegebene Toleranz ein."],
      "shipping-planning": ["Notiere Gewicht und Maße, wenn das Ziel sie veröffentlicht.", "Prüfe Einschränkungen, Steuern und Methoden für dein Land.", "Nutze das aktuelle Angebot; mache aus einer alten Schätzung kein Versprechen."],
      "hacoo-returns-refunds": ["Prüfe Berechtigung und Frist, bevor du eine Rückgabe vorbereitest.", "Bewahre Fotos von Paket, Variante und genauem Problem auf.", "Nutze Refund/Exchange in der Bestellung und dokumentiere den gesamten Verlauf."],
    },
  },
  it: {
    category: {
      label: "Scheda di confronto",
      title: "Conserva prove utili prima di scegliere.",
      intro: (name) => `Per confrontare ${name.toLowerCase()} in modo responsabile, annota l’opzione esatta, usa lo stesso metodo di misurazione e associa ogni foto alla variante selezionata. Questi controlli riducono gli errori senza sostituire l’inserzione attuale.`,
      reviewed: "Percorso di categoria verificato il 26 agosto 2026. Disponibilità, opzioni e condizioni esterne possono cambiare.",
      productLabel: "Prodotto attuale", productTitle: "Un’inserzione reale, verificata direttamente.", openListing: "Apri inserzione verificata", fallback: "Ricerca alternativa",
      tableLabel: "Tabella taglia e QC", tableTitle: "Registra prove, non impressioni.", tableHeaders: ["Controllo", "Cosa annotare", "Prova utile"], tableRecord: "Annota il valore o l’opzione esatta.", tableEvidence: "Foto, tabella o testo dell’inserzione attuale.",
      faqTitle: "Domande di verifica", updateLabel: "Registro aggiornamenti", updateTitle: "Prodotto e guida aggiornati", updateText: "L’inserzione è stata verificata, è stata aggiunta una ricerca alternativa e la tabella taglia/QC è stata aggiornata.", disclosure: "L’inclusione non conferma disponibilità, qualità, autenticità o idoneità. Verifica l’opzione attuale.",
    },
    guide: {
      label: "Controllo pratico",
      title: "Trasforma la lettura in una verifica ripetibile.",
      intro: "Usa questi punti come breve registro. Se manca un dato o due fonti non coincidono, interrompi il confronto e conferma l’informazione sulla pagina attuale.",
    },
    indexes: {
      categoriesTitle: "Come usare l’elenco",
      categoriesText: "Scegli prima il tipo di prodotto. Applica poi la checklist specifica e apri la destinazione solo per confermare i dati attuali.",
      guidesTitle: "Leggi in base alla decisione da prendere",
      guidesText: "La guida all’uso spiega il percorso completo; taglie, foto QC e spedizione risolvono controlli specifici. L’inserzione attuale resta il riferimento finale.",
    },
    about: {
      title: "Come verifichiamo un percorso",
      intro: "Ogni percorso è separato in tre livelli, così i consigli editoriali non vengono confusi con i dati variabili di un’inserzione esterna.",
      steps: [["Contesto", "Spieghiamo quali informazioni servono per confrontare quel tipo di prodotto."], ["Verifica", "Controlliamo che la destinazione si apra e corrisponda alla categoria indicata."], ["Limite", "Segnaliamo quali dati devono essere confermati di nuovo prima di decidere."]],
    },
    faqExtra: [["Quando vengono verificati i link?", "I percorsi sono controllati periodicamente e mostrano una data di revisione quando utile. Un link valido non garantisce che ogni opzione resti disponibile."], ["Cosa faccio se mancano misure o foto?", "Non colmare i vuoti con supposizioni. Scegli un’altra opzione con dati confrontabili oppure attendi informazioni sufficienti dalla destinazione."]],
    categoryChecks: {
      shoes: ["Confronta lunghezza del piede e lunghezza interna, non solo la taglia stampata.", "Controlla punta, tallone, suola e due lati da angolazioni comparabili.", "Conferma colore, taglia, disponibilità e possibile volume della scatola nell’inserzione attuale."],
      headwear: ["Confronta la circonferenza della testa con l’intervallo di regolazione.", "Controlla profondità della corona, tipo di chiusura e forma della visiera.", "Verifica cuciture e ricamo sul colore esatto selezionato."],
      "hoodies-sweaters": ["Confronta petto, spalle, maniche e lunghezza con un capo che possiedi.", "Conferma composizione, peso del tessuto e finitura interna quando indicati.", "Associa polsini, fondo e grafiche alla taglia e al colore scelti."],
      "t-shirts": ["Misura spalle, petto e lunghezza con il capo steso in piano.", "Controlla composizione, grammatura disponibile e costruzione del collo.", "Verifica posizione e finitura della stampa sull’opzione esatta."],
      jackets: ["Usa come riferimento una giacca che lasci spazio agli strati abituali.", "Controlla cerniere, tasche, fodera e giunzioni delle cuciture.", "Conferma taglia, peso e volume imballato prima di pianificare la spedizione."],
      "pants-shorts": ["Confronta vita, cavallo, interno gamba, coscia e fondo.", "Chiarisci se la vita è indicata in piano, come circonferenza o intervallo elastico.", "Associa le misure al taglio e all’opzione esatti."],
      accessories: ["Annota lunghezza, larghezza e profondità reali invece di stimarle dalla foto.", "Controlla chiusure, bordi, cerniere e altre parti mobili.", "Conferma materiale, parti incluse e dimensioni nell’inserzione attuale."],
      electronics: ["Fai corrispondere numero di modello e revisione completi.", "Controlla tensione, spina, connettori e compatibilità regionale.", "Conferma accessori inclusi, garanzia e condizioni per gli articoli soggetti a restrizioni."],
    },
    guideChecks: {
      "what-is-a-hacoo-spreadsheet": ["Distingui un indice editoriale da un negozio o servizio ufficiale.", "Verifica che ogni link porti a una pagina attuale e pertinente.", "Non considerare l’inclusione come garanzia di qualità o disponibilità."],
      "how-to-use-hacoo-spreadsheet": ["Inizia da una categoria precisa, non da una lista infinita.", "Confronta le stesse misure e opzioni per tutti i candidati.", "Termina sull’inserzione attuale e ricontrolla le sue condizioni."],
      "hacoo-reviews-explained": ["Separa recensioni su app, ordine, prodotto e trasporto.", "Verifica data, paese, variante e prove prima di usare un’esperienza.", "Confronta i temi delle recensioni con la politica ufficiale attuale."],
      "qc-photo-checklist": ["Cerca viste frontali, posteriori, laterali e di dettaglio comparabili.", "Associa tutte le foto alla stessa taglia, colore e variante.", "Chiedi chiarezza quando una misura o un’area importante non è visibile."],
      "size-guide": ["Misura un capo che possiedi con lo stesso metodo della tabella.", "Confronta le misure del capo, non solo le lettere della taglia.", "Lascia margine in base a vestibilità, strati e tolleranza indicata."],
      "shipping-planning": ["Registra peso e dimensioni quando la destinazione li pubblica.", "Controlla restrizioni, imposte e metodi per il tuo paese.", "Usa il preventivo attuale; non trasformare una vecchia stima in promessa."],
      "hacoo-returns-refunds": ["Verifica idoneità e scadenza prima di preparare un reso.", "Conserva foto del pacco, della variante e del problema preciso.", "Usa Refund/Exchange nell’ordine e conserva la cronologia del caso."],
    },
  },
  pt: {
    category: {
      label: "Registo de comparação",
      title: "Guarde provas úteis antes de escolher.",
      intro: (name) => `Para comparar ${name.toLowerCase()} com responsabilidade, anote a opção exata, use o mesmo método de medição e associe cada fotografia à variante selecionada. Estas verificações reduzem erros sem substituir o anúncio atual.`,
      reviewed: "Rota de categoria verificada em 26 de agosto de 2026. Disponibilidade, opções e condições externas podem mudar.",
      productLabel: "Produto atual", productTitle: "Um anúncio real, verificado diretamente.", openListing: "Abrir anúncio verificado", fallback: "Pesquisa alternativa",
      tableLabel: "Tabela de tamanho e QC", tableTitle: "Registe provas, não impressões.", tableHeaders: ["Verificação", "O que registar", "Prova útil"], tableRecord: "Registe o valor ou a opção exata.", tableEvidence: "Fotografia, tabela ou texto do anúncio atual.",
      faqTitle: "Perguntas de verificação", updateLabel: "Registo de atualizações", updateTitle: "Produto e guia atualizados", updateText: "O anúncio foi verificado, foi adicionada uma pesquisa alternativa e a tabela de tamanho/QC foi atualizada.", disclosure: "A inclusão não confirma stock, qualidade, autenticidade ou adequação. Verifique a opção atual.",
    },
    guide: {
      label: "Verificação prática",
      title: "Transforme a leitura numa revisão repetível.",
      intro: "Use estes pontos como um registo curto. Se faltar um dado ou duas fontes não coincidirem, pare a comparação e confirme a informação na página atual.",
    },
    indexes: {
      categoriesTitle: "Como usar o diretório",
      categoriesText: "Escolha primeiro o tipo de produto. Depois aplique a checklist específica e abra o destino apenas para confirmar dados atuais.",
      guidesTitle: "Leia conforme a decisão que precisa de tomar",
      guidesText: "O guia de utilização explica o processo completo; tamanhos, fotografias QC e envio resolvem verificações específicas. O anúncio atual continua a ser a referência final.",
    },
    about: {
      title: "Como verificamos uma rota",
      intro: "Cada rota é separada em três camadas para que a orientação editorial não seja confundida com dados variáveis de um anúncio externo.",
      steps: [["Contexto", "Explicamos quais informações ajudam a comparar esse tipo de produto."], ["Verificação", "Confirmamos que o destino abre e corresponde à categoria indicada."], ["Limite", "Assinalamos os dados que devem ser confirmados novamente antes de decidir."]],
    },
    faqExtra: [["Quando são verificados os links?", "As rotas são verificadas periodicamente e mostram uma data de revisão quando útil. Um link válido não garante que todas as opções continuem disponíveis."], ["O que faço se faltarem medidas ou fotografias?", "Não preencha lacunas com suposições. Escolha outra opção com dados comparáveis ou espere por informação suficiente no destino."]],
    categoryChecks: {
      shoes: ["Compare o comprimento do pé e o comprimento interno, não apenas o tamanho impresso.", "Verifique biqueira, calcanhar, sola e ambos os lados em ângulos comparáveis.", "Confirme cor, tamanho, stock e possível volume da caixa no anúncio atual."],
      headwear: ["Compare a circunferência da cabeça com o intervalo de ajuste indicado.", "Verifique profundidade da copa, tipo de fecho e formato da pala.", "Confirme costuras e bordado na cor exata selecionada."],
      "hoodies-sweaters": ["Compare peito, ombros, mangas e comprimento com uma peça que possui.", "Confirme composição, peso do tecido e acabamento interior quando indicados.", "Associe punhos, bainha e gráficos ao tamanho e à cor escolhidos."],
      "t-shirts": ["Meça ombros, peito e comprimento com a peça colocada em plano.", "Verifique composição, gramagem disponível e construção da gola.", "Confirme posição e acabamento da impressão na opção exata."],
      jackets: ["Use como referência um casaco com espaço para as camadas habituais.", "Verifique fechos, bolsos, forro e uniões das costuras.", "Confirme tamanho, peso e volume embalado antes de planear o envio."],
      "pants-shorts": ["Compare cintura, gancho, entreperna, coxa e abertura da perna.", "Confirme se a cintura é medida em plano, como contorno ou intervalo elástico.", "Associe as medidas ao corte e à opção exatos."],
      accessories: ["Anote comprimento, largura e profundidade reais em vez de estimar pela fotografia.", "Verifique fechos, bordas, dobradiças e outras peças móveis.", "Confirme material, peças incluídas e dimensões no anúncio atual."],
      electronics: ["Compare o número de modelo e a revisão completos.", "Verifique tensão, ficha, conectores e compatibilidade regional.", "Confirme acessórios incluídos, garantia e condições para artigos restritos."],
    },
    guideChecks: {
      "what-is-a-hacoo-spreadsheet": ["Distinga um índice editorial de uma loja ou serviço oficial.", "Confirme que cada link leva a uma página atual e relevante.", "Não interprete a inclusão como garantia de qualidade ou disponibilidade."],
      "how-to-use-hacoo-spreadsheet": ["Comece por uma categoria específica, não por uma lista interminável.", "Compare as mesmas medidas e opções entre todos os candidatos.", "Termine no anúncio atual e volte a verificar as condições."],
      "hacoo-reviews-explained": ["Separe avaliações da aplicação, encomenda, produto e transporte.", "Confirme data, país, variante e provas antes de usar uma experiência.", "Compare os temas das avaliações com a política oficial atual."],
      "qc-photo-checklist": ["Procure vistas frontal, traseira, lateral e de detalhe comparáveis.", "Associe todas as fotografias ao mesmo tamanho, cor e variante.", "Peça clareza quando uma medida ou área importante não estiver visível."],
      "size-guide": ["Meça uma peça que possui com o mesmo método da tabela.", "Compare medidas da peça, não apenas letras de tamanho.", "Deixe margem conforme o corte, as camadas e a tolerância indicada."],
      "shipping-planning": ["Registe peso e dimensões quando o destino os publicar.", "Verifique restrições, impostos e métodos para o seu país.", "Use a cotação atual; não transforme uma estimativa antiga numa promessa."],
      "hacoo-returns-refunds": ["Confirme elegibilidade e prazo antes de preparar uma devolução.", "Guarde fotografias do pacote, da variante e do problema exato.", "Use Refund/Exchange na encomenda e conserve a cronologia do caso."],
    },
  },
};

export function getLocalizedDepth(locale) {
  return localizedDepth[locale] || localizedDepth.es;
}
