const shared = {
  en: {
    kicker: "Hacoo outfit planning / inspiration-to-wear workflow",
    dateLabel: "Published and reviewed August 29, 2026",
    intro: "Hacoo outfit planning works best when an inspiring image is treated as a starting hypothesis, not a ready-made shopping list. Hacoo describes its platform as a lifestyle discovery community where independent creators share content and ideas. A post can reveal a proportion, colour relationship or layering idea, but it cannot prove that the same pieces suit your routine, measurements, climate or existing wardrobe. This guide converts one inspiration reference into a wearable outfit plan with named roles, practical constraints and a clear decision to use, adapt or archive the idea.",
    factBox: [["Primary decision", "Can this inspiration become an outfit for a real occasion using mostly what you own?"], ["Planning limit", "One reference, one use case, three existing anchors and at most one wardrobe candidate"], ["Evidence date", "Hacoo public platform descriptions checked August 29, 2026"]],
    sections: [
      ["Describe the outfit idea without naming products", ["Start with the visual relationship that attracted you. Write ‘short dark jacket over a longer pale layer with straight trousers and low-profile shoes’ rather than copying creator captions, labels or trend names. This removes brand excitement and exposes the actual styling mechanism: length contrast, colour balance, volume, texture or formality. If you cannot describe the relationship, the image may be interesting without offering a useful outfit idea.", "Separate visible observation from inference. You can observe a cropped jacket, but not its fabric composition, warmth, weight or exact fit. You can see a shoe shape, but not comfort over a full day. Record unknown points instead of filling them from appearance. The plan should work even if the exact creator item is unavailable, because the goal is a wearable relationship rather than a replica of the post."]],
      ["Name the occasion and operating conditions", ["Assign the outfit one real job: a two-hour campus day, a casual office, a weekend walk, dinner reached by public transport or a travel day with changing temperatures. Add duration, movement, indoor and outdoor time, weather exposure, expected carrying needs and dress-code limits. ‘Autumn outfit’ is too broad; ‘eight-hour casual workday with a cold commute and warm office’ creates useful decisions.", "Translate conditions into pass-or-fail requirements. A work outfit may require a closed shoe, non-sheer top and layer that fits on a chair. A walking outfit needs movement and a bag that stays secure. A travel outfit needs repeatable combinations and manageable care. If the inspiration depends on a piece that conflicts with the occasion, adapt the role rather than forcing the exact item."]],
      ["Break the look into wardrobe roles", ["List roles before categories: base, main silhouette, temperature layer, footwear, carry piece and optional accent. One item can fill two roles. A cardigan can create the main line and provide warmth; a structured tote can carry essentials and increase formality. Roles reveal whether the image contains five necessary functions or merely five visible products.", "Mark each role as essential, flexible or decorative. Essential roles protect comfort, coverage or the dress code. Flexible roles can be filled by several items you own. Decorative roles should be the first to disappear when they create cost or complexity. This prevents an accessory seen in the post from becoming an automatic purchase."]],
      ["Test three existing wardrobe anchors", ["Choose three pieces you already wear frequently that can occupy the major roles. Photograph them together or place them on a neutral surface. Compare colour temperature, contrast, volume and length. Then try the combination on the body or in a mirror. Flat-lay harmony is not enough: a jacket hem can interrupt a trouser rise, and two relaxed shapes can create more volume than the reference suggests.", "Use a substitution ladder. First try the closest existing item, then a piece with the same function but different detail, then a deliberate adaptation. A navy overshirt may replace a black cropped jacket if it creates enough contrast and handles the weather. Record which visual principle survives. If the idea works with existing anchors, you may not have a wardrobe gap at all."]],
      ["Set proportion, colour and movement constraints", ["Write measurable or testable constraints. For proportion, note where the upper layer should end relative to the waist or hip, the intended trouser line and how much footwear is visible. For colour, select one dominant neutral, one supporting tone and an optional accent already present in your wardrobe. Product photographs are not calibrated colour evidence, so treat a shade name and image as approximate until the current option can be checked.", "Movement changes the outfit. Sit, raise the arms, walk stairs, carry the intended bag and add the actual coat if needed. Note pulling, exposed areas, slipping straps, pocket access and whether layers bunch. A creator post freezes one angle; a wearable plan must survive the sequence of actions in the named occasion."]],
      ["Decide whether one new candidate is justified", ["Only after testing existing anchors should you define a missing candidate. Write the gap as a role plus constraints: ‘mid-thigh water-resistant layer, room for a medium knit, two secure pockets, compatible with navy and grey.’ Do not begin with a product title. Search terms and Hacoo finds should be evaluated against this sentence, not allowed to rewrite it.", "Keep no more than three candidates for the missing role. Record the exact option, relevant measurements, material statements, closure, care, interaction with anchors and the most important unknown. A creator claim belongs in a dated source note, not in the confirmed-fact column. A missing decisive field can be a reason to pause rather than an invitation to assume."]],
      ["Run the three-outfit and friction tests", ["A justified candidate should complete at least three outfits built from real anchors: the target inspiration, a simpler everyday version and an alternative for changed weather or formality. Score each as ready, workable with an existing adjustment, or poor. If the candidate succeeds only in the copied look, it is closer to a costume component than a wardrobe solution.", "List friction separately: special underwear, uncomfortable socks, dry cleaning, constant adjustment, a bag that conflicts with the layer, or another purchase needed to complete the look. Do not hide friction inside an overall score. One hard operational conflict can outweigh several attractive details."]],
      ["Use, adapt or archive the inspiration", ["Choose ‘use’ when the plan works largely with what you own and the remaining evidence is sufficient. Choose ‘adapt’ when the useful principle survives but a colour, layer, shoe or silhouette must change. Choose ‘archive’ when the occasion is imaginary, hard constraints fail, the plan triggers multiple purchases or the idea no longer feels useful after a normal outfit cycle.", "Save the decision, not a fake review. Record the reference date, the styling principle, anchors tested, movement result, unresolved question and outcome. If a candidate later arrives, compare the delivered item with this original brief rather than rewriting the brief to defend the purchase. A good outfit-planning journal makes future decisions easier even when the final answer is not to buy."]],
    ],
    matrix: { title: "Inspiration-to-outfit decision matrix", headers: ["Field", "Reference idea", "Existing-wardrobe test", "Decision"], rows: [["Real occasion", "Name place, duration and movement", "Already occurs / hypothetical", "Continue / archive"], ["Core principle", "Colour, line, layer or proportion", "Survives substitution?", "Use / adapt"], ["Three anchors", "Roles needed", "Direct / adjusted / poor", "Keep / revise"], ["Missing role", "One constrained candidate", "Three outfits supported?", "Compare / pause"], ["Friction", "Care, comfort, extra purchase", "Low / manageable / high", "Use / adapt / archive"]] },
    faqs: [["Must I buy the exact items shown in a Hacoo creator post?", "No. Extract the outfit relationship, then test it with existing pieces before defining any gap."], ["How many new items should one inspiration create?", "Set a working limit of one candidate. If several roles are missing, archive the idea or adapt it more aggressively."], ["Can a product photo confirm the colour match?", "No. Lighting, editing and screens affect appearance. Use the image as context and keep colour uncertainty visible."], ["What if the outfit only works while standing still?", "It fails the named use case. Test sitting, walking, carrying and the intended outer layer."], ["Is archiving an idea a failed plan?", "No. It is a useful decision when the occasion, anchors or constraints do not support the look."]],
    steps: ["Describe the styling principle", "Name one real occasion", "Assign wardrobe roles", "Test three existing anchors", "Compare at most one missing-role shortlist", "Choose use, adapt or archive"],
    sourceNote: "Hacoo Terms of Service and Trust Center reviewed August 29, 2026 for the platform's lifestyle-discovery role, independent creator responsibility and evidence limits. The outfit method is independent editorial analysis, not an official Hacoo workflow or a product guarantee.",
  },
};

const translations = {
  es: { kicker:"Planificación de outfits Hacoo / de inspiración a uso real", dateLabel:"Publicado y revisado el 29 de agosto de 2026", intro:"La planificación de outfits Hacoo funciona cuando una imagen inspiradora es una hipótesis, no una lista de compra. Hacoo se presenta como comunidad de descubrimiento lifestyle con contenido de creadores independientes. Una publicación puede mostrar proporción, color o capas, pero no demuestra que las mismas prendas sirvan para tu rutina, medidas, clima o armario. Este método convierte una referencia en un plan ponible con funciones, límites y una decisión de usar, adaptar o archivar.", headings:["Describe la idea sin nombrar productos","Nombra ocasión y condiciones","Divide el look en funciones","Prueba tres prendas ancla","Fija límites de proporción, color y movimiento","Decide si se justifica un candidato","Aplica pruebas de tres outfits y fricción","Usa, adapta o archiva"], faqTitle:"Preguntas de planificación" },
  fr: { kicker:"Planification de tenue Hacoo / de l'inspiration à l'usage", dateLabel:"Publié et vérifié le 29 août 2026", intro:"La planification de tenue Hacoo devient utile lorsqu'une image est une hypothèse et non une liste d'achats. Hacoo se présente comme une communauté de découverte lifestyle alimentée par des créateurs indépendants. Un post montre proportions, couleurs ou superpositions, mais ne prouve pas l'adéquation à votre routine, vos mesures, votre climat ou votre garde-robe. Cette méthode transforme une référence en plan portable avec rôles, contraintes et décision d'utiliser, adapter ou archiver.", headings:["Décrire l'idée sans nommer de produits","Nommer l'occasion et les conditions","Décomposer la tenue en rôles","Tester trois pièces repères","Fixer proportions, couleurs et mouvement","Justifier au plus un candidat","Tester trois tenues et les frictions","Utiliser, adapter ou archiver"], faqTitle:"Questions de planification" },
  de: { kicker:"Hacoo-Outfitplanung / von Inspiration zu Nutzung", dateLabel:"Veröffentlicht und geprüft am 29. August 2026", intro:"Hacoo-Outfitplanung hilft, wenn ein Inspirationsbild als Hypothese statt Einkaufsliste dient. Hacoo beschreibt sich als Lifestyle-Entdeckungscommunity mit Inhalten unabhängiger Creator. Ein Post kann Proportion, Farbbezug oder Schichtung zeigen, beweist aber nicht die Eignung für Alltag, Maße, Klima oder vorhandene Garderobe. Diese Methode macht aus einer Referenz einen tragbaren Plan mit Rollen, Grenzen und der Entscheidung Nutzen, Anpassen oder Archivieren.", headings:["Idee ohne Produktnamen beschreiben","Anlass und Bedingungen nennen","Look in Garderobenrollen zerlegen","Drei vorhandene Anker testen","Proportion, Farbe und Bewegung begrenzen","Einen neuen Kandidaten begründen","Drei Outfits und Reibung testen","Nutzen, anpassen oder archivieren"], faqTitle:"Fragen zur Outfitplanung" },
  it: { kicker:"Pianificazione outfit Hacoo / dall'ispirazione all'uso", dateLabel:"Pubblicato e verificato il 29 agosto 2026", intro:"La pianificazione outfit Hacoo è utile quando un'immagine è un'ipotesi e non una lista acquisti. Hacoo si descrive come comunità di scoperta lifestyle con contenuti di creator indipendenti. Un post può mostrare proporzioni, colori o strati, ma non prova l'idoneità alla tua routine, misure, clima o guardaroba. Il metodo trasforma una referenza in un piano indossabile con ruoli, vincoli e decisione di usare, adattare o archiviare.", headings:["Descrivi l'idea senza prodotti","Definisci occasione e condizioni","Dividi il look in ruoli","Prova tre capi ancora","Fissa proporzioni, colore e movimento","Giustifica un solo candidato","Testa tre outfit e attrito","Usa, adatta o archivia"], faqTitle:"Domande di pianificazione" },
  pt: { kicker:"Planeamento de conjuntos Hacoo / da inspiração ao uso", dateLabel:"Publicado e revisto em 29 de agosto de 2026", intro:"O planeamento de conjuntos Hacoo funciona quando uma imagem é uma hipótese e não uma lista de compras. A Hacoo apresenta-se como comunidade de descoberta lifestyle com criadores independentes. Uma publicação mostra proporção, cor ou camadas, mas não prova adequação à rotina, medidas, clima ou guarda-roupa. Este método transforma uma referência num plano utilizável com funções, limites e decisão de usar, adaptar ou arquivar.", headings:["Descreva a ideia sem produtos","Defina ocasião e condições","Divida o visual em funções","Teste três peças âncora","Fixe proporção, cor e movimento","Justifique um candidato","Teste três conjuntos e atrito","Use, adapte ou arquive"], faqTitle:"Perguntas de planeamento" },
};

const translatedBody = {
  es:["Escribe la relación visible: chaqueta corta sobre capa larga, pantalón recto y calzado bajo. Separa observación de inferencia: la foto no confirma tejido, abrigo, comodidad ni ajuste.","Asigna un trabajo real con duración, movimiento, interior, exterior, clima, carga y código. Convierte esas condiciones en requisitos de aprobado o fallo.","Enumera base, silueta, capa térmica, calzado, bolso y acento. Marca cada función como esencial, flexible o decorativa; elimina primero lo decorativo.","Prueba tres prendas que ya usas y una escalera de sustitución. Observa el cuerpo, no solo un flat lay: dobladillos, volumen, tiro y capas cambian la proporción.","Anota largos, volumen, paleta y acciones: sentarse, caminar, subir escaleras, llevar bolso y abrigo. Una pose fija no demuestra movimiento.","Solo después define una función ausente con medidas, material, cierre y compatibilidad. Mantén tres candidatos y deja visibles los datos no indicados.","El candidato debe completar el look objetivo, una versión diaria y otra para clima o formalidad distinta. Separa cuidado, comodidad y compras adicionales del atractivo visual.","Usa si funciona; adapta si sobrevive el principio con cambios; archiva si la ocasión es imaginaria, fallan límites o exige varias compras. Guarda la decisión, no una reseña falsa."],
  fr:["Décrivez la relation visible sans marques. Séparez observation et déduction : la photo ne confirme ni matière, chaleur, confort ni coupe exacte.","Attribuez un usage réel avec durée, mouvement, intérieur, extérieur, météo, portage et code vestimentaire. Transformez-les en critères éliminatoires.","Listez base, ligne principale, couche thermique, chaussures, sac et accent. Classez chaque rôle essentiel, flexible ou décoratif.","Testez trois pièces souvent portées et une échelle de substitution. Observez sur le corps : ourlets, volume, taille et couches changent la proportion.","Notez longueurs, volumes, palette et actions : s'asseoir, marcher, monter, porter le sac et le manteau. Une pose ne prouve pas le mouvement.","Définissez seulement ensuite le rôle manquant avec mesures, matière, fermeture et compatibilité. Gardez trois candidats et les champs absents visibles.","Le candidat doit servir la tenue cible, une version quotidienne et une variante météo ou formelle. Isolez entretien, confort et achats annexes.","Utilisez si le plan fonctionne, adaptez si le principe survit, archivez si l'occasion est fictive ou si plusieurs achats sont nécessaires. Conservez la décision, pas un faux avis."],
  de:["Beschreibe die sichtbare Beziehung ohne Marken. Trenne Beobachtung von Schlussfolgerung: Fotos bestätigen Material, Wärme, Komfort oder genaue Passform nicht.","Gib dem Outfit einen echten Zweck mit Dauer, Bewegung, Innen- und Außenzeit, Wetter, Tragebedarf und Dresscode. Daraus entstehen Ausschlusskriterien.","Liste Basis, Hauptlinie, Wärmeschicht, Schuhe, Tasche und Akzent. Kennzeichne jede Rolle als wesentlich, flexibel oder dekorativ.","Teste drei oft getragene Teile und eine Ersatzleiter. Prüfe am Körper: Säume, Volumen, Bund und Schichten verändern Proportionen.","Notiere Längen, Volumen, Palette und Bewegungen: sitzen, gehen, Treppen, Tasche und Mantel. Eine Pose beweist keine Alltagstauglichkeit.","Definiere erst dann eine fehlende Rolle mit Maßen, Material, Verschluss und Ankerbezug. Halte drei Kandidaten und fehlende Angaben sichtbar.","Der Kandidat muss Ziellook, Alltagsversion und Wetter- oder Formalitätsvariante tragen. Pflege, Komfort und Zusatzkäufe bleiben eigene Reibungsfelder.","Nutzen bei tragfähigem Plan, anpassen bei übertragbarem Prinzip, archivieren bei erfundenem Anlass oder mehreren nötigen Käufen. Speichere die Entscheidung statt einer Scheinbewertung."],
  it:["Descrivi la relazione visibile senza marchi. Separa osservazione e deduzione: la foto non conferma tessuto, calore, comfort o vestibilità esatta.","Assegna un uso reale con durata, movimento, interno, esterno, meteo, trasporto e dress code. Trasformali in requisiti eliminatori.","Elenca base, linea principale, strato termico, scarpe, borsa e accento. Segna ogni ruolo come essenziale, flessibile o decorativo.","Prova tre capi frequenti e una scala di sostituzione. Guarda sul corpo: orli, volume, vita e strati cambiano proporzioni.","Annota lunghezze, volume, palette e azioni: sedersi, camminare, scale, borsa e cappotto. Una posa non prova il movimento.","Solo dopo definisci il ruolo mancante con misure, materiale, chiusura e compatibilità. Mantieni tre candidati e i dati assenti visibili.","Il candidato deve completare look obiettivo, versione quotidiana e variante meteo o formale. Cura, comfort e acquisti extra restano attriti separati.","Usa se funziona, adatta se sopravvive il principio, archivia se l'occasione è immaginaria o servono più acquisti. Salva la decisione, non una falsa recensione."],
  pt:["Descreva a relação visível sem marcas. Separe observação de inferência: a foto não confirma tecido, calor, conforto ou ajuste exato.","Atribua um uso real com duração, movimento, interior, exterior, clima, carga e código. Transforme essas condições em critérios eliminatórios.","Liste base, linha principal, camada térmica, calçado, mala e detalhe. Marque cada função como essencial, flexível ou decorativa.","Teste três peças frequentes e uma escada de substituição. Observe no corpo: bainhas, volume, cintura e camadas mudam proporções.","Registe comprimentos, volume, paleta e ações: sentar, caminhar, subir, usar mala e casaco. Uma pose não prova movimento.","Só depois defina a função em falta com medidas, material, fecho e compatibilidade. Mantenha três candidatos e campos ausentes visíveis.","O candidato deve servir o visual alvo, versão diária e alternativa climática ou formal. Cuidados, conforto e compras extra ficam separados.","Use se funcionar, adapte se o princípio sobreviver, arquive se a ocasião é imaginária ou exige várias compras. Guarde a decisão, não uma avaliação falsa."],
};

const localExtras = {
  es:{ add:"Registra el resultado con fecha y mantén las incertidumbres separadas de los hechos observables.", matrix:{title:"Matriz de inspiración a outfit",headers:["Campo","Idea","Prueba del armario","Decisión"],rows:[["Ocasión","Lugar, duración y movimiento","Real / hipotética","Seguir / archivar"],["Principio","Color, línea, capa o proporción","¿Sobrevive a sustituciones?","Usar / adaptar"],["Tres anclas","Funciones necesarias","Directa / ajustada / mala","Mantener / revisar"],["Fricción","Cuidado, comodidad, compra extra","Baja / media / alta","Usar / archivar"]]},faqs:[["¿Debo comprar exactamente lo mostrado?","No. Extrae la relación y pruébala con lo que posees."],["¿Cuántas compras debe crear una imagen?","Limita el plan a un candidato; si faltan varias funciones, adapta o archiva."],["¿La foto confirma el color?","No. Luz, edición y pantalla limitan la evidencia."],["¿Y si solo funciona de pie?","Falla el uso: prueba asiento, caminar, bolso y abrigo."],["¿Archivar es fracasar?","No; es una decisión útil cuando no encajan ocasión o límites."]],steps:["Describe el principio","Nombra una ocasión","Asigna funciones","Prueba tres anclas","Compara un rol ausente","Usa, adapta o archiva"]},
  fr:{ add:"Consignez le résultat avec une date et séparez les inconnues des faits observables.", matrix:{title:"Matrice inspiration-tenue",headers:["Champ","Idée","Test garde-robe","Décision"],rows:[["Occasion","Lieu, durée, mouvement","Réelle / fictive","Continuer / archiver"],["Principe","Couleur, ligne, couche, proportion","Résiste aux substitutions ?","Utiliser / adapter"],["Trois repères","Rôles requis","Direct / ajusté / faible","Garder / revoir"],["Friction","Entretien, confort, achat","Faible / moyen / fort","Utiliser / archiver"]]},faqs:[["Faut-il acheter les pièces exactes ?","Non. Extrayez la relation et testez-la avec vos vêtements."],["Combien d'achats pour une image ?","Limitez à un candidat ; sinon adaptez ou archivez."],["La photo confirme-t-elle la couleur ?","Non. Lumière, retouche et écran limitent la preuve."],["Et si cela ne marche que debout ?","Le cas d'usage échoue : testez assise, marche, sac et manteau."],["Archiver est-il un échec ?","Non, c'est une décision utile lorsque les contraintes échouent."]],steps:["Décrire le principe","Nommer une occasion","Attribuer les rôles","Tester trois repères","Comparer un rôle manquant","Utiliser, adapter ou archiver"]},
  de:{ add:"Halte das Ergebnis datiert fest und trenne Unbekanntes von beobachtbaren Fakten.", matrix:{title:"Inspirations-zu-Outfit-Matrix",headers:["Feld","Idee","Garderobentest","Entscheidung"],rows:[["Anlass","Ort, Dauer, Bewegung","Real / erfunden","Weiter / archivieren"],["Prinzip","Farbe, Linie, Schicht, Proportion","Überlebt Ersatz?","Nutzen / anpassen"],["Drei Anker","Nötige Rollen","Direkt / angepasst / schwach","Behalten / prüfen"],["Reibung","Pflege, Komfort, Zusatzkauf","Niedrig / mittel / hoch","Nutzen / archivieren"]]},faqs:[["Muss ich die genauen Teile kaufen?","Nein. Extrahiere die Beziehung und teste eigene Kleidung."],["Wie viele Käufe soll ein Bild auslösen?","Begrenze auf einen Kandidaten; sonst anpassen oder archivieren."],["Bestätigt das Foto die Farbe?","Nein. Licht, Bearbeitung und Bildschirm begrenzen den Beweis."],["Was, wenn es nur im Stehen klappt?","Dann scheitert der Zweck; teste Sitzen, Gehen, Tasche und Mantel."],["Ist Archivieren ein Fehlschlag?","Nein, wenn Anlass oder Grenzen nicht tragen, ist es eine gute Entscheidung."]],steps:["Prinzip beschreiben","Anlass nennen","Rollen vergeben","Drei Anker testen","Fehlende Rolle vergleichen","Nutzen, anpassen oder archivieren"]},
  it:{ add:"Registra il risultato con data e separa le incognite dai fatti osservabili.", matrix:{title:"Matrice ispirazione-outfit",headers:["Campo","Idea","Test guardaroba","Decisione"],rows:[["Occasione","Luogo, durata, movimento","Reale / ipotetica","Continua / archivia"],["Principio","Colore, linea, strato, proporzione","Resiste alle sostituzioni?","Usa / adatta"],["Tre ancore","Ruoli necessari","Diretto / adattato / scarso","Tieni / rivedi"],["Attrito","Cura, comfort, acquisto","Basso / medio / alto","Usa / archivia"]]},faqs:[["Devo comprare i capi esatti?","No. Estrai la relazione e provala con ciò che possiedi."],["Quanti acquisti deve creare un'immagine?","Limita a un candidato; altrimenti adatta o archivia."],["La foto conferma il colore?","No. Luce, editing e schermo limitano la prova."],["E se funziona solo in piedi?","Fallisce l'uso: prova seduta, cammino, borsa e cappotto."],["Archiviare è fallire?","No, è utile quando occasione o vincoli non reggono."]],steps:["Descrivi il principio","Definisci un'occasione","Assegna i ruoli","Prova tre ancore","Confronta un ruolo mancante","Usa, adatta o archivia"]},
  pt:{ add:"Registe o resultado com data e mantenha as incertezas separadas dos factos observáveis.", matrix:{title:"Matriz inspiração-conjunto",headers:["Campo","Ideia","Teste do guarda-roupa","Decisão"],rows:[["Ocasião","Lugar, duração, movimento","Real / hipotética","Continuar / arquivar"],["Princípio","Cor, linha, camada, proporção","Sobrevive à substituição?","Usar / adaptar"],["Três âncoras","Funções necessárias","Direto / ajustado / fraco","Manter / rever"],["Atrito","Cuidados, conforto, compra","Baixo / médio / alto","Usar / arquivar"]]},faqs:[["Devo comprar as peças exatas?","Não. Extraia a relação e teste-a com o que possui."],["Quantas compras deve criar uma imagem?","Limite a um candidato; caso contrário adapte ou arquive."],["A foto confirma a cor?","Não. Luz, edição e ecrã limitam a prova."],["E se só funcionar de pé?","Falha o uso: teste sentar, caminhar, mala e casaco."],["Arquivar é falhar?","Não, é útil quando ocasião ou limites não funcionam."]],steps:["Descreva o princípio","Defina uma ocasião","Atribua funções","Teste três âncoras","Compare uma função em falta","Use, adapte ou arquive"]},
};

for (const [locale, meta] of Object.entries(translations)) {
  shared[locale] = {
    kicker: meta.kicker, dateLabel: meta.dateLabel, intro: meta.intro,
    factBox: [["Decision", "Real occasion, existing anchors and no more than one missing role"], ["Limit", "One reference, three anchors, three candidates"], ["Checked", "Hacoo public descriptions reviewed 29 August 2026"]],
    sections: meta.headings.map((heading, i) => [heading, [translatedBody[locale][i], translatedBody[locale][i] + " " + localExtras[locale].add]]),
    matrix: localExtras[locale].matrix, faqs: localExtras[locale].faqs, steps: localExtras[locale].steps,
    sourceNote: "Hacoo Terms of Service and Trust Center reviewed August 29, 2026. Independent editorial outfit-planning method; no affiliation, authenticity claim or product guarantee.",
  };
}

export const outfitPlanningArticle = shared;
