const tools: Record<string, {title: string; intro: string; headings: string[]; rows: string[][]}> = {
 "plan-allchinabuy-shipping": {title:"Worked example: physical and volumetric weight",intro:"Illustration only, not an AllChinaBuy quote. Assume a route uses length × width × height in centimetres divided by 6,000 and charges the greater of physical and volumetric weight. The real divisor, rounding and fees must come from the selected route.",headings:["Parcel","Calculation","Illustrative result"],rows:[["3 kg; 40 × 30 × 25 cm","40 × 30 × 25 ÷ 6,000","5 kg volumetric; 5 kg before route rounding"],["3 kg; 35 × 25 × 20 cm","35 × 25 × 20 ÷ 6,000","2.92 kg volumetric; 3 kg before route rounding"],["Before choosing packing","Compare protection and final dimensions","A lower volume does not guarantee a lower invoice"]]},
 "allchinabuy-tracking-order-parcel-status": {title:"When tracking does not update",intro:"Match the last confirmed event to the information you need. These are checks, not promised processing or delivery times.",headings:["Last event","Evidence to check","Next step"],rows:[["Order paid; no dispatch","Order reference and seller or agent message","Ask whether purchase or dispatch is still pending"],["Label created; no carrier scan","Parcel reference, label date and route estimate","Ask whether the parcel has been handed to the carrier"],["Warehouse received","Stored-item record and QC status","Check intake; international shipping may not yet exist"],["Carrier exception or address problem","Original event text and recipient details","Contact the responsible service with the exact event"]]},
 "warehouse-qc-photo-checklist": {title:"Match the photograph to the decision",intro:"Product listing images illustrate the intended item. Warehouse QC must show the particular unit received for your order.",headings:["Category","Useful views","What photos do not prove"],rows:[["Shoes","Pair together, size labels, fronts, heels and soles","Fit, authenticity or long-term durability"],["Hoodies","Front, back, label, cuffs and requested flat measurements","Fabric feel or shrinkage after washing"],["Jerseys","Front, back, size and selected name, number or badges","Breathability, licensing or wash resistance"]]},
 "allchinabuy-order-status-explained": {title:"Order record to keep",intro:"Record the last confirmed stage before asking for an update. Website maintenance and order progress are separate observations.",headings:["Record","Why it matters"],rows:[["Order number and payment date","Distinguishes the purchase from a parcel"],["Selected size, colour and quantity","Makes a confirmation request specific"],["Latest message and action requested","Identifies whether the next step belongs to you"],["Seller dispatch and warehouse receipt","Keeps domestic delivery separate from international shipping"]]},
 "allchinabuy-warehouse-storage-guide": {title:"A storage ledger for each item",intro:"Older guidance advertised 90-day free storage. This does not establish current availability or an extension during maintenance.",headings:["Field","Record it separately"],rows:[["Warehouse item reference","Match it to the original order"],["Arrival date and displayed deadline","Do not infer an extension"],["QC result and unresolved request","Separate approval from storage"],["Packing or return decision","Confirm order-specific eligibility"]]},
 "allchinabuy-return-refund-guide": {title:"Separate the four after-sales records",intro:"A request or processing label does not establish that money has reached the original payment method.",headings:["Action","Evidence"],rows:[["Cancellation requested","Order number, request date and acknowledgement"],["Seller return accepted","Approval and return tracking if supplied"],["Refund recorded","Amount, currency and account transaction reference"],["Withdrawal completed","Payment-method reference and receipt"]]},
 "allchinabuy-fees-payment-methods": {title:"A complete cost record",intro:"Keep confirmed amounts separate from estimates. No current payment method, fee percentage or delivery price is established by this example.",headings:["Cost component","Evidence to save"],rows:[["Selected product and domestic delivery","Exact option, currency and dated checkout total"],["Payment and conversion","Displayed fees and receipt"],["Warehouse or packing services","Services selected and their quoted amounts"],["International parcel","Destination, dimensions, billed weight and quote"]]},
 "allchinabuy-parcel-packing-consolidation": {title:"Compare one parcel with a sensible split",intro:"Consolidation can reduce repeated base charges, but the dimensions and item restrictions of the complete parcel still matter.",headings:["Scenario","Compare"],rows:[["One combined parcel","External dimensions, compatible items and route options"],["Two separate parcels","Both base charges, both weights and extra packing"],["Keep original packaging","Protection, presentation and extra volume"],["Remove selected packaging","Protection replacement and measured result"]]},
 "allchinabuy-listing-identity-verification": {title:"Record a listing decision",intro:"Use observable evidence rather than a promotional label. Recheck a replacement as a new listing.",headings:["Decision","Evidence threshold"],rows:[["Pass","Current page and selected option match the saved item"],["Hold","A decision-critical detail remains unclear"],["Replace","A different destination has been checked separately"],["Remove from shortlist","Dead route or unresolved identity mismatch"]]},
 "how-to-use-allchinabuy-spreadsheet": {title:"Fields that make a shortlist useful",intro:"A product directory and a historical platform tutorial are different resources. Keep the exact destination and verification date with each selection.",headings:["Before ordering","After ordering, if available"],rows:[["Current product link and exact option","Order number and payment record"],["Size chart and reference measurements","Warehouse item and QC evidence"],["Dated price and uncertain cost components","Actual parcel dimensions and route quote"],["Unresolved questions","Support request and confirmed resolution"]]}
};
export default function ArticleTools({slug}:{slug:string}) {
 const tool=tools[slug]; if(!tool) return null;
 return <section className="article-tool"><p className="section-kicker">Practical reference · updated October 2026</p><h2>{tool.title}</h2><p>{tool.intro}</p><table><thead><tr>{tool.headings.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{tool.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></section>;
}
