const base = {
  pl: {
    title: "Jak korzystać z mapowanego indeksu produktów FindQC, nie traktując go jako rekomendacji", shortTitle: "Ostrożne używanie indeksu produktów", description: "Zawężaj kandydatów w mapowanym indeksie FindQC, oddzielając obecność w indeksie od aktualności oferty, jakości i przydatności.", excerpt: "Indeks jest warstwą nawigacji, a nie listą najlepszych produktów. Zweryfikuj dokładną stronę docelową i zachowaj niewiadome.", category: "Nawigacja po indeksie produktów", readTime: "11 min czytania", date: "1 września 2026", heroAlt: "Złożona koszulka jako redakcyjny przykład mapowanego znaleziska", keywords: ["indeks produktów FindQC", "mapowane znaleziska QC", "trasy kategorii", "niezależny indeks produktów"],
    intro: ["Mapowany indeks rozwiązuje problem nawigacji: dzieli duży katalog na nazwane kategorie i powtarzalne trasy. Nie rozstrzyga zakupu. Obecność nie oznacza, że produkt jest najlepszy, aktualny, autentyczny, wolny od wad ani odpowiedni dla konkretnej osoby.", "Użyj indeksu do zmniejszenia obszaru poszukiwań, a potem sprawdź każdego kandydata na dokładnej stronie docelowej. Oddziel twierdzenia oferty, obrazy referencyjne i niewiadome. FindQC dostarcza kontekst badawczy QC; wybrany przez kupującego agent realizuje zakup, magazyn, zwroty, pakowanie i wysyłkę."],
    sectionTitles: ["1. Określ, co indeks może robić", "2. Zacznij od trasy kategorii, nie rankingu „najlepszych”", "3. Czytaj kartę produktu jako zestaw wskazówek", "4. Sprawdź dokładny cel przed zapisaniem kandydata", "5. Oddziel trzy warstwy dowodów", "6. Zbuduj shortlistę bez nieuzasadnionych rankingów", "7. Sprawdź zapisane znalezisko ponownie", "8. Audytuj trasę od kategorii do produktu"],
    p: [
      ["Traktuj indeks jak mapę. Etykieta kategorii prowadzi do właściwej części katalogu, a karta zachowuje tytuł, obraz, identyfikator i trasę. Przyspiesza to odkrywanie, lecz nie weryfikuje bieżącej oferty ani sfotografowanego egzemplarza. Karta rozpoczyna kontrolę, a jej nie kończy.", "Przed przeglądaniem określ decyzję na poziomie kategorii: porównać kształty butów, znaleźć bluzę o danej konstrukcji albo akcesorium w limicie wymiarów. Konkretny cel zapobiega przypadkowemu uznaniu atrakcyjnej karty za rekomendację."],
      ["Wybierz najwęższą użyteczną kategorię i poznaj jej zakres. Buty, koszulki sportowe, elektronika i akcesoria wymagają innych kontroli. Nie zakładaj, że pierwsza karta jest najlepsza; kolejność może wynikać z grupowania redakcyjnego, aktualizacji lub układu.", "Przejrzyj kilka kart, aby poznać zakres. Zanotuj typ, przybliżoną cenę referencyjną, kształt i identyfikator. Odrzucaj oczywiste niezgodności według wymagań kategorii, nie popularności. Trzech różnych kandydatów łatwiej zweryfikować niż długą listę bez powodów."],
      ["Tytuł jest etykietą, nie specyfikacją. Miniatura jest obrazem referencyjnym, nie dowodem dostarczonego koloru lub stanu. Kwota USD jest przybliżeniem, dopóki strona docelowa nie pokaże aktualnej ceny. Identyfikator pomaga zachować ciągłość, ale oferta może się zmienić lub przekierować.", "Zapisuj pola osobno. Jeśli tytuł sugeruje materiał, którego strona docelowa nie potwierdza, oznacz go jako niezweryfikowany. Jeśli obraz pokazuje dodatek niewymieniony w opcji, nie zakładaj, że jest dołączony. Karta tworzy pytania weryfikacyjne, nie odpowiedzi poza widocznym zakresem."],
      ["Otwórz mapowany link i poczekaj na końcowy adres. Porównaj domenę, trasę, ID produktu, kontekst sprzedawcy, tytuł, pierwszy obraz i opcje z kartą. Przekierowanie nie musi być błędem, ale wymaga nowej kontroli tożsamości. Kategoria, ekran logowania lub niepowiązany zamiennik nie jest zweryfikowaną trasą produktu.", "Sprawdź, czy wymagany kolor, rozmiar, wersja i liczba są obecnie dostępne. Zapisz datę i końcowy URL. Jeśli strony nie da się otworzyć, oznacz kandydata jako nieaktualnego lub niezweryfikowanego zamiast wyprowadzać dostępność ze starej miniatury."],
      ["Warstwa pierwsza to dane indeksu: kategoria, tytuł, miniatura, kwota referencyjna i trasa. Druga to aktualna strona: sprzedawca, tytuł, wybrana opcja, cena i dostępność. Trzecia to niezależne badania QC: datowane zdjęcia lub rekordy konkretnej próbki. Łączenie warstw daje pozornie pewne wnioski.", "Obraz referencyjny może potwierdzić rodzinę produktu, ale nie jakość obecnego egzemplarza. Historyczne QC pokazuje punkty kontroli, lecz nie gwarantuje kolejnej partii. Strona może deklarować materiał, ale deklaracja nie jest badaniem laboratoryjnym. Oznaczaj każdą tezę warstwą."],
      ["Porównuj kandydatów według tych samych wymagań: dokładna opcja, potrzebny wymiar, kontekst QC, sprawdzona cena i krytyczne niewiadome. Nie dodawaj oceny jakości bez pomiaru jakości. „Nieznane” jest prawidłowym i często najważniejszym wynikiem.", "Nie nazywaj produktu najlepszym tylko dlatego, że karta jest pełniejsza. Może to świadczyć o lepszym indeksowaniu, nie lepszym towarze. Odrzuć niespełniających warunków, a kompromisy pozostaw jawne. Jeśli żaden nie pasuje, wróć do kategorii zamiast obniżać wymóg konieczny."],
      ["Mapowana trasa starzeje się. Otwórz kandydatów ponownie przed zakupem oraz po zmianie ważnej opcji lub ceny. Porównaj końcowy URL, ID, sprzedawcę, opcje i status z zapisanym rekordem. Dopisuj zmiany, nie nadpisuj wcześniejszej weryfikacji.", "Gdy link jest nieaktualny, zgłoś mapowany URL, cel, datę i konflikt. Samo przekierowanie nie dowodzi oszustwa ani złej jakości. Odpowiedzialny indeks poprawia nawigację, lecz nie zna przyczyny zmiany oferty. W międzyczasie wybierz innego zweryfikowanego kandydata."],
      ["Obronna trasa jest powtarzalna. Inna osoba powinna zacząć w kategorii, otworzyć tę samą kartę, dotrzeć do celu, wskazać wymaganą opcję i zobaczyć niewiadome. Usuń kandydatów bez odtwarzalnej trasy i zapisuj krótkie, polowe powody włączenia i wykluczenia.", "Końcowy wniosek powinien być skromny: kandydat pozostaje, bo dokładny cel i opcję zweryfikowano 1 września, obraz pasuje do rodziny, a dwa ważne pola nadal potrzebują bieżących dowodów. To mówi, co wniósł indeks i co musi ustalić późniejszy proces."],
    ],
  },
  es: {
    title: "Cómo usar un índice mapeado de productos FindQC sin tratarlo como recomendación", shortTitle: "Usar un índice de productos con criterio", description: "Reduce candidatos con un índice mapeado de FindQC sin confundir inclusión, disponibilidad, calidad e idoneidad.", excerpt: "Un índice es navegación, no una lista de mejores productos. Verifica el destino exacto y conserva lo desconocido.", category: "Navegación del índice", readTime: "11 min de lectura", date: "1 de septiembre de 2026", heroAlt: "Camiseta doblada como ejemplo editorial de un producto mapeado", keywords: ["índice de productos FindQC", "hallazgos QC mapeados", "rutas de categoría", "índice independiente"],
    intro: ["Un índice mapeado resuelve la navegación: convierte un catálogo grande en categorías y rutas repetibles. No resuelve la compra. Estar incluido no significa ser el mejor, estar disponible, ser auténtico, no tener defectos o servir para una persona concreta.", "Úsalo para reducir el espacio de búsqueda y verifica cada candidato en su destino exacto. Separa afirmaciones del anuncio, imágenes de referencia e incógnitas. FindQC aporta contexto de investigación QC; el agente elegido por el comprador ejecuta compra, almacén, devoluciones, embalaje y envío."],
    sectionTitles: ["1. Define lo que el índice puede hacer", "2. Empieza por la ruta de categoría, no por un ranking", "3. Lee la tarjeta como un conjunto de pistas", "4. Verifica el destino exacto antes de guardar", "5. Mantén separadas tres capas de evidencia", "6. Crea una lista corta sin rankings infundados", "7. Revisa un hallazgo guardado antes de actuar", "8. Audita la ruta de categoría a producto"],
    p: [
      ["Trata el índice como un mapa. La categoría conduce a la parte adecuada y la tarjeta conserva título, imagen, identificador y destino. Esto acelera el descubrimiento, pero no verifica la oferta actual ni la unidad fotografiada. La tarjeta inicia la comprobación; no la termina.", "Antes de navegar, define la decisión de categoría: comparar formas de calzado, encontrar una sudadera con cierta construcción o un accesorio dentro de un límite. Un propósito concreto evita que una tarjeta atractiva se convierta por accidente en recomendación."],
      ["Elige la categoría útil más estrecha y entiende su alcance. Calzado, camisetas deportivas, electrónica y accesorios exigen controles distintos. No supongas que la primera tarjeta es la mejor: el orden puede reflejar edición, actualización o diseño, no calidad.", "Examina varias tarjetas para entender el rango. Anota tipo, referencia aproximada, forma e identificador. Descarta incompatibilidades mediante requisitos, no popularidad. Tres candidatos diferentes son más verificables que una lista larga sin motivos."],
      ["El título es una etiqueta, no una ficha técnica. La miniatura es referencia, no prueba del color o estado entregado. El USD mostrado es aproximado hasta que el destino confirme el precio. El identificador ayuda, pero el anuncio puede cambiar, redirigir o desaparecer.", "Mantén los campos separados. Si el título sugiere un material que el destino no declara, márcalo sin verificar. Si la imagen incluye un accesorio que la opción no nombra, no lo des por incluido. Los campos generan preguntas de verificación; no responden fuera de su alcance."],
      ["Abre el enlace y espera el destino final. Compara dominio, ruta, ID, vendedor, título, primera imagen y opciones con la tarjeta. Una redirección no es necesariamente errónea, pero exige otra comprobación. Una categoría, acceso o sustituto no relacionado no es una ruta de producto verificada.", "Comprueba que color, talla, versión y cantidad requeridos sean seleccionables ahora. Registra la fecha y URL final. Si la página no abre, marca el candidato como obsoleto o no verificado; no inventes disponibilidad desde una miniatura antigua."],
      ["La primera capa es lo que dice el índice: categoría, título, miniatura, referencia y ruta. La segunda es el destino vivo: vendedor, título, opción, importe y disponibilidad. La tercera es investigación QC: fotos fechadas de una muestra. Mezclarlas crea conclusiones seguras pero no respaldadas.", "Una imagen ayuda a confirmar la familia, no la calidad actual. El QC histórico señala qué revisar, no garantiza el siguiente lote. Una página puede declarar material, pero no es una prueba de laboratorio. Etiqueta cada afirmación por capa para conservar su límite."],
      ["Compara con los mismos requisitos: opción exacta, dimensión necesaria, contexto QC, precio comprobado e incógnitas críticas. No añadas una nota de calidad sin medición. “Desconocido” es válido y a menudo es la diferencia más importante.", "No llames mejor a un artículo porque su tarjeta esté más completa; puede ser mejor indexación. Elimina quien falla una condición y deja visibles los compromisos. Si ninguno encaja, vuelve a la categoría en vez de rebajar un requisito obligatorio."],
      ["Una ruta envejece. Reabre candidatos antes de comprar y cuando cambie una opción o precio material. Compara URL final, ID, vendedor, opciones y estado con el registro. Añade cambios; no borres la verificación anterior que explica por qué entró en la lista.", "Si el enlace está obsoleto, informa URL, destino, fecha y conflicto. Una redirección sola no demuestra fraude ni mala calidad. El índice puede corregir navegación, no explicar por qué cambió el vendedor. Usa otro candidato verificado mientras se revisa."],
      ["Una ruta defendible puede repetirse. Otra persona debe entrar por la categoría, abrir la tarjeta, llegar al destino, hallar la opción y ver incógnitas. Retira rutas que no puedan reproducirse y conserva motivos breves basados en campos.", "La conclusión debe ser modesta: el candidato sigue porque destino y opción se verificaron el 1 de septiembre, la imagen coincide con la familia y dos campos aún necesitan evidencia actual. Explica qué aportó el índice y qué debe establecer el proceso posterior."],
    ],
  },
  de: {
    title: "Einen kartierten FindQC-Produktindex nutzen, ohne ihn als Empfehlung zu behandeln", shortTitle: "Produktindex bewusst nutzen", description: "Kandidaten mit einem kartierten FindQC-Index eingrenzen und Aufnahme, Verfügbarkeit, Qualität und Eignung getrennt halten.", excerpt: "Ein Index ist Navigation, keine Bestenliste. Prüfe das genaue Ziel und halte Unbekanntes sichtbar.", category: "Produktindex-Navigation", readTime: "11 Min. Lesezeit", date: "1. September 2026", heroAlt: "Gefaltetes Shirt als redaktionelles Beispiel eines kartierten Produktfunds", keywords: ["FindQC Produktindex", "kartierte QC-Funde", "Kategorierouten", "unabhängiger Produktindex"],
    intro: ["Ein kartierter Index löst ein Navigationsproblem: Er macht aus einem großen Katalog benannte Kategorien und wiederholbare Routen. Er löst nicht die Kaufentscheidung. Aufnahme bedeutet weder bestes, aktuelles, authentisches, fehlerfreies noch persönlich geeignetes Produkt.", "Nutze den Index zum Verkleinern des Suchraums und prüfe jeden Kandidaten auf der exakten Zielseite. Trenne Angebotsaussagen, Referenzbilder und Unbekanntes. FindQC liefert QC-Recherchekontext; der vom Käufer gewählte Agent führt Kauf, Lager, Rückgabe, Verpackung und Versand aus."],
    sectionTitles: ["1. Erlaubte Aufgabe des Index festlegen", "2. Mit der Kategorieroute statt einem Ranking beginnen", "3. Produktkarten als Hinweise lesen", "4. Exaktes Ziel vor dem Speichern prüfen", "5. Drei Belegebenen getrennt halten", "6. Shortlist ohne unbelegte Rangfolge bauen", "7. Gespeicherten Fund erneut prüfen", "8. Route von Kategorie zu Produkt auditieren"],
    p: [
      ["Behandle den Index wie eine Karte. Die Kategorie führt in den richtigen Katalogteil; die Karte bewahrt Titel, Bild, Kennung und Route. Das beschleunigt die Entdeckung, bestätigt aber weder das aktuelle Angebot noch das fotografierte Exemplar. Die Karte beginnt die Prüfung, sie beendet sie nicht.", "Formuliere vor dem Browsen die Kategorieentscheidung: Schuhformen vergleichen, einen Hoodie mit bestimmter Konstruktion oder Zubehör unter einer Größenbegrenzung finden. Ein klarer Zweck verhindert, dass eine attraktive Karte versehentlich zur Empfehlung wird."],
      ["Wähle die engste nützliche Kategorie und lies ihren Umfang. Schuhe, Trikots, Elektronik und Zubehör brauchen andere Prüfungen. Die erste Karte ist nicht automatisch die stärkste; Reihenfolge kann Redaktion, Aktualisierung oder Layout spiegeln und nicht Qualität.", "Scanne mehrere Karten. Notiere Typ, ungefähre Referenz, Form und Kennung. Entferne offensichtliche Abweichungen anhand der Anforderungen statt Popularität. Drei unterschiedliche Kandidaten lassen sich besser prüfen als eine lange Liste ohne Gründe."],
      ["Ein Titel ist ein Etikett, kein Datenblatt. Die Miniatur ist ein Referenzbild, kein Beleg für gelieferten Farbton oder Zustand. USD bleibt näherungsweise, bis das Ziel den aktuellen Preis zeigt. Eine Kennung hilft, doch Angebote können wechseln, umleiten oder verschwinden.", "Halte Felder getrennt. Behauptet der Titel ein Material, das die Zielseite nicht nennt, bleibt es ungeprüft. Zeigt das Bild Zubehör, das die Option nicht nennt, gilt es nicht als enthalten. Kartenfelder erzeugen Prüffragen, keine Antworten jenseits ihres sichtbaren Umfangs."],
      ["Öffne den Link bis zum endgültigen Ziel. Vergleiche Domain, Route, Produkt-ID, Verkäuferkontext, Titel, erstes Bild und Optionen mit der Karte. Eine Umleitung ist nicht automatisch falsch, verlangt aber eine neue Identitätsprüfung. Kategorie, Anmeldung oder unpassender Ersatz sind keine verifizierte Produktroute.", "Prüfe, ob Farbe, Größe, Version und Menge jetzt wählbar sind. Speichere Datum und endgültige URL. Ist die Seite nicht erreichbar, markiere den Kandidaten als veraltet oder ungeprüft, statt aus der alten Miniatur Verfügbarkeit abzuleiten."],
      ["Ebene eins ist der Index: Kategorie, Titel, Miniatur, Referenzbetrag und Route. Ebene zwei ist das Live-Ziel: Verkäufer, Titel, Option, Betrag und Verfügbarkeit. Ebene drei ist QC-Recherche: datierte Aufnahmen einer Probe. Vermischung erzeugt selbstsichere, unbelegte Schlüsse.", "Ein Referenzbild bestätigt höchstens die Produktfamilie, nicht die Qualität des aktuellen Exemplars. Historische QC zeigt Prüfpunkte, garantiert aber keine Charge. Eine Materialangabe ist kein Labortest. Kennzeichne Aussagen nach Ebene, damit Grenzen sichtbar bleiben."],
      ["Vergleiche Kandidaten mit denselben Anforderungen: exakte Option, nötiges Maß, relevanter QC-Kontext, geprüfter Preis und kritische Lücken. Vergib keinen Qualitätsscore ohne Qualitätsmessung. „Unbekannt“ ist ein gültiges und oft wichtiges Ergebnis.", "Nenne keinen Artikel den besten, weil seine Karte vollständiger ist; das kann nur bessere Indexierung sein. Entferne Pflichtfehler, zeige verbleibende Kompromisse. Passt keiner, gehe zur Kategorie zurück, statt eine unverhandelbare Bedingung zu senken."],
      ["Eine Route altert. Öffne Kandidaten vor dem Kauf sowie nach wichtigen Options- oder Preisänderungen neu. Vergleiche Ziel-URL, ID, Verkäufer, Optionen und Status mit dem Datensatz. Hänge Änderungen an, statt frühere Prüfung zu überschreiben.", "Melde bei veraltetem Link die kartierte URL, das Ziel, Datum und den Konflikt. Eine Umleitung allein beweist weder Betrug noch schlechte Qualität. Der Index korrigiert Navigation, kennt aber nicht den Änderungsgrund. Nutze während der Prüfung einen anderen verifizierten Kandidaten."],
      ["Eine belastbare Route ist wiederholbar. Eine andere Person sollte über die Kategorie dieselbe Karte und das Ziel erreichen, die Option erkennen und Lücken sehen. Entferne nicht reproduzierbare Routen und halte Ein- und Ausschlussgründe kurz und feldbezogen.", "Der Schlusssatz bleibt bescheiden: Ziel und Option wurden am 1. September geprüft, das Bild passt zur Familie und zwei relevante Felder brauchen aktuelle Belege. Das erklärt den Beitrag des Index und was Kauf- und Lagerprozess noch feststellen müssen."],
    ],
  },
  ro: {
    title: "Cum folosești un index mapat de produse FindQC fără să-l tratezi ca recomandare", shortTitle: "Folosirea atentă a indexului", description: "Restrânge candidații cu un index FindQC mapat, separând includerea, disponibilitatea, calitatea și potrivirea.", excerpt: "Indexul este navigație, nu listă de produse bune. Verifică destinația exactă și păstrează necunoscutele.", category: "Navigare în indexul de produse", readTime: "11 min de citit", date: "1 septembrie 2026", heroAlt: "Tricou pliat ca exemplu editorial de produs mapat", keywords: ["index produse FindQC", "produse QC mapate", "rute de categorie", "index independent"],
    intro: ["Un index mapat rezolvă navigarea: transformă un catalog mare în categorii și rute repetabile. Nu decide cumpărarea. Includerea nu înseamnă că produsul este cel mai bun, actual, autentic, fără defecte sau potrivit unei persoane.", "Folosește indexul pentru a micșora căutarea, apoi verifică fiecare candidat pe destinația exactă. Separă afirmațiile listării, imaginile de referință și necunoscutele. FindQC oferă context de cercetare QC; agentul ales de cumpărător execută achiziția, depozitul, returul, ambalarea și transportul."],
    sectionTitles: ["1. Definește ce are voie să facă indexul", "2. Începe cu ruta categoriei, nu cu un clasament", "3. Citește cardul ca set de indicii", "4. Verifică destinația exactă înainte de salvare", "5. Separă trei niveluri de dovezi", "6. Construiește lista scurtă fără clasamente nefondate", "7. Reverifică produsul salvat", "8. Auditează ruta categorie-produs"],
    p: [
      ["Tratează indexul ca pe o hartă. Categoria duce în zona potrivită, iar cardul păstrează titlul, imaginea, identificatorul și ruta. Descoperirea devine mai rapidă, dar oferta curentă și unitatea fotografiată nu sunt verificate. Cardul începe controlul, nu îl încheie.", "Înainte de navigare, scrie decizia la nivel de categorie: compararea formelor de pantofi, găsirea unui hanorac cu o construcție anume sau a unui accesoriu sub o limită. Un scop clar împiedică transformarea unei imagini atrăgătoare în recomandare."],
      ["Alege cea mai îngustă categorie utilă. Pantofii, tricourile sportive, electronicele și accesoriile cer verificări diferite. Primul card nu este automat cea mai bună opțiune; ordinea poate reflecta editarea, actualizarea sau aspectul, nu calitatea.", "Privește mai multe carduri pentru a înțelege gama. Notează tipul, referința aproximativă, forma și identificatorul. Elimină nepotrivirile după cerințe, nu popularitate. Trei candidați diferiți sunt mai ușor de verificat decât o listă fără motive."],
      ["Titlul este etichetă, nu specificație. Miniatura este referință, nu dovada culorii sau stării livrate. Valoarea USD este aproximativă până când destinația confirmă prețul. Identificatorul ajută, dar listarea se poate schimba, redirecționa sau închide.", "Păstrează câmpurile separat. Dacă titlul sugerează un material pe care destinația nu îl declară, marchează-l neverificat. Dacă imaginea arată o piesă care nu apare în opțiune, nu o considera inclusă. Cardul generează întrebări, nu răspunsuri în afara limitelor sale."],
      ["Deschide linkul până la destinația finală. Compară domeniul, ruta, ID-ul, vânzătorul, titlul, prima imagine și opțiunile. O redirecționare nu este neapărat greșită, dar cere o nouă verificare. O categorie, autentificare sau înlocuire fără legătură nu este rută de produs verificată.", "Verifică dacă varianta, mărimea, culoarea și cantitatea necesare pot fi selectate acum. Salvează data și URL-ul final. Dacă pagina nu este accesibilă, marcheaz-o depășită sau neverificată, fără a inventa disponibilitatea din miniatura veche."],
      ["Primul nivel este indexul: categorie, titlu, miniatură, valoare de referință și rută. Al doilea este destinația actuală: vânzător, titlu, opțiune, sumă și disponibilitate. Al treilea este cercetarea QC: imagini datate ale unei mostre. Amestecarea produce concluzii nefondate.", "Imaginea de referință confirmă familia, nu calitatea unității curente. QC istoric indică ce să verifici, dar nu garantează lotul următor. O declarație de material nu este test de laborator. Etichetează fiecare afirmație după nivel."],
      ["Compară aceleași cerințe: opțiune exactă, dimensiune necesară, context QC, preț verificat și necunoscute critice. Nu crea scor de calitate fără măsurare. „Necunoscut” este un rezultat valid și adesea important.", "Nu numi un produs cel mai bun pentru că are card complet; poate fi doar mai bine indexat. Elimină candidații care nu îndeplinesc condițiile și păstrează compromisurile vizibile. Dacă niciunul nu se potrivește, revino la categorie."],
      ["O rută îmbătrânește. Redeschide candidații înainte de cumpărare și după schimbări de opțiune sau preț. Compară URL-ul final, ID-ul, vânzătorul, opțiunile și starea cu înregistrarea. Adaugă modificările fără a șterge verificarea inițială.", "Pentru un link vechi, raportează URL-ul mapat, destinația, data și conflictul. Redirecționarea singură nu dovedește fraudă sau calitate slabă. Indexul poate corecta navigarea, nu explica motivul. Alege alt candidat verificat între timp."],
      ["O rută defensabilă poate fi repetată. Altă persoană trebuie să pornească din categorie, să deschidă același card, să ajungă la destinație, să identifice opțiunea și necunoscutele. Elimină rutele nereproductibile și păstrează motive scurte, bazate pe câmpuri.", "Concluzia trebuie să fie modestă: destinația și opțiunea au fost verificate la 1 septembrie, imaginea corespunde familiei, iar două câmpuri necesită dovezi actuale. Astfel se vede ce a oferit indexul și ce mai trebuie stabilit."],
    ],
  },
};

const listText = {
  pl: ["Kategoria odpowiada zamierzonemu użyciu.","Odrzucono oczywiste niezgodności rozmiaru, kształtu lub zgodności.","Zachowano dwóch lub trzech istotnie różnych kandydatów.","Zapisano powód pozostawienia każdego.","Cenę i dostępność sprawdza się na stronie docelowej."],
  es: ["La categoría coincide con el uso previsto.","Se descartan incompatibilidades evidentes.","Se conservan dos o tres candidatos distintos.","Se registra por qué sigue cada uno.","Precio y disponibilidad se verifican en el destino."],
  de: ["Kategorie passt zum Zweck.","Offensichtliche Größen-, Form- oder Kompatibilitätsfehler sind entfernt.","Zwei oder drei unterschiedliche Kandidaten bleiben.","Der Grund für jeden Kandidaten ist notiert.","Preis und Verfügbarkeit werden am Live-Ziel geprüft."],
  ro: ["Categoria corespunde utilizării.","Nepotrivirile evidente sunt eliminate.","Rămân doi sau trei candidați diferiți.","Motivul fiecăruia este notat.","Prețul și disponibilitatea se verifică la destinație."],
};

function article(lang, d) {
  const sections = d.sectionTitles.map((title, i) => ({ id: ["purpose","route","card","destination","evidence","shortlist","refresh","audit"][i], title, blocks: [
    { type:"p", text:d.p[i][0] }, { type:"p", text:d.p[i][1] },
    ...(i === 1 ? [{ type:"list", title: lang === "de" ? "Erster Durchgang" : lang === "es" ? "Primera pasada" : lang === "pl" ? "Pierwszy przebieg" : "Prima trecere", items:listText[lang] }] : []),
    ...(i === 2 ? [{ type:"table", headers: lang === "de" ? ["Kartenfeld","Nützlicher Hinweis","Noch zu prüfen"] : lang === "es" ? ["Campo","Pista útil","Por verificar"] : lang === "pl" ? ["Pole karty","Przydatna wskazówka","Do sprawdzenia"] : ["Câmp","Indiciu util","De verificat"], rows:[["Title / tytuł","Product family / familie","Exact option / genaue Option"],["Thumbnail / miniatură","Visual identity / identitate","Current images / aktuelle Bilder"],["USD reference","Rough position","Live option price"],["Mapped link","Destination route","Redirect and availability"]] }] : []),
    ...(i === 7 ? [{ type:"list", title: lang === "de" ? "Abschlussaudit" : lang === "es" ? "Auditoría final" : lang === "pl" ? "Audyt końcowy" : "Audit final", items:[d.sectionTitles[0], d.sectionTitles[3], d.sectionTitles[4], d.sectionTitles[5], d.sectionTitles[7]] }] : []),
  ] }));
  return { ...d, heroImage:"/products/tshirt.webp", intro:d.intro, sections, cta:{ eyebrow:d.category, title:d.excerpt, label:d.shortTitle } };
}

export const mappedIndexLocales = Object.fromEntries(Object.entries(base).map(([lang, d]) => [lang, article(lang, d)]));
