import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SitePage } from "../../site-page";
import { copy, languages, pageIntro, pageKeys, type Lang, type PageKey } from "../../site-data";
import { seoArticleSlugs } from "../../seo-articles";
import { getLocalizedSeoArticle } from "../../seo-article-locales";
import { trustPageKeys, trustPages } from "../../trust-data";

const siteBase = "https://joyagoos.org";
export const dynamicParams = false;
const basePages=["spreadsheet","finds","guide","qc","shipping","faq","articles"];
function parsePage(slug?: string[]): PageKey | null { if(!slug?.length)return "home"; if(slug.length===1&&(basePages.includes(slug[0])||trustPageKeys.includes(slug[0] as typeof trustPageKeys[number])))return slug[0] as PageKey; if(slug.length===2&&slug[0]==="articles"&&seoArticleSlugs.includes(slug[1]))return slug[1] as PageKey; return null; }
function route(lang:Lang,page:PageKey){if(page==="home")return `/${lang}/`;if(seoArticleSlugs.includes(page))return `/${lang}/articles/${page}/`;return `/${lang}/${page}/`;}
export function generateStaticParams(){return languages.flatMap(lang=>pageKeys.map(page=>({lang,slug:page==="home"?[]:seoArticleSlugs.includes(page)?["articles",page]:[page]})));}
const conciseTitles:Record<Lang,Partial<Record<PageKey,string>>>= {
  en:{home:"Joyagoo Reviews, Fees & Buyer Policy Guide",spreadsheet:"Joyagoo Fees, Returns & Warehouse Policy Index",finds:"Joyagoo Product Risk Examples",guide:"Joyagoo Buyer Policy Verification Guide",qc:"Joyagoo QC & 5-Day Return Guide",shipping:"Joyagoo Shipping Cost, Weight & Warehouse Guide",faq:"Joyagoo Fees, Returns & Shipping FAQ",articles:"Joyagoo Reviews, Fees & Policy Research","joyagoo-buying-fees-guide":"Joyagoo Fees & Buying Costs Guide","joyagoo-qc-return-window-guide":"Joyagoo QC & 5-Day Return Guide","joyagoo-warehouse-rehearsal-shipping-guide":"Joyagoo Warehouse & Rehearsal Shipping","volumetric-weight-guide":"Joyagoo Volumetric Weight Guide","joyagoo-reviews-buyer-signals":"Joyagoo Reviews: Buyer Signals & Risks"},
  de:{home:"Joyagoo Bewertungen, Gebühren & Käuferregeln",spreadsheet:"Joyagoo Gebühren-, Rückgabe- & Lagerindex",finds:"Joyagoo Produktrisiko-Beispiele",guide:"Joyagoo Richtlinien-Prüfleitfaden",qc:"Joyagoo QC & 5-Tage-Rückgabe",shipping:"Joyagoo Versandkosten, Gewicht & Lager",faq:"Joyagoo Gebühren-, Rückgabe- & Versand-FAQ",articles:"Joyagoo Bewertungen & Richtlinienanalyse","joyagoo-buying-fees-guide":"Joyagoo Gebühren & Kaufkosten","joyagoo-qc-return-window-guide":"Joyagoo QC & 5-Tage-Rückgabe","joyagoo-warehouse-rehearsal-shipping-guide":"Joyagoo Lager & Probeverpackung","volumetric-weight-guide":"Joyagoo Volumengewicht","joyagoo-reviews-buyer-signals":"Joyagoo Bewertungen & Käufersignale"},
  es:{home:"Opiniones, tarifas y políticas de Joyagoo",spreadsheet:"Índice Joyagoo de tarifas, devoluciones y almacén",finds:"Ejemplos de riesgo de productos Joyagoo",guide:"Guía para verificar políticas de Joyagoo",qc:"QC Joyagoo y devolución de 5 días",shipping:"Coste, peso y almacén de Joyagoo",faq:"Preguntas sobre tarifas, devoluciones y envío",articles:"Opiniones y análisis de políticas Joyagoo","joyagoo-buying-fees-guide":"Tarifas y costes de compra Joyagoo","joyagoo-qc-return-window-guide":"QC Joyagoo y devolución de 5 días","joyagoo-warehouse-rehearsal-shipping-guide":"Almacén y ensayo de envío Joyagoo","volumetric-weight-guide":"Peso volumétrico Joyagoo","joyagoo-reviews-buyer-signals":"Opiniones Joyagoo: señales y riesgos"},
  fr:{home:"Avis, frais et politiques acheteurs Joyagoo",spreadsheet:"Index Joyagoo des frais, retours et stockage",finds:"Exemples de risques produits Joyagoo",guide:"Guide de vérification des règles Joyagoo",qc:"QC Joyagoo et retour sous 5 jours",shipping:"Coût, poids et entrepôt Joyagoo",faq:"FAQ frais, retours et livraison Joyagoo",articles:"Avis et analyse des politiques Joyagoo","joyagoo-buying-fees-guide":"Frais et coûts d’achat Joyagoo","joyagoo-qc-return-window-guide":"QC Joyagoo et retour sous 5 jours","joyagoo-warehouse-rehearsal-shipping-guide":"Entrepôt et pré-emballage Joyagoo","volumetric-weight-guide":"Poids volumétrique Joyagoo","joyagoo-reviews-buyer-signals":"Avis Joyagoo : signaux et risques"},
  it:{home:"Recensioni, costi e regole Joyagoo",spreadsheet:"Indice Joyagoo su costi, resi e deposito",finds:"Esempi di rischio prodotto Joyagoo",guide:"Guida alla verifica delle regole Joyagoo",qc:"QC Joyagoo e reso entro 5 giorni",shipping:"Costi, peso e deposito Joyagoo",faq:"FAQ Joyagoo su costi, resi e spedizione",articles:"Recensioni e analisi delle regole Joyagoo","joyagoo-buying-fees-guide":"Costi e tariffe di acquisto Joyagoo","joyagoo-qc-return-window-guide":"QC Joyagoo e reso entro 5 giorni","joyagoo-warehouse-rehearsal-shipping-guide":"Deposito e prova imballaggio Joyagoo","volumetric-weight-guide":"Peso volumetrico Joyagoo","joyagoo-reviews-buyer-signals":"Recensioni Joyagoo: segnali e rischi"}
};
export async function generateMetadata({params}:{params:Promise<{lang:string;slug?:string[]}>}):Promise<Metadata>{const {lang:rawLang,slug}=await params;const lang=rawLang as Lang;const page=parsePage(slug);if(!languages.includes(lang)||!page)return{};const article=getLocalizedSeoArticle(page,lang);const trust=trustPageKeys.includes(page as typeof trustPageKeys[number])?trustPages[lang][page as typeof trustPageKeys[number]]:null;const intro=page!=="home"&&!article&&!trust?pageIntro[lang][page as keyof typeof pageIntro.en]:null;const label=trust?.title??conciseTitles[lang][page]??article?.title??intro?.[1]??"Joyagoos";const description=trust?.description??(page==="home"?copy[lang].lede as string:article?.description??intro?.[2]??copy[lang].disclaimer as string);const canonical=`${siteBase}${route(lang,page)}`;const map=Object.fromEntries(languages.map(code=>[code,`${siteBase}${route(code,page)}`]));return{title:{absolute:`${label} | Joyagoos`},description,robots:{index:true,follow:true},alternates:{canonical,languages:{...map,"x-default":`${siteBase}${route("en",page)}`}},openGraph:{title:`${label} | Joyagoos`,description,url:canonical,siteName:"Joyagoos",locale:lang,type:article?"article":"website",images:[{url:`${siteBase}/products/accessories.webp`,width:960,height:1280,alt:"Joyagoos buyer policy research"}]},twitter:{card:"summary_large_image",title:`${label} | Joyagoos`,description,images:[`${siteBase}/products/accessories.webp`]}};}
export default async function LangPage({params}:{params:Promise<{lang:string;slug?:string[]}>}){const {lang:rawLang,slug}=await params;const lang=rawLang as Lang;const page=parsePage(slug);if(!languages.includes(lang)||!page)notFound();return <SitePage lang={lang} page={page}/>;}
