import type { Metadata } from "next";
import InfoPage from "../ui/InfoPage";

export const metadata: Metadata = { title: "ACBuy Shipping Cost Guide | Estimates, Weight & Packing", description: "Understand consolidation, chargeable weight, packaging, shipping estimates, restrictions, and parcel submission.", alternates: { canonical: "https://acbuys.shop/shipping/" } };

export default function ShippingPage() {
  return <InfoPage canonicalPath="/shipping/" accent="lime" eyebrow="Parcel planning" title="ACBuy shipping costs: compare estimates, weight and packing." intro="International shipping depends on the destination, line, weight, dimensions, restrictions, and packaging choices. A useful guide explains those variables instead of publishing a fake universal price." sections={[
    { kicker: "Estimate", title: "Prepare the shipping calculator inputs", body: <><p>Choose the destination, then enter the weight and dimensions in the units requested by the current estimator. Check the product category and route restrictions before comparing quotes. Use measured warehouse information when available; a pre-purchase estimate is a planning scenario.</p><p>Keep the destination, contents and packaging identical across route comparisons. Record the quote date, billing method, rounding rule and optional charges. A low headline price is not useful if the route excludes part of your parcel.</p><a className="article-link" href="/articles/acbuy-shipping-cost-guide/">Read the complete shipping cost guide ↗</a></> },
    { kicker: "Factor 01", title: "Actual versus volumetric weight", body: <><p>Carriers may charge using actual weight or dimensional weight. Bulky but light products can therefore cost more than their scale weight suggests. Compare both the item weight and packed dimensions when the estimate provides them.</p></> },
    { kicker: "Factor 02", title: "Consolidation", body: <><p>ACBuy’s official guide says combining more products for international shipping can help save shipping costs. Consolidation avoids repeating some base parcel costs, but the final parcel must still match the chosen line’s size, weight, and product restrictions.</p><p>Use the current shipping estimator after the warehouse records actual item data. Pre-purchase estimates are useful for planning, not a final invoice.</p></> },
    { kicker: "Factor 03", title: "Packaging choices", body: <><p>Removing unnecessary packaging can reduce volume, while reinforcement may protect fragile items at the cost of extra size and weight. Decide based on the product: soft clothing and rigid footwear do not need the same packing strategy.</p></> },
    { kicker: "Next step", title: "Rehearsal, submission and tracking", body: <><p>ACBuy’s Shopping Guide describes rehearsal as a paid simulated packaging service. Check the live service terms before requesting it, and compare its results with the final parcel measurements.</p><a className="article-link" href="/articles/acbuy-rehearsal-packing-guide/">Prepare rehearsal packing ↗</a><p>Once a parcel is submitted, follow its international tracking record separately from the seller’s domestic delivery.</p><a className="article-link" href="/articles/acbuy-parcel-tracking-guide/">Understand parcel tracking ↗</a></> },
    { kicker: "Factor 04", title: "Line restrictions and customs", body: <><p>Available routes vary by destination and item type. Read the current line notes for restricted categories, tracking level, compensation terms, declared-value rules, and estimated transit time. Customs decisions are made by local authorities, so no external guide can guarantee clearance or delivery dates.</p></> },
  ]} />;
}
