import Link from "next/link";
import { Arrow, CheckIcon } from "@/components/Icons";
import { CategoryCard } from "@/components/Cards";
import StructuredData from "@/components/StructuredData";
import { categories, SITE_URL } from "../data";
import { languageAlternates } from "../i18n";
import { createPageMetadata } from "../seo";

export const metadata = createPageMetadata({ title: "Hacoo Spreadsheet 2026: Links, Categories & Method", description: "Use a fact-checked independent Hacoo spreadsheet directory for category routes, current product links, sizing, QC and live listing verification.", path: "/spreadsheet", alternates: languageAlternates("/spreadsheet", "en") });

export default function SpreadsheetPage() {
  const spreadsheetFaqs = [["Is this an official Hacoo spreadsheet?","No. Hacoos is an independent directory and editorial guide."],["How often should product links be checked?","Check the live destination every time you use a link because stock, options, images and terms can change."],["Does a spreadsheet verify product quality?","No. It organizes discovery and explains useful checks, but it cannot guarantee a product or transaction."]];
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "WebPage", name: "Hacoo Spreadsheet Guide", url: `${SITE_URL}/spreadsheet/`, description: "Independent guide to Hacoo spreadsheet-style product discovery.", dateModified: "2026-08-26" }, { "@type": "FAQPage", mainEntity: spreadsheetFaqs.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}})) }] };
  return <><StructuredData data={schema}/><section className="page-hero lime-hero"><div className="wrap narrow"><span className="section-label">Hacoo spreadsheet / 2026 guide</span><h1>One index.<br/>Better decisions.</h1><p>Use this hub to move from a broad Hacoo spreadsheet search to the right category, the right checklist and a current external listing.</p><div className="hero-actions"><Link className="button dark" href="/categories">Choose a category <Arrow/></Link><Link className="button quiet-dark" href="/guides/how-to-use-hacoo-spreadsheet">How it works</Link></div></div></section>
    <section className="section wrap"><div className="split-copy"><div><span className="section-label">The short answer</span><h2>What is a Hacoo spreadsheet?</h2></div><div><p className="large-copy">It is a structured product-discovery route: category links, current listing destinations and practical notes collected in one place for easier comparison.</p><p>Hacoos is independent. It does not operate Hacoo, process transactions or guarantee external products. Its job is to reduce noise during research and make the next verification step obvious.</p></div></div></section>
    <section className="soft-section"><div className="wrap"><div className="section-heading compact"><div><span className="section-label">Browse the index</span><h2>Choose a product route.</h2></div><p>Each section uses category-specific checks rather than repeating the same generic shopping advice.</p></div><div className="category-grid">{categories.map((c, i) => <CategoryCard category={c} index={i} key={c.slug}/>)}</div></div></section>
    <section className="section wrap"><div className="section-heading"><div><span className="section-label">Use it responsibly</span><h2>Four checks before<br/>the destination.</h2></div></div><div className="check-grid">{[["Current link","Confirm that the external page still opens and describes the item shown."],["Exact option","Match color, size, version and included items to the option you intend to inspect."],["Useful evidence","Prefer clear measurements and multiple views over a single promotional image."],["Live terms","Read current availability, shipping, returns and destination-specific information."]].map(([h,p])=><div className="check-card" key={h}><CheckIcon size={24}/><h3>{h}</h3><p>{p}</p></div>)}</div></section>
    <section className="dark-section"><div className="wrap process-layout"><div className="process-intro"><span className="section-label inverse">Official platform context</span><h2>Community discovery is not the same as product verification.</h2><p>Hacoo's public website describes the service as an open content-sharing community. Its Terms say posts and recommendations come from independent users and creators, whose content can become inaccurate or outdated.</p><Link className="button light" href="/guides/what-is-a-hacoo-spreadsheet">Read the full definition <Arrow/></Link></div><ol className="process-list"><li><span>01</span><div><h3>Community content</h3><p>Useful for ideas and personal experiences, but it should be matched to the exact current option.</p></div></li><li><span>02</span><div><h3>Official policy</h3><p>Shipping, return and support claims are checked against Hacoo's current public help information.</p></div></li><li><span>03</span><div><h3>Independent index</h3><p>Hacoos organizes routes and methods; it does not claim to be an official Hacoo spreadsheet.</p></div></li></ol></div></section>
    <section className="soft-section"><div className="wrap"><div className="section-heading"><div><span className="section-label">How the directory is maintained</span><h2>Useful dates, not false promises.</h2></div><p>The category and product destinations were checked on August 26, 2026. A successful check confirms that a page opens; it does not freeze its stock or terms.</p></div><div className="research-grid">{[["Route check","We open category and featured product destinations and remove links that no longer resolve."],["Editorial check","We keep measurement, QC and shipping guidance separate from claims that require a live source."],["Visitor check","Before acting, confirm the exact option, current availability and applicable destination terms yourself."]].map(([title,text],index)=><article className="research-card" key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section wrap category-faq"><div><span className="section-label">Spreadsheet FAQ</span><h2>What the index can—and cannot—do.</h2></div><div className="faq-list">{spreadsheetFaqs.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section></>;
}
