import type { Metadata } from "next";
import { notFound } from "next/navigation";
import SiteFooter from "../components/SiteFooter";
import SiteHeader from "../components/SiteHeader";

const MAIN = "https://www.cnfanssp.com";
type InfoPage = { eyebrow: string; title: string; intro: string; color: string; keywords: string[]; blocks: { title: string; text: string }[] };

const pages: Record<string, InfoPage> = {
  spreadsheet: { eyebrow: "Verified product workflow", title: "AllChinaBuy Spreadsheet Guide", intro: "Use a product directory as a discovery tool, then verify every listing before it becomes an order. This page explains a repeatable process for finding, checking and saving useful links.", color: "blue", keywords: ["AllChinaBuy spreadsheet", "AllChinaBuy finds", "AllChinaBuy product links"], blocks: [
    { title: "What an AllChinaBuy spreadsheet can—and cannot—do", text: "A spreadsheet can group product links by category, reduce repetitive searching and make comparisons easier. It cannot confirm that a seller still has stock, that a displayed price applies to your variant or that the unit sent to the warehouse will match every marketing image. AllChinaBuy describes itself as an agent that purchases from third-party Chinese marketplaces; the seller remains the source of the merchandise. Treat the directory as the first filter, not as a quality certificate or permanent product database." },
    { title: "Begin with purchase intent, not popularity", text: "Choose a category and write down the few details that would change your decision. For shoes, these may be size availability, colorway and whether a box matters. For clothing, prioritize the seller's size chart, flat measurements, fabric description and selected color. For accessories, record dimensions, hardware and included pieces. This turns a broad product search into a checklist. Popularity labels are less useful than information you can verify on the current destination listing." },
    { title: "Reopen the live destination page", text: "Open the current product page before saving or ordering. Confirm that the title, main photos, option images and available variants describe the same item you expected. Check whether the lowest displayed price belongs to the relevant option rather than a small accessory or deposit. Listing content, domestic delivery and stock can change without the spreadsheet changing. If a link is unavailable, search by a distinctive product phrase and compare details instead of assuming the first similar result is equivalent." },
    { title: "Use the official workflow as your second check", text: "AllChinaBuy's current public pages describe a three-stage workflow: selection and purchase, quality inspection and storage, then international delivery. The official interface promotes link or keyword shopping across major Chinese marketplaces including Taobao, Tmall and 1688. That separation matters. The product page helps you choose an item; warehouse information helps you examine the received unit; the parcel interface provides the routes and quote available for the shipment you actually create." },
    { title: "Build a dated shortlist", text: "Keep only two or three serious candidates per item. Record the product name, URL, intended variant, key measurement, estimated weight if shown and the date checked. A date makes the record honest: a link verified today may be changed or removed later. Delete dead links instead of preserving a large but unreliable archive. A concise shortlist also reduces wrong-variant mistakes because you can compare option names and seller charts without dozens of nearly identical tabs open." },
    { title: "Review warehouse evidence before parcel submission", text: "AllChinaBuy advertises inspection, photography and storage after the seller's parcel reaches its warehouse. Compare the warehouse record with your saved variant. Check product identity, quantity, color, size label and visible condition. Request clarification when a material detail is not visible. Photographs can reveal a mismatch, but they cannot prove comfort, material feel, authenticity or long-term durability. Resolve a return, exchange or extra-photo question under the current account rules before submitting international delivery." },
    { title: "Keep the sheet useful for future searches", text: "Update high-traffic categories first, mark the last-check date and avoid absolute claims such as “best,” “guaranteed” or “QC approved.” Useful notes describe observable details: available size range, visible construction, packaging choice and the exact page reviewed. For SEO and for readers, a smaller index with working destination links is more valuable than thousands of copied rows. The current listing and the user's own warehouse photos must remain the final decision points." },
  ]},
  finds: { eyebrow: "Curated discovery", title: "AllChinaBuy Product Finds", intro: "A practical way to shortlist shoes, clothing and accessories without confusing a curated link with a verified purchase outcome.", color: "coral", keywords: ["AllChinaBuy finds", "AllChinaBuy products", "AllChinaBuy product search"], blocks: [
    { title: "How products are selected", text: "A useful find should have a working destination page, recognizable product photos, readable options and enough information to compare it with alternatives. We prioritize clear categories and live pages over vague trend claims. Selection does not mean endorsement of the seller or a promise about the unit delivered. AllChinaBuy states that it acts as a shopping agent for products from third-party platforms and does not remove product-quality or intellectual-property risks. Every find therefore needs a second check before purchase." },
    { title: "Shoes: verify size, version and packaging", text: "Start with the size system used on the seller page and look for any insole-length guidance. Compare the option image with the color or version name because translated labels may be ambiguous. Decide before ordering whether the original box matters: keeping it may protect presentation, while removing bulky packaging can change parcel dimensions. When the pair reaches the warehouse, review both shoes together and then inspect the toe area, heels, soles, labels and any visible construction issue." },
    { title: "Hoodies, tees and jackets: measurements beat letter sizes", text: "Do not rely on S, M or L across unrelated sellers. Compare flat measurements from the listing with a garment that already fits. Chest width and length are usually more useful than a generic fit label; sleeve, shoulder, waist or rise may matter by category. Save the intended color and size with the link. At the warehouse, verify the size tag, print placement, closures, visible stains and the general shape before adding the item to an international parcel." },
    { title: "Jerseys and coordinated sets: check every included piece", text: "A product title can describe a full set while one option includes only a top, shorts or an accessory. Read the variant list and option images together. For jerseys, inspect the requested name, number, badge or size only when the seller listing actually offered that customization. For coordinated sets, confirm quantity and color consistency across the pieces. A concise order note can clarify your selection, but it cannot create an option the seller does not offer." },
    { title: "Accessories: small products still need exact dimensions", text: "Bags, hats, belts and other accessories can look larger in close-up photos than they are. Record measurements, material notes, closure type, strap length and included pieces. Inspect visible hardware and attachment points in warehouse photos. Small items may reduce physical parcel weight, but rigid cases or protective packaging can still affect volume. Check route restrictions for electronics, batteries, liquids or magnets rather than assuming every accessory can use the same international line." },
    { title: "Compare two live listings, not two card titles", text: "When two cards look similar, compare the actual destination pages: option range, seller-provided measurements, main-photo consistency, domestic delivery and available evidence. Ignore claims that cannot be verified from the listing or warehouse record. If one page is clearer but slightly more expensive, the extra information may reduce ordering risk. Save the reason for your choice so you can verify the same criteria when the product arrives at the warehouse." },
    { title: "Turn a find into a controlled order", text: "Recheck the listing immediately before payment, select the exact variant and separate the item budget from future international shipping. After arrival, use inspection photos as a decision point rather than automatically submitting a parcel. AllChinaBuy's public workflow places quality inspection and storage between purchase and international delivery for this reason. A product find becomes useful only when the link, selected option, warehouse evidence and parcel choice all refer to the same item." },
  ]},
  guide: { eyebrow: "Beginner workflow", title: "How to Use AllChinaBuy", intro: "A fact-checked walkthrough of the shopping-agent process, from a Chinese marketplace link to warehouse inspection and international parcel submission.", color: "coral", keywords: ["how to use AllChinaBuy", "AllChinaBuy guide", "AllChinaBuy shopping agent"], blocks: [
    { title: "1. Find a product or paste a marketplace link", text: "AllChinaBuy's current public guidance presents the service as a way to shop from major Chinese marketplaces such as Taobao, Tmall and 1688. Start with a product link or a precise keyword. Review the translated title, seller photos, available options and seller-provided size information. The agent helps process the purchase, but the merchandise comes from a third-party seller. Do not order until the option name, photo and price all describe the version you want." },
    { title: "2. Confirm the order and domestic-stage cost", text: "Select the exact color, size, model and quantity. The first payment is associated with purchasing the item and moving it from the Chinese seller to the warehouse; international parcel delivery is handled later. Keep an order note only when it clarifies an available option. Save the destination listing and selected variant because the page may change after payment. The official site lists top-up, international credit card and telegraphic transfer among its payment help topics; use only the methods currently offered in your own account." },
    { title: "3. Follow the seller-to-warehouse status", text: "After purchase, the seller must dispatch the item domestically. AllChinaBuy's Help Center includes order-status tools and states that a shopping-agent order can be urged for delivery after three days. That is not a promise that every seller will dispatch within three days; it describes when an urge action may be available. Watch the order timeline, and use the current account record rather than a community estimate to understand whether the seller has shipped and whether the warehouse has received the parcel." },
    { title: "4. Review quality inspection and photography", text: "The official homepage advertises quality inspection and photography as part of the warehouse stage. Use the images to confirm identity, selected variant, quantity, labels and visible condition. Ask a specific question when a standard image does not show a decision-critical detail. Photographs are evidence, not a guarantee: they cannot establish comfort, fabric feel, authenticity, electronics reliability or future durability. If the received item appears wrong, review the applicable after-sales options before moving it into an international parcel." },
    { title: "5. Use storage time to plan, not to postpone forever", text: "AllChinaBuy currently advertises 90-day free storage on its public pages. Confirm the active policy and the stored-item dates shown in your account before relying on that period. Storage allows purchases from different sellers to arrive before parcel submission, but waiting also gives listings and service windows time to change. Keep a simple arrival record, resolve inspection questions early and build a parcel only from items you have deliberately approved." },
    { title: "6. Compare the routes available for your parcel", text: "Use the official freight calculator as an estimate, then compare the live options shown after warehouse weight and dimensions are available. Destination, physical or volumetric weight, product restrictions, tracking and current route conditions can change the choice. The public interface also lists mail limitations, customs and taxation, receipt information and parcel tracking as separate help topics. Do not copy a friend's route without confirming it accepts your item category and destination." },
    { title: "7. Choose packing and submit international delivery", text: "Decide whether original packaging is necessary, whether items should be split and what level of protection is appropriate. AllChinaBuy's Shipping Expert interface currently asks users to choose between keeping or removing packaging and between lowest freight, fastest delivery or an overall-optimal plan; it also says warehouse handling after a request may take one to three working days. These are planning controls, not guaranteed outcomes. Review the final quote, address, declaration and route notes before payment." },
    { title: "8. Track the parcel and keep evidence", text: "Save the parcel number, selected shipping line, declared value, payment record and warehouse photos. Use official parcel tracking and distinguish a normal tracking gap from a missed route milestone. Customs and last-mile events depend on the destination and are not controlled solely by the shopping agent. If you contact support, provide the order or parcel number and describe the last recorded event clearly. The Help Center currently lists service hours as 09:00–18:00 Beijing time and provides a customer-service email." },
  ]},
  qc: { eyebrow: "Inspection desk", title: "AllChinaBuy QC Photo Checklist", intro: "Use warehouse photographs to answer specific questions before international shipping—without treating photos as proof of everything a product will be.", color: "blue", keywords: ["AllChinaBuy QC", "AllChinaBuy QC photos", "warehouse inspection checklist"], blocks: [
    { title: "Understand what the warehouse stage is for", text: "AllChinaBuy's official homepage places quality inspection and storage between product purchase and international delivery and advertises photography during this stage. That creates a useful decision window: compare the received unit with your order before paying to send it abroad. QC should confirm observable identity and condition. It should not be described as authentication, laboratory testing or a lifetime guarantee. Start with the order record and the seller listing open beside the warehouse images." },
    { title: "Check identity before small cosmetic details", text: "Confirm product type, quantity, color, model and visible size label first. If the seller offered several similar options, compare the exact option image with the warehouse view. A wrong size, wrong color or missing piece usually matters more than a tiny alignment question. Record one issue at a time and cite the relevant photo. This makes an additional-photo or after-sales request easier to understand than a general message such as “please check quality.”" },
    { title: "Inspect the full exterior in a fixed order", text: "Use the widest views to examine overall shape and visible condition, then move from front to back and from left to right. Look for stains, tears, dents, missing parts, damaged packaging, uneven construction or obvious asymmetry. Compare both members of a pair. Lighting, camera angle and compression can change color and proportion, so ask for another angle when a suspected problem appears in only one photograph." },
    { title: "Use a category-specific checklist", text: "For clothing, inspect the size tag, print or embroidery placement, seams, closures and visible marks. For shoes, review the pair together, then the toe area, heels, soles, labels and visible glue or stitching. For bags, check handles, straps, closures, hardware and included pieces. For electronics, a photo can confirm model and visible damage but not long-term operation, battery health or electrical safety. Match the inspection question to the product." },
    { title: "Request measurements when fit changes the decision", text: "A familiar letter size is not a universal measurement. Compare flat garment measurements with something you already own: chest width, length, waist, sleeve or rise as relevant. For footwear, verify the ordered size and use seller-provided insole guidance where available. Ask that the tape and endpoints are visible. Warehouse measurements can vary slightly with placement and fabric tension, so use them as a practical comparison rather than exact laboratory data." },
    { title: "Know what photographs cannot establish", text: "Warehouse images cannot prove fabric hand-feel, odor, comfort, authenticity, water resistance, electronics reliability or durability after repeated use. They also cannot show an issue hidden inside a sealed product unless the service permits opening it. If your purchase depends on a property that cannot be assessed visually, decide whether the remaining uncertainty is acceptable before ordering. Good QC reduces avoidable mismatch risk; it does not remove every product risk." },
    { title: "Resolve a problem before parcel submission", text: "If the item appears wrong or damaged, check the current account deadline and applicable return, exchange or after-sales policy while it remains at the warehouse. Attach the relevant image and describe the mismatch precisely. AllChinaBuy states that it provides after-sales assistance, but eligibility can depend on the seller, platform and product type. Its goods notice specifically warns that some used-item or unverifiable third-party purchases may carry extra fees and may not be eligible for return or exchange." },
    { title: "Keep a QC record with the parcel", text: "Save the order screenshot, selected variant, warehouse photos, measurement images and any support response. Once you approve the item, note that approval date and use the same record when building the parcel. If a later issue arises, evidence is more useful than memory. A trustworthy directory should never label every linked product “QC approved”; inspection belongs to the specific unit received for the specific order." },
  ]},
  shipping: { eyebrow: "Parcel planner", title: "AllChinaBuy Shipping Guide", intro: "Plan around the parcel you actually create: destination, measured weight, dimensions, product restrictions, packing and current route availability.", color: "yellow", keywords: ["AllChinaBuy shipping", "AllChinaBuy shipping calculator", "AllChinaBuy parcel guide"], blocks: [
    { title: "Separate product cost from international shipping", text: "The shopping-agent workflow has two financial stages. First, the item is purchased from a Chinese seller and delivered domestically to the warehouse. Later, approved stored items are combined or separated into an international parcel. A low product price therefore does not reveal the total delivered cost. Budget for the item, domestic-stage charges shown at order time, packing choices, international freight and possible destination taxes as separate components." },
    { title: "Use the official calculator as an estimate", text: "AllChinaBuy provides a freight calculator and describes it as a way to estimate logistics fees. Enter the correct destination and realistic parcel information to compare possible routes before a large order. The final choice can change after the warehouse records the parcel's actual weight and dimensions. Do not publish or trust one universal price per kilogram: base charges, weight steps, volumetric rules, restrictions and route availability can produce different totals for parcels with the same scale weight." },
    { title: "Plan for physical and volumetric weight", text: "Bulky packaging can make a light parcel expensive when a route bills by volume. Shoe boxes, rigid gift packaging and puffy outerwear are common examples. Decide which original packaging protects the product or matters to you and which can be removed. AllChinaBuy's Shipping Expert form currently includes keep-packaging and package-removal choices. Removing packaging is not automatically better; balance reduced dimensions against protection and collector value." },
    { title: "Check mail restrictions for the exact item mix", text: "The official Help Center separates freight estimation from mail limitations because a route can accept one category but reject another. Batteries, liquids, magnets, food, oversized goods and other sensitive products may reduce the available lines. A mixed parcel inherits the restrictions of its most difficult item. Splitting may open more routes, but separate parcels also create separate base charges, declarations and tracking histories. Verify the current route notes at submission." },
    { title: "Compare routes beyond the fastest headline", text: "Review destination coverage, tracking, billing method, product restrictions, compensation or insurance terms and the current estimate. Transit ranges are not delivery guarantees. Flight capacity, handoffs, peak-season volume, customs and last-mile delivery can add time. A route with the shortest displayed estimate may not be the best balance for a valuable, bulky or restricted parcel. Choose using the information available for your parcel rather than a community ranking." },
    { title: "Handle declarations and destination taxes carefully", text: "Customs rules and tax treatment depend on the destination and shipment. AllChinaBuy's public help navigation includes customs and taxation, and the Shipping Expert form notes that some routes may collect value-added tax in advance based on the declared value. Follow the current instructions presented for your route and provide truthful information. Another customer's declaration or customs result is an anecdote, not a safe template or guarantee for your parcel." },
    { title: "Use Shipping Expert for a defined objective", text: "The current Shipping Expert form lets users state whether parcels may be split, whether packaging should be kept and whether the priority is lowest freight, fastest delivery or an overall-optimal plan. It says warehouse specialists may handle the request within one to three working days and distinguishes the service from separate packaging and handling fees. Write a clear objective and still review the resulting plan, address, declaration and payment before authorizing shipment." },
    { title: "Track the parcel and preserve the record", text: "Keep the parcel number, line name, warehouse measurements, packing choice, declared value, quote and payment record. Use the official parcel-tracking tool and compare new events with the route's expected milestones. Tracking can pause between export, customs and last-mile scans. If the shipment exceeds the expected range or records an exception, contact support with the parcel number and exact last event. Insurance or compensation depends on current terms, not on the existence of tracking alone." },
  ]},
  faq: { eyebrow: "Fact-checked answers", title: "AllChinaBuy FAQ", intro: "Clear answers based on AllChinaBuy's current public pages, with changing prices, policies and third-party seller risks kept in view.", color: "green", keywords: ["AllChinaBuy FAQ", "is AllChinaBuy safe", "AllChinaBuy storage", "AllChinaBuy shipping"], blocks: [
    { title: "Is this the official AllChinaBuy website?", text: "No. This is an independent product-discovery and educational site. It does not operate AllChinaBuy accounts, purchase products or control shipping routes. Current orders, policies, balances and parcel actions must be checked in the destination platform. We reviewed AllChinaBuy's public homepage, Help Center, User Guidance, freight calculator, goods notice and Shipping Expert interface on August 26, 2026." },
    { title: "What does AllChinaBuy do?", text: "Its public pages describe a shopping-agent workflow for buying from third-party Chinese marketplaces, receiving items at a warehouse, providing inspection and photography, storing items and arranging international delivery. The homepage names Taobao, Tmall and 1688 among the marketplaces it supports. The agent facilitates the transaction and logistics process; it is not the manufacturer or seller of the merchandise." },
    { title: "Does AllChinaBuy guarantee product quality or authenticity?", text: "No such guarantee should be inferred from a product link or warehouse photo. AllChinaBuy's goods notice says it is not responsible for product risks such as quality issues or intellectual-property infringement, although it describes inspection, communication and after-sales assistance. Photographs can help identify a visible mismatch or defect, but they cannot establish authenticity, material feel, electronics reliability or long-term durability." },
    { title: "How long is free warehouse storage?", text: "AllChinaBuy currently advertises 90-day free storage on its public homepage and freight-calculator page. Policies can change, and stored items may have dates or conditions shown inside the account, so confirm the current rule before relying on the full period. Storage is most useful for waiting for several seller parcels and resolving QC questions before international shipping." },
    { title: "Are purchase and international shipping paid together?", text: "They are separate stages in the public workflow. The product is first ordered from the seller and delivered domestically to the warehouse. After inspection, the user selects stored items, packing and an international route and pays the parcel quote. Product price therefore should not be presented as a delivered total. Destination, weight, dimensions, restrictions and route conditions affect international freight." },
    { title: "Which payment methods are available?", text: "AllChinaBuy's public help navigation currently lists top-up, international credit card and telegraphic transfer, while the main site also displays PayPal in its payment section. Availability, fees, currency conversion and account eligibility may vary. Use only the methods presented in your current account and review the final amount before payment rather than relying on an old tutorial." },
    { title: "What can I check in warehouse QC photos?", text: "Check product identity, selected color and size, quantity, labels, visible condition, missing pieces and category-specific construction. Request a measurement or close-up when it would change your decision. Do not treat a standard photo set as proof of comfort, authenticity, odor, hidden components or durability. Resolve a clear issue while the item remains at the warehouse and under the current after-sales rules." },
    { title: "Can every item be returned or exchanged?", text: "No universal promise is safe. Eligibility can depend on seller policy, marketplace, product condition, timing and service type. AllChinaBuy's goods notice specifically states that purchases from used-item platforms such as Xianyu or unverifiable third-party platforms may involve an extra service fee and may not be eligible for return or exchange. Review the current order-specific terms before payment and act promptly after warehouse inspection." },
    { title: "How do I estimate shipping cost?", text: "Use the official freight calculator with the correct destination and realistic weight, then compare the live parcel options after warehouse measurements are available. Include possible volumetric weight, packing choices and route restrictions. There is no fixed global price per kilogram that safely describes every parcel. The final quote and available lines must come from the current submission interface." },
    { title: "Does a shipping estimate guarantee delivery time?", text: "No. Displayed transit ranges are planning estimates. Export handling, flight capacity, peak seasons, customs and last-mile delivery can cause variation. Compare routes on restrictions, tracking and current terms as well as speed. Keep parcel records and use official tracking. If a parcel records an exception or exceeds its expected range, contact support with the exact parcel number and last event." },
  ]},
};

export function generateStaticParams() {
  return Object.keys(pages).map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params; const page = pages[slug]; if (!page) return {};
  const description = page.intro;
  return {
    title: `${page.title} | AllChinaBuy Finds`,
    description,
    keywords: page.keywords,
    alternates: { canonical: `https://allchinabuys.shop/${slug}/` },
    openGraph: { title: page.title, description, url: `https://allchinabuys.shop/${slug}/`, images: [{url:"/og.png",width:1200,height:630}] },
    twitter: { card:"summary_large_image", title:page.title, description, images:["/og.png"] },
  };
}

export default async function InformationPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const page = pages[slug];
  if (!page) notFound();
  const schema = slug === "faq" ? {"@context":"https://schema.org","@type":"FAQPage","mainEntity":page.blocks.map(b=>({"@type":"Question","name":b.title,"acceptedAnswer":{"@type":"Answer","text":b.text}}))} : {"@context":"https://schema.org","@type":"WebPage","name":page.title,"description":page.intro,"url":`https://allchinabuys.shop/${slug}/`};
  return <main className={`info-page info-${page.color}`}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} />
    <SiteHeader />
    <section className="info-hero"><p className="section-kicker">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p></section>
    <section className="info-body"><aside><span>ON THIS PAGE</span>{page.blocks.map((b, i)=><a href={`#part-${i}`} key={b.title}>{String(i+1).padStart(2,"0")} {b.title}</a>)}</aside><div className="info-blocks">{page.blocks.map((b,i)=><article id={`part-${i}`} key={b.title}><span>{String(i+1).padStart(2,"0")}</span><h2>{b.title}</h2><p>{b.text}</p></article>)}<div className="research-note"><b>Research standard</b><p>Fact-checked against AllChinaBuy's public homepage, Help Center, User Guidance, freight calculator, goods notice and Shipping Expert interface on August 26, 2026. Platform policies, routes and prices can change; confirm them in the current account before acting.</p></div></div></section>
    <section className="info-cta"><div><p className="section-kicker">Continue browsing</p><h2>Use the guide, then check the live listing.</h2></div><a href={`${MAIN}/AllProducts/`} target="_blank" rel="noopener noreferrer">Open product index ↗</a></section>
    <SiteFooter />
  </main>;
}
