import type { Metadata } from "next";
import Link from "next/link";
import { PageShell } from "@/components/PageShell";

export const metadata: Metadata = { title: "AllChinaBuy Spreadsheet FAQ", description: "Fact-checked answers about AllChinaBuy links, supported marketplaces, ordering, QC photos, 90-day storage, payments, shipping estimates and reviews.", alternates: { canonical: "/faq" } };

const faqs = [
  ["Is this an official AllChinaBuy website?", "No. This is an independent discovery and shopping-education website. It does not sell products, process payments or provide an AllChinaBuy account. The corresponding product buttons lead to the live catalog records used for browsing and purchase-platform selection."],
  ["What is an AllChinaBuy spreadsheet?", "It is an organized directory of product records. It can help visitors find categories and source pages faster, but it does not replace the original listing, current price, size chart, warehouse photos or the buyer’s own checks."],
  ["Which shopping platforms does AllChinaBuy support?", "The official homepage says its search accepts product URLs or keywords from Taobao, Tmall, 1688 and JD. A specific listing may still be unavailable, restricted or require manual details, so confirm the current result before paying."],
  ["What happens after I pay for an item?", "AllChinaBuy presents the workflow as selection and purchase, quality inspection and storage, then international delivery. Product payment and international parcel payment are separate stages."],
  ["Does “source checked” mean the product is guaranteed?", "No. It means the preview page and corresponding destination were checked when the record was prepared. Product availability, price, variants and seller information can change afterward."],
  ["Are all products QC approved?", "No. This site deliberately avoids that claim. Warehouse photos are evidence that a buyer can inspect; they are not an automatic certificate of quality. Review the images for your own item and request extra evidence when needed."],
  ["Does AllChinaBuy offer free storage?", "The official homepage advertises 90-day free storage. Confirm the current order-level storage deadline, overdue rules and fees because a return window can expire much earlier than a warehouse storage period."],
  ["What payment methods are listed officially?", "The official help area lists top-up, PayPal, international credit card and telegraphic transfer, and the site footer displays several card and wallet brands. Actual availability, fees and exchange rates can depend on the account, country and transaction."],
  ["Why do product prices sometimes change?", "The source seller can change pricing, variants or availability. A multi-option listing may also show the lowest option price first. Confirm the exact selected option and current amount on the live record."],
  ["How should I choose a clothing size?", "Compare actual garment measurements with an item that fits you. Check that the chart belongs to the selected version. Labels such as S, M or XL are less reliable than chest, length, shoulder, waist and inseam measurements."],
  ["How should I choose a shoe size?", "Use the listing’s current chart and compare foot or insole measurements when possible. Outsole length is not the same as internal fit. Ask for an insole measurement if the listing is unclear."],
  ["Is the shipping calculator the final price?", "No. A calculator provides an estimate based on the entered weight, dimensions, destination and route. The final packed parcel may be charged using actual or volumetric weight, and eligible lines or rates can change."],
  ["What is Shipping Expert?", "It is one of the logistics tools listed by AllChinaBuy, alongside the Shipping Calculator, Parcel Tracking and Customized Logistics. Treat its output as a parcel recommendation or service result and review the route, packed measurements, price and terms before paying."],
  ["Should I remove shoe boxes and retail packaging?", "It can reduce volume, but it can also remove protection. Decide by item. Structured shoes, hats, bags, fragile goods and gifts may justify keeping or replacing protective packaging."],
  ["Can the site guarantee customs clearance?", "No. Import rules, inspections and destination requirements are outside an independent spreadsheet site’s control. Check current restrictions, provide accurate information and use the live route terms for the destination."],
  ["Is AllChinaBuy legit according to customer reviews?", "Public ratings show many successful users and a meaningful group of serious complaints. On August 26, 2026, Trustpilot displayed 4.1 from 214 reviews and the US App Store displayed 4.7 from roughly 1,000 ratings. Ratings change and cannot guarantee an individual order."],
  ["What do negative reviews most often warn about?", "The critical reports reviewed for this site commonly concern shipping price, delivery transparency, documentation or problem resolution. They are individual reports, but they justify saving order evidence, comparing live freight terms and resolving product issues before parcel submission."],
];

export default function FaqPage() {
  const schema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
  return <PageShell><main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><header className="page-hero"><div className="section-shell"><div className="breadcrumbs"><Link href="/">Home</Link> / FAQ</div><p className="eyebrow">Fact-checked August 26, 2026</p><h1>Frequently asked questions</h1><p className="lede">Answers based on the official platform flow and clearly labeled review snapshots—not unsupported guarantees.</p></div></header><section className="section-shell section-block faq-preview"><div><p className="eyebrow">{faqs.length} useful answers</p><h2>Check the limitation as carefully as the link.</h2><Link href="/guides/how-to-use" className="button button-dark">Read the full guide</Link></div><div className="faq-list">{faqs.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}</summary><p>{answer}</p></details>)}</div></section></main></PageShell>;
}
