import type { Metadata } from "next";
import Link from "next/link";
import { PageShell } from "@/components/PageShell";
import { ProductCard } from "@/components/ProductCard";
import { SearchBox } from "@/components/SearchBox";
import { categories, products } from "@/lib/data";

export const metadata: Metadata = { title: { absolute: "AllChinaBuy Product Spreadsheet & Source Records" }, description: "Browse an organized AllChinaBuy spreadsheet with source-checked products, direct catalog links and notes aligned with the official purchase, QC, storage and shipping workflow.", alternates: { canonical: "/spreadsheet" } };

export default function SpreadsheetPage() {
  return <PageShell><main><header className="page-hero"><div className="section-shell"><div className="breadcrumbs"><Link href="/">Home</Link> / Spreadsheet</div><p className="eyebrow">The organized index</p><h1>AllChinaBuy Spreadsheet</h1><p className="lede">Start with a category, search the live product database or open one of the source-checked records below. Every entry opens the matching main-catalog page directly, because price, variants and availability can change.</p><SearchBox compact /></div></header><section className="section-shell section-block"><div className="section-heading"><div><p className="eyebrow">Category routes</p><h2>Browse by what you need to inspect.</h2></div><p>Official AllChinaBuy materials describe a flow from selection and purchase to quality inspection and storage, followed by international delivery. These categories organize discovery; they do not replace the live listing or warehouse evidence.</p></div><div className="category-grid">{categories.map((category) => <article className="category-card" key={category.slug}><span className="category-number">{category.mark}</span><div><h3><Link href={`/categories/${category.slug}`}>{category.name}</Link></h3><p>{category.description}</p></div><a href={category.destination} target="_blank" rel="noopener noreferrer" className="category-arrow" aria-label="Open live category">↗</a></article>)}</div></section><section className="section-shell index-facts"><div><span>Official workflow</span><b>Purchase → QC &amp; storage → international delivery</b></div><div><span>Published storage</span><b>90-day free storage</b></div><div><span>Source coverage</span><b>Taobao · Tmall · 1688 · JD</b></div></section><section className="section-shell section-block products-section"><div className="section-heading align-end"><div><p className="eyebrow">Checked records</p><h2>Open the matching product pages.</h2></div><Link href="/finds" className="button button-outline">All finds</Link></div><div className="product-grid">{products.map((product) => <ProductCard key={product.slug} product={product} />)}</div></section></main></PageShell>;
}
