import type { Metadata } from "next";
import Link from "next/link";
import { EditorialPage } from "../../components/EditorialPage";

const canonical = "/articles/qc-evidence-freshness-source-record-review-dates/";

export const metadata: Metadata = {
  title: "QC Evidence Freshness Record: Source and Review Dates | FindQCs",
  description: "Build a QC evidence freshness record that separates listing capture, inspection, access and review dates without inventing a universal expiry rule.",
  keywords: ["QC evidence freshness record", "QC source date log", "QC record review date", "inspection evidence age"],
  alternates: { canonical },
  robots: { index: true, follow: true },
  openGraph: { type: "article", title: "Record Source Date, QC Record Date and Evidence Freshness", description: "A dated method for preserving what was available, when it was captured and when it was last reviewed.", url: canonical, images: ["/og.png"], publishedTime: "2026-09-01", modifiedTime: "2026-09-01" },
  twitter: { card: "summary_large_image", title: "Build a QC Evidence Freshness Record", description: "Separate listing, inspection, access and review dates before comparing evidence.", images: ["/og.png"] },
};

export default function EvidenceFreshnessRecord() {
  const articleSchema = { "@context":"https://schema.org", "@type":"Article", headline:"Record Source Date, QC Record Date and Evidence Freshness", description:"A practical dated record for reviewing already-found listing and QC material without treating age as a universal pass or fail rule.", image:"https://findqcs.net/og.png", datePublished:"2026-09-01", dateModified:"2026-09-01", inLanguage:"en", author:{"@type":"Organization",name:"FindQCs",url:"https://findqcs.net/"}, publisher:{"@type":"Organization",name:"FindQCs",logo:{"@type":"ImageObject",url:"https://findqcs.net/findqc-logo.png"}}, mainEntityOfPage:{"@type":"WebPage","@id":"https://findqcs.net/articles/qc-evidence-freshness-source-record-review-dates/"}, keywords:"QC evidence freshness record, QC source date log, QC record review date, inspection evidence age" };
  const breadcrumbSchema = { "@context":"https://schema.org", "@type":"BreadcrumbList", itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://findqcs.net/"},{"@type":"ListItem",position:2,name:"Articles",item:"https://findqcs.net/articles/"},{"@type":"ListItem",position:3,name:"Evidence Freshness Record",item:"https://findqcs.net/articles/qc-evidence-freshness-source-record-review-dates/"}] };

  return <EditorialPage eyebrow="EVIDENCE FRESHNESS / 11 MIN READ" title="Record source date, QC record date and evidence freshness." intro="Freshness is not one timestamp. An auditable QC record preserves when the listing was captured, when the unit was inspected, when the material was accessed and when a reviewer last checked whether the evidence still answers the current question." breadcrumbs={[["Articles","/articles/"],["Evidence Freshness Record",canonical]]}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}} />
    <div className="article-layout"><aside className="toc"><strong>ON THIS PAGE</strong><a href="#dates">1. Four dates</a><a href="#header">2. Dated header</a><a href="#events">3. Event timeline</a><a href="#risk">4. Relevance risk</a><a href="#changes">5. Listing changes</a><a href="#review">6. Review protocol</a><a href="#handoff">7. Handoff note</a><a href="#audit">8. Final audit</a></aside>
      <div className="prose">
        <p className="lead">A screenshot saved today may show a listing from last month. A QC gallery opened today may contain photos taken much earlier. A review written today may rely on a record that has since been replaced. Storing only “checked today” hides those differences and makes later verification unnecessarily difficult.</p>
        <p>This QC evidence freshness record applies to already-found listing and inspection material. FindQC can surface research records and product intelligence where available, but it does not place orders, operate a warehouse, photograph the buyer’s unit or execute a return. Those actions belong to the buyer-selected agent. The record’s purpose is narrower: preserve dated evidence so another person can reproduce the reasoning and identify what must be checked on the current unit.</p>

        <h2 id="dates">1. Separate four dates instead of using one “freshness” field</h2>
        <p>Start with four distinct timestamps. The <strong>source date</strong> is when the listing, option menu or policy statement was captured. The <strong>record date</strong> is when the QC photos, measurement or video were produced, if that date is shown. The <strong>access date</strong> is when the reviewer opened or downloaded the material. The <strong>review date</strong> is when someone last checked its relevance to the present decision.</p>
        <p>These dates answer different questions. Source date establishes what the seller page stated at that moment. Record date locates the observed sample in time. Access date proves when the reviewer actually obtained the file. Review date shows when the relationship between evidence and current target was reconsidered. Never substitute one for another. If the record date is not displayed, write “not shown”; do not convert the access date into an assumed inspection date.</p>
        <div className="check-block"><strong>DATE FIELDS</strong><ul><li>Source capture: timestamp and time zone when practical</li><li>QC production: displayed date, or “not shown”</li><li>Access: when the file or page was retrieved</li><li>Review: when relevance was last assessed</li><li>Effective period: only when the source explicitly provides one</li><li>Private file reference: stable name, not personal account data</li></ul></div>

        <h2 id="header">2. Build a dated evidence header before recording observations</h2>
        <p>Give every source a short stable ID, then capture source type, exact URL or internal record reference, item and seller identity when shown, variant fields, and all available dates. Add the reviewer’s current decision target beside it. This prevents a record about a black size M sample from quietly becoming evidence for a navy size L target merely because the product title looks similar.</p>
        <p>Preserve time zones when they affect ordering. A date-only label may be enough for a historical gallery; a rapidly changing option or price may need a timestamp. Use an ISO-style value such as 2026-09-01 14:20 +08:00 for sortable private records. The public-facing handoff can stay readable, but the archive should make event order unambiguous.</p>
        <div className="check-block"><strong>HEADER EXAMPLE</strong><ul><li>Source ID: LISTING-A-20260901</li><li>Target: navy / size L / one unit</li><li>Listing captured: 2026-09-01 14:20 +08:00</li><li>QC record date: 2026-08-12, as displayed</li><li>Accessed: 2026-09-01</li><li>Last reviewed: 2026-09-01</li><li>Open issue: photographed size label not visible</li></ul></div>

        <h2 id="events">3. Use an append-only event timeline</h2>
        <p>Freshness changes because the world changes. A listing redirects, an option disappears, a seller edits the title, a new QC set appears, or a measurement becomes available. Record those events as new lines rather than overwriting the earlier snapshot. An append-only timeline lets a reviewer see what was known at each decision point and prevents later information from being mistaken for evidence that existed earlier.</p>
        <p>Each event needs date, source, observed change and effect on the record. Keep observation separate from inference. “Red option no longer visible in menu” is an observation. “Seller permanently discontinued red” is an inference unless the source says so. Likewise, “new QC set dated August 29” does not prove it belongs to the same batch or exact option; it only adds a dated sample whose identity must still be mapped.</p>
        <div className="check-block"><strong>EVENT STATES</strong><ul><li>Added: a new source or QC record appeared</li><li>Changed: a field differs from the preserved snapshot</li><li>Redirected: the saved URL now resolves elsewhere</li><li>Unavailable: the page or option cannot currently be reached</li><li>Unverified: access failed or the required field is not shown</li><li>Superseded for this decision: newer exact-target evidence is available</li></ul></div>

        <h2 id="risk">4. Judge relevance risk, not age alone</h2>
        <p>No universal number of days makes QC evidence valid or invalid. Age matters through the field being decided. A historical construction photo may still help define which seams deserve inspection. The same photo may be weak evidence for current color, packaging, included parts or an active listing option. A recent image can also be unusable when identity is uncertain or a critical angle is missing.</p>
        <p>Rate freshness risk by combining identity, volatility and coverage. Identity asks whether item, seller and required variant fields match. Volatility asks how likely the relevant field is to change: price and availability can move quickly, while a photographed stitching location may be more stable but still sample-specific. Coverage asks whether the evidence actually shows the field. This produces a reasoned note instead of an arbitrary expiration label.</p>
        <div className="check-block"><strong>RELEVANCE STATES</strong><ul><li>Current enough: exact target and required field recently rechecked</li><li>Historical context: useful for planning, not proof of the current unit</li><li>Needs refresh: a material field may have changed</li><li>Identity-limited: date is known but option match is incomplete</li><li>Coverage-limited: recent evidence omits the needed view</li><li>Not transferable: a required identity field conflicts</li></ul></div>

        <h2 id="changes">5. Preserve listing changes without rewriting history</h2>
        <p>When a current page differs from a saved record, capture the new state as a second source. Compare URL, item ID, seller, title, thumbnail, option labels, quantity, price state and availability. Do not edit the old row to look current. The earlier record may accurately explain an older QC set even when it no longer supports today’s purchase target.</p>
        <p>Write the effect at field level. A price change may require a budget recheck but leave construction context intact. A changed model code can invalidate transfer of most product-specific observations. A removed bundle option can make included-parts evidence irrelevant. A redirect with unchanged visible identity remains a re-verification task, not automatic proof of continuity.</p>
        <div className="check-block"><strong>CHANGE NOTE</strong><ul><li>Previous value and its capture date</li><li>Current value and its capture date</li><li>Directly observed difference</li><li>Required field affected</li><li>Evidence that remains contextual</li><li>Evidence that must be refreshed</li></ul></div>

        <h2 id="review">6. Run a review protocol before comparison</h2>
        <p>Before comparing records, confirm that each has a dated source, an honest record-date state and a current review date. Reopen the target listing when possible. Recheck the exact variant fields. Confirm that images still load and that the saved record has not been silently replaced. Then state the comparison question: measurement, surface defect, alignment, included parts or another visible field.</p>
        <p>For every observation, add an “as of” clause and an allowed-use note. For example: “As of September 1, the August 12 size-L record shows the front measurement angle, but the tape endpoint is partly cropped; use it only to identify the extra measurement needed.” This is more precise than calling the record fresh or stale as a whole.</p>
        <div className="check-block"><strong>REVIEW ORDER</strong><ul><li>Confirm exact decision target</li><li>Verify source identity and capture date</li><li>Record QC date as displayed or unknown</li><li>Recheck required option fields</li><li>Test access and note replacements</li><li>Assess relevance per observation</li><li>Set the next review trigger</li></ul></div>

        <h2 id="handoff">7. Turn freshness gaps into a concise dated handoff note</h2>
        <p>A useful handoff contains the target, latest verified source state, historical evidence being relied upon, specific uncertainty and requested current-unit confirmation. Avoid sending an unlabeled folder of screenshots. The selected agent should not have to infer which image is historical or which option the buyer intends.</p>
        <p>Example: “Target is navy, size L, one unit. Listing option captured September 1. Available QC record is dated August 12 and matches item and color, but its size label is not visible. Treat its construction views as historical context only. Please confirm the size label and provide the currently available measurement for this unit.” The agent determines which action is available under its own service terms; the dated record does not promise a photo, exchange or return.</p>

        <h2 id="audit">8. Audit the packet and set a review trigger</h2>
        <p>Finish by asking whether another reviewer can reconstruct the chronology without private chats. Every source should have an ID, date state, exact target relationship and permitted use. Every change should be appended. Every unknown should remain explicit. Remove account names, order numbers, addresses and payment data from any shared version.</p>
        <div className="check-block"><strong>FINAL AUDIT</strong><ul><li>Source, record, access and review dates are separate</li><li>Unknown dates are not inferred</li><li>Earlier snapshots remain intact</li><li>Changes are recorded at field level</li><li>Freshness is assessed per decision question</li><li>Historical context is not called current-unit proof</li><li>Next review has a trigger, not an invented expiry period</li><li>Agent responsibilities remain correctly attributed</li></ul></div>
        <p>A good trigger is concrete: before checkout, after an option change, when a new QC set appears, or immediately before the evidence is handed to the selected agent. The result is not a claim that old material is useless. It is a transparent record of when each source existed, what it can still support and what must be rechecked.</p>
        <Link className="article-cta" href="/articles/record-variant-color-size-quantity-before-comparison/">Confirm the exact variant before dating its evidence <span>→</span></Link>
      </div>
    </div>
  </EditorialPage>;
}
