import type { Locale } from "./site-data";
import type { Article } from "./article-content";

export const readinessKey = "articles/hacoo-uk-pre-order-readiness-sheet" as const;

const en: Article = {
  minutes: 10,
  sections: [
    {
      heading: "A readiness sheet starts with the real UK use case",
      paragraphs: [
        "A Hacoo UK pre-order checklist should begin before a product page feels urgent. Write one sentence describing the job the item must do: for example, a light layer for an October city break, everyday trainers for a commute, or a dress for an event with a fixed date. Add the latest acceptable arrival date and the features that are genuinely non-negotiable. This brief turns an attractive find into a decision that can be tested. It also gives you a rational reason to pause when the listing, size evidence or timing does not support the intended use.",
        "Hacoo describes its service as a lifestyle discovery and shopping community, so inspiration and transaction context can appear close together. That does not remove the need for a buyer-side record. This independent guide does not process an order or guarantee a seller, product or delivery. Its job is to help a UK user capture the region, address, exact option, measurements, timing and evidence that were visible before acting. Keep the sheet beside the current product page rather than treating an old post or screenshot as the controlling source.",
      ],
    },
    {
      heading: "Gate one: confirm region and destination before comparing products",
      paragraphs: [
        "Record the country shown in the app or page and the actual delivery country as United Kingdom. A shared find may have been created in another region, on another app version or under a different destination. If the visible selection, price or availability differs, that difference is a reason to recheck context, not evidence that either view is universally correct. Use the real destination and current official app. Do not use a false address or borrowed account to force a view that cannot support the eventual order.",
        "Your first row should contain check date, app or page context, delivery country and the exact source you opened. If a product becomes unavailable after you saved it, keep the old record as history and treat any replacement as a new candidate. Similar photos do not prove the same seller, batch, material, measurements or option set. This region gate prevents a common planning error: spending time on fit and styling before confirming that the candidate is visible in the context where the decision will actually be made.",
      ],
    },
    {
      heading: "Gate two: make the UK address delivery-ready",
      paragraphs: [
        "Copy the delivery name exactly as the recipient can use it, then check house or flat number, street, town or city, postcode and country. Add a reachable phone number only in the form requested at checkout. For flats, offices, student halls or buildings with reception, record the unit, company or hall name and any field that the current form provides for delivery detail. Do not place sensitive address data in a public spreadsheet, shared screenshot or review; the readiness sheet should remain private.",
        "Run a second-person or read-back check: say the address line by line and compare it with a recent trusted document or a delivery that arrived successfully. Autofill deserves special attention because it can retain an old postcode or remove a flat number. The final checkout summary, not the draft in your sheet, controls what you submit. If any required field is unclear, pause before payment and use the official support path. Correcting ambiguity before ordering is more reliable than assuming a courier can infer a missing unit later.",
      ],
    },
    {
      heading: "Gate three: freeze the exact product and size evidence",
      paragraphs: [
        "Save the current title, first image, selected colour, selected size or bundle, displayed price, product or content identifier where available, and the check date. Then separate label from measurement. A familiar UK size or an S, M or L is only a label; it does not establish chest width, rise, inseam, garment length or insole length. Compare the listing measurements with a similar item that already fits, measured with the same endpoints and without stretching the fabric.",
        "Write down the limiting measurement for the use case. A jacket may fail because its chest does not allow the planned knitwear layer even when sleeve length looks right. Trousers may fail on rise or thigh while the waist seems acceptable. Shoes can match a nominal size yet differ in insole length, width or toe shape. When a necessary measurement is missing, mark it as unknown. Do not convert missing information into a confident fit prediction, and do not treat a creator's appearance or a single review as a personal sizing guarantee.",
      ],
    },
    {
      heading: "Gate four: build timing backwards from the need date",
      paragraphs: [
        "Hacoo's official shipping information listed a 15–25 day receiving estimate for the United Kingdom when checked on 29 August 2026. Treat that range as planning context, not a delivery promise. The same official guidance separates processing from shipping and warns that preorders or backorders can lead to separate dispatches. A status estimate can change, and a split order means one item arriving does not prove that every item is moving on the same timeline.",
        "Work backwards from the date the item must be usable. Reserve time for processing, transit, final-mile delivery, trying the item on and responding if it is unsuitable. A calculation is useful even though it cannot predict the outcome: need date minus your evidence-based buffer equals the latest sensible action date. If that date has passed, choose a candidate that is not deadline-dependent or buy through a route whose current terms fit the deadline. Never compress an estimated range into a guaranteed arrival day simply because an event matters.",
      ],
    },
    {
      heading: "Gate five: preserve a small, useful evidence pack",
      paragraphs: [
        "Before acting, capture the exact option page, measurement chart, delivery estimate shown for the real destination and final order summary. Record the time and keep the original files rather than only a cropped collage. After ordering, add confirmation, status changes and delivery evidence to the same private folder. Do not publish an order number, address, payment information, tracking code, chat transcript or another person's identity. The goal is a compact record that helps you reconstruct what was selected, not a public diary.",
        "Evidence has levels. An official policy states the platform's published rule at a date. A current order screen records what was shown in one transaction context. A creator post or public review is an individual report. Your own comparison is editorial analysis. Label these separately. A screenshot can show wording or an option at a moment, but it cannot prove future stock, product authenticity, material performance or delivery. This distinction keeps the sheet useful without turning ordinary observations into unsupported guarantees.",
      ],
    },
    {
      heading: "Use a five-column go, pause or reject decision",
      paragraphs: [
        "Create five columns: use case, region and address, option and measurements, timing, and evidence. Give each column one of three results. Go means the necessary information is present and supports the brief. Pause means a resolvable gap remains, such as a missing inseam or an unclear flat number. Reject means the candidate conflicts with a non-negotiable need, such as a deadline outside the realistic planning buffer or a measurement below the required minimum. Do not average a reject into a pass because the image is appealing.",
        "For example, a coat may score well for colour and price but remain a pause if the listing lacks chest width and the plan requires layering. A pair of shoes can pass measurements yet be rejected for a fixed event when the available estimate leaves no sensible try-on buffer. A no-buy result is a successful use of the sheet: it has prevented an avoidable mismatch. If two candidates pass, compare only the factors that matter to the original brief instead of inventing a broad 'best Hacoo item' ranking.",
      ],
      bullets: ["Use case", "Region and address", "Option and measurements", "Timing buffer", "Evidence quality"],
    },
    {
      heading: "The two-minute final review",
      paragraphs: [
        "Immediately before payment, reopen the live page and verify the five gates again. Confirm United Kingdom as the true destination, read the full delivery address, select the intended colour and size, compare the displayed measurement information, and inspect the current timing language. Check the final price and terms where the transaction occurs. If the page has changed since your saved record, update the sheet and reconsider the decision; do not assume the earlier state still applies.",
        "Finish by writing one sentence: 'I am choosing this candidate because it meets this wardrobe need, these measurements and this timing condition.' If the sentence depends on an unverified promise, stop. The best Hacoo UK pre-order readiness sheet is deliberately modest. It cannot guarantee fit, quality, authenticity or arrival, but it can expose missing information, protect private evidence and make the final choice traceable to the needs you defined before browsing.",
      ],
    },
  ],
  takeaways: ["Define the UK use case and deadline first.", "Check the real region and complete address privately.", "Save the exact option and compare measurements, not labels.", "Treat 15–25 days as an official UK estimate, never a promise.", "Use go, pause or reject; a no-buy result can be correct."],
};

const translated: Record<Exclude<Locale, "en">, Article> = {
  de: { minutes: 10, sections: [
    { heading: "Mit dem echten UK-Einsatzzweck beginnen", paragraphs: ["Beschreibe in einem Satz, wofür der Artikel gebraucht wird, nenne den spätesten Ankunftstermin und unverzichtbare Eigenschaften. So wird aus Inspiration eine prüfbare Entscheidung.", "Hacoo beschreibt sich als Lifestyle-, Entdeckungs- und Shopping-Community. Dieses unabhängige Blatt verarbeitet keine Bestellung und garantiert weder Anbieter noch Produkt oder Lieferung; es hält Region, Adresse, Option, Maße, Zeit und Belege fest."] },
    { heading: "Tor 1: Region und Ziel prüfen", paragraphs: ["Notiere die angezeigte Region und das echte Lieferland Vereinigtes Königreich. Geteilte Funde können aus einer anderen Region oder App-Version stammen; nutze keine falsche Adresse, um eine Ansicht zu erzwingen.", "Speichere Prüfdatum, Kontext und genaue Quelle. Ein Ersatz mit ähnlichem Foto ist ein neuer Kandidat und beweist nicht denselben Verkäufer, dieselbe Charge oder dieselben Maße."] },
    { heading: "Tor 2: die UK-Adresse zustellbar machen", paragraphs: ["Prüfe Empfängername, Haus- oder Wohnungsnummer, Straße, Ort, Postleitzahl und Land. Bei Wohnheim, Büro oder Empfang ergänze nur die vorgesehenen Felder; halte Daten privat.", "Lies jede Zeile gegen eine verlässliche Quelle zurück und kontrolliere Autofill. Die finale Bestellübersicht zählt; bei unklaren Pflichtfeldern vor Zahlung pausieren."] },
    { heading: "Tor 3: Option und Größenbelege einfrieren", paragraphs: ["Speichere Titel, erstes Bild, Farbe, Größe oder Bundle, Preis, Kennung und Datum. Vergleiche Maße mit einem passenden eigenen Artikel; Buchstaben oder UK-Größen sind nur Etiketten.", "Notiere das begrenzende Maß: etwa Brustweite zum Layering, Leibhöhe, Oberschenkel, Einlegesohlenlänge oder Breite. Fehlende Maße bleiben unbekannt; Creator-Fotos sind keine Passformgarantie."] },
    { heading: "Tor 4: vom Bedarfstermin rückwärts planen", paragraphs: ["Die offizielle Versandseite nannte am 29. August 2026 für das Vereinigte Königreich 15–25 Tage als Empfangsschätzung. Das ist keine Garantie; Bearbeitung und Versand sind getrennt, Vor- oder Nachbestellungen können geteilt werden.", "Plane Puffer für Bearbeitung, Transport, Zustellung, Anprobe und Reaktion ein. Ist der späteste sinnvolle Aktionstag vorbei, wähle keine terminkritische Option."] },
    { heading: "Tor 5: ein kleines Belegpaket", paragraphs: ["Sichere genaue Option, Maßtabelle, Zielschätzung und Bestellübersicht mit Zeitstempel. Ergänze später Bestätigung und Status, veröffentliche aber nie Adresse, Zahlung, Tracking oder Chatdaten.", "Trenne offizielle Regel, transaktionsbezogene Anzeige, Nutzerbericht und eigene Analyse. Ein Screenshot belegt einen Moment, nicht künftigen Bestand, Echtheit, Leistung oder Lieferung."] },
    { heading: "Go, Pause oder Ablehnen in fünf Spalten", paragraphs: ["Bewerte Einsatzzweck, Region/Adresse, Option/Maße, Zeit und Belege. Go = ausreichend, Pause = lösbare Lücke, Ablehnen = Konflikt mit einer Muss-Anforderung.", "Ein Mantel ohne Brustweite bleibt trotz guter Farbe Pause; ein passender Schuh kann bei fehlendem Termin-Puffer abgelehnt werden. Ein Nichtkauf ist ein gültiges Ergebnis."], bullets: ["Einsatzzweck", "Region und Adresse", "Option und Maße", "Zeitpuffer", "Belegqualität"] },
    { heading: "Der Zwei-Minuten-Endcheck", paragraphs: ["Öffne die aktuelle Seite erneut: echtes UK-Ziel, vollständige Adresse, Farbe, Größe, Maße, Zeitangabe, Preis und Bedingungen. Bei Änderungen Blatt aktualisieren und neu entscheiden.", "Formuliere den Grund für die Wahl in einem Satz. Beruht er auf einem unbelegten Versprechen, stoppen. Das Blatt garantiert nichts, macht Lücken und Entscheidung aber nachvollziehbar."] },
  ], takeaways: ["Einsatzzweck und Termin zuerst.", "Echte Region und private Adresse prüfen.", "Maße statt Etiketten vergleichen.", "15–25 Tage nur als UK-Schätzung behandeln.", "Go, Pause oder Ablehnen nutzen."] },
  fr: { minutes: 10, sections: [
    { heading: "Commencer par le besoin réel au Royaume-Uni", paragraphs: ["Décrivez en une phrase l'usage, la dernière date acceptable et les critères indispensables. L'inspiration devient ainsi une décision testable.", "Hacoo se présente comme un écosystème de découverte lifestyle et d'achat. Cette fiche indépendante ne traite aucune commande et ne garantit ni vendeur, ni produit, ni livraison; elle consigne région, adresse, option, mesures, délai et preuves."] },
    { heading: "Porte 1 : confirmer région et destination", paragraphs: ["Notez la région affichée et le vrai pays de livraison, Royaume-Uni. Un partage peut venir d'une autre région ou version; n'utilisez pas une fausse adresse pour forcer une vue.", "Enregistrez date, contexte et source exacte. Une fiche de remplacement, même ressemblante, est un nouveau candidat et ne prouve pas vendeur, lot ou mesures identiques."] },
    { heading: "Porte 2 : rendre l'adresse UK livrable", paragraphs: ["Vérifiez nom, numéro de maison ou appartement, rue, ville, code postal et pays. Pour résidence ou réception, remplissez uniquement les champs prévus et gardez ces données privées.", "Relisez chaque ligne avec une source fiable et contrôlez le remplissage automatique. Le récapitulatif final fait foi; si un champ reste ambigu, mettez en pause avant paiement."] },
    { heading: "Porte 3 : figer option et preuves de taille", paragraphs: ["Sauvez titre, première image, couleur, taille ou lot, prix, identifiant et date. Comparez les mesures avec un vêtement qui va bien; une taille UK ou une lettre reste une étiquette.", "Notez la mesure limitante: poitrine pour superposition, hauteur, cuisse, semelle ou largeur. Une mesure absente reste inconnue; une photo de créateur n'est pas une garantie de coupe."] },
    { heading: "Porte 4 : planifier à rebours", paragraphs: ["La page officielle indiquait le 29 août 2026 une estimation de réception de 15–25 jours au Royaume-Uni. Ce n'est pas une promesse; traitement et expédition sont distincts, et précommandes ou réassorts peuvent être séparés.", "Gardez une marge pour traitement, transit, dernier kilomètre, essayage et réaction. Si la dernière date raisonnable est passée, évitez un candidat dépendant d'une échéance."] },
    { heading: "Porte 5 : conserver un petit dossier de preuves", paragraphs: ["Capturez option exacte, tableau de mesures, estimation pour la destination et récapitulatif daté. Ajoutez confirmation et statuts, sans jamais publier adresse, paiement, suivi ou conversations.", "Distinguez politique officielle, écran de transaction, témoignage public et analyse éditoriale. Une capture prouve un affichage à un instant, pas stock futur, authenticité, performance ou livraison."] },
    { heading: "Décider en cinq colonnes", paragraphs: ["Évaluez usage, région/adresse, option/mesures, délai et preuves: OK si suffisant, Pause si une lacune peut être résolue, Rejet si une exigence essentielle est contredite.", "Un manteau sans largeur poitrine reste en pause; une chaussure bien mesurée peut être rejetée sans marge avant un événement. Ne pas acheter est un résultat utile."], bullets: ["Usage", "Région et adresse", "Option et mesures", "Marge de délai", "Qualité des preuves"] },
    { heading: "La revue finale de deux minutes", paragraphs: ["Rouvrez la page: vraie destination UK, adresse complète, couleur, taille, mesures, délai, prix et conditions. Si l'état a changé, mettez la fiche à jour et redécidez.", "Expliquez le choix en une phrase. S'il dépend d'une promesse non vérifiée, arrêtez. La fiche ne garantit rien mais rend visibles les lacunes et la logique."] },
  ], takeaways: ["Besoin et date d'abord.", "Vérifier région réelle et adresse privée.", "Comparer les mesures, pas les étiquettes.", "Traiter 15–25 jours comme estimation UK.", "Choisir OK, Pause ou Rejet."] },
  es: { minutes: 10, sections: [
    { heading: "Empieza por la necesidad real en Reino Unido", paragraphs: ["Define en una frase el uso, la última fecha aceptable y los requisitos imprescindibles. Así la inspiración se convierte en una decisión comprobable.", "Hacoo se describe como ecosistema de descubrimiento lifestyle y compras. Esta hoja independiente no procesa pedidos ni garantiza vendedor, producto o entrega; registra región, dirección, opción, medidas, tiempo y pruebas."] },
    { heading: "Puerta 1: confirma región y destino", paragraphs: ["Anota la región mostrada y el país real, Reino Unido. Un hallazgo compartido puede proceder de otra región o versión; no uses una dirección falsa para forzar una vista.", "Guarda fecha, contexto y fuente exacta. Un reemplazo parecido es un candidato nuevo y no demuestra mismo vendedor, lote, material o medidas."] },
    { heading: "Puerta 2: prepara la dirección UK", paragraphs: ["Revisa nombre, número de casa o piso, calle, ciudad, código postal y país. En residencias u oficinas usa los campos previstos y mantén los datos en privado.", "Lee cada línea contra una fuente fiable y revisa el autocompletado. El resumen final manda; si un campo obligatorio es ambiguo, pausa antes de pagar."] },
    { heading: "Puerta 3: fija opción y pruebas de talla", paragraphs: ["Guarda título, primera imagen, color, talla o lote, precio, identificador y fecha. Compara medidas con una prenda que ya te queda bien; una talla UK o letra solo es etiqueta.", "Anota la medida limitante: pecho para capas, tiro, muslo, plantilla o anchura. Una medida ausente sigue desconocida; la imagen de un creador no garantiza ajuste."] },
    { heading: "Puerta 4: planifica hacia atrás", paragraphs: ["La página oficial indicaba el 29 de agosto de 2026 una estimación de 15–25 días para Reino Unido. No es promesa; procesamiento y envío son etapas distintas, y preórdenes o reposiciones pueden dividirse.", "Reserva margen para procesamiento, tránsito, última milla, prueba y reacción. Si ya pasó la última fecha sensata, no elijas una opción dependiente del plazo."] },
    { heading: "Puerta 5: conserva un paquete pequeño de pruebas", paragraphs: ["Captura opción exacta, tabla de medidas, estimación del destino y resumen final con fecha. Añade confirmación y estados sin publicar dirección, pago, seguimiento o chats.", "Separa política oficial, pantalla de transacción, informe de usuario y análisis propio. Una captura prueba un momento, no stock futuro, autenticidad, rendimiento o entrega."] },
    { heading: "Decide en cinco columnas", paragraphs: ["Evalúa uso, región/dirección, opción/medidas, tiempo y pruebas: Adelante si basta, Pausa si falta algo resoluble, Rechazo si contradice una necesidad esencial.", "Un abrigo sin ancho de pecho queda en pausa; un zapato puede encajar y rechazarse sin margen para un evento. No comprar también es un buen resultado."], bullets: ["Uso", "Región y dirección", "Opción y medidas", "Margen temporal", "Calidad de pruebas"] },
    { heading: "Revisión final de dos minutos", paragraphs: ["Reabre la página: destino UK real, dirección completa, color, talla, medidas, plazo, precio y condiciones. Si cambió, actualiza la hoja y vuelve a decidir.", "Explica la elección en una frase. Si depende de una promesa no verificada, detente. La hoja no garantiza nada, pero hace visibles los huecos y la lógica."] },
  ], takeaways: ["Uso y fecha primero.", "Revisa región real y dirección privada.", "Compara medidas, no etiquetas.", "Trata 15–25 días como estimación UK.", "Usa Adelante, Pausa o Rechazo."] },
  it: { minutes: 10, sections: [
    { heading: "Partire dall'esigenza reale nel Regno Unito", paragraphs: ["Descrivi in una frase uso, ultima data accettabile e requisiti indispensabili. L'ispirazione diventa così una decisione verificabile.", "Hacoo si descrive come ecosistema lifestyle di scoperta e acquisto. Questo foglio indipendente non gestisce ordini e non garantisce venditore, prodotto o consegna; registra regione, indirizzo, opzione, misure, tempo e prove."] },
    { heading: "Fase 1: confermare regione e destinazione", paragraphs: ["Annota la regione mostrata e il vero paese di consegna, Regno Unito. Un contenuto condiviso può provenire da altra regione o versione; non usare un indirizzo falso per forzare la vista.", "Salva data, contesto e fonte precisa. Una scheda sostitutiva simile è un nuovo candidato e non prova stesso venditore, lotto, materiale o misure."] },
    { heading: "Fase 2: rendere pronto l'indirizzo UK", paragraphs: ["Controlla nome, numero civico o appartamento, strada, città, postcode e paese. Per residence o uffici usa solo i campi previsti e mantieni privati i dati.", "Rileggi ogni riga con una fonte affidabile e verifica l'autocompilazione. Conta il riepilogo finale; se un campo è ambiguo, fermati prima del pagamento."] },
    { heading: "Fase 3: fissare opzione e prove di taglia", paragraphs: ["Salva titolo, prima immagine, colore, taglia o set, prezzo, identificativo e data. Confronta le misure con un capo che veste bene; una taglia UK o lettera resta un'etichetta.", "Annota la misura limitante: torace per gli strati, cavallo, coscia, soletta o larghezza. Una misura assente resta sconosciuta; la foto di un creator non garantisce la vestibilità."] },
    { heading: "Fase 4: pianificare a ritroso", paragraphs: ["La pagina ufficiale indicava il 29 agosto 2026 una stima di 15–25 giorni per il Regno Unito. Non è una promessa; elaborazione e spedizione sono separate, e preordini o riassortimenti possono partire divisi.", "Prevedi margine per lavorazione, transito, ultimo miglio, prova e reazione. Se l'ultima data ragionevole è passata, evita un candidato legato alla scadenza."] },
    { heading: "Fase 5: conservare un piccolo pacchetto di prove", paragraphs: ["Acquisisci opzione esatta, tabella misure, stima per la destinazione e riepilogo datato. Aggiungi conferma e stati senza pubblicare indirizzo, pagamento, tracking o chat.", "Separa politica ufficiale, schermata di transazione, testimonianza pubblica e analisi editoriale. Uno screenshot prova un momento, non stock futuro, autenticità, prestazioni o consegna."] },
    { heading: "Decidere in cinque colonne", paragraphs: ["Valuta uso, regione/indirizzo, opzione/misure, tempo e prove: Via se basta, Pausa per una lacuna risolvibile, Rifiuta se contraddice un requisito essenziale.", "Un cappotto senza torace resta in pausa; una scarpa può avere misure giuste ma essere rifiutata senza margine per un evento. Non acquistare è un risultato utile."], bullets: ["Uso", "Regione e indirizzo", "Opzione e misure", "Margine temporale", "Qualità delle prove"] },
    { heading: "Il controllo finale di due minuti", paragraphs: ["Riapri la pagina: vera destinazione UK, indirizzo, colore, taglia, misure, tempi, prezzo e condizioni. Se qualcosa è cambiato, aggiorna il foglio e decidi di nuovo.", "Spiega la scelta in una frase. Se dipende da una promessa non verificata, fermati. Il foglio non garantisce nulla, ma rende visibili lacune e logica."] },
  ], takeaways: ["Uso e data prima.", "Verificare regione reale e indirizzo privato.", "Confrontare misure, non etichette.", "Trattare 15–25 giorni come stima UK.", "Usare Via, Pausa o Rifiuta."] },
};

export const readinessArticles: Record<Locale, Article> = { en, ...translated };
