import type { Locale, PageKey } from "./site-data";

export type ArticleKey = Extract<PageKey, `articles/${string}`>;

type LocalizedUi = {
  primaryNav: string;
  language: string;
  liveIndex: string;
  matchedFinds: string;
  languages: string;
  buyerGuides: string;
  explore: string;
  matched: string;
  route: string;
  seoLibrary: string;
  quickAnswers: string;
  deepReads: string;
  answers: string;
  practicalChecklist: string;
  evidenceTitle: string;
  evidenceChecked: string;
  keyTakeaways: string;
  articleSources: string;
  readingTime: string;
  minutes: string;
  lastReviewed: string;
  relatedReading: string;
  exampleImage: string;
  figureCaption: string;
  categoryNames: Record<string, string>;
  productCategories: Record<string, string>;
  productNames: Record<string, string>;
};

export const ui: Record<Locale, LocalizedUi> = {
  en: {
    primaryNav: "Primary navigation", language: "Language", liveIndex: "UK LINK INDEX", matchedFinds: "source-matched finds", languages: "languages", buyerGuides: "buyer guides", explore: "EXPLORE", matched: "MATCHED", route: "ROUTE", seoLibrary: "GUIDE LIBRARY", quickAnswers: "QUICK ANSWERS", deepReads: "DEEP READS", answers: "ANSWERS", practicalChecklist: "PRACTICAL CHECKLIST", evidenceTitle: "Verified Hacoo facts", evidenceChecked: "Evidence checked 28 August 2026", keyTakeaways: "Key takeaways", articleSources: "Research basis", readingTime: "Reading time", minutes: "min", lastReviewed: "Last reviewed", relatedReading: "Related reading", exampleImage: "Source-matched listing example", figureCaption: "The first image helps confirm listing identity, but the current variant, measurements and recent reviews still need checking.",
    categoryNames: { shoes: "Shoes", hoodies: "Sweatshirts", "t-shirts": "T-Shirts", jackets: "Jackets", pants: "Pants / Shorts", headwear: "Headwear", accessories: "Accessories", jersey: "Jersey" },
    productCategories: { shoes: "shoes", sets: "sets", hoodies: "hoodies", bags: "bags", "t-shirts": "t-shirts" },
    productNames: { "7638942248": "AMIRI MA-1 Sneakers — 9 styles", "7656214053": "World T-shirt & Hoodie Set — 40+ styles", "7622957753": "Celine Hoodie", "7666359522": "Neverfull Tote Bag — 39 styles", "7588924374": "Omerta 47 T-shirt", "7572947321": "6PM Hoodie Set", "7582900895": "Trapstar Bag", "7645681448": "Autry Shoes" },
  },
  de: {
    primaryNav: "Hauptnavigation", language: "Sprache", liveIndex: "LIVE-INDEX", matchedFinds: "abgeglichene Funde", languages: "Sprachen", buyerGuides: "Kaufratgeber", explore: "ENTDECKEN", matched: "ABGEGLICHEN", route: "ABLAUF", seoLibrary: "SEO-BIBLIOTHEK", quickAnswers: "SCHNELLE ANTWORTEN", deepReads: "AUSFÜHRLICHE ARTIKEL", answers: "ANTWORTEN", practicalChecklist: "PRAKTISCHE CHECKLISTE", evidenceTitle: "Geprüfte Fakten zu Hacoo", evidenceChecked: "Quellen geprüft am 28. August 2026", keyTakeaways: "Wichtigste Erkenntnisse", articleSources: "Recherchegrundlage", readingTime: "Lesezeit", minutes: "Min.", lastReviewed: "Zuletzt geprüft", relatedReading: "Weiterführende Artikel", exampleImage: "Beispiel eines abgeglichenen Eintrags", figureCaption: "Das erste Bild bestätigt die Identität, doch Variante, Maße und aktuelle Bewertungen müssen weiterhin geprüft werden.",
    categoryNames: { shoes: "Schuhe", hoodies: "Sweatshirts", "t-shirts": "T-Shirts", jackets: "Jacken", pants: "Hosen / Shorts", headwear: "Kopfbedeckungen", accessories: "Accessoires", jersey: "Trikots" },
    productCategories: { shoes: "Schuhe", sets: "Sets", hoodies: "Hoodies", bags: "Taschen", "t-shirts": "T-Shirts" },
    productNames: { "7638942248": "AMIRI MA-1 Sneaker — 9 Varianten", "7656214053": "World T-Shirt- & Hoodie-Set — über 40 Varianten", "7622957753": "Celine Hoodie", "7666359522": "Neverfull Tragetasche — 39 Varianten", "7588924374": "Omerta 47 T-Shirt", "7572947321": "6PM Hoodie-Set", "7582900895": "Trapstar Tasche", "7645681448": "Autry Schuhe" },
  },
  fr: {
    primaryNav: "Navigation principale", language: "Langue", liveIndex: "INDEX ACTUEL", matchedFinds: "fiches vérifiées", languages: "langues", buyerGuides: "guides d’achat", explore: "EXPLORER", matched: "VÉRIFIÉ", route: "PARCOURS", seoLibrary: "BIBLIOTHÈQUE SEO", quickAnswers: "RÉPONSES RAPIDES", deepReads: "ARTICLES APPROFONDIS", answers: "RÉPONSES", practicalChecklist: "LISTE DE CONTRÔLE", evidenceTitle: "Faits vérifiés sur Hacoo", evidenceChecked: "Sources vérifiées le 28 août 2026", keyTakeaways: "À retenir", articleSources: "Base documentaire", readingTime: "Temps de lecture", minutes: "min", lastReviewed: "Dernière vérification", relatedReading: "À lire aussi", exampleImage: "Exemple de fiche rapprochée", figureCaption: "La première image aide à confirmer l’identité, mais il faut encore vérifier variante, mesures et avis récents.",
    categoryNames: { shoes: "Chaussures", hoodies: "Sweats", "t-shirts": "T-shirts", jackets: "Vestes", pants: "Pantalons / Shorts", headwear: "Couvre-chefs", accessories: "Accessoires", jersey: "Maillots" },
    productCategories: { shoes: "chaussures", sets: "ensembles", hoodies: "sweats", bags: "sacs", "t-shirts": "t-shirts" },
    productNames: { "7638942248": "Sneakers AMIRI MA-1 — 9 modèles", "7656214053": "Ensemble T-shirt et sweat World — plus de 40 modèles", "7622957753": "Sweat Celine", "7666359522": "Sac cabas Neverfull — 39 modèles", "7588924374": "T-shirt Omerta 47", "7572947321": "Ensemble sweat 6PM", "7582900895": "Sac Trapstar", "7645681448": "Chaussures Autry" },
  },
  es: {
    primaryNav: "Navegación principal", language: "Idioma", liveIndex: "ÍNDICE ACTUAL", matchedFinds: "hallazgos verificados", languages: "idiomas", buyerGuides: "guías de compra", explore: "EXPLORAR", matched: "VERIFICADO", route: "RUTA", seoLibrary: "BIBLIOTECA SEO", quickAnswers: "RESPUESTAS RÁPIDAS", deepReads: "ARTÍCULOS EN PROFUNDIDAD", answers: "RESPUESTAS", practicalChecklist: "LISTA DE CONTROL", evidenceTitle: "Datos verificados sobre Hacoo", evidenceChecked: "Fuentes revisadas el 28 de agosto de 2026", keyTakeaways: "Puntos clave", articleSources: "Base de la investigación", readingTime: "Tiempo de lectura", minutes: "min", lastReviewed: "Última revisión", relatedReading: "Lecturas relacionadas", exampleImage: "Ejemplo de ficha comprobada", figureCaption: "La primera imagen ayuda a confirmar la identidad, pero aún deben revisarse variante, medidas y opiniones recientes.",
    categoryNames: { shoes: "Zapatillas", hoodies: "Sudaderas", "t-shirts": "Camisetas", jackets: "Chaquetas", pants: "Pantalones / Shorts", headwear: "Gorras y gorros", accessories: "Accesorios", jersey: "Camisetas deportivas" },
    productCategories: { shoes: "zapatillas", sets: "conjuntos", hoodies: "sudaderas", bags: "bolsos", "t-shirts": "camisetas" },
    productNames: { "7638942248": "Zapatillas AMIRI MA-1 — 9 modelos", "7656214053": "Conjunto de camiseta y sudadera World — más de 40 modelos", "7622957753": "Sudadera Celine", "7666359522": "Bolso Neverfull — 39 modelos", "7588924374": "Camiseta Omerta 47", "7572947321": "Conjunto de sudadera 6PM", "7582900895": "Bolso Trapstar", "7645681448": "Zapatillas Autry" },
  },
  it: {
    primaryNav: "Navigazione principale", language: "Lingua", liveIndex: "INDICE AGGIORNATO", matchedFinds: "prodotti verificati", languages: "lingue", buyerGuides: "guide all’acquisto", explore: "ESPLORA", matched: "VERIFICATO", route: "PERCORSO", seoLibrary: "RACCOLTA SEO", quickAnswers: "RISPOSTE RAPIDE", deepReads: "ARTICOLI APPROFONDITI", answers: "RISPOSTE", practicalChecklist: "LISTA DI CONTROLLO", evidenceTitle: "Dati verificati su Hacoo", evidenceChecked: "Fonti verificate il 28 agosto 2026", keyTakeaways: "Punti chiave", articleSources: "Base della ricerca", readingTime: "Tempo di lettura", minutes: "min", lastReviewed: "Ultima verifica", relatedReading: "Letture correlate", exampleImage: "Esempio di scheda verificata", figureCaption: "La prima immagine aiuta a confermare l’identità, ma variante, misure e recensioni recenti vanno ancora controllate.",
    categoryNames: { shoes: "Scarpe", hoodies: "Felpe", "t-shirts": "T-shirt", jackets: "Giacche", pants: "Pantaloni / Shorts", headwear: "Cappelli", accessories: "Accessori", jersey: "Maglie sportive" },
    productCategories: { shoes: "scarpe", sets: "completi", hoodies: "felpe", bags: "borse", "t-shirts": "t-shirt" },
    productNames: { "7638942248": "Sneaker AMIRI MA-1 — 9 modelli", "7656214053": "Completo T-shirt e felpa World — oltre 40 modelli", "7622957753": "Felpa Celine", "7666359522": "Borsa Neverfull — 39 modelli", "7588924374": "T-shirt Omerta 47", "7572947321": "Completo felpa 6PM", "7582900895": "Borsa Trapstar", "7645681448": "Scarpe Autry" },
  },
};

export type EvidenceFact = { value: string; label: string; note: string };

export const evidenceFacts: Record<Locale, EvidenceFact[]> = {
  en: [
    { value: "10M+", label: "Google Play downloads", note: "Google Play listed Hacoo at more than ten million downloads when checked." },
    { value: "15–25 days", label: "official UK delivery estimate", note: "Hacoo's official shipping guidance lists a 15–25 day estimate for the UK." },
    { value: "15 days", label: "general return window", note: "The official policy lists exclusions and says exchanges are not currently supported." },
    { value: "3.6 / 5", label: "Trustpilot snapshot", note: "3,274 reviews showed sharply mixed experiences; this is context, not a quality guarantee." },
  ],
  de: [
    { value: "10 Mio.+", label: "Downloads bei Google Play", note: "Google Play führte Hacoo bei der Prüfung mit mehr als zehn Millionen Downloads." },
    { value: "15–28 Tage", label: "offizielle Lieferprognose", note: "Das Help Center nennt 3–7 Tage Vorbereitung, 7–15 Tage Versand und 5–10 Tage Zustellung." },
    { value: "15 Tage", label: "allgemeine Rückgabefrist", note: "Die offizielle Regel nennt Ausnahmen und erklärt, dass derzeit kein Umtausch angeboten wird." },
    { value: "3,6 / 5", label: "Trustpilot-Momentaufnahme", note: "3.274 Bewertungen zeigten stark gemischte Erfahrungen; das ist Kontext, keine Qualitätsgarantie." },
  ],
  fr: [
    { value: "10 M+", label: "téléchargements Google Play", note: "Google Play affichait plus de dix millions de téléchargements lors de notre vérification." },
    { value: "15–28 jours", label: "délai officiel estimé", note: "Le centre d’aide additionne 3–7 jours de préparation, 7–15 jours d’expédition et 5–10 jours de livraison finale." },
    { value: "15 jours", label: "délai général de retour", note: "La politique officielle prévoit des exclusions et indique que les échanges ne sont pas proposés actuellement." },
    { value: "3,6 / 5", label: "instantané Trustpilot", note: "3 274 avis montraient des expériences très partagées; ce chiffre ne garantit pas la qualité." },
  ],
  es: [
    { value: "10 M+", label: "descargas en Google Play", note: "Google Play mostraba más de diez millones de descargas en la fecha de revisión." },
    { value: "15–28 días", label: "estimación oficial de entrega", note: "El centro de ayuda suma 3–7 días de preparación, 7–15 de envío y 5–10 de entrega final." },
    { value: "15 días", label: "plazo general de devolución", note: "La política oficial incluye excepciones e indica que actualmente no hay cambios." },
    { value: "3,6 / 5", label: "captura de Trustpilot", note: "3.274 reseñas mostraban experiencias muy divididas; es contexto, no una garantía de calidad." },
  ],
  it: [
    { value: "10 M+", label: "download su Google Play", note: "Google Play indicava oltre dieci milioni di download alla data della verifica." },
    { value: "15–28 giorni", label: "stima ufficiale di consegna", note: "Il centro assistenza somma 3–7 giorni di preparazione, 7–15 di spedizione e 5–10 di consegna finale." },
    { value: "15 giorni", label: "termine generale di reso", note: "La politica ufficiale prevede esclusioni e precisa che al momento non sono disponibili cambi." },
    { value: "3,6 / 5", label: "istantanea Trustpilot", note: "3.274 recensioni mostravano esperienze molto contrastanti; è un contesto, non una garanzia." },
  ],
};

const enChecklists: Partial<Record<PageKey, string[]>> = {
  spreadsheet: ["Record the product ID as the stable reference before comparing any copied link.", "Open the destination and match its first image, title, selected option and source price as one set.", "Mark a route as changed when the URL works but any identity field points to a different item.", "Keep one current row per product ID and move duplicate or expired routes into the update record.", "Recheck the destination on mobile because regional app routing can differ from a desktop browser."],
  finds: ["Treat each card as a dated route check, not a permanent availability promise.", "Use the product ID to distinguish a real update from a repost with a new caption.", "Compare the card image with the destination before relying on category, style or price labels.", "If a variant disappears, keep the route only when the remaining listing still identifies the same product.", "Save a replacement route only after the title, image, option and source price agree."],
  categories: ["Start with the narrowest relevant category route instead of a broad wardrobe search.", "For shoes, verify model, colourway, size system and product ID before comparing price.", "For clothing, match garment type, variant label, measurement chart and current first image.", "For bags and accessories, check dimensions, material wording, hardware option and listing ID.", "Remove duplicate paths from your comparison so one product ID is not counted as several finds."],
  "qc-guide": ["Confirm the exact item, colour and variant before examining quality.", "Compare proportions, symmetry, stitching, edge paint, hardware and printed details.", "Use ruler photos for dimensions rather than judging scale by eye.", "Keep packaging and photograph defects: Hacoo's return guidance asks for different evidence for quality, damage, wrong-item and missing-item claims.", "Judge one item from its current evidence; neither a link nor an average rating guarantees the unit you receive."],
  shipping: ["Budget for Hacoo's official 15–25 day UK estimate, not a best-case social-media delivery story.", "Treat preparation, international transit and final-mile delivery as separate stages.", "Confirm the destination and address before payment; region and availability can affect what appears in the app.", "Keep tracking, the outer package and shipping label until the order is complete.", "Open after-sales promptly: the official general window is 15 days after receipt, with exclusions."],
  guide: ["Set the correct country or region before searching because catalog visibility can vary.", "Match the title, first image, variant, product ID and current price at the destination.", "Read recent item-level reviews and inspect user photos rather than relying on a spreadsheet label.", "Check measurements and the official delivery/return conditions before paying.", "Save the selected option and product ID so you can document what you intended to open."],
  faq: ["Use the product ID—not a shortened redirect—as the first troubleshooting reference.", "A working page can still be wrong when its title, image or option no longer matches.", "Regional availability should be checked before classifying a route as expired.", "Price, quality and delivery are separate questions from whether a destination is correctly matched.", "Keep a screenshot of the selected option when reporting a changed or broken route."],
  articles: ["Link-verification notes explain the exact fields checked and the date of the destination review.", "Product-ID research is grouped separately from QC, size and official-policy evidence.", "Each long guide distinguishes official Hacoo information from independent listing observations.", "Update records focus on changed routes, duplicate IDs and mismatched first images.", "Start with the article closest to the decision you need to verify, then return to the live index."],
};

export const pageChecklists: Record<Locale, Partial<Record<PageKey, string[]>>> = {
  en: enChecklists,
  de: {
    spreadsheet: ["Produkt-ID zuerst als stabile Referenz notieren, bevor kopierte Links verglichen werden.", "Ziel öffnen und erstes Bild, Titel, Variante sowie Quellpreis gemeinsam abgleichen.", "Eine Route als geändert markieren, wenn die URL funktioniert, aber Identitätsfelder abweichen.", "Pro Produkt-ID nur eine aktuelle Zeile führen und Duplikate ins Änderungsprotokoll verschieben.", "Ziel auch mobil prüfen, da regionale App-Routen vom Desktop abweichen können."],
    finds: ["Jede Karte als datierte Routenprüfung verstehen, nicht als dauerhafte Verfügbarkeitszusage.", "Mit der Produkt-ID echte Aktualisierungen von neu beschrifteten Kopien unterscheiden.", "Kartenbild und Zielseite vergleichen, bevor Kategorie, Stil oder Preis übernommen werden.", "Bei fehlender Variante die Route nur behalten, wenn das verbleibende Angebot dasselbe Produkt bezeichnet.", "Ersatzroute erst speichern, wenn Titel, Bild, Option und Quellpreis übereinstimmen."],
    categories: ["Mit der engsten passenden Kategorie statt einer breiten Kleidersuche beginnen.", "Bei Schuhen Modell, Farbe, Größensystem und Produkt-ID vor dem Preisvergleich prüfen.", "Bei Kleidung Artikelart, Variante, Maßtabelle und aktuelles erstes Bild abgleichen.", "Bei Taschen und Accessoires Maße, Materialangabe, Hardware-Option und Listing-ID prüfen.", "Doppelte Pfade entfernen, damit eine Produkt-ID nicht als mehrere Funde gezählt wird."],
    "qc-guide": ["Zuerst Artikel, Farbe und Variante eindeutig bestätigen.", "Proportionen, Symmetrie, Nähte, Kanten, Beschläge und Druckdetails vergleichen.", "Für Maße Linealbilder nutzen, statt Größenverhältnisse zu schätzen.", "Verpackung aufbewahren und Mängel fotografieren; Hacoos Rückgabehinweise verlangen je nach Problem unterschiedliche Nachweise.", "Jeden Artikel anhand aktueller Belege beurteilen; weder Link noch Durchschnittsbewertung garantieren das erhaltene Exemplar."],
    shipping: ["Mit der offiziellen Spanne von 15–28 Tagen planen, nicht mit einem Best-Case-Bericht aus sozialen Medien.", "Vorbereitung, internationalen Transport und letzte Zustellung getrennt betrachten.", "Zielland und Adresse vor der Zahlung prüfen; Region und Verfügbarkeit können die Anzeige im App-Katalog verändern.", "Tracking, Außenverpackung und Versandetikett bis zum Abschluss aufbewahren.", "After-Sales zügig starten: Die allgemeine offizielle Frist beträgt 15 Tage nach Erhalt, mit Ausnahmen."],
    guide: ["Vor der Suche Land oder Region korrekt einstellen, da der sichtbare Katalog variieren kann.", "Titel, erstes Bild, Variante, Produkt-ID und aktuellen Zielpreis abgleichen.", "Neue artikelbezogene Bewertungen und Nutzerfotos lesen, nicht nur einer Tabellenzeile vertrauen.", "Maße sowie offizielle Liefer- und Rückgabebedingungen vor der Zahlung prüfen.", "Gewählte Option und Produkt-ID speichern, um die beabsichtigte Auswahl zu dokumentieren."],
    faq: ["Produkt-ID statt Kurzweiterleitung als erste Referenz zur Fehlersuche verwenden.", "Eine funktionierende Seite kann falsch sein, wenn Titel, Bild oder Option nicht mehr passen.", "Regionale Verfügbarkeit prüfen, bevor eine Route als abgelaufen gilt.", "Preis, Qualität und Lieferung getrennt von der korrekten Zielzuordnung bewerten.", "Bei geänderter Route einen Screenshot der gewählten Option aufbewahren."],
    articles: ["Routenartikel nennen geprüfte Felder und Datum der Zielkontrolle.", "Produkt-ID-Recherche bleibt von QC, Größe und offiziellen Richtlinien getrennt.", "Jeder Leitfaden unterscheidet offizielle Hacoo-Informationen von unabhängigen Listing-Beobachtungen.", "Änderungsprotokolle konzentrieren sich auf Routenwechsel, doppelte IDs und abweichende Titelbilder.", "Mit dem passenden Entscheidungsartikel beginnen und danach zum Live-Index zurückkehren."],
  },
  fr: {
    spreadsheet: ["Noter d’abord l’identifiant produit comme référence stable avant de comparer les liens copiés.", "Ouvrir la destination et rapprocher première image, titre, option et prix source.", "Signaler une route modifiée si l’URL fonctionne mais que les champs d’identité diffèrent.", "Conserver une ligne actuelle par identifiant et déplacer doublons ou liens expirés dans le journal.", "Recontrôler sur mobile, car le routage régional de l’application peut différer du navigateur."],
    finds: ["Considérer chaque carte comme un contrôle daté, pas une promesse permanente de disponibilité.", "Utiliser l’identifiant pour distinguer une vraie mise à jour d’une republication.", "Comparer image et destination avant de reprendre catégorie, style ou prix.", "Si une variante disparaît, garder la route seulement si la fiche désigne encore le même produit.", "Enregistrer un remplacement uniquement lorsque titre, image, option et prix source concordent."],
    categories: ["Commencer par la catégorie la plus précise plutôt qu’une recherche vestimentaire générale.", "Pour les chaussures, vérifier modèle, couleur, système de pointure et identifiant avant le prix.", "Pour les vêtements, rapprocher type, variante, tableau de mesures et première image actuelle.", "Pour sacs et accessoires, contrôler dimensions, matière, finition et identifiant de fiche.", "Écarter les chemins dupliqués pour ne pas compter plusieurs fois le même identifiant."],
    "qc-guide": ["Confirmer l’article exact, la couleur et la variante avant d’évaluer la qualité.", "Comparer proportions, symétrie, coutures, bords, pièces métalliques et impressions.", "Utiliser des photos avec règle pour les dimensions au lieu d’estimer à l’œil.", "Conserver l’emballage et photographier les défauts; les consignes Hacoo demandent des preuves différentes selon le problème.", "Évaluer chaque article avec des preuves récentes; ni un lien ni une moyenne d’avis ne garantissent l’exemplaire reçu."],
    shipping: ["Prévoir le délai officiel de 15–28 jours, pas seulement un témoignage de livraison très rapide.", "Séparer préparation, transport international et livraison du dernier kilomètre.", "Confirmer pays et adresse avant paiement; région et disponibilité peuvent modifier le catalogue visible.", "Garder le suivi, l’emballage extérieur et l’étiquette jusqu’à la fin.", "Ouvrir rapidement le dossier après-vente: le délai général officiel est de 15 jours après réception, avec exclusions."],
    guide: ["Régler correctement le pays ou la région avant la recherche, car le catalogue visible peut varier.", "Comparer titre, première image, variante, identifiant et prix actuel de la destination.", "Lire les avis récents sur l’article et examiner les photos d’utilisateurs.", "Vérifier mesures, livraison officielle et conditions de retour avant de payer.", "Enregistrer l’option choisie et l’identifiant produit pour garder une preuve claire."],
    faq: ["Utiliser l’identifiant produit plutôt qu’une redirection courte pour le diagnostic.", "Une page active peut être incorrecte si titre, image ou option ne correspondent plus.", "Vérifier la disponibilité régionale avant de déclarer une route expirée.", "Séparer prix, qualité et livraison de la question de correspondance de destination.", "Conserver une capture de l’option choisie pour signaler une route modifiée."],
    articles: ["Les notes de vérification précisent champs contrôlés et date de révision.", "La recherche d’identifiant est séparée des preuves QC, taille et politiques officielles.", "Chaque guide distingue les informations officielles des observations indépendantes sur les fiches.", "Les mises à jour ciblent routes modifiées, identifiants dupliqués et premières images discordantes.", "Choisir l’article lié à la décision, puis revenir à l’index actuel."],
  },
  es: {
    spreadsheet: ["Anota primero el ID de producto como referencia estable antes de comparar enlaces copiados.", "Abre el destino y comprueba juntos primera imagen, título, opción y precio original.", "Marca una ruta como cambiada si la URL funciona pero los campos de identidad no coinciden.", "Mantén una fila vigente por ID y pasa duplicados o caducados al registro de cambios.", "Revisa también en móvil porque la ruta regional de la app puede diferir del navegador."],
    finds: ["Trata cada tarjeta como una revisión fechada, no como promesa permanente de disponibilidad.", "Usa el ID para distinguir una actualización real de una republicación con otro texto.", "Compara imagen y destino antes de aceptar categoría, estilo o precio.", "Si desaparece una variante, conserva la ruta solo si la ficha sigue identificando el mismo producto.", "Guarda una ruta alternativa únicamente cuando título, imagen, opción y precio coincidan."],
    categories: ["Empieza por la categoría más específica en lugar de una búsqueda general de ropa.", "En calzado, verifica modelo, color, sistema de talla e ID antes del precio.", "En ropa, compara tipo, variante, tabla de medidas y primera imagen actual.", "En bolsos y accesorios, revisa dimensiones, material, acabado e ID de ficha.", "Elimina rutas duplicadas para no contar un mismo ID como varios hallazgos."],
    "qc-guide": ["Confirma el artículo, color y variante exactos antes de evaluar la calidad.", "Compara proporciones, simetría, costuras, bordes, herrajes e impresiones.", "Usa fotos con regla para las medidas en vez de calcular la escala a ojo.", "Conserva el embalaje y fotografía los defectos; la guía de devoluciones de Hacoo pide pruebas distintas según el problema.", "Evalúa cada unidad con pruebas actuales; ni un enlace ni una nota media garantizan lo que recibirás."],
    shipping: ["Planifica con la estimación oficial de 15–28 días, no con el mejor caso visto en redes sociales.", "Separa preparación, tránsito internacional y reparto de última milla.", "Confirma destino y dirección antes de pagar; la región puede cambiar el catálogo visible.", "Guarda seguimiento, paquete exterior y etiqueta hasta completar el pedido.", "Abre la posventa pronto: el plazo general oficial es de 15 días desde la recepción, con excepciones."],
    guide: ["Configura bien país o región antes de buscar porque el catálogo visible puede variar.", "Comprueba título, primera imagen, variante, ID y precio actual de la página de destino.", "Lee reseñas recientes del artículo y revisa fotos de usuarios.", "Verifica medidas y condiciones oficiales de entrega y devolución antes de pagar.", "Guarda la opción elegida y el ID para documentar lo que pretendías abrir."],
    faq: ["Usa el ID de producto, no una redirección corta, como primera referencia de diagnóstico.", "Una página activa puede ser incorrecta si título, imagen u opción ya no coinciden.", "Comprueba disponibilidad regional antes de declarar caducada una ruta.", "Separa precio, calidad y entrega de la correcta correspondencia del destino.", "Conserva una captura de la opción elegida al informar de una ruta cambiada."],
    articles: ["Las notas de verificación indican campos revisados y fecha de control.", "La investigación de ID se separa de pruebas QC, tallas y políticas oficiales.", "Cada guía distingue información oficial de observaciones independientes sobre fichas.", "Los cambios se centran en rutas modificadas, ID duplicados e imágenes iniciales discordantes.", "Empieza por el artículo de tu decisión y vuelve después al índice actual."],
  },
  it: {
    spreadsheet: ["Annota prima l’ID prodotto come riferimento stabile, poi confronta i link copiati.", "Apri la destinazione e verifica insieme prima immagine, titolo, opzione e prezzo originale.", "Segna la rotta come cambiata se l’URL funziona ma i campi identificativi non coincidono.", "Mantieni una riga attuale per ID e sposta duplicati o scaduti nel registro modifiche.", "Controlla anche da mobile perché il routing regionale dell’app può differire dal browser."],
    finds: ["Considera ogni scheda un controllo datato, non una promessa permanente di disponibilità.", "Usa l’ID per distinguere un vero aggiornamento da una ripubblicazione.", "Confronta immagine e destinazione prima di accettare categoria, stile o prezzo.", "Se una variante scompare, conserva la rotta solo se la scheda identifica ancora lo stesso prodotto.", "Salva un’alternativa soltanto quando titolo, immagine, opzione e prezzo coincidono."],
    categories: ["Inizia dalla categoria più precisa invece di una ricerca generica di abbigliamento.", "Per le scarpe verifica modello, colore, sistema taglie e ID prima del prezzo.", "Per l’abbigliamento confronta tipo, variante, tabella misure e prima immagine attuale.", "Per borse e accessori controlla dimensioni, materiale, finitura e ID inserzione.", "Elimina percorsi duplicati per non contare lo stesso ID come più risultati."],
    "qc-guide": ["Conferma articolo, colore e variante esatti prima di valutare la qualità.", "Confronta proporzioni, simmetria, cuciture, bordi, minuteria e stampe.", "Usa foto con righello per le misure invece di stimare a occhio.", "Conserva l’imballaggio e fotografa i difetti; le istruzioni Hacoo richiedono prove diverse a seconda del problema.", "Valuta ogni unità con prove attuali; né un link né una media recensioni garantiscono ciò che riceverai."],
    shipping: ["Pianifica sulla stima ufficiale di 15–28 giorni, non sul caso migliore raccontato sui social.", "Considera separatamente preparazione, transito internazionale e ultimo miglio.", "Conferma destinazione e indirizzo prima del pagamento; la regione può cambiare il catalogo visibile.", "Conserva tracking, imballaggio esterno ed etichetta fino alla conclusione.", "Apri presto l’assistenza post-vendita: il termine generale ufficiale è 15 giorni dalla ricezione, con esclusioni."],
    guide: ["Imposta correttamente paese o regione prima della ricerca perché il catalogo può variare.", "Confronta titolo, prima immagine, variante, ID e prezzo attuale della destinazione.", "Leggi recensioni recenti del singolo articolo e controlla le foto degli utenti.", "Verifica misure e condizioni ufficiali di consegna e reso prima di pagare.", "Salva opzione scelta e ID prodotto per documentare chiaramente la selezione."],
    faq: ["Usa l’ID prodotto, non un reindirizzamento breve, come primo riferimento diagnostico.", "Una pagina attiva può essere errata se titolo, immagine o opzione non coincidono più.", "Controlla la disponibilità regionale prima di dichiarare scaduta una rotta.", "Separa prezzo, qualità e consegna dalla corretta corrispondenza della destinazione.", "Conserva uno screenshot dell’opzione scelta quando segnali una rotta cambiata."],
    articles: ["Le note di verifica indicano campi controllati e data della revisione.", "La ricerca per ID resta separata da prove QC, taglie e politiche ufficiali.", "Ogni guida distingue informazioni ufficiali da osservazioni indipendenti sulle inserzioni.", "Gli aggiornamenti riguardano rotte modificate, ID duplicati e prime immagini discordanti.", "Inizia dall’articolo pertinente alla decisione, poi torna all’indice aggiornato."],
  },
};

export const pageExplanations: Record<Locale, Partial<Record<PageKey, string>>> = {
  en: {
    spreadsheet: "Hacoo's official materials describe a community-driven discovery and content-sharing platform, not a permanent public product database. That is why this index treats every spreadsheet row as a dated research record. A useful record keeps the product ID, current title, first image, selected option, source price, region and check date together. If one identity field changes, the route needs a fresh review even when the URL still opens.",
    finds: "A checked find proves only that the route and visible identity fields matched on the review date. It does not prove stock, delivery, quality or platform approval. Hacoo's Trust Center says posts and links can be removed for deception, malicious redirects, spam or intellectual-property violations. Its published 2025 enforcement counts are internal platform figures, so they explain why links can change without explaining any one missing item.",
    categories: "Category pages are discovery shortcuts, not evidence about a product. Narrow the query to the actual garment or accessory type, then compare model, variant, measurements and ID at the destination. This prevents a broad phrase such as Hacoo shoes or Hacoo bags from doing the work of a proper listing check. Each category should answer a distinct search intent instead of repeating the same spreadsheet copy across thin pages.",
    "qc-guide": "Identity comes before quality scoring. Start with the product ID, selected colour and variant, then place the listing image beside user photos. Compare shape and proportions before small details; use ruler images for dimensions; separate cosmetic variation from damage. If evidence is needed later, photograph the item, packaging, shipping label and exact defect without filters so the record still describes the selected listing.",
    shipping: "Hacoo's UK shipping page gives an estimated 15–25 days, while its broader help article describes a 15–28 day total made from preparation, international transport and final delivery. These are estimates, not guarantees. Save the order date, dispatch date, tracking number, last scan, destination and package label. The detailed return help describes a general 15-day window after receipt, category exclusions, approval and issue-specific evidence, and says exchanges are not currently offered. Follow the live order flow when its instructions are more specific.",
    guide: "The complete verification path starts with a search term, narrows to a category route, records the product ID and then checks the destination fields in one pass. Title, first image, selected option, measurements and source price must describe the same item. A redirect that opens successfully is not enough. Save the result with its check date and replace a route only after the alternative passes the same field-by-field comparison.",
    faq: "The answers on this page separate official policy, independent link checks and third-party customer reports. Hacoo's terms say user-generated posts and recommendations can be outdated and that third-party links operate under their own policies. A concise answer should therefore state its scope: an official estimate, a current route observation or an individual review theme. Mixing those categories creates confident but misleading advice.",
    articles: "The library is arranged by decision stage: discovery and product IDs first, reviews and QC second, sizing third, with shipping and return evidence covered in the dedicated policy guide. Each article owns one primary keyword and supports related questions naturally. This reduces keyword cannibalisation, gives internal links a clear purpose and makes updates easier when an app-store rating, policy page or route changes.",
  },
  de: {
    "qc-guide": "Identität kommt vor der Qualitätsbewertung. Beginne mit Produkt-ID, Farbe und Variante und lege dann Listingbild und Nutzerfotos nebeneinander. Vergleiche zuerst Form und Proportionen, danach Details; nutze Linealbilder für Maße und trenne normale Abweichungen von Schäden. Für einen späteren Nachweis fotografiere Artikel, Verpackung, Versandetikett und Mangel ohne Filter.",
    shipping: "Ein brauchbares Versandprotokoll trennt Vorbereitung, internationalen Transport und letzte Zustellung. Speichere Bestell- und Versanddatum, Trackingnummer, letzten Scan, Ziel und Paketetikett statt nur eines Lieferdatums. Volumen und Ziel können die Route verändern. Bei Stillstand den letzten Carrier-Scan mit der Bestellung vergleichen und die Außenverpackung bis zum Ende der Rückgabefrist behalten.",
    guide: "Der vollständige Prüfpfad beginnt mit dem Suchbegriff, führt über eine passende Kategorie zur Produkt-ID und vergleicht dann alle Zielfelder. Titel, erstes Bild, Option, Maße und Quellpreis müssen denselben Artikel beschreiben. Eine erfolgreiche Weiterleitung reicht nicht. Ergebnis mit Prüfdatum speichern und eine Route nur ersetzen, wenn die Alternative denselben Feldvergleich besteht.",
  },
  fr: {
    "qc-guide": "L’identité précède l’évaluation de qualité. Commencez par l’identifiant, la couleur et la variante, puis placez image de fiche et photos d’utilisateurs côte à côte. Comparez forme et proportions avant les détails, utilisez les photos avec règle et distinguez variation cosmétique et dommage. Pour une preuve, photographiez article, emballage, étiquette et défaut précis sans filtre.",
    shipping: "Un dossier de livraison utile sépare préparation, transport international et dernier kilomètre. Conservez dates de commande et d’expédition, suivi, dernier scan, destination et étiquette plutôt qu’une seule date estimée. Volume et destination peuvent modifier la route. Si le suivi bloque, rapprochez le dernier scan de la commande et gardez l’emballage jusqu’à la fin du délai de retour.",
    guide: "Le parcours complet part d’un mot-clé, passe par une catégorie, enregistre l’identifiant puis contrôle tous les champs de destination. Titre, première image, option, mesures et prix source doivent décrire le même article. Une redirection active ne suffit pas. Enregistrez la date et ne remplacez une route qu’après le même contrôle champ par champ.",
  },
  es: {
    "qc-guide": "La identidad va antes que la puntuación de calidad. Empieza por ID, color y variante y coloca imagen de ficha y fotos de usuarios juntas. Compara forma y proporciones antes de los detalles, usa fotos con regla y separa variación estética de daños. Si necesitas pruebas, fotografía artículo, embalaje, etiqueta y defecto exacto sin filtros.",
    shipping: "Un registro útil separa preparación, tránsito internacional y última milla. Guarda fechas de pedido y salida, número de seguimiento, último escaneo, destino y etiqueta en lugar de una sola fecha prevista. Volumen y destino pueden cambiar la ruta. Si el seguimiento se detiene, compara el último escaneo con el pedido y conserva el embalaje hasta cerrar el plazo de devolución.",
    guide: "La ruta completa parte de una búsqueda, pasa por una categoría, registra el ID y comprueba los campos de destino. Título, primera imagen, opción, medidas y precio original deben describir el mismo artículo. Una redirección que abre no basta. Guarda la fecha y sustituye la ruta solo cuando la alternativa supere la misma comparación campo por campo.",
  },
  it: {
    "qc-guide": "L’identità viene prima del giudizio sulla qualità. Parti da ID, colore e variante e affianca immagine dell’inserzione e foto utenti. Confronta forma e proporzioni prima dei dettagli, usa foto con righello e separa variazioni estetiche da danni. Per eventuali prove fotografa articolo, imballaggio, etichetta e difetto preciso senza filtri.",
    shipping: "Un registro utile separa preparazione, transito internazionale e ultimo miglio. Salva date di ordine e spedizione, tracking, ultima scansione, destinazione ed etichetta invece di una sola data stimata. Volume e destinazione possono cambiare il percorso. Se il tracking si ferma, confronta l’ultima scansione con l’ordine e conserva l’imballaggio fino alla chiusura del reso.",
    guide: "Il percorso completo parte da una ricerca, passa per una categoria, registra l’ID e controlla tutti i campi della destinazione. Titolo, prima immagine, opzione, misure e prezzo originale devono descrivere lo stesso articolo. Un redirect funzionante non basta. Salva la data e sostituisci il percorso solo quando l’alternativa supera lo stesso confronto campo per campo.",
  },
};

export const researchBasis: Record<Locale, string[]> = {
  en: ["Hacoo official website, Trust Center and Help Center", "Google Play listing for com.saramart.android", "Apple App Store listing for Hacoo", "Trustpilot review profile and recent review themes"],
  de: ["Offizielle Hacoo-Website, Trust Center und Help Center", "Google-Play-Eintrag für com.saramart.android", "Apple-App-Store-Eintrag für Hacoo", "Trustpilot-Profil und Themen aktueller Bewertungen"],
  fr: ["Site officiel Hacoo, Trust Center et centre d’aide", "Fiche Google Play com.saramart.android", "Fiche Hacoo de l’Apple App Store", "Profil Trustpilot et tendances des avis récents"],
  es: ["Web oficial de Hacoo, Trust Center y centro de ayuda", "Ficha de Google Play com.saramart.android", "Ficha de Hacoo en Apple App Store", "Perfil de Trustpilot y temas de reseñas recientes"],
  it: ["Sito ufficiale Hacoo, Trust Center e centro assistenza", "Scheda Google Play com.saramart.android", "Scheda Hacoo su Apple App Store", "Profilo Trustpilot e temi delle recensioni recenti"],
};
