import { makeGuide } from './shared.js';
export const englishEditorial = {
  'qc-checker-review-decision-guide': {
    title:'QC Checker: How to Review Photos and Decide Before Shipping',
    description:'Use a QC checker worksheet to separate a confirmed defect from an unclear photo, request the right evidence, and record a shipping decision.',
    keywords:['QC checker','QC check','check QC photos','warehouse quality check','QC review'],
    intro:['A QC finder helps locate photos; a QC check evaluates a particular item against an order and a set of requirements. Searching for a QC checker does not turn historical photos into an inspection of your parcel. Start by identifying whose item is pictured and which decision you need to make.','This guide is a manual review worksheet, not an automated inspection tool. It helps you write a useful conclusion: what is visible, what remains uncertain, and whether to accept, request another check, or ask about an exchange.'],
    sections:[
      {title:'1. Set the requirements before judging the pictures',paragraphs:['Open the order confirmation and the listing captured when you bought the item. Write down the selected size, colour, model and included accessories. Then list the few requirements that would change your decision. A jacket might need a specific measured width and a working zipper; a pair of shoes might need matching size labels and an undamaged sole.','Distinguish a requirement from a preference. If you did not establish an acceptable measurement range, comparing a photo to an imagined perfect product will produce inconsistent decisions. Use a garment or shoe you already find comfortable as a reference, measured with the same method. A numerical example in a guide is not a universal tolerance.']},
      {title:'2. Confirm that the evidence belongs to this order',paragraphs:['Check the warehouse order reference privately, the selected option and the visible labels. Keep historical QC records in a separate folder. A public gallery can reveal details worth examining, but it does not identify the unit now waiting for dispatch. If the record lacks an order reference, ask the agent to confirm the association before interpreting the images.','Do not combine a good front view of one unit with the good rear view of another and call the result a complete inspection. Every decision-critical image should be traceable to the same current item. Remove names, addresses and order references before asking a public community for help.']},
      {title:'3. Use four evidence states',paragraphs:['A binary pass or fail hides important uncertainty. Assign one of four states to each requirement and keep the observation separate from your interpretation. “The end of the ruler is hidden” describes evidence; “the item is too short” is an unsupported conclusion until a usable measurement arrives.'],table:[['State','What it means','Next action'],['Confirmed match','The current evidence answers the requirement','Record the image and observation'],['Confirmed mismatch','A visible, repeatable difference crosses your requirement','Ask about correction, exchange or return'],['Unclear','Angle, lighting or missing context prevents a conclusion','Request one targeted check'],['Not assessable from photos','The property requires a test or later use','Record the remaining risk']]},
      {title:'4. Work through an example without inventing certainty',paragraphs:['Illustrative case: you ordered a blue jacket in size M. The warehouse label says M, but the chest-width ruler starts outside the frame. The first checkpoint is a confirmed label match. The measurement checkpoint is unclear, even if the visible number looks reassuring. Ask for a flat measurement from one armpit seam to the other, with zero and the endpoint visible.','A second image then shows a measurement outside the range you recorded from your own jacket. Save both photos and the reference method. You now have a specific sizing question for the agent, rather than a vague claim that the jacket looks wrong. If the two garments use different measurement points, resolve that difference before deciding.']},
      {title:'5. Choose a next action and a deadline',paragraphs:['Accept the visible condition only when the relevant checks are resolved to your satisfaction. If a decisive detail is unclear, request another photo and ask the agent to hold dispatch where that option is available. If a mismatch is confirmed, contact the party handling the order about the available remedy and its deadline.','Do not assume that a forum vote or an automated score changes a seller’s return rules. Confirm the actual response in your order account. When the service cannot test a property, such as long-term wear, write it as an unresolved risk rather than repeatedly requesting pictures that cannot answer it.']},
      {title:'6. Save a short, reproducible review',items:['Item: source link, option and private order reference.','Requirement: the size, feature or condition that matters.','Evidence: image filename, date, angle and measurement method.','Finding: observed match, observed mismatch, unclear or not assessable.','Action: accept, request a specific check, or contact the agent; include the deadline.'],paragraphs:['Keep the review with the original images rather than only edited crops. A concise record makes a later discussion easier and prevents a decision from being remembered as a guarantee of authenticity, material composition or future durability. FindQCS does not provide those certifications.']},
    ],
  },
  'request-extra-qc-photos-templates': {
    title:'How to Request Extra QC Photos: Measurements and Message Templates',
    description:'Copy precise QC photo requests for clothing measurements, shoe symmetry, labels and suspected damage. Specify the angle, scale and next action.',
    keywords:['request extra QC photos','QC photo request','warehouse measurement request','additional QC pictures'],
    intro:['The best extra QC photo request answers one unresolved question. Name the item, the exact area, the camera angle and the evidence you need. “More photos please” often produces another overview that still does not show the measurement or detail that matters.','The templates below are editable examples for messages inside your agent account. Replace the brackets with your own information. Check the service’s current fees, available checks and response times before requesting work; a template does not promise that a warehouse offers every service.'],
    sections:[
      {title:'1. Give the request a purpose and a deadline',paragraphs:['First identify the decision you cannot make. If you need to compare a garment’s width with one you own, request the exact measurement method. If you suspect a scratch, request a close-up and a wider view that locates it. One clear question is easier to fulfil than a long list of unrelated angles.','Keep your order reference in the private ticket. Mention any return deadline shown in the account and ask whether dispatch can remain on hold. Do not assume a support message automatically suspends shipping or extends the deadline. Wait for confirmation in the order workflow.']},
      {title:'2. Template: flat clothing measurement',paragraphs:['“For order [reference], please lay the garment flat without stretching it. Measure the chest width in a straight line from armpit seam to armpit seam. Show the entire tape, including zero and the endpoint, in one overhead photo. Please state the unit and measured value. I need this to compare with a garment measured the same way.”','For length, specify the starting point, such as the shoulder next to the collar, and the endpoint at the hem. For trousers, distinguish waistband width from circumference and inseam from outer-leg length. Do not double a flat measurement unless that conversion is appropriate for the construction and question. A photograph of the size tag is a different check.']},
      {title:'3. Template: shoes, labels and symmetry',paragraphs:['“For order [reference], please place both shoes upright on the same level surface. Take a rear photo at heel height with both shoes equally distant from the camera. Include clear photos of both size labels and the box label. I want to check pair identity and compare heel alignment.”','If fit is unresolved, ask whether the insole can be safely removed and measured. Do not request dismantling or force that might damage the item. State the endpoints and ask for the complete ruler. An external sole measurement is not interchangeable with usable internal length, and a photograph cannot tell you how the shoe will feel on your foot.']},
      {title:'4. Template: suspected damage or an unclear detail',paragraphs:['“In image [filename], the area beside [seam or feature] looks marked. Please take one sharp close-up and one wider photo locating the same area, under even lighting without a filter. Please tell me whether the mark remains after a permitted surface check. Do not alter or repair the item without asking me first.”','Describe what you see rather than naming an unconfirmed cause. A dark line could be a shadow, a fold or damage. If surface handling could affect return eligibility or the product, ask the agent what is allowed before requesting it. Keep the original photo so you can compare the same location after the reply.']},
      {title:'5. Template: accessories and a permitted function check',paragraphs:['“Please place the item and all supplied accessories together in one photo, outside the packaging where permitted. Compare the contents with this selected option: [option text]. I need to confirm [specific included part]. Please keep all packaging until I confirm the next step.”','For a function check, ask what service is available before specifying a procedure: for example, a short video opening and closing a garment zipper. Do not infer electrical safety, battery health or waterproofing from a brief video. Those questions require appropriate testing and supporting documentation, not a generic QC picture.']},
      {title:'6. Check the reply and close the loop',table:[['Question','Usable response','If still missing'],['Measurement','Both endpoints, scale, unit and method visible','Request the missing endpoint or method'],['Mark or defect','Same area in close and wider views','Ask for a consistent location and lighting'],['Identity','Readable labels associated with this order','Ask the agent to confirm the association'],['Contents','Selected bundle and all parts visible','Name the particular missing part']],paragraphs:['When the new evidence answers your question, update the review and explicitly choose the next action in the agent’s system. A resolved photo request is not necessarily shipping approval. Save the reply, costs if any, and the decision date with your original order record.']},
    ],
  },
  'compare-qc-photos-same-item': {
    title:'How to Compare QC Photos: Same Item, Different Seller or Batch?',
    description:'Compare two QC photo sets without confusing similar images with the same item. Check identifiers, variants, dates, angles and measurements.',
    keywords:['compare QC photos','same item QC','QC photo comparison','different batch QC','QC photos seller'],
    intro:['Two nearly identical QC photos may show different sellers, variants or production runs. A useful comparison starts with the relationship between the records, then compares only details that the available evidence can support. Similar appearance alone does not establish a shared supplier or batch.','Use this worksheet when comparing a saved FindQC result with a current listing or with your own warehouse photos. The goal is to find meaningful differences and better inspection questions, not to declare a winning seller from a few attractive images.'],
    sections:[
      {title:'1. Build a record for each photo set',paragraphs:['Label the sets A and B. For each, save the source platform, final listing URL, item ID, seller, selected size and colour, date of the record and whether the pictured unit belongs to your order. Keep unavailable fields marked unknown. A download date is not necessarily the date the item was photographed.','Do not use a filename, image watermark or shared product photograph as a substitute for the listing identity. Reused marketing images are common enough that the image itself cannot establish a transaction chain. If you only have an image, use it for candidate discovery and stop short of calling the records identical.']},
      {title:'2. Classify the relationship before comparing quality',table:[['Relationship','Useful comparison','Limit'],['Same listing and variant','Visible changes between dated units','Does not prove the same batch'],['Same listing, different variant','Construction and options that are genuinely shared','Size and colour differences need their own baseline'],['Different listing or seller','Separate candidates and inspection questions','Do not transfer a quality conclusion'],['Image-only resemblance','Visual search clues','Identity remains unknown']],paragraphs:['Even a matching item ID can lead to a changed offer over time. Open the current page and check the option set and seller context. If the page has been replaced, label the relationship changed rather than silently attaching the old QC set to the new product.']},
      {title:'3. Make the viewing conditions comparable',paragraphs:['Compare front with front, rear with rear and the same detail at a similar angle. Keep a wide view next to each crop so the location remains identifiable. A shoe closer to a wide-angle camera can look longer; a garment hanging from a hook cannot be directly compared with one laid flat.','Screen brightness, lighting and white balance can change apparent colour. Do not use a pixel colour sample to claim a material or dye mismatch without controlled lighting. Ask for consistent views if the suspected difference could affect your decision. Cropping improves visibility, but aggressive sharpening or colour correction can manufacture a difference.']},
      {title:'4. Compare measurements by method, not just by number',paragraphs:['Confirm what was measured and where the tape starts. Chest width is not circumference, outsole length is not insole length, and product dimensions are not packed-parcel dimensions. If one set measures a different quantity, mark the comparison unavailable instead of putting the values into one ranking.','Illustrative case: set A shows a flat chest width of 54 cm; set B shows a seller size-chart value of 108 cm described as circumference. The numbers might look convertible, but one is a measured unit and the other a seller specification. Record their different origins and request a comparable warehouse measurement before treating them as confirmation.']},
      {title:'5. Turn repeated observations into a targeted check',paragraphs:['If several independent records show a concern in the same seam or joint, ask for a focused view of that area on your own item. First check that the records are not duplicates of one photo set. Repeated uploads of the same image do not provide independent observations.','Avoid claims such as “this batch always has the defect” when the batch identity and sampling are unknown. Describe the observation precisely: a visible feature appears in these dated records, and the current unit needs a check. The absence of a defect in a gallery also does not prove that every future unit is free of it.']},
      {title:'6. Finish with a comparison you can defend',items:['Identity: record what matches and what remains unknown.','Conditions: note angle, lighting, scale and measurement method.','Observation: describe the specific visible difference.','Confidence: distinguish direct evidence from a possible explanation.','Action: request a current photo, verify the listing, or keep the candidates separate.'],paragraphs:['A sound conclusion may be that two sets are not comparable. That is useful: it tells you which evidence is missing and prevents a persuasive photograph from becoming an unsupported purchase recommendation. Keep the source records intact so the comparison can be repeated later.']},
    ],
  },
  'findqc-product-signals': {
    title:'FindQC Trending, Karma, Reviews and Hauls: How to Use Product Signals',
    description:'Read popularity, reviews and haul records as research signals. Connect each signal to the original listing and the evidence for your own order.',
    keywords:['FindQC trending','FindQC karma','FindQC reviews','FindQC hauls','product research'],
    intro:['Community signals help decide what to investigate next. They do not establish what will arrive in your parcel. Treat a popular product, a positive review and a completed haul as different types of information, each with its own date and connection to a listing.','Use the following research card to weigh discovery signals without confusing popularity with inspection. Keep the original offer and the evidence for your own unit at the centre of the decision.'],
    sections:[
      {title:'1. Separate attention from evidence',paragraphs:['A trending list can make a candidate easier to discover. It does not provide a measurement, a material test or a guarantee that the current seller ships the pictured version. Open the underlying offer and identify the exact option before assigning any weight to the surrounding attention.','Keep the date with the signal. A recently popular page may contain older inspection photos, while an older page may have a changed offer. The signal’s freshness and the evidence’s freshness are separate questions.']},
      {title:'2. Treat Karma as a prompt for research',paragraphs:['A community preference can tell you where people have directed attention or approval, but the meaning depends on how the service presents it. Read the current explanation of the feature instead of inventing a quality score or assuming a particular voting formula.','Use the signal to create a shortlist. Then check listing identity, option availability and current warehouse evidence. If the exact item cannot be connected to the signal, retain it only as a discovery clue. A high score does not fill a missing size measurement.']},
      {title:'3. Read the observation inside a review',paragraphs:['A useful review tells you what was ordered, what arrived, when it was inspected and which observation supports the opinion. “The zipper caught at the lower seam” gives you a concrete checkpoint. “Perfect” does not tell you whether the reviewer examined the same variant or cared about the same requirement.','Separate the reviewer’s measurement from their fit judgment. A width can be compared when the method is clear; “true to size” depends on the person, reference garment and preference. Look for independent records and do not count duplicated images as separate experiences.']},
      {title:'4. Use hauls as context, not a price quote',paragraphs:['A haul can illustrate how someone combined items and what happened in that particular shipment. Different dates, destinations, parcel sizes and service choices prevent a direct transfer of their total to your order. Save those fields if they are available.','Do not infer an endorsement of every item merely because it appears in a parcel. Review any item-specific comments and return to the source listing. Parcel experience and product condition answer different questions.']},
      {title:'5. Give your own item the strongest relevance',paragraphs:['The closer evidence is to your selected variant, purchase date and actual unit, the more useful it is for your shipping decision. An old favourable review cannot remove a visible mismatch in the current warehouse photographs. Conversely, an unrelated negative review does not prove that your unit has the same issue.','When sources conflict, write the disagreement and ask for the evidence that could resolve it. Do not average incompatible observations into a single score.']},
      {title:'6. Keep a five-line research card',items:['Identity: platform, listing, seller and option.','Signal: what attracted attention and its date.','Evidence: independent photos, measurements or specific observations.','Current unit: what your own warehouse record shows.','Unknowns: missing fields and the next check.'],paragraphs:['The card keeps community discovery useful without promoting it into a certification. Reopen the live listing before ordering, and update the record when your own QC set becomes available.']},
    ],
  },
  'findqc-shopping-agent-workflow': {
    title:'FindQC and a Shopping Agent: From Product Link to Warehouse Decision',
    description:'Keep product research, ordering, warehouse QC and parcel planning connected with the exact listing, variant and a clear decision record.',
    keywords:['FindQC shopping agent','FindQC how to buy','agent QC workflow','warehouse QC photos'],
    intro:['A research platform, a marketplace seller and a shopping agent perform different jobs. Keep those roles visible as you move from a product link to an order, a warehouse photo set and a parcel. The most useful continuity is the exact listing and selected variant.','This guide explains the handoffs. It does not place an order, promise an agent service or certify a seller. Confirm the current services, prices and deadlines in the account of the party handling your transaction.'],
    sections:[
      {title:'1. Start with a source record',paragraphs:['Save the original marketplace URL, item ID, seller and selected colour, size or model. Include the quantity and any accessories that belong to that option. A screenshot of the cover image alone may describe a different bundle from the one you intend to purchase.','If you discovered the item through the FindQCS index, open the linked destination and verify the current fields there. The index is a navigation aid. The current offer determines what is actually available.']},
      {title:'2. Research the listing before sending an order',paragraphs:['Use the exact source link in a QC finder when supported. Separate historical records associated with that listing from visually similar recommendations. Save the details you want checked on your own item, such as a seam, label, measurement or included component.','A missing gallery does not prove the item is defective, and a large gallery does not guarantee current stock or consistent production. Record what you found and what remains unknown without turning the result count into a quality score.']},
      {title:'3. Transfer the option accurately',paragraphs:['Paste the original link into the agent’s supported ordering flow and check the parsed product. Confirm the selected option in words, especially if the interface translates or abbreviates the seller’s labels. Before payment, review the item total, domestic delivery, service charges and available return conditions.','Keep the agent’s order confirmation beside your source record. If the agent cannot confirm an option, resolve it before relying on historical photos for a different one.']},
      {title:'4. Check the unit that reaches the warehouse',paragraphs:['Match the private order reference and labels first. Then review overview images, construction details, dimensions and accessories according to the product category. Use historical QC as a list of questions, not as a substitute for the current unit’s photos.','If a decisive angle is missing, submit a targeted request with the location, method and reason. Confirm whether extra photographs or tests are available, what they cost and whether the item can remain on hold while the question is answered.']},
      {title:'5. Decide about the item before packing the parcel',paragraphs:['Record whether to accept the visible condition, request a check, or contact the agent about an exchange or return. Keep the supporting evidence and deadline. Only then decide about removing boxes, reinforcing fragile items or consolidating products.','A photograph cannot establish every property. If comfort, composition or long-term durability remains unknown, preserve that limitation in the decision rather than describing the item as fully verified.']},
      {title:'6. Plan shipping with current parcel data',paragraphs:['Ask for actual packed weight and dimensions, the relevant route quote and its current limits. An item’s historical weight is not the final parcel weight; packaging can change both mass and volume. Compare the same destination, service and parcel assumptions when evaluating quotes.','Save the final order record, QC images, parcel measurements and tracking details privately. These records connect the stages if a later support question arises. The essential outcome is a traceable handoff at each stage, not a promise that research eliminates every risk.']},
    ],
  },
};
export const newEnglishArticles=Object.entries(englishEditorial).map(([slug,content])=>makeGuide(slug,'en',content));
