const slugs=[
'before-you-buy-qc-guide','product-search-link-id-keyword','what-qc-photos-can-prove','warehouse-measurement-guide','shipping-cost-checklist','mapped-findqc-product-index-without-recommendation','taobao-qc-finder-item-id-link-checks','weidian-qc-finder-item-id-original-listing','1688-qc-finder-supplier-variant-batch-checks','qc-finder-no-photos-dead-link-recovery','findqc-image-search-reference-photo-checks','qc-photos-vs-qc-videos-evidence-guide','sneaker-qc-photo-checklist-shape-tags-soles-box','clothing-qc-photos-measurements-print-stitching','qc-checker-review-decision-guide','request-extra-qc-photos-templates','compare-qc-photos-same-item','findqc-product-signals','findqc-shopping-agent-workflow'];
const titles={
 en:['QC Photo Checklist: What to Check Before Shipping','FindQC Search: Product Link, Item ID or Image?','What QC Photos Can and Cannot Prove','Read QC Measurements: Tape, Size and Photo Checks','Shipping Cost Checklist: Weight, Volume and Fees','How to Use the FindQCS Product Index','Taobao QC Finder: Check Links, IDs and Photos','Weidian QC Finder: Verify the Original Item ID','1688 QC Finder: Supplier, Variant and Batch Checks','QC Finder Not Finding Photos? Link Recovery Guide','FindQC Image Search: Find and Verify Photo Matches','QC Photos vs Video: Choose the Right Evidence','Sneaker QC Checklist: Shape, Labels, Soles and Box','Clothing QC Photos: Measurements, Prints and Seams','QC Checker: Review Photos and Decide Before Shipping','Request Extra QC Photos: Message Templates','Compare QC Photos: Same Item, Seller or Batch?','FindQC Trending, Karma, Reviews and Hauls Explained','FindQC and Shopping Agents: The Order Workflow'],
 de:['QC-Foto-Checkliste: Vor dem Versand prüfen','FindQC-Suche: Link, Artikel-ID oder Bild?','Was QC-Fotos zeigen können – und was nicht','QC-Maße lesen: Maßband und Größenvergleich','Versandkosten: Gewicht, Volumen und Gebühren','Den FindQCS-Produktindex richtig nutzen','Taobao QC Finder: Links, IDs und Fotos prüfen','Weidian QC Finder: Original-ID verifizieren','1688 QC Finder: Lieferant, Variante und Charge','QC Finder findet keine Fotos? Linkprüfung','FindQC-Bildsuche: Treffer finden und prüfen','QC-Fotos oder Video: passende Nachweise wählen','Sneaker-QC: Form, Labels, Sohlen und Karton','Kleidung-QC: Maße, Druck und Nähte prüfen','QC Checker: Fotos prüfen und entscheiden','Zusätzliche QC-Fotos: Vorlagen für Anfragen','QC-Fotos vergleichen: Artikel, Verkäufer, Charge','FindQC: Trending, Karma, Reviews und Hauls','FindQC und Shopping Agent: der Bestellablauf'],
 es:['Checklist de fotos QC antes del envío','Búsqueda FindQC: ¿enlace, ID o imagen?','Qué pueden demostrar las fotos QC','Medidas en fotos QC: cinta y comparación','Gastos de envío: peso, volumen y cargos','Cómo usar el índice de productos FindQCS','Taobao QC Finder: verificar enlaces, ID y fotos','Weidian QC Finder: comprobar el ID original','1688 QC Finder: proveedor, variante y lote','QC Finder sin fotos: cómo revisar el enlace','FindQC por imagen: encontrar y verificar resultados','Fotos QC o vídeo: elegir la prueba adecuada','QC de zapatillas: forma, etiquetas, suelas y caja','QC de ropa: medidas, estampados y costuras','QC Checker: revisar fotos y decidir','Pedir fotos QC adicionales: plantillas de mensajes','Comparar fotos QC: artículo, vendedor y lote','FindQC: Trending, Karma, reseñas y hauls','FindQC y agente de compras: pasos del pedido'],
 pl:['Lista kontroli zdjęć QC przed wysyłką','Wyszukiwanie FindQC: link, ID czy obraz?','Co mogą potwierdzić zdjęcia QC?','Wymiary QC: taśma i porównanie rozmiaru','Koszty wysyłki: waga, objętość i opłaty','Jak korzystać z indeksu produktów FindQCS','Taobao QC Finder: linki, ID i zdjęcia','Weidian QC Finder: sprawdź oryginalne ID','1688 QC Finder: dostawca, wariant i partia','QC Finder bez zdjęć: sprawdzanie linków','FindQC obrazem: znajdź i sprawdź wyniki','Zdjęcia QC czy film: wybierz właściwy dowód','QC sneakersów: kształt, metki, podeszwy i pudełko','QC odzieży: wymiary, nadruki i szwy','QC Checker: sprawdź zdjęcia i podejmij decyzję','Dodatkowe zdjęcia QC: wzory wiadomości','Porównaj zdjęcia QC: produkt, sprzedawca i partia','FindQC: Trending, Karma, opinie i haule','FindQC i agent zakupowy: przebieg zamówienia'],
 ro:['Checklist fotografii QC înainte de expediere','Căutare FindQC: link, ID sau imagine?','Ce pot demonstra fotografiile QC?','Dimensiuni QC: ruletă și comparația mărimii','Costuri de transport: greutate, volum și taxe','Cum folosești indexul de produse FindQCS','Taobao QC Finder: verifică linkuri, ID-uri și poze','Weidian QC Finder: verifică ID-ul original','1688 QC Finder: furnizor, variantă și lot','QC Finder fără poze: verificarea linkului','FindQC prin imagini: găsește și verifică rezultate','Fotografii QC sau video: alege dovada potrivită','QC sneakers: formă, etichete, tălpi și cutie','QC haine: măsurători, imprimeuri și cusături','QC Checker: verifică pozele și decide','Poze QC suplimentare: modele de mesaje','Compară poze QC: articol, vânzător și lot','FindQC: Trending, Karma, recenzii și haul-uri','FindQC și agentul de cumpărături: fluxul comenzii'],
};
export const articleSearchTitles=Object.fromEntries(Object.entries(titles).map(([lang,values])=>[lang,Object.fromEntries(slugs.map((slug,i)=>[slug,values[i]]))]));
