type Dictionary = Record<string,string>;

export const extraTranslations: Record<"de"|"es"|"fr"|"it",Dictionary> = {
  de: {
    "FAQ":"FAQ","QC Guide":"QC-Ratgeber","Open catalog":"Katalog öffnen","Search product finds":"Produkte durchsuchen","Search":"Suchen",
    "Research library":"Recherche-Bibliothek","Read before you ship.":"Vor dem Versand lesen.","Long-form guides built from official platform information, warehouse decision checks and clearly labelled public-review evidence.":"Ausführliche Ratgeber auf Basis offizieller Plattformangaben, Lagerprüfungen und klar gekennzeichneter öffentlicher Erfahrungsberichte.",
    "Spreadsheet workflow":"Tabellen-Workflow","Warehouse check · QC photos":"Lagerprüfung · QC-Fotos","Parcel planning · Shipping cost":"Paketplanung · Versandkosten","Read full article":"Vollständigen Artikel lesen","View the article library →":"Zur Artikelbibliothek →",
    "How to Use a Hipobuy Spreadsheet Without Buying Blind":"Eine Hipobuy-Tabelle nutzen, ohne blind zu kaufen","Hipobuy QC Photos: A Practical Inspection Guide for 2026":"Hipobuy-QC-Fotos: Praktischer Prüfleitfaden 2026","Hipobuy Shipping Cost: How to Estimate the Real Delivered Price":"Hipobuy-Versandkosten: Den tatsächlichen Endpreis schätzen",
    "Evidence-led buyer library":"Faktenbasierte Käuferbibliothek","Hipobuy articles built around real decisions.":"Hipobuy-Artikel für echte Kaufentscheidungen.","Long-form guides based on current official platform information, clearly separated from estimates, community reports and changing seller details.":"Ausführliche Ratgeber auf Grundlage aktueller offizieller Plattformangaben, klar getrennt von Schätzungen, Community-Berichten und veränderlichen Verkäuferdaten.",
    "Published guides":"Veröffentlichte Ratgeber","Start with the workflow, then go deeper.":"Mit dem Ablauf beginnen, dann vertiefen.","The first three articles follow the order a buyer actually makes decisions: find the listing, inspect the warehouse evidence, then calculate the delivered cost.":"Die ersten drei Artikel folgen der tatsächlichen Entscheidungsreihenfolge: Angebot finden, Lagerbelege prüfen und anschließend die Gesamtkosten berechnen.",
    "Publishing standard":"Redaktionsstandard","Facts, claims and experience stay separate.":"Fakten, Behauptungen und Erfahrungen bleiben getrennt.","Official platform statements are attributed and dated. Shipping figures remain estimates. Community reviews are used to identify recurring questions, not copied as universal conclusions.":"Offizielle Plattformangaben werden zugeordnet und datiert. Versandwerte bleiben Schätzungen. Community-Bewertungen dienen zur Erkennung wiederkehrender Fragen und nicht als allgemeingültige Schlussfolgerungen.",
    "Enough detail to complete one buyer decision":"Genug Details für eine konkrete Kaufentscheidung","A clearly defined purpose for every guide":"Ein klar definierter Zweck für jeden Ratgeber","Original checklists and decision frameworks":"Eigene Checklisten und Entscheidungsmodelle","Visible source notes and update date":"Sichtbare Quellenhinweise und Aktualisierungsdatum","No fabricated review, delivery promise or price guarantee":"Keine erfundenen Bewertungen, Lieferzusagen oder Preisgarantien",
    "Published":"Veröffentlicht","Updated":"Aktualisiert","Independent guide":"Unabhängiger Ratgeber","On this page":"Auf dieser Seite","Sources checked · 25 August 2026":"Quellen geprüft · 25. August 2026","Research notes":"Recherchehinweise","Sources support specific platform facts or identify recurring buyer questions. Community reports are not treated as official terms or guaranteed outcomes.":"Quellen belegen konkrete Plattformangaben oder zeigen wiederkehrende Käuferfragen. Community-Berichte gelten nicht als offizielle Bedingungen oder garantierte Ergebnisse.","Continue checking":"Weiter prüfen","Use the guide, then verify the live listing.":"Ratgeber nutzen und danach das aktuelle Angebot prüfen.","All articles":"Alle Artikel","Browse current catalog ↗":"Aktuellen Katalog ansehen ↗",
    "What a Hipobuy spreadsheet actually does":"Was eine Hipobuy-Tabelle tatsächlich leistet","Why Hipobuy sits between the listing and your address":"Warum Hipobuy zwischen Angebot und Lieferadresse steht","Step 1: search by product intent, not hype":"Schritt 1: Nach Produktabsicht statt Hype suchen","Step 2: run a pre-order cost screen":"Schritt 2: Kosten vor der Bestellung prüfen","Step 3: wait for warehouse evidence":"Schritt 3: Auf Lagerbelege warten","Step 4: consolidate with a parcel plan":"Schritt 4: Mit einem Paketplan konsolidieren","Step 5: compare shipping lines on the actual parcel":"Schritt 5: Versandlinien am echten Paket vergleichen","Common spreadsheet mistakes":"Häufige Tabellenfehler","The 60-second decision checklist":"Die 60-Sekunden-Checkliste","A spreadsheet should make you slower at the right moment":"Eine Tabelle sollte dich im richtigen Moment bremsen",
    "What “QC” means in a shopping-agent workflow":"Was „QC“ im Einkaufsagenten-Ablauf bedeutet","Prepare before the item reaches the warehouse":"Vor Ankunft im Lager vorbereiten","Pass 1: confirm the order before judging quality":"Prüfung 1: Bestellung vor der Qualität bestätigen","Pass 2: read the overview photos":"Prüfung 2: Übersichtsfotos lesen","Pass 3: inspect construction and finishing":"Prüfung 3: Verarbeitung und Finish untersuchen","Pass 4: treat measurements as data":"Prüfung 4: Maße als Daten behandeln","When to request an extra photo":"Wann ein zusätzliches Foto sinnvoll ist","Red light, yellow light and green light decisions":"Entscheidungen mit Rot, Gelb und Grün","Returns are easier before international shipping—but not automatic":"Rückgaben sind vor dem internationalen Versand leichter – aber nicht automatisch","A repeatable eight-point QC checklist":"Wiederholbare QC-Checkliste mit acht Punkten","The most useful QC photo is the one tied to a decision":"Das nützlichste QC-Foto ist an eine Entscheidung gebunden",
    "Why the first price is not the delivered price":"Warum der erste Preis nicht der Endpreis ist","Build a delivered-cost model":"Ein Gesamtkostenmodell erstellen","Actual weight versus volumetric weight":"Tatsächliches Gewicht und Volumengewicht","Use the official estimator correctly":"Den offiziellen Rechner richtig nutzen","Does consolidation always save money?":"Spart Konsolidierung immer Geld?","Packing choices that change the quote":"Verpackungsentscheidungen, die den Preis ändern","How to compare shipping lines":"Versandlinien vergleichen","What public reviews reveal—and what they do not":"Was öffentliche Bewertungen zeigen – und was nicht","Country-specific costs need country-specific checks":"Länderspezifische Kosten brauchen länderspezifische Prüfungen","A practical pre-shipping comparison":"Praktischer Vergleich vor dem Versand","Reduce surprises, not just the displayed price":"Überraschungen reduzieren, nicht nur den angezeigten Preis"
  },
  es: {
    "FAQ":"Preguntas frecuentes","QC Guide":"Guía de control","Open catalog":"Abrir catálogo","Search product finds":"Buscar productos","Search":"Buscar",
    "Research library":"Biblioteca de investigación","Read before you ship.":"Lee antes de enviar.","Long-form guides built from official platform information, warehouse decision checks and clearly labelled public-review evidence.":"Guías detalladas basadas en información oficial, controles de almacén y reseñas públicas claramente identificadas.",
    "Spreadsheet workflow":"Proceso de la hoja","Warehouse check · QC photos":"Control de almacén · Fotos QC","Parcel planning · Shipping cost":"Planificación del paquete · Envío","Read full article":"Leer artículo completo","View the article library →":"Ver biblioteca de artículos →",
    "How to Use a Hipobuy Spreadsheet Without Buying Blind":"Cómo usar una hoja de Hipobuy sin comprar a ciegas","Hipobuy QC Photos: A Practical Inspection Guide for 2026":"Fotos QC de Hipobuy: guía práctica de inspección 2026","Hipobuy Shipping Cost: How to Estimate the Real Delivered Price":"Coste de envío de Hipobuy: cómo calcular el precio final real",
    "Evidence-led buyer library":"Biblioteca para compradores basada en pruebas","Hipobuy articles built around real decisions.":"Artículos de Hipobuy para decisiones reales.","Long-form guides based on current official platform information, clearly separated from estimates, community reports and changing seller details.":"Guías extensas basadas en información oficial actual, separando claramente estimaciones, testimonios de la comunidad y datos cambiantes de vendedores.",
    "Published guides":"Guías publicadas","Start with the workflow, then go deeper.":"Empieza por el proceso y profundiza después.","The first three articles follow the order a buyer actually makes decisions: find the listing, inspect the warehouse evidence, then calculate the delivered cost.":"Los tres primeros artículos siguen el orden real de decisión: encontrar el anuncio, revisar las pruebas del almacén y calcular el coste final.",
    "Publishing standard":"Estándar editorial","Facts, claims and experience stay separate.":"Los hechos, las afirmaciones y las experiencias se mantienen separados.","Official platform statements are attributed and dated. Shipping figures remain estimates. Community reviews are used to identify recurring questions, not copied as universal conclusions.":"Las afirmaciones oficiales se atribuyen y se fechan. Los importes de envío siguen siendo estimaciones. Las reseñas sirven para detectar dudas recurrentes, no como conclusiones universales.",
    "Enough detail to complete one buyer decision":"Detalle suficiente para tomar una decisión","A clearly defined purpose for every guide":"Un propósito claro para cada guía","Original checklists and decision frameworks":"Listas y marcos de decisión originales","Visible source notes and update date":"Fuentes y fecha de actualización visibles","No fabricated review, delivery promise or price guarantee":"Sin reseñas inventadas, promesas de entrega ni precios garantizados",
    "Published":"Publicado","Updated":"Actualizado","Independent guide":"Guía independiente","On this page":"En esta página","Sources checked · 25 August 2026":"Fuentes revisadas · 25 de agosto de 2026","Research notes":"Notas de investigación","Sources support specific platform facts or identify recurring buyer questions. Community reports are not treated as official terms or guaranteed outcomes.":"Las fuentes respaldan datos concretos o identifican preguntas frecuentes. Los testimonios comunitarios no se tratan como condiciones oficiales ni resultados garantizados.","Continue checking":"Seguir comprobando","Use the guide, then verify the live listing.":"Usa la guía y verifica después el anuncio actual.","All articles":"Todos los artículos","Browse current catalog ↗":"Ver catálogo actual ↗",
    "What a Hipobuy spreadsheet actually does":"Qué hace realmente una hoja de Hipobuy","Why Hipobuy sits between the listing and your address":"Por qué Hipobuy está entre el anuncio y tu dirección","Step 1: search by product intent, not hype":"Paso 1: busca por producto, no por moda","Step 2: run a pre-order cost screen":"Paso 2: revisa los costes antes de comprar","Step 3: wait for warehouse evidence":"Paso 3: espera las pruebas del almacén","Step 4: consolidate with a parcel plan":"Paso 4: consolida con un plan de paquete","Step 5: compare shipping lines on the actual parcel":"Paso 5: compara líneas con el paquete real","Common spreadsheet mistakes":"Errores frecuentes al usar hojas","The 60-second decision checklist":"Lista de decisión de 60 segundos","A spreadsheet should make you slower at the right moment":"Una hoja debe hacerte frenar en el momento correcto",
    "What “QC” means in a shopping-agent workflow":"Qué significa “QC” en el proceso de un agente","Prepare before the item reaches the warehouse":"Prepárate antes de que llegue al almacén","Pass 1: confirm the order before judging quality":"Revisión 1: confirma el pedido antes de valorar la calidad","Pass 2: read the overview photos":"Revisión 2: analiza las fotos generales","Pass 3: inspect construction and finishing":"Revisión 3: inspecciona construcción y acabados","Pass 4: treat measurements as data":"Revisión 4: trata las medidas como datos","When to request an extra photo":"Cuándo pedir una foto adicional","Red light, yellow light and green light decisions":"Decisiones en rojo, amarillo y verde","Returns are easier before international shipping—but not automatic":"Las devoluciones son más fáciles antes del envío internacional, pero no automáticas","A repeatable eight-point QC checklist":"Lista QC repetible de ocho puntos","The most useful QC photo is the one tied to a decision":"La foto QC más útil es la que resuelve una decisión",
    "Why the first price is not the delivered price":"Por qué el primer precio no es el precio final","Build a delivered-cost model":"Construye un modelo de coste final","Actual weight versus volumetric weight":"Peso real frente a peso volumétrico","Use the official estimator correctly":"Usa correctamente el estimador oficial","Does consolidation always save money?":"¿Consolidar siempre ahorra dinero?","Packing choices that change the quote":"Decisiones de embalaje que cambian el precio","How to compare shipping lines":"Cómo comparar líneas de envío","What public reviews reveal—and what they do not":"Qué revelan las reseñas públicas y qué no","Country-specific costs need country-specific checks":"Los costes por país requieren comprobaciones por país","A practical pre-shipping comparison":"Comparación práctica antes del envío","Reduce surprises, not just the displayed price":"Reduce sorpresas, no solo el precio mostrado"
  },
  fr: {
    "FAQ":"FAQ","QC Guide":"Guide QC","Open catalog":"Ouvrir le catalogue","Search product finds":"Rechercher des produits","Search":"Rechercher",
    "Research library":"Bibliothèque de recherche","Read before you ship.":"À lire avant l’expédition.","Long-form guides built from official platform information, warehouse decision checks and clearly labelled public-review evidence.":"Guides détaillés fondés sur les informations officielles, les contrôles en entrepôt et des avis publics clairement identifiés.",
    "Spreadsheet workflow":"Processus du tableur","Warehouse check · QC photos":"Contrôle entrepôt · Photos QC","Parcel planning · Shipping cost":"Préparation du colis · Livraison","Read full article":"Lire l’article complet","View the article library →":"Voir la bibliothèque d’articles →",
    "How to Use a Hipobuy Spreadsheet Without Buying Blind":"Utiliser un tableur Hipobuy sans acheter à l’aveugle","Hipobuy QC Photos: A Practical Inspection Guide for 2026":"Photos QC Hipobuy : guide pratique d’inspection 2026","Hipobuy Shipping Cost: How to Estimate the Real Delivered Price":"Frais de livraison Hipobuy : estimer le vrai prix final",
    "Evidence-led buyer library":"Bibliothèque d’achat fondée sur des preuves","Hipobuy articles built around real decisions.":"Des articles Hipobuy pour de vraies décisions.","Long-form guides based on current official platform information, clearly separated from estimates, community reports and changing seller details.":"Guides complets fondés sur les informations officielles actuelles, en séparant clairement estimations, témoignages de la communauté et données variables des vendeurs.",
    "Published guides":"Guides publiés","Start with the workflow, then go deeper.":"Commencez par le processus, puis approfondissez.","The first three articles follow the order a buyer actually makes decisions: find the listing, inspect the warehouse evidence, then calculate the delivered cost.":"Les trois premiers articles suivent l’ordre réel des décisions : trouver l’annonce, examiner les preuves d’entrepôt, puis calculer le coût final.",
    "Publishing standard":"Norme éditoriale","Facts, claims and experience stay separate.":"Les faits, affirmations et expériences restent séparés.","Official platform statements are attributed and dated. Shipping figures remain estimates. Community reviews are used to identify recurring questions, not copied as universal conclusions.":"Les déclarations officielles sont attribuées et datées. Les montants de livraison restent des estimations. Les avis servent à repérer les questions récurrentes et non à établir des conclusions universelles.",
    "Enough detail to complete one buyer decision":"Assez de détails pour prendre une décision","A clearly defined purpose for every guide":"Un objectif clair pour chaque guide","Original checklists and decision frameworks":"Listes et cadres de décision originaux","Visible source notes and update date":"Sources et date de mise à jour visibles","No fabricated review, delivery promise or price guarantee":"Aucun faux avis, délai promis ou prix garanti",
    "Published":"Publié","Updated":"Mis à jour","Independent guide":"Guide indépendant","On this page":"Sur cette page","Sources checked · 25 August 2026":"Sources vérifiées · 25 août 2026","Research notes":"Notes de recherche","Sources support specific platform facts or identify recurring buyer questions. Community reports are not treated as official terms or guaranteed outcomes.":"Les sources appuient des faits précis ou identifient des questions récurrentes. Les témoignages communautaires ne sont pas considérés comme des conditions officielles ou des résultats garantis.","Continue checking":"Continuer les vérifications","Use the guide, then verify the live listing.":"Utilisez le guide puis vérifiez l’annonce actuelle.","All articles":"Tous les articles","Browse current catalog ↗":"Voir le catalogue actuel ↗",
    "What a Hipobuy spreadsheet actually does":"Ce que fait réellement un tableur Hipobuy","Why Hipobuy sits between the listing and your address":"Pourquoi Hipobuy se place entre l’annonce et votre adresse","Step 1: search by product intent, not hype":"Étape 1 : chercher un produit, pas une tendance","Step 2: run a pre-order cost screen":"Étape 2 : vérifier les coûts avant commande","Step 3: wait for warehouse evidence":"Étape 3 : attendre les preuves d’entrepôt","Step 4: consolidate with a parcel plan":"Étape 4 : regrouper avec un plan de colis","Step 5: compare shipping lines on the actual parcel":"Étape 5 : comparer les lignes sur le colis réel","Common spreadsheet mistakes":"Erreurs fréquentes avec un tableur","The 60-second decision checklist":"Liste de décision en 60 secondes","A spreadsheet should make you slower at the right moment":"Un tableur doit vous ralentir au bon moment",
    "What “QC” means in a shopping-agent workflow":"Ce que signifie « QC » dans le processus d’un agent","Prepare before the item reaches the warehouse":"Se préparer avant l’arrivée en entrepôt","Pass 1: confirm the order before judging quality":"Contrôle 1 : confirmer la commande avant la qualité","Pass 2: read the overview photos":"Contrôle 2 : analyser les vues d’ensemble","Pass 3: inspect construction and finishing":"Contrôle 3 : inspecter fabrication et finitions","Pass 4: treat measurements as data":"Contrôle 4 : traiter les mesures comme des données","When to request an extra photo":"Quand demander une photo supplémentaire","Red light, yellow light and green light decisions":"Décisions rouge, jaune et verte","Returns are easier before international shipping—but not automatic":"Les retours sont plus simples avant l’expédition internationale, mais pas automatiques","A repeatable eight-point QC checklist":"Liste QC reproductible en huit points","The most useful QC photo is the one tied to a decision":"La photo QC la plus utile répond à une décision",
    "Why the first price is not the delivered price":"Pourquoi le premier prix n’est pas le prix final","Build a delivered-cost model":"Construire un modèle de coût final","Actual weight versus volumetric weight":"Poids réel et poids volumétrique","Use the official estimator correctly":"Bien utiliser l’estimateur officiel","Does consolidation always save money?":"Le regroupement fait-il toujours économiser ?","Packing choices that change the quote":"Choix d’emballage qui modifient le tarif","How to compare shipping lines":"Comparer les lignes de livraison","What public reviews reveal—and what they do not":"Ce que révèlent les avis publics, et leurs limites","Country-specific costs need country-specific checks":"Les coûts par pays exigent des contrôles par pays","A practical pre-shipping comparison":"Comparaison pratique avant expédition","Reduce surprises, not just the displayed price":"Réduire les surprises, pas seulement le prix affiché"
  },
  it: {
    "FAQ":"FAQ","QC Guide":"Guida QC","Open catalog":"Apri catalogo","Search product finds":"Cerca prodotti","Search":"Cerca",
    "Research library":"Biblioteca di ricerca","Read before you ship.":"Leggi prima di spedire.","Long-form guides built from official platform information, warehouse decision checks and clearly labelled public-review evidence.":"Guide approfondite basate su informazioni ufficiali, controlli di magazzino e recensioni pubbliche chiaramente indicate.",
    "Spreadsheet workflow":"Flusso del foglio","Warehouse check · QC photos":"Controllo magazzino · Foto QC","Parcel planning · Shipping cost":"Pianificazione pacco · Spedizione","Read full article":"Leggi l’articolo completo","View the article library →":"Vedi la biblioteca degli articoli →",
    "How to Use a Hipobuy Spreadsheet Without Buying Blind":"Usare un foglio Hipobuy senza acquistare alla cieca","Hipobuy QC Photos: A Practical Inspection Guide for 2026":"Foto QC Hipobuy: guida pratica all’ispezione 2026","Hipobuy Shipping Cost: How to Estimate the Real Delivered Price":"Costo di spedizione Hipobuy: stimare il prezzo finale reale",
    "Evidence-led buyer library":"Biblioteca acquisti basata su prove","Hipobuy articles built around real decisions.":"Articoli Hipobuy per decisioni reali.","Long-form guides based on current official platform information, clearly separated from estimates, community reports and changing seller details.":"Guide complete basate su informazioni ufficiali aggiornate, distinguendo chiaramente stime, testimonianze della comunità e dati variabili dei venditori.",
    "Published guides":"Guide pubblicate","Start with the workflow, then go deeper.":"Inizia dal processo, poi approfondisci.","The first three articles follow the order a buyer actually makes decisions: find the listing, inspect the warehouse evidence, then calculate the delivered cost.":"I primi tre articoli seguono l’ordine reale delle decisioni: trovare l’inserzione, controllare le prove di magazzino e calcolare il costo finale.",
    "Publishing standard":"Standard editoriale","Facts, claims and experience stay separate.":"Fatti, affermazioni ed esperienze restano separati.","Official platform statements are attributed and dated. Shipping figures remain estimates. Community reviews are used to identify recurring questions, not copied as universal conclusions.":"Le dichiarazioni ufficiali sono attribuite e datate. I costi di spedizione restano stime. Le recensioni servono a individuare domande ricorrenti, non come conclusioni universali.",
    "Enough detail to complete one buyer decision":"Dettagli sufficienti per una decisione","A clearly defined purpose for every guide":"Uno scopo chiaro per ogni guida","Original checklists and decision frameworks":"Checklist e modelli decisionali originali","Visible source notes and update date":"Fonti e data di aggiornamento visibili","No fabricated review, delivery promise or price guarantee":"Nessuna recensione inventata, promessa di consegna o prezzo garantito",
    "Published":"Pubblicato","Updated":"Aggiornato","Independent guide":"Guida indipendente","On this page":"In questa pagina","Sources checked · 25 August 2026":"Fonti controllate · 25 agosto 2026","Research notes":"Note di ricerca","Sources support specific platform facts or identify recurring buyer questions. Community reports are not treated as official terms or guaranteed outcomes.":"Le fonti supportano fatti specifici o individuano domande ricorrenti. Le testimonianze della comunità non sono considerate condizioni ufficiali o risultati garantiti.","Continue checking":"Continua a verificare","Use the guide, then verify the live listing.":"Usa la guida, poi verifica l’inserzione attuale.","All articles":"Tutti gli articoli","Browse current catalog ↗":"Sfoglia il catalogo attuale ↗",
    "What a Hipobuy spreadsheet actually does":"Cosa fa davvero un foglio Hipobuy","Why Hipobuy sits between the listing and your address":"Perché Hipobuy si trova tra l’inserzione e il tuo indirizzo","Step 1: search by product intent, not hype":"Passo 1: cerca il prodotto, non l’hype","Step 2: run a pre-order cost screen":"Passo 2: controlla i costi prima dell’ordine","Step 3: wait for warehouse evidence":"Passo 3: attendi le prove dal magazzino","Step 4: consolidate with a parcel plan":"Passo 4: consolida con un piano del pacco","Step 5: compare shipping lines on the actual parcel":"Passo 5: confronta le linee sul pacco reale","Common spreadsheet mistakes":"Errori comuni con i fogli","The 60-second decision checklist":"Checklist decisionale in 60 secondi","A spreadsheet should make you slower at the right moment":"Un foglio deve rallentarti al momento giusto",
    "What “QC” means in a shopping-agent workflow":"Cosa significa “QC” nel flusso di un agente","Prepare before the item reaches the warehouse":"Preparati prima dell’arrivo in magazzino","Pass 1: confirm the order before judging quality":"Controllo 1: conferma l’ordine prima della qualità","Pass 2: read the overview photos":"Controllo 2: analizza le foto generali","Pass 3: inspect construction and finishing":"Controllo 3: esamina costruzione e finiture","Pass 4: treat measurements as data":"Controllo 4: tratta le misure come dati","When to request an extra photo":"Quando chiedere una foto aggiuntiva","Red light, yellow light and green light decisions":"Decisioni rosse, gialle e verdi","Returns are easier before international shipping—but not automatic":"I resi sono più semplici prima della spedizione internazionale, ma non automatici","A repeatable eight-point QC checklist":"Checklist QC ripetibile in otto punti","The most useful QC photo is the one tied to a decision":"La foto QC più utile è legata a una decisione",
    "Why the first price is not the delivered price":"Perché il primo prezzo non è quello finale","Build a delivered-cost model":"Costruisci un modello del costo finale","Actual weight versus volumetric weight":"Peso reale e peso volumetrico","Use the official estimator correctly":"Usa correttamente lo stimatore ufficiale","Does consolidation always save money?":"Consolidare fa sempre risparmiare?","Packing choices that change the quote":"Scelte d’imballaggio che cambiano il prezzo","How to compare shipping lines":"Come confrontare le linee di spedizione","What public reviews reveal—and what they do not":"Cosa rivelano le recensioni pubbliche e cosa no","Country-specific costs need country-specific checks":"I costi per paese richiedono controlli specifici","A practical pre-shipping comparison":"Confronto pratico prima della spedizione","Reduce surprises, not just the displayed price":"Riduci le sorprese, non solo il prezzo mostrato"
  }
};
