import type { Metadata } from "next";
import { ArticleCard, Breadcrumbs, Footer, Header, PageIntro } from "../components";
import { articles, PLANNED_ORIGIN } from "../data";

export const metadata: Metadata = { title: "FindQC Guides: QC Photos, Reviews, Shipping & Product Intelligence", description: "Independent FindQC research covering QC evidence, Product Intelligence, Real Hauls statistics, public review patterns and decision limits.", alternates: { canonical: `${PLANNED_ORIGIN}/articles` } };

export default function ArticlesPage() {
  return <><Header /><main><Breadcrumbs items={[{ label: "Articles" }]} /><PageIntro eyebrow="Independent field notes" title="Detailed enough to change a decision." description="Human-readable research for the moments between finding a listing, reviewing warehouse evidence and deciding what happens next." /><section className="shell page-content"><div className="article-grid article-hub">{articles.map((article) => <ArticleCard key={article.slug} article={article} />)}</div>
    <section className="content-roadmap"><div><span className="mini-label">PUBLISHING ORDER</span><h2>Build authority from the core task outward</h2><p>Start with the pages that answer what FindQC is and how to inspect evidence. Add operational and country-specific long tails only after the central topic cluster is internally linked.</p></div><ol><li><b>01</b><span><strong>How FindQC works</strong><small>findqc guide · qc finder · product intelligence</small></span></li><li><b>02</b><span><strong>How to read QC photos</strong><small>qc photos · warehouse qc checklist</small></span></li><li><b>03</b><span><strong>QC finder vs spreadsheet</strong><small>qc finder vs spreadsheet · qc finds</small></span></li><li><b>04</b><span><strong>Real Hauls and shipping data</strong><small>findqc shipping · haul shipping cost</small></span></li><li><b>05</b><span><strong>Real buyer review analysis</strong><small>findqc reviews · qc product reviews</small></span></li><li><b>06</b><span><strong>Seller, sizing and country routes</strong><small>seller reliability · volumetric weight · destination guides</small></span></li></ol></section>
    <div className="editorial-note"><span>EDITORIAL STANDARD</span><h2>Evidence before adjectives</h2><p>We distinguish official platform descriptions, public aggregate data, buyer comments, live destination facts, approximate conversions and exact-unit QC evidence. A page opening successfully is never presented as proof of seller or product quality.</p></div></section></main><Footer /></>;
}
