import type { Locale, Section } from "@/lib/site-data";

export type SectionDetail = {
  label: string;
  heading: string;
  paragraphs: [string, string];
  checks: [string, string, string];
};

export const sectionDetails: Record<Locale, Record<Section, SectionDetail>> = {
  en: {
    spreadsheet: {
      label: "How this index works",
      heading: "Use the Hacoo product-link index as a live research tool",
      paragraphs: [
        "The index is designed for discovery, not endorsement. Begin with a category or a short product phrase, open the current source page, and record the exact option that caught your attention. A useful row keeps the link, selected variant and check date together. That makes it possible to revisit the decision when a title, image, price or availability signal changes.",
        "Keep the index separate from the full spreadsheet guide. This page is the working entrance: search, filter and reach a current listing. The long guide explains how to verify, save and compare those links. Using the two pages for different jobs prevents a broad catalogue query from being confused with evidence about one product.",
      ],
      checks: ["Open the current source page", "Match the image and exact option", "Record the date before saving"],
    },
    finds: {
      label: "Editorial selection",
      heading: "Treat every Hacoo find as a candidate, not a verdict",
      paragraphs: [
        "The finds page keeps a small cross-section of current references visible so that different product types can be compared without an endless feed. Inclusion does not mean that an item is approved, authentic or permanently available. Each card is a research starting point whose title, image, variant and destination should still agree when you open it.",
        "A practical shortlist compares candidates against one brief: intended use, measurements, material evidence, construction details, open questions and likely handling needs. Add a dated note explaining why each candidate survived the first review, then reopen all finalists together so price or availability changes do not distort the comparison. Remove a link when the current page no longer supports the saved description. A replacement should satisfy the same brief rather than simply look similar. Compare the current listing rather than relying on a screenshot, and keep uncertainty visible when a material, dimension or option is not stated. If two candidates cannot be evaluated on the same evidence, record that gap instead of assigning a false winner. When a listing has several colours or sizes, save the exact option label and recheck it separately: a parent page can remain live after one variant disappears. This keeps the page useful as an editorial collection rather than turning it into an undated archive of attractive images.",
      ],
      checks: ["Confirm the destination", "Compare like-for-like variants", "Remove stale candidates"],
    },
    articles: {
      label: "Research library",
      heading: "Four long Hacoo guides, each answering a different question",
      paragraphs: [
        "The article library separates four search intents that are often mixed together: finding and saving product links, evaluating public reviews, reading visual quality evidence, and checking shipping information before commitment. Each article is long enough to explain the decision process, but it should not replace the live product page or the current terms of the service handling the transaction.",
        "Dates and evidence boundaries matter. Official information, publicly reported customer experience and editorial interpretation are different kinds of evidence and should not be blended into one claim. Review-style writing therefore explains source date, region and sample limits, while the QC and shipping guides focus on repeatable checks rather than promises about every listing. The article hub labels these purposes so readers can choose depth without opening four near-duplicate tutorials.",
      ],
      checks: ["Choose the guide by search intent", "Check the reviewed date", "Return to the live page before acting"],
    },
    guides: {
      label: "Decision workflow",
      heading: "Move from an interesting reference to a documented decision",
      paragraphs: [
        "A reliable workflow starts by defining the product brief before opening more tabs. Write down the use, non-negotiable detail and acceptable compromise, then search with the language used by the current category. Save only candidates that can be identified again through a stable link, image, option and date.",
        "Verification should narrow uncertainty in a fixed order: identity first, then measurements, material or construction, seller-page evidence, current price context and unresolved questions. Stop when a small shortlist answers the same brief. The guides are built to support that sequence, while the index and finds pages remain faster entry points.",
      ],
      checks: ["Define one clear brief", "Verify evidence in a fixed order", "Stop at a comparable shortlist"],
    },
    qc: {
      label: "Quick QC checklist",
      heading: "Use the QC page for a fast visual decision before the full guide",
      paragraphs: [
        "This page is the compact checkpoint: confirm identity, compare proportions, read visible measurements, inspect surface and construction, and note anything the photographs cannot prove. Start with the selected colour, size and model because a clearly photographed wrong option is still the wrong item. Only then zoom into stitching, edges, hardware or print placement.",
        "The long QC guide goes deeper into request wording, severity and decision categories. The short page should help you identify the next precise question, not imply that every link includes warehouse photographs or that an image can prove authenticity. Compare normal-angle views before close-ups, because lighting and compression can exaggerate small surface differences. When evidence is missing, ask for one targeted view rather than treating uncertainty as a pass. Keep that unresolved point attached to the saved candidate until it is answered.",
      ],
      checks: ["Confirm identity first", "Separate visible fact from inference", "Request one targeted missing view"],
    },
    shipping: {
      label: "Before checkout",
      heading: "Check product and destination variables before estimating delivery",
      paragraphs: [
        "Shipping decisions begin with the current item and destination, not a universal rate copied from an old post. Note the likely packed size, whether shape requires protective packaging, the destination region and any material restrictions that could change route eligibility. Treat every quote as dated until the responsible service confirms it for the actual parcel.",
        "The long shipping guide explains weight, volume, consolidation, tracking and regional differences in more detail. This page remains a pre-check: gather the inputs that make a later quote meaningful and avoid presenting one route or timeframe as permanent. Compare actual weight with possible volumetric weight, and record whether protective packaging changes the dimensions. Keep tracking expectations separate from processing time before dispatch, and note whether duties or local delivery charges are included or merely unknown. Recheck the offer immediately before payment or parcel submission.",
      ],
      checks: ["Estimate packed dimensions", "Verify destination eligibility", "Recheck the dated quote"],
    },
    faq: {
      label: "Scope and evidence",
      heading: "Answers about Hacoo links, reviews, QC and shipping",
      paragraphs: [
        "The FAQ explains what Hacoos.org does and does not do. It is an independent research index: it organises references and editorial guidance, but it does not sell, fulfil, inspect or guarantee products. A link can be useful while still requiring a fresh check of its destination, selected option and current transaction conditions.",
        "Questions about legitimacy, ratings and public experience need careful wording because sources cover different regions, dates and samples. Questions about QC and shipping also depend on the exact product and service involved. The answers below state those limits directly so a reader can decide what evidence is still missing before continuing.",
      ],
      checks: ["Know who handles the transaction", "Distinguish evidence from opinion", "Verify the exact current conditions"],
    },
  },
  de: {
    spreadsheet: {
      label: "So funktioniert der Index", heading: "Den Hacoo-Produktlink-Index als aktuelles Recherchewerkzeug nutzen",
      paragraphs: ["Der Index dient der Entdeckung, nicht als Empfehlung. Beginne mit einer Kategorie oder einem kurzen Produktbegriff, öffne die aktuelle Quellseite und notiere die genaue Option. Ein brauchbarer Eintrag hält Link, Variante und Prüfdatum zusammen. So lässt sich die Entscheidung erneut prüfen, wenn sich Titel, Bild, Preis oder Verfügbarkeit ändern.", "Index und ausführlicher Spreadsheet-Ratgeber haben verschiedene Aufgaben. Diese Seite ist der schnelle Einstieg für Suche, Filter und aktuelle Listings. Der Langartikel erklärt, wie Links geprüft, gespeichert und verglichen werden. Dadurch wird eine breite Katalogsuche nicht mit einem Nachweis für ein einzelnes Produkt verwechselt."],
      checks: ["Aktuelle Quellseite öffnen", "Bild und genaue Option abgleichen", "Prüfdatum festhalten"],
    },
    finds: {
      label: "Redaktionelle Auswahl", heading: "Jeden Hacoo-Fund als Kandidaten statt als Urteil behandeln",
      paragraphs: ["Die Finds-Seite zeigt eine kleine Auswahl aktueller Referenzen, damit verschiedene Produkttypen ohne endlosen Feed vergleichbar bleiben. Eine Aufnahme bedeutet weder Freigabe noch Echtheits- oder Verfügbarkeitsgarantie. Titel, Bild, Variante und Ziel müssen beim Öffnen weiterhin zusammenpassen.", "Eine sinnvolle Shortlist vergleicht Kandidaten mit demselben Brief: Nutzung, Maße, Materialbelege, Verarbeitung, offene Fragen und Handhabungsrisiken. Notiere mit Datum, warum jeder Kandidat die erste Prüfung bestanden hat, und öffne alle Finalisten gemeinsam erneut. Entferne einen Link, wenn die aktuelle Seite die gespeicherte Beschreibung nicht mehr stützt; ein Ersatz muss denselben Brief erfüllen und nicht nur ähnlich aussehen. So bleibt die Auswahl redaktionell und wird nicht zum undatierten Bilderarchiv."],
      checks: ["Zielseite bestätigen", "Gleiche Varianten vergleichen", "Veraltete Kandidaten entfernen"],
    },
    articles: {
      label: "Recherchebibliothek", heading: "Vier ausführliche Hacoo-Ratgeber für vier verschiedene Fragen",
      paragraphs: ["Die Artikel trennen Suchintentionen, die oft vermischt werden: Produktlinks finden und speichern, öffentliche Bewertungen einordnen, sichtbare Qualitätsmerkmale prüfen und Versandinformationen vor einer Entscheidung bewerten. Kein Artikel ersetzt die aktuelle Produktseite oder die Bedingungen des Dienstes, der die Transaktion abwickelt.", "Datum und Belegart sind entscheidend. Offizielle Information, öffentlich berichtete Kundenerfahrung und redaktionelle Analyse sind nicht dasselbe. Bewertungsartikel nennen daher Region, Datum und Stichprobenlimit; QC- und Versandtexte setzen auf wiederholbare Prüfungen statt Versprechen für jedes Listing. Der Artikelbereich kennzeichnet diese Aufgaben, damit Leser Tiefe wählen können, ohne vier fast gleiche Tutorials zu öffnen."],
      checks: ["Ratgeber nach Suchintention wählen", "Prüfdatum beachten", "Vor der Handlung zur Live-Seite zurückkehren"],
    },
    guides: {
      label: "Entscheidungsablauf", heading: "Aus einer interessanten Referenz eine dokumentierte Entscheidung machen",
      paragraphs: ["Ein verlässlicher Ablauf beginnt mit einem Produktbrief, bevor weitere Tabs geöffnet werden. Notiere Nutzung, unverzichtbares Merkmal und akzeptablen Kompromiss. Suche dann mit der Sprache der aktuellen Kategorie und speichere nur Kandidaten, die über Link, Bild, Option und Datum wiedergefunden werden können.", "Prüfe Unsicherheit in fester Reihenfolge: Identität, Maße, Material oder Konstruktion, Belege auf der Verkäuferseite, aktueller Preiskontext und offene Fragen. Stoppe bei einer kleinen, vergleichbaren Auswahl. Die Ratgeber unterstützen diesen Ablauf; Index und Finds bleiben die schnellen Einstiegspunkte."],
      checks: ["Einen klaren Brief definieren", "Belege in fester Reihenfolge prüfen", "Bei einer vergleichbaren Shortlist stoppen"],
    },
    qc: {
      label: "Kurze QC-Checkliste", heading: "Die QC-Seite für eine schnelle Sichtprüfung vor dem Langratgeber nutzen",
      paragraphs: ["Diese Seite ist der kompakte Kontrollpunkt: Identität bestätigen, Proportionen vergleichen, sichtbare Maße lesen, Oberfläche und Verarbeitung prüfen und fehlende Belege notieren. Beginne mit Farbe, Größe und Modell. Eine gut fotografierte falsche Option bleibt falsch. Erst danach zählen Nähte, Kanten, Hardware oder Druckposition.", "Der ausführliche QC-Ratgeber behandelt Anfrageformulierung, Schweregrad und Entscheidungskategorien. Die Kurzseite soll zur nächsten präzisen Frage führen. Sie behauptet weder QC-Fotos für jeden Link noch Echtheitsnachweise durch ein Bild. Vergleiche normale Ansichten vor Nahaufnahmen, da Licht und Kompression kleine Unterschiede übertreiben können. Fehlt Beleg, fordere eine gezielte Ansicht an."],
      checks: ["Identität zuerst bestätigen", "Sichtbaren Fakt von Annahme trennen", "Eine gezielte Ansicht anfordern"],
    },
    shipping: {
      label: "Vor dem Checkout", heading: "Produkt- und Zielvariablen vor einer Lieferprognose prüfen",
      paragraphs: ["Versandentscheidungen beginnen beim aktuellen Artikel und Ziel, nicht bei einer Universalrate aus einem alten Beitrag. Notiere wahrscheinliche Packmaße, nötigen Formschutz, Zielregion und Materialbeschränkungen. Jedes Angebot bleibt datiert, bis der verantwortliche Dienst es für das konkrete Paket bestätigt.", "Der ausführliche Versandratgeber erklärt Gewicht, Volumen, Konsolidierung, Tracking und regionale Unterschiede. Diese Seite bleibt der Vorabcheck: Sie sammelt Eingaben für ein sinnvolles Angebot und vermeidet dauerhafte Aussagen über Route oder Laufzeit. Vergleiche tatsächliches und mögliches Volumengewicht und notiere, ob Schutzverpackung die Maße verändert. Trenne Bearbeitungszeit vor dem Versand von der späteren Tracking-Erwartung. Direkt vor Zahlung oder Paketeinreichung erneut prüfen."],
      checks: ["Packmaße schätzen", "Zielberechtigung prüfen", "Datiertes Angebot erneut prüfen"],
    },
    faq: {
      label: "Umfang und Belege", heading: "Antworten zu Hacoo-Links, Bewertungen, QC und Versand",
      paragraphs: ["Die FAQ erklärt, was Hacoos.org leistet und was nicht. Die Seite ist ein unabhängiger Rechercheindex: Sie ordnet Referenzen und Hinweise, verkauft, versendet, prüft oder garantiert jedoch keine Produkte. Ein Link kann nützlich sein und trotzdem eine neue Prüfung von Ziel, Option und Bedingungen benötigen.", "Fragen zu Legitimität, Bewertungen und Erfahrungen brauchen vorsichtige Formulierungen, weil Quellen Region, Datum und Stichprobe unterscheiden. Auch QC und Versand hängen vom konkreten Produkt und Dienst ab. Die Antworten benennen diese Grenzen, damit fehlende Belege vor dem nächsten Schritt sichtbar werden."],
      checks: ["Verantwortlichen Dienst kennen", "Beleg und Meinung trennen", "Aktuelle Bedingungen prüfen"],
    },
  },
  fr: {
    spreadsheet: { label: "Fonctionnement de l’index", heading: "Utiliser l’index de liens produits Hacoo comme outil de recherche vivant", paragraphs: ["L’index sert à découvrir, pas à approuver. Partez d’une catégorie ou d’un terme court, ouvrez la page source actuelle et notez l’option exacte. Une entrée utile conserve ensemble le lien, la variante et la date de contrôle. Vous pourrez ainsi réexaminer votre choix si le titre, l’image, le prix ou la disponibilité change.", "L’index et le guide complet n’ont pas le même rôle. Cette page est l’entrée de travail pour rechercher, filtrer et atteindre une fiche actuelle. L’article long explique comment vérifier, enregistrer et comparer les liens. Cette séparation évite de confondre une recherche de catalogue avec une preuve concernant un produit."], checks: ["Ouvrir la page source actuelle", "Comparer l’image et l’option exacte", "Noter la date avant d’enregistrer"] },
    finds: { label: "Sélection éditoriale", heading: "Considérer chaque trouvaille Hacoo comme une candidate, pas un verdict", paragraphs: ["La sélection montre un petit éventail de références actuelles afin de comparer plusieurs types de produits sans flux infini. Une présence ne signifie ni approbation, ni authenticité, ni disponibilité durable. Le titre, l’image, la variante et la destination doivent encore correspondre à l’ouverture.", "Une liste courte utile compare les candidats selon le même besoin : usage, mesures, matière documentée, construction, questions ouvertes et contraintes de manipulation. Ajoutez une note datée expliquant pourquoi chaque candidat a passé le premier tri, puis rouvrez tous les finalistes ensemble. Retirez un lien lorsque la page actuelle ne confirme plus la description ; un remplacement doit répondre au même besoin et pas seulement lui ressembler. La page reste ainsi une collection éditoriale plutôt qu’une archive d’images sans date."], checks: ["Confirmer la destination", "Comparer des variantes équivalentes", "Retirer les références périmées"] },
    articles: { label: "Bibliothèque de recherche", heading: "Quatre guides Hacoo approfondis pour quatre questions distinctes", paragraphs: ["La bibliothèque sépare quatre intentions souvent mélangées : trouver et sauvegarder des liens, lire des avis publics, examiner des éléments visuels de qualité et vérifier la livraison avant de s’engager. Aucun article ne remplace la fiche actuelle ni les conditions du service qui gère la transaction.", "La date et la nature de la preuve comptent. Information officielle, témoignage public et analyse éditoriale ne sont pas équivalents. Les articles d’avis précisent donc région, date et limites de l’échantillon ; les guides QC et livraison privilégient des contrôles répétables plutôt que des promesses générales. Le centre d’articles indique ces rôles afin de choisir le bon niveau de détail sans ouvrir quatre tutoriels presque identiques."], checks: ["Choisir selon l’intention", "Vérifier la date de révision", "Revenir à la page active avant d’agir"] },
    guides: { label: "Parcours de décision", heading: "Passer d’une référence intéressante à une décision documentée", paragraphs: ["Un bon parcours commence par définir le besoin avant d’ouvrir davantage d’onglets. Notez l’usage, le détail indispensable et le compromis acceptable, puis recherchez avec le vocabulaire de la catégorie actuelle. Ne gardez que les candidats identifiables par un lien, une image, une option et une date.", "Réduisez l’incertitude dans un ordre fixe : identité, mesures, matière ou construction, preuves visibles sur la fiche, contexte de prix et questions restantes. Arrêtez-vous à une petite sélection comparable. Les guides soutiennent cette méthode ; l’index et les finds restent des entrées rapides."], checks: ["Définir un besoin clair", "Vérifier dans un ordre fixe", "S’arrêter à une liste comparable"] },
    qc: { label: "Liste QC rapide", heading: "Utiliser la page QC pour une décision visuelle rapide avant le guide complet", paragraphs: ["Cette page est le contrôle compact : confirmer l’identité, comparer les proportions, lire les mesures visibles, inspecter surface et construction, puis noter ce que les photos ne prouvent pas. Commencez par couleur, taille et modèle. Une mauvaise option bien photographiée reste une mauvaise option.", "Le guide QC complet approfondit la formulation des demandes, la gravité et les catégories de décision. La page courte sert à formuler la prochaine question précise ; elle ne promet ni photos d’entrepôt pour chaque lien, ni preuve d’authenticité par l’image. Comparez les vues normales avant les gros plans, car lumière et compression peuvent amplifier de petites différences. Si une vue manque, demandez-la directement."], checks: ["Confirmer d’abord l’identité", "Séparer fait visible et déduction", "Demander une vue ciblée"] },
    shipping: { label: "Avant le paiement", heading: "Vérifier le produit et la destination avant d’estimer la livraison", paragraphs: ["Une décision de livraison part de l’article et de la destination actuels, pas d’un tarif universel repris d’un ancien message. Notez la taille emballée probable, la protection nécessaire, la région de destination et les restrictions de matière. Tout devis reste daté jusqu’à confirmation pour le colis réel.", "Le guide complet détaille poids, volume, regroupement, tracking et écarts régionaux. Cette page reste un précontrôle : réunir les données qui rendent le devis utile et éviter de présenter une ligne ou un délai comme permanent. Comparez poids réel et poids volumétrique possible, puis notez si la protection modifie les dimensions. Séparez le temps de traitement avant expédition de l’attente de tracking. Vérifiez à nouveau juste avant paiement ou soumission du colis."], checks: ["Estimer les dimensions emballées", "Vérifier l’éligibilité de la destination", "Recontrôler le devis daté"] },
    faq: { label: "Périmètre et preuves", heading: "Réponses sur les liens Hacoo, les avis, le QC et la livraison", paragraphs: ["La FAQ explique ce que Hacoos.org fait et ne fait pas. Cet index indépendant organise références et conseils, mais ne vend, n’expédie, n’inspecte ni ne garantit les produits. Un lien utile exige encore une vérification actuelle de sa destination, de l’option et des conditions de transaction.", "Les questions de légitimité, de notes et d’expérience exigent de la prudence car les sources diffèrent par région, date et échantillon. QC et livraison dépendent aussi du produit et du service exacts. Les réponses rendent ces limites visibles avant de poursuivre."], checks: ["Identifier le responsable de la transaction", "Distinguer preuve et opinion", "Vérifier les conditions actuelles"] },
  },
  es: {
    spreadsheet: { label: "Cómo funciona el índice", heading: "Usa el índice de enlaces Hacoo como herramienta de investigación activa", paragraphs: ["El índice sirve para descubrir, no para aprobar. Empieza con una categoría o una frase corta, abre la página fuente actual y anota la opción exacta. Una entrada útil mantiene juntos enlace, variante y fecha de revisión. Así podrás comprobar de nuevo la decisión si cambian título, imagen, precio o disponibilidad.", "El índice y la guía larga cumplen trabajos distintos. Esta página es la entrada práctica para buscar, filtrar y llegar a una ficha actual. El artículo explica cómo verificar, guardar y comparar enlaces. Separarlos evita confundir una búsqueda amplia con pruebas sobre un producto concreto."], checks: ["Abrir la página fuente actual", "Comparar imagen y opción exacta", "Registrar la fecha"] },
    finds: { label: "Selección editorial", heading: "Trata cada hallazgo Hacoo como candidato, no como veredicto", paragraphs: ["La selección mantiene visibles pocas referencias actuales para comparar tipos de producto sin un feed infinito. Incluir una ficha no significa aprobarla ni garantizar autenticidad o disponibilidad. Título, imagen, variante y destino deben seguir coincidiendo al abrirla.", "Una lista corta útil compara candidatos con el mismo objetivo: uso, medidas, pruebas de material, construcción, preguntas abiertas y necesidades de manipulación. Añade una nota fechada que explique por qué cada candidato superó la primera revisión y vuelve a abrir todos los finalistas juntos. Elimina un enlace si la página actual ya no sostiene la descripción; un sustituto debe cumplir el mismo objetivo y no solo parecerse. Así la selección no se convierte en un archivo de imágenes sin fecha."], checks: ["Confirmar el destino", "Comparar variantes equivalentes", "Eliminar candidatos obsoletos"] },
    articles: { label: "Biblioteca de investigación", heading: "Cuatro guías Hacoo extensas para cuatro preguntas diferentes", paragraphs: ["La biblioteca separa intenciones que suelen mezclarse: encontrar y guardar enlaces, valorar opiniones públicas, leer pruebas visuales de calidad y revisar el envío antes de comprometerse. Ningún artículo sustituye la ficha activa ni las condiciones del servicio responsable de la transacción.", "La fecha y el tipo de evidencia importan. Información oficial, experiencia pública y análisis editorial no son lo mismo. Los textos de opiniones indican región, fecha y límites de muestra; QC y envío se centran en comprobaciones repetibles, no en promesas para todas las fichas. El centro de artículos identifica esas funciones para elegir profundidad sin abrir cuatro tutoriales casi iguales."], checks: ["Elegir según la intención", "Mirar la fecha de revisión", "Volver a la página activa"] },
    guides: { label: "Flujo de decisión", heading: "Convierte una referencia interesante en una decisión documentada", paragraphs: ["Un flujo fiable empieza por definir el objetivo antes de abrir más pestañas. Anota uso, requisito imprescindible y compromiso aceptable; después busca con el lenguaje de la categoría actual. Guarda solo candidatos que puedan identificarse otra vez mediante enlace, imagen, opción y fecha.", "Reduce la incertidumbre en orden: identidad, medidas, material o construcción, pruebas de la ficha, contexto de precio y dudas pendientes. Detente con una lista corta comparable. Las guías apoyan ese proceso; índice y hallazgos siguen siendo entradas rápidas."], checks: ["Definir un objetivo claro", "Comprobar en orden fijo", "Detenerse con una lista comparable"] },
    qc: { label: "Lista QC rápida", heading: "Usa la página QC para una decisión visual rápida antes de la guía completa", paragraphs: ["Esta página es el punto de control compacto: confirma identidad, compara proporciones, lee medidas visibles, revisa superficie y construcción y apunta lo que las fotos no demuestran. Empieza por color, talla y modelo. Una opción equivocada bien fotografiada sigue siendo equivocada.", "La guía QC completa profundiza en cómo pedir pruebas, valorar gravedad y clasificar decisiones. La página corta ayuda a formular la siguiente pregunta precisa; no promete fotos de almacén para cada enlace ni autenticidad demostrada por una imagen. Compara vistas normales antes de primeros planos, porque luz y compresión pueden exagerar pequeñas diferencias. Pide una vista concreta cuando falte evidencia."], checks: ["Confirmar primero la identidad", "Separar hecho e inferencia", "Pedir una vista específica"] },
    shipping: { label: "Antes de pagar", heading: "Comprueba producto y destino antes de estimar la entrega", paragraphs: ["La decisión de envío empieza con el artículo y destino actuales, no con una tarifa universal tomada de una publicación antigua. Anota tamaño embalado probable, protección necesaria, región y restricciones de material. Todo presupuesto está fechado hasta que el servicio responsable lo confirme para el paquete real.", "La guía larga explica peso, volumen, consolidación, tracking y diferencias regionales. Esta página es un control previo: reúne los datos que hacen útil un presupuesto y evita presentar una ruta o plazo como permanente. Compara peso real y posible peso volumétrico, y anota si el embalaje protector cambia las medidas. Separa el tiempo de procesamiento previo del tiempo de tracking. Comprueba de nuevo justo antes del pago o envío del paquete."], checks: ["Estimar dimensiones embaladas", "Verificar elegibilidad del destino", "Revisar el presupuesto fechado"] },
    faq: { label: "Alcance y evidencia", heading: "Respuestas sobre enlaces Hacoo, opiniones, QC y envío", paragraphs: ["La FAQ explica qué hace y qué no hace Hacoos.org. Es un índice independiente que organiza referencias y orientación, pero no vende, envía, inspecciona ni garantiza productos. Un enlace útil todavía exige revisar destino, opción y condiciones actuales.", "Las preguntas sobre legitimidad, puntuaciones y experiencias requieren cautela porque las fuentes cubren regiones, fechas y muestras distintas. QC y envío también dependen del producto y servicio exactos. Las respuestas dejan visibles esos límites antes de continuar."], checks: ["Saber quién gestiona la transacción", "Distinguir evidencia y opinión", "Verificar condiciones actuales"] },
  },
  it: {
    spreadsheet: { label: "Come funziona l’indice", heading: "Usa l’indice di link Hacoo come strumento di ricerca aggiornato", paragraphs: ["L’indice serve alla scoperta, non all’approvazione. Parti da una categoria o da una frase breve, apri la pagina sorgente attuale e annota l’opzione esatta. Una voce utile conserva link, variante e data di controllo. Così potrai rivalutare la scelta se cambiano titolo, immagine, prezzo o disponibilità.", "Indice e guida completa svolgono compiti diversi. Questa pagina è l’ingresso operativo per cercare, filtrare e raggiungere una scheda attuale. L’articolo lungo spiega come verificare, salvare e confrontare i link. La separazione evita di confondere una ricerca ampia con prove su un singolo prodotto."], checks: ["Aprire la pagina sorgente attuale", "Confrontare immagine e opzione", "Annotare la data"] },
    finds: { label: "Selezione editoriale", heading: "Considera ogni Hacoo find un candidato, non un verdetto", paragraphs: ["La selezione mostra poche referenze attuali per confrontare tipi di prodotto senza un feed infinito. L’inclusione non equivale ad approvazione né garantisce autenticità o disponibilità. Titolo, immagine, variante e destinazione devono ancora coincidere quando apri la pagina.", "Una shortlist utile confronta candidati con lo stesso obiettivo: uso, misure, prove sul materiale, costruzione, domande aperte e necessità di protezione. Aggiungi una nota datata sul motivo per cui ogni candidato ha superato il primo controllo, poi riapri insieme tutti i finalisti. Rimuovi un link se la pagina attuale non sostiene più la descrizione; un sostituto deve rispondere allo stesso brief e non solo apparire simile. La raccolta resta così editoriale e non diventa un archivio senza data."], checks: ["Confermare la destinazione", "Confrontare varianti equivalenti", "Rimuovere candidati obsoleti"] },
    articles: { label: "Biblioteca di ricerca", heading: "Quattro guide Hacoo approfondite per quattro domande distinte", paragraphs: ["La biblioteca separa intenzioni spesso mescolate: trovare e salvare link, valutare recensioni pubbliche, leggere prove visive di qualità e controllare la spedizione prima di impegnarsi. Nessun articolo sostituisce la scheda corrente o le condizioni del servizio responsabile della transazione.", "Data e tipo di evidenza contano. Informazione ufficiale, esperienza pubblica e analisi editoriale non sono la stessa cosa. Le recensioni indicano regione, data e limiti del campione; QC e spedizione usano controlli ripetibili invece di promesse per ogni listing. Il centro articoli distingue questi scopi per scegliere la profondità senza aprire quattro tutorial quasi identici."], checks: ["Scegliere per intento", "Controllare la data", "Tornare alla pagina attiva"] },
    guides: { label: "Percorso decisionale", heading: "Trasforma una referenza interessante in una decisione documentata", paragraphs: ["Un percorso affidabile parte da un brief prima di aprire altre schede. Annota uso, requisito indispensabile e compromesso accettabile, poi cerca con il linguaggio della categoria attuale. Salva solo candidati identificabili tramite link, immagine, opzione e data.", "Riduci l’incertezza in ordine fisso: identità, misure, materiale o costruzione, prove della scheda, contesto di prezzo e domande residue. Fermati a una shortlist comparabile. Le guide sostengono il processo; indice e finds restano ingressi rapidi."], checks: ["Definire un brief chiaro", "Verificare in ordine fisso", "Fermarsi a una shortlist comparabile"] },
    qc: { label: "Checklist QC rapida", heading: "Usa la pagina QC per una decisione visiva rapida prima della guida completa", paragraphs: ["Questa pagina è il controllo compatto: conferma identità, confronta proporzioni, leggi misure visibili, esamina superficie e costruzione e annota ciò che le foto non provano. Parti da colore, taglia e modello. Un’opzione sbagliata ben fotografata resta sbagliata.", "La guida QC completa approfondisce richieste, gravità e categorie decisionali. La pagina breve aiuta a formulare la prossima domanda precisa; non promette foto di magazzino per ogni link né autenticità provata da un’immagine. Confronta viste normali prima dei primi piani, perché luce e compressione possono amplificare piccole differenze. Se manca una prova, chiedi una vista mirata."], checks: ["Confermare prima l’identità", "Separare fatto e deduzione", "Chiedere una vista mirata"] },
    shipping: { label: "Prima del pagamento", heading: "Controlla prodotto e destinazione prima di stimare la consegna", paragraphs: ["La decisione di spedizione parte dall’articolo e dalla destinazione attuali, non da una tariffa universale copiata da un vecchio post. Annota dimensioni imballate probabili, protezione necessaria, regione e restrizioni di materiale. Ogni preventivo resta datato finché il servizio non lo conferma per il pacco reale.", "La guida lunga spiega peso, volume, consolidamento, tracking e differenze regionali. Questa pagina è un pre-controllo: raccoglie i dati che rendono utile il preventivo ed evita di presentare rotta o tempi come permanenti. Confronta peso reale e possibile peso volumetrico e annota se la protezione modifica le dimensioni. Separa il tempo di elaborazione prima della partenza dall’attesa del tracking. Ricontrolla subito prima del pagamento o invio del pacco."], checks: ["Stimare dimensioni imballate", "Verificare la destinazione", "Ricontrollare il preventivo"] },
    faq: { label: "Ambito ed evidenze", heading: "Risposte su link Hacoo, recensioni, QC e spedizione", paragraphs: ["La FAQ chiarisce cosa fa e non fa Hacoos.org. È un indice indipendente che organizza referenze e indicazioni, ma non vende, spedisce, ispeziona o garantisce prodotti. Un link utile richiede comunque una verifica attuale di destinazione, opzione e condizioni.", "Le domande su legittimità, punteggi ed esperienze richiedono cautela perché le fonti coprono regioni, date e campioni diversi. Anche QC e spedizione dipendono dal prodotto e servizio esatti. Le risposte rendono visibili questi limiti prima di procedere."], checks: ["Conoscere chi gestisce la transazione", "Distinguere prova e opinione", "Verificare le condizioni attuali"] },
  },
  pt: {
    spreadsheet: { label: "Como funciona o índice", heading: "Use o índice de links Hacoo como ferramenta de pesquisa atual", paragraphs: ["O índice serve para descoberta, não para aprovação. Comece por uma categoria ou frase curta, abra a página de origem atual e registe a opção exata. Uma entrada útil mantém ligação, variante e data de verificação juntas. Assim pode rever a decisão se título, imagem, preço ou disponibilidade mudar.", "O índice e o guia completo têm funções diferentes. Esta página é a entrada prática para pesquisar, filtrar e chegar a uma ficha atual. O artigo longo explica como verificar, guardar e comparar ligações. A separação evita confundir uma pesquisa ampla com prova sobre um produto específico."], checks: ["Abrir a página de origem atual", "Comparar imagem e opção exata", "Registar a data"] },
    finds: { label: "Seleção editorial", heading: "Trate cada achado Hacoo como candidato, não como veredicto", paragraphs: ["A seleção mostra poucas referências atuais para comparar tipos de produto sem um feed infinito. A inclusão não significa aprovação nem garante autenticidade ou disponibilidade. Título, imagem, variante e destino ainda devem coincidir quando abrir a página.", "Uma shortlist útil compara candidatos com o mesmo objetivo: uso, medidas, provas de material, construção, questões abertas e necessidades de proteção. Adicione uma nota datada sobre por que cada candidato passou a primeira revisão e volte a abrir todos os finalistas juntos. Remova uma ligação se a página atual já não sustentar a descrição; uma substituição deve cumprir o mesmo objetivo e não apenas parecer semelhante. Assim a coleção continua editorial e não se torna arquivo de imagens sem data."], checks: ["Confirmar o destino", "Comparar variantes equivalentes", "Remover candidatos desatualizados"] },
    articles: { label: "Biblioteca de pesquisa", heading: "Quatro guias Hacoo extensos para quatro perguntas distintas", paragraphs: ["A biblioteca separa intenções muitas vezes misturadas: encontrar e guardar ligações, avaliar avaliações públicas, ler provas visuais de qualidade e verificar envio antes de avançar. Nenhum artigo substitui a ficha atual nem as condições do serviço responsável pela transação.", "Data e tipo de prova importam. Informação oficial, experiência pública e análise editorial não são iguais. Os artigos de avaliações indicam região, data e limites da amostra; QC e envio usam verificações repetíveis em vez de promessas para todas as fichas. O centro de artigos identifica essas funções para escolher profundidade sem abrir quatro tutoriais quase iguais."], checks: ["Escolher pelo objetivo", "Verificar a data", "Voltar à página ativa"] },
    guides: { label: "Fluxo de decisão", heading: "Transforme uma referência interessante numa decisão documentada", paragraphs: ["Um fluxo fiável começa por definir o objetivo antes de abrir mais separadores. Registe uso, requisito indispensável e compromisso aceitável; depois pesquise com a linguagem da categoria atual. Guarde apenas candidatos identificáveis por ligação, imagem, opção e data.", "Reduza a incerteza em ordem fixa: identidade, medidas, material ou construção, provas da ficha, contexto de preço e dúvidas restantes. Pare numa shortlist comparável. Os guias apoiam esse processo; índice e achados continuam entradas rápidas."], checks: ["Definir um objetivo claro", "Verificar numa ordem fixa", "Parar numa lista comparável"] },
    qc: { label: "Checklist QC rápida", heading: "Use a página QC para uma decisão visual rápida antes do guia completo", paragraphs: ["Esta página é o controlo compacto: confirme identidade, compare proporções, leia medidas visíveis, examine superfície e construção e registe o que as fotos não provam. Comece por cor, tamanho e modelo. Uma opção errada bem fotografada continua errada.", "O guia QC completo aprofunda pedidos, gravidade e categorias de decisão. A página curta ajuda a formular a próxima pergunta precisa; não promete fotos de armazém para cada ligação nem autenticidade provada por imagem. Compare vistas normais antes de aproximações, pois luz e compressão podem exagerar pequenas diferenças. Se faltar prova, peça uma vista direcionada."], checks: ["Confirmar primeiro a identidade", "Separar facto e inferência", "Pedir uma vista direcionada"] },
    shipping: { label: "Antes do pagamento", heading: "Verifique produto e destino antes de estimar a entrega", paragraphs: ["A decisão de envio começa no artigo e destino atuais, não numa tarifa universal copiada de uma publicação antiga. Registe tamanho embalado provável, proteção necessária, região e restrições de material. Cada orçamento permanece datado até o serviço responsável o confirmar para o pacote real.", "O guia longo explica peso, volume, consolidação, tracking e diferenças regionais. Esta página é um pré-controlo: reúne dados que tornam o orçamento útil e evita apresentar rota ou prazo como permanente. Compare peso real e possível peso volumétrico, anotando se a proteção muda as dimensões. Separe o tempo de processamento antes do envio da expectativa de tracking. Verifique novamente antes do pagamento ou submissão do pacote."], checks: ["Estimar dimensões embaladas", "Verificar elegibilidade do destino", "Rever o orçamento datado"] },
    faq: { label: "Âmbito e provas", heading: "Respostas sobre links Hacoo, avaliações, QC e envio", paragraphs: ["A FAQ explica o que Hacoos.org faz e não faz. É um índice independente que organiza referências e orientação, mas não vende, envia, inspeciona ou garante produtos. Uma ligação útil ainda exige verificação atual de destino, opção e condições.", "Questões sobre legitimidade, pontuações e experiências exigem cautela porque as fontes cobrem regiões, datas e amostras diferentes. QC e envio também dependem do produto e serviço exatos. As respostas tornam esses limites visíveis antes de continuar."], checks: ["Saber quem gere a transação", "Distinguir prova e opinião", "Verificar condições atuais"] },
  },
};
