const LEGAL_COPY = {
  es: {
    reviewed: "Revisado el 26 de agosto de 2026",
    contact: { label: "Contacto", title: ["Las correcciones", "mejoran las guías."], intro: "La dirección editorial se activará cuando se conecte el dominio personalizado. Durante esta revisión, envía correcciones factuales, enlaces rotos o avisos de derechos por el mismo canal que compartió la vista previa e incluye la URL exacta de Hacoos.", important: "Importante", note: "Hacoos no procesa pedidos ni puede prestar asistencia sobre transacciones realizadas en un sitio externo." },
    privacy: { title: "Política de privacidad", intro: "Esta política explica el enfoque de privacidad de Hacoos, una guía editorial y de descubrimiento independiente.", sections: [["Información tratada","El sitio no ofrece cuentas ni acepta pagos. Los registros normales del alojamiento pueden incluir dirección IP, navegador, página de referencia y URL solicitada para seguridad y rendimiento."],["Sitios externos","Los enlaces abren un catálogo independiente, que funciona con su propia política de privacidad y sus propios controles."],["Cookies y analítica","No se incluyen de forma intencionada cookies publicitarias ni de analítica de comportamiento. Si se añaden, esta política y el consentimiento necesario se actualizarán antes."],["Contacto","La dirección de privacidad se activará con el dominio personalizado. No envíes a Hacoos datos innecesarios de pedidos, pagos u otra información sensible."]] },
    terms: { title: "Condiciones de uso", intro: "Estas condiciones describen la función, los límites y las prácticas de enlaces externos de Hacoos.", sections: [["Servicio informativo independiente","Hacoos es un recurso editorial y de navegación independiente. No está afiliado, respaldado ni operado por Hacoo ni por ningún marketplace o plataforma."],["Sin ventas ni pagos","Hacoos no vende, acepta pagos, procesa pedidos ni controla anuncios externos. Las transacciones realizadas fuera del sitio corresponden al usuario y al servicio externo."],["Exactitud e información cambiante","Intentamos aportar contexto útil, pero precios, imágenes, disponibilidad, especificaciones, envío y políticas externas pueden cambiar. Debes confirmar los datos actuales en el destino."],["Propiedad intelectual","Los nombres e imágenes de terceros se usan para identificación, comentario y navegación. Los derechos pertenecen a sus titulares."],["Limitación","El uso del sitio y de los enlaces externos queda a criterio del usuario. Hacoos no garantiza calidad, legalidad, idoneidad, entrega ni actuación de terceros."]] },
  },
  fr: {
    reviewed: "Révisé le 26 août 2026",
    contact: { label: "Contact", title: ["Les corrections", "améliorent les guides."], intro: "L’adresse éditoriale sera activée lorsque le domaine personnalisé sera connecté. Pour cette version de contrôle, envoyez les corrections factuelles, liens rompus ou demandes relatives aux droits par le canal ayant partagé l’aperçu, avec l’URL Hacoos exacte.", important: "Important", note: "Hacoos ne traite pas les commandes et ne peut pas assurer le support de transactions réalisées sur un site externe." },
    privacy: { title: "Politique de confidentialité", intro: "Cette politique explique l’approche de Hacoos, guide indépendant de découverte et de rédaction.", sections: [["Informations traitées","Le site ne propose pas de compte et n’accepte aucun paiement. Les journaux d’hébergement peuvent inclure adresse IP, navigateur, page d’origine et URL demandée à des fins de sécurité et de performance."],["Sites externes","Les liens ouvrent un catalogue distinct soumis à sa propre politique de confidentialité et à ses propres contrôles."],["Cookies et mesure","Aucun cookie publicitaire ou d’analyse comportementale n’est volontairement intégré. Si de tels outils sont ajoutés, cette politique et le consentement requis seront d’abord mis à jour."],["Contact","L’adresse de confidentialité sera activée avec le domaine personnalisé. N’envoyez pas à Hacoos de données inutiles de commande, de paiement ou d’autres informations sensibles."]] },
    terms: { title: "Conditions d’utilisation", intro: "Ces conditions décrivent le rôle, les limites et les pratiques de liens externes de Hacoos.", sections: [["Service d’information indépendant","Hacoos est une ressource éditoriale et de navigation indépendante, sans affiliation, approbation ou exploitation par Hacoo ou une place de marché."],["Aucune vente ni transaction","Hacoos ne vend pas, n’accepte aucun paiement, ne traite aucune commande et ne contrôle pas les annonces externes."],["Exactitude et changements","Nous visons un contexte utile, mais prix, images, disponibilité, caractéristiques, livraison et politiques externes peuvent changer. Vérifiez les informations actuelles sur la destination."],["Propriété intellectuelle","Les noms et images de tiers servent uniquement à l’identification, au commentaire et à la navigation. Les droits restent à leurs titulaires."],["Limitation","L’utilisation du site et des liens externes relève du choix de l’utilisateur. Hacoos ne garantit ni qualité, légalité, adéquation, livraison ni prestation de tiers."]] },
  },
  de: {
    reviewed: "Geprüft am 26. August 2026",
    contact: { label: "Kontakt", title: ["Korrekturen machen", "Ratgeber besser."], intro: "Die redaktionelle Kontaktadresse wird aktiviert, sobald die eigene Domain verbunden ist. Sende in dieser Prüfversion sachliche Korrekturen, defekte Links oder Rechtehinweise über denselben Kanal, über den die Vorschau geteilt wurde, und nenne die genaue Hacoos-URL.", important: "Wichtig", note: "Hacoos bearbeitet keine Bestellungen und kann keinen Support für Transaktionen auf externen Websites leisten." },
    privacy: { title: "Datenschutzerklärung", intro: "Diese Erklärung beschreibt den Datenschutzansatz von Hacoos als unabhängigem Recherche- und Redaktionsratgeber.", sections: [["Verarbeitete Informationen","Die Website bietet keine Konten und nimmt keine Zahlungen an. Übliche Hosting-Protokolle können IP-Adresse, Browser, verweisende Seite und aufgerufene URL für Sicherheit und Leistung enthalten."],["Externe Websites","Links öffnen einen getrennten Zielkatalog mit eigener Datenschutzerklärung und eigenen Kontrollen."],["Cookies und Analyse","Werbe- oder verhaltensbezogene Analyse-Cookies werden nicht absichtlich eingebunden. Vor einer späteren Ergänzung werden diese Erklärung und eine erforderliche Einwilligung aktualisiert."],["Kontakt","Die Datenschutzadresse wird mit der eigenen Domain aktiviert. Sende Hacoos keine unnötigen Bestell-, Zahlungs- oder anderen sensiblen Daten."]] },
    terms: { title: "Nutzungsbedingungen", intro: "Diese Bedingungen beschreiben Rolle, Grenzen und externe Verlinkung von Hacoos.", sections: [["Unabhängiger Informationsdienst","Hacoos ist eine unabhängige redaktionelle Navigationsressource und weder mit Hacoo noch mit einem Marktplatz verbunden, von ihnen empfohlen oder betrieben."],["Kein Verkauf und keine Abwicklung","Hacoos verkauft nichts, nimmt keine Zahlungen an, bearbeitet keine Bestellungen und kontrolliert keine externen Angebote."],["Genauigkeit und Änderungen","Wir bieten nützlichen Kontext, doch externe Preise, Bilder, Verfügbarkeit, Spezifikationen, Versandoptionen und Richtlinien können sich ändern. Prüfe aktuelle Angaben auf der Zielseite."],["Geistiges Eigentum","Namen und Bilder Dritter dienen nur der Identifikation, Einordnung und Navigation. Die Rechte verbleiben bei ihren Inhabern."],["Begrenzung","Die Nutzung der Website und externer Links erfolgt nach eigenem Ermessen. Hacoos garantiert weder Qualität, Rechtmäßigkeit, Eignung, Lieferung noch Leistungen Dritter."]] },
  },
  it: {
    reviewed: "Revisionato il 26 agosto 2026",
    contact: { label: "Contatti", title: ["Le correzioni", "migliorano le guide."], intro: "L’indirizzo editoriale sarà attivato quando verrà collegato il dominio personalizzato. Per questa versione di controllo, invia correzioni fattuali, link non funzionanti o segnalazioni sui diritti tramite lo stesso canale che ha condiviso l’anteprima e indica l’URL Hacoos esatto.", important: "Importante", note: "Hacoos non gestisce ordini e non può fornire assistenza per transazioni effettuate su siti esterni." },
    privacy: { title: "Informativa sulla privacy", intro: "Questa informativa descrive l’approccio alla privacy di Hacoos, guida editoriale e di scoperta indipendente.", sections: [["Informazioni trattate","Il sito non offre account e non accetta pagamenti. I normali log di hosting possono includere indirizzo IP, browser, pagina di provenienza e URL richiesti per sicurezza e prestazioni."],["Siti esterni","I link aprono un catalogo separato che opera secondo la propria informativa e i propri controlli."],["Cookie e analisi","Non sono inseriti intenzionalmente cookie pubblicitari o di analisi comportamentale. Se verranno aggiunti strumenti simili, saranno prima aggiornati questa informativa e il consenso necessario."],["Contatti","L’indirizzo privacy sarà attivato con il dominio personalizzato. Non inviare a Hacoos dati non necessari su ordini, pagamenti o altre informazioni sensibili."]] },
    terms: { title: "Termini di utilizzo", intro: "Questi termini descrivono il ruolo, i limiti e le pratiche di collegamento esterno di Hacoos.", sections: [["Servizio informativo indipendente","Hacoos è una risorsa editoriale e di navigazione indipendente, non affiliata, approvata o gestita da Hacoo né da marketplace o piattaforme."],["Nessuna vendita o transazione","Hacoos non vende, non accetta pagamenti, non elabora ordini e non controlla inserzioni esterne."],["Accuratezza e cambiamenti","Cerchiamo di offrire contesto utile, ma prezzi, immagini, disponibilità, specifiche, spedizione e politiche esterne possono cambiare. Verifica i dati attuali sulla destinazione."],["Proprietà intellettuale","Nomi e immagini di terzi sono usati solo per identificazione, commento e navigazione. I diritti restano ai rispettivi titolari."],["Limitazione","L’uso del sito e dei link esterni è a discrezione dell’utente. Hacoos non garantisce qualità, legalità, idoneità, consegna o prestazioni di terzi."]] },
  },
  pt: {
    reviewed: "Revisto em 26 de agosto de 2026",
    contact: { label: "Contacto", title: ["As correções", "melhoram os guias."], intro: "O endereço editorial será ativado quando o domínio personalizado estiver ligado. Nesta versão de revisão, envie correções factuais, links quebrados ou questões de direitos pelo mesmo canal que partilhou a pré-visualização e inclua o URL Hacoos exato.", important: "Importante", note: "O Hacoos não processa encomendas nem pode prestar apoio a transações realizadas num site externo." },
    privacy: { title: "Política de privacidade", intro: "Esta política explica a abordagem de privacidade do Hacoos, um guia editorial e de descoberta independente.", sections: [["Informação tratada","O site não disponibiliza contas nem aceita pagamentos. Os registos normais do alojamento podem incluir endereço IP, navegador, página de referência e URL pedido para segurança e desempenho."],["Sites externos","Os links abrem um catálogo separado que funciona segundo a sua própria política de privacidade e os seus controlos."],["Cookies e análise","Não são incluídos intencionalmente cookies publicitários ou de análise comportamental. Se forem acrescentados, esta política e o consentimento necessário serão atualizados primeiro."],["Contacto","O endereço de privacidade será ativado com o domínio personalizado. Não envie ao Hacoos dados desnecessários de encomendas, pagamentos ou outras informações sensíveis."]] },
    terms: { title: "Termos de utilização", intro: "Estes termos descrevem a função, os limites e as práticas de links externos do Hacoos.", sections: [["Serviço de informação independente","O Hacoos é um recurso editorial e de navegação independente. Não é afiliado, aprovado nem operado pela Hacoo ou por qualquer marketplace ou plataforma."],["Sem vendas ou processamento","O Hacoos não vende, aceita pagamentos, processa encomendas ou controla anúncios externos."],["Exatidão e alterações","Procuramos oferecer contexto útil, mas preços, imagens, disponibilidade, especificações, envio e políticas externas podem mudar. Confirme os dados atuais no destino."],["Propriedade intelectual","Nomes e imagens de terceiros são usados apenas para identificação, comentário e navegação. Os direitos permanecem com os respetivos titulares."],["Limitação","A utilização do site e de links externos fica ao critério do utilizador. O Hacoos não garante qualidade, legalidade, adequação, entrega ou desempenho de terceiros."]] },
  },
};

export function getLegalCopy(locale) { return LEGAL_COPY[locale] || LEGAL_COPY.es; }

export function LocalizedContact({ locale }) {
  const page=getLegalCopy(locale).contact;
  return <section className="page-hero simple-hero full-page" lang={locale}><div className="wrap narrow"><span className="section-label">{page.label}</span><h1>{page.title[0]}<br/><em>{page.title[1]}</em></h1><p>{page.intro}</p><div className="contact-note"><strong>{page.important}</strong><p>{page.note}</p></div></div></section>;
}

function Legal({ locale, page }) {
  const copy=getLegalCopy(locale);
  return <section className="legal wrap" lang={locale}><span className="section-label">{copy.reviewed}</span><h1>{page.title}</h1><p className="legal-intro">{page.intro}</p>{page.sections.map(([title,text])=><div key={title}><h2>{title}</h2><p>{text}</p></div>)}</section>;
}

export function LocalizedPrivacy({ locale }) { return <Legal locale={locale} page={getLegalCopy(locale).privacy}/>; }
export function LocalizedTerms({ locale }) { return <Legal locale={locale} page={getLegalCopy(locale).terms}/>; }
