import { getArticle } from "../articles/article-data";
type Pairs=Array<[string,string]>; const a=getArticle("acbuy-shipping-cost-guide");
const s=[a.shortTitle,a.title,a.category,a.primaryKeyword,a.dek,a.researchNote,...(a.visual?.items??[]),a.visual?.caption??"",...a.sections.flatMap(x=>[x.heading,...x.paragraphs,...(x.bullets??[]),...(x.callout?[x.callout.title,x.callout.text]:[])]),...a.faq.flatMap(f=>[f.question,f.answer])];
function m(v:string[]):Pairs{if(v.length!==s.length)throw new Error("Article 3 translation count mismatch");return s.map((x,i)=>[x,v[i]])}
export const article3Translations:Record<"de"|"fr"|"es"|"it"|"pl",Pairs>={
de:m([
"ACBuy-Versandkosten und Paketplanung","ACBuy-Versandkosten: Paketplanung ohne falsche Einheitspreise","Internationaler Versand","ACBuy-Versandkosten","Für internationalen Versand gibt es keinen ehrlichen Einheitspreis. Eine brauchbare Schätzung beginnt mit Ziel, Lagerdaten, Verpackung, Einschränkungen und aktuell verfügbaren Routen.","Der offizielle ACBuy-Ablauf trennt Produkt- und Inlandsgebühren vom internationalen Versand, unterstützt Bündelung, bewirbt 90 Tage kostenlose Lagerung und derzeit mehr als 150 Linien. Verfügbarkeit und Preise bleiben dynamisch.",
"Produktpreis","Inlandsversand","Lagerdienste","Abrechnungsgewicht","Verpackung","Zielroute","Lokale Steuer oder Zoll","Eine Paketschätzung besteht aus Variablen, nicht aus einem wiederverwendbaren Kilopreis.",
"Produktkosten vom internationalen Versand trennen","Die aktuelle Bestelloberfläche trennt Stückpreis und Inlandsversand zum Lager vom internationalen Versand. Ein günstiger Artikel bedeutet daher nicht automatisch eine günstige Endlieferung; er muss erst empfangen, geprüft, verpackt und einer Zielroute zugeordnet werden.","Schätze in Stufen: vor dem Kauf mit Preis, bekanntem Inlandsversand und vorsichtiger Gewichts-/Größenannahme; nach Lagerankunft mit realen Daten; bei Paketeinreichung mit aktuellen Routen, Abrechnungsgewicht, Verpackung und Einschränkungen. Steuern oder Zielgebühren können separat folgen.","Warum feste Preistabellen scheitern","Eine Tabelle ohne Ziel, Datum, Route, Paketmaße und enthaltene Gebühren kann präzise aussehen und für dein Paket trotzdem unbrauchbar sein.",
"Tatsächliches und Volumengewicht verstehen","Viele Linien berechnen nach tatsächlichem oder dimensionalem Gewicht. Sperrige leichte Ware kann daher mehr kosten als die Waage vermuten lässt, etwa Schuhe in Boxen, dicke Jacken oder strukturierte Taschen.","Übernimm keinen alten Volumendivisor aus Foren. Linien nutzen unterschiedliche Formeln, Mindestschritte und Rundungen. Nutze aktuelle Routendaten und vergleiche das Abrechnungsgewicht, nicht nur die Waage.",
"Bündelung bewusst nutzen","ACBuy beschreibt Käufe mehrerer Verkäufer, die im Lager zusammengeführt werden. Bündelung kann wiederholte Grundkosten senken; aktuell werden 90 Tage kostenlose Lagerung beworben. Bestätige die Frist im Konto.","Mehr Artikel bedeuten nicht automatisch geringere Kosten oder Risiko. Ein großes Paket kann eine Gewichts- oder Größenstufe überschreiten, Routen verlieren oder inkompatible Kategorien mischen. Vergleiche ein großes mit zwei kleineren Szenarien.","Artikel mit kompatiblen Einschränkungen gruppieren.","Abrechnungsgewicht vor und nach Verpackung vergleichen.","Größen- und Gewichtslimits der Route beachten.","Zeit für QC und After-Sales vor Lagerfrist lassen.",
"Verpackung nach Produktrisiko wählen","Verpackung verändert Schutz und Kosten. Entfernen von Verkaufsverpackung senkt Volumen; Verstärkung erhöht Gewicht und Maße. Weiche Kleidung und zerbrechliche, strukturierte Ware brauchen unterschiedliche Lösungen.","Beginne mit dem Risiko: Feuchtigkeit bei Kleidung, Formschutz bei Schuhen, Stütze bei Taschen, Trennung kleiner harter Teile. Prüfe aktuelle Dienste und Gebühren und wähle nur sinnvolle Maßnahmen.",
"Routen über den Überschriftspreis hinaus vergleichen","ACBuy nennt aktuell mehr als 150 Versandlinien. Das bedeutet nicht, dass jede Route für jedes Land, Maß oder Produkt verfügbar ist. Entscheidend ist die bei Paketeinreichung angezeigte berechtigte Liste.","Vergleiche Tracking, Laufzeitbereich, Entschädigung, Einschränkungen, Maximalmaße, Abrechnungsregeln und Zielabdeckung. Niedriger Preis kann schwächeres Tracking bedeuten; eine schnellere Schätzung ist keine Garantie.","Live-Berechtigung gewinnt","Die für das reale Lagerpaket erzeugte Routenliste ist verlässlicher als eine statische Blogliste oder ein älterer Kundenscreenshot.",
"Produkteinschränkungen berücksichtigen","Batterien, Flüssigkeiten, Pulver, Magnete, Druckbehälter, Lebensmittel, Pflanzen oder sensible Kategorien können Routen einschränken. Kaufbarkeit beweist nicht internationale Eignung.","Ein eingeschränkter Artikel kann Optionen für das ganze Bündel entfernen. Trennung kann sinnvoller sein. Artikel nie verbergen oder falsch beschreiben; bei unklarer Klassifizierung Support vor Einreichung fragen.",
"Zoll und Steuer als zielspezifisch behandeln","Zollbehörden des Ziellands entscheiden, nicht Tabelle oder Kundenbericht. Schwellen, VAT, Erklärungen und Verbote unterscheiden sich. Kein Leitfaden kann steuerfreie Zustellung oder Freigabe garantieren.","Nutze korrekte Beschreibungen und die aktuelle Deklaration. Prüfe offizielle Zielregeln, lies genau enthaltene Steuerdienste und bewahre Rechnungen auf. Laufzeiten bleiben Bereiche, die Zoll und Zustellung verändern können.",
"Rechner zum richtigen Zeitpunkt nutzen","Ein Vorab-Rechner zeigt, ob eine Kategorie ins Budget passt, ist aber keine Rechnung. Nutze realistisches Ziel, Gewichts- und Größenbereich plus Reserve. Funktioniert der Kauf nur im optimistischsten Fall, ist der Plan schwach.","Nach Lagerankunft mit realen Daten neu rechnen, nach Produktauswahl und Verpackung erneut. Kunden zahlen für ähnliche Ware verschieden, weil Ziel, Route, Maße, Bündelung und Datum abweichen.",
"Drei Paket-Szenarien erstellen","Vergleiche kompakt-günstig, ausgewogenen Schutz und maximalen Schutz. Notiere enthaltene Produkte, Verpackung, Maße, Abrechnungsgewicht, Routen und damalige Summe. So werden sichtbare Kompromisse statt vager Preise verglichen.","Prüfe zuletzt Adresse, Kontakt, Deklaration, Route und Bedingungen. Speichere Paket- und Trackingdaten, aber keine privaten Adressen im gemeinsamen Sheet. Der Leitfaden macht Variablen sichtbar, nicht die Entscheidung universell.",
"Warum gibt es keinen einzigen ACBuy-Kilopreis?","Ziel, Route, tatsächliches oder Volumengewicht, Maße, Verpackung, Einschränkungen und aktuelle Tarife verändern das Ergebnis.","Spart Bündelung immer Geld?","Sie kann Grundkosten senken, aber ein größeres Paket kann Limits überschreiten und Routen verlieren. Live-Szenarien vergleichen.","Ist die Vorab-Schätzung endgültig?","Nein. Sie dient der Planung; nach Lagerdaten und Endverpackung neu berechnen.","Kann ein Leitfaden Zollfreigabe garantieren?","Nein. Zielbehörden kontrollieren Zoll und Steuern. Aktuelle Deklarationen und offizielle lokale Regeln befolgen."
]),
fr:m([
"Coût d’expédition ACBuy et planification","Coût ACBuy : planifier un colis sans faux prix universel","Expédition internationale","coût d’expédition ACBuy","Il n’existe pas de prix universel honnête. Une estimation utile commence par la destination, les données d’entrepôt, l’emballage, les restrictions et les lignes disponibles.","Le parcours officiel sépare produit et livraison nationale de l’international, propose le regroupement, annonce 90 jours de stockage gratuit et plus de 150 lignes. Disponibilité et tarifs restent variables.",
"Prix du produit","Livraison nationale","Services d’entrepôt","Poids facturable","Emballage","Ligne de destination","Taxe locale ou douane","Une estimation est un empilement de variables, pas un prix au kilo réutilisable.",
"Séparer produit et expédition internationale","L’interface actuelle sépare prix unitaire et livraison à l’entrepôt de l’expédition internationale. Un produit peu cher n’est pas forcément peu coûteux livré : il doit être reçu, contrôlé, emballé et associé à une ligne.","Estimez par étapes : avant achat avec prix, livraison connue et hypothèse prudente ; après arrivée avec les données réelles ; au colis avec lignes, poids facturable, emballage et restrictions. Taxes et frais locaux peuvent s’ajouter.","Pourquoi les tableaux fixes échouent","Sans destination, date, ligne, dimensions et frais inclus, un tableau peut sembler précis tout en étant inutilisable.",
"Comprendre poids réel et volumétrique","De nombreuses lignes facturent le poids réel ou dimensionnel. Un article léger mais volumineux peut coûter plus cher, comme chaussures en boîte, manteaux épais ou sacs structurés.","Ne copiez pas un diviseur ancien. Les lignes ont formules, minimums et arrondis différents. Utilisez les règles actuelles et comparez le poids facturable, pas seulement la balance.",
"Regrouper avec intention","ACBuy décrit des achats de plusieurs vendeurs regroupés à l’entrepôt. Cela peut réduire des frais de base ; 90 jours gratuits sont actuellement annoncés. Confirmez la limite dans le compte.","Plus d’articles ne signifie pas toujours moins cher. Un gros colis peut franchir un palier, perdre une ligne ou mélanger des catégories incompatibles. Comparez un grand colis à deux petits.","Grouper des articles aux restrictions compatibles.","Comparer le poids facturable avant et après emballage.","Surveiller limites de taille et de poids.","Garder du temps pour QC et après-vente avant l’échéance.",
"Choisir l’emballage selon le risque","L’emballage change protection et coût. Retirer le superflu réduit le volume ; renforcer ajoute poids et dimensions. Vêtement souple et article fragile demandent des stratégies différentes.","Partez du risque : humidité, déformation, écrasement ou choc. Consultez services et frais actuels et choisissez les protections utiles.",
"Comparer les lignes au-delà du prix","ACBuy mentionne actuellement plus de 150 lignes, mais toutes ne sont pas disponibles pour chaque pays, taille ou catégorie. La liste utile est celle générée pour votre colis.","Comparez suivi, délai estimé, indemnisation, restrictions, dimensions, calcul du poids et couverture. Un prix bas peut avoir moins de suivi ; une estimation rapide n’est pas une garantie.","L’éligibilité en direct prime","La liste générée pour le vrai colis d’entrepôt est plus fiable qu’un blog statique ou une ancienne capture client.",
"Tenir compte des restrictions produit","Batteries, liquides, poudres, aimants, pression, aliments, plantes ou catégories sensibles peuvent bloquer des lignes. Un produit achetable n’est pas éligible partout.","Un article restreint peut supprimer les options du colis entier. Le séparer peut être préférable. Ne cachez ni ne décrivez mal un produit ; demandez au support si la classification est incertaine.",
"Traiter douane et taxe par destination","Les autorités du pays décident, pas une feuille ou un avis. Seuils, TVA, déclarations et interdictions varient. Aucun guide ne garantit livraison sans taxe ou dédouanement.","Décrivez correctement les articles, suivez la déclaration actuelle, consultez les règles officielles et gardez les factures. Les délais restent des fourchettes influencées par douane et dernier kilomètre.",
"Utiliser l’estimateur au bon moment","Avant achat, l’estimateur aide à savoir si la catégorie convient au budget, mais ce n’est pas une facture. Utilisez destination, poids et taille réalistes avec une marge.","Après arrivée, remplacez les hypothèses par les données réelles puis recalculez après emballage. Deux clients paient différemment selon pays, ligne, dimensions, regroupement et date.",
"Construire trois scénarios","Comparez compact économique, protection équilibrée et protection maximale. Notez articles, emballage, dimensions, poids, lignes et total affiché pour rendre les compromis visibles.","Revérifiez adresse, contact, déclaration, ligne et conditions. Conservez colis et suivi sans publier les données privées. Le guide expose les variables plutôt qu’un prix universel.",
"Pourquoi aucun prix ACBuy unique au kilo ?","Destination, ligne, poids réel ou volumétrique, dimensions, emballage, restrictions et tarifs changent le résultat.","Le regroupement économise-t-il toujours ?","Il peut réduire les frais de base, mais un gros colis peut franchir des limites et perdre des lignes. Comparez en direct.","L’estimation avant achat est-elle finale ?","Non. Elle sert à planifier ; recalculez avec données d’entrepôt et emballage final.","Un guide garantit-il le dédouanement ?","Non. Douane et taxes relèvent des autorités. Suivez déclarations actuelles et règles locales officielles."
]),
es:m([
"Coste de envío ACBuy y planificación","Coste de ACBuy: planificar sin precios universales falsos","Envío internacional","coste de envío ACBuy","No existe un precio único honesto. Una estimación útil empieza por destino, datos del almacén, embalaje, restricciones y rutas disponibles.","El flujo oficial separa producto y entrega nacional del envío internacional, permite consolidar, anuncia 90 días de almacenamiento gratuito y más de 150 líneas. Disponibilidad y tarifas cambian.",
"Precio del producto","Entrega nacional","Servicios de almacén","Peso facturable","Embalaje","Ruta de destino","Impuesto local o aduana","Una estimación es una suma de variables, no un precio reutilizable por kilo.",
"Separa producto y envío internacional","La interfaz actual separa precio y entrega al almacén del transporte internacional. Un artículo barato no implica entrega barata: debe recibirse, revisarse, embalarse y asociarse con una ruta.","Calcula por etapas: antes de comprar con precio, entrega conocida e hipótesis prudente; después con datos reales; al enviar con rutas, peso facturable, embalaje y restricciones. Pueden añadirse impuestos o cargos locales.","Por qué fallan las tablas fijas","Sin destino, fecha, ruta, dimensiones y cargos incluidos, una tabla puede parecer precisa y no servir para tu paquete.",
"Comprende peso real y volumétrico","Muchas líneas cobran por peso real o dimensional. Un artículo ligero pero grande puede costar más, como calzado con caja, abrigo grueso o bolso estructurado.","No copies un divisor antiguo. Las líneas usan fórmulas, mínimos y redondeos distintos. Usa las reglas actuales y compara peso facturable, no solo báscula.",
"Consolida de forma deliberada","ACBuy describe compras de varios vendedores que se agrupan en almacén. Puede reducir cargos base; actualmente anuncia 90 días gratuitos. Confirma el límite en la cuenta.","Más artículos no siempre reducen coste o riesgo. Un paquete grande puede cruzar tramos, perder rutas o mezclar categorías incompatibles. Compara uno grande con dos pequeños.","Agrupa artículos con restricciones compatibles.","Compara peso facturable antes y después de embalar.","Vigila límites de tamaño y peso.","Deja tiempo para QC y posventa antes del plazo.",
"Elige embalaje según el riesgo","El embalaje cambia protección y coste. Quitar cajas reduce volumen; reforzar añade peso y medidas. Ropa blanda y productos frágiles necesitan estrategias distintas.","Empieza por el fallo que quieres evitar: humedad, deformación, aplastamiento o golpes. Revisa servicios y tarifas actuales y elige solo protección útil.",
"Compara rutas más allá del precio","ACBuy menciona más de 150 líneas, pero no todas sirven para cada país, tamaño o categoría. La lista útil es la generada para tu paquete.","Compara seguimiento, plazo estimado, compensación, restricciones, dimensiones, reglas de peso y cobertura. Menor precio puede tener menos seguimiento; rapidez estimada no es garantía.","La elegibilidad en vivo gana","La lista generada para el paquete real es más fiable que un blog estático o una captura antigua.",
"Considera restricciones del producto","Baterías, líquidos, polvos, imanes, presión, alimentos, plantas o categorías sensibles pueden bloquear rutas. Poder comprar no demuestra elegibilidad internacional.","Un artículo restringido puede eliminar rutas del paquete entero. Separarlo puede convenir. No ocultes ni describas mal; consulta soporte si la clasificación es incierta.",
"Trata aduanas e impuestos por destino","Deciden las autoridades del país, no una hoja o reseña. Umbrales, IVA, declaraciones y prohibiciones varían. Ninguna guía garantiza entrega sin impuestos o despacho.","Describe bien, sigue la declaración actual, consulta reglas oficiales y conserva facturas. Los plazos son rangos afectados por aduanas y última milla.",
"Usa el estimador en el momento correcto","Antes de comprar ayuda a saber si cabe en presupuesto, pero no es factura. Usa destino, peso y tamaño realistas con margen.","Después de llegar, sustituye supuestos por datos reales y recalcula tras el embalaje. Dos clientes pagan distinto por país, ruta, dimensiones, consolidación y fecha.",
"Crea tres escenarios","Compara compacto económico, protección equilibrada y máxima. Anota productos, embalaje, dimensiones, peso, rutas y total para ver los compromisos.","Revisa dirección, contacto, declaración, ruta y condiciones. Guarda paquete y seguimiento sin publicar datos privados. La guía muestra variables, no un precio universal.",
"¿Por qué no hay un precio ACBuy por kilo?","Destino, ruta, peso real o volumétrico, medidas, embalaje, restricciones y tarifas cambian el resultado.","¿Consolidar siempre ahorra?","Puede reducir cargos base, pero un paquete mayor puede superar límites y perder rutas. Compara en vivo.","¿La estimación previa es final?","No. Sirve para planificar; recalcula con datos del almacén y embalaje final.","¿Puede una guía garantizar aduanas?","No. Aduanas e impuestos dependen de autoridades. Sigue declaraciones actuales y reglas locales oficiales."
]),
it:m([
"Costo spedizione ACBuy e pianificazione","Costo ACBuy: pianificare senza falsi prezzi universali","Spedizione internazionale","costo spedizione ACBuy","Non esiste un prezzo unico onesto. Una stima utile parte da destinazione, dati di magazzino, imballaggio, restrizioni e rotte disponibili.","Il flusso ufficiale separa prodotto e consegna nazionale dalla spedizione internazionale, consente consolidamento, indica 90 giorni gratuiti e oltre 150 linee. Disponibilità e prezzi cambiano.",
"Prezzo prodotto","Consegna nazionale","Servizi di magazzino","Peso fatturabile","Imballaggio","Rotta di destinazione","Tassa locale o dogana","Una stima è un insieme di variabili, non un prezzo al chilo riutilizzabile.",
"Separa prodotto e spedizione internazionale","L’interfaccia attuale separa prezzo e consegna al magazzino dal trasporto internazionale. Un articolo economico non significa consegna economica: va ricevuto, controllato, imballato e associato a una rotta.","Stima per fasi: prima dell’acquisto con prezzo, consegna nota e ipotesi prudente; dopo con dati reali; all’invio con rotte, peso, imballaggio e restrizioni. Possono aggiungersi tasse locali.","Perché le tabelle fisse falliscono","Senza destinazione, data, rotta, dimensioni e costi inclusi, una tabella può sembrare precisa ma non servire.",
"Comprendi peso reale e volumetrico","Molte linee fatturano peso reale o dimensionale. Un articolo leggero ma grande può costare di più, come scarpe in scatola, cappotti o borse strutturate.","Non copiare un divisore vecchio. Le linee usano formule, minimi e arrotondamenti diversi. Usa le regole attuali e confronta peso fatturabile, non solo bilancia.",
"Consolida con criterio","ACBuy descrive acquisti di più venditori raggruppati in magazzino. Può ridurre costi base; oggi indica 90 giorni gratuiti. Conferma il termine nell’account.","Più articoli non significano sempre meno costo o rischio. Un pacco grande può superare fasce, perdere rotte o mescolare categorie incompatibili. Confronta uno grande con due piccoli.","Raggruppa articoli con restrizioni compatibili.","Confronta il peso prima e dopo l’imballaggio.","Controlla limiti di dimensione e peso.","Lascia tempo per QC e assistenza prima della scadenza.",
"Scegli l’imballaggio per rischio","L’imballaggio cambia protezione e costo. Togliere scatole riduce volume; rinforzare aggiunge peso e misure. Abbigliamento morbido e prodotti fragili richiedono strategie diverse.","Parti dal rischio: umidità, deformazione, schiacciamento o urti. Controlla servizi e tariffe attuali e scegli protezioni utili.",
"Confronta le rotte oltre il prezzo","ACBuy cita oltre 150 linee, ma non tutte sono disponibili per ogni paese, misura o categoria. Conta la lista generata per il tuo pacco.","Confronta tracking, intervallo, compensazione, restrizioni, dimensioni, regole di peso e copertura. Prezzo basso può avere meno tracking; velocità stimata non è garanzia.","Conta l’idoneità live","La lista generata per il pacco reale è più affidabile di un blog statico o una vecchia schermata.",
"Considera le restrizioni prodotto","Batterie, liquidi, polveri, magneti, pressione, alimenti, piante o categorie sensibili possono bloccare rotte. Acquistabile non significa spedibile ovunque.","Un articolo ristretto può eliminare rotte dell’intero pacco. Separarlo può convenire. Non nascondere o descrivere male; chiedi assistenza se incerto.",
"Tratta dogana e tasse per destinazione","Decidono le autorità del paese, non un foglio o una recensione. Soglie, IVA, dichiarazioni e divieti cambiano. Nessuna guida garantisce esenzione o sdoganamento.","Descrivi correttamente, segui la dichiarazione, consulta regole ufficiali e conserva fatture. I tempi sono intervalli influenzati da dogana e ultimo miglio.",
"Usa il calcolatore al momento giusto","Prima dell’acquisto aiuta a capire il budget, ma non è fattura. Usa destinazione, peso e dimensioni realistici con margine.","Dopo l’arrivo sostituisci ipotesi con dati reali e ricalcola dopo imballaggio. Due clienti pagano diversamente per paese, rotta, misure, consolidamento e data.",
"Crea tre scenari","Confronta compatto economico, protezione equilibrata e massima. Annota prodotti, imballaggio, dimensioni, peso, rotte e totale per vedere i compromessi.","Ricontrolla indirizzo, contatto, dichiarazione, rotta e condizioni. Salva pacco e tracking senza pubblicare dati privati. La guida mostra variabili, non un prezzo universale.",
"Perché non esiste un prezzo ACBuy al chilo?","Destinazione, rotta, peso reale o volumetrico, dimensioni, imballaggio, restrizioni e tariffe cambiano il risultato.","Il consolidamento fa sempre risparmiare?","Può ridurre costi base, ma un pacco maggiore può superare limiti e perdere rotte. Confronta live.","La stima iniziale è finale?","No. Serve a pianificare; ricalcola con dati di magazzino e imballaggio finale.","Una guida può garantire lo sdoganamento?","No. Dogana e tasse dipendono dalle autorità. Segui dichiarazioni attuali e regole locali."
]),
pl:m([
"Koszt wysyłki ACBuy i planowanie paczki","Koszt ACBuy: planowanie bez fałszywych cen uniwersalnych","Wysyłka międzynarodowa","koszt wysyłki ACBuy","Nie istnieje uczciwa jedna cena. Użyteczny szacunek zaczyna się od kraju, danych magazynowych, opakowania, ograniczeń i dostępnych tras.","Oficjalny proces oddziela produkt i dostawę krajową od międzynarodowej, umożliwia łączenie, podaje 90 dni darmowego magazynowania i ponad 150 linii. Dostępność i ceny są zmienne.",
"Cena produktu","Dostawa krajowa","Usługi magazynowe","Waga rozliczeniowa","Opakowanie","Trasa docelowa","Podatek lokalny lub cło","Szacunek paczki to zestaw zmiennych, nie jedna cena za kilogram.",
"Oddziel produkt od wysyłki międzynarodowej","Interfejs oddziela cenę i dostawę do magazynu od transportu międzynarodowego. Tani produkt nie oznacza taniego odbioru: musi być przyjęty, sprawdzony, zapakowany i dopasowany do trasy.","Szacuj etapami: przed zakupem z ceną i ostrożnym założeniem; po przyjęciu z realnymi danymi; przy paczce z trasami, wagą, opakowaniem i ograniczeniami. Mogą dojść podatki lokalne.","Dlaczego stałe tabele zawodzą","Bez kraju, daty, trasy, wymiarów i zawartych opłat tabela może wyglądać dokładnie, ale nie pasować do paczki.",
"Zrozum wagę rzeczywistą i gabarytową","Wiele linii rozlicza wagę rzeczywistą lub gabarytową. Lekki, duży artykuł może kosztować więcej, np. buty w pudełku, gruby płaszcz lub sztywna torba.","Nie kopiuj starego dzielnika. Linie mają różne wzory, minima i zaokrąglenia. Użyj bieżących zasad i porównaj wagę rozliczeniową, nie samą wagę.",
"Łącz świadomie","ACBuy opisuje zakupy od wielu sprzedawców łączone w magazynie. Może to obniżyć opłaty bazowe; obecnie podaje 90 dni bezpłatnie. Potwierdź termin na koncie.","Więcej artykułów nie zawsze oznacza niższy koszt. Duża paczka może przekroczyć próg, stracić trasy lub mieszać niezgodne kategorie. Porównaj jedną dużą z dwiema małymi.","Grupuj artykuły z zgodnymi ograniczeniami.","Porównaj wagę przed i po pakowaniu.","Pilnuj limitów rozmiaru i wagi.","Zostaw czas na QC i obsługę przed terminem.",
"Wybierz opakowanie według ryzyka","Opakowanie zmienia ochronę i koszt. Usunięcie pudeł zmniejsza objętość; wzmocnienie dodaje wagę i wymiary. Miękka odzież i delikatne produkty potrzebują innych strategii.","Zacznij od ryzyka: wilgoć, odkształcenie, zgniecenie lub uderzenie. Sprawdź bieżące usługi i ceny i wybierz potrzebną ochronę.",
"Porównaj trasy poza ceną","ACBuy podaje ponad 150 linii, ale nie wszystkie są dostępne dla każdego kraju, rozmiaru i kategorii. Liczy się lista wygenerowana dla paczki.","Porównaj śledzenie, zakres czasu, rekompensatę, ograniczenia, wymiary, zasady wagi i zasięg. Niższa cena może oznaczać słabsze śledzenie; szacowana szybkość nie jest gwarancją.","Wygrywa dostępność na żywo","Lista dla rzeczywistej paczki jest bardziej wiarygodna niż stały blog lub stary zrzut klienta.",
"Uwzględnij ograniczenia produktu","Baterie, płyny, proszki, magnesy, ciśnienie, żywność, rośliny lub wrażliwe kategorie mogą blokować trasy. Możliwość zakupu nie potwierdza wysyłki.","Ograniczony artykuł może usunąć trasy całej paczki. Rozdzielenie może być lepsze. Nie ukrywaj ani nie opisuj fałszywie; przy niejasności zapytaj obsługę.",
"Traktuj cło i podatek według kraju","Decydują władze kraju, nie arkusz ani opinia. Progi, VAT, deklaracje i zakazy różnią się. Żaden poradnik nie gwarantuje braku podatku lub odprawy.","Opisuj poprawnie, stosuj bieżącą deklarację, sprawdź oficjalne zasady i zachowaj faktury. Czas to zakres zależny od cła i doręczenia.",
"Użyj kalkulatora we właściwym momencie","Przed zakupem pomaga ocenić budżet, ale nie jest fakturą. Użyj realistycznego kraju, wagi i rozmiaru z marginesem.","Po przyjęciu zastąp założenia realnymi danymi i przelicz po pakowaniu. Klienci płacą różnie przez kraj, trasę, wymiary, łączenie i datę.",
"Zbuduj trzy scenariusze","Porównaj kompaktowy tani, zrównoważoną ochronę i maksymalną ochronę. Zapisz produkty, opakowanie, wymiary, wagę, trasy i sumę, aby zobaczyć kompromisy.","Sprawdź adres, kontakt, deklarację, trasę i warunki. Zachowaj dane paczki i śledzenie bez publikowania prywatnych informacji. Poradnik pokazuje zmienne, nie cenę uniwersalną.",
"Dlaczego nie ma jednej ceny ACBuy za kilogram?","Kraj, trasa, waga rzeczywista lub gabarytowa, wymiary, opakowanie, ograniczenia i stawki zmieniają wynik.","Czy łączenie zawsze oszczędza?","Może obniżyć opłaty bazowe, ale większa paczka może przekroczyć limity i stracić trasy. Porównaj na żywo.","Czy szacunek przed zakupem jest końcowy?","Nie. Służy do planowania; przelicz po danych magazynu i końcowym pakowaniu.","Czy poradnik gwarantuje odprawę?","Nie. Cło i podatki kontrolują władze. Stosuj bieżące deklaracje i oficjalne zasady lokalne."
])};
