import { getArticle } from "../articles/article-data";
type Pairs = Array<[string,string]>;
const a = getArticle("acbuy-qc-photos-guide");
const sources = [a.shortTitle,a.title,a.category,a.primaryKeyword,a.dek,a.researchNote,...(a.visual?.items??[]),a.visual?.caption??"",...a.sections.flatMap(s=>[s.heading,...s.paragraphs,...(s.bullets??[]),...(s.callout?[s.callout.title,s.callout.text]:[])]),...a.faq.flatMap(f=>[f.question,f.answer])];
function make(values:string[]):Pairs { if(values.length!==sources.length) throw new Error("Article 2 translation count mismatch"); return sources.map((s,i)=>[s,values[i]]); }

export const article2Translations: Record<"de"|"fr"|"es"|"it"|"pl",Pairs> = {
de: make([
"ACBuy-QC-Fotos: Praktische Checkliste","ACBuy-QC-Fotos: Was sie zeigen, beweisen und übersehen","Lager-QC","ACBuy-QC-Fotos","Lagerfotos sind der erste Beleg für den angekommenen physischen Artikel. Eine feste Prüfung findet sichtbare Probleme und zeigt zugleich die Grenzen eines Fotos.","Die aktuelle offizielle ACBuy-Startseite nennt drei bis fünf kostenlose QC-Fotos und eine Qualitätsprüfung nach der Lagerankunft. Diese Aussagen gelten aktuell; Fotos werden nicht als Echtheits- oder Garantiebeleg dargestellt.",
"Bestellabgleich","Gesamtform","Farbkonsistenz","Verarbeitungsdetails","Maße","Schäden und Zubehör","Prüfe die Belege immer in derselben Reihenfolge; Konstanz verhindert übersehene Mängel.",
"Aufgabe des Lager-QC verstehen","QC-Fotos stehen zwischen Verkäuferangebot und internationalem Paket. Das Angebot zeigt die versprochene Ware, Lagerbilder den angekommenen Artikel. ACBuy beschreibt aktuell eine Prüfung und drei bis fünf kostenlose Fotos; den genauen Umfang im Konto bestätigen.","Entscheidend ist nicht, ob Bilder attraktiv wirken, sondern ob sie den Vergleich mit der Bestellung erlauben. QC kann falsche Farbe, Schäden, fehlendes Zubehör oder grobe Maßabweichungen zeigen, aber Material, Passform, Haltbarkeit oder Zollausgang nicht garantieren.","Beleg, keine Zertifizierung","Lagerfotos sind sichtbare Belege eines Artikels, keine Authentifizierung, Laborprüfung oder allgemeine Qualitätsgarantie.",
"Bestellung vor den Fotos erneut öffnen","Beginne mit dem Auftrag, nicht mit dem ersten Foto. Prüfe Quell-ID, Farbe, Größe, Menge, Set und sichtbare Verkäuferzusagen. Ohne gespeicherte Variante sind ähnliche Optionen später schwer zu unterscheiden.","Notiere zwei oder drei Pflichtmerkmale: bei Schuhen etwa Größe, Sohle und Schnürsenkel, bei Taschen Riemen und Verschluss, bei Kleidung Größe, Druck und Maße. So wird das Foto zum Vergleich statt zum spontanen Eindruck.",
"Zuerst die Gesamtform prüfen","Beginne mit der weitesten Ansicht. Vergleiche Seiten, Proportionen, Ausrichtung, Zehen- oder Kragenform, Taschenstruktur und Stofffall. Ein Artikel kann saubere Nähte haben und trotzdem verdreht oder ungleich sein.","Perspektive kann täuschen. Kameranähe vergrößert eine Seite, weiche Ware kann einsinken. Vergleiche mehrere Bilder; eine Abweichung in allen Ansichten ist aussagekräftiger als in nur einer.","Gesamtproportionen vor Kleindetails vergleichen.","Auf Seitenungleichheit und versetzte Teile achten.","Mehrere Bilder nutzen, um Form von Perspektive zu trennen.","Klarere Belege anfordern, wenn die Ansicht die Frage nicht beantwortet.",
"Farbe als Muster, nicht als Einzelbild bewerten","Lagerlicht, Weißabgleich und Bildschirm verändern Farbtöne. Vergleiche alle Bilder und frage, ob die Abweichung konstant ist. Verkäuferfotos sind Referenz, kein kalibrierter Standard.","Am zuverlässigsten sind Teile, die im selben Bild gleich aussehen sollten, etwa beide Schuhe, Riemen und Tasche oder wiederholte Druckflächen. Bei entscheidender Unklarheit eine klarere Aufnahme prüfen.",
"Verarbeitung und Beschläge vergrößern","Prüfe Nähte, Stickerei, Druck, Reißverschlüsse, Schnallen, Ösen, Sohlenverbindungen und Befestigungen. Achte auf Fehlstiche, lose Fäden, versetzte Motive, Abblättern, Kratzer und unpassende Teile.","Trenne Kosmetik von Funktion. Ein loser Faden ist anders als ein kaputter Reißverschluss oder gerissener Anker. Fotos zeigen Bewegung nicht immer; bei Bedarf einen aktuellen Funktionsbeleg anfordern.","Kein Ein-Logo-QC","Verarbeitung, Symmetrie, Maße, Schäden und enthaltene Teile sagen meist mehr als ein einzelnes Logo-Nahbild.",
"Maße zur Prüfung der Größenangabe nutzen","Ein Größenetikett bestätigt keine Passform. Vergleiche sichtbare oder angeforderte Maße mit einem eigenen Artikel: Brust, Länge, Schulter, Ärmel, Einlegesohle oder Taschenmaße.","Auch Maßfotos haben Grenzen. Bandanfang, Lage und Stoffspannung müssen stimmen. Fehlt das benötigte Maß, aktuelle Zusatzfoto-Optionen prüfen; keine exakte Zahl aus unklarem Bild erfinden.",
"Schäden, Sauberkeit und Zubehör prüfen","Untersuche sichtbare Flächen auf Flecken, Risse, Dellen, Kleber, Kratzer, Brüche und Feuchtigkeit. Vergleiche Zubehör wie Schnürsenkel, Riemen, Beutel oder abnehmbare Teile mit der Bestellung.","Folge einem festen Weg über Vorderseite, Rückseite, Seiten, Ober- und Unterseite. Prüfe bei Paaren beide Teile. Beschreibe Probleme präzise mit Ort, Größe und Bildnummer.",
"Nächsten Schritt wählen, solange Optionen offen sind","Bei möglicher Abweichung vor Paketeinreichung stoppen. Prüfe aktuelle After-Sales-Optionen und stelle eine konkrete Frage. Zusatzfoto, Maß, Verkäuferbestätigung, Rückgabe oder Umtausch hängen von Regeln und Bedingungen ab.","Drei sinnvolle Ergebnisse: annehmen, weil Belege passen; mehr Belege anfordern; oder bei sichtbarer wesentlicher Abweichung den verfügbaren After-Sales-Weg nutzen. Belege und Auftrag sind wichtiger als ein pauschales Online-Urteil.",
"Grenzen geteilter QC-Galerien kennen","Geteilte Galerien zeigen nützliche Winkel und typische Probleme, beweisen aber nicht, dass dein Artikel identisch wird. Verkäufer, Chargen, Varianten und Lagerdaten unterscheiden sich.","Gute Kundenberichte nennen Datum, Fotos, genaue Quelle und trennen Lagerservice von Produktqualität. Reine Sterne oder Versandtempo sind wenig aussagekräftig; Einzelfälle dürfen nicht als offizieller Standard gelten.",
"Wie viele kostenlose ACBuy-QC-Fotos werden aktuell beworben?","Die offizielle Startseite nennt derzeit drei bis fünf. Bestätige Umfang und Zusatzdienste im Live-Konto.","Können QC-Fotos Echtheit beweisen?","Nein. Sie zeigen sichtbare Merkmale, sind aber keine Labor- oder Rechtsauthentifizierung und kein Materialnachweis.","Was tun, wenn ein Detail fehlt?","Aktuelle Optionen für Zusatzfotos oder Supportfragen prüfen und eine konkrete messbare Ansicht anfordern.","Reichen Verkäuferbilder für QC?","Nein. Sie beschreiben das Angebot; Lagerbilder belegen den angekommenen physischen Artikel und müssen mit der Bestellung verglichen werden."
]),
fr: make([
"Photos QC ACBuy : liste pratique","Photos QC ACBuy : quoi contrôler, ce qu’elles prouvent et leurs limites","QC en entrepôt","photos QC ACBuy","Les photos d’entrepôt sont la première preuve de l’article physique reçu. Une méthode fixe repère les problèmes visibles tout en respectant les limites de l’image.","La page officielle actuelle d’ACBuy annonce trois à cinq photos QC gratuites et un contrôle à l’arrivée. Ces informations sont datées ; les photos ne sont pas présentées comme preuve d’authenticité ou garantie.",
"Correspondance commande","Forme globale","Cohérence des couleurs","Détails de fabrication","Mesures","Dommages et accessoires","Examinez toujours les preuves dans le même ordre ; la régularité réduit les défauts oubliés.",
"Comprendre le rôle du QC d’entrepôt","Les photos QC se situent entre l’annonce vendeur et le colis international. L’annonce montre l’offre ; les images montrent l’article arrivé. ACBuy décrit actuellement un contrôle et trois à cinq photos gratuites, à confirmer dans le compte.","La question n’est pas si les images sont jolies, mais si elles permettent la comparaison. Le QC peut révéler mauvaise couleur, dommage, accessoire absent ou écart visible, mais pas garantir matière, coupe, durée ou douane.","Preuve, pas certification","Les photos sont une preuve visuelle d’un article, pas une authentification, un test de laboratoire ou une garantie universelle.",
"Rouvrir la commande avant les photos","Commencez par le dossier : identifiant source, couleur, taille, quantité, lot et promesses visibles. Sans variante sauvegardée, des options proches deviennent difficiles à distinguer.","Notez deux ou trois éléments obligatoires : taille, semelle et lacets pour des chaussures ; sangle et fermeture pour un sac ; taille, impression et mesures pour un vêtement. Les photos deviennent alors une comparaison.",
"Contrôler d’abord la forme globale","Commencez par la vue la plus large. Comparez côtés, proportions, alignement, forme, structure et tombé. Un article peut avoir des coutures propres tout en étant tordu ou irrégulier.","La perspective trompe : un côté proche paraît plus grand et un produit souple peut s’affaisser. Comparez plusieurs vues ; un écart présent partout est plus significatif.","Comparer les proportions avant les petits détails.","Chercher déséquilibre gauche-droite et panneaux décalés.","Utiliser plusieurs vues pour distinguer forme et perspective.","Demander une preuve plus claire si la vue ne répond pas.",
"Évaluer la couleur comme un ensemble","Lumière, balance des blancs et écran modifient les tons. Comparez toutes les vues et recherchez une différence constante. L’image vendeur est une référence, pas un étalon calibré.","La comparaison est meilleure entre deux pièces censées correspondre dans la même image : chaussures, sangle et corps, zones imprimées. Si la couleur est essentielle, demandez une vue plus claire.",
"Agrandir fabrication et quincaillerie","Contrôlez coutures, broderie, impression, zips, boucles, œillets, semelles et attaches. Cherchez points manqués, fils libres, motifs décalés, pelage, rayures ou pièces incompatibles.","Distinguez cosmétique et fonction. Un fil libre n’équivaut pas à un zip cassé ou une attache fendue. Si le fonctionnement compte, demandez une preuve actuelle adaptée.","Ne pas faire un QC sur un seul logo","Fabrication, symétrie, mesures, dommages et pièces incluses apprennent plus qu’un seul gros plan de logo.",
"Utiliser les mesures pour vérifier la taille","Une étiquette ne confirme pas la coupe. Comparez les mesures visibles ou demandées avec un article possédé : poitrine, longueur, épaule, manche, semelle ou dimensions du sac.","Les photos de mesure ont aussi des limites : départ du ruban, position et tension doivent être corrects. Si la mesure manque, vérifiez les options de photo ; n’inventez pas un chiffre précis.",
"Contrôler dommages, propreté et pièces incluses","Inspectez les surfaces pour taches, déchirures, bosses, colle, rayures, casse et humidité. Comparez lacets, sangles, pochettes et pièces amovibles avec la commande.","Suivez un trajet fixe sur face, dos, côtés, dessus et dessous. Pour une paire, contrôlez les deux unités. Décrivez précisément emplacement, taille et numéro d’image.",
"Choisir l’action suivante tant que les options existent","En cas d’écart possible, arrêtez avant de soumettre le colis. Consultez les options après-vente actuelles et posez une question précise. Photo, mesure, confirmation, retour ou échange dépendent des règles et du vendeur.","Trois résultats : accepter si les preuves correspondent ; demander plus de preuves ; ou utiliser l’option après-vente en cas d’écart visible important. Le dossier compte plus qu’un avis générique.",
"Connaître les limites des galeries QC","Les galeries partagées montrent des angles utiles et des défauts possibles, mais ne prouvent pas que votre unité sera identique. Vendeurs, lots, variantes et dates diffèrent.","Un bon avis indique date, photos, source exacte et sépare service d’entrepôt et qualité vendeur. Étoiles ou vitesse seules sont faibles ; une expérience individuelle n’est pas une norme officielle.",
"Combien de photos QC gratuites ACBuy annonce-t-il actuellement ?","La page officielle annonce actuellement trois à cinq photos. Confirmez le lot exact et les services dans le compte.","Les photos QC prouvent-elles l’authenticité ?","Non. Elles montrent des éléments visibles, mais ne sont ni test de laboratoire ni authentification légale.","Que faire si un détail manque ?","Vérifiez les options actuelles de photo ou d’assistance et demandez une vue précise et mesurable.","Les images vendeur suffisent-elles pour le QC ?","Non. Elles décrivent l’offre ; les images d’entrepôt prouvent l’unité reçue et doivent être comparées à la commande."
]),
es: make([
"Fotos QC de ACBuy: lista práctica","Fotos QC de ACBuy: qué revisar, qué demuestran y qué omiten","QC de almacén","fotos QC de ACBuy","Las fotos del almacén son la primera prueba del artículo físico recibido. Un método fijo detecta problemas visibles y respeta los límites de una imagen.","La página oficial actual de ACBuy anuncia de tres a cinco fotos QC gratuitas y control tras la llegada. Son datos actuales; las fotos no se presentan como autenticación o garantía.",
"Coincidencia del pedido","Forma completa","Consistencia del color","Detalles de fabricación","Medidas","Daños y accesorios","Revisa las pruebas siempre en el mismo orden; la constancia reduce defectos pasados por alto.",
"Comprende el papel del QC de almacén","Las fotos QC están entre la oferta del vendedor y el paquete internacional. La oferta muestra lo prometido; las imágenes, lo que llegó. ACBuy describe control y tres-cinco fotos gratuitas, que deben confirmarse en la cuenta.","La cuestión no es que sean bonitas, sino que permitan comparar. El QC revela color incorrecto, daños, accesorios ausentes o diferencias visibles, pero no garantiza material, ajuste, duración o aduanas.","Prueba, no certificación","Trata las fotos como prueba visual de un artículo, no como autenticación, análisis de laboratorio o garantía universal.",
"Reabre el pedido antes de ver las fotos","Empieza por el pedido: ID de origen, color, talla, cantidad, lote y promesas visibles. Sin variante guardada, opciones similares son difíciles de distinguir.","Anota dos o tres rasgos obligatorios: talla, suela y cordones; correa y cierre; o talla, impresión y medidas. Así las fotos se convierten en comparación.",
"Inspecciona primero la forma completa","Empieza por la vista más amplia. Compara lados, proporciones, alineación, forma, estructura y caída. Un artículo puede tener costuras limpias y seguir torcido o desigual.","La perspectiva engaña: el lado más cercano parece mayor y un producto blando puede hundirse. Compara varios cuadros; una diferencia constante importa más.","Compara proporciones antes de detalles pequeños.","Busca desequilibrio y paneles desalineados.","Usa varias imágenes para separar forma y perspectiva.","Pide pruebas más claras si la vista no responde.",
"Juzga el color como un patrón","La iluminación, el balance y la pantalla alteran los tonos. Compara todas las fotos y busca una diferencia constante. La imagen del vendedor es referencia, no patrón calibrado.","Compara piezas que deberían coincidir en la misma foto: zapatos, correa y cuerpo o áreas impresas. Si el color es esencial, pide una vista más clara.",
"Amplía construcción y herrajes","Revisa costuras, bordado, impresión, cremalleras, hebillas, ojales, uniones y anclajes. Busca puntadas fallidas, hilos sueltos, gráficos desviados, pelado, arañazos o piezas distintas.","Distingue estética y función. Un hilo suelto no equivale a una cremallera rota o un anclaje agrietado. Si importa el funcionamiento, pide una prueba adecuada.","No hagas QC de un solo logo","Construcción, simetría, medidas, daños y piezas incluidas dicen más que un único primer plano de logo.",
"Usa medidas para comprobar la talla","Una etiqueta no confirma el ajuste. Compara medidas visibles o solicitadas con una prenda propia: pecho, largo, hombro, manga, plantilla o dimensiones del bolso.","Las fotos de medición tienen límites: inicio de la cinta, posición y tensión deben ser correctos. Si falta la medida, revisa opciones de foto; no inventes precisión.",
"Comprueba daños, limpieza y piezas","Busca manchas, roturas, golpes, pegamento, arañazos, piezas rotas y humedad. Compara cordones, correas, bolsas y piezas extraíbles con el pedido.","Sigue un recorrido fijo por frente, dorso, lados, parte superior e inferior. En pares, revisa ambos. Describe ubicación, tamaño y número de foto.",
"Elige la siguiente acción mientras haya opciones","Ante una posible diferencia, detente antes de enviar el paquete. Revisa opciones posventa y formula una pregunta concreta. Foto, medida, confirmación, devolución o cambio dependen de las reglas.","Tres resultados: aceptar si coincide; pedir más pruebas; o usar la vía posventa si hay una diferencia visible importante. Las pruebas valen más que una opinión genérica.",
"Conoce los límites de las galerías QC","Las galerías compartidas enseñan ángulos útiles y posibles defectos, pero no prueban que tu unidad sea igual. Cambian vendedor, lote, variante y fecha.","Una reseña útil incluye fecha, fotos, fuente exacta y separa servicio de almacén y calidad del vendedor. Estrellas o rapidez solas aportan poco; un caso no es norma oficial.",
"¿Cuántas fotos QC gratuitas anuncia ACBuy?","La página oficial actual indica de tres a cinco. Confirma el conjunto y los servicios en la cuenta.","¿Las fotos QC prueban autenticidad?","No. Muestran rasgos visibles, pero no son análisis de laboratorio ni autenticación legal.","¿Qué hago si falta un detalle?","Revisa opciones actuales de fotos o soporte y pide una vista concreta y medible.","¿Bastan las imágenes del vendedor?","No. Describen la oferta; las fotos de almacén muestran la unidad recibida y deben compararse con el pedido."
]),
it: make([
"Foto QC ACBuy: lista pratica","Foto QC ACBuy: cosa controllare, cosa provano e cosa manca","QC di magazzino","foto QC ACBuy","Le foto di magazzino sono la prima prova dell’articolo fisico ricevuto. Un metodo fisso individua problemi visibili e riconosce i limiti di un’immagine.","La pagina ufficiale attuale di ACBuy indica tre-cinque foto QC gratuite e controllo all’arrivo. Sono dati attuali; le foto non sono presentate come autenticazione o garanzia.",
"Corrispondenza ordine","Forma completa","Coerenza colore","Dettagli costruttivi","Misure","Danni e accessori","Esamina le prove sempre nello stesso ordine; la costanza riduce i difetti dimenticati.",
"Capire il ruolo del QC in magazzino","Le foto QC stanno tra offerta del venditore e pacco internazionale. L’offerta mostra ciò che è promesso; le immagini ciò che è arrivato. ACBuy descrive controllo e tre-cinque foto gratuite, da confermare nell’account.","Non conta che le immagini siano belle, ma che permettano il confronto. Il QC mostra colore errato, danni, accessori mancanti o differenze visibili, ma non garantisce materiale, vestibilità, durata o dogana.","Prova, non certificazione","Tratta le foto come prova visiva di un articolo, non come autenticazione, test di laboratorio o garanzia universale.",
"Riapri l’ordine prima delle foto","Parti dall’ordine: ID sorgente, colore, taglia, quantità, set e promesse visibili. Senza variante salvata, opzioni simili sono difficili da distinguere.","Annota due o tre elementi obbligatori: taglia, suola e lacci; tracolla e chiusura; oppure taglia, stampa e misure. Le foto diventano così un confronto.",
"Controlla prima la forma completa","Inizia dalla vista più ampia. Confronta lati, proporzioni, allineamento, forma, struttura e caduta. Un articolo può avere cuciture pulite ma essere storto o irregolare.","La prospettiva inganna: il lato vicino sembra maggiore e un prodotto morbido può cedere. Confronta più immagini; una differenza costante conta di più.","Confronta le proporzioni prima dei piccoli dettagli.","Cerca squilibrio e pannelli disallineati.","Usa più immagini per separare forma e prospettiva.","Chiedi prove più chiare se la vista non risponde.",
"Valuta il colore come insieme","Luce, bilanciamento e schermo cambiano i toni. Confronta tutte le foto e cerca differenze costanti. L’immagine del venditore è riferimento, non standard calibrato.","Confronta componenti che dovrebbero coincidere nella stessa foto: scarpe, tracolla e corpo, aree stampate. Se il colore è essenziale, chiedi una vista più chiara.",
"Ingrandisci costruzione e accessori","Controlla cuciture, ricamo, stampa, zip, fibbie, occhielli, giunti e attacchi. Cerca punti mancanti, fili liberi, grafiche spostate, sfogliature, graffi o parti diverse.","Distingui estetica e funzione. Un filo libero non equivale a una zip rotta o a un attacco crepato. Se la funzione conta, chiedi una prova adeguata.","Non fare QC su un solo logo","Costruzione, simmetria, misure, danni e parti incluse dicono più di un unico primo piano del logo.",
"Usa le misure per verificare la taglia","Un’etichetta non conferma la vestibilità. Confronta misure visibili o richieste con un articolo proprio: petto, lunghezza, spalla, manica, soletta o dimensioni della borsa.","Le foto di misura hanno limiti: inizio del metro, posizione e tensione devono essere corretti. Se manca una misura, controlla opzioni foto; non inventare precisione.",
"Controlla danni, pulizia e pezzi inclusi","Cerca macchie, strappi, ammaccature, colla, graffi, parti rotte e umidità. Confronta lacci, tracolle, sacchetti e pezzi rimovibili con l’ordine.","Segui un percorso fisso su fronte, retro, lati, sopra e sotto. Per le coppie controlla entrambi. Descrivi posizione, dimensione e numero foto.",
"Scegli il passo successivo finché le opzioni sono aperte","Se c’è una possibile differenza, fermati prima del pacco. Controlla le opzioni post-vendita e fai una domanda precisa. Foto, misura, conferma, reso o cambio dipendono dalle regole.","Tre esiti: accetta se coincide; chiedi altre prove; oppure usa il percorso post-vendita per una differenza importante. Le prove valgono più di un giudizio generico.",
"Conosci i limiti delle gallerie QC","Le gallerie condivise mostrano angoli utili e possibili difetti, ma non provano che la tua unità sarà uguale. Cambiano venditore, lotto, variante e data.","Una recensione utile include data, foto, fonte esatta e separa servizio di magazzino e qualità venditore. Stelle o velocità da sole dicono poco; un caso non è uno standard ufficiale.",
"Quante foto QC gratuite indica ACBuy?","La pagina ufficiale attuale indica tre-cinque. Conferma il set e i servizi nell’account.","Le foto QC provano l’autenticità?","No. Mostrano elementi visibili, ma non sono test di laboratorio o autenticazione legale.","Cosa fare se manca un dettaglio?","Controlla le opzioni attuali per foto o assistenza e chiedi una vista precisa e misurabile.","Bastano le immagini del venditore?","No. Descrivono l’offerta; le foto di magazzino mostrano l’unità arrivata e vanno confrontate con l’ordine."
]),
pl: make([
"Zdjęcia QC ACBuy: praktyczna lista","Zdjęcia QC ACBuy: co sprawdzać, co potwierdzają i czego nie pokazują","QC w magazynie","zdjęcia QC ACBuy","Zdjęcia magazynowe są pierwszym dowodem fizycznego artykułu. Stała metoda wykrywa widoczne problemy i uwzględnia ograniczenia obrazu.","Aktualna oficjalna strona ACBuy podaje trzy–pięć darmowych zdjęć QC i kontrolę po przyjęciu. To bieżące informacje; zdjęcia nie są uwierzytelnieniem ani gwarancją.",
"Zgodność zamówienia","Kształt całości","Spójność koloru","Szczegóły wykonania","Wymiary","Uszkodzenia i dodatki","Sprawdzaj dowody zawsze w tej samej kolejności; stałość zmniejsza liczbę przeoczonych wad.",
"Zrozum rolę QC w magazynie","Zdjęcia QC są między ofertą sprzedawcy a paczką międzynarodową. Oferta pokazuje obietnicę, zdjęcia — towar przyjęty. ACBuy opisuje kontrolę i trzy–pięć darmowych zdjęć; zakres potwierdź na koncie.","Nie chodzi o atrakcyjny wygląd zdjęć, lecz o możliwość porównania. QC pokazuje zły kolor, uszkodzenia, brak dodatku lub widoczną różnicę, ale nie gwarantuje materiału, dopasowania, trwałości ani odprawy.","Dowód, nie certyfikat","Traktuj zdjęcia jako dowód wizualny jednego artykułu, nie jako uwierzytelnienie, test laboratoryjny lub gwarancję jakości.",
"Otwórz zamówienie przed oglądaniem zdjęć","Zacznij od zamówienia: ID źródła, kolor, rozmiar, ilość, zestaw i widoczne obietnice. Bez zapisanego wariantu podobne opcje trudno później rozróżnić.","Zapisz dwie–trzy cechy obowiązkowe: rozmiar, podeszwa i sznurowadła; pasek i zamknięcie; albo rozmiar, nadruk i wymiary. Zdjęcia stają się wtedy porównaniem.",
"Najpierw sprawdź kształt całości","Zacznij od najszerszego widoku. Porównaj strony, proporcje, ustawienie, kształt, konstrukcję i układ materiału. Artykuł może mieć czyste szwy, a nadal być skręcony lub nierówny.","Perspektywa myli: bliższa strona wygląda na większą, a miękki produkt może opaść. Porównaj kilka ujęć; różnica widoczna wszędzie ma większe znaczenie.","Porównaj proporcje przed drobnymi detalami.","Szukaj nierównowagi i przesuniętych paneli.","Użyj kilku ujęć, by oddzielić kształt od perspektywy.","Poproś o wyraźniejszy dowód, jeśli widok nie odpowiada.",
"Oceniaj kolor jako wzór","Światło, balans bieli i ekran zmieniają odcienie. Porównaj wszystkie zdjęcia i szukaj stałej różnicy. Zdjęcie sprzedawcy jest odniesieniem, nie skalibrowanym wzorcem.","Porównuj elementy, które powinny być zgodne w tym samym ujęciu: buty, pasek i korpus, obszary nadruku. Gdy kolor jest kluczowy, poproś o wyraźniejsze ujęcie.",
"Powiększ wykonanie i okucia","Sprawdź szwy, haft, nadruk, zamki, klamry, oczka, łączenia i mocowania. Szukaj brakujących ściegów, luźnych nici, przesuniętej grafiki, łuszczenia, rys i różnych części.","Oddziel kosmetykę od funkcji. Luźna nić to nie to samo co zepsuty zamek lub pęknięte mocowanie. Jeśli funkcja jest ważna, poproś o odpowiedni dowód.","Nie rób QC jednego logo","Wykonanie, symetria, wymiary, uszkodzenia i dodatki mówią więcej niż jedno zbliżenie logo.",
"Użyj wymiarów do sprawdzenia rozmiaru","Metka nie potwierdza dopasowania. Porównaj widoczne lub zamówione wymiary z własnym artykułem: klatka, długość, ramię, rękaw, wkładka lub wymiary torby.","Zdjęcia miary mają ograniczenia: początek taśmy, położenie i napięcie muszą być poprawne. Gdy brakuje wymiaru, sprawdź opcje zdjęcia; nie wymyślaj dokładnej liczby.",
"Sprawdź uszkodzenia, czystość i dodatki","Szukaj plam, rozdarć, wgnieceń, kleju, rys, złamanych części i wilgoci. Porównaj sznurowadła, paski, worki i elementy zdejmowane z zamówieniem.","Idź stałą drogą przez przód, tył, boki, górę i spód. W parach sprawdź obie sztuki. Opisz miejsce, rozmiar i numer zdjęcia.",
"Wybierz kolejny krok, gdy opcje są dostępne","Przy możliwej różnicy zatrzymaj się przed wysłaniem paczki. Sprawdź bieżące opcje posprzedażowe i zadaj konkretne pytanie. Zdjęcie, wymiar, potwierdzenie, zwrot lub wymiana zależą od zasad.","Trzy wyniki: zaakceptuj przy zgodności; poproś o więcej dowodów; albo użyj ścieżki posprzedażowej przy istotnej różnicy. Dowody są ważniejsze niż ogólna opinia.",
"Poznaj ograniczenia galerii QC","Galerie pokazują użyteczne kąty i możliwe wady, ale nie dowodzą, że twoja sztuka będzie taka sama. Zmieniają się sprzedawcy, partie, warianty i daty.","Użyteczna recenzja ma datę, zdjęcia, dokładne źródło i oddziela obsługę magazynu od jakości produktu. Same gwiazdki lub szybkość mówią niewiele; przypadek nie jest normą.",
"Ile darmowych zdjęć QC podaje ACBuy?","Aktualna strona oficjalna podaje trzy–pięć. Potwierdź zestaw i usługi na koncie.","Czy zdjęcia QC potwierdzają autentyczność?","Nie. Pokazują cechy widoczne, ale nie są testem laboratoryjnym ani prawnym uwierzytelnieniem.","Co zrobić, gdy brakuje szczegółu?","Sprawdź bieżące opcje zdjęć lub wsparcia i poproś o konkretne, mierzalne ujęcie.","Czy zdjęcia sprzedawcy wystarczą?","Nie. Opisują ofertę; zdjęcia magazynowe pokazują przyjętą sztukę i trzeba je porównać z zamówieniem."
])};
