import { article1Translations } from "./article-1-translations";
import { article2Translations } from "./article-2-translations";
import { article3Translations } from "./article-3-translations";
import { article4Translations } from "./article-4-translations";
import { polishPageTranslations } from "./polish-page-translations";

export type TranslationPairs = Array<[string, string]>;

const common: Record<"de" | "fr" | "es" | "it" | "pl", TranslationPairs> = {
  de: [["Facts checked against current official pages","Fakten mit aktuellen offiziellen Seiten abgeglichen"],["Home","Startseite"],["Articles","Artikel"],["Updated","Aktualisiert"],["min read","Min. Lesezeit"],["Primary keyword:","Hauptkeyword:"],["In this guide","In diesem Leitfaden"],["Research note","Recherchehinweis"],["Questions readers usually ask","Häufige Fragen von Lesern"],["Sources and verification","Quellen und Prüfung"],["Platform-specific statements were checked on ACBuy’s official homepage, shopping flow and product-order interface on","Plattformspezifische Aussagen wurden auf der offiziellen ACBuy-Startseite, im Einkaufsablauf und in der Bestelloberfläche geprüft am"],["Policies, routes, prices and availability can change, so live account information takes priority.","Regeln, Routen, Preise und Verfügbarkeit können sich ändern; aktuelle Kontoinformationen haben Vorrang."],["Read next","Weiterlesen"],["Continue the research.","Recherche fortsetzen."],["Use the research","Recherche anwenden"],["Compare current product records.","Aktuelle Produkteinträge vergleichen."],["Browse the full catalog ↗","Vollständigen Katalog öffnen ↗"],["Independent educational guide. Verify current product, storage, shipping and after-sales details before ordering.","Unabhängiger Ratgeber. Prüfe vor der Bestellung aktuelle Produkt-, Lager-, Versand- und After-Sales-Daten."]],
  fr: [["Facts checked against current official pages","Informations vérifiées sur les pages officielles actuelles"],["Home","Accueil"],["Articles","Articles"],["Updated","Mis à jour"],["min read","min de lecture"],["Primary keyword:","Mot-clé principal :"],["In this guide","Dans ce guide"],["Research note","Note de recherche"],["Questions readers usually ask","Questions fréquentes des lecteurs"],["Sources and verification","Sources et vérification"],["Platform-specific statements were checked on ACBuy’s official homepage, shopping flow and product-order interface on","Les informations propres à la plateforme ont été vérifiées sur la page officielle ACBuy, le parcours d’achat et l’interface de commande le"],["Policies, routes, prices and availability can change, so live account information takes priority.","Les règles, lignes, prix et disponibilités peuvent changer ; les informations du compte en direct priment."],["Read next","À lire ensuite"],["Continue the research.","Poursuivre la recherche."],["Use the research","Appliquer la recherche"],["Compare current product records.","Comparer les fiches produit actuelles."],["Browse the full catalog ↗","Parcourir le catalogue complet ↗"],["Independent educational guide. Verify current product, storage, shipping and after-sales details before ordering.","Guide indépendant. Vérifiez les informations actuelles sur le produit, le stockage, l’expédition et l’après-vente avant de commander."]],
  es: [["Facts checked against current official pages","Datos comprobados en páginas oficiales actuales"],["Home","Inicio"],["Articles","Artículos"],["Updated","Actualizado"],["min read","min de lectura"],["Primary keyword:","Palabra clave principal:"],["In this guide","En esta guía"],["Research note","Nota de investigación"],["Questions readers usually ask","Preguntas habituales de los lectores"],["Sources and verification","Fuentes y verificación"],["Platform-specific statements were checked on ACBuy’s official homepage, shopping flow and product-order interface on","Las afirmaciones sobre la plataforma se comprobaron en la página oficial de ACBuy, el proceso de compra y la interfaz de pedido el"],["Policies, routes, prices and availability can change, so live account information takes priority.","Las políticas, rutas, precios y disponibilidad pueden cambiar; la información de la cuenta en vivo tiene prioridad."],["Read next","Leer después"],["Continue the research.","Continúa investigando."],["Use the research","Aplica la investigación"],["Compare current product records.","Compara fichas de producto actuales."],["Browse the full catalog ↗","Explorar el catálogo completo ↗"],["Independent educational guide. Verify current product, storage, shipping and after-sales details before ordering.","Guía educativa independiente. Verifica producto, almacenamiento, envío y posventa antes de pedir."]],
  it: [["Facts checked against current official pages","Dati verificati sulle pagine ufficiali attuali"],["Home","Home"],["Articles","Articoli"],["Updated","Aggiornato"],["min read","min di lettura"],["Primary keyword:","Parola chiave principale:"],["In this guide","In questa guida"],["Research note","Nota di ricerca"],["Questions readers usually ask","Domande frequenti dei lettori"],["Sources and verification","Fonti e verifica"],["Platform-specific statements were checked on ACBuy’s official homepage, shopping flow and product-order interface on","Le affermazioni sulla piattaforma sono state verificate sulla pagina ufficiale ACBuy, nel flusso di acquisto e nell’interfaccia d’ordine il"],["Policies, routes, prices and availability can change, so live account information takes priority.","Regole, rotte, prezzi e disponibilità possono cambiare; le informazioni live dell’account hanno priorità."],["Read next","Leggi dopo"],["Continue the research.","Continua la ricerca."],["Use the research","Usa la ricerca"],["Compare current product records.","Confronta le schede prodotto attuali."],["Browse the full catalog ↗","Sfoglia il catalogo completo ↗"],["Independent educational guide. Verify current product, storage, shipping and after-sales details before ordering.","Guida indipendente. Verifica prodotto, deposito, spedizione e assistenza prima di ordinare."]],
  pl: [["Facts checked against current official pages","Fakty sprawdzone na aktualnych stronach oficjalnych"],["Home","Strona główna"],["Articles","Artykuły"],["Updated","Aktualizacja"],["min read","min czytania"],["Primary keyword:","Główne słowo kluczowe:"],["In this guide","W tym poradniku"],["Research note","Nota badawcza"],["Questions readers usually ask","Najczęstsze pytania czytelników"],["Sources and verification","Źródła i weryfikacja"],["Platform-specific statements were checked on ACBuy’s official homepage, shopping flow and product-order interface on","Informacje o platformie sprawdzono na oficjalnej stronie ACBuy, w procesie zakupowym i interfejsie zamówienia dnia"],["Policies, routes, prices and availability can change, so live account information takes priority.","Zasady, trasy, ceny i dostępność mogą się zmieniać; pierwszeństwo mają dane widoczne na koncie."],["Read next","Czytaj dalej"],["Continue the research.","Kontynuuj analizę."],["Use the research","Wykorzystaj analizę"],["Compare current product records.","Porównaj aktualne wpisy produktów."],["Browse the full catalog ↗","Przeglądaj pełny katalog ↗"],["Independent educational guide. Verify current product, storage, shipping and after-sales details before ordering.","Niezależny poradnik. Przed zamówieniem sprawdź aktualne dane produktu, magazynowania, wysyłki i obsługi posprzedażowej."]],
};

const infoPageVerification: Record<"de" | "fr" | "es" | "it" | "pl", TranslationPairs> = {
  de: [
    ["Facts checked August 26, 2026", "Fakten geprüft am 26. August 2026"],
    ["Platform-specific statements were reviewed against ACBuy’s current official homepage, shopping flow and product-order interface. Live account terms take priority when prices, routes, storage, QC or after-sales options change.", "Plattformspezifische Angaben wurden anhand der aktuellen offiziellen ACBuy-Startseite, des Einkaufsablaufs und der Bestelloberfläche geprüft. Wenn sich Preise, Versandrouten, Lagerung, Qualitätskontrolle oder After-Sales-Optionen ändern, gelten vorrangig die aktuellen Bedingungen im Konto."],
    ["August 26, 2026", "26. August 2026"],
  ],
  fr: [
    ["Facts checked August 26, 2026", "Informations vérifiées le 26 août 2026"],
    ["Platform-specific statements were reviewed against ACBuy’s current official homepage, shopping flow and product-order interface. Live account terms take priority when prices, routes, storage, QC or after-sales options change.", "Les informations propres à la plateforme ont été vérifiées sur la page d’accueil officielle actuelle d’ACBuy, le parcours d’achat et l’interface de commande. Si les prix, les lignes d’expédition, le stockage, le contrôle qualité ou les options après-vente changent, les conditions affichées dans le compte prévalent."],
    ["August 26, 2026", "26 août 2026"],
  ],
  es: [
    ["Facts checked August 26, 2026", "Datos comprobados el 26 de agosto de 2026"],
    ["Platform-specific statements were reviewed against ACBuy’s current official homepage, shopping flow and product-order interface. Live account terms take priority when prices, routes, storage, QC or after-sales options change.", "Las afirmaciones específicas de la plataforma se revisaron en la página oficial actual de ACBuy, el proceso de compra y la interfaz de pedidos. Si cambian los precios, las rutas, el almacenamiento, el control de calidad o las opciones posventa, prevalecen las condiciones vigentes en la cuenta."],
    ["August 26, 2026", "26 de agosto de 2026"],
  ],
  it: [
    ["Facts checked August 26, 2026", "Dati verificati il 26 agosto 2026"],
    ["Platform-specific statements were reviewed against ACBuy’s current official homepage, shopping flow and product-order interface. Live account terms take priority when prices, routes, storage, QC or after-sales options change.", "Le informazioni specifiche della piattaforma sono state verificate sulla pagina ufficiale attuale di ACBuy, nel flusso di acquisto e nell’interfaccia d’ordine. Se cambiano prezzi, rotte, deposito, controllo qualità o opzioni post-vendita, prevalgono le condizioni visibili nell’account."],
    ["August 26, 2026", "26 agosto 2026"],
  ],
  pl: [
    ["Facts checked August 26, 2026", "Fakty sprawdzone 26 sierpnia 2026 r."],
    ["Platform-specific statements were reviewed against ACBuy’s current official homepage, shopping flow and product-order interface. Live account terms take priority when prices, routes, storage, QC or after-sales options change.", "Informacje dotyczące platformy zweryfikowano na aktualnej oficjalnej stronie ACBuy, w procesie zakupowym i interfejsie zamówienia. Gdy zmieniają się ceny, trasy, przechowywanie, kontrola jakości lub opcje posprzedażowe, pierwszeństwo mają bieżące warunki widoczne na koncie."],
    ["August 26, 2026", "26 sierpnia 2026 r."],
  ],
};

const sharedLabels: Record<"de" | "fr" | "es" | "it" | "pl", TranslationPairs> = {
  de: [["Facts checked before publication", "Fakten vor der Veröffentlichung geprüft"], ["QC", "QC"], ["FAQ", "FAQ"], ["© 2026 ACBuy Finds. Not affiliated with ACBuy or displayed brands.", "© 2026 ACBuy Finds. Keine Verbindung zu ACBuy oder den dargestellten Marken."]],
  fr: [["Facts checked before publication", "Informations vérifiées avant publication"], ["QC", "QC"], ["FAQ", "FAQ"], ["© 2026 ACBuy Finds. Not affiliated with ACBuy or displayed brands.", "© 2026 ACBuy Finds. Site non affilié à ACBuy ni aux marques présentées."]],
  es: [["Facts checked before publication", "Datos verificados antes de publicar"], ["QC", "QC"], ["FAQ", "FAQ"], ["© 2026 ACBuy Finds. Not affiliated with ACBuy or displayed brands.", "© 2026 ACBuy Finds. Sitio no afiliado a ACBuy ni a las marcas mostradas."]],
  it: [["Facts checked before publication", "Dati verificati prima della pubblicazione"], ["QC", "QC"], ["FAQ", "FAQ"], ["© 2026 ACBuy Finds. Not affiliated with ACBuy or displayed brands.", "© 2026 ACBuy Finds. Sito non affiliato ad ACBuy né ai marchi mostrati."]],
  pl: [["Facts checked before publication", "Fakty sprawdzone przed publikacją"], ["QC", "QC"], ["FAQ", "FAQ"], ["© 2026 ACBuy Finds. Not affiliated with ACBuy or displayed brands.", "© 2026 ACBuy Finds. Serwis nie jest powiązany z ACBuy ani prezentowanymi markami."]],
};

export const longArticleTranslations: Record<"de" | "fr" | "es" | "it" | "pl", TranslationPairs> = {
  de: [...common.de, ...infoPageVerification.de, ...sharedLabels.de, ...article1Translations.de, ...article2Translations.de, ...article3Translations.de, ...article4Translations.de],
  fr: [...common.fr, ...infoPageVerification.fr, ...sharedLabels.fr, ...article1Translations.fr, ...article2Translations.fr, ...article3Translations.fr, ...article4Translations.fr],
  es: [...common.es, ...infoPageVerification.es, ...sharedLabels.es, ...article1Translations.es, ...article2Translations.es, ...article3Translations.es, ...article4Translations.es],
  it: [...common.it, ...infoPageVerification.it, ...sharedLabels.it, ...article1Translations.it, ...article2Translations.it, ...article3Translations.it, ...article4Translations.it],
  pl: [...common.pl, ...infoPageVerification.pl, ...sharedLabels.pl, ...polishPageTranslations, ...article1Translations.pl, ...article2Translations.pl, ...article3Translations.pl, ...article4Translations.pl],
};
