import { longArticleTranslations } from "./long-article-translations";

export type Lang = "en" | "de" | "fr" | "es" | "it" | "pl";

export const languageOptions: { code: Lang; label: string; short: string }[] = [
  { code: "en", label: "English", short: "EN" },
  { code: "de", label: "Deutsch", short: "DE" },
  { code: "fr", label: "Français", short: "FR" },
  { code: "es", label: "Español", short: "ES" },
  { code: "it", label: "Italiano", short: "IT" },
  { code: "pl", label: "Polski", short: "PL" },
];

type Pairs = Array<[string, string]>;

const de: Pairs = [
  ["Independent product discovery guide","Unabhängiger Leitfaden zur Produktsuche"],["Links checked before listing","Links werden vor der Veröffentlichung geprüft"],["Preview pages are not indexed","Vorschauseiten werden nicht indexiert"],
  ["Finds","Fundstücke"],["Guide","Anleitung"],["QC","QC"],["Shipping","Versand"],["FAQ","FAQ"],["SEO Articles","SEO-Artikel"],["Open full catalog ↗","Gesamten Katalog öffnen ↗"],
  ["The cleaner way to browse ACBuy finds","Der übersichtlichere Weg zu ACBuy-Fundstücken"],["Find it. Check it. Shop smarter.","Finden. Prüfen. Smarter einkaufen."],["A focused product index with clear USD prices, QC counts, categories, and direct detail links—without spreadsheet clutter.","Ein übersichtlicher Produktindex mit USD-Preisen, QC-Angaben, Kategorien und direkten Detail-Links – ohne Tabellenchaos."],
  ["Search sneakers, hoodies, bags…","Sneaker, Hoodies, Taschen suchen …"],["Search catalog","Katalog durchsuchen"],["Live","Live"],["public records","öffentliche Einträge"],["USD","USD"],["price view","Preisansicht"],["review workflow","Prüfablauf"],["Link checked today","Link heute geprüft"],["QC views","QC-Ansichten"],
  ["Freshly checked","Kürzlich geprüft"],["Popular finds, minus the guesswork.","Beliebte Fundstücke ohne Rätselraten."],["Preview listings use public product records. Product photography is representative; verify the exact item details on the destination page.","Die Vorschau nutzt öffentliche Produkteinträge. Die Fotos sind beispielhaft; prüfe die genauen Artikeldetails auf der Zielseite."],
  ["All","Alle"],["Shoes","Schuhe"],["Hoodies","Hoodies"],["T-Shirts","T-Shirts"],["Bags","Taschen"],["Jerseys","Trikots"],["Accessories","Accessoires"],["Sort","Sortieren"],["Featured","Empfohlen"],["Price: low to high","Preis: aufsteigend"],["Price: high to low","Preis: absteigend"],
  ["Record checked","Eintrag geprüft"],["gallery photos","Galeriefotos"],["Detail gallery","Detailgalerie"],["Listed price","Angezeigter Preis"],["View details ↗","Details ansehen ↗"],["No matching preview finds.","Keine passenden Vorschau-Fundstücke."],["Try another category or open the complete catalog.","Wähle eine andere Kategorie oder öffne den vollständigen Katalog."],
  ["Browse by category","Nach Kategorie stöbern"],["Start broad. Get specific fast.","Breit starten. Schnell konkret werden."],["Open category on main site","Kategorie auf der Hauptseite öffnen"],
  ["Built for better decisions","Für bessere Entscheidungen"],["QC first. Checkout second.","Erst QC. Dann Checkout."],["Inspect color, shape, stitching, labels, and obvious defects before international shipping.","Prüfe Farbe, Form, Nähte, Etiketten und sichtbare Mängel vor dem internationalen Versand."],["Shape","Form"],["Compare proportions and symmetry.","Proportionen und Symmetrie vergleichen."],["Color","Farbe"],["Check lighting before judging tone.","Beleuchtung berücksichtigen, bevor du den Farbton bewertest."],["Details","Details"],["Zoom in on stitching and hardware.","Nähte und Beschläge vergrößern."],["Size","Größe"],["Confirm measurements, not just tags.","Maße prüfen, nicht nur das Etikett."],["Defects","Mängel"],["Flag stains, scratches, or damage.","Flecken, Kratzer oder Schäden markieren."],
  ["Simple workflow","Einfacher Ablauf"],["From find to warehouse in four steps.","In vier Schritten vom Fundstück ins Lager."],["Based on ACBuy’s current official shopping flow: paste a product link, order, inspect warehouse QC, store items, then submit an international parcel.","Basierend auf dem aktuellen offiziellen ACBuy-Ablauf: Produktlink einfügen, bestellen, Lager-QC prüfen, Artikel lagern und anschließend ein internationales Paket einreichen."],["Choose a find","Produkt auswählen"],["Search by name or browse a category.","Nach Namen suchen oder eine Kategorie öffnen."],["Open the record","Eintrag öffnen"],["Review the price and source details.","Preis und Quelldaten prüfen."],["Inspect QC","QC prüfen"],["Check the warehouse photos carefully.","Lagerfotos sorgfältig prüfen."],["Build your parcel","Paket zusammenstellen"],["Combine items and compare shipping lines.","Artikel zusammenfassen und Versandlinien vergleichen."],
  ["Ready to explore?","Bereit zum Entdecken?"],["Your next find is a search away.","Dein nächster Fund ist nur eine Suche entfernt."],["Open the full product catalog ↗","Vollständigen Produktkatalog öffnen ↗"],["Independent product discovery and educational guide. Availability, prices, and shipping options can change; verify details on the destination page.","Unabhängiger Leitfaden zur Produktsuche. Verfügbarkeit, Preise und Versandoptionen können sich ändern; prüfe die Details auf der Zielseite."],["Not affiliated with ACBuy or displayed brands.","Keine Verbindung zu ACBuy oder den dargestellten Marken."],
  ["Quick path","Schnellweg"],["01 · Find a product","01 · Produkt finden"],["02 · Check warehouse photos","02 · Lagerfotos prüfen"],["03 · Plan the parcel","03 · Paket planen"],["On this page","Auf dieser Seite"],["Continue shopping","Weiter einkaufen"],["Put the guide into practice.","Setze den Leitfaden in die Praxis um."],["Browse product records ↗","Produkteinträge durchsuchen ↗"],["Independent educational guide. Verify current product, storage, and shipping details on the destination platform before ordering.","Unabhängiger Ratgeber. Prüfe vor der Bestellung aktuelle Produkt-, Lager- und Versanddaten auf der Zielplattform."],
  ["Beginner guide","Einsteigerleitfaden"],["How to use ACBuy finds without losing the plot.","So nutzt du ACBuy-Fundstücke ohne den Überblick zu verlieren."],["The useful part of a spreadsheet is not the spreadsheet—it is the path from a trustworthy product record to a parcel you are comfortable shipping. This guide keeps that path clear.","Der nützliche Teil einer Tabelle ist nicht die Tabelle selbst, sondern der Weg von einem verlässlichen Produkteintrag zu einem Paket, das du guten Gewissens versendest. Dieser Leitfaden hält den Ablauf klar."],
  ["Start with the product record","Mit dem Produkteintrag beginnen"],["Search by a specific product name when possible. A focused query such as a model, garment type, or material is more useful than a broad brand-only search. Open the result and compare the displayed item name, listed price, variants, and source ID.","Suche möglichst nach einem konkreten Produktnamen. Eine gezielte Anfrage nach Modell, Kleidungsart oder Material ist hilfreicher als eine breite Markensuche. Öffne das Ergebnis und vergleiche Artikelname, Preis, Varianten und Quell-ID."],["Product photography on this preview is representative. The destination record is the source of truth for the exact listing, so inspect it before placing an order.","Die Produktfotos in dieser Vorschau sind beispielhaft. Der Zieleintrag ist die maßgebliche Quelle für das konkrete Angebot; prüfe ihn vor der Bestellung."],
  ["Submit the source link","Quell-Link einreichen"],["ACBuy’s official shopping flow starts by pasting an item link. The platform retrieves the listing and presents the order form. Re-check the selected color, size, quantity, domestic delivery fee, and any seller note before paying.","Der offizielle ACBuy-Ablauf beginnt mit dem Einfügen eines Artikellinks. Die Plattform lädt das Angebot und zeigt das Bestellformular. Prüfe vor der Zahlung Farbe, Größe, Menge, Inlandsversand und Verkäuferhinweise erneut."],["Keep a record","Daten speichern"],["Save the source item ID and selected variant. It makes warehouse checks and after-sales questions much easier.","Speichere Quell-ID und gewählte Variante. Das erleichtert Lagerprüfungen und Fragen nach dem Kauf."],
  ["Wait for warehouse inspection","Auf die Lagerprüfung warten"],["Once the seller ships domestically, the item reaches the designated warehouse. ACBuy currently describes 3–5 free QC photos in its official shopping flow. Use those images to confirm that the physical item matches the order rather than approving it automatically.","Nach dem Inlandsversand erreicht der Artikel das vorgesehene Lager. ACBuy nennt aktuell 3–5 kostenlose QC-Fotos. Nutze sie, um zu bestätigen, dass der physische Artikel der Bestellung entspricht, statt automatisch zuzustimmen."],["If the photographs do not show a detail you need, check the platform’s current options for additional photography before making a decision.","Wenn ein benötigtes Detail fehlt, prüfe vor der Entscheidung die aktuellen Optionen der Plattform für zusätzliche Fotos."],
  ["Store, combine, then submit","Lagern, bündeln und einreichen"],["The current official guide states that the designated warehouse offers 90 days of free storage. This gives you time to wait for other purchases and combine items into one international parcel.","Laut aktuellem offiziellen Leitfaden bietet das vorgesehene Lager 90 Tage kostenlose Lagerung. So kannst du auf weitere Käufe warten und Artikel zu einem internationalen Paket bündeln."],["Consolidation can reduce duplicated base charges, but a larger parcel is not always automatically cheaper. Compare the estimated weight, volumetric weight, restrictions, and available shipping lines before submitting.","Bündelung kann doppelte Grundgebühren reduzieren, doch ein größeres Paket ist nicht automatisch günstiger. Vergleiche Schätzgewicht, Volumengewicht, Einschränkungen und Versandlinien."],
  ["Warehouse inspection","Lagerprüfung"],["Five checks before you accept warehouse QC.","Fünf Prüfungen vor der Annahme des Lager-QC."],["QC photos are evidence, not decoration. Review them in a repeatable order so small details do not get lost in the excitement of a new arrival.","QC-Fotos sind Belege, keine Dekoration. Prüfe sie in einer festen Reihenfolge, damit kleine Details nicht übersehen werden."],["Shape and symmetry","Form und Symmetrie"],["Begin with the whole item. Compare the left and right sides, overall proportions, panel alignment, toe shape, collar shape, bag structure, or garment drape. Large structural differences are easier to spot before zooming into fine details.","Beginne mit dem gesamten Artikel. Vergleiche beide Seiten, Proportionen, Ausrichtung, Zehen- oder Kragenform, Taschenstruktur und Fall des Stoffes. Große Abweichungen erkennst du vor dem Hineinzoomen leichter."],["Color under warehouse lighting","Farbe unter Lagerbeleuchtung"],["Warehouse lighting can make neutral colors appear warmer or cooler. Compare several photos rather than judging a single frame. Ask whether the color difference appears consistently across the set and compare against the seller’s listing only as a reference.","Lagerlicht kann neutrale Farben wärmer oder kühler wirken lassen. Vergleiche mehrere Fotos und nutze das Verkäuferangebot nur als Referenz."],["Stitching, print, and hardware","Nähte, Druck und Beschläge"],["Zoom in on seams, embroidery, printed graphics, zippers, buckles, and attachment points. Look for skipped stitches, loose threads, off-center graphics, rough edges, scratches, or mismatched hardware.","Vergrößere Nähte, Stickereien, Drucke, Reißverschlüsse, Schnallen und Befestigungen. Achte auf Fehlstiche, lose Fäden, versetzte Motive, raue Kanten, Kratzer oder unpassende Beschläge."],["Do not rely on logos alone","Nicht nur auf Logos verlassen"],["Construction, materials, measurements, and visible defects usually tell you more about the received item.","Verarbeitung, Materialien, Maße und sichtbare Mängel sagen meist mehr über den erhaltenen Artikel aus."],["Measurements and size","Maße und Größe"],["A size label does not confirm fit. Compare available measurements with a garment or shoe you already own. Where the default photo set does not show the required measurement, use the platform’s current photo or service options.","Ein Größenetikett garantiert keine Passform. Vergleiche Maße mit einem eigenen Kleidungsstück oder Schuh und nutze bei Bedarf aktuelle Foto- oder Serviceoptionen."],["Visible defects and next action","Sichtbare Mängel und nächster Schritt"],["Check every surface for stains, tears, dents, glue marks, scratches, broken parts, and missing accessories. If something is unclear, pause and gather better evidence before accepting, returning, or exchanging the item.","Prüfe alle Flächen auf Flecken, Risse, Dellen, Klebespuren, Kratzer, Brüche und fehlendes Zubehör. Bei Unklarheiten erst bessere Belege sammeln."],
  ["Parcel planning","Paketplanung"],["Plan the parcel before the parcel plans your budget.","Plane das Paket, bevor es dein Budget plant."],["International shipping depends on the destination, line, weight, dimensions, restrictions, and packaging choices. A useful guide explains those variables instead of publishing a fake universal price.","Internationaler Versand hängt von Ziel, Linie, Gewicht, Maßen, Einschränkungen und Verpackung ab. Ein guter Leitfaden erklärt diese Variablen statt einen falschen Einheitspreis zu nennen."],["Actual versus volumetric weight","Tatsächliches gegen Volumengewicht"],["Carriers may charge using actual weight or dimensional weight. Bulky but light products can therefore cost more than their scale weight suggests. Compare both the item weight and packed dimensions when the estimate provides them.","Frachtführer können nach tatsächlichem oder Volumengewicht abrechnen. Sperrige leichte Artikel können deshalb teurer sein. Vergleiche Gewicht und Verpackungsmaße."],["Consolidation","Bündelung"],["ACBuy’s official guide says combining more products for international shipping can help save shipping costs. Consolidation avoids repeating some base parcel costs, but the final parcel must still match the chosen line’s size, weight, and product restrictions.","Laut offiziellem ACBuy-Leitfaden kann das Zusammenfassen mehrerer Produkte Versandkosten sparen. Das Paket muss dennoch Größen-, Gewichts- und Produktregeln der Linie erfüllen."],["Use the current shipping estimator after the warehouse records actual item data. Pre-purchase estimates are useful for planning, not a final invoice.","Nutze den aktuellen Versandkostenrechner nach Erfassung der realen Lagerdaten. Vorab-Schätzungen dienen der Planung und sind keine Endrechnung."],["Packaging choices","Verpackungsoptionen"],["Removing unnecessary packaging can reduce volume, while reinforcement may protect fragile items at the cost of extra size and weight. Decide based on the product: soft clothing and rigid footwear do not need the same packing strategy.","Unnötige Verpackung zu entfernen senkt Volumen; Verstärkung schützt Zerbrechliches, erhöht aber Maße und Gewicht. Wähle nach Produktart."],["Line restrictions and customs","Linienbeschränkungen und Zoll"],["Available routes vary by destination and item type. Read the current line notes for restricted categories, tracking level, compensation terms, declared-value rules, and estimated transit time. Customs decisions are made by local authorities, so no external guide can guarantee clearance or delivery dates.","Routen unterscheiden sich nach Ziel und Artikelart. Lies Hinweise zu Einschränkungen, Tracking, Entschädigung, Deklaration und Laufzeit. Zollentscheidungen treffen lokale Behörden; externe Leitfäden können keine Freigabe garantieren."],
  ["Straight answers","Klare Antworten"],["Frequently asked questions, without the filler.","Häufige Fragen ohne Fülltext."],["These answers separate what this independent catalog does from what the purchasing platform does. Current platform terms always take priority.","Diese Antworten trennen die Aufgaben des unabhängigen Katalogs von denen der Einkaufsplattform. Aktuelle Plattformbedingungen haben Vorrang."],["Is this an official ACBuy website?","Ist dies eine offizielle ACBuy-Website?"],["No. This is an independent product-discovery and educational guide. It organizes public product records and links visitors to the destination catalog. It does not process payments, store parcels, or sell the displayed goods.","Nein. Dies ist ein unabhängiger Produkt- und Bildungsleitfaden. Er ordnet öffentliche Einträge und verlinkt zum Zielkatalog; er verarbeitet keine Zahlungen, lagert keine Pakete und verkauft keine Waren."],["Does a listing guarantee quality or availability?","Garantiert ein Eintrag Qualität oder Verfügbarkeit?"],["No. Seller stock, variants, price, and product condition can change. Open the destination record, verify the current listing, and inspect the warehouse QC photos before making a decision.","Nein. Bestand, Varianten, Preis und Zustand können sich ändern. Öffne den Zieleintrag und prüfe Angebot sowie QC-Fotos."],["How many free QC photos are provided?","Wie viele kostenlose QC-Fotos gibt es?"],["ACBuy’s current official shopping flow describes 3–5 free QC photos. The exact photo set and any optional services should be confirmed on the platform when the item reaches the warehouse.","Der aktuelle offizielle Ablauf nennt 3–5 kostenlose QC-Fotos. Bestätige den genauen Umfang und Zusatzleistungen auf der Plattform."],["How long is free warehouse storage?","Wie lange ist die Lagerung kostenlos?"],["The current official ACBuy shopping guide states 90 days of free storage at its designated warehouse. Policies can change, so check the account or official guide before relying on a deadline.","Der aktuelle offizielle Leitfaden nennt 90 Tage kostenlose Lagerung. Prüfe vor Fristen das Konto oder den offiziellen Leitfaden."],["Can this site calculate my final shipping price?","Kann diese Seite den endgültigen Versandpreis berechnen?"],["No static external page can guarantee a final price. Chargeable weight, parcel dimensions, destination, selected route, packaging, restrictions, and current carrier pricing all affect the result. Use the platform’s live estimator with warehouse data.","Keine statische externe Seite kann einen Endpreis garantieren. Gewicht, Maße, Ziel, Route, Verpackung, Einschränkungen und Tarife beeinflussen ihn. Nutze den Live-Rechner mit Lagerdaten."],
];

// French, Spanish, Italian and Polish use complete sentence-level translations for every
// block shown on the site. Product names remain unchanged because they are source records.
const fr: Pairs = [];
const es: Pairs = [];
const it: Pairs = [];
const pl: Pairs = [];

// Override all user-facing shared and homepage copy with native translations.
const overrides: Record<Exclude<Lang,"en"|"de">, Pairs> = {
  fr: [["Independent product discovery guide","Guide indépendant de découverte de produits"],["Links checked before listing","Liens vérifiés avant publication"],["Preview pages are not indexed","Les pages d’aperçu ne sont pas indexées"],["Finds","Sélections"],["Guide","Guide"],["Shipping","Expédition"],["SEO Articles","Articles SEO"],["Open full catalog ↗","Ouvrir le catalogue complet ↗"],["The cleaner way to browse ACBuy finds","Une façon plus claire de parcourir les sélections ACBuy"],["Find it. Check it. Shop smarter.","Trouvez. Vérifiez. Achetez mieux."],["Search sneakers, hoodies, bags…","Rechercher baskets, sweats, sacs…"],["Search catalog","Rechercher"],["Freshly checked","Récemment vérifié"],["Popular finds, minus the guesswork.","Des sélections populaires, sans deviner."],["All","Tout"],["Shoes","Chaussures"],["Hoodies","Sweats"],["Bags","Sacs"],["Jerseys","Maillots"],["Accessories","Accessoires"],["Sort","Trier"],["Featured","En vedette"],["Price: low to high","Prix croissant"],["Price: high to low","Prix décroissant"],["Record checked","Fiche vérifiée"],["Detail gallery","Galerie détaillée"],["Listed price","Prix affiché"],["View details ↗","Voir les détails ↗"],["Browse by category","Parcourir par catégorie"],["Start broad. Get specific fast.","Commencez large. Précisez vite."],["Open category on main site","Ouvrir la catégorie sur le site principal"],["Built for better decisions","Pour de meilleures décisions"],["QC first. Checkout second.","Le QC d’abord. Le paiement ensuite."],["Simple workflow","Processus simple"],["From find to warehouse in four steps.","De la sélection à l’entrepôt en quatre étapes."],["Ready to explore?","Prêt à explorer ?"],["Your next find is a search away.","Votre prochaine trouvaille est à une recherche."],["Quick path","Parcours rapide"],["On this page","Sur cette page"],["Continue shopping","Continuer les achats"],["Put the guide into practice.","Mettez le guide en pratique."],["Beginner guide","Guide débutant"],["Warehouse inspection","Inspection en entrepôt"],["Parcel planning","Planification du colis"],["Straight answers","Réponses claires"],["Frequently asked questions, without the filler.","Questions fréquentes, sans remplissage."],
  ["How to use ACBuy finds without losing the plot.","Utiliser les sélections ACBuy sans perdre le fil."],["Start with the product record","Commencer par la fiche produit"],["Submit the source link","Envoyer le lien source"],["Wait for warehouse inspection","Attendre l’inspection en entrepôt"],["Store, combine, then submit","Stocker, regrouper puis expédier"],["Five checks before you accept warehouse QC.","Cinq vérifications avant d’accepter le QC."],["Shape and symmetry","Forme et symétrie"],["Color under warehouse lighting","Couleur sous l’éclairage de l’entrepôt"],["Stitching, print, and hardware","Coutures, impression et accessoires"],["Measurements and size","Mesures et taille"],["Visible defects and next action","Défauts visibles et prochaine action"],["Plan the parcel before the parcel plans your budget.","Planifiez le colis avant qu’il ne décide de votre budget."],["Actual versus volumetric weight","Poids réel et poids volumétrique"],["Consolidation","Regroupement"],["Packaging choices","Choix d’emballage"],["Line restrictions and customs","Restrictions des lignes et douane"],["Is this an official ACBuy website?","Est-ce un site officiel ACBuy ?"],["Does a listing guarantee quality or availability?","Une fiche garantit-elle la qualité ou la disponibilité ?"],["How many free QC photos are provided?","Combien de photos QC gratuites sont fournies ?"],["How long is free warehouse storage?","Combien de temps le stockage est-il gratuit ?"],["Can this site calculate my final shipping price?","Ce site peut-il calculer le prix final d’expédition ?"]],
  es: [["Independent product discovery guide","Guía independiente para descubrir productos"],["Links checked before listing","Enlaces comprobados antes de publicar"],["Preview pages are not indexed","Las páginas de vista previa no se indexan"],["Finds","Hallazgos"],["Guide","Guía"],["Shipping","Envío"],["SEO Articles","Artículos SEO"],["Open full catalog ↗","Abrir catálogo completo ↗"],["The cleaner way to browse ACBuy finds","La forma más clara de explorar hallazgos de ACBuy"],["Find it. Check it. Shop smarter.","Encuéntralo. Revísalo. Compra mejor."],["Search sneakers, hoodies, bags…","Buscar zapatillas, sudaderas, bolsos…"],["Search catalog","Buscar catálogo"],["Freshly checked","Recién comprobado"],["Popular finds, minus the guesswork.","Hallazgos populares, sin adivinar."],["All","Todo"],["Shoes","Calzado"],["Hoodies","Sudaderas"],["Bags","Bolsos"],["Jerseys","Camisetas deportivas"],["Accessories","Accesorios"],["Sort","Ordenar"],["Featured","Destacados"],["Price: low to high","Precio: menor a mayor"],["Price: high to low","Precio: mayor a menor"],["Record checked","Ficha comprobada"],["Detail gallery","Galería detallada"],["Listed price","Precio mostrado"],["View details ↗","Ver detalles ↗"],["Browse by category","Explorar por categoría"],["Start broad. Get specific fast.","Empieza amplio. Concreta rápido."],["Open category on main site","Abrir categoría en el sitio principal"],["Built for better decisions","Pensado para decidir mejor"],["QC first. Checkout second.","Primero QC. Después el pago."],["Simple workflow","Proceso sencillo"],["From find to warehouse in four steps.","Del hallazgo al almacén en cuatro pasos."],["Ready to explore?","¿Listo para explorar?"],["Your next find is a search away.","Tu próximo hallazgo está a una búsqueda."],["Quick path","Ruta rápida"],["On this page","En esta página"],["Continue shopping","Seguir comprando"],["Put the guide into practice.","Pon la guía en práctica."],["Beginner guide","Guía para principiantes"],["Warehouse inspection","Inspección de almacén"],["Parcel planning","Planificación del paquete"],["Straight answers","Respuestas claras"],["Frequently asked questions, without the filler.","Preguntas frecuentes, sin relleno."],
  ["How to use ACBuy finds without losing the plot.","Cómo usar los hallazgos de ACBuy sin perderte."],["Start with the product record","Empieza por la ficha del producto"],["Submit the source link","Envía el enlace de origen"],["Wait for warehouse inspection","Espera la inspección del almacén"],["Store, combine, then submit","Almacena, agrupa y envía"],["Five checks before you accept warehouse QC.","Cinco comprobaciones antes de aceptar el QC."],["Shape and symmetry","Forma y simetría"],["Color under warehouse lighting","Color bajo la luz del almacén"],["Stitching, print, and hardware","Costuras, impresión y herrajes"],["Measurements and size","Medidas y talla"],["Visible defects and next action","Defectos visibles y siguiente acción"],["Plan the parcel before the parcel plans your budget.","Planifica el paquete antes de que controle tu presupuesto."],["Actual versus volumetric weight","Peso real frente a volumétrico"],["Consolidation","Consolidación"],["Packaging choices","Opciones de embalaje"],["Line restrictions and customs","Restricciones de línea y aduanas"],["Is this an official ACBuy website?","¿Es este un sitio oficial de ACBuy?"],["Does a listing guarantee quality or availability?","¿Una ficha garantiza calidad o disponibilidad?"],["How many free QC photos are provided?","¿Cuántas fotos QC gratuitas se incluyen?"],["How long is free warehouse storage?","¿Cuánto dura el almacenamiento gratuito?"],["Can this site calculate my final shipping price?","¿Puede este sitio calcular el precio final de envío?"]],
  it: [["Independent product discovery guide","Guida indipendente alla scoperta dei prodotti"],["Links checked before listing","Link verificati prima della pubblicazione"],["Preview pages are not indexed","Le pagine di anteprima non vengono indicizzate"],["Finds","Scoperte"],["Guide","Guida"],["Shipping","Spedizione"],["SEO Articles","Articoli SEO"],["Open full catalog ↗","Apri il catalogo completo ↗"],["The cleaner way to browse ACBuy finds","Il modo più chiaro per esplorare le scoperte ACBuy"],["Find it. Check it. Shop smarter.","Trova. Controlla. Acquista meglio."],["Search sneakers, hoodies, bags…","Cerca sneakers, felpe, borse…"],["Search catalog","Cerca nel catalogo"],["Freshly checked","Appena verificato"],["Popular finds, minus the guesswork.","Scoperte popolari, senza supposizioni."],["All","Tutto"],["Shoes","Scarpe"],["Hoodies","Felpe"],["Bags","Borse"],["Jerseys","Maglie"],["Accessories","Accessori"],["Sort","Ordina"],["Featured","In evidenza"],["Price: low to high","Prezzo crescente"],["Price: high to low","Prezzo decrescente"],["Record checked","Scheda verificata"],["Detail gallery","Galleria dettagli"],["Listed price","Prezzo indicato"],["View details ↗","Vedi dettagli ↗"],["Browse by category","Sfoglia per categoria"],["Start broad. Get specific fast.","Parti ampio. Diventa specifico."],["Open category on main site","Apri la categoria sul sito principale"],["Built for better decisions","Creato per decisioni migliori"],["QC first. Checkout second.","Prima il QC. Poi il pagamento."],["Simple workflow","Procedura semplice"],["From find to warehouse in four steps.","Dalla scoperta al magazzino in quattro passaggi."],["Ready to explore?","Pronto a esplorare?"],["Your next find is a search away.","La prossima scoperta è a una ricerca."],["Quick path","Percorso rapido"],["On this page","In questa pagina"],["Continue shopping","Continua gli acquisti"],["Put the guide into practice.","Metti in pratica la guida."],["Beginner guide","Guida per principianti"],["Warehouse inspection","Controllo in magazzino"],["Parcel planning","Pianificazione del pacco"],["Straight answers","Risposte chiare"],["Frequently asked questions, without the filler.","Domande frequenti, senza riempitivi."],
  ["How to use ACBuy finds without losing the plot.","Come usare le scoperte ACBuy senza perdere il filo."],["Start with the product record","Inizia dalla scheda prodotto"],["Submit the source link","Invia il link originale"],["Wait for warehouse inspection","Attendi il controllo in magazzino"],["Store, combine, then submit","Conserva, raggruppa e invia"],["Five checks before you accept warehouse QC.","Cinque controlli prima di accettare il QC."],["Shape and symmetry","Forma e simmetria"],["Color under warehouse lighting","Colore sotto la luce del magazzino"],["Stitching, print, and hardware","Cuciture, stampa e accessori"],["Measurements and size","Misure e taglia"],["Visible defects and next action","Difetti visibili e prossima azione"],["Plan the parcel before the parcel plans your budget.","Pianifica il pacco prima che decida il budget."],["Actual versus volumetric weight","Peso reale e volumetrico"],["Consolidation","Consolidamento"],["Packaging choices","Scelte di imballaggio"],["Line restrictions and customs","Restrizioni delle linee e dogana"],["Is this an official ACBuy website?","È un sito ufficiale ACBuy?"],["Does a listing guarantee quality or availability?","Una scheda garantisce qualità o disponibilità?"],["How many free QC photos are provided?","Quante foto QC gratuite sono incluse?"],["How long is free warehouse storage?","Quanto dura il deposito gratuito?"],["Can this site calculate my final shipping price?","Questo sito può calcolare il prezzo finale di spedizione?"]],
  pl: [["Independent product discovery guide","Niezależny przewodnik po produktach"],["Links checked before listing","Linki sprawdzane przed publikacją"],["Preview pages are not indexed","Strony podglądu nie są indeksowane"],["Finds","Znaleziska"],["Guide","Poradnik"],["Shipping","Wysyłka"],["SEO Articles","Artykuły SEO"],["Open full catalog ↗","Otwórz pełny katalog ↗"],["The cleaner way to browse ACBuy finds","Czytelniejszy sposób przeglądania znalezisk ACBuy"],["Find it. Check it. Shop smarter.","Znajdź. Sprawdź. Kupuj mądrzej."],["Search sneakers, hoodies, bags…","Szukaj butów, bluz, toreb…"],["Search catalog","Przeszukaj katalog"],["Freshly checked","Ostatnio sprawdzone"],["Popular finds, minus the guesswork.","Popularne znaleziska bez zgadywania."],["All","Wszystko"],["Shoes","Buty"],["Hoodies","Bluzy"],["Bags","Torby"],["Jerseys","Koszulki sportowe"],["Accessories","Akcesoria"],["Sort","Sortuj"],["Featured","Polecane"],["Price: low to high","Cena rosnąco"],["Price: high to low","Cena malejąco"],["Record checked","Wpis sprawdzony"],["Detail gallery","Galeria szczegółów"],["Listed price","Podana cena"],["View details ↗","Zobacz szczegóły ↗"],["Browse by category","Przeglądaj kategorie"],["Start broad. Get specific fast.","Zacznij szeroko. Szybko zawęź."],["Open category on main site","Otwórz kategorię w serwisie głównym"],["Built for better decisions","Stworzone do lepszych decyzji"],["QC first. Checkout second.","Najpierw QC. Potem płatność."],["Simple workflow","Prosty proces"],["From find to warehouse in four steps.","Od znaleziska do magazynu w czterech krokach."],["Ready to explore?","Gotowy do odkrywania?"],["Your next find is a search away.","Kolejne znalezisko dzieli jedna wyszukiwarka."],["Quick path","Szybka ścieżka"],["On this page","Na tej stronie"],["Continue shopping","Kontynuuj zakupy"],["Put the guide into practice.","Wykorzystaj poradnik w praktyce."],["Beginner guide","Poradnik dla początkujących"],["Warehouse inspection","Kontrola magazynowa"],["Parcel planning","Planowanie paczki"],["Straight answers","Konkretne odpowiedzi"],["Frequently asked questions, without the filler.","Najczęstsze pytania bez zbędnych treści."],
  ["How to use ACBuy finds without losing the plot.","Jak korzystać ze znalezisk ACBuy i się nie pogubić."],["Start with the product record","Zacznij od karty produktu"],["Submit the source link","Prześlij link źródłowy"],["Wait for warehouse inspection","Poczekaj na kontrolę magazynową"],["Store, combine, then submit","Przechowaj, połącz i wyślij"],["Five checks before you accept warehouse QC.","Pięć kontroli przed akceptacją QC."],["Shape and symmetry","Kształt i symetria"],["Color under warehouse lighting","Kolor w świetle magazynowym"],["Stitching, print, and hardware","Szwy, nadruk i okucia"],["Measurements and size","Wymiary i rozmiar"],["Visible defects and next action","Widoczne wady i kolejny krok"],["Plan the parcel before the parcel plans your budget.","Zaplanuj paczkę, zanim ona zaplanuje budżet."],["Actual versus volumetric weight","Waga rzeczywista i gabarytowa"],["Consolidation","Konsolidacja"],["Packaging choices","Wybór opakowania"],["Line restrictions and customs","Ograniczenia linii i cło"],["Is this an official ACBuy website?","Czy to oficjalna strona ACBuy?"],["Does a listing guarantee quality or availability?","Czy oferta gwarantuje jakość lub dostępność?"],["How many free QC photos are provided?","Ile bezpłatnych zdjęć QC otrzymam?"],["How long is free warehouse storage?","Jak długo magazynowanie jest bezpłatne?"],["Can this site calculate my final shipping price?","Czy ta strona obliczy końcowy koszt wysyłki?"]],
};

const nativeBody: Record<Exclude<Lang,"en"|"de">, Pairs> = {
  fr: [
    ["A focused product index with clear USD prices, QC counts, categories, and direct detail links—without spreadsheet clutter.","Un index produit clair avec prix en USD, informations QC, catégories et liens directs, sans le désordre d’une feuille de calcul."],
    ["Preview listings use public product records. Product photography is representative; verify the exact item details on the destination page.","Les fiches d’aperçu utilisent des données publiques. Les photos sont représentatives : vérifiez le produit exact sur la page de destination."],
    ["Inspect color, shape, stitching, labels, and obvious defects before international shipping.","Contrôlez la couleur, la forme, les coutures, les étiquettes et les défauts visibles avant l’expédition internationale."],
    ["Based on ACBuy’s current official shopping flow: paste a product link, order, inspect warehouse QC, store items, then submit an international parcel.","Selon le parcours officiel actuel d’ACBuy : collez un lien produit, commandez, contrôlez le QC en entrepôt, stockez les articles puis soumettez le colis international."],
    ["Independent product discovery and educational guide. Availability, prices, and shipping options can change; verify details on the destination page.","Guide indépendant de découverte et d’information. La disponibilité, les prix et les options d’expédition peuvent changer ; vérifiez-les sur la page de destination."],
    ["Independent educational guide. Verify current product, storage, and shipping details on the destination platform before ordering.","Guide pédagogique indépendant. Vérifiez les informations actuelles sur le produit, le stockage et l’expédition sur la plateforme avant de commander."],
    ["The useful part of a spreadsheet is not the spreadsheet—it is the path from a trustworthy product record to a parcel you are comfortable shipping. This guide keeps that path clear.","L’intérêt d’une feuille n’est pas la feuille elle-même, mais le parcours entre une fiche fiable et un colis que vous pouvez expédier sereinement. Ce guide clarifie ce parcours."],
    ["Search by a specific product name when possible. A focused query such as a model, garment type, or material is more useful than a broad brand-only search. Open the result and compare the displayed item name, listed price, variants, and source ID.","Recherchez si possible un produit précis. Une requête par modèle, type de vêtement ou matière est plus utile qu’une marque seule. Comparez le nom, le prix, les variantes et l’identifiant source."],
    ["Product photography on this preview is representative. The destination record is the source of truth for the exact listing, so inspect it before placing an order.","Les photos de l’aperçu sont représentatives. La fiche de destination reste la référence pour l’offre exacte ; contrôlez-la avant de commander."],
    ["ACBuy’s official shopping flow starts by pasting an item link. The platform retrieves the listing and presents the order form. Re-check the selected color, size, quantity, domestic delivery fee, and any seller note before paying.","Le parcours officiel commence par le collage du lien de l’article. La plateforme charge l’offre et le formulaire. Vérifiez couleur, taille, quantité, livraison nationale et notes du vendeur avant paiement."],
    ["Keep a record","Conserver une trace"],["Save the source item ID and selected variant. It makes warehouse checks and after-sales questions much easier.","Conservez l’identifiant source et la variante choisie. Les contrôles en entrepôt et les demandes après-vente seront plus simples."],
    ["Once the seller ships domestically, the item reaches the designated warehouse. ACBuy currently describes 3–5 free QC photos in its official shopping flow. Use those images to confirm that the physical item matches the order rather than approving it automatically.","Après l’envoi national, l’article arrive à l’entrepôt. ACBuy indique actuellement 3 à 5 photos QC gratuites. Utilisez-les pour confirmer que l’article reçu correspond à la commande."],
    ["If the photographs do not show a detail you need, check the platform’s current options for additional photography before making a decision.","Si un détail manque, consultez les options actuelles de photos supplémentaires avant de décider."],
    ["The current official guide states that the designated warehouse offers 90 days of free storage. This gives you time to wait for other purchases and combine items into one international parcel.","Le guide officiel actuel annonce 90 jours de stockage gratuit, ce qui permet d’attendre d’autres achats et de regrouper les articles."],
    ["Consolidation can reduce duplicated base charges, but a larger parcel is not always automatically cheaper. Compare the estimated weight, volumetric weight, restrictions, and available shipping lines before submitting.","Le regroupement peut réduire les frais de base répétés, mais un gros colis n’est pas toujours moins cher. Comparez poids estimé, poids volumétrique, restrictions et lignes disponibles."],
    ["QC photos are evidence, not decoration. Review them in a repeatable order so small details do not get lost in the excitement of a new arrival.","Les photos QC sont des preuves, pas une décoration. Examinez-les dans un ordre constant pour ne pas manquer les petits détails."],
    ["Begin with the whole item. Compare the left and right sides, overall proportions, panel alignment, toe shape, collar shape, bag structure, or garment drape. Large structural differences are easier to spot before zooming into fine details.","Commencez par l’article entier. Comparez les côtés, les proportions, l’alignement, la forme, la structure ou le tombé. Les écarts importants se voient mieux avant de zoomer."],
    ["Warehouse lighting can make neutral colors appear warmer or cooler. Compare several photos rather than judging a single frame. Ask whether the color difference appears consistently across the set and compare against the seller’s listing only as a reference.","L’éclairage de l’entrepôt peut réchauffer ou refroidir les couleurs. Comparez plusieurs photos et utilisez l’offre du vendeur uniquement comme référence."],
    ["Zoom in on seams, embroidery, printed graphics, zippers, buckles, and attachment points. Look for skipped stitches, loose threads, off-center graphics, rough edges, scratches, or mismatched hardware.","Zoomez sur les coutures, broderies, impressions, fermetures, boucles et points d’attache. Recherchez fils lâches, motifs décentrés, bords irréguliers, rayures ou pièces incohérentes."],
    ["Do not rely on logos alone","Ne vous fiez pas uniquement aux logos"],["Construction, materials, measurements, and visible defects usually tell you more about the received item.","La construction, les matières, les mesures et les défauts visibles renseignent davantage sur l’article reçu."],
    ["A size label does not confirm fit. Compare available measurements with a garment or shoe you already own. Where the default photo set does not show the required measurement, use the platform’s current photo or service options.","Une étiquette ne garantit pas la coupe. Comparez les mesures avec un article que vous possédez et utilisez les options photo de la plateforme si nécessaire."],
    ["Check every surface for stains, tears, dents, glue marks, scratches, broken parts, and missing accessories. If something is unclear, pause and gather better evidence before accepting, returning, or exchanging the item.","Vérifiez chaque surface : taches, déchirures, bosses, traces de colle, rayures, pièces cassées ou accessoires manquants. En cas de doute, demandez de meilleures preuves."],
    ["International shipping depends on the destination, line, weight, dimensions, restrictions, and packaging choices. A useful guide explains those variables instead of publishing a fake universal price.","L’expédition internationale dépend de la destination, de la ligne, du poids, des dimensions, des restrictions et de l’emballage. Un guide utile explique ces variables au lieu d’annoncer un faux prix universel."],
    ["Carriers may charge using actual weight or dimensional weight. Bulky but light products can therefore cost more than their scale weight suggests. Compare both the item weight and packed dimensions when the estimate provides them.","Les transporteurs peuvent facturer le poids réel ou volumétrique. Un article léger mais encombrant peut donc coûter plus cher. Comparez poids et dimensions emballées."],
    ["ACBuy’s official guide says combining more products for international shipping can help save shipping costs. Consolidation avoids repeating some base parcel costs, but the final parcel must still match the chosen line’s size, weight, and product restrictions.","Le guide officiel indique que regrouper plusieurs produits peut réduire les frais. Le colis final doit toutefois respecter les limites de taille, poids et produit de la ligne choisie."],
    ["Use the current shipping estimator after the warehouse records actual item data. Pre-purchase estimates are useful for planning, not a final invoice.","Utilisez l’estimateur actuel après l’enregistrement des données réelles en entrepôt. Une estimation avant achat sert à planifier, pas à établir la facture finale."],
    ["Removing unnecessary packaging can reduce volume, while reinforcement may protect fragile items at the cost of extra size and weight. Decide based on the product: soft clothing and rigid footwear do not need the same packing strategy.","Retirer l’emballage inutile réduit le volume ; renforcer protège les articles fragiles mais augmente taille et poids. Adaptez la stratégie au produit."],
    ["Available routes vary by destination and item type. Read the current line notes for restricted categories, tracking level, compensation terms, declared-value rules, and estimated transit time. Customs decisions are made by local authorities, so no external guide can guarantee clearance or delivery dates.","Les routes varient selon la destination et le produit. Lisez les restrictions, le suivi, l’indemnisation, la déclaration et le délai. Les autorités locales décident du dédouanement ; aucun guide externe ne peut le garantir."],
    ["These answers separate what this independent catalog does from what the purchasing platform does. Current platform terms always take priority.","Ces réponses distinguent le rôle du catalogue indépendant de celui de la plateforme. Les conditions actuelles de la plateforme priment toujours."],
    ["No. This is an independent product-discovery and educational guide. It organizes public product records and links visitors to the destination catalog. It does not process payments, store parcels, or sell the displayed goods.","Non. C’est un guide indépendant qui organise des fiches publiques et renvoie au catalogue de destination. Il ne traite aucun paiement, ne stocke aucun colis et ne vend aucun produit."],
    ["No. Seller stock, variants, price, and product condition can change. Open the destination record, verify the current listing, and inspect the warehouse QC photos before making a decision.","Non. Stock, variantes, prix et état peuvent changer. Ouvrez la fiche de destination, vérifiez l’offre et examinez les photos QC."],
    ["ACBuy’s current official shopping flow describes 3–5 free QC photos. The exact photo set and any optional services should be confirmed on the platform when the item reaches the warehouse.","Le parcours officiel actuel indique 3 à 5 photos QC gratuites. Confirmez le lot exact et les services optionnels sur la plateforme."],
    ["The current official ACBuy shopping guide states 90 days of free storage at its designated warehouse. Policies can change, so check the account or official guide before relying on a deadline.","Le guide officiel actuel indique 90 jours de stockage gratuit. Les règles peuvent changer : vérifiez le compte ou le guide avant de retenir une échéance."],
    ["No static external page can guarantee a final price. Chargeable weight, parcel dimensions, destination, selected route, packaging, restrictions, and current carrier pricing all affect the result. Use the platform’s live estimator with warehouse data.","Aucune page externe statique ne peut garantir un prix final. Poids facturable, dimensions, destination, route, emballage, restrictions et tarifs influencent le résultat. Utilisez l’estimateur en direct."],
  ],
  es: [
    ["A focused product index with clear USD prices, QC counts, categories, and direct detail links—without spreadsheet clutter.","Un índice claro con precios en USD, datos QC, categorías y enlaces directos, sin el desorden de una hoja de cálculo."],
    ["Preview listings use public product records. Product photography is representative; verify the exact item details on the destination page.","Las fichas de vista previa usan registros públicos. Las fotos son representativas; comprueba el artículo exacto en la página de destino."],
    ["Inspect color, shape, stitching, labels, and obvious defects before international shipping.","Revisa color, forma, costuras, etiquetas y defectos visibles antes del envío internacional."],
    ["Based on ACBuy’s current official shopping flow: paste a product link, order, inspect warehouse QC, store items, then submit an international parcel.","Según el proceso oficial actual de ACBuy: pega el enlace, compra, revisa el QC del almacén, guarda los artículos y presenta el paquete internacional."],
    ["Independent product discovery and educational guide. Availability, prices, and shipping options can change; verify details on the destination page.","Guía independiente de productos. La disponibilidad, los precios y las opciones de envío pueden cambiar; compruébalos en la página de destino."],
    ["Independent educational guide. Verify current product, storage, and shipping details on the destination platform before ordering.","Guía educativa independiente. Comprueba los datos actuales de producto, almacenamiento y envío en la plataforma antes de comprar."],
    ["The useful part of a spreadsheet is not the spreadsheet—it is the path from a trustworthy product record to a parcel you are comfortable shipping. This guide keeps that path clear.","Lo útil no es la hoja en sí, sino el camino desde una ficha fiable hasta un paquete que quieras enviar. Esta guía mantiene ese camino claro."],
    ["Search by a specific product name when possible. A focused query such as a model, garment type, or material is more useful than a broad brand-only search. Open the result and compare the displayed item name, listed price, variants, and source ID.","Busca un producto concreto siempre que sea posible. Una consulta por modelo, prenda o material es más útil que una marca genérica. Compara nombre, precio, variantes e ID de origen."],
    ["Product photography on this preview is representative. The destination record is the source of truth for the exact listing, so inspect it before placing an order.","Las fotos de esta vista previa son representativas. La ficha de destino es la referencia exacta; revísala antes de comprar."],
    ["ACBuy’s official shopping flow starts by pasting an item link. The platform retrieves the listing and presents the order form. Re-check the selected color, size, quantity, domestic delivery fee, and any seller note before paying.","El proceso oficial empieza pegando el enlace del artículo. La plataforma carga la oferta y el formulario. Revisa color, talla, cantidad, envío nacional y notas antes de pagar."],
    ["Keep a record","Guarda un registro"],["Save the source item ID and selected variant. It makes warehouse checks and after-sales questions much easier.","Guarda el ID de origen y la variante elegida. Facilita las revisiones de almacén y las consultas posventa."],
    ["Once the seller ships domestically, the item reaches the designated warehouse. ACBuy currently describes 3–5 free QC photos in its official shopping flow. Use those images to confirm that the physical item matches the order rather than approving it automatically.","Tras el envío nacional, el artículo llega al almacén. ACBuy indica actualmente 3–5 fotos QC gratuitas. Úsalas para confirmar que el artículo recibido coincide con el pedido."],
    ["If the photographs do not show a detail you need, check the platform’s current options for additional photography before making a decision.","Si falta un detalle, consulta las opciones actuales de fotos adicionales antes de decidir."],
    ["The current official guide states that the designated warehouse offers 90 days of free storage. This gives you time to wait for other purchases and combine items into one international parcel.","La guía oficial actual indica 90 días de almacenamiento gratuito, lo que permite esperar otras compras y agruparlas."],
    ["Consolidation can reduce duplicated base charges, but a larger parcel is not always automatically cheaper. Compare the estimated weight, volumetric weight, restrictions, and available shipping lines before submitting.","La consolidación puede reducir cargos base repetidos, pero un paquete mayor no siempre es más barato. Compara peso estimado, peso volumétrico, restricciones y líneas."],
    ["QC photos are evidence, not decoration. Review them in a repeatable order so small details do not get lost in the excitement of a new arrival.","Las fotos QC son pruebas, no decoración. Revísalas siempre en el mismo orden para no perder detalles."],
    ["Begin with the whole item. Compare the left and right sides, overall proportions, panel alignment, toe shape, collar shape, bag structure, or garment drape. Large structural differences are easier to spot before zooming into fine details.","Empieza por el artículo completo. Compara lados, proporciones, alineación, forma, estructura y caída. Las diferencias grandes se detectan mejor antes de ampliar."],
    ["Warehouse lighting can make neutral colors appear warmer or cooler. Compare several photos rather than judging a single frame. Ask whether the color difference appears consistently across the set and compare against the seller’s listing only as a reference.","La luz del almacén puede alterar los tonos. Compara varias fotos y usa la oferta del vendedor solo como referencia."],
    ["Zoom in on seams, embroidery, printed graphics, zippers, buckles, and attachment points. Look for skipped stitches, loose threads, off-center graphics, rough edges, scratches, or mismatched hardware.","Amplía costuras, bordados, estampados, cremalleras, hebillas y uniones. Busca puntadas fallidas, hilos sueltos, gráficos descentrados, bordes ásperos, arañazos o herrajes distintos."],
    ["Do not rely on logos alone","No te fijes solo en los logotipos"],["Construction, materials, measurements, and visible defects usually tell you more about the received item.","La construcción, los materiales, las medidas y los defectos visibles dicen más sobre el artículo recibido."],
    ["A size label does not confirm fit. Compare available measurements with a garment or shoe you already own. Where the default photo set does not show the required measurement, use the platform’s current photo or service options.","La etiqueta no confirma el ajuste. Compara las medidas con una prenda o zapato propio y usa las opciones de fotos de la plataforma cuando falten datos."],
    ["Check every surface for stains, tears, dents, glue marks, scratches, broken parts, and missing accessories. If something is unclear, pause and gather better evidence before accepting, returning, or exchanging the item.","Revisa manchas, roturas, golpes, pegamento, arañazos, piezas dañadas y accesorios ausentes. Si algo no está claro, pide mejores pruebas antes de aceptar o devolver."],
    ["International shipping depends on the destination, line, weight, dimensions, restrictions, and packaging choices. A useful guide explains those variables instead of publishing a fake universal price.","El envío internacional depende del destino, línea, peso, medidas, restricciones y embalaje. Una guía útil explica estas variables en vez de publicar un precio universal falso."],
    ["Carriers may charge using actual weight or dimensional weight. Bulky but light products can therefore cost more than their scale weight suggests. Compare both the item weight and packed dimensions when the estimate provides them.","El transportista puede cobrar por peso real o volumétrico. Un artículo ligero pero grande puede costar más. Compara peso y dimensiones embaladas."],
    ["ACBuy’s official guide says combining more products for international shipping can help save shipping costs. Consolidation avoids repeating some base parcel costs, but the final parcel must still match the chosen line’s size, weight, and product restrictions.","La guía oficial dice que agrupar productos puede ahorrar envío. El paquete debe seguir cumpliendo los límites de tamaño, peso y producto de la línea."],
    ["Use the current shipping estimator after the warehouse records actual item data. Pre-purchase estimates are useful for planning, not a final invoice.","Usa el estimador actual después de que el almacén registre los datos reales. Las estimaciones previas sirven para planificar, no son la factura final."],
    ["Removing unnecessary packaging can reduce volume, while reinforcement may protect fragile items at the cost of extra size and weight. Decide based on the product: soft clothing and rigid footwear do not need the same packing strategy.","Quitar embalaje innecesario reduce volumen; reforzar protege artículos frágiles pero aumenta tamaño y peso. Decide según el producto."],
    ["Available routes vary by destination and item type. Read the current line notes for restricted categories, tracking level, compensation terms, declared-value rules, and estimated transit time. Customs decisions are made by local authorities, so no external guide can guarantee clearance or delivery dates.","Las rutas varían por destino y producto. Lee restricciones, seguimiento, compensación, declaración y plazo. La aduana depende de autoridades locales; ninguna guía externa puede garantizarla."],
    ["These answers separate what this independent catalog does from what the purchasing platform does. Current platform terms always take priority.","Estas respuestas separan la función del catálogo independiente de la plataforma de compra. Las condiciones actuales de la plataforma tienen prioridad."],
    ["No. This is an independent product-discovery and educational guide. It organizes public product records and links visitors to the destination catalog. It does not process payments, store parcels, or sell the displayed goods.","No. Es una guía independiente que organiza registros públicos y enlaza al catálogo de destino. No procesa pagos, almacena paquetes ni vende productos."],
    ["No. Seller stock, variants, price, and product condition can change. Open the destination record, verify the current listing, and inspect the warehouse QC photos before making a decision.","No. El stock, las variantes, el precio y el estado pueden cambiar. Abre la ficha de destino, verifica la oferta y revisa las fotos QC."],
    ["ACBuy’s current official shopping flow describes 3–5 free QC photos. The exact photo set and any optional services should be confirmed on the platform when the item reaches the warehouse.","El proceso oficial actual describe 3–5 fotos QC gratuitas. Confirma el conjunto exacto y los servicios opcionales en la plataforma."],
    ["The current official ACBuy shopping guide states 90 days of free storage at its designated warehouse. Policies can change, so check the account or official guide before relying on a deadline.","La guía oficial actual indica 90 días de almacenamiento gratuito. Las políticas pueden cambiar; comprueba la cuenta o la guía antes de confiar en un plazo."],
    ["No static external page can guarantee a final price. Chargeable weight, parcel dimensions, destination, selected route, packaging, restrictions, and current carrier pricing all affect the result. Use the platform’s live estimator with warehouse data.","Ninguna página externa puede garantizar el precio final. Peso facturable, dimensiones, destino, ruta, embalaje, restricciones y tarifas influyen. Usa el estimador en vivo con datos del almacén."],
  ], it: [
    ["A focused product index with clear USD prices, QC counts, categories, and direct detail links—without spreadsheet clutter.","Un indice chiaro con prezzi in USD, dati QC, categorie e link diretti, senza il caos di un foglio di calcolo."],
    ["Preview listings use public product records. Product photography is representative; verify the exact item details on the destination page.","Le schede di anteprima usano dati pubblici. Le foto sono rappresentative: verifica l’articolo esatto nella pagina di destinazione."],
    ["Inspect color, shape, stitching, labels, and obvious defects before international shipping.","Controlla colore, forma, cuciture, etichette e difetti visibili prima della spedizione internazionale."],
    ["Based on ACBuy’s current official shopping flow: paste a product link, order, inspect warehouse QC, store items, then submit an international parcel.","In base al flusso ufficiale attuale di ACBuy: incolla il link, ordina, controlla il QC in magazzino, conserva gli articoli e invia il pacco internazionale."],
    ["Independent product discovery and educational guide. Availability, prices, and shipping options can change; verify details on the destination page.","Guida indipendente ai prodotti. Disponibilità, prezzi e opzioni di spedizione possono cambiare; verifica i dettagli sulla pagina di destinazione."],
    ["Independent educational guide. Verify current product, storage, and shipping details on the destination platform before ordering.","Guida educativa indipendente. Prima di ordinare, verifica sulla piattaforma i dati attuali di prodotto, deposito e spedizione."],
    ["The useful part of a spreadsheet is not the spreadsheet—it is the path from a trustworthy product record to a parcel you are comfortable shipping. This guide keeps that path clear.","La parte utile non è il foglio, ma il percorso da una scheda affidabile a un pacco che vuoi spedire. Questa guida rende chiaro il percorso."],
    ["Search by a specific product name when possible. A focused query such as a model, garment type, or material is more useful than a broad brand-only search. Open the result and compare the displayed item name, listed price, variants, and source ID.","Cerca un prodotto preciso quando possibile. Modello, tipo di capo o materiale sono più utili di una ricerca generica per marchio. Confronta nome, prezzo, varianti e ID sorgente."],
    ["Product photography on this preview is representative. The destination record is the source of truth for the exact listing, so inspect it before placing an order.","Le foto dell’anteprima sono rappresentative. La scheda di destinazione è la fonte corretta per l’offerta esatta: controllala prima dell’ordine."],
    ["ACBuy’s official shopping flow starts by pasting an item link. The platform retrieves the listing and presents the order form. Re-check the selected color, size, quantity, domestic delivery fee, and any seller note before paying.","Il flusso ufficiale inizia incollando il link dell’articolo. La piattaforma carica l’offerta e il modulo. Ricontrolla colore, taglia, quantità, spedizione nazionale e note prima di pagare."],
    ["Keep a record","Conserva i dati"],["Save the source item ID and selected variant. It makes warehouse checks and after-sales questions much easier.","Salva l’ID sorgente e la variante scelta. Facilita i controlli in magazzino e le richieste post-vendita."],
    ["Once the seller ships domestically, the item reaches the designated warehouse. ACBuy currently describes 3–5 free QC photos in its official shopping flow. Use those images to confirm that the physical item matches the order rather than approving it automatically.","Dopo la spedizione nazionale, l’articolo arriva in magazzino. ACBuy indica 3–5 foto QC gratuite. Usale per confermare che l’articolo ricevuto corrisponda all’ordine."],
    ["If the photographs do not show a detail you need, check the platform’s current options for additional photography before making a decision.","Se manca un dettaglio, controlla le opzioni attuali per foto aggiuntive prima di decidere."],
    ["The current official guide states that the designated warehouse offers 90 days of free storage. This gives you time to wait for other purchases and combine items into one international parcel.","La guida ufficiale attuale indica 90 giorni di deposito gratuito, utili per attendere altri acquisti e raggrupparli."],
    ["Consolidation can reduce duplicated base charges, but a larger parcel is not always automatically cheaper. Compare the estimated weight, volumetric weight, restrictions, and available shipping lines before submitting.","Il consolidamento può ridurre i costi base ripetuti, ma un pacco grande non è sempre più economico. Confronta peso stimato, volumetrico, restrizioni e linee."],
    ["QC photos are evidence, not decoration. Review them in a repeatable order so small details do not get lost in the excitement of a new arrival.","Le foto QC sono prove, non decorazione. Esaminale sempre nello stesso ordine per non perdere piccoli dettagli."],
    ["Begin with the whole item. Compare the left and right sides, overall proportions, panel alignment, toe shape, collar shape, bag structure, or garment drape. Large structural differences are easier to spot before zooming into fine details.","Inizia dall’articolo intero. Confronta lati, proporzioni, allineamento, forma, struttura e vestibilità. Le differenze grandi si vedono meglio prima di ingrandire."],
    ["Warehouse lighting can make neutral colors appear warmer or cooler. Compare several photos rather than judging a single frame. Ask whether the color difference appears consistently across the set and compare against the seller’s listing only as a reference.","La luce del magazzino può alterare i colori. Confronta più foto e usa l’offerta del venditore solo come riferimento."],
    ["Zoom in on seams, embroidery, printed graphics, zippers, buckles, and attachment points. Look for skipped stitches, loose threads, off-center graphics, rough edges, scratches, or mismatched hardware.","Ingrandisci cuciture, ricami, stampe, zip, fibbie e attacchi. Cerca punti mancanti, fili liberi, grafiche decentrate, bordi ruvidi, graffi o accessori diversi."],
    ["Do not rely on logos alone","Non affidarti solo ai loghi"],["Construction, materials, measurements, and visible defects usually tell you more about the received item.","Costruzione, materiali, misure e difetti visibili dicono di più sull’articolo ricevuto."],
    ["A size label does not confirm fit. Compare available measurements with a garment or shoe you already own. Where the default photo set does not show the required measurement, use the platform’s current photo or service options.","L’etichetta non conferma la vestibilità. Confronta le misure con un capo o una scarpa che possiedi e usa le opzioni foto della piattaforma quando serve."],
    ["Check every surface for stains, tears, dents, glue marks, scratches, broken parts, and missing accessories. If something is unclear, pause and gather better evidence before accepting, returning, or exchanging the item.","Controlla macchie, strappi, ammaccature, colla, graffi, parti rotte e accessori mancanti. Se qualcosa non è chiaro, chiedi prove migliori prima di accettare o restituire."],
    ["International shipping depends on the destination, line, weight, dimensions, restrictions, and packaging choices. A useful guide explains those variables instead of publishing a fake universal price.","La spedizione internazionale dipende da destinazione, linea, peso, dimensioni, restrizioni e imballaggio. Una guida utile spiega queste variabili invece di pubblicare un falso prezzo universale."],
    ["Carriers may charge using actual weight or dimensional weight. Bulky but light products can therefore cost more than their scale weight suggests. Compare both the item weight and packed dimensions when the estimate provides them.","I vettori possono usare il peso reale o volumetrico. Un articolo leggero ma ingombrante può costare di più. Confronta peso e dimensioni imballate."],
    ["ACBuy’s official guide says combining more products for international shipping can help save shipping costs. Consolidation avoids repeating some base parcel costs, but the final parcel must still match the chosen line’s size, weight, and product restrictions.","La guida ufficiale dice che raggruppare più prodotti può ridurre i costi. Il pacco deve comunque rispettare limiti di dimensione, peso e prodotto della linea."],
    ["Use the current shipping estimator after the warehouse records actual item data. Pre-purchase estimates are useful for planning, not a final invoice.","Usa il calcolatore attuale dopo che il magazzino registra i dati reali. Le stime prima dell’acquisto servono a pianificare, non sono la fattura finale."],
    ["Removing unnecessary packaging can reduce volume, while reinforcement may protect fragile items at the cost of extra size and weight. Decide based on the product: soft clothing and rigid footwear do not need the same packing strategy.","Rimuovere imballaggi inutili riduce il volume; il rinforzo protegge ma aumenta dimensioni e peso. Scegli in base al prodotto."],
    ["Available routes vary by destination and item type. Read the current line notes for restricted categories, tracking level, compensation terms, declared-value rules, and estimated transit time. Customs decisions are made by local authorities, so no external guide can guarantee clearance or delivery dates.","Le rotte variano per destinazione e prodotto. Leggi restrizioni, tracking, compensazione, dichiarazione e tempi. Le decisioni doganali spettano alle autorità locali; nessuna guida può garantirle."],
    ["These answers separate what this independent catalog does from what the purchasing platform does. Current platform terms always take priority.","Queste risposte separano il ruolo del catalogo indipendente da quello della piattaforma. Le condizioni attuali della piattaforma hanno sempre priorità."],
    ["No. This is an independent product-discovery and educational guide. It organizes public product records and links visitors to the destination catalog. It does not process payments, store parcels, or sell the displayed goods.","No. È una guida indipendente che organizza schede pubbliche e collega al catalogo di destinazione. Non gestisce pagamenti, non conserva pacchi e non vende prodotti."],
    ["No. Seller stock, variants, price, and product condition can change. Open the destination record, verify the current listing, and inspect the warehouse QC photos before making a decision.","No. Scorte, varianti, prezzo e condizioni possono cambiare. Apri la scheda di destinazione, verifica l’offerta e controlla le foto QC."],
    ["ACBuy’s current official shopping flow describes 3–5 free QC photos. The exact photo set and any optional services should be confirmed on the platform when the item reaches the warehouse.","Il flusso ufficiale attuale indica 3–5 foto QC gratuite. Conferma sulla piattaforma il set esatto e i servizi opzionali."],
    ["The current official ACBuy shopping guide states 90 days of free storage at its designated warehouse. Policies can change, so check the account or official guide before relying on a deadline.","La guida ufficiale attuale indica 90 giorni di deposito gratuito. Le regole possono cambiare: controlla l’account o la guida prima di affidarti a una scadenza."],
    ["No static external page can guarantee a final price. Chargeable weight, parcel dimensions, destination, selected route, packaging, restrictions, and current carrier pricing all affect the result. Use the platform’s live estimator with warehouse data.","Nessuna pagina esterna può garantire il prezzo finale. Peso fatturabile, dimensioni, destinazione, rotta, imballaggio, restrizioni e tariffe incidono. Usa il calcolatore live con i dati del magazzino."],
  ], pl: [],
};

const pageExtras: Record<Exclude<Lang,"en">, Pairs> = {
  de: [
    ["Find it.","Finden."],["Check it.","Prüfen."],["Shop smarter.","Smarter einkaufen."],["QC first.","Erst QC."],["Checkout second.","Dann Checkout."],
    ["SEO articles","SEO-Artikel"],["Useful ACBuy research, written for real shopping decisions.","Nützliche ACBuy-Recherchen für echte Kaufentscheidungen."],["This article hub targets the questions people search before ordering. Every topic is separated by intent, grounded in current platform information, and linked to a practical next step.","Dieser Artikelbereich beantwortet Fragen, die Nutzer vor einer Bestellung suchen. Jedes Thema folgt einer klaren Absicht, basiert auf aktuellen Plattformangaben und führt zu einem praktischen nächsten Schritt."],
    ["Product discovery","Produktsuche"],["How to use an ACBuy spreadsheet efficiently","So nutzt du eine ACBuy-Produkttabelle effizient"],["A useful product index should shorten the path from a search term to a verifiable source record. Start with a specific product type, model, material, or use case; then compare the listed price, source ID, available variants, and destination record before ordering.","Ein guter Produktindex verkürzt den Weg vom Suchbegriff zu einem überprüfbaren Quelleintrag. Beginne mit Produkttyp, Modell, Material oder Einsatzzweck und vergleiche vor der Bestellung Preis, Quell-ID, Varianten und Zieleintrag."],["Category pages help broad discovery, while individual product pages answer narrower searches. Neither replaces warehouse inspection: the seller listing describes what is offered, while QC photos show what actually arrived.","Kategorieseiten helfen bei der breiten Suche, Produktseiten bei konkreten Fragen. Beides ersetzt nicht die Lagerprüfung: Das Verkäuferangebot beschreibt die Ware, QC-Fotos zeigen, was tatsächlich angekommen ist."],["Read the complete beginner guide ↗","Vollständigen Einsteigerleitfaden lesen ↗"],
    ["Quality control","Qualitätskontrolle"],["What ACBuy QC photos can—and cannot—prove","Was ACBuy-QC-Fotos belegen können – und was nicht"],["Warehouse photographs can reveal shape, color consistency, stitching, measurements, visible damage, and included accessories. They cannot guarantee material composition, long-term durability, fit, or customs outcomes.","Lagerfotos können Form, Farbkonsistenz, Nähte, Maße, sichtbare Schäden und Zubehör zeigen. Materialzusammensetzung, Haltbarkeit, Passform oder Zollausgang können sie nicht garantieren."],["Review every photo in the same order and request clearer evidence when an important detail is missing. A repeatable checklist is more reliable than judging an item from one flattering angle.","Prüfe jedes Foto in derselben Reihenfolge und fordere klarere Nachweise an, wenn ein wichtiges Detail fehlt. Eine feste Checkliste ist zuverlässiger als ein schmeichelhafter Blickwinkel."],["Open the five-point QC guide ↗","Fünf-Punkte-QC-Leitfaden öffnen ↗"],
    ["Parcel planning without fake universal prices","Paketplanung ohne erfundene Einheitspreise"],["International shipping cost depends on destination, available line, actual or volumetric weight, packaging, product restrictions, and current carrier pricing. That is why a fixed external price table quickly becomes misleading.","Internationale Versandkosten hängen von Ziel, Linie, tatsächlichem oder volumetrischem Gewicht, Verpackung, Beschränkungen und aktuellen Tarifen ab. Eine feste externe Preistabelle wird deshalb schnell irreführend."],["Use estimates for planning, then recalculate after the warehouse records the real item data. Consolidation may reduce repeated base charges, but a larger parcel is not automatically the cheapest or most suitable option.","Nutze Schätzungen zur Planung und rechne neu, sobald das Lager die echten Artikeldaten erfasst. Bündelung kann Grundkosten senken, doch ein größeres Paket ist nicht automatisch am günstigsten oder geeignetsten."],["Read the parcel planning guide ↗","Leitfaden zur Paketplanung lesen ↗"],
    ["Research standard","Recherche-Standard"],["How this independent guide verifies information","So überprüft dieser unabhängige Leitfaden Informationen"],["Platform facts are checked against ACBuy’s current official pages before publication. Product names, prices, and source links are checked against public destination records. Claims that cannot be verified—such as guaranteed delivery times, customs clearance, or universal quality—are not presented as facts.","Plattformangaben werden vor der Veröffentlichung mit den aktuellen offiziellen ACBuy-Seiten abgeglichen. Produktnamen, Preise und Quellenlinks werden anhand öffentlicher Zieleinträge geprüft. Nicht überprüfbare Aussagen wie garantierte Lieferzeiten, Zollabfertigung oder allgemeine Qualität werden nicht als Fakten dargestellt."],["Because prices, stock, routes, and policies can change, every guide tells readers which details must be confirmed again on the destination platform.","Da Preise, Bestand, Routen und Regeln wechseln können, nennt jeder Leitfaden die Details, die auf der Zielplattform erneut geprüft werden müssen."],["Browse current product records ↗","Aktuelle Produkteinträge ansehen ↗"],
  ],
  fr: [
    ["Find it.","Trouvez."],["Check it.","Vérifiez."],["Shop smarter.","Achetez mieux."],["QC first.","Le QC d’abord."],["Checkout second.","Le paiement ensuite."],
    ["SEO articles","Articles SEO"],["Useful ACBuy research, written for real shopping decisions.","Des recherches ACBuy utiles pour de vraies décisions d’achat."],["This article hub targets the questions people search before ordering. Every topic is separated by intent, grounded in current platform information, and linked to a practical next step.","Ce centre d’articles répond aux questions posées avant une commande. Chaque sujet correspond à une intention précise, s’appuie sur les informations actuelles de la plateforme et mène à une prochaine étape concrète."],
    ["Product discovery","Découverte de produits"],["How to use an ACBuy spreadsheet efficiently","Comment utiliser efficacement une feuille ACBuy"],["A useful product index should shorten the path from a search term to a verifiable source record. Start with a specific product type, model, material, or use case; then compare the listed price, source ID, available variants, and destination record before ordering.","Un index utile doit raccourcir le chemin entre une recherche et une fiche source vérifiable. Commencez par un type, un modèle, une matière ou un usage précis, puis comparez prix, identifiant source, variantes et fiche de destination."],["Category pages help broad discovery, while individual product pages answer narrower searches. Neither replaces warehouse inspection: the seller listing describes what is offered, while QC photos show what actually arrived.","Les catégories facilitent l’exploration générale et les fiches produit répondent aux recherches précises. Aucune ne remplace le contrôle en entrepôt : l’annonce décrit l’offre, les photos QC montrent l’article reçu."],["Read the complete beginner guide ↗","Lire le guide débutant complet ↗"],
    ["Quality control","Contrôle qualité"],["What ACBuy QC photos can—and cannot—prove","Ce que les photos QC ACBuy peuvent — ou non — prouver"],["Warehouse photographs can reveal shape, color consistency, stitching, measurements, visible damage, and included accessories. They cannot guarantee material composition, long-term durability, fit, or customs outcomes.","Les photos d’entrepôt peuvent montrer forme, couleur, coutures, mesures, dommages visibles et accessoires. Elles ne garantissent ni composition, ni durabilité, ni coupe, ni résultat douanier."],["Review every photo in the same order and request clearer evidence when an important detail is missing. A repeatable checklist is more reliable than judging an item from one flattering angle.","Examinez chaque photo dans le même ordre et demandez une preuve plus claire si un détail manque. Une liste de contrôle répétable est plus fiable qu’un seul angle avantageux."],["Open the five-point QC guide ↗","Ouvrir le guide QC en cinq points ↗"],
    ["Parcel planning without fake universal prices","Planifier un colis sans faux prix universel"],["International shipping cost depends on destination, available line, actual or volumetric weight, packaging, product restrictions, and current carrier pricing. That is why a fixed external price table quickly becomes misleading.","Le coût international dépend de la destination, de la ligne, du poids réel ou volumétrique, de l’emballage, des restrictions et des tarifs actuels. Un tableau de prix fixe devient donc vite trompeur."],["Use estimates for planning, then recalculate after the warehouse records the real item data. Consolidation may reduce repeated base charges, but a larger parcel is not automatically the cheapest or most suitable option.","Utilisez les estimations pour planifier puis recalculez après l’enregistrement des données réelles. Le regroupement peut réduire certains frais, mais un colis plus gros n’est pas toujours le moins cher ni le mieux adapté."],["Read the parcel planning guide ↗","Lire le guide de planification du colis ↗"],
    ["Research standard","Méthode de recherche"],["How this independent guide verifies information","Comment ce guide indépendant vérifie les informations"],["Platform facts are checked against ACBuy’s current official pages before publication. Product names, prices, and source links are checked against public destination records. Claims that cannot be verified—such as guaranteed delivery times, customs clearance, or universal quality—are not presented as facts.","Avant publication, les informations de plateforme sont comparées aux pages officielles actuelles d’ACBuy. Noms, prix et liens sources sont contrôlés sur les fiches publiques. Les promesses invérifiables ne sont pas présentées comme des faits."],["Because prices, stock, routes, and policies can change, every guide tells readers which details must be confirmed again on the destination platform.","Comme les prix, stocks, lignes et règles peuvent changer, chaque guide indique les détails à confirmer sur la plateforme de destination."],["Browse current product records ↗","Parcourir les fiches produit actuelles ↗"],
  ],
  es: [
    ["Find it.","Encuéntralo."],["Check it.","Revísalo."],["Shop smarter.","Compra mejor."],["QC first.","Primero QC."],["Checkout second.","Después el pago."],
    ["SEO articles","Artículos SEO"],["Useful ACBuy research, written for real shopping decisions.","Investigación útil sobre ACBuy para decisiones de compra reales."],["This article hub targets the questions people search before ordering. Every topic is separated by intent, grounded in current platform information, and linked to a practical next step.","Este centro responde a lo que la gente busca antes de pedir. Cada tema tiene una intención clara, usa información actual de la plataforma y enlaza con un siguiente paso práctico."],
    ["Product discovery","Descubrimiento de productos"],["How to use an ACBuy spreadsheet efficiently","Cómo usar una hoja de ACBuy con eficiencia"],["A useful product index should shorten the path from a search term to a verifiable source record. Start with a specific product type, model, material, or use case; then compare the listed price, source ID, available variants, and destination record before ordering.","Un índice útil acorta el camino entre una búsqueda y una ficha verificable. Empieza por un tipo, modelo, material o uso concreto; luego compara precio, ID de origen, variantes y ficha de destino."],["Category pages help broad discovery, while individual product pages answer narrower searches. Neither replaces warehouse inspection: the seller listing describes what is offered, while QC photos show what actually arrived.","Las categorías ayudan a explorar y las fichas responden búsquedas concretas. Ninguna sustituye la inspección: el anuncio describe la oferta y las fotos QC muestran lo recibido."],["Read the complete beginner guide ↗","Leer la guía completa para principiantes ↗"],
    ["Quality control","Control de calidad"],["What ACBuy QC photos can—and cannot—prove","Lo que las fotos QC de ACBuy pueden —y no pueden— demostrar"],["Warehouse photographs can reveal shape, color consistency, stitching, measurements, visible damage, and included accessories. They cannot guarantee material composition, long-term durability, fit, or customs outcomes.","Las fotos pueden mostrar forma, color, costuras, medidas, daños visibles y accesorios. No garantizan composición, durabilidad, ajuste ni resultados aduaneros."],["Review every photo in the same order and request clearer evidence when an important detail is missing. A repeatable checklist is more reliable than judging an item from one flattering angle.","Revisa todas las fotos en el mismo orden y pide pruebas más claras si falta un detalle. Una lista repetible es más fiable que un único ángulo favorecedor."],["Open the five-point QC guide ↗","Abrir la guía QC de cinco puntos ↗"],
    ["Parcel planning without fake universal prices","Planificar paquetes sin precios universales falsos"],["International shipping cost depends on destination, available line, actual or volumetric weight, packaging, product restrictions, and current carrier pricing. That is why a fixed external price table quickly becomes misleading.","El envío depende del destino, línea, peso real o volumétrico, embalaje, restricciones y tarifas actuales. Por eso una tabla externa fija queda obsoleta y resulta engañosa."],["Use estimates for planning, then recalculate after the warehouse records the real item data. Consolidation may reduce repeated base charges, but a larger parcel is not automatically the cheapest or most suitable option.","Usa estimaciones para planificar y recalcula con los datos reales del almacén. Consolidar puede reducir cargos base, pero un paquete mayor no siempre es la opción más barata o adecuada."],["Read the parcel planning guide ↗","Leer la guía de planificación del paquete ↗"],
    ["Research standard","Estándar de investigación"],["How this independent guide verifies information","Cómo verifica la información esta guía independiente"],["Platform facts are checked against ACBuy’s current official pages before publication. Product names, prices, and source links are checked against public destination records. Claims that cannot be verified—such as guaranteed delivery times, customs clearance, or universal quality—are not presented as facts.","Antes de publicar, comprobamos la información con las páginas oficiales actuales de ACBuy. Nombres, precios y enlaces se verifican con fichas públicas. Las afirmaciones no verificables no se presentan como hechos."],["Because prices, stock, routes, and policies can change, every guide tells readers which details must be confirmed again on the destination platform.","Como precios, stock, rutas y políticas pueden cambiar, cada guía indica qué datos deben confirmarse de nuevo en la plataforma."],["Browse current product records ↗","Explorar fichas de producto actuales ↗"],
  ],
  it: [
    ["Find it.","Trova."],["Check it.","Controlla."],["Shop smarter.","Acquista meglio."],["QC first.","Prima il QC."],["Checkout second.","Poi il pagamento."],
    ["SEO articles","Articoli SEO"],["Useful ACBuy research, written for real shopping decisions.","Ricerche utili su ACBuy per vere decisioni d’acquisto."],["This article hub targets the questions people search before ordering. Every topic is separated by intent, grounded in current platform information, and linked to a practical next step.","Questa raccolta risponde alle domande cercate prima di ordinare. Ogni argomento ha un intento chiaro, usa informazioni attuali della piattaforma e porta a un passo pratico."],
    ["Product discovery","Scoperta dei prodotti"],["How to use an ACBuy spreadsheet efficiently","Come usare in modo efficiente un foglio ACBuy"],["A useful product index should shorten the path from a search term to a verifiable source record. Start with a specific product type, model, material, or use case; then compare the listed price, source ID, available variants, and destination record before ordering.","Un indice utile accorcia il percorso dalla ricerca a una scheda verificabile. Parti da tipo, modello, materiale o uso specifico, poi confronta prezzo, ID sorgente, varianti e scheda di destinazione."],["Category pages help broad discovery, while individual product pages answer narrower searches. Neither replaces warehouse inspection: the seller listing describes what is offered, while QC photos show what actually arrived.","Le categorie aiutano l’esplorazione generale e le schede rispondono a ricerche precise. Nessuna sostituisce il controllo in magazzino: l’offerta descrive il prodotto, le foto QC mostrano ciò che è arrivato."],["Read the complete beginner guide ↗","Leggi la guida completa per principianti ↗"],
    ["Quality control","Controllo qualità"],["What ACBuy QC photos can—and cannot—prove","Cosa possono — e non possono — provare le foto QC ACBuy"],["Warehouse photographs can reveal shape, color consistency, stitching, measurements, visible damage, and included accessories. They cannot guarantee material composition, long-term durability, fit, or customs outcomes.","Le foto possono mostrare forma, uniformità del colore, cuciture, misure, danni e accessori. Non garantiscono composizione, durata, vestibilità o esito doganale."],["Review every photo in the same order and request clearer evidence when an important detail is missing. A repeatable checklist is more reliable than judging an item from one flattering angle.","Esamina le foto sempre nello stesso ordine e chiedi prove più chiare se manca un dettaglio. Una lista ripetibile è più affidabile di una sola angolazione favorevole."],["Open the five-point QC guide ↗","Apri la guida QC in cinque punti ↗"],
    ["Parcel planning without fake universal prices","Pianificare il pacco senza falsi prezzi universali"],["International shipping cost depends on destination, available line, actual or volumetric weight, packaging, product restrictions, and current carrier pricing. That is why a fixed external price table quickly becomes misleading.","Il costo internazionale dipende da destinazione, linea, peso reale o volumetrico, imballaggio, restrizioni e tariffe attuali. Una tabella esterna fissa diventa quindi presto fuorviante."],["Use estimates for planning, then recalculate after the warehouse records the real item data. Consolidation may reduce repeated base charges, but a larger parcel is not automatically the cheapest or most suitable option.","Usa le stime per pianificare e ricalcola con i dati reali del magazzino. Il consolidamento può ridurre i costi base, ma un pacco più grande non è sempre il più economico o adatto."],["Read the parcel planning guide ↗","Leggi la guida alla pianificazione del pacco ↗"],
    ["Research standard","Standard di ricerca"],["How this independent guide verifies information","Come questa guida indipendente verifica le informazioni"],["Platform facts are checked against ACBuy’s current official pages before publication. Product names, prices, and source links are checked against public destination records. Claims that cannot be verified—such as guaranteed delivery times, customs clearance, or universal quality—are not presented as facts.","Prima della pubblicazione, le informazioni vengono confrontate con le pagine ufficiali attuali di ACBuy. Nomi, prezzi e link sono verificati sulle schede pubbliche. Le affermazioni non verificabili non sono presentate come fatti."],["Because prices, stock, routes, and policies can change, every guide tells readers which details must be confirmed again on the destination platform.","Poiché prezzi, scorte, rotte e regole possono cambiare, ogni guida indica quali dettagli verificare di nuovo sulla piattaforma."],["Browse current product records ↗","Sfoglia le schede prodotto attuali ↗"],
  ],
  pl: [
    ["Find it.","Znajdź."],["Check it.","Sprawdź."],["Shop smarter.","Kupuj mądrzej."],["QC first.","Najpierw QC."],["Checkout second.","Potem płatność."],
    ["SEO articles","Artykuły SEO"],["Useful ACBuy research, written for real shopping decisions.","Praktyczne analizy ACBuy pomagające w realnych decyzjach zakupowych."],["This article hub targets the questions people search before ordering. Every topic is separated by intent, grounded in current platform information, and linked to a practical next step.","Ten dział odpowiada na pytania zadawane przed zamówieniem. Każdy temat ma jasny cel, opiera się na aktualnych informacjach platformy i prowadzi do praktycznego kolejnego kroku."],
    ["Product discovery","Wyszukiwanie produktów"],["How to use an ACBuy spreadsheet efficiently","Jak skutecznie korzystać z arkusza ACBuy"],["A useful product index should shorten the path from a search term to a verifiable source record. Start with a specific product type, model, material, or use case; then compare the listed price, source ID, available variants, and destination record before ordering.","Dobry indeks skraca drogę od wyszukiwania do weryfikowalnego wpisu. Zacznij od konkretnego typu, modelu, materiału lub zastosowania, a następnie porównaj cenę, ID źródła, warianty i stronę docelową."],["Category pages help broad discovery, while individual product pages answer narrower searches. Neither replaces warehouse inspection: the seller listing describes what is offered, while QC photos show what actually arrived.","Kategorie ułatwiają ogólne wyszukiwanie, a karty produktów odpowiadają na precyzyjne pytania. Żadna z nich nie zastępuje kontroli magazynowej: oferta opisuje towar, a zdjęcia QC pokazują, co dotarło."],["Read the complete beginner guide ↗","Przeczytaj pełny poradnik dla początkujących ↗"],
    ["Quality control","Kontrola jakości"],["What ACBuy QC photos can—and cannot—prove","Co zdjęcia QC ACBuy mogą — a czego nie mogą — potwierdzić"],["Warehouse photographs can reveal shape, color consistency, stitching, measurements, visible damage, and included accessories. They cannot guarantee material composition, long-term durability, fit, or customs outcomes.","Zdjęcia magazynowe pokazują kształt, kolor, szwy, wymiary, uszkodzenia i akcesoria. Nie gwarantują składu, trwałości, dopasowania ani wyniku odprawy celnej."],["Review every photo in the same order and request clearer evidence when an important detail is missing. A repeatable checklist is more reliable than judging an item from one flattering angle.","Oglądaj zdjęcia zawsze w tej samej kolejności i proś o wyraźniejsze ujęcie, gdy brakuje szczegółu. Powtarzalna lista kontroli jest pewniejsza niż jedna korzystna perspektywa."],["Open the five-point QC guide ↗","Otwórz pięciopunktowy poradnik QC ↗"],
    ["Parcel planning without fake universal prices","Planowanie paczki bez fałszywych uniwersalnych cen"],["International shipping cost depends on destination, available line, actual or volumetric weight, packaging, product restrictions, and current carrier pricing. That is why a fixed external price table quickly becomes misleading.","Koszt wysyłki zależy od kraju, linii, wagi rzeczywistej lub gabarytowej, opakowania, ograniczeń i bieżących stawek. Stała zewnętrzna tabela szybko staje się więc myląca."],["Use estimates for planning, then recalculate after the warehouse records the real item data. Consolidation may reduce repeated base charges, but a larger parcel is not automatically the cheapest or most suitable option.","Używaj szacunków do planowania, a potem przelicz koszt na danych z magazynu. Łączenie może obniżyć opłaty bazowe, ale większa paczka nie zawsze jest najtańsza lub najlepsza."],["Read the parcel planning guide ↗","Przeczytaj poradnik planowania paczki ↗"],
    ["Research standard","Standard badań"],["How this independent guide verifies information","Jak ten niezależny poradnik weryfikuje informacje"],["Platform facts are checked against ACBuy’s current official pages before publication. Product names, prices, and source links are checked against public destination records. Claims that cannot be verified—such as guaranteed delivery times, customs clearance, or universal quality—are not presented as facts.","Przed publikacją informacje są porównywane z aktualnymi oficjalnymi stronami ACBuy. Nazwy, ceny i linki są sprawdzane w publicznych wpisach. Nieweryfikowalne obietnice nie są przedstawiane jako fakty."],["Because prices, stock, routes, and policies can change, every guide tells readers which details must be confirmed again on the destination platform.","Ponieważ ceny, stany, trasy i zasady mogą się zmieniać, każdy poradnik wskazuje, co trzeba ponownie sprawdzić na platformie docelowej."],["Browse current product records ↗","Przeglądaj aktualne wpisy produktów ↗"],
  ],
};


const trustFixes: Record<Exclude<Lang,"en">, Pairs> = {
  de: [["Research & Guides","Recherche & Ratgeber"],["Research & guides","Recherche & Ratgeber"],["Search full catalog","Gesamten Katalog durchsuchen"],["Links checked August 26, 2026","Links geprüft am 26. August 2026"],["Preview listings use public product records and the current first image from each linked product page. Verify the exact item details on the destination page.","Die Vorschau nutzt öffentliche Produkteinträge und das aktuelle erste Bild jeder verlinkten Produktseite. Prüfe die genauen Artikeldetails auf der Zielseite."],["Checked Aug 26, 2026","Geprüft am 26. Aug. 2026"],["Approx. USD","Ca. USD"]],
  fr: [["Research & Guides","Recherches et guides"],["Research & guides","Recherches et guides"],["Search full catalog","Rechercher dans tout le catalogue"],["Links checked August 26, 2026","Liens vérifiés le 26 août 2026"],["Preview listings use public product records and the current first image from each linked product page. Verify the exact item details on the destination page.","Les aperçus utilisent des fiches publiques et la première image actuelle de chaque page produit liée. Vérifiez les détails exacts sur la page de destination."],["Checked Aug 26, 2026","Vérifié le 26 août 2026"],["Approx. USD","USD env."]],
  es: [["Research & Guides","Investigación y guías"],["Research & guides","Investigación y guías"],["Search full catalog","Buscar en todo el catálogo"],["Links checked August 26, 2026","Enlaces comprobados el 26 de agosto de 2026"],["Preview listings use public product records and the current first image from each linked product page. Verify the exact item details on the destination page.","Las vistas previas usan fichas públicas y la primera imagen actual de cada página enlazada. Verifica los detalles exactos en la página de destino."],["Checked Aug 26, 2026","Comprobado el 26 ago 2026"],["Approx. USD","USD aprox."]],
  it: [["Research & Guides","Ricerche e guide"],["Research & guides","Ricerche e guide"],["Search full catalog","Cerca nell’intero catalogo"],["Links checked August 26, 2026","Link verificati il 26 agosto 2026"],["Preview listings use public product records and the current first image from each linked product page. Verify the exact item details on the destination page.","Le anteprime usano schede pubbliche e la prima immagine attuale di ogni pagina prodotto collegata. Verifica i dettagli esatti nella pagina di destinazione."],["Checked Aug 26, 2026","Verificato il 26 ago 2026"],["Approx. USD","USD circa"]],
  pl: [["Research & Guides","Analizy i poradniki"],["Research & guides","Analizy i poradniki"],["Search full catalog","Przeszukaj pełny katalog"],["Links checked August 26, 2026","Linki sprawdzone 26 sierpnia 2026 r."],["Preview listings use public product records and the current first image from each linked product page. Verify the exact item details on the destination page.","Podgląd korzysta z publicznych kart produktów i aktualnego pierwszego zdjęcia z każdej strony docelowej. Sprawdź dokładne dane na stronie produktu."],["Checked Aug 26, 2026","Sprawdzono 26.08.2026"],["Approx. USD","Około USD"]],
};

function makeMap(base: Pairs, extra: Pairs = []) {
  return new Map<string,string>([...base, ...extra]);
}

export const dictionaries: Record<Exclude<Lang,"en">, Map<string,string>> = {
  de: makeMap(de, [...pageExtras.de, ...longArticleTranslations.de, ...trustFixes.de]),
  fr: makeMap(fr, [...overrides.fr, ...nativeBody.fr, ...pageExtras.fr, ...longArticleTranslations.fr, ...trustFixes.fr]),
  es: makeMap(es, [...overrides.es, ...nativeBody.es, ...pageExtras.es, ...longArticleTranslations.es, ...trustFixes.es]),
  it: makeMap(it, [...overrides.it, ...nativeBody.it, ...pageExtras.it, ...longArticleTranslations.it, ...trustFixes.it]),
  pl: makeMap(pl, [...overrides.pl, ...nativeBody.pl, ...pageExtras.pl, ...longArticleTranslations.pl, ...trustFixes.pl]),
};
