import type {SeoArticle} from "./seo-articles";
import type {Lang} from "./site-data";

export const variantCheckArticle:SeoArticle={
slug:"joyagoo-color-size-quantity-variant-check",
title:"Joyagoo Product Options: Confirm Color, Size, Quantity and Variant Before Ordering",
description:"Use a precise Joyagoo product-option check to copy the exact color, size, quantity and variant from a live listing into a decision-ready order record.",
meta:"PRODUCT OPTION CHECK · 15 MIN",
sourceNote:"Workflow checked September 6, 2026 against current Joyagoo Shopping Guidance. The live source listing and final order summary control every option decision.",
quickFacts:["Copy option text exactly","Treat quantity as a separate field","Check option-linked images","Record uncertainty before payment","Recheck the final order summary"],
sections:[
{heading:"Why an option check needs its own gate",paragraphs:["A product link can reach the correct listing and still produce the wrong order. The page may contain several colors, sizes, bundles, materials or model years under one product identity. A spreadsheet thumbnail normally represents one visible example, while the default option on the destination page may be another. The identity check answers ‘is this the right listing?’ The option check answers the narrower transaction question: ‘does the order instruction identify the exact unit I intend to buy?’ Both must pass before payment.","Joyagoo’s current Shopping Guidance explicitly places color, size and quantity selection before an item is added or paid for. That ordering matters. These are not cosmetic notes for the warehouse to interpret later; they define what the purchasing agent is asked to buy from the seller. A disciplined record therefore preserves the seller’s exact option language, the visible image associated with that choice, the quantity and any remaining ambiguity. It does not translate a guess into a confident instruction." ]},
{heading:"Freeze the live listing before interpreting it",paragraphs:["Open the source listing from the final destination link and record the check date. Save the listing title, product identifier, seller context and a screenshot showing the complete option area. If the page redirects, loads a different product or hides options behind a login that you cannot evaluate, stop. A saved spreadsheet row is dated discovery evidence; it cannot establish which options exist today. The current source page is the controlling evidence until the final Joyagoo order summary is created.","Do not begin by choosing the option that looks closest to the spreadsheet image. First inventory every selector the seller exposes: color, size, style, version, pack count, material, model, left or right orientation, and any customization field. A selector may combine two facts in one label, such as ‘black / upgraded version’ or ‘blue / set of two.’ Copy the whole visible label. Shortening it can erase the part that distinguishes one sellable unit from another." ]},
{heading:"Separate color from image appearance",paragraphs:["Copy the seller’s color label exactly, then describe what the selected image visibly shows in a separate field. Lighting, screen settings and seller photography can make black appear charcoal or cream appear white. The written label is the purchase instruction; the image is supporting evidence for the buyer’s interpretation. If the label and image appear inconsistent, record the contradiction and ask for clarification rather than replacing the seller’s wording with your own preferred color name.","Watch for image changes after selecting a color. Some listings update the gallery to the intended option; others keep a generic promotional image. Record ‘option-linked image’ only when the page actually changes in response to the selection. Never call a color verified simply because one thumbnail resembles it. A useful order record might say: seller label ‘dark grey,’ selected thumbnail shows a charcoal zip hoodie, image response observed on September 6. That statement is reproducible and makes no promise about exact real-world shade." ]},
{heading:"Treat size as a label plus evidence",paragraphs:["A size label is not a universal measurement. Save the exact selected label—such as 42, XL or 170/92A—and separately save the size-chart row or measurements used to choose it. Note the units and measurement method when shown. If the listing offers several charts for different versions, connect the intended option to the correct chart. Do not silently convert a seller size into a familiar regional size or promise fit from a letter label alone.","Build a small size record with five fields: option label, relevant body or garment measurements, units, chart date and unresolved question. For footwear, distinguish seller size, foot-length guidance and insole measurement; they are not interchangeable. For clothing, identify whether the chart describes the garment or the wearer. When a decisive measurement is missing, the result is ‘hold for answer,’ not ‘choose the usual size.’ The later warehouse QC stage can check a received item, but it should not be used to excuse an avoidable pre-payment guess." ]},
{heading:"Make quantity unambiguous",paragraphs:["Quantity has two layers: the checkout quantity and the number of pieces contained in one selected option. A listing can price one pair, one piece, a two-pack or a component rather than the pictured set. Read the title, option label, unit description and quantity control together. Record ‘1 selected unit = 2 pieces’ only when the live listing clearly supports it. A gallery showing several objects is not proof that all are included.","For wholesale or tiered listings, check whether a minimum quantity applies and whether the displayed price changes with the count. Do not assume the lowest visible figure buys one complete retail unit. Your working record should show intended units, pieces per unit, total expected pieces and the evidence behind that interpretation. If any of those fields conflict, stop before transfer. A precise quantity instruction prevents a correct product and color from becoming an incorrect order simply because the seller’s unit was misunderstood." ]},
{heading:"Resolve variant labels without inventing meaning",paragraphs:["Variant labels often carry the hardest distinctions: standard versus upgraded, old versus new version, device model, plug type, fabric weight, set composition or personalized text. Preserve the original visible label before translating it. Then write a plain-language interpretation and mark it as seller-stated, visually observed or still uncertain. Similar labels are not interchangeable merely because their thumbnails look alike or their prices are close.","Use a variant matrix when more than one selector interacts. Put each sellable combination on one row and record color, size, version, quantity, option image and displayed product-stage price. Eliminate rows that do not meet the buyer’s must-have conditions. This method narrows a complex listing without ranking quality or seller reliability. If selecting one field resets another, repeat the whole combination and take a fresh snapshot; otherwise the saved instruction may combine options the page never allowed together." ]},
{heading:"Create a decision-ready handoff record",paragraphs:["Before using the link in Joyagoo, write one compact instruction block: source URL, product identifier, exact color label, exact size label, exact variant label, quantity, included-piece interpretation and check date. Attach the listing screenshot and relevant size evidence. Add a short ‘do not substitute’ note only when substitution would materially change the purchase. Avoid long informal messages that mix preferences, assumptions and required fields, because the operative instruction becomes difficult to identify.","Classify each field as confirmed on the live listing, buyer preference, seller statement or unresolved. Proceed only when every required selector is confirmed and any uncertainty has been consciously accepted. Pause when the intended option is absent, two labels remain ambiguous, the quantity unit is unclear or a decisive compatibility field is missing. Cancel the candidate when the live combination contradicts a non-negotiable requirement. These outcomes keep a shortlist useful without pretending that every link must end in a purchase." ]},
{heading:"Recheck the order summary before payment",paragraphs:["Paste or search the product through the current Joyagoo workflow, choose the recorded color, size and quantity, and compare the resulting order summary field by field. The final summary should preserve the same product identity and option combination. If the platform displays a translated label, compare its position, source value and linked image with the original record. A mismatch at this stage is a stop signal, even when the product image still looks familiar.","Record the visible product-stage price and China domestic-freight field at this final check, but keep them outside the option conclusion because they can change independently. Reopen the source listing immediately before payment if the record is not fresh. The correct outcome is not ‘verified product.’ It is narrower: on the stated date, the live listing and Joyagoo order summary agreed on the exact color, size, variant and quantity requested. That is enough to authorize the purchase instruction without claiming future stock, quality, authenticity or seller performance." ]},
{heading:"Use the same record when QC arrives",paragraphs:["Keep the option record until warehouse inspection is complete. When photos and status evidence arrive, compare product identity first, then color label, size tag, visible variant features, quantity and included parts. The warehouse evidence can show what arrived; it cannot retroactively repair an ambiguous order instruction. If the received item differs, the pre-payment record establishes what was selected and gives a return or clarification request a factual starting point.","Close the record with one result: matched, evidence requested, mismatch under review or no longer actionable. Include the relevant timestamp rather than rewriting the original fields. This preserves a clean chain from spreadsheet discovery to source listing, order summary and warehouse evidence. The method does not make a product better or a seller safer. It makes the buyer’s intended option legible, reproducible and testable at every stage where a reversible decision still exists." ]}
]};

const make=(lang:Lang,title:string,description:string,sourceNote:string,facts:string[],rows:[string,string,string][]):SeoArticle=>({slug:variantCheckArticle.slug,title,description,meta:{de:"PRODUKTOPTIONEN · 15 MIN",es:"OPCIONES DE PRODUCTO · 15 MIN",fr:"OPTIONS PRODUIT · 15 MIN",it:"OPZIONI PRODOTTO · 15 MIN",en:"PRODUCT OPTION CHECK · 15 MIN"}[lang],sourceNote,quickFacts:facts,sections:rows.map(([heading,a,b])=>({heading,paragraphs:[a,b]}))});

export const variantCheckTranslations:Partial<Record<Lang,SeoArticle>>={
de:make("de","Joyagoo-Produktoptionen: Farbe, Größe, Menge und Variante vor der Bestellung bestätigen","Übertrage Farbe, Größe, Menge und Variante aus dem Live-Angebot in einen eindeutigen Joyagoo-Bestelldatensatz.","Ablauf am 6. September 2026 anhand der aktuellen Joyagoo Shopping Guidance geprüft. Live-Angebot und endgültige Bestellübersicht entscheiden.",["Optionstext exakt kopieren","Menge separat erfassen","Optionsbilder prüfen","Unsicherheit vor Zahlung notieren","Bestellübersicht erneut abgleichen"],[
["Warum Optionen ein eigenes Prüftor brauchen","Der richtige Link kann trotzdem zur falschen Bestellung führen, weil eine Seite mehrere Farben, Größen, Sets, Materialien oder Versionen bündelt. Das Tabellenbild zeigt oft nur ein Beispiel. Die Identitätsprüfung fragt nach dem richtigen Angebot; die Optionsprüfung nach der exakt gewünschten Einheit. Beide müssen vor Zahlung bestehen.","Die aktuelle Joyagoo-Anleitung setzt die Wahl von Farbe, Größe und Menge vor Hinzufügen und Zahlung. Diese Angaben definieren den Einkaufsauftrag. Speichere daher Originalbezeichnung, zugeordnetes Bild, Menge und offene Unsicherheit, statt eine Vermutung als klare Anweisung zu übersetzen."],
["Das Live-Angebot vor der Auslegung sichern","Öffne die endgültige Quellseite, notiere Datum, Titel, Produkt-ID, Verkäuferkontext und den ganzen Optionsbereich. Stoppe bei Weiterleitung, anderem Produkt oder nicht prüfbarer Login-Sperre. Eine Tabellenzeile ist nur datierter Entdeckungsbeleg; die aktuelle Quelle steuert bis zur Joyagoo-Bestellübersicht.","Inventarisiere jeden Selektor: Farbe, Größe, Stil, Version, Packung, Material, Modell, Ausrichtung und Personalisierung. Kopiere kombinierte Labels vollständig, etwa „schwarz / verbesserte Version“. Eine Kürzung kann genau den Teil löschen, der eine verkaufte Einheit unterscheidet."],
["Farbe und Bildwirkung trennen","Kopiere den Farbtext und beschreibe das sichtbare Bild separat. Licht und Bildschirm können Schwarz grau oder Creme weiß wirken lassen. Der Text ist die Kaufanweisung, das Bild nur Beleg. Bei Widerspruch frage nach, statt den Verkäufernamen durch eine eigene Farbe zu ersetzen.","Beobachte, ob sich das Bild nach Farbauswahl ändert. Nenne es nur dann optionsbezogen. Ein ähnliches Thumbnail bestätigt keine Farbe. Ein belastbarer Satz nennt Verkäuferlabel, sichtbares Motiv, Reaktion der Seite und Prüfdatum, ohne einen exakten realen Farbton zu versprechen."],
["Größe als Label plus Beleg behandeln","Speichere das exakte Label wie 42, XL oder 170/92A und getrennt die verwendete Tabellenzeile oder Maße mit Einheit und Methode. Verknüpfe die richtige Tabelle mit der Variante. Wandle Verkäufergrößen nicht still in regionale Größen um und verspreche keine Passform.","Erfasse Label, Körper- oder Kleidungsmaß, Einheit, Tabellendatum und offene Frage. Bei Schuhen sind Verkäufergröße, Fußlänge und Innensohlenmaß verschieden; bei Kleidung ist Körper- oder Produktmaß zu unterscheiden. Fehlende Schlüsselmaße bedeuten warten, nicht die gewohnte Größe raten."],
["Menge eindeutig machen","Unterscheide Checkout-Menge und Stücke pro Option. Ein Angebot kann Paar, Einzelstück, Zweierpack oder nur einen Bestandteil bepreisen. Lies Titel, Label, Einheit und Mengenfeld zusammen. Mehrere Gegenstände im Bild beweisen keinen Lieferumfang.","Bei Staffelpreisen prüfe Mindestmenge und Preisänderung. Speichere Einheiten, Stücke je Einheit, erwartete Gesamtstücke und Beleg. Bei Konflikt stoppe. Eine genaue Menge verhindert, dass ein sonst richtiges Produkt allein wegen missverstandener Verkaufseinheit falsch bestellt wird."],
["Varianten ohne erfundene Bedeutung klären","Varianten unterscheiden Standard, Upgrade, Modell, Stecker, Stoffgewicht, Set oder Personalisierung. Bewahre das Original vor Übersetzung und kennzeichne Interpretation als Verkäuferaussage, Beobachtung oder offen. Ähnliche Bilder und Preise machen Labels nicht austauschbar.","Nutze bei kombinierten Selektoren eine Matrix mit Farbe, Größe, Version, Menge, Bild und angezeigtem Produktpreis. Entferne unpassende Reihen, ohne Qualitätsranking. Wenn eine Auswahl eine andere zurücksetzt, speichere die komplette Kombination neu, damit keine unmögliche Variante entsteht."],
["Einen entscheidungsreifen Übergabedatensatz bauen","Notiere Quelle, ID, exakte Farb-, Größen- und Variantenlabels, Menge, Lieferumfang und Datum. Hänge Screenshot und Größenbeleg an. Ein „nicht ersetzen“ ist nur bei wesentlicher Abweichung sinnvoll. Lange Nachrichten aus Wunsch und Annahme verschleiern die operative Anweisung.","Markiere jedes Feld als live bestätigt, Käuferwunsch, Verkäuferaussage oder offen. Weiter nur bei bestätigten Pflichtfeldern. Pause bei fehlender Option, unklarer Einheit oder Kompatibilität; Kandidat streichen bei Widerspruch zu Muss-Kriterien. Nicht jeder Link muss zum Kauf führen."],
["Vor Zahlung die Bestellübersicht prüfen","Übernimm den Artikel in den aktuellen Joyagoo-Ablauf und vergleiche Produkt, Farbe, Größe, Variante und Menge. Bei übersetzten Labels nutze Position, Quellwert und Bild. Jede Abweichung stoppt, auch wenn das Hauptbild vertraut bleibt.","Notiere Produktpreis und China-Inlandsfracht separat, weil sie unabhängig wechseln. Öffne eine nicht frische Quelle erneut. Ergebnis ist nicht „verifiziertes Produkt“, sondern datierte Übereinstimmung der konkreten Optionen—ohne Versprechen zu Bestand, Qualität, Echtheit oder Verkäufer."],
["Den Datensatz beim QC weiterverwenden","Bewahre den Datensatz bis zur Lagerprüfung. Vergleiche zuerst Identität, dann Farbe, Größenetikett, Variantenmerkmale, Menge und Teile. Lagerbelege zeigen das Angekommene, können aber eine unklare Anweisung nicht nachträglich reparieren. Bei Abweichung liefert der Zahlungsdatensatz den sachlichen Ausgangspunkt.","Schließe mit passend, Beleg angefordert, Abweichung in Prüfung oder nicht mehr umkehrbar. Erhalte Originalfelder und ergänze Zeitpunkte. So bleibt die Kette von Spreadsheet über Quelle und Bestellübersicht bis zum Lager prüfbar, ohne Produkt- oder Verkäufersicherheit zu behaupten."]]),
es:make("es","Opciones de producto Joyagoo: confirma color, talla, cantidad y variante antes de pedir","Copia color, talla, cantidad y variante del anuncio activo a un registro de pedido Joyagoo sin ambigüedad.","Flujo comprobado el 6 de septiembre de 2026 con la Shopping Guidance actual de Joyagoo. Mandan el anuncio activo y el resumen final.",["Copia el texto exacto","Separa la cantidad","Comprueba imágenes vinculadas","Anota dudas antes de pagar","Revisa el resumen final"],[
["Por qué las opciones necesitan su propio control","El enlace correcto puede generar un pedido erróneo si la página agrupa colores, tallas, sets, materiales o versiones. La miniatura muestra un ejemplo. La identidad responde si es el anuncio correcto; las opciones, si la instrucción identifica la unidad exacta. Ambos controles deben aprobarse.","La guía actual de Joyagoo coloca color, talla y cantidad antes de añadir o pagar. Definen lo que el agente compra. Conserva texto original, imagen asociada, cantidad y dudas; no conviertas una suposición en instrucción segura."],
["Guardar el anuncio activo antes de interpretarlo","Abre el destino final y registra fecha, título, ID, vendedor y todos los selectores. Detente si redirige, cambia de producto o no puede evaluarse. La fila es evidencia fechada de descubrimiento; la fuente actual controla hasta el resumen Joyagoo.","Enumera color, talla, estilo, versión, pack, material, modelo, orientación y personalización. Copia completas las etiquetas combinadas. Acortarlas puede borrar justo el rasgo que diferencia una unidad vendible."],
["Separar color de apariencia","Copia el nombre del vendedor y describe la imagen aparte. Luz y pantalla alteran el tono. El texto instruye la compra; la imagen apoya la interpretación. Si se contradicen, registra y pregunta, sin sustituir el nombre por tu color preferido.","Observa si la galería cambia al seleccionar. Solo entonces llámala vinculada a la opción. Una miniatura parecida no verifica el color. Anota etiqueta, aspecto, respuesta de página y fecha sin prometer un tono real exacto."],
["Tratar la talla como etiqueta y evidencia","Guarda 42, XL o 170/92A y por separado la fila o medidas, unidades y método. Relaciona la tabla correcta con la versión. No conviertas silenciosamente a tallas regionales ni prometas ajuste.","Registra etiqueta, medidas corporales o de prenda, unidades, fecha y duda. En calzado no confundas talla, longitud del pie y plantilla; en ropa distingue cuerpo y prenda. Si falta una medida decisiva, espera una respuesta en vez de elegir la habitual."],
["Hacer inequívoca la cantidad","Distingue cantidad de checkout y piezas por opción. Puede venderse par, unidad, pack o componente. Lee título, etiqueta, unidad y control juntos; una foto con varios objetos no demuestra contenido.","En precios por tramos comprueba mínimo y cambios. Guarda unidades, piezas por unidad, total y evidencia. Si chocan, detente. Una cantidad precisa evita que un producto correcto termine mal pedido por interpretar la unidad."],
["Resolver variantes sin inventar","Las variantes pueden distinguir estándar, mejorada, modelo, enchufe, tejido, set o personalización. Conserva el original y clasifica la interpretación como declaración, observación o duda. Fotos y precios similares no hacen equivalentes las etiquetas.","Usa una matriz para combinaciones y registra color, talla, versión, cantidad, imagen y precio mostrado. Elimina las que no cumplen requisitos sin clasificarlas por calidad. Si un selector reinicia otro, vuelve a capturar toda la combinación."],
["Crear un registro listo para transferir","Escribe URL, ID, etiquetas exactas, cantidad, piezas y fecha; adjunta captura y talla. Usa ‘no sustituir’ solo si importa. Los mensajes largos que mezclan preferencias y supuestos esconden la instrucción operativa.","Marca cada campo como confirmado, preferencia, declaración o abierto. Avanza solo con selectores requeridos claros; pausa ante opción ausente, unidad o compatibilidad dudosa; elimina si contradice un requisito. No todo enlace debe acabar en compra."],
["Revisar el resumen antes de pagar","Traslada el producto al flujo Joyagoo y compara identidad, color, talla, variante y cantidad. Para etiquetas traducidas, contrasta posición, origen e imagen. Cualquier diferencia obliga a parar aunque la foto resulte familiar.","Anota precio y envío nacional aparte porque cambian independientemente. Reabre la fuente si no es reciente. La conclusión es coincidencia fechada de opciones, no producto verificado ni promesa de stock, calidad, autenticidad o vendedor."],
["Reutilizar el registro en QC","Conserva el registro hasta almacén. Compara identidad, color, etiqueta de talla, rasgos, cantidad y piezas. Las pruebas muestran lo recibido, pero no arreglan una instrucción ambigua. Ante diferencia, el registro previo aporta el punto de partida factual.","Cierra como coincide, pedir evidencia, discrepancia en revisión o irreversible. Añade tiempos sin reescribir campos. Así la cadena hoja-fuente-resumen-almacén queda comprobable sin prometer calidad o seguridad del vendedor."]]),
fr:make("fr","Options produit Joyagoo : confirmer couleur, taille, quantité et variante avant commande","Copiez les options exactes de l’annonce active dans un dossier de commande Joyagoo sans ambiguïté.","Processus vérifié le 6 septembre 2026 avec le guide d’achat Joyagoo actuel. L’annonce active et le récapitulatif final font foi.",["Copier le libellé exact","Séparer la quantité","Contrôler l’image d’option","Noter les doutes avant paiement","Comparer le récapitulatif"],[
["Pourquoi les options exigent un contrôle distinct","Le bon lien peut produire la mauvaise commande si la page regroupe couleurs, tailles, lots, matières ou versions. La miniature n’en montre souvent qu’une. L’identité vérifie l’annonce; les options vérifient l’unité exacte. Les deux doivent réussir.","Le guide Joyagoo actuel place couleur, taille et quantité avant ajout ou paiement. Elles définissent l’achat demandé. Conservez libellé original, image associée, quantité et doute; ne transformez pas une hypothèse en instruction certaine."],
["Figer l’annonce active avant interprétation","Ouvrez la destination finale et notez date, titre, ID, vendeur et zone d’options. Arrêtez en cas de redirection, autre produit ou page non vérifiable. La ligne du tableau n’est qu’une preuve de découverte datée; la source active contrôle la suite.","Inventoriez couleur, taille, style, version, lot, matière, modèle, orientation et personnalisation. Copiez les libellés combinés en entier: les raccourcir peut supprimer précisément la différence entre deux unités vendues."],
["Séparer couleur et apparence","Copiez le nom de couleur du vendeur et décrivez l’image dans un autre champ. Lumière et écran modifient les tons. Le texte est l’instruction, l’image une preuve secondaire. En cas de conflit, notez-le et demandez, sans renommer la couleur.","Vérifiez si l’image change réellement après sélection. Sinon, ne la dites pas liée à l’option. Une miniature semblable ne valide rien. Notez libellé, apparence, réaction et date sans promettre la nuance réelle."],
["Traiter la taille comme libellé et preuve","Sauvegardez 42, XL ou 170/92A, puis séparément mesures, unités, méthode et tableau pertinent. Ne convertissez pas silencieusement en taille régionale et ne promettez pas l’ajustement.","Consignez libellé, mesures du corps ou vêtement, unités, date et question. Pour les chaussures, taille, longueur du pied et semelle diffèrent; pour les vêtements, distinguez corps et article. Une mesure décisive absente impose d’attendre, pas de deviner."],
["Rendre la quantité explicite","Séparez quantité au panier et pièces par option. L’annonce peut vendre une paire, une pièce, un lot ou un composant. Lisez titre, libellé, unité et commande ensemble; plusieurs objets en photo ne prouvent pas le contenu.","Pour les paliers, contrôlez minimum et prix. Notez unités, pièces par unité, total attendu et preuve. Stoppez en cas de conflit. Une quantité précise évite une erreur malgré un produit et une couleur corrects."],
["Résoudre les variantes sans inventer","Les variantes distinguent standard, amélioration, modèle, prise, matière, lot ou personnalisation. Conservez l’original et marquez l’explication comme déclaration, observation ou incertitude. Images et prix proches ne rendent pas les libellés équivalents.","Une matrice peut noter couleur, taille, version, quantité, image et prix pour chaque combinaison. Écartez les incompatibles sans classer la qualité. Si une sélection réinitialise l’autre, capturez de nouveau la combinaison entière."],
["Créer un dossier prêt à transmettre","Écrivez URL, ID, libellés exacts, quantité, contenu et date; joignez capture et preuve de taille. Réservez ‘ne pas substituer’ aux différences décisives. Un long message mêlant goûts et hypothèses masque l’instruction.","Classez chaque champ: confirmé, préférence, déclaration ou ouvert. Continuez seulement si les sélecteurs requis sont clairs; pause si option, unité ou compatibilité manque; abandon si un impératif est contredit. Tout lien ne doit pas devenir commande."],
["Comparer le récapitulatif avant paiement","Dans le flux Joyagoo, comparez identité, couleur, taille, variante et quantité. Si les labels sont traduits, contrôlez position, valeur source et image. Toute différence arrête le processus même si la photo semble connue.","Notez prix et fret national séparément, car ils changent indépendamment. Rouvrez une source ancienne. La conclusion est un accord daté des options, pas un produit vérifié ni une garantie de stock, qualité, authenticité ou vendeur."],
["Réutiliser le dossier au QC","Gardez le dossier jusqu’au contrôle entrepôt. Comparez identité, couleur, étiquette de taille, caractéristiques, quantité et pièces. La preuve montre le reçu mais ne corrige pas une instruction ambiguë. En cas d’écart, le dossier initial donne la base factuelle.","Clôturez par conforme, preuve demandée, écart examiné ou irréversible. Ajoutez l’heure sans réécrire les champs. La chaîne tableur-source-récapitulatif-entrepôt reste testable sans promesse de qualité ou fiabilité."]]),
it:make("it","Opzioni prodotto Joyagoo: confermare colore, taglia, quantità e variante prima dell’ordine","Copia le opzioni esatte dell’inserzione attiva in un record d’ordine Joyagoo privo di ambiguità.","Flusso verificato il 6 settembre 2026 con l’attuale Shopping Guidance Joyagoo. Contano inserzione live e riepilogo finale.",["Copia il testo esatto","Separa la quantità","Controlla le immagini collegate","Annota i dubbi prima del pagamento","Ricontrolla il riepilogo"],[
["Perché le opzioni richiedono un controllo dedicato","Il link giusto può produrre l’ordine sbagliato se la pagina raccoglie colori, taglie, set, materiali o versioni. La miniatura mostra spesso un solo esempio. L’identità verifica l’inserzione; le opzioni verificano l’unità precisa. Entrambi i controlli devono riuscire.","La guida Joyagoo attuale colloca colore, taglia e quantità prima di aggiunta e pagamento. Definiscono ciò che l’agente acquista. Conserva etichetta originale, immagine associata, quantità e dubbi; non trasformare una supposizione in istruzione certa."],
["Salvare l’inserzione live prima di interpretarla","Apri la destinazione finale e registra data, titolo, ID, venditore e area opzioni. Fermati con redirect, prodotto diverso o pagina non valutabile. La riga del foglio è solo prova datata di scoperta; la fonte attuale governa fino al riepilogo Joyagoo.","Elenca colore, taglia, stile, versione, confezione, materiale, modello, orientamento e personalizzazione. Copia interamente le etichette combinate: abbreviare può eliminare proprio la distinzione tra unità vendibili."],
["Separare colore e aspetto","Copia il nome colore del venditore e descrivi l’immagine in un campo separato. Luce e schermo alterano i toni. Il testo istruisce l’acquisto; l’immagine sostiene l’interpretazione. Se discordano, registra e chiedi senza rinominare il colore.","Controlla se la galleria cambia dopo la selezione. Solo allora chiamala collegata all’opzione. Una miniatura simile non verifica il colore. Annota etichetta, aspetto, risposta della pagina e data senza promettere la tonalità reale."],
["Trattare la taglia come etichetta più prova","Salva 42, XL o 170/92A e separatamente riga, misure, unità e metodo. Collega la tabella corretta alla versione. Non convertire silenziosamente in taglie regionali né promettere vestibilità.","Registra etichetta, misura corpo o capo, unità, data e domanda. Nelle scarpe taglia, lunghezza piede e soletta differiscono; nell’abbigliamento separa corpo e prodotto. Se manca una misura decisiva, attendi una risposta invece di scegliere la solita."],
["Rendere inequivocabile la quantità","Distingui quantità al checkout e pezzi per opzione. Si può vendere paio, singolo, multipack o componente. Leggi titolo, etichetta, unità e controllo insieme; più oggetti in foto non provano il contenuto.","Con prezzi a scaglioni verifica minimo e variazioni. Salva unità, pezzi per unità, totale e prova. In caso di conflitto fermati. Una quantità precisa evita un ordine errato nonostante prodotto e colore corretti."],
["Risolvere le varianti senza inventare","Le varianti distinguono standard, upgrade, modello, spina, tessuto, set o personalizzazione. Conserva l’originale e classifica l’interpretazione come dichiarazione, osservazione o dubbio. Foto e prezzi simili non rendono equivalenti le etichette.","Usa una matrice per colore, taglia, versione, quantità, immagine e prezzo di ogni combinazione. Elimina quelle incompatibili senza classificarne la qualità. Se un selettore ne azzera un altro, salva di nuovo l’intera combinazione."],
["Creare un record pronto al passaggio","Scrivi URL, ID, etichette esatte, quantità, contenuto e data; allega schermata e prova taglia. Usa ‘non sostituire’ solo per differenze sostanziali. Messaggi lunghi che mescolano preferenze e ipotesi nascondono l’istruzione operativa.","Marca ogni campo come confermato, preferenza, dichiarazione o aperto. Procedi solo con selettori richiesti chiari; pausa per opzione, unità o compatibilità dubbia; escludi se contraddice un requisito. Non ogni link deve diventare acquisto."],
["Ricontrollare il riepilogo prima del pagamento","Nel flusso Joyagoo confronta identità, colore, taglia, variante e quantità. Per etichette tradotte verifica posizione, valore sorgente e immagine. Ogni differenza impone stop anche se la foto è familiare.","Registra prezzo e spedizione domestica separatamente perché cambiano da soli. Riapri una fonte non recente. La conclusione è corrispondenza datata delle opzioni, non prodotto verificato né promessa su stock, qualità, autenticità o venditore."],
["Riutilizzare il record al QC","Conserva il record fino al magazzino. Confronta identità, colore, etichetta taglia, caratteristiche, quantità e parti. Le prove mostrano ciò che è arrivato ma non riparano un’istruzione ambigua. Se differisce, il record pre-pagamento è la base fattuale.","Chiudi come corrisponde, prova richiesta, discrepanza in esame o non reversibile. Aggiungi tempi senza riscrivere i campi. La catena foglio-fonte-riepilogo-magazzino resta verificabile senza promettere qualità o affidabilità."]])
};
