import type {SeoArticle} from "./seo-articles";
import type {Lang} from "./site-data";

export const identifierGuideArticle:SeoArticle={
slug:"joyagoo-product-id-source-link-destination-url-guide",
title:"Joyagoo Product ID, Source Link and Destination URL: Which Identifier Solves Which Problem",
description:"Use the right Joyagoo product identifier for matching, reopening and reporting a spreadsheet find without treating any single field as proof of quality or availability.",
meta:"IDENTIFIER MAP · 15 MIN",
sourceNote:"Use the live destination and current order screen for decisions. An identifier helps locate or compare a record; it does not freeze stock, options, price or seller performance.",
quickFacts:["A product ID is a matching token","A source link preserves seller context","A destination URL shows the current route","Redirects require a fresh identity check","Save all three with a check date"],
sections:[
{heading:"Three fields, three different jobs",paragraphs:["A Joyagoo spreadsheet find can carry several strings that look like links or identifiers, but they answer different questions. A product ID helps determine whether two records point to the same underlying listing. A source link preserves the marketplace page and seller context. A destination URL records the page that the buyer actually reached through the current discovery route. Keeping them in separate columns prevents one field from being stretched into evidence it cannot provide.","None of the three proves that the product is available, correctly described, well made or suitable for a buyer. A valid-looking ID can belong to a removed listing. A source link can redirect. A destination page can display a cached preview or a different option structure from the spreadsheet row. The useful method is therefore not to choose one universal identifier. It is to select the field that solves the immediate problem, then confirm the commercial facts on the live page before payment." ]},
{heading:"Use the product ID to match records",paragraphs:["A product ID is most useful when URLs contain tracking parameters, language paths or different wrappers. Extract the marketplace item token exactly as displayed rather than copying a number that merely appears in a campaign parameter. Compare the token from the spreadsheet, the final source page and the current destination. Agreement strengthens the identity match; disagreement is a stop signal that needs explanation.","The ID is not a permanent certificate. Sellers can remove products, replace pages or create a new listing for a similar item. Even when the token is unchanged, the available colors, sizes, quantity tiers and description can change. Record the marketplace or source type beside the ID because equal-looking number formats from different systems are not interchangeable. Use the ID for equality testing and reporting, not as a shortcut for quality, authenticity, inventory or seller reliability." ]},
{heading:"Use the source link to preserve seller context",paragraphs:["The source link points to the original marketplace environment behind a find. It can preserve the seller or shop context, option selector, title, images, quantity rules and China-side delivery fields that matter before ordering. Save the cleanest reachable version and note the date. If the page requires a current session or cannot be opened directly, record that limitation rather than inventing missing details from the spreadsheet preview.","A source link is especially useful when a buyer needs to explain where a model number, color name or size chart came from. It lets the order note refer back to the exact page instead of a cropped image. But it remains third-party seller content. The link does not mean Joyagoo endorses the seller, and it does not guarantee that the destination parser will reproduce every field. Compare what the source says with what the active ordering page accepts." ]},
{heading:"Use the destination URL to reproduce the current route",paragraphs:["The destination URL is the final page reached after the product route has resolved. It answers a practical question: where does this spreadsheet row send a buyer today? Save the post-redirect address rather than only the original click target. Then compare title meaning, main image, product type, source identity and option structure. A successful 200 response is not enough when the content has changed.","Destination URLs are best for reproducing a problem. If a row opens a different product, loses the intended option or lands on a generic page, the final address gives an editor or buyer a concrete starting point. Preserve the input link and final URL together so the redirect can be examined. Do not silently replace the destination with a similar listing while retaining the old product ID, thumbnail or checked date." ]},
{heading:"Strip noise without deleting evidence",paragraphs:["Long URLs often contain referral codes, campaign parameters, language settings or session values. Create a clean comparison copy only after saving the original route. Remove parameters one at a time and confirm that the cleaned address still opens the same product and option context. Never remove a parameter that carries the actual item identity. If cleaning changes the page, keep the original and label the route as dependent on that value.","Use privacy judgment as well. Do not store account tokens, personal addresses or private session data in an editorial spreadsheet or public report. A safe record normally needs the marketplace name, product ID, source link, destination URL, exact option text and checked date. When a private account view is necessary for ordering, keep that evidence in the buyer's own record rather than copying it into a public product index." ]},
{heading:"Resolve redirects with an identity ledger",paragraphs:["Record four values for every redirect check: input URL, final URL, response date and identity result. Classify the identity as matched, partial, mismatch or unavailable. Matched means the product family and stable token agree. Partial means the family looks related but the exact option or seller context cannot be reconciled. Mismatch means the final page is another item or generic landing page. Unavailable means the page cannot currently be evaluated.","This ledger keeps network status separate from product status. A dead link is obvious, but a live redirect to the wrong item is more dangerous because it can look successful to an automated checker. Human review should compare the destination's title, image, product type, seller context and option structure. If the evidence remains partial, do not promote the row as current. Place it in a review queue with the unresolved field named." ]},
{heading:"Choose the identifier by the question",paragraphs:["Use the product ID when asking whether two rows represent the same listing. Use the source link when checking seller wording, images, size data or quantity rules. Use the destination URL when reproducing what a visitor reaches or diagnosing a redirect. Use the exact option text when the question concerns color, size, version or quantity. Use the order number only after an order exists; it identifies a transaction, not the public product page.","A useful worksheet makes that mapping explicit. Add columns named question, controlling field and supporting evidence. For example, 'same listing?' is controlled by source type plus product ID. 'Where does the row open?' is controlled by the final destination. 'Which blue option?' is controlled by live option text and the order summary. This stops a convenient field from becoming a false answer to a different question." ]},
{heading:"Build a compact identifier packet",paragraphs:["Before shortlisting, save the spreadsheet row, source marketplace, product ID, clean source link, input destination, final destination, title snapshot, chosen option text and checked date. Add one line describing any redirect. If a manually entered or DIY order is required, keep the buyer-supplied fields in a separate note and follow the current official instructions rather than assuming the link parser supports the source.","Before payment, reopen the final page and compare the packet with the current order summary. Confirm product identity first, then color, size, version, quantity and any seller note. If the source page and destination disagree, pause and ask which page controls the order. Do not let a matching image override a conflicting ID or option label. The packet exists to expose contradictions before money or return windows become involved." ]},
{heading:"Report a stale or mismatched row precisely",paragraphs:["A useful stale-link report states the spreadsheet page, row or category, input URL, final URL, source type, product ID expected, identity observed and date checked. Describe the mismatch without guessing why it happened. 'Expected jacket ID 123, final page shows shoes ID 456' is actionable. 'Bad link' is not. If only one option disappeared, name that option rather than declaring the whole listing dead.","Do not include login details, private order data or unsupported accusations about the seller. The report should help an editor reproduce the result and decide whether to update, suspend or remove the row. If a replacement listing is proposed, verify it as a new record with its own ID, source, options and date. A replacement is not a continuation simply because the thumbnail looks similar." ]},
{heading:"End with a decision, not a pile of links",paragraphs:["The final outcome should be one of four actions: proceed, ask, suspend or remove. Proceed when the source identity, destination and required option agree. Ask when one named field remains unresolved but the route is otherwise consistent. Suspend when the page cannot be evaluated or redirects unpredictably. Remove when the destination clearly represents another product or no longer supports the row's purpose.","This decision system is deliberately narrower than a product recommendation. It does not rank quality, predict seller dispatch or promise warehouse results. It makes a Joyagoo spreadsheet record reproducible and order-ready by using each identifier for the job it can actually perform. Save the evidence with a date, repeat the check before payment, and treat every later change as a new verification event rather than proof that the earlier record was wrong." ]}
]};

const make=(title:string,description:string,sourceNote:string,facts:string[],rows:[string,string,string][]):SeoArticle=>({slug:identifierGuideArticle.slug,title,description,meta:"IDENTIFIER MAP · 15 MIN",sourceNote,quickFacts:facts,sections:rows.map(([heading,a,b])=>({heading,paragraphs:[a,b]}))});

export const identifierGuideTranslations:Partial<Record<Lang,SeoArticle>>={
de:make("Joyagoo Produkt-ID, Quelllink und Ziel-URL: Welcher Bezeichner löst welches Problem?","Ordne Produkt-ID, Quelllink und endgültige Ziel-URL richtig zu, um einen Spreadsheet-Fund abzugleichen, erneut zu öffnen und präzise zu melden.","Die Live-Zielseite und die aktuelle Bestellung entscheiden. Ein Bezeichner findet einen Datensatz, friert aber Bestand, Optionen, Preis oder Verkäuferleistung nicht ein.",["Produkt-ID gleicht Datensätze ab","Quelllink erhält Verkäuferkontext","Ziel-URL zeigt den aktuellen Weg","Weiterleitungen brauchen Identitätsprüfung","Alle drei mit Datum speichern"],[
["Drei Felder, drei Aufgaben","Die Produkt-ID prüft, ob Datensätze dieselbe Listing-Identität tragen. Der Quelllink erhält Marktplatz, Verkäufer, Optionen und Beschreibung. Die Ziel-URL zeigt, wo ein Besucher nach Weiterleitungen heute ankommt. Getrennte Spalten verhindern, dass ein Feld mehr beweisen soll, als es kann.","Keines beweist Bestand, Qualität oder Eignung. Eine ID kann zu einem entfernten Angebot gehören, ein Link kann umleiten und eine Zielseite kann andere Optionen zeigen. Wähle das Feld nach der Frage und bestätige Kaufdaten immer live."],
["Produkt-ID zum Abgleich nutzen","Extrahiere den tatsächlichen Artikel-Token und verwechsle ihn nicht mit Kampagnenparametern. Vergleiche Spreadsheet, finale Quellseite und Zielseite. Übereinstimmung stärkt den Match; Abweichung bedeutet Stopp und Klärung.","Die ID ist kein Zertifikat. Optionen und Beschreibung können sich bei gleicher ID ändern, ähnliche Produkte können neue IDs erhalten. Speichere deshalb auch Quelltyp und nutze die ID nur für Gleichheitsprüfung und Meldung."],
["Quelllink für Verkäuferkontext","Der Quelllink bewahrt Titel, Bilder, Optionsauswahl, Mengenregeln und Inlandsversand. Speichere die sauberste erreichbare Version mit Datum; ist sie nicht direkt zugänglich, dokumentiere die Grenze statt fehlende Daten zu raten.","Er hilft, Modell, Farbe oder Größentabelle nachzuvollziehen, bleibt aber Inhalt eines Drittverkäufers. Er bedeutet keine Empfehlung und garantiert nicht, dass die Zielseite jedes Feld gleich wiedergibt."],
["Ziel-URL für den aktuellen Weg","Speichere die Adresse nach allen Weiterleitungen. Vergleiche Titelbedeutung, Hauptbild, Produkttyp, Quelle und Optionen. HTTP 200 reicht nicht, wenn die Seite inzwischen ein anderes Produkt zeigt.","Die finale URL macht Fehler reproduzierbar. Bewahre Eingabe und Ergebnis zusammen auf. Ersetze sie nicht still durch ein ähnliches Listing unter alter ID, altem Bild oder altem Prüfdatum."],
["URL-Rauschen sicher entfernen","Sichere zuerst den Originalweg. Entferne Referral-, Sprach- oder Kampagnenparameter einzeln und kontrolliere nach jedem Schritt, ob dasselbe Produkt und derselbe Kontext bleiben. Identitätsparameter dürfen nicht gelöscht werden.","Speichere keine Kontotoken, Adressen oder privaten Sitzungsdaten öffentlich. Meist genügen Marktplatz, ID, Quelllink, Ziel-URL, Option und Datum; private Bestellansichten bleiben im persönlichen Datensatz."],
["Weiterleitungen protokollieren","Erfasse Eingabe-URL, finale URL, Datum und Ergebnis: Match, teilweise, falsch oder nicht verfügbar. Ein Match verlangt passende Produktfamilie und Identität; teilweise bedeutet eine offene Option oder Quelle; falsch ist ein anderes Produkt.","So bleibt Netzwerkstatus von Produktstatus getrennt. Eine lebende falsche Weiterleitung ist gefährlicher als ein klarer 404. Prüfe Titel, Bild, Typ, Verkäufer und Optionen und verschiebe unklare Zeilen in eine Prüfwarteschlange."],
["Bezeichner nach Frage wählen","Für 'gleiches Listing?' nutze Quelltyp plus ID. Für Verkäufertext oder Größendaten den Quelllink. Für den aktuellen Klickweg die Ziel-URL. Für Farbe, Größe, Version und Menge den Live-Optionstext. Eine Bestellnummer identifiziert erst die Transaktion.","Eine Tabelle mit Frage, kontrollierendem Feld und Stützbeleg verhindert falsche Schlüsse. Ein Bild darf keinen ID-Konflikt überstimmen; ein Produktlink beantwortet nicht automatisch eine Variantenfrage."],
["Kompaktes Paket bauen","Speichere Zeile, Marktplatz, ID, sauberen Quelllink, Eingabe- und Ziel-URL, Titel, Option und Datum. Notiere die Weiterleitung. Bei DIY-Aufträgen bleiben manuell eingegebene Angaben getrennt und folgen der aktuellen offiziellen Anleitung.","Vor Zahlung öffne die Seite erneut und vergleiche zuerst Identität, dann Farbe, Größe, Version, Menge und Hinweise. Bei Widerspruch pausieren und klären, welche Seite die Bestellung steuert."],
["Veraltete Zeile präzise melden","Nenne Seite oder Kategorie, Eingabe, Ziel, Quelltyp, erwartete ID, beobachtete Identität und Datum. Beschreibe den Unterschied ohne Ursache zu erfinden. Wenn nur eine Option fehlt, melde genau diese Option.","Keine Logins, privaten Bestelldaten oder unbelegten Verkäuferanschuldigungen. Ein Ersatz ist ein neuer Datensatz mit eigener ID, Quelle, Optionen und Datum, nicht automatisch eine Fortsetzung."],
["Mit einer Entscheidung enden","Ergebnis ist weiter, fragen, sperren oder entfernen. Weiter nur bei übereinstimmender Identität, Zielseite und Option; fragen bei einer klar benannten Lücke; sperren bei unprüfbarer Route; entfernen bei falschem Produkt.","Das ist keine Qualitätsrangliste. Die Methode macht den Datensatz reproduzierbar, speichert Belege mit Datum und verlangt vor Zahlung eine erneute Prüfung."]]),
es:make("ID de producto, enlace fuente y URL de destino Joyagoo: qué resuelve cada identificador","Usa cada identificador Joyagoo para comparar, reabrir o informar un hallazgo sin convertirlo en prueba de calidad o disponibilidad.","La página de destino y el pedido activo mandan. Un identificador localiza un registro; no congela stock, opciones, precio ni rendimiento del vendedor.",["El ID compara registros","El enlace conserva el contexto","La URL muestra la ruta actual","Las redirecciones exigen revisar identidad","Guarda los tres con fecha"],[
["Tres campos y tres trabajos","El ID sirve para saber si dos registros apuntan al mismo anuncio; el enlace fuente conserva mercado, vendedor y opciones; la URL final registra dónde llega hoy el comprador. Separarlos evita usar un campo como prueba de algo distinto.","Ninguno demuestra stock, calidad o idoneidad. Un ID puede estar retirado, un enlace puede redirigir y un destino puede cambiar opciones. Elige el campo según la pregunta y verifica los datos comerciales en vivo."],
["Usar el ID para comparar","Extrae el token real del artículo, no un número de campaña. Compáralo entre hoja, fuente final y destino. Coincidencia refuerza la identidad; diferencia obliga a detenerse y explicarla.","El ID no es certificado: la misma página puede cambiar colores, tallas y texto, y un producto similar puede tener otro ID. Registra también el tipo de fuente y úsalo solo para igualdad e informes."],
["Conservar el enlace fuente","Guarda el contexto del vendedor, título, imágenes, selector, reglas de cantidad y entrega nacional. Usa la versión más limpia accesible y fecha; si necesita sesión, anota la limitación sin inventar campos.","Sirve para rastrear un modelo, color o tabla, pero sigue siendo contenido de un tercero. No implica aval ni garantiza que el destino reproduzca todos los datos."],
["Reproducir la URL final","Guarda la dirección después de redirecciones y compara título, imagen, tipo, identidad y opciones. Un 200 no basta si la página ya muestra otro producto.","Conserva entrada y salida para reproducir el fallo. No sustituyas silenciosamente por un anuncio parecido manteniendo ID, miniatura o fecha anteriores."],
["Limpiar sin borrar pruebas","Conserva primero la ruta original. Quita referencias, idioma o campañas uno a uno y confirma que producto y contexto no cambian. No elimines el parámetro que contiene la identidad.","No publiques tokens, direcciones o sesiones privadas. Normalmente bastan mercado, ID, fuente, destino, opción y fecha; los datos de cuenta quedan en el archivo personal."],
["Registrar redirecciones","Anota URL inicial, final, fecha y resultado: coincide, parcial, no coincide o no disponible. Parcial significa que falta reconciliar opción o vendedor; no coincide es otro producto o página genérica.","Separa estado de red e identidad. Una redirección viva al artículo equivocado es peligrosa. Revisa título, imagen, tipo, vendedor y opciones y suspende lo incierto."],
["Elegir por la pregunta","Para '¿es el mismo anuncio?', fuente más ID. Para texto o talla, enlace fuente. Para ruta actual, URL final. Para color, talla, versión o cantidad, opción en vivo. El número de pedido solo identifica una transacción existente.","Añade pregunta, campo controlador y prueba. Así una imagen no oculta un conflicto de ID y un enlace no responde por sí solo a una duda de variante."],
["Crear un paquete compacto","Guarda fila, mercado, ID, fuente limpia, destino inicial y final, título, opción y fecha. Describe la redirección. En pedidos DIY, separa los campos del comprador y sigue las instrucciones actuales.","Antes de pagar, reabre y compara identidad, color, talla, versión, cantidad y nota. Si fuente y destino chocan, pausa y pregunta cuál controla el pedido."],
["Informar una fila obsoleta","Indica hoja, fila o categoría, entrada, final, fuente, ID esperado, identidad vista y fecha. Describe el hecho sin adivinar la causa. Si falta una opción, nómbrala.","No incluyas login, pedido privado ni acusaciones sin pruebas. Un reemplazo es un registro nuevo con su propio ID, fuente, opciones y fecha."],
["Cerrar con decisión","Elige continuar, preguntar, suspender o quitar. Continúa solo con identidad, destino y opción coherentes; pregunta por una laguna concreta; suspende lo no evaluable; quita el producto incorrecto.","No es una recomendación de calidad. Es un método reproducible con fecha y nueva comprobación antes del pago."]]),
fr:make("Identifiant produit, lien source et URL de destination Joyagoo : quel champ pour quel problème ?","Attribuez à chaque identifiant Joyagoo son vrai rôle pour comparer, rouvrir ou signaler un résultat sans prétendre prouver qualité ou disponibilité.","La destination en direct et la commande active font foi. Un identifiant retrouve un enregistrement sans figer stock, options, prix ou vendeur.",["L'ID rapproche les fiches","Le lien garde le contexte vendeur","L'URL montre le chemin actuel","Une redirection impose un contrôle","Conservez les trois avec la date"],[
["Trois champs, trois rôles","L'ID indique si deux fiches visent le même listing, le lien source conserve marché, vendeur et options, l'URL finale montre où arrive le visiteur. Les séparer évite d'exiger d'un champ une preuve qu'il ne fournit pas.","Aucun ne prouve stock, qualité ou adéquation. Une ID peut être retirée, un lien rediriger et une destination changer. Choisissez selon la question et confirmez les faits commerciaux en direct."],
["Comparer avec l'ID","Extrayez le vrai jeton article, pas un numéro de campagne. Comparez feuille, source finale et destination. Un accord renforce l'identité ; un écart exige arrêt et explication.","L'ID n'est pas un certificat : options et description peuvent évoluer. Notez aussi le type de source et limitez son usage à l'égalité et au signalement."],
["Préserver le lien source","Il garde titre, images, vendeur, sélecteur, quantité et livraison intérieure. Sauvegardez la version accessible la plus propre avec date ; si une session est requise, notez la limite.","Il retrace modèle, couleur ou taille, mais reste un contenu tiers. Il n'implique pas d'approbation et ne garantit pas la reproduction de tous les champs."],
["Reproduire l'URL finale","Conservez l'adresse après redirections et comparez titre, image, type, identité et options. Un code 200 ne suffit pas si le contenu est devenu autre.","Gardez entrée et sortie ensemble. Ne remplacez pas silencieusement par une fiche similaire sous l'ancien ID, image ou date."],
["Nettoyer sans perdre la preuve","Sauvegardez d'abord le trajet original. Retirez campagne, langue ou référence un élément à la fois et vérifiez le même produit. Ne retirez jamais le paramètre d'identité.","Ne publiez pas jetons, adresses ou sessions. Marché, ID, source, destination, option et date suffisent généralement ; les données privées restent chez l'acheteur."],
["Tenir un registre des redirections","Notez URL d'entrée, finale, date et résultat : correspondance, partiel, faux ou indisponible. Partiel signifie qu'une option ou un vendeur reste à résoudre.","Séparez réseau et produit. Une redirection active vers le mauvais article est trompeuse. Vérifiez titre, image, type, vendeur et options et suspendez l'incertain."],
["Choisir selon la question","Même listing : source plus ID. Texte vendeur ou taille : lien source. Chemin actuel : URL finale. Couleur, taille, version, quantité : option en direct. Le numéro de commande vient après transaction.","Une colonne question, champ directeur et preuve empêche une image de masquer un conflit d'ID ou un lien de répondre à tort sur la variante."],
["Former un paquet compact","Gardez ligne, marché, ID, source propre, destination initiale et finale, titre, option et date. Décrivez la redirection. Pour DIY, séparez les champs fournis par l'acheteur.","Avant paiement, rouvrir et comparer identité puis options. Si source et destination divergent, mettre en pause et demander laquelle pilote la commande."],
["Signaler précisément","Indiquez page, ligne, entrée, finale, source, ID attendu, identité observée et date. Décrivez sans inventer la cause ; si une option manque, nommez-la.","Pas de connexion, commande privée ni accusation. Un remplacement devient une nouvelle fiche avec ID, source, options et date propres."],
["Finir par une décision","Continuer, demander, suspendre ou retirer. Continuer si identité, destination et option concordent ; demander pour une lacune nommée ; suspendre si invérifiable ; retirer si autre produit.","Ce n'est pas un classement qualité. C'est un dossier reproductible, daté et revérifié avant paiement."]]),
it:make("ID prodotto, link sorgente e URL di destinazione Joyagoo: quale identificatore risolve quale problema","Usa ogni identificatore Joyagoo per confrontare, riaprire o segnalare un prodotto senza trattarlo come prova di qualità o disponibilità.","La destinazione live e l'ordine corrente controllano la decisione. Un identificatore trova un record, ma non blocca stock, opzioni, prezzo o venditore.",["L'ID confronta i record","Il link conserva il contesto","L'URL mostra il percorso attuale","I redirect richiedono verifica","Salva tutti e tre con data"],[
["Tre campi, tre compiti","L'ID verifica se due record indicano lo stesso listing; il link sorgente conserva mercato, venditore e opzioni; l'URL finale mostra dove arriva oggi l'utente. Colonne separate evitano prove improprie.","Nessuno prova stock, qualità o idoneità. Un ID può essere rimosso, un link reindirizzare e una pagina cambiare opzioni. Scegli il campo in base alla domanda e controlla i dati live."],
["Usare l'ID per confrontare","Estrai il token articolo reale e non un numero di campagna. Confronta foglio, sorgente finale e destinazione. Corrispondenza rafforza l'identità; differenza impone pausa.","L'ID non è certificazione: opzioni e descrizione possono cambiare. Registra anche il tipo di sorgente e usalo solo per uguaglianza e segnalazione."],
["Conservare il link sorgente","Mantiene titolo, immagini, venditore, selettore, quantità e consegna nazionale. Salva la versione pulita accessibile con data; se serve una sessione, annota il limite.","È utile per modello, colore e tabella taglie, ma resta contenuto del venditore. Non implica approvazione né garantisce tutti i campi nel percorso destinazione."],
["Riprodurre l'URL finale","Salva l'indirizzo dopo i redirect e confronta titolo, immagine, tipo, identità e opzioni. Una risposta 200 non basta se il prodotto è cambiato.","Conserva input e finale insieme. Non sostituire in silenzio con un listing simile mantenendo vecchi ID, immagine o data."],
["Pulire senza perdere prova","Salva prima il percorso originale. Rimuovi referral, lingua o campagne uno alla volta e conferma che prodotto e contesto restino uguali. Non rimuovere il parametro identità.","Non pubblicare token, indirizzi o sessioni. Di solito bastano mercato, ID, sorgente, destinazione, opzione e data; i dati privati restano nel record personale."],
["Registrare i redirect","Annota URL iniziale, finale, data e risultato: corrisponde, parziale, errato o non disponibile. Parziale segnala opzione o venditore non conciliati; errato è altro prodotto.","Separa rete e identità. Un redirect vivo al prodotto sbagliato è pericoloso. Controlla titolo, immagine, tipo, venditore e opzioni e sospendi l'incerto."],
["Scegliere in base alla domanda","Stesso listing: sorgente più ID. Testo o taglia: link sorgente. Percorso attuale: URL finale. Colore, taglia, versione e quantità: opzione live. Il numero d'ordine identifica la transazione.","Colonne per domanda, campo di controllo e prova impediscono a un'immagine di superare un conflitto ID o a un link di risolvere la variante."],
["Creare un pacchetto compatto","Salva riga, mercato, ID, sorgente pulita, destinazione iniziale e finale, titolo, opzione e data. Descrivi il redirect. Per DIY separa i campi forniti dall'acquirente.","Prima del pagamento riapri e confronta identità e opzioni. Se sorgente e destinazione divergono, fermati e chiedi quale controlla l'ordine."],
["Segnalare con precisione","Indica pagina, riga, input, finale, sorgente, ID atteso, identità osservata e data. Descrivi il fatto senza inventare la causa; nomina l'opzione mancante.","Niente login, ordini privati o accuse. Un sostituto è un nuovo record con ID, sorgente, opzioni e data propri."],
["Chiudere con una decisione","Procedi, chiedi, sospendi o rimuovi. Procedi con identità, destinazione e opzione coerenti; chiedi per una lacuna; sospendi se non valutabile; rimuovi se altro prodotto.","Non è una classifica di qualità. È un metodo riproducibile e datato, da ripetere prima del pagamento."]])
};
