import type {SeoArticle} from "./seo-articles";
import type {Lang} from "./site-data";

export const listingConsistencyArticle:SeoArticle={
slug:"joyagoo-title-thumbnail-destination-consistency-check",
title:"Joyagoo Listing Checks: Match the Title, Thumbnail and Destination Before Shortlisting",
description:"Use a repeatable Joyagoo listing check to catch mismatched titles, reused thumbnails, redirects and changed destinations before a product enters your shortlist.",
meta:"LISTING CONSISTENCY · 15 MIN",
sourceNote:"Method and platform scope checked September 4, 2026. The current destination page and order screen control the decision; an index image or saved title is only dated discovery evidence.",
quickFacts:["Match meaning, not just words","Treat thumbnails as locators","Inspect the final destination","Write down every contradiction","Shortlist only decision-ready records"],
sections:[
{heading:"Why three-way consistency matters",paragraphs:["A Joyagoo spreadsheet row normally offers at least three clues: a saved title, a thumbnail and a destination link. Those clues can make discovery fast, but none is independently strong enough to confirm the current listing. Titles are shortened, images are reused and links can redirect after a seller edits or replaces a page. The safest shortlist rule is simple: all three clues must still describe the same product family, and the live destination must contain the option the buyer intends to order.","This is an identity check, not a quality review. Agreement does not prove authenticity, workmanship, inventory or seller reliability. It proves only that the discovery record still leads to a page that appears to represent the same item. That narrower conclusion is useful: it stops a buyer from spending time comparing measurements, colors or QC requests for a listing that already fails at the first factual gate."]},
{heading:"Start with the title's product meaning",paragraphs:["Read the saved title as a description of product type, model or defining feature, not as an exact string that must survive translation. Remove promotional phrases and isolate the nouns and attributes that make the item distinct: jacket rather than shirt, zip closure rather than pullover, low-top rather than boot, single unit rather than set. Then read the destination title and option labels. A harmless wording change can still match; a change in product class cannot.","Mark the result as match, partial or conflict. Match means the essential product meaning agrees. Partial means the page may be related but omits a decisive feature or mixes several products. Conflict means the destination title describes a different item. Do not let a familiar brand word or seller name outweigh a product-class conflict. A spreadsheet needs the exact transaction candidate, not merely another page from the same shop."]},
{heading:"Use the thumbnail as a locator, not proof",paragraphs:["Compare the saved thumbnail with the destination's main image and the image attached to the intended option. Look for silhouette, closure, panel layout, color blocking, included pieces and other stable visual features. A crop, background or model can change without breaking identity. A different sole shape, pocket layout, number of pieces or accessory set is more serious because it can indicate that the row now reaches another product or option.","Never treat a visual match as proof of authenticity or condition. Sellers can reuse catalog images, and a thumbnail may show only the most attractive option. Its job is to help detect obvious inconsistency. If the title and product ID disagree while the image looks similar, the disagreement wins. Save the image comparison as supporting evidence, then rely on the live option text and order summary for the purchase instruction."]},
{heading:"Follow the link to its final destination",paragraphs:["Open the row in a clean session when possible and record both the input address and the final address after redirects. A network success only proves that something loaded. Check whether the final page is a product detail, a search result, a shop home, a login wall or an unrelated item. Compare the marketplace, seller context and product identifier with the values already saved in the row.","If the destination cannot be evaluated, label it unavailable rather than matched. If it resolves to a generic page, the row has lost its precise buying target even if the page is technically live. A redirect to a replacement listing must be reviewed as a new candidate with its own title, thumbnail, identifier, options and check date. Do not inherit the old row's confidence automatically."]},
{heading:"Check the selected option, not only the default view",paragraphs:["A destination may represent the correct product family while the intended color, size, version or quantity has disappeared. Select the planned option and watch whether the image, title fragment, displayed price or stock message changes. Joyagoo's current shopping guidance instructs buyers to choose color, size and quantity before adding or paying, so the consistency review must reach that same option level rather than stopping at the page header.","Copy the exact visible option text into the shortlist. Avoid translating or normalizing it until the original has been saved, because two similar labels may refer to different versions. When an option changes the image to a visibly different product, record that relationship. If the required choice is missing or ambiguous, the listing is partial, not ready, regardless of how well the default thumbnail matches."]},
{heading:"Use a contradiction ledger",paragraphs:["Create four columns: field, index evidence, destination evidence and decision. Enter product type, title meaning, thumbnail features, product ID, seller context and intended option. Agreement can be marked confirmed for identity; a missing value stays open; a genuine conflict receives a stop flag. Add the check date and final URL so another editor or buyer can reproduce the result instead of relying on memory.","Contradictions should be written literally. 'Index says two-piece set; destination title and option show one bag' is useful. 'Looks wrong' is not. Do not invent the cause: the seller may have edited a page, the index may be stale or the redirect may be faulty. The ledger's purpose is to locate the difference and decide whether the row can proceed, not to accuse a party without evidence."]},
{heading:"Apply a shortlisting decision tree",paragraphs:["Proceed when title meaning, destination identity and the required option agree, while the thumbnail contains no material contradiction. Ask for review when exactly one noncritical field is unclear and the final page remains stable. Suspend the row when the destination cannot be evaluated or redirects inconsistently. Remove it from active discovery when the final page is a different product, the controlling identifier conflicts or the intended option no longer exists.","This decision tree prevents weak records from competing with well-documented candidates. It also avoids unsupported 'best product' rankings. A row can be more decision-ready because its evidence is complete without claiming that its product is better made. When two candidates both pass, compare their listing details in a separate worksheet; do not turn the consistency check into a price, seller or quality verdict."]},
{heading:"Work through a concrete example",paragraphs:["Imagine an index row titled 'black zip hoodie' with a front image showing a full zip and two pockets. The final page now says 'pullover sweatshirt.' Its default image still resembles the saved thumbnail, but the option list contains only pullover colors and no zip version. Product family overlaps, yet the defining closure and intended option conflict. The correct result is remove or suspend, not shortlist.","Now consider a row titled 'grey running shoe' whose destination uses a translated title, a new studio background and the same source identifier. The selected grey option shows the same sole geometry and size range, while the live page clearly presents a single pair. That record can pass the identity gate, with the new final URL and check date saved. The method accepts harmless presentation changes while rejecting transactional differences."]},
{heading:"Recheck at the handoff to ordering",paragraphs:["A shortlist is dated evidence, not a reservation. Reopen the destination immediately before transferring the link or selecting the item in the live Joyagoo workflow. Compare product identity and the exact color, size and quantity with the saved record and the order summary. If the platform cannot retrieve the source normally, follow only current official DIY instructions and treat every manually entered detail as buyer-supplied information that requires an extra review.","Take a fresh decision snapshot: final URL, option labels, quantity, visible product-stage price and China domestic-freight field if shown. These commercial details are outside the narrow title-thumbnail test, but they determine whether the already-matched candidate is ready for payment. A consistency pass from yesterday cannot justify ignoring a changed option or price today."]},
{heading:"Keep the index useful after a failure",paragraphs:["When a row fails, record whether the problem was title conflict, thumbnail conflict, destination redirect, missing option or unavailable page. Send a stale-listing report with the row location, input URL, final URL, expected identity, observed identity and date. Exclude login tokens, private order details and unsupported seller claims. A precise report lets an editor reproduce and correct the route without exposing buyer data.","Only restore the row after a complete new pass. A replacement URL receives its own product ID, title snapshot, thumbnail check, option record and verification date. The final output is one of four clear actions—shortlist, review, suspend or remove. That is the value of Joyagoo listing checks: they turn three imperfect discovery clues into a documented pre-purchase decision without promising anything the evidence cannot prove."]}
]};

const make=(lang:Lang,title:string,description:string,sourceNote:string,facts:string[],rows:[string,string,string][]):SeoArticle=>({slug:listingConsistencyArticle.slug,title,description,meta:{de:"LISTING-ABGLEICH · 15 MIN",es:"COHERENCIA DEL ANUNCIO · 15 MIN",fr:"COHÉRENCE DE L’ANNONCE · 15 MIN",it:"COERENZA INSERZIONE · 15 MIN",en:"LISTING CONSISTENCY · 15 MIN"}[lang],sourceNote,quickFacts:facts,sections:rows.map(([heading,a,b])=>({heading,paragraphs:[a,b]}))});

export const listingConsistencyTranslations:Partial<Record<Lang,SeoArticle>>={
de:make("de","Joyagoo-Listing prüfen: Titel, Vorschaubild und Zielseite vor der Auswahl abgleichen","Mit einem wiederholbaren Joyagoo-Listing-Check erkennst du widersprüchliche Titel, wiederverwendete Bilder, Weiterleitungen und geänderte Zielseiten vor der Shortlist.","Methode und Plattformumfang am 4. September 2026 geprüft. Live-Zielseite und Bestellansicht entscheiden; Titel und Bild im Index sind nur datierte Entdeckungsbelege.",["Bedeutung statt Wortlaut vergleichen","Vorschaubild nur als Wegweiser nutzen","Endgültige Zielseite prüfen","Jeden Widerspruch notieren","Nur entscheidungsreife Datensätze auswählen"],[
["Warum der Dreifachabgleich zählt","Eine Tabellenzeile liefert meist Titel, Bild und Zieladresse. Alle drei beschleunigen die Suche, doch keiner bestätigt allein das aktuelle Angebot: Titel werden gekürzt, Bilder wiederverwendet und Links umgeleitet. Für die Shortlist müssen alle Hinweise dieselbe Produktfamilie beschreiben, und die Live-Seite muss die gewünschte Option enthalten.","Das ist eine Identitäts-, keine Qualitätsprüfung. Übereinstimmung beweist weder Echtheit noch Verarbeitung, Bestand oder Verkäuferzuverlässigkeit. Sie zeigt nur, dass der Datensatz noch zum gleichen Kaufkandidaten führt und verhindert weitere Arbeit an einem bereits falsch zugeordneten Angebot."],
["Mit der Produktbedeutung des Titels beginnen","Lies den gespeicherten Titel nach Produkttyp, Modell und entscheidendem Merkmal. Entferne Werbung und isolierte Begriffe wie Jacke statt Shirt, Reißverschluss statt Pullover oder Einzelstück statt Set. Vergleiche anschließend Live-Titel und Optionen. Andere Übersetzung ist erlaubt, andere Produktklasse nicht.","Markiere Match, teilweise oder Konflikt. Match bedeutet gleiche Kernaussage; teilweise heißt, dass ein entscheidendes Merkmal fehlt; Konflikt bezeichnet ein anderes Produkt. Ein bekannter Marken- oder Shopname darf einen Konflikt der Produktklasse nicht überstimmen."],
["Das Bild als Wegweiser nutzen","Vergleiche gespeichertes Bild, Hauptbild und Bild der gewünschten Option anhand von Silhouette, Verschluss, Paneelen, Farben und Zubehör. Hintergrund oder Zuschnitt dürfen variieren; andere Sohle, Taschen, Stückzahl oder Teile können auf ein anderes Produkt hinweisen.","Ein Bild beweist keine Echtheit oder Qualität. Katalogbilder können mehrfach genutzt werden und oft nur eine Option zeigen. Bei Konflikt zwischen Bild, Titel und ID gewinnt der Konflikt. Live-Optionstext und Bestellübersicht steuern die Anweisung."],
["Bis zur endgültigen Zielseite folgen","Speichere Eingabe- und Endadresse nach Weiterleitungen. HTTP-Erfolg sagt nur, dass etwas lädt. Prüfe, ob die Seite ein Produktdetail, eine Suche, einen Shop, Login oder fremden Artikel zeigt, und gleiche Marktplatz, Verkäuferkontext und ID ab.","Nicht prüfbare Ziele heißen nicht verfügbar, nicht passend. Eine generische Seite hat das genaue Kaufziel verloren. Eine Ersatzweiterleitung wird als neuer Kandidat mit eigenem Titel, Bild, ID, Optionen und Datum geprüft; alte Sicherheit wird nicht übernommen."],
["Die gewählte Option kontrollieren","Die Produktfamilie kann stimmen, während Farbe, Größe, Version oder Menge verschwunden ist. Wähle die geplante Option und beobachte Bild, Titelteil, Preis und Bestand. Die aktuelle Joyagoo-Anleitung verlangt Farbe, Größe und Menge vor dem Hinzufügen oder Bezahlen; die Prüfung muss daher bis auf diese Ebene gehen.","Speichere den sichtbaren Originaltext der Option vor einer Übersetzung. Ähnliche Bezeichnungen können verschiedene Versionen meinen. Ändert die Option das Bild zu einem anderen Produkt, notiere es. Fehlende oder unklare Auswahl macht den Datensatz teilweise statt bestellbereit."],
["Ein Widerspruchsprotokoll führen","Nutze Feld, Indexbeleg, Zielbeleg und Entscheidung für Produkttyp, Titelbedeutung, Bildmerkmale, ID, Verkäufer und Option. Übereinstimmung bestätigt nur die Identität; fehlend bleibt offen; echter Konflikt stoppt. Datum und finale URL machen die Prüfung reproduzierbar.","Schreibe Unterschiede wörtlich: „Index nennt Zweier-Set, Zielseite zeigt eine Tasche“. „Sieht falsch aus“ hilft nicht. Erfinde keine Ursache. Das Protokoll lokalisiert die Abweichung und entscheidet über die Zeile, ohne unbelegte Vorwürfe."],
["Einen Entscheidungsbaum anwenden","Weiter nur, wenn Titelbedeutung, Zielidentität und Option stimmen und das Bild nicht materiell widerspricht. Prüfen lassen bei genau einer unkritischen Lücke. Sperren bei nicht bewertbarer oder wechselnder Weiterleitung. Entfernen bei anderem Produkt, ID-Konflikt oder entfallener Option.","So konkurrieren schwache Datensätze nicht mit dokumentierten Kandidaten. Entscheidungsreife ist keine „beste Produkt“-Rangliste. Wenn zwei Angebote bestehen, vergleiche Details separat und mache aus dem Identitätscheck kein Preis-, Verkäufer- oder Qualitätsurteil."],
["Ein konkretes Beispiel","Eine Zeile „schwarzer Zip-Hoodie“ zeigt Reißverschluss und zwei Taschen, das Ziel heißt aber Pullover und bietet keine Zip-Option. Produktfamilie ähnlich, doch Verschluss und gewünschte Option widersprechen. Ergebnis: sperren oder entfernen, nicht auswählen.","Bei einem „grauen Laufschuh“ können Übersetzung und Hintergrund wechseln. Gleiche Quell-ID, gleiche Sohlengeometrie, graue Option und passender Größenbereich erlauben den Identitäts-Pass. Speichere neue URL und Datum: harmlose Darstellung ändert sich, die Transaktion nicht."],
["Vor Übergabe an die Bestellung erneut prüfen","Eine Shortlist reserviert nichts. Öffne das Ziel unmittelbar vor der Übertragung in Joyagoo und vergleiche Identität, Farbe, Größe und Menge mit Datensatz und Bestellübersicht. Bei DIY folge nur aktuellen offiziellen Hinweisen und prüfe alle manuell eingegebenen Käuferdaten zusätzlich.","Speichere Endadresse, Optionen, Menge, sichtbaren Produktpreis und China-Inlandsversand, falls angezeigt. Diese Felder liegen außerhalb des engen Bild-Titel-Tests, entscheiden aber über Zahlungsreife. Ein gestriger Pass rechtfertigt keine heute geänderte Option."],
["Den Index nach einem Fehler verbessern","Melde Titel-, Bild-, Weiterleitungs-, Options- oder Verfügbarkeitsfehler mit Zeile, Eingabe, Ziel, erwarteter und beobachteter Identität sowie Datum. Keine Logins, privaten Bestellungen oder unbelegten Verkäuferbehauptungen. So kann die Redaktion den Fehler reproduzieren.","Stelle die Zeile erst nach komplettem neuen Durchlauf wieder her. Ein Ersatz erhält eigene ID, Titel, Bildprüfung, Optionen und Datum. Das Ergebnis lautet auswählen, prüfen, sperren oder entfernen—eine belegte Kaufvorentscheidung ohne falsches Versprechen."]]),
es:make("es","Comprobar un anuncio Joyagoo: título, miniatura y destino antes de preseleccionar","Usa una comprobación repetible del anuncio Joyagoo para detectar títulos contradictorios, miniaturas reutilizadas, redirecciones y destinos modificados.","Método y alcance comprobados el 4 de septiembre de 2026. La página final y el pedido activo controlan la decisión; título e imagen del índice son pruebas fechadas de descubrimiento.",["Compara significado, no palabras","Usa la miniatura como localizador","Examina el destino final","Registra cada contradicción","Preselecciona solo registros listos"],[
["Por qué importa la coherencia triple","Una fila suele aportar título, miniatura y enlace. Agilizan el descubrimiento, pero ninguno confirma por sí solo el anuncio actual: los títulos se acortan, las imágenes se reutilizan y los enlaces cambian. Los tres deben describir la misma familia y el destino activo debe conservar la opción prevista.","Es una prueba de identidad, no de calidad. La coincidencia no demuestra autenticidad, fabricación, stock ni fiabilidad. Solo confirma que el registro aún lleva al mismo candidato y evita comparar medidas o preparar QC para una página ya equivocada."],
["Empezar por el significado del título","Lee tipo, modelo y atributo decisivo, sin frases promocionales: chaqueta y no camiseta, cremallera y no pulóver, unidad y no conjunto. Compara después título y opciones del destino. Una traducción distinta puede coincidir; otra clase de producto no.","Clasifica como coincide, parcial o conflicto. Parcial omite un rasgo decisivo; conflicto describe otro artículo. Una marca o tienda familiar no puede compensar un conflicto de tipo: la hoja necesita el candidato exacto."],
["Usar la miniatura como localizador","Compara miniatura, imagen principal e imagen de la opción por silueta, cierre, paneles, colores y piezas. Recorte o fondo pueden cambiar; otra suela, bolsillos, cantidad o accesorios pueden señalar un artículo diferente.","La imagen no prueba autenticidad ni estado. Puede ser un catálogo reutilizado y mostrar solo una opción. Si ID y título contradicen una foto parecida, manda la contradicción. El texto activo y el resumen del pedido controlan la compra."],
["Seguir hasta el destino final","Guarda dirección inicial y final tras redirecciones. Que algo cargue no basta: identifica si es ficha, búsqueda, tienda, acceso o artículo ajeno. Compara mercado, vendedor e ID con la fila guardada.","Un destino no evaluable queda no disponible, nunca coincidente. Una página genérica ha perdido el objetivo exacto. Un reemplazo se revisa como candidato nuevo con título, miniatura, ID, opciones y fecha propios."],
["Revisar la opción elegida","La familia puede coincidir aunque falten color, talla, versión o cantidad. Selecciona la opción prevista y observa imagen, fragmento de título, precio y disponibilidad. La guía actual de Joyagoo pide elegir color, talla y cantidad antes de añadir o pagar; la revisión debe llegar al mismo nivel.","Copia el texto original de la opción antes de traducirlo. Etiquetas similares pueden ser versiones distintas. Si al elegir cambia a otro producto, regístralo. Una opción ausente o ambigua deja la fila parcial, no lista."],
["Mantener un registro de contradicciones","Anota campo, prueba del índice, prueba del destino y decisión para tipo, título, imagen, ID, vendedor y opción. Coincidencia confirma solo identidad; ausencia queda abierta; conflicto detiene. Fecha y URL final permiten reproducirlo.","Describe literalmente: “índice dice conjunto de dos; destino muestra una bolsa”. “Parece mal” no sirve. No inventes la causa. El registro localiza la diferencia y decide sin acusaciones sin prueba."],
["Aplicar un árbol de decisión","Continúa cuando significado, identidad final y opción coinciden sin contradicción visual importante. Revisa si falta un dato no crítico. Suspende si el destino no puede evaluarse o cambia. Retira si es otro producto, el ID contradice o desapareció la opción.","Así los registros débiles no compiten con candidatos documentados. Estar listo no significa ser el mejor producto. Compara después los detalles en otra hoja sin convertir esta prueba en veredicto de precio, vendedor o calidad."],
["Ejemplo concreto","Una fila “sudadera negra con cremallera” muestra cierre completo y dos bolsillos, pero el destino dice pulóver y no ofrece cierre. Aunque la familia se parece, cierre y opción chocan: suspender o retirar, no preseleccionar.","Un “zapato gris para correr” puede tener título traducido y fondo nuevo. Si coinciden ID, geometría de suela, opción gris y tallas, pasa identidad. Guarda URL y fecha nuevas: acepta cambios de presentación, no diferencias transaccionales."],
["Volver a revisar al pedir","La preselección no reserva nada. Reabre justo antes de transferir a Joyagoo y compara identidad, color, talla y cantidad con registro y resumen. Si requiere DIY, sigue solo instrucciones oficiales actuales y revisa cada dato manual del comprador.","Guarda URL, opciones, cantidad, precio visible y transporte nacional si aparece. Quedan fuera del test estrecho de título e imagen, pero deciden si puede pagarse. Una revisión de ayer no valida un cambio de hoy."],
["Mejorar el índice después de un fallo","Informa si falló título, imagen, redirección, opción o disponibilidad con fila, URL inicial/final, identidad esperada/observada y fecha. Sin tokens, pedidos privados ni acusaciones. El editor podrá reproducirlo.","Restaura solo tras repetir todo. Un reemplazo recibe ID, título, miniatura, opciones y fecha propios. El resultado final es preseleccionar, revisar, suspender o retirar: una decisión documentada sin garantías falsas."]]),
fr:make("fr","Contrôle d’une annonce Joyagoo : titre, miniature et destination avant sélection","Utilisez un contrôle répétable pour repérer titres contradictoires, miniatures réutilisées, redirections et destinations modifiées avant la sélection.","Méthode et périmètre contrôlés le 4 septembre 2026. La destination et la commande actives décident ; titre et image de l’index sont des preuves de découverte datées.",["Comparer le sens, pas les mots","Traiter l’image comme repère","Inspecter la destination finale","Noter chaque contradiction","Ne retenir que les dossiers prêts"],[
["Pourquoi le triple accord compte","Une ligne fournit souvent titre, miniature et lien. Ils accélèrent la découverte mais aucun ne confirme seul l’annonce actuelle : titres raccourcis, images réutilisées, liens redirigés. Les trois doivent encore décrire la même famille et la page active doit proposer l’option voulue.","C’est un contrôle d’identité, non de qualité. L’accord ne prouve ni authenticité, fabrication, stock ou fiabilité. Il montre seulement que le dossier mène encore au même candidat et évite de travailler sur une annonce déjà incohérente."],
["Commencer par le sens du titre","Isolez type, modèle et attribut décisif sans promotion : veste plutôt que t-shirt, fermeture plutôt que pull, unité plutôt qu’ensemble. Comparez ensuite titre et options actifs. Une traduction différente peut correspondre ; une autre classe de produit, non.","Classez accord, partiel ou conflit. Partiel omet un élément décisif ; conflit décrit un autre article. Une marque ou boutique familière ne doit jamais effacer un conflit de catégorie."],
["Employer la miniature comme repère","Comparez miniature, image principale et image d’option selon silhouette, fermeture, panneaux, couleurs et pièces. Recadrage ou décor peuvent varier ; semelle, poches, quantité ou accessoires différents signalent un risque d’autre produit.","L’image ne prouve pas authenticité ou état. Elle peut être réutilisée et ne montrer qu’une option. Si ID et titre contredisent une image similaire, le conflit l’emporte. Texte actif et résumé de commande pilotent l’achat."],
["Suivre jusqu’à la destination finale","Conservez adresse d’entrée et adresse après redirections. Un chargement réussi ne suffit pas : distinguez fiche, recherche, boutique, connexion ou produit sans rapport, puis comparez marché, vendeur et ID.","Une page non évaluable reste indisponible. Une page générique a perdu la cible exacte. Un remplacement devient un nouveau candidat avec son propre titre, image, ID, options et date, sans hériter de l’ancienne confiance."],
["Contrôler l’option choisie","La famille peut correspondre alors que couleur, taille, version ou quantité a disparu. Sélectionnez l’option et observez image, titre, prix et disponibilité. Le guide Joyagoo actuel demande couleur, taille et quantité avant ajout ou paiement ; le contrôle doit aller aussi loin.","Copiez le libellé original avant traduction. Des mots proches peuvent désigner des versions distinctes. Si l’option change l’image vers un autre produit, notez-le. Une option absente ou ambiguë rend le dossier partiel."],
["Tenir un registre des contradictions","Utilisez champ, preuve index, preuve destination et décision pour type, sens du titre, image, ID, vendeur et option. Accord confirme seulement l’identité ; absence reste ouverte ; conflit bloque. Date et URL finale rendent le test reproductible.","Écrivez la différence : « index : lot de deux ; destination : un sac ». « Semble faux » n’aide pas. N’inventez pas la cause. Le registre localise l’écart et décide sans accusation non prouvée."],
["Appliquer un arbre de décision","Continuez si sens, identité finale et option concordent sans contradiction visuelle importante. Faites revoir une seule lacune non critique. Suspendez une page instable ou impossible à évaluer. Retirez autre produit, ID contradictoire ou option supprimée.","Ainsi, les dossiers faibles ne rivalisent pas avec les candidats documentés. Prêt à décider ne veut pas dire « meilleur produit ». Comparez les détails ailleurs sans transformer ce contrôle en verdict de prix, vendeur ou qualité."],
["Exemple concret","Une ligne « hoodie noir zippé » montre zip intégral et deux poches, mais la destination dit pull et n’offre aucun zip. La famille est proche, mais fermeture et option se contredisent : suspendre ou retirer.","Pour une « chaussure running grise », traduction et décor peuvent changer. Même ID, même semelle, option grise et tailles compatibles autorisent le passage. Sauvegardez URL et date : changements de présentation acceptés, différences transactionnelles refusées."],
["Revérifier au passage en commande","Une sélection ne réserve rien. Rouvrez juste avant le transfert dans Joyagoo et comparez identité, couleur, taille et quantité au dossier et au résumé. Pour DIY, suivez seulement l’aide officielle actuelle et revérifiez chaque champ saisi manuellement.","Sauvegardez URL, options, quantité, prix produit visible et livraison intérieure si affichée. Hors du test titre-image, ces données déterminent le paiement. Un passage hier n’autorise pas à ignorer un changement aujourd’hui."],
["Améliorer l’index après échec","Signalez conflit de titre, image, redirection, option ou disponibilité avec ligne, URL d’entrée/finale, identité attendue/observée et date. Aucun jeton, commande privée ou accusation. L’éditeur peut reproduire.","Ne restaurez qu’après un nouveau contrôle complet. Un remplacement a son ID, titre, image, options et date. Résultat : retenir, revoir, suspendre ou retirer—une décision documentée sans promesse abusive."]]),
it:make("it","Controllo inserzione Joyagoo: titolo, miniatura e destinazione prima della selezione","Usa un controllo ripetibile per trovare titoli incoerenti, miniature riutilizzate, reindirizzamenti e destinazioni cambiate prima della shortlist.","Metodo e ambito controllati il 4 settembre 2026. La destinazione e l’ordine attivi decidono; titolo e immagine dell’indice sono prove di scoperta datate.",["Confronta il significato","Usa l’immagine come indicatore","Controlla la destinazione finale","Registra ogni contraddizione","Seleziona solo record pronti"],[
["Perché serve la coerenza a tre","Una riga offre titolo, miniatura e link. Accelerano la ricerca ma nessuno conferma da solo l’inserzione corrente: titoli abbreviati, immagini riutilizzate e link deviati. Tutti devono descrivere la stessa famiglia e la pagina attiva deve contenere l’opzione voluta.","È un controllo d’identità, non di qualità. L’accordo non dimostra autenticità, lavorazione, stock o affidabilità. Conferma solo che il record porta ancora allo stesso candidato ed evita lavoro su una pagina già incoerente."],
["Partire dal significato del titolo","Isola tipo, modello e caratteristica decisiva senza promozioni: giacca non maglia, zip non pullover, unità non set. Confronta poi titolo e opzioni. Una traduzione diversa può coincidere; una diversa classe di prodotto no.","Classifica corrispondenza, parziale o conflitto. Parziale omette un elemento decisivo; conflitto descrive altro. Marca o negozio familiari non compensano un conflitto di categoria."],
["Usare la miniatura come indicatore","Confronta miniatura, immagine principale e opzione per sagoma, chiusure, pannelli, colori e pezzi. Sfondo o taglio possono cambiare; suola, tasche, quantità o accessori diversi possono segnalare un altro articolo.","L’immagine non prova autenticità o stato. Può essere riutilizzata e mostrare una sola variante. Se ID e titolo contraddicono una foto simile, vince il conflitto. Testo live e riepilogo ordine controllano l’acquisto."],
["Seguire la destinazione finale","Salva indirizzo iniziale e finale dopo i redirect. Il caricamento non basta: identifica scheda, ricerca, negozio, login o articolo estraneo e confronta mercato, venditore e ID.","Una pagina non valutabile resta non disponibile. Una pagina generica ha perso il bersaglio. Un sostituto è un nuovo candidato con titolo, immagine, ID, opzioni e data propri."],
["Controllare l’opzione scelta","La famiglia può coincidere mentre colore, taglia, versione o quantità manca. Seleziona l’opzione e osserva immagine, titolo, prezzo e disponibilità. La guida Joyagoo corrente richiede colore, taglia e quantità prima di aggiungere o pagare; il controllo deve arrivare lì.","Copia il testo originale prima di tradurre. Etichette simili possono indicare versioni diverse. Se l’opzione mostra un altro prodotto, registralo. Una scelta assente o ambigua rende il record parziale."],
["Tenere un registro dei conflitti","Usa campo, prova indice, prova destinazione e decisione per tipo, titolo, immagine, ID, venditore e opzione. Accordo conferma solo identità; assenza resta aperta; conflitto ferma. Data e URL finale rendono il test ripetibile.","Scrivi la differenza: “indice: set da due; destinazione: una borsa”. “Sembra sbagliato” non aiuta. Non inventare la causa: il registro individua lo scarto senza accuse."],
["Applicare un albero decisionale","Procedi se significato, identità finale e opzione coincidono senza contraddizione visiva importante. Revisiona una sola lacuna non critica. Sospendi se instabile o non valutabile. Rimuovi altro prodotto, ID opposto o opzione sparita.","Così i record deboli non competono con candidati documentati. Essere pronto non significa “migliore”. Confronta poi i dettagli altrove senza trasformare il test in verdetto di prezzo, venditore o qualità."],
["Esempio concreto","Una riga “felpa nera con zip” mostra zip intera e due tasche, ma il destino dice pullover e non ha zip. Famiglia simile, chiusura e opzione in conflitto: sospendere o rimuovere.","Per una “scarpa running grigia”, titolo tradotto e sfondo nuovo sono accettabili se ID, forma suola, opzione grigia e taglie coincidono. Salva URL e data: cambia la presentazione, non la transazione."],
["Ricontrollare prima dell’ordine","La shortlist non prenota nulla. Riapri prima di trasferire in Joyagoo e confronta identità, colore, taglia e quantità con record e riepilogo. Per DIY segui solo istruzioni ufficiali attuali e ricontrolla ogni dato manuale.","Salva URL, opzioni, quantità, prezzo visibile e trasporto nazionale se mostrato. Fuori dal test titolo-immagine, questi dati decidono il pagamento. Un controllo di ieri non copre una modifica di oggi."],
["Migliorare l’indice dopo un errore","Segnala titolo, immagine, redirect, opzione o disponibilità con riga, URL iniziale/finale, identità prevista/osservata e data. Niente token, ordini privati o accuse. L’editor può riprodurre.","Ripristina solo dopo un nuovo controllo completo. Il sostituto riceve ID, titolo, miniatura, opzioni e data propri. Esito: seleziona, revisiona, sospendi o rimuovi—decisione documentata senza garanzie false."]])
};
