import type {SeoArticle} from "./seo-articles";
import type {Lang} from "./site-data";

export const destinationListingArticle:SeoArticle={
slug:"joyagoo-destination-listing-verification-guide",title:"Verify the Exact Destination Listing Behind a Joyagoo Spreadsheet Find",description:"A precise Joyagoo product-link verification workflow for matching a spreadsheet row to the exact live destination listing before you shortlist or order.",meta:"PRODUCT-LINK VERIFICATION · 15 MIN",sourceNote:"Checked August 31, 2026. Joyagoo's public guidance accepts an original product link or product search, but the current destination page remains the evidence for identity, options and availability.",quickFacts:["Follow the final destination, not the label","Match identity with several signals","Record redirects and option changes","Never repair uncertainty by guessing","Stop when the exact listing cannot be proved"],sections:[
{heading:"Start with the final destination, not the spreadsheet label",paragraphs:["A spreadsheet row is a pointer. Its title, thumbnail and category can help you decide which link deserves attention, but they are not the transaction page. The first task in Joyagoo product-link verification is to open the row and identify the final destination that actually loads. Copy that complete address into a private working record before clicking other products, changing language or selecting an option. If the link passes through a redirect, preserve both the stored address and the final address.","This distinction matters because a readable spreadsheet title can remain unchanged while the destination is replaced, redirected or removed. A successful page load proves only that a server answered. It does not prove that the page still represents the intended item. Your verification question is narrower: does this exact final page still describe the same product family and the option that made the row relevant? If not, the find is not ready for a shortlist, even when its thumbnail still looks familiar."]},
{heading:"Build a six-field identity record before comparing details",paragraphs:["Record six fields together: final destination URL, marketplace or source host, visible product identifier, seller or shop identity when shown, product type, and the meaning of the current title. No single field is conclusive. A reused image may appear on several listings; a title may be generic; a seller may relist an item under a new identifier. Agreement across several independent fields gives stronger identity evidence than one attractive photo or one matching word.","Keep the source wording as well as your short English note. Translate for understanding, but do not replace model numbers, version codes, quantities or material terms with a guess. If a page exposes a stable item ID in the address or interface, save it exactly. If it does not, write ‘not visible’ rather than inventing one. The record should let another careful reader reopen the same page and understand why you considered it the destination behind that row."]},
{heading:"Compare the row and destination in a fixed order",paragraphs:["First compare product class: shoes should not land on a jacket, an accessory set should not become one replacement part, and an electronics model should not become a generic category. Next compare title meaning and the lead image. Then check identifier, seller context and option structure. A difference in photography can be harmless when the identifier and options agree; a matching thumbnail can be misleading when the destination title and ID point to another item.","Use three outcomes. A match means the product identity and intended option remain consistent. A partial match means the product family agrees but one decisive field—such as model, quantity, size system or included part—cannot be reconciled. A mismatch means the page is unrelated, dead, replaced or clearly a different item. A partial match is not permission to improvise. It creates a written question or a stop; a mismatch removes the row from the active shortlist."]},
{heading:"Treat redirects as evidence, not automatically as failure",paragraphs:["Redirects can be routine, but they change what must be checked. A link may move from a tracking wrapper to a marketplace page, from a mobile address to a canonical address, or from an expired listing to a shop or search page. Record each meaningful hop and inspect the final page. A mobile-to-desktop canonical change can preserve identity. A product-to-storefront redirect loses the exact destination and should not be treated as a verified product match.","Do not copy a product ID from the old address into a manual order merely because the new page looks similar. Confirm that the live page itself exposes the intended identity. If a marketplace asks for sign-in or blocks the detail view, mark the destination as not fully inspectable in your current session. Verification depends on observable evidence, not on what the link probably used to show. Try the current official Joyagoo link-entry flow, but stop if it cannot retrieve a definite listing."]},
{heading:"Verify the intended option on the destination page",paragraphs:["A correct product page can still be wrong for the intended order. Check the exact color, size, version and quantity that made the spreadsheet row useful. Read how options interact: selecting a color may change the image, price, stock message or available sizes. A low displayed amount can belong to the cheapest option, a deposit or a different quantity. Save the chosen option text exactly as displayed, plus the date and time checked.","For size-dependent products, preserve the seller's size system and measurements rather than translating a label into a familiar local size. For sets and accessories, identify how many pieces are included. For electronics, retain model, plug, voltage and connector details. The goal is not to cover every category in one record; it is to identify the field that could turn a correct product page into an incorrect purchase instruction."]},
{heading:"Separate current facts, snapshots and unanswered questions",paragraphs:["Give every important field one of four labels: confirmed on destination, shown only in spreadsheet, buyer assumption, or open question. Current destination facts can support the shortlist. Spreadsheet-only facts remain dated snapshots until the destination confirms them. Buyer assumptions should be eliminated or accepted consciously. Open questions need a specific answer before payment when the answer would change whether you order.","This method prevents quiet evidence drift. A thumbnail caption should not become a material claim; an old price should not become the expected checkout amount; a translated nickname should not become the seller's model designation. If a field changes during your session, keep the before-and-after record and use the later visible state. Do not overwrite the old observation as though it never existed, because that change explains why a previously saved find may no longer be usable."]},
{heading:"Use Joyagoo's current workflow without confusing roles",paragraphs:["Joyagoo's current public shopping guidance says buyers can paste an original product link or search by name or image, then choose product details such as color, size and quantity. That is the ordering interface receiving information from the source listing. It does not make an independent spreadsheet an official catalogue, freeze a seller page or guarantee that a retrieved result is the same item you intended.","After pasting the source link, compare the destination that Joyagoo presents with your six-field identity record. Check the item and options again before adding it to a cart or paying. If the interface cannot retrieve the page and a manual or DIY process is used, mark every entered field as buyer-supplied and attach the exact source evidence. A manually typed title is an instruction, not independent proof that the seller will interpret an ambiguous link as you intended."]},
{heading:"Create a useful mismatch report",paragraphs:["When a row fails, report the stored URL, final URL, check date, expected product identity, observed identity and mismatch type. Choose a precise reason: dead page, storefront redirect, unrelated replacement, missing option, changed quantity, changed model, inaccessible detail, or identifier conflict. Do not label a seller fraudulent or a product fake merely because a link changed. Link maintenance and product judgment are different questions.","A good report is reversible. An editor can reopen both addresses, reproduce the check and decide whether to repair, relabel or retire the row. If suggesting a replacement, submit it as a new candidate with its own identity record rather than silently swapping destinations beneath the old title and thumbnail. This protects the spreadsheet history and stops an old check date from being inherited by a page that was never actually reviewed."]},
{heading:"Run a final handoff check before shortlisting",paragraphs:["Before a candidate leaves research, read the final URL and identifier aloud against the working record. Confirm product type, seller context, exact option, quantity, required measurement or specification, and the date checked. Make sure the destination can be reopened from the saved address. If a different browser state produces a different result, document the condition instead of claiming a universal match.","Then apply a stop rule. Stop when the final destination is not a specific product page, the identity signals conflict, the intended option is absent, the identifier cannot be reconciled, or a decisive specification remains unknown. Proceed only when the exact destination and intended option are supported by current evidence. This is not a quality endorsement. It is a defensible statement that the spreadsheet row leads to the product page you mean to evaluate."]},
{heading:"Keep verification narrow enough to remain trustworthy",paragraphs:["Product-link verification answers identity and destination questions. It does not prove authenticity, construction quality, seller reliability, return eligibility, warehouse condition, route availability or final cost. Those decisions require their own current evidence at later stages. Keeping the scope narrow prevents a clean link match from becoming an unsupported promise about the transaction.","Save the completed record with its check date and review it again immediately before payment. Listings can change after an earlier successful check. A useful Joyagoo spreadsheet workflow therefore has two moments: editorial verification when the row is maintained, and buyer verification when the candidate is about to become an order. The durable result is not a permanent ‘verified’ badge; it is a reproducible identity check with a clear stop condition."]}
]};

const make=(title:string,description:string,sourceNote:string,quickFacts:string[],rows:[string,string,string][]):SeoArticle=>({slug:destinationListingArticle.slug,title,description,meta:"PRODUCT-LINK CHECK · 15 MIN",sourceNote,quickFacts,sections:rows.map(([heading,a,b])=>({heading,paragraphs:[a,b]}))});

export const destinationListingTranslations:Partial<Record<Lang,SeoArticle>>={
de:make("Exakte Zielseite hinter einem Joyagoo-Spreadsheet-Fund prüfen","Ein reproduzierbarer Ablauf, um Spreadsheet-Zeile und aktuelle Produktseite vor Auswahl oder Bestellung eindeutig abzugleichen.","Geprüft am 31. August 2026. Die öffentliche Anleitung akzeptiert Quelllinks; die aktuelle Zielseite bleibt der Identitätsnachweis.",["Endziel statt Linktext prüfen","Mehrere Identitätssignale verbinden","Umleitungen und Optionen protokollieren","Unklarheit nie erraten","Bei fehlendem Nachweis stoppen"],[
["Mit dem Endziel beginnen","Eine Spreadsheet-Zeile ist ein Wegweiser. Öffne sie, notiere die endgültig geladene Adresse und bewahre bei einer Umleitung sowohl Ausgangs- als auch Zieladresse auf. Titel, Vorschaubild und Kategorie sind nur Hinweise.","Ein erfolgreicher Seitenaufruf beweist nicht das richtige Produkt. Entscheidend ist, ob die endgültige Seite weiterhin dieselbe Produktfamilie und die benötigte Option zeigt. Andernfalls ist der Fund nicht auswahlbereit."],
["Sechs Identitätsfelder sichern","Speichere Ziel-URL, Quellplattform, sichtbare Produkt-ID, Verkäufer oder Shop, Produkttyp und Titelbedeutung. Mehrere übereinstimmende Felder sind stärker als ein einzelnes Bild oder Wort.","Bewahre Quellbegriffe neben deiner Übersetzung. Modelle, Versionen und Mengen dürfen nicht geraten werden. Ist keine ID sichtbar, notiere genau das, damit eine zweite Person deine Prüfung nachvollziehen kann."],
["In fester Reihenfolge vergleichen","Vergleiche zuerst Produktklasse, dann Titel und Leitbild, anschließend Kennung, Verkäuferkontext und Optionsstruktur. Andere Fotos können harmlos sein; gleiche Bilder können verschiedene Angebote verdecken.","Verwende Übereinstimmung, teilweise Übereinstimmung oder Widerspruch. Teilweise bedeutet konkrete Rückfrage oder Pause; Widerspruch entfernt die Zeile aus der aktiven Auswahl."],
["Umleitungen als Beleg behandeln","Mobile oder kanonische Umleitungen können die Identität erhalten. Eine Weiterleitung von einem Produkt zu einer Shop- oder Suchseite verliert dagegen das genaue Ziel. Halte wichtige Sprünge fest.","Übertrage keine alte ID in eine manuelle Bestellung. Wenn Anmeldung oder Sperre die Detailseite verhindert, markiere sie als nicht vollständig prüfbar und stoppe, falls auch der aktuelle Joyagoo-Ablauf kein bestimmtes Angebot liefert."],
["Die beabsichtigte Option prüfen","Auch die richtige Produktseite kann für die Bestellung falsch sein. Prüfe Farbe, Größe, Version und Menge sowie Änderungen von Bild, Preis oder Verfügbarkeit nach einer Auswahl.","Bewahre Größensystem und Maße, Stückzahl eines Sets oder Modell, Stecker und Spannung exakt. Das entscheidende Feld unterscheidet eine passende Zielseite von einer falschen Bestellanweisung."],
["Fakten und Fragen trennen","Kennzeichne jedes Feld als auf der Zielseite bestätigt, nur im Spreadsheet gezeigt, Käuferannahme oder offene Frage. Nur aktuelle Zielseitenbelege dürfen die Auswahl stützen.","So wird ein Bildtext nicht zur Materialzusage und ein alter Preis nicht zum erwarteten Checkout. Bei Änderungen speicherst du Vorher und Nachher, statt die frühere Beobachtung lautlos zu überschreiben."],
["Den offiziellen Ablauf richtig einordnen","Joyagoo beschreibt das Einfügen eines Quelllinks oder die Suche und danach die Wahl von Farbe, Größe und Menge. Das Bestellinterface übernimmt Daten; es macht das Spreadsheet nicht zum offiziellen Katalog.","Vergleiche die in Joyagoo angezeigte Seite erneut mit deinem Sechs-Felder-Datensatz. Bei manueller Eingabe bleiben alle Felder Käuferangaben und brauchen den genauen Quellbeleg."],
["Einen prüfbaren Fehlerbericht schreiben","Nenne gespeicherte und finale URL, Datum, erwartete und beobachtete Identität sowie den genauen Fehlertyp: tot, Shop-Umleitung, Ersatz, fehlende Option, andere Menge, Modell oder ID.","Ein Editor muss die Prüfung wiederholen können. Ein Ersatzlink ist ein neuer Kandidat mit eigener Identitätsprüfung und darf nicht lautlos unter alten Bildern und Daten eingetragen werden."],
["Vor der Auswahl final prüfen","Lies URL und ID gegen den Datensatz. Bestätige Produkttyp, Verkäufer, Option, Menge, entscheidende Spezifikation und Datum sowie die erneute Öffnung der gespeicherten Adresse.","Stoppe bei unspezifischem Ziel, widersprüchlicher Identität, fehlender Option oder ungeklärter Spezifikation. Fortfahren bedeutet nur Identitätsbereitschaft, keine Qualitätsbewertung."],
["Den Umfang eng halten","Linkprüfung beantwortet Identitäts- und Zielfragen. Sie beweist weder Echtheit noch Qualität, Verkäuferleistung, Rückgabe, Versandfähigkeit oder Endkosten; dafür sind spätere aktuelle Belege nötig.","Prüfe unmittelbar vor Zahlung erneut. Ein guter Ablauf verbindet redaktionelle Kontrolle und Käuferkontrolle. Das Ergebnis ist kein ewiges Siegel, sondern eine reproduzierbare Prüfung mit Stopregel."]]),
es:make("Verifica el destino exacto de un hallazgo en una hoja Joyagoo","Método reproducible para vincular una fila de hoja con la ficha activa exacta antes de seleccionar o pedir.","Comprobado el 31 de agosto de 2026. La guía pública acepta enlaces originales; la ficha de destino activa demuestra la identidad.",["Comprueba el destino final","Combina varias señales","Registra redirecciones y opciones","No adivines lo incierto","Detente sin prueba exacta"],[
["Empieza por el destino final","Una fila es un puntero. Ábrela, guarda la dirección final y conserva también la original si hubo redirección. Título, miniatura y categoría solo ayudan a orientarse.","Que la página cargue no demuestra el producto correcto. Debe seguir mostrando la misma familia y la opción que motivó la fila; de lo contrario no está lista para la selección."],
["Guarda seis campos de identidad","Anota URL final, plataforma, ID visible, vendedor o tienda, tipo de producto y significado del título. Varias coincidencias independientes pesan más que una sola foto.","Conserva términos originales junto a la traducción. No inventes modelos, versiones ni cantidades; si no aparece un ID, registra ‘no visible’ para que otro lector pueda repetir el control."],
["Compara siempre en el mismo orden","Contrasta clase, título, imagen principal, identificador, vendedor y estructura de opciones. Una foto distinta puede ser inocua; una miniatura igual puede ocultar otra ficha.","Clasifica como coincidencia, parcial o discrepancia. La parcial exige pregunta o pausa y la discrepancia sale de la lista activa."],
["Trata las redirecciones como pruebas","El cambio móvil-canónico puede conservar identidad; una redirección de producto a tienda o búsqueda pierde el destino exacto. Registra los saltos importantes.","No copies el ID antiguo en un pedido manual. Si el inicio de sesión impide inspeccionar la ficha, decláralo y detente si el flujo actual de Joyagoo tampoco recupera un anuncio concreto."],
["Confirma la opción prevista","Una ficha correcta puede producir un pedido incorrecto. Revisa color, talla, versión y cantidad y observa si al elegir cambian imagen, precio o disponibilidad.","Conserva sistema y medidas de talla, piezas incluidas o modelo, enchufe y voltaje. El campo decisivo distingue una coincidencia real de una instrucción equivocada."],
["Separa hechos y preguntas","Etiqueta cada dato: confirmado en destino, solo en hoja, supuesto del comprador o pregunta abierta. Solo el dato actual confirmado sostiene la selección.","Así una miniatura no se convierte en composición y un precio antiguo no se trata como checkout. Guarda los cambios en lugar de borrar silenciosamente la observación anterior."],
["Ubica bien el flujo oficial","Joyagoo describe pegar un enlace o buscar y después elegir color, talla y cantidad. Esa interfaz recibe información, pero no convierte la hoja independiente en catálogo oficial.","Compara otra vez la ficha mostrada con los seis campos. Si usas entrada manual, marca todos los datos como aportados por el comprador y adjunta la fuente exacta."],
["Redacta un informe reproducible","Incluye URL guardada y final, fecha, identidad esperada y observada y motivo: página muerta, tienda, sustitución, opción, cantidad, modelo, acceso o ID.","Un sustituto es un candidato nuevo con su propio registro. No lo intercambies bajo el título, la imagen y la fecha de una fila antigua."],
["Haz el control final","Lee URL e ID frente al registro y confirma tipo, vendedor, opción, cantidad, especificación y fecha. Comprueba que la dirección guardada se abre de nuevo.","Detente si el destino no es específico, las señales chocan, falta la opción o queda una especificación decisiva. Continuar prueba identidad, no calidad."],
["Mantén un alcance estrecho","La verificación resuelve destino e identidad, no autenticidad, calidad, vendedor, devoluciones, rutas o coste. Cada decisión posterior necesita pruebas actuales propias.","Repite el control antes de pagar. El resultado útil no es una insignia permanente, sino un control reproducible y una condición clara para detenerse."]]),
fr:make("Vérifier la fiche de destination exacte d'une trouvaille Joyagoo","Méthode reproductible pour relier une ligne de tableur à la fiche active exacte avant sélection ou commande.","Vérifié le 31 août 2026. Le guide public accepte les liens source ; la fiche active reste la preuve d'identité.",["Contrôler la destination finale","Croiser plusieurs signaux","Tracer redirections et options","Ne jamais deviner","S'arrêter sans preuve exacte"],[
["Commencer par la destination finale","Une ligne est un pointeur. Ouvrez-la, conservez l'adresse finale et l'adresse initiale en cas de redirection. Titre, miniature et catégorie ne sont que des repères.","Une page chargée ne prouve pas le bon produit. Elle doit encore montrer la même famille et l'option visée ; sinon la trouvaille n'est pas prête pour la sélection."],
["Conserver six champs d'identité","Notez URL finale, plateforme, identifiant visible, vendeur ou boutique, type de produit et sens du titre. Plusieurs concordances indépendantes valent mieux qu'une image seule.","Gardez les termes source avec la traduction. N'inventez ni modèle, ni version, ni quantité ; si l'ID manque, écrivez-le afin qu'un autre lecteur puisse reproduire le contrôle."],
["Comparer dans un ordre fixe","Contrôlez classe, titre, image principale, identifiant, vendeur et structure des options. Une autre photo peut être normale ; la même miniature peut masquer une autre fiche.","Classez en correspondance, partielle ou contradictoire. Une correspondance partielle exige une question ou une pause ; une contradiction retire la ligne active."],
["Traiter les redirections comme preuves","Le passage mobile-canonique peut préserver l'identité. Une redirection produit vers boutique ou recherche perd la destination exacte. Consignez les étapes significatives.","Ne recopiez pas un ancien ID dans une commande manuelle. Si la connexion bloque la fiche, indiquez qu'elle n'est pas vérifiable et arrêtez-vous si Joyagoo ne récupère aucun produit précis."],
["Confirmer l'option voulue","Une fiche correcte peut encore mener à une mauvaise commande. Vérifiez couleur, taille, version et quantité, puis les changements d'image, prix ou disponibilité.","Gardez système de taille et mesures, nombre de pièces ou modèle, prise et tension. Le champ décisif distingue la bonne destination d'une instruction erronée."],
["Séparer faits et questions","Étiquetez chaque champ : confirmé sur destination, montré seulement dans le tableur, hypothèse ou question ouverte. Seul le fait actuel confirmé soutient la sélection.","Ainsi une miniature ne devient pas une matière et un ancien prix ne devient pas le checkout. Conservez avant et après lorsqu'un champ change."],
["Situer le parcours officiel","Joyagoo décrit le collage d'un lien ou la recherche, puis le choix de la couleur, taille et quantité. L'interface reçoit des données sans rendre le tableur officiel.","Comparez encore la fiche présentée aux six champs. En saisie manuelle, marquez chaque donnée comme fournie par l'acheteur et joignez la source exacte."],
["Rédiger un rapport reproductible","Donnez URL stockée et finale, date, identité attendue et observée, puis le motif exact : page morte, boutique, remplacement, option, quantité, modèle, accès ou ID.","Un remplacement devient un nouveau candidat avec son propre contrôle. Ne l'échangez pas silencieusement sous l'ancien titre, l'ancienne image et l'ancienne date."],
["Effectuer le contrôle final","Relisez URL et ID face au dossier. Confirmez type, vendeur, option, quantité, spécification, date et réouverture de l'adresse sauvegardée.","Arrêtez-vous si la destination n'est pas précise, si les signaux divergent, si l'option manque ou si une spécification reste inconnue. Continuer ne prouve que l'identité."],
["Garder une portée étroite","La vérification répond aux questions de destination et d'identité, pas d'authenticité, qualité, vendeur, retour, route ou coût. Chaque étape exige ses preuves actuelles.","Recontrôlez avant paiement. Le résultat n'est pas un badge permanent, mais une vérification reproductible avec une condition d'arrêt claire."]]),
it:make("Verifica la pagina esatta dietro una selezione del foglio Joyagoo","Metodo ripetibile per collegare una riga del foglio alla pagina attiva esatta prima di selezionare o ordinare.","Verificato il 31 agosto 2026. La guida pubblica accetta link originali; la pagina attiva resta la prova d'identità.",["Controlla la destinazione finale","Combina più segnali","Registra reindirizzi e opzioni","Non indovinare","Fermati senza prova esatta"],[
["Parti dalla destinazione finale","Una riga è un puntatore. Aprila, salva l'indirizzo finale e anche quello iniziale se c'è un reindirizzo. Titolo, miniatura e categoria servono solo a orientarsi.","Una pagina caricata non prova il prodotto giusto. Deve ancora mostrare la stessa famiglia e l'opzione prevista; altrimenti non è pronta per la selezione."],
["Salva sei campi d'identità","Registra URL finale, piattaforma, ID visibile, venditore o negozio, tipo di prodotto e significato del titolo. Più segnali concordi valgono più di una foto.","Conserva i termini originali accanto alla traduzione. Non inventare modelli, versioni o quantità; se l'ID non appare, annotalo per rendere ripetibile il controllo."],
["Confronta in ordine fisso","Verifica classe, titolo, immagine principale, identificatore, venditore e struttura delle opzioni. Una foto diversa può essere normale; la stessa miniatura può nascondere un'altra inserzione.","Classifica come corrispondenza, parziale o conflitto. La parziale richiede domanda o pausa; il conflitto elimina la riga dalla lista attiva."],
["Tratta i reindirizzi come prove","Il passaggio mobile-canonico può mantenere identità; un prodotto che apre negozio o ricerca perde la destinazione esatta. Registra i passaggi significativi.","Non copiare un vecchio ID in un ordine manuale. Se l'accesso blocca i dettagli, dichiaralo e fermati se anche Joyagoo non recupera una pagina precisa."],
["Conferma l'opzione prevista","Una pagina corretta può generare un ordine sbagliato. Controlla colore, taglia, versione e quantità e osserva variazioni di immagine, prezzo o disponibilità.","Mantieni sistema taglie e misure, pezzi inclusi oppure modello, spina e tensione. Il campo decisivo separa una vera corrispondenza da un'istruzione errata."],
["Separa fatti e domande","Etichetta ogni campo: confermato a destinazione, solo nel foglio, ipotesi o domanda aperta. Solo il dato attuale confermato sostiene la scelta.","Così una didascalia non diventa materiale e un vecchio prezzo non diventa checkout. Conserva prima e dopo quando un campo cambia."],
["Inquadra il flusso ufficiale","Joyagoo descrive incollare un link o cercare, poi scegliere colore, taglia e quantità. L'interfaccia riceve dati, ma non rende ufficiale il foglio indipendente.","Confronta ancora la pagina mostrata con i sei campi. Nell'inserimento manuale, marca ogni dato come fornito dall'acquirente e allega la fonte esatta."],
["Scrivi un rapporto ripetibile","Indica URL salvato e finale, data, identità attesa e osservata e motivo: pagina morta, negozio, sostituzione, opzione, quantità, modello, accesso o ID.","Un sostituto è un candidato nuovo con verifica propria. Non scambiarlo sotto il vecchio titolo, immagine e data."],
["Esegui il controllo finale","Leggi URL e ID contro il record. Conferma tipo, venditore, opzione, quantità, specifica, data e riapertura dell'indirizzo salvato.","Fermati se la destinazione non è specifica, i segnali confliggono, manca l'opzione o resta un dubbio decisivo. Procedere prova identità, non qualità."],
["Mantieni un ambito stretto","La verifica risponde a identità e destinazione, non autenticità, qualità, venditore, resi, rotte o costi. Ogni fase successiva richiede prove attuali.","Ricontrolla prima del pagamento. Il risultato non è un bollino permanente, ma una verifica ripetibile con una chiara regola di arresto."]])
};
