import { categories, categoryKeys, copy, facts, languageNames, languages, nav, pageIntro, products, uiText, type CategoryKey, type Lang, type PageKey, type TrustPageKey } from "./site-data";
import { locale, officialFacts, type OfficialFactKey, type StepKey } from "./locale-data";
import { seoArticleSlugs } from "./seo-articles";
import { articleUi, getLocalizedSeoArticle, getLocalizedSeoArticles } from "./seo-article-locales";
import { getCategoryPage, getFindsMethod, getTrustPage } from "./support-pages";

const basePages=["spreadsheet","finds","guide","qc","shipping","faq","articles"] as const;
function JsonLd({data}:{data:object}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,"\\u003c")}}/>;}
function pathFor(lang:Lang,page:PageKey){if(page==="home")return `/${lang}/`;if(seoArticleSlugs.includes(page))return `/${lang}/articles/${page}/`;if(categoryKeys.includes(page as CategoryKey))return `/${lang}/categories/${page}/`;return `/${lang}/${page}/`;}
function Logo({lang}:{lang:Lang}){return <a className="wordmark" href={pathFor(lang,"home")} aria-label={uiText[lang].home}><img src="/joyagoo-logo.png" width="768" height="235" alt="Joyagoo"/></a>;}
function Search({lang}:{lang:Lang}){const t=copy[lang];return <form className="search-panel" action="https://cnfanssp.com/search.html" method="get"><label htmlFor={`product-search-${lang}`}>{t.search as string}</label><div className="search-row"><input id={`product-search-${lang}`} name="keywords" placeholder={t.placeholder as string}/><input type="hidden" name="channelid" value=""/><button type="submit">{t.searchButton as string} <span>→</span></button></div></form>;}
function Header({lang,page}:{lang:Lang;page:PageKey}){const article=seoArticleSlugs.includes(page),ui=uiText[lang];return <><header className="site-header"><Logo lang={lang}/><nav className="desktop-nav" aria-label={ui.primaryNav}>{basePages.map(key=><a className={page===key||(key==="articles"&&article)?"active":""} href={pathFor(lang,key)} key={key}>{nav[lang][key]}</a>)}</nav><details className="language-menu"><summary>{lang.toUpperCase()}</summary><div>{languages.map(code=><a href={pathFor(code,page)} lang={code} key={code}>{languageNames[code]}</a>)}</div></details></header><nav className="mobile-nav" aria-label={ui.mobileNav}>{basePages.map(key=><a className={page===key||(key==="articles"&&article)?"active":""} href={pathFor(lang,key)} key={key}>{nav[lang][key]}</a>)}</nav></>;}
const footerLinks:Record<Lang,Record<TrustPageKey,string>>={en:{about:"About", "editorial-policy":"Editorial policy", "how-we-verify-links":"How we verify links"},de:{about:"Über uns", "editorial-policy":"Redaktionsrichtlinie", "how-we-verify-links":"Linkprüfung"},es:{about:"Quiénes somos", "editorial-policy":"Política editorial", "how-we-verify-links":"Verificación"},fr:{about:"À propos", "editorial-policy":"Politique éditoriale", "how-we-verify-links":"Vérification"},it:{about:"Chi siamo", "editorial-policy":"Politica editoriale", "how-we-verify-links":"Verifica link"}};
function Footer({lang}:{lang:Lang}){return <footer className="site-footer"><Logo lang={lang}/><p>{copy[lang].disclaimer as string}</p><div><a href={pathFor(lang,"articles")}>{nav[lang].articles}</a><a href={pathFor(lang,"faq")}>{nav[lang].faq}</a><a href={pathFor(lang,"about")}>{footerLinks[lang].about}</a><a href={pathFor(lang,"editorial-policy")}>{footerLinks[lang]["editorial-policy"]}</a><a href={pathFor(lang,"how-we-verify-links")}>{footerLinks[lang]["how-we-verify-links"]}</a><span>© 2026</span></div></footer>;}
function productCategory(lang:Lang,type:string){const index=categories.findIndex(([name])=>name===type);return locale[lang].categories[index]??type;}
function productName(lang:Lang,name:string,type:string){return `${productCategory(lang,type)}-${name.split("-").at(-1)}`;}
function ProductGrid({lang,category}:{lang:Lang;category?:string}){const l=locale[lang],ui=uiText[lang];const visible=category?products.filter(product=>product.type===category):products;return <div className="product-grid">{visible.map((product,index)=>{const label=productCategory(lang,product.type),name=productName(lang,product.name,product.type);return <article className="product-card" key={product.href}><a href={product.href}><div className="product-image"><img src={product.image} width="640" height="640" loading="lazy" alt={`${label} ${ui.listingSample}`}/><span>0{index+1}</span></div><div className="product-meta"><div className="product-meta-top"><small>{label}</small><i>JOY / 2026</i></div><h3>{name}</h3><p>{l.exact}</p><div className="product-meta-action"><b>{l.details}</b><span>↗</span></div></div></a></article>;})}</div>;}
function CategoryGrid({lang}:{lang:Lang}){const l=locale[lang];return <div className="category-grid">{categories.map(([,key,href,number],index)=><a href={href} key={key}><span>{number}</span><strong>{l.categories[index]}</strong><b>↗</b></a>)}</div>;}
function CategoryResearchGrid({lang}:{lang:Lang}){const l=locale[lang];const label={en:"Category research",de:"Kategorierecherche",es:"Investigación por categoría",fr:"Recherche par catégorie",it:"Ricerca per categoria"}[lang];return <section className="category-rack"><div className="section-kicker"><span>08 / {label}</span><h2>{copy[lang].productHeading as string}</h2></div><div className="category-grid">{categories.map(([,key,,number],index)=><a href={pathFor(lang,key)} key={key}><span>{number}</span><strong>{l.categories[index]}</strong><b>→</b></a>)}</div></section>;}
const pageFactKeys:Record<StepKey,OfficialFactKey[]>={spreadsheet:["serviceFee","orderFlow","qcPhotos","restrictions"],guide:["serviceFee","orderFlow","returnCost","coupon","customs"],qc:["qcPhotos","returnWindow","returnCost","damageEvidence"],shipping:["storage","rehearsal","chargeableWeight","routeRules","insurance","customs","tracking"]};
const officialSourceUrls:Record<OfficialFactKey,string>={serviceFee:"https://mgt.joyagoo.com/help-center/how-does-shopping-agent-service-charge/",orderFlow:"https://mgt.joyagoo.com/help-center/shopping-assistant-guidance/",qcPhotos:"https://mgt.joyagoo.com/help-center/shopping-assistant-guidance/",returnWindow:"https://mgt.joyagoo.com/help-center/terms-of-promised-returns-with-no-reasons/",returnCost:"https://mgt.joyagoo.com/help-center/terms-of-promised-returns-with-no-reasons/",storage:"https://mgt.joyagoo.com/help-center/how-long-can-the-goods-be-stored-in-the-joyagoo-warehouse/",rehearsal:"https://mgt.joyagoo.com/help-center/joyabuy-rehearsal-packing/",chargeableWeight:"https://mgt.joyagoo.com/help-center/actual-weight-and-volumetric-weight/",routeRules:"https://mgt.joyagoo.com/help-center/weighing-standards-for-each-transportation-services/",coupon:"https://mgt.joyagoo.com/help-center/shopping-assistant-guidance/",insurance:"https://mgt.joyagoo.com/help-center/insurance-policy-compensation-rules-insurance-purchase-instruction/",customs:"https://mgt.joyagoo.com/help-center/what-are-the-customs-risks/",damageEvidence:"https://mgt.joyagoo.com/help-center/what-do-i-do-if-there-is-something-wrong-after-i-received/",tracking:"https://mgt.joyagoo.com/help-center/logistics-platform-introduction/",restrictions:"https://mgt.joyagoo.com/help-center/list-of-prohibited-export-items-from-joyabuy/"};
const articleSources:Record<string,string[]>={
  "joyagoo-buying-fees-guide":[officialSourceUrls.orderFlow,officialSourceUrls.serviceFee,"https://mgt.joyagoo.com/help-center/status-of-the-shopping-agent-orders/"],
  "joyagoo-qc-return-window-guide":[officialSourceUrls.qcPhotos,officialSourceUrls.returnWindow,officialSourceUrls.damageEvidence],
  "joyagoo-warehouse-rehearsal-shipping-guide":[officialSourceUrls.storage,officialSourceUrls.rehearsal,officialSourceUrls.tracking,officialSourceUrls.insurance],
  "volumetric-weight-guide":[officialSourceUrls.chargeableWeight,officialSourceUrls.routeRules,officialSourceUrls.orderFlow],
  "joyagoo-reviews-buyer-signals":["https://www.trustpilot.com/review/joyagoo.com","https://apps.apple.com/us/app/joyagoo/id6742399785?see-all=reviews",officialSourceUrls.orderFlow]
};
const sourceUi:Record<Lang,{heading:string,label:string}>={en:{heading:"Sources checked for this guide",label:"Source"},de:{heading:"Geprüfte Quellen für diesen Leitfaden",label:"Quelle"},es:{heading:"Fuentes verificadas para esta guía",label:"Fuente"},fr:{heading:"Sources vérifiées pour ce guide",label:"Source"},it:{heading:"Fonti verificate per questa guida",label:"Fonte"}};
function ArticleSources({lang,slug}:{lang:Lang;slug:string}){const links=articleSources[slug]??[],ui=sourceUi[lang];return <section className="article-sources" aria-label={ui.heading}><span>{ui.heading}</span><div>{links.map((url,index)=><a href={url} target="_blank" rel="nofollow noopener noreferrer" key={url}>{ui.label} 0{index+1} · {new URL(url).hostname.replace("www.","")} ↗</a>)}</div></section>;}
function ResearchGrid({lang,page}:{lang:Lang;page:StepKey}){const heading={en:"What the official guidance actually says",de:"Was die offizielle Anleitung wirklich sagt",es:"Lo que realmente dice la guía oficial",fr:"Ce que dit réellement le guide officiel",it:"Cosa dice davvero la guida ufficiale"}[lang];const kicker={en:"OFFICIAL RESEARCH / 2026",de:"OFFIZIELLE RECHERCHE / 2026",es:"INVESTIGACIÓN OFICIAL / 2026",fr:"RECHERCHE OFFICIELLE / 2026",it:"RICERCA UFFICIALE / 2026"}[lang];return <section className="research-section"><div className="section-kicker"><span>{kicker}</span><h2>{heading}</h2></div><div className="research-grid">{pageFactKeys[page].map((key,index)=>{const fact=officialFacts[lang][key];return <article key={key}><span>0{index+1}</span><h3>{fact.title}</h3><p>{fact.body}</p><small><a href={officialSourceUrls[key]} target="_blank" rel="nofollow noopener noreferrer">{fact.source} ↗</a></small></article>;})}</div></section>;}

function Home({lang}:{lang:Lang}){const t=copy[lang],l=locale[lang],ui=uiText[lang],hero=t.hero as string[];return <>
  <JsonLd data={{"@context":"https://schema.org","@type":"WebSite",name:"Joyagoos",url:`https://joyagoos.shop/${lang}/`,description:t.lede,inLanguage:lang,publisher:{"@type":"Organization",name:"Joyagoos Editorial",url:"https://joyagoos.shop/en/about/"}}}/>
  <section className="hero"><div className="hero-copy"><div className="eyebrow"><span>{t.eyebrow as string}</span><b>{ui.indexLabel} / 2026</b></div><h1><span>{hero[0]}</span><em>{hero[1]}</em><span>{hero[2]}</span></h1><p className="hero-lede">{t.lede as string}</p><Search lang={lang}/><div className="hero-notes">{l.route.slice(0,3).map((item,index)=><span key={item}>0{index+1} · {item}</span>)}</div></div>
  <aside className="hero-board" aria-label={l.live}><div className="hero-board-heading"><span>{l.live}</span><b>03 / {l.checked}</b></div><div className="hero-lookbook">{products.slice(0,3).map((product,index)=>{const category=productCategory(lang,product.type),name=productName(lang,product.name,product.type);return <a href={product.href} className={`snapshot-image card-${index+1}`} key={product.href}><img src={product.image} alt={`${category} ${ui.listingSample}`} width="560" height="560"/><span><small>0{index+1} / {category}</small><b>{name}</b><i>↗</i></span></a>;})}</div><div className="product-snapshot"><span>{l.live}</span><b>{l.checked}</b></div></aside></section>
  <section className="route-strip route-strip--wide">{l.route.map((item,index)=><span key={item}><b>0{index+1}</b>{item}{index<l.route.length-1&&<i>→</i>}</span>)}</section>
  <section className="category-rack"><div className="section-kicker"><span>01 / {t.productRoutes as string}</span><h2>{t.productHeading as string}</h2></div><CategoryGrid lang={lang}/></section>
  <section className="home-products"><div className="section-kicker"><span>{l.productsKicker}</span><h2>{l.productsTitle}</h2></div><ProductGrid lang={lang}/></section>
  <section className="manual-section"><div className="manual-heading"><span>04 / {t.verified as string}</span><h2>{t.verifiedHeading as string}</h2><p>{t.verifiedText as string}</p></div><div className="fact-grid">{facts.map(([value],index)=><article key={value}><strong>{value}</strong><p>{l.facts[index]}</p></article>)}</div></section>
  <section className="update-strip"><span>{t.next as string}</span><p>{getLocalizedSeoArticles(lang).map(item=>item.title).join(" · ")}</p><a href={pathFor(lang,"articles")}>{nav[lang].articles} →</a></section>
  </>;}

function PageHero({lang,page}:{lang:Lang;page:typeof basePages[number]}){const [kicker,title,description]=pageIntro[lang][page];return <section className="page-hero"><span>{kicker}</span><h1>{title}</h1><p>{description}</p></section>;}
function StepPage({lang,page}:{lang:Lang;page:StepKey}){const l=locale[lang];return <><PageHero lang={lang} page={page}/><section className="step-layout"><div className="steps">{l.steps[page].map((item,index)=><article key={item}><span>0{index+1}</span><h2>{item}</h2><p>{l.stepNote}</p></article>)}</div><aside className="desk-note"><span>{l.deskRule}</span><h2>{l.deskTitles[page]}</h2><p>{copy[lang].verifiedText as string}</p><a href={page==="shipping"?pathFor(lang,"volumetric-weight-guide"):"https://cnfanssp.com/AllProducts/"}>{page==="shipping"?l.readWeight:l.openIndex} ↗</a></aside></section><ResearchGrid lang={lang} page={page}/>{page==="spreadsheet"&&<section className="category-rack"><div className="section-kicker"><span>{copy[lang].productRoutes as string}</span><h2>{copy[lang].productHeading as string}</h2></div><CategoryGrid lang={lang}/></section>}{page==="guide"&&<section className="search-section"><div><span>{l.searchDesk}</span><h2>{l.searchTitle}</h2></div><Search lang={lang}/></section>}</>;}
function Finds({lang}:{lang:Lang}){const l=locale[lang],method=getFindsMethod(lang);return <><PageHero lang={lang} page="finds"/><ProductGrid lang={lang}/><section className="research-section support-page"><div className="section-kicker"><span>{method.kicker}</span><h2>{method.title}</h2></div><div className="research-grid">{method.sections.map((section,index)=><article key={section.heading}><span>0{index+1}</span><h3>{section.heading}</h3><p>{section.body}</p></article>)}</div></section><CategoryResearchGrid lang={lang}/><section className="search-section"><div><span>{l.searchDesk}</span><h2>{l.moreProducts}</h2></div><Search lang={lang}/></section></>;}
function CategoryPage({lang,page}:{lang:Lang;page:CategoryKey}){const data=getCategoryPage(lang,page);const record=categories.find(([,key])=>key===page);const categoryName=record?.[0]??"";const mainHref=record?.[2]??"https://cnfanssp.com/AllProducts/";const matching=products.some(product=>product.type===categoryName);const cta={en:"Open live category",de:"Live-Kategorie öffnen",es:"Abrir categoría activa",fr:"Ouvrir la catégorie active",it:"Apri categoria attiva"}[lang];return <><section className="page-hero"><span>{data.kicker}</span><h1>{data.title}</h1><p>{data.description}</p></section>{matching&&<ProductGrid lang={lang} category={categoryName}/>}<section className="research-section support-page"><div className="research-grid">{data.sections.map((section,index)=><article key={section.heading}><span>0{index+1}</span><h3>{section.heading}</h3><p>{section.body}</p>{index===0&&<small><a href={mainHref}>{cta} ↗</a></small>}</article>)}</div></section><section className="search-section"><div><span>{copy[lang].search as string}</span><h2>{copy[lang].productHeading as string}</h2></div><Search lang={lang}/></section></>;}
function TrustPage({lang,page}:{lang:Lang;page:TrustPageKey}){const data=getTrustPage(lang,page);return <><section className="page-hero"><span>{data.kicker}</span><h1>{data.title}</h1><p>{data.description}</p></section><section className="research-section support-page"><div className="research-grid">{data.sections.map((section,index)=><article key={section.heading}><span>0{index+1}</span><h3>{section.heading}</h3><p>{section.body}</p></article>)}</div></section></>;}
function FAQ({lang}:{lang:Lang}){const items=locale[lang].faq;return <><JsonLd data={{"@context":"https://schema.org","@type":"FAQPage",mainEntity:items.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}}/><PageHero lang={lang} page="faq"/><section className="faq-list">{items.map(([q,a],index)=><details key={q} open={index===0}><summary><span>0{index+1}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</section></>;}
const shopLanes:Record<Lang,{label:string;items:[string,PageKey][]}>={
  en:{label:"SHOP CONTENT LANES",items:[["Latest Joyagoo Finds Updated Weekly","finds"],["Verified Joyagoo Shoes Product Links","shoes"],["Joyagoo Hoodies and Jackets Finds","hoodies"],["How We Check Dead Product Links","how-we-verify-links"],["Joyagoo Product Categories and Sizing Notes","spreadsheet"]]},
  de:{label:"SHOP-INHALTSSPUREN",items:[["Aktuelle Joyagoo Finds, regelmäßig geprüft","finds"],["Geprüfte Joyagoo-Produktlinks für Schuhe","shoes"],["Joyagoo Finds für Hoodies und Jacken","hoodies"],["So prüfen wir tote Produktlinks","how-we-verify-links"],["Joyagoo Kategorien und Größenhinweise","spreadsheet"]]},
  es:{label:"LÍNEAS DE CONTENIDO SHOP",items:[["Últimos hallazgos Joyagoo revisados","finds"],["Enlaces Joyagoo verificados para zapatillas","shoes"],["Hallazgos Joyagoo de sudaderas y chaquetas","hoodies"],["Cómo comprobamos enlaces muertos","how-we-verify-links"],["Categorías Joyagoo y notas de talla","spreadsheet"]]},
  fr:{label:"AXES DE CONTENU SHOP",items:[["Sélections Joyagoo récentes et vérifiées","finds"],["Liens Joyagoo vérifiés pour chaussures","shoes"],["Sélections hoodies et vestes Joyagoo","hoodies"],["Comment nous contrôlons les liens morts","how-we-verify-links"],["Catégories Joyagoo et notes de taille","spreadsheet"]]},
  it:{label:"FILONI DI CONTENUTO SHOP",items:[["Ultime selezioni Joyagoo controllate","finds"],["Link Joyagoo verificati per scarpe","shoes"],["Selezioni Joyagoo di felpe e giacche","hoodies"],["Come controlliamo i link morti","how-we-verify-links"],["Categorie Joyagoo e note sulle taglie","spreadsheet"]]},
};
function Articles({lang}:{lang:Lang}){const cta=locale[lang].articles[0].cta,items=getLocalizedSeoArticles(lang),ui=articleUi[lang],lanes=shopLanes[lang];return <><PageHero lang={lang} page="articles"/><section className="publishing-order publishing-order--shop"><span>{lanes.label}</span><ol>{lanes.items.map(([title,page],index)=><li key={title}><b>0{index+1}</b><a href={pathFor(lang,page)}>{title}</a></li>)}</ol></section><section className="publishing-order"><span>{ui.order}</span><ol>{items.map((item,index)=><li key={item.slug}><b>0{index+1}</b><a href={pathFor(lang,item.slug as PageKey)}>{item.title}</a></li>)}</ol></section><section className="article-grid article-grid--five">{items.map((item,index)=><a className={index===0?"feature-article":""} href={pathFor(lang,item.slug as PageKey)} key={item.slug}><span>{item.meta}</span><h2>{item.title}</h2><p>{item.description}</p><b>{cta} →</b></a>)}</section></>;}
function WeightArticle({lang}:{lang:Lang}){const a=locale[lang].article,l=locale[lang];const formula={en:"(length × width × height) ÷ route divisor",de:"(Länge × Breite × Höhe) ÷ Routenteiler",es:"(largo × ancho × alto) ÷ divisor de ruta",fr:"(longueur × largeur × hauteur) ÷ diviseur",it:"(lunghezza × larghezza × altezza) ÷ divisore"}[lang];return <article className="long-article"><header><span>{a.meta}</span><h1>{a.title}</h1><p className="standfirst">{a.standfirst}</p></header><div className="article-body"><aside><b>{a.quick}</b><ol>{a.checks.map(item=><li key={item}>{item}</li>)}</ol></aside><div>{a.sections.map(([title,p1,p2],index)=><section key={title}><h2>{title}</h2><p>{p1}</p>{index===0&&<div className="formula"><span>{a.formulaLabel}</span><strong>{formula}</strong><small>{a.formulaNote}</small></div>}<p>{p2}</p></section>)}</div></div><footer><a href={pathFor(lang,"shipping")}>← {a.back}</a><a href="https://cnfanssp.com/AllProducts/">{l.openIndex} ↗</a></footer></article>;}

function SeoArticlePage({lang,slug}:{lang:Lang;slug:string}){const article=getLocalizedSeoArticle(slug,lang),ui=articleUi[lang],citations=articleSources[slug]??[];if(!article)return null;const pageUrl=`https://joyagoos.shop${pathFor(lang,slug as PageKey)}`;return <article className="long-article seo-article" lang={lang}><JsonLd data={{"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.description,image:"https://joyagoos.shop/joyagoo-logo.png",mainEntityOfPage:{"@type":"WebPage","@id":pageUrl},datePublished:"2026-08-28",dateModified:"2026-08-28",inLanguage:lang,citation:citations,author:{"@type":"Organization",name:"Joyagoos Editorial",url:"https://joyagoos.shop/en/about/"},publisher:{"@type":"Organization",name:"Joyagoos Editorial",logo:{"@type":"ImageObject",url:"https://joyagoos.shop/joyagoo-logo.png"}}}}/><header><span>{article.meta} · {ui.updated}</span><h1>{article.title}</h1><p className="standfirst">{article.description}</p><small className="source-note">{article.sourceNote}</small><ArticleSources lang={lang} slug={slug}/></header><div className="article-body"><aside><b>{ui.quick}</b><ol>{article.quickFacts.map(item=><li key={item}>{item}</li>)}</ol><a href={pathFor(lang,"articles")}>{ui.all} ←</a></aside><div>{article.sections.map(section=><section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</section>)}</div></div><footer><a href={pathFor(lang,"articles")}>← {ui.back}</a><a href="https://cnfanssp.com/AllProducts/">{ui.products} ↗</a></footer></article>;}

export function SitePage({lang,page}:{lang:Lang;page:PageKey}){let content;if(page==="home")content=<Home lang={lang}/>;else if(page==="finds")content=<Finds lang={lang}/>;else if(page==="faq")content=<FAQ lang={lang}/>;else if(page==="articles")content=<Articles lang={lang}/>;else if(categoryKeys.includes(page as CategoryKey))content=<CategoryPage lang={lang} page={page as CategoryKey}/>;else if(["about","editorial-policy","how-we-verify-links"].includes(page))content=<TrustPage lang={lang} page={page as TrustPageKey}/>;else if(seoArticleSlugs.includes(page))content=<SeoArticlePage lang={lang} slug={page}/>;else content=<StepPage lang={lang} page={page as StepKey}/>;return <main lang={lang}><Header lang={lang} page={page}/>{content}<Footer lang={lang}/></main>;}
