export const languages = ["en", "de", "es", "fr", "it"] as const;
export type Lang = (typeof languages)[number];
export const categoryKeys = ["shoes", "hoodies", "t-shirts", "jackets", "pants", "accessories"] as const;
export type CategoryKey = (typeof categoryKeys)[number];
export type TrustPageKey = "about" | "editorial-policy" | "how-we-verify-links";
export type PageKey = "home" | "spreadsheet" | "finds" | "guide" | "qc" | "shipping" | "faq" | "articles" | TrustPageKey | CategoryKey | "joyagoo-spreadsheet-independent-product-index-guide" | "joyagoo-buying-fees-guide" | "joyagoo-qc-return-window-guide" | "joyagoo-warehouse-rehearsal-shipping-guide" | "volumetric-weight-guide" | "joyagoo-reviews-buyer-signals";
export const pageKeys: PageKey[] = ["home", "spreadsheet", "finds", "guide", "qc", "shipping", "faq", "articles", ...categoryKeys, "about", "editorial-policy", "how-we-verify-links", "joyagoo-spreadsheet-independent-product-index-guide", "joyagoo-buying-fees-guide", "joyagoo-qc-return-window-guide", "joyagoo-warehouse-rehearsal-shipping-guide", "volumetric-weight-guide", "joyagoo-reviews-buyer-signals"];
export const languageNames: Record<Lang, string> = { en: "English", de: "Deutsch", es: "Español", fr: "Français", it: "Italiano" };
export const uiText: Record<Lang, {home:string;primaryNav:string;mobileNav:string;listingSample:string;indexLabel:string;homeTitle:string}> = {
  en: {home:"Joyagoo home",primaryNav:"Primary navigation",mobileNav:"Mobile navigation",listingSample:"listing sample",indexLabel:"INDEX",homeTitle:"Joyagoo Finds & Spreadsheet 2026 | Verified Product Links"},
  de: {home:"Joyagoo Startseite",primaryNav:"Hauptnavigation",mobileNav:"Mobile Navigation",listingSample:"Beispielangebot",indexLabel:"REGISTER",homeTitle:"Joyagoo Finds & Tabelle 2026 | Geprüfte Produktlinks"},
  es: {home:"Inicio de Joyagoo",primaryNav:"Navegación principal",mobileNav:"Navegación móvil",listingSample:"anuncio de muestra",indexLabel:"ÍNDICE",homeTitle:"Hallazgos y hoja Joyagoo 2026 | Enlaces verificados"},
  fr: {home:"Accueil Joyagoo",primaryNav:"Navigation principale",mobileNav:"Navigation mobile",listingSample:"exemple d’annonce",indexLabel:"INDEX",homeTitle:"Sélections et tableur Joyagoo 2026 | Liens vérifiés"},
  it: {home:"Home Joyagoo",primaryNav:"Navigazione principale",mobileNav:"Navigazione mobile",listingSample:"inserzione di esempio",indexLabel:"INDICE",homeTitle:"Selezioni e foglio Joyagoo 2026 | Link verificati"},
};
export const nav: Record<Lang, Record<string, string>> = {
  en: { spreadsheet: "Spreadsheet", finds: "Finds", guide: "Guide", qc: "QC", shipping: "Shipping", faq: "FAQ", articles: "Articles" },
  de: { spreadsheet: "Tabelle", finds: "Fundstücke", guide: "Anleitung", qc: "Qualitätscheck", shipping: "Versand", faq: "FAQ", articles: "Artikel" },
  es: { spreadsheet: "Hoja", finds: "Hallazgos", guide: "Guía", qc: "Control", shipping: "Envío", faq: "FAQ", articles: "Artículos" },
  fr: { spreadsheet: "Tableur", finds: "Sélections", guide: "Guide", qc: "Contrôle", shipping: "Livraison", faq: "FAQ", articles: "Articles" },
  it: { spreadsheet: "Foglio", finds: "Selezioni", guide: "Guida", qc: "Controllo", shipping: "Spedizione", faq: "FAQ", articles: "Articoli" },
};
export const copy = {
  en: { eyebrow:"Independent buyer field manual",hero:["Joyagoo finds.","Verified links.","A smarter spreadsheet."],lede:"A faster Joyagoo spreadsheet companion for product discovery, QC decisions, packing choices and shipping prep—built from published platform guidance.",search:"Search the complete product index",placeholder:"Try: shoes, jacket, jersey...",searchButton:"Search products",productRoutes:"Product routes",productHeading:"Start with a category, not a guess.",verified:"Verified basics",verifiedHeading:"Use published rules as your baseline.",verifiedText:"Seller terms, category restrictions and route availability can still change. Re-check the live platform before paying.",next:"Next in the manual",disclaimer:"Independent guide. Always verify the live listing, route rules and final charges before paying. Information may change."},
  de: { eyebrow:"Unabhängiges Käufer-Handbuch",hero:["Joyagoo Finds.","Geprüfte Links.","Eine bessere Tabelle."],lede:"Ein schneller Joyagoo-Spreadsheet-Begleiter für Produktsuche, Qualitätskontrolle, Verpackung und Versandplanung—auf Basis veröffentlichter Plattformhinweise.",search:"Gesamten Produktindex durchsuchen",placeholder:"Zum Beispiel: Schuhe, Jacke, Trikot...",searchButton:"Produkte suchen",productRoutes:"Produktwege",productHeading:"Beginne mit einer Kategorie, nicht mit einer Vermutung.",verified:"Geprüfte Grundlagen",verifiedHeading:"Veröffentlichte Regeln sind deine Basis.",verifiedText:"Verkäuferbedingungen, Kategorien und Versandrouten können sich ändern. Prüfe die Live-Plattform vor der Zahlung.",next:"Als Nächstes",disclaimer:"Unabhängiger Leitfaden. Prüfe vor der Zahlung immer das Live-Angebot, die Routenregeln und die Endkosten."},
  es: { eyebrow:"Manual independiente del comprador",hero:["Hallazgos Joyagoo.","Enlaces verificados.","Una hoja mejor."],lede:"Un compañero de hoja Joyagoo para descubrir productos, decidir sobre el control de calidad, elegir el embalaje y preparar el envío.",search:"Buscar en el índice completo",placeholder:"Prueba: zapatillas, chaqueta, camiseta...",searchButton:"Buscar productos",productRoutes:"Rutas de producto",productHeading:"Empieza por una categoría, no por una suposición.",verified:"Datos verificados",verifiedHeading:"Usa las reglas publicadas como referencia.",verifiedText:"Las condiciones del vendedor, las restricciones y las rutas pueden cambiar. Comprueba la plataforma antes de pagar.",next:"Siguiente en el manual",disclaimer:"Guía independiente. Verifica siempre el anuncio, las reglas de ruta y los cargos finales antes de pagar."},
  fr: { eyebrow:"Manuel indépendant de l’acheteur",hero:["Sélections Joyagoo.","Liens vérifiés.","Un meilleur tableur."],lede:"Un compagnon de tableur Joyagoo pour découvrir les produits, décider du contrôle qualité, choisir l’emballage et préparer l’expédition.",search:"Rechercher dans l’index complet",placeholder:"Exemple : chaussures, veste, maillot...",searchButton:"Rechercher",productRoutes:"Parcours produits",productHeading:"Commencez par une catégorie, pas une supposition.",verified:"Bases vérifiées",verifiedHeading:"Utilisez les règles publiées comme référence.",verifiedText:"Les conditions du vendeur, les restrictions et les itinéraires peuvent changer. Vérifiez la plateforme avant de payer.",next:"Suite du manuel",disclaimer:"Guide indépendant. Vérifiez toujours l’annonce, les règles d’itinéraire et le total avant de payer."},
  it: { eyebrow:"Manuale indipendente dell’acquirente",hero:["Selezioni Joyagoo.","Link verificati.","Un foglio migliore."],lede:"Un compagno del foglio Joyagoo per scoprire prodotti, decidere sul controllo qualità, scegliere l’imballaggio e preparare la spedizione.",search:"Cerca nell’indice completo",placeholder:"Prova: scarpe, giacca, maglia...",searchButton:"Cerca prodotti",productRoutes:"Percorsi prodotto",productHeading:"Inizia da una categoria, non da un’ipotesi.",verified:"Basi verificate",verifiedHeading:"Usa le regole pubblicate come riferimento.",verifiedText:"Le condizioni del venditore, le restrizioni e le rotte possono cambiare. Controlla la piattaforma prima di pagare.",next:"Prossimo nel manuale",disclaimer:"Guida indipendente. Controlla sempre l’inserzione, le regole della rotta e i costi finali prima di pagare."},
} satisfies Record<Lang, Record<string,string|string[]>>;
export const categories = [["Shoes","shoes","https://cnfanssp.com/shoes/","01"],["Sweatshirts","hoodies","https://cnfanssp.com/hoodies-sweaters/","02"],["T-Shirts","t-shirts","https://cnfanssp.com/t-shirts/","03"],["Jackets","jackets","https://cnfanssp.com/jackets/","04"],["Pants / Shorts","pants","https://cnfanssp.com/pants-shorts/","05"],["Accessories","accessories","https://cnfanssp.com/accessories/","06"]] as const;
export const products = [
  {name:"Accessories-60",type:"Accessories",href:"https://cnfanssp.com/AllProducts/6427.html",image:"https://cnfanssp.com/uploads/allimg/20260430/1-260430161230537.jpg"},
  {name:"Shoes-60",type:"Shoes",href:"https://cnfanssp.com/AllProducts/6050.html",image:"https://cnfanssp.com/uploads/allimg/20260416/1-260416213T1S9.jpg"},
  {name:"Jackets-60",type:"Jackets",href:"https://cnfanssp.com/AllProducts/6247.html",image:"https://cnfanssp.com/uploads/allimg/20260429/1-2604291F305238.jpg"},
  {name:"T-Shirts-60",type:"T-Shirts",href:"https://cnfanssp.com/AllProducts/6187.html",image:"https://cnfanssp.com/uploads/allimg/20260429/1-260429162000554.jpg"},
] as const;
export const facts = [["90 days","Free warehouse storage listed in published shopping guidance"],["120 hours","Published QC return request window, subject to seller and item conditions"],["20 CNY / $3","Two official rehearsal-packing pages currently show different fee formats"]] as const;
export const pageIntro: Record<Lang,Record<"spreadsheet"|"finds"|"guide"|"qc"|"shipping"|"faq"|"articles",[string,string,string]>> = {
  en:{spreadsheet:["01 / JOYAGOO SPREADSHEET","Joyagoo Spreadsheet 2026: verified product links.","Discover by category, open the exact matching detail page, then verify the live listing before you import or order."],finds:["02 / LATEST JOYAGOO FINDS","Latest Joyagoo finds with verified product links.","Every sample pairs the first visible image with its corresponding detail page and records the category route used for the check."],guide:["03 / JOYAGOO BUYING GUIDE","How to use Joyagoo: a complete buying guide.","A compact order flow for comparing the live listing, confirming options, planning QC and preparing shipment."],qc:["04 / JOYAGOO QC GUIDE","Joyagoo QC guide: how to check warehouse photos.","Use a repeatable inspection checklist, compare the saved listing with the evidence, and act inside the published return window."],shipping:["05 / JOYAGOO SHIPPING GUIDE","Joyagoo shipping: weight, packing and cost decisions.","Estimate actual and volumetric weight, consolidate deliberately and use rehearsal packing when uncertainty matters."],faq:["06 / JOYAGOO FAQ","Joyagoo FAQ: spreadsheet, QC, returns and shipping.","Direct answers to common product-link, warehouse, QC and shipping questions, grounded in published guidance."],articles:["07 / JOYAGOO PRODUCT RESEARCH","Joyagoo product-link research and buyer guides.","Long-form field notes about finds, link checks, categories and the buyer decisions behind a usable spreadsheet."]},
  de:{spreadsheet:["01 / JOYAGOO TABELLE","Joyagoo Tabelle 2026 mit geprüften Produktlinks.","Nach Kategorie suchen, die exakte Detailseite öffnen und das Live-Angebot vor Import oder Bestellung prüfen."],finds:["02 / AKTUELLE JOYAGOO FINDS","Aktuelle Joyagoo Finds mit geprüften Produktlinks.","Jedes Beispiel verbindet das erste sichtbare Bild mit der passenden Detailseite und dokumentiert den Kategoriepfad."],guide:["03 / JOYAGOO KAUFANLEITUNG","Joyagoo verwenden: die vollständige Kaufanleitung.","Ein kompakter Ablauf für Live-Angebot, Optionen, Qualitätskontrolle und Versand."],qc:["04 / JOYAGOO QC-ANLEITUNG","Joyagoo QC: Lagerfotos systematisch prüfen.","Gespeichertes Angebot und Fotos vergleichen und innerhalb des veröffentlichten Rückgabefensters handeln."],shipping:["05 / JOYAGOO VERSAND","Joyagoo Versand: Gewicht, Verpackung und Kosten.","Ist- und Volumengewicht schätzen, bewusst konsolidieren und bei Unsicherheit Probeverpackung nutzen."],faq:["06 / JOYAGOO FAQ","Joyagoo FAQ zu Tabelle, QC, Rückgabe und Versand.","Direkte Antworten zu Produktlinks, Lager, Qualitätskontrolle und Versand auf Basis veröffentlichter Hinweise."],articles:["07 / JOYAGOO PRODUKTRECHERCHE","Joyagoo Produktlinks, Finds und Prüfanleitungen.","Ausführliche Notizen zu Kategorien, Linkprüfung und Entscheidungen hinter einer brauchbaren Tabelle."]},
  es:{spreadsheet:["01 / HOJA JOYAGOO","Hoja Joyagoo 2026 con enlaces verificados.","Explora por categoría, abre la ficha exacta y verifica el anuncio activo antes de importar o pedir."],finds:["02 / ÚLTIMOS HALLAZGOS JOYAGOO","Últimos hallazgos Joyagoo con enlaces verificados.","Cada muestra une la primera imagen visible con su página exacta y registra la ruta de categoría."],guide:["03 / GUÍA DE COMPRA JOYAGOO","Cómo usar Joyagoo: guía de compra completa.","Un flujo compacto para comparar el anuncio, confirmar opciones, planear el control y preparar el envío."],qc:["04 / GUÍA QC JOYAGOO","QC Joyagoo: cómo revisar fotos de almacén.","Compara el anuncio guardado con las pruebas y actúa dentro del plazo de devolución publicado."],shipping:["05 / ENVÍO JOYAGOO","Envío Joyagoo: peso, embalaje y costes.","Calcula peso real y volumétrico, consolida con intención y ensaya el embalaje cuando importe la incertidumbre."],faq:["06 / FAQ JOYAGOO","FAQ Joyagoo: hoja, QC, devoluciones y envío.","Respuestas directas sobre enlaces, almacén, control y envío basadas en guías publicadas."],articles:["07 / INVESTIGACIÓN DE PRODUCTOS JOYAGOO","Investigación de enlaces, hallazgos y verificación Joyagoo.","Notas detalladas sobre categorías, controles de enlaces y decisiones detrás de una hoja útil."]},
  fr:{spreadsheet:["01 / TABLEUR JOYAGOO","Tableur Joyagoo 2026 avec liens produits vérifiés.","Explorez par catégorie, ouvrez la fiche exacte et vérifiez l’annonce active avant d’importer ou commander."],finds:["02 / SÉLECTIONS JOYAGOO RÉCENTES","Sélections Joyagoo récentes avec liens vérifiés.","Chaque exemple associe la première image visible à sa fiche exacte et conserve le parcours de catégorie."],guide:["03 / GUIDE D’ACHAT JOYAGOO","Comment utiliser Joyagoo : guide d’achat complet.","Un parcours compact pour comparer l’annonce, confirmer les options, planifier le contrôle et l’envoi."],qc:["04 / GUIDE QC JOYAGOO","QC Joyagoo : vérifier les photos d’entrepôt.","Comparez l’annonce sauvegardée aux preuves et agissez pendant la période de retour publiée."],shipping:["05 / LIVRAISON JOYAGOO","Livraison Joyagoo : poids, emballage et coûts.","Estimez le poids réel et volumétrique, consolidez avec intention et utilisez le pré-emballage si nécessaire."],faq:["06 / FAQ JOYAGOO","FAQ Joyagoo : tableur, QC, retours et livraison.","Réponses directes sur liens, entrepôt, contrôle et expédition à partir des guides publiés."],articles:["07 / RECHERCHE PRODUITS JOYAGOO","Recherche de liens, sélections et vérification Joyagoo.","Notes détaillées sur catégories, contrôle des liens et décisions derrière un tableur utile."]},
  it:{spreadsheet:["01 / FOGLIO JOYAGOO","Foglio Joyagoo 2026 con link prodotto verificati.","Esplora per categoria, apri la scheda esatta e verifica l’inserzione attiva prima di importare o ordinare."],finds:["02 / ULTIME SELEZIONI JOYAGOO","Ultime selezioni Joyagoo con link verificati.","Ogni esempio collega la prima immagine visibile alla pagina esatta e registra il percorso di categoria."],guide:["03 / GUIDA ACQUISTO JOYAGOO","Come usare Joyagoo: guida completa all’acquisto.","Un percorso compatto per confrontare l’inserzione, confermare le opzioni, pianificare il controllo e la spedizione."],qc:["04 / GUIDA QC JOYAGOO","QC Joyagoo: controllare le foto del magazzino.","Confronta l’inserzione salvata con le prove e agisci entro la finestra di reso pubblicata."],shipping:["05 / SPEDIZIONE JOYAGOO","Spedizione Joyagoo: peso, imballo e costi.","Stima peso reale e volumetrico, consolida con attenzione e usa la prova d’imballaggio quando serve."],faq:["06 / FAQ JOYAGOO","FAQ Joyagoo: foglio, QC, resi e spedizione.","Risposte dirette su link, magazzino, controllo e spedizione basate su guide pubblicate."],articles:["07 / RICERCA PRODOTTI JOYAGOO","Ricerca link, selezioni e verifica Joyagoo.","Note dettagliate su categorie, controllo dei link e decisioni dietro un foglio utile."]},
};
