export const languages = ["en", "de", "es", "fr", "it"] as const;
export type Lang = (typeof languages)[number];
export type PageKey = "home" | "spreadsheet" | "finds" | "guide" | "qc" | "shipping" | "faq" | "articles" | "joyagoo-buying-fees-guide" | "joyagoo-qc-return-window-guide" | "joyagoo-warehouse-rehearsal-shipping-guide" | "volumetric-weight-guide" | "joyagoo-reviews-buyer-signals";
export const pageKeys: PageKey[] = ["home", "spreadsheet", "finds", "guide", "qc", "shipping", "faq", "articles", "joyagoo-buying-fees-guide", "joyagoo-qc-return-window-guide", "joyagoo-warehouse-rehearsal-shipping-guide", "volumetric-weight-guide", "joyagoo-reviews-buyer-signals"];
export const languageNames: Record<Lang, string> = { en: "English", de: "Deutsch", es: "Español", fr: "Français", it: "Italiano" };
export const uiText: Record<Lang, {home:string;primaryNav:string;mobileNav:string;listingSample:string;indexLabel:string;homeTitle:string}> = {
  en: {home:"Joyagoo home",primaryNav:"Primary navigation",mobileNav:"Mobile navigation",listingSample:"listing sample",indexLabel:"INDEX",homeTitle:"Joyagoo Spreadsheet · Joyagoos"},
  de: {home:"Joyagoo Startseite",primaryNav:"Hauptnavigation",mobileNav:"Mobile Navigation",listingSample:"Beispielangebot",indexLabel:"REGISTER",homeTitle:"Joyagoo Tabelle · Joyagoos"},
  es: {home:"Inicio de Joyagoo",primaryNav:"Navegación principal",mobileNav:"Navegación móvil",listingSample:"anuncio de muestra",indexLabel:"ÍNDICE",homeTitle:"Hoja Joyagoo · Joyagoos"},
  fr: {home:"Accueil Joyagoo",primaryNav:"Navigation principale",mobileNav:"Navigation mobile",listingSample:"exemple d’annonce",indexLabel:"INDEX",homeTitle:"Tableur Joyagoo · Joyagoos"},
  it: {home:"Home Joyagoo",primaryNav:"Navigazione principale",mobileNav:"Navigazione mobile",listingSample:"inserzione di esempio",indexLabel:"INDICE",homeTitle:"Foglio Joyagoo · Joyagoos"},
};
export const nav: Record<Lang, Record<string, string>> = {
  en: { spreadsheet: "Spreadsheet", finds: "Finds", guide: "Guide", qc: "QC", shipping: "Shipping", faq: "FAQ", articles: "Articles" },
  de: { spreadsheet: "Tabelle", finds: "Fundstücke", guide: "Anleitung", qc: "Qualitätscheck", shipping: "Versand", faq: "FAQ", articles: "Artikel" },
  es: { spreadsheet: "Hoja", finds: "Hallazgos", guide: "Guía", qc: "Control", shipping: "Envío", faq: "FAQ", articles: "Artículos" },
  fr: { spreadsheet: "Tableur", finds: "Sélections", guide: "Guide", qc: "Contrôle", shipping: "Livraison", faq: "FAQ", articles: "Articles" },
  it: { spreadsheet: "Foglio", finds: "Selezioni", guide: "Guida", qc: "Controllo", shipping: "Spedizione", faq: "FAQ", articles: "Articoli" },
};
export const copy = {
  en: { eyebrow:"Independent buyer field manual",hero:["Find the item.","Check the risk.","Ship with a plan."],lede:"A faster Joyagoo spreadsheet companion for product discovery, QC decisions, packing choices and shipping prep—built from published platform guidance.",search:"Search the complete product index",placeholder:"Try: shoes, jacket, jersey...",searchButton:"Search products",productRoutes:"Product routes",productHeading:"Start with a category, not a guess.",verified:"Verified basics",verifiedHeading:"Use published rules as your baseline.",verifiedText:"Seller terms, category restrictions and route availability can still change. Re-check the live platform before paying.",next:"Next in the manual",disclaimer:"Independent guide. Always verify the live listing, route rules and final charges before paying. Information may change."},
  de: { eyebrow:"Unabhängiges Käufer-Handbuch",hero:["Artikel finden.","Risiko prüfen.","Versand planen."],lede:"Ein schneller Joyagoo-Spreadsheet-Begleiter für Produktsuche, Qualitätskontrolle, Verpackung und Versandplanung—auf Basis veröffentlichter Plattformhinweise.",search:"Gesamten Produktindex durchsuchen",placeholder:"Zum Beispiel: Schuhe, Jacke, Trikot...",searchButton:"Produkte suchen",productRoutes:"Produktwege",productHeading:"Beginne mit einer Kategorie, nicht mit einer Vermutung.",verified:"Geprüfte Grundlagen",verifiedHeading:"Veröffentlichte Regeln sind deine Basis.",verifiedText:"Verkäuferbedingungen, Kategorien und Versandrouten können sich ändern. Prüfe die Live-Plattform vor der Zahlung.",next:"Als Nächstes",disclaimer:"Unabhängiger Leitfaden. Prüfe vor der Zahlung immer das Live-Angebot, die Routenregeln und die Endkosten."},
  es: { eyebrow:"Manual independiente del comprador",hero:["Encuentra el artículo.","Revisa el riesgo.","Envía con un plan."],lede:"Un compañero de hoja Joyagoo para descubrir productos, decidir sobre el control de calidad, elegir el embalaje y preparar el envío.",search:"Buscar en el índice completo",placeholder:"Prueba: zapatillas, chaqueta, camiseta...",searchButton:"Buscar productos",productRoutes:"Rutas de producto",productHeading:"Empieza por una categoría, no por una suposición.",verified:"Datos verificados",verifiedHeading:"Usa las reglas publicadas como referencia.",verifiedText:"Las condiciones del vendedor, las restricciones y las rutas pueden cambiar. Comprueba la plataforma antes de pagar.",next:"Siguiente en el manual",disclaimer:"Guía independiente. Verifica siempre el anuncio, las reglas de ruta y los cargos finales antes de pagar."},
  fr: { eyebrow:"Manuel indépendant de l’acheteur",hero:["Trouvez l’article.","Vérifiez le risque.","Expédiez avec un plan."],lede:"Un compagnon de tableur Joyagoo pour découvrir les produits, décider du contrôle qualité, choisir l’emballage et préparer l’expédition.",search:"Rechercher dans l’index complet",placeholder:"Exemple : chaussures, veste, maillot...",searchButton:"Rechercher",productRoutes:"Parcours produits",productHeading:"Commencez par une catégorie, pas une supposition.",verified:"Bases vérifiées",verifiedHeading:"Utilisez les règles publiées comme référence.",verifiedText:"Les conditions du vendeur, les restrictions et les itinéraires peuvent changer. Vérifiez la plateforme avant de payer.",next:"Suite du manuel",disclaimer:"Guide indépendant. Vérifiez toujours l’annonce, les règles d’itinéraire et le total avant de payer."},
  it: { eyebrow:"Manuale indipendente dell’acquirente",hero:["Trova l’articolo.","Controlla il rischio.","Spedisci con un piano."],lede:"Un compagno del foglio Joyagoo per scoprire prodotti, decidere sul controllo qualità, scegliere l’imballaggio e preparare la spedizione.",search:"Cerca nell’indice completo",placeholder:"Prova: scarpe, giacca, maglia...",searchButton:"Cerca prodotti",productRoutes:"Percorsi prodotto",productHeading:"Inizia da una categoria, non da un’ipotesi.",verified:"Basi verificate",verifiedHeading:"Usa le regole pubblicate come riferimento.",verifiedText:"Le condizioni del venditore, le restrizioni e le rotte possono cambiare. Controlla la piattaforma prima di pagare.",next:"Prossimo nel manuale",disclaimer:"Guida indipendente. Controlla sempre l’inserzione, le regole della rotta e i costi finali prima di pagare."},
} satisfies Record<Lang, Record<string,string|string[]>>;
export const categories = [["Shoes","https://cnfanssp.com/shoes/","01"],["Sweatshirts","https://cnfanssp.com/hoodies-sweaters/","02"],["T-Shirts","https://cnfanssp.com/t-shirts/","03"],["Jackets","https://cnfanssp.com/jackets/","04"],["Pants / Shorts","https://cnfanssp.com/pants-shorts/","05"],["Accessories","https://cnfanssp.com/accessories/","06"]] as const;
export const products = [
  {name:"Accessories-60",type:"Accessories",href:"https://cnfanssp.com/AllProducts/6427.html",image:"https://cnfanssp.com/uploads/allimg/20260430/1-260430161230537.jpg"},
  {name:"Shoes-60",type:"Shoes",href:"https://cnfanssp.com/AllProducts/6050.html",image:"https://cnfanssp.com/uploads/allimg/20260416/1-260416213T1S9.jpg"},
  {name:"Jackets-60",type:"Jackets",href:"https://cnfanssp.com/AllProducts/6247.html",image:"https://cnfanssp.com/uploads/allimg/20260429/1-2604291F305238.jpg"},
  {name:"T-Shirts-60",type:"T-Shirts",href:"https://cnfanssp.com/AllProducts/6187.html",image:"https://cnfanssp.com/uploads/allimg/20260429/1-260429162000554.jpg"},
] as const;
export const facts = [["90 days","Free warehouse storage listed in published shopping guidance"],["120 hours","Published QC return request window, subject to seller and item conditions"],["20 CNY / $3","Two official rehearsal-packing pages currently show different fee formats"]] as const;
export const pageIntro: Record<Lang,Record<"spreadsheet"|"finds"|"guide"|"qc"|"shipping"|"faq"|"articles",[string,string,string]>> = {
  en:{spreadsheet:["01 / SPREADSHEET","A product index that leads somewhere useful.","Discover by category, open the exact matching detail page, then verify the listing before you import or order."],finds:["02 / CURATED FINDS","Exact image. Exact detail page.","Every sample below pairs the first visible image with its corresponding detail page—no mystery redirects."],guide:["03 / BUYER GUIDE","Make the risky decisions before checkout.","A compact order flow for comparing the listing, confirming options, planning QC and preparing shipment."],qc:["04 / QC DESK","A photo is evidence, not a verdict.","Use a repeatable inspection checklist and act inside the available return window."],shipping:["05 / SHIPPING","Pack for the billing rule, not the product photo.","Estimate actual and volumetric weight, consolidate deliberately and use rehearsal packing when uncertainty matters."],faq:["06 / FAQ","Short answers before you spend.","The most common spreadsheet, warehouse, QC and shipping questions in one place."],articles:["07 / FIELD NOTES","Long-form guidance for expensive mistakes.","Practical articles that separate published platform rules from buyer judgment."]},
  de:{spreadsheet:["01 / TABELLE","Ein Produktindex mit klarem Ziel.","Nach Kategorie suchen, die exakte Detailseite öffnen und das Angebot vor Import oder Bestellung prüfen."],finds:["02 / FUNDSTÜCKE","Exaktes Bild. Exakte Detailseite.","Jedes Beispiel verbindet das erste sichtbare Bild mit der passenden Detailseite."],guide:["03 / KÄUFERLEITFADEN","Triff riskante Entscheidungen vor dem Checkout.","Ein kompakter Ablauf für Angebot, Optionen, Qualitätskontrolle und Versand."],qc:["04 / QUALITÄTSCHECK","Ein Foto ist ein Beleg, kein Urteil.","Nutze eine wiederholbare Prüfliste und handle innerhalb des Rückgabefensters."],shipping:["05 / VERSAND","Plane nach Abrechnungsregel, nicht nach Produktfoto.","Schätze Ist- und Volumengewicht und konsolidiere bewusst."],faq:["06 / FAQ","Kurze Antworten vor dem Kauf.","Häufige Fragen zu Tabelle, Lager, Qualitätskontrolle und Versand."],articles:["07 / NOTIZEN","Detaillierte Hilfe gegen teure Fehler.","Praktische Artikel trennen Plattformregeln von Käuferentscheidungen."]},
  es:{spreadsheet:["01 / HOJA","Un índice que conduce a algo útil.","Explora por categoría, abre la página exacta y verifica el anuncio antes de importar o pedir."],finds:["02 / HALLAZGOS","Imagen exacta. Página exacta.","Cada muestra enlaza la primera imagen visible con su página de detalle correspondiente."],guide:["03 / GUÍA","Toma las decisiones de riesgo antes de pagar.","Un flujo compacto para comparar el anuncio, confirmar opciones, planear el control y preparar el envío."],qc:["04 / CONTROL","Una foto es evidencia, no un veredicto.","Usa una lista de inspección repetible y actúa dentro del plazo disponible."],shipping:["05 / ENVÍO","Empaca según la regla de cobro.","Calcula peso real y volumétrico, consolida con intención y ensaya el embalaje si importa la incertidumbre."],faq:["06 / FAQ","Respuestas antes de gastar.","Preguntas frecuentes sobre hoja, almacén, control y envío."],articles:["07 / NOTAS","Guías largas para evitar errores caros.","Artículos prácticos que separan reglas publicadas y decisiones del comprador."]},
  fr:{spreadsheet:["01 / TABLEUR","Un index qui mène au bon endroit.","Explorez par catégorie, ouvrez la fiche exacte et vérifiez l’annonce avant d’importer ou commander."],finds:["02 / SÉLECTIONS","Image exacte. Fiche exacte.","Chaque exemple associe la première image visible à sa page de détail correspondante."],guide:["03 / GUIDE","Prenez les décisions risquées avant de payer.","Un parcours compact pour comparer l’annonce, confirmer les options, planifier le contrôle et l’envoi."],qc:["04 / CONTRÔLE","Une photo est une preuve, pas un verdict.","Utilisez une liste reproductible et agissez pendant la période de retour disponible."],shipping:["05 / LIVRAISON","Emballez selon la règle de facturation.","Estimez le poids réel et volumétrique, consolidez avec intention et utilisez la répétition d’emballage si nécessaire."],faq:["06 / FAQ","Des réponses avant de dépenser.","Questions courantes sur le tableur, l’entrepôt, le contrôle et l’expédition."],articles:["07 / NOTES","Des guides détaillés contre les erreurs coûteuses.","Des articles pratiques qui séparent les règles publiées du jugement de l’acheteur."]},
  it:{spreadsheet:["01 / FOGLIO","Un indice che porta alla pagina giusta.","Esplora per categoria, apri la scheda esatta e verifica l’inserzione prima di importare o ordinare."],finds:["02 / SELEZIONI","Immagine esatta. Pagina esatta.","Ogni esempio collega la prima immagine visibile alla pagina di dettaglio corrispondente."],guide:["03 / GUIDA","Prendi le decisioni rischiose prima di pagare.","Un percorso compatto per confrontare l’inserzione, confermare le opzioni, pianificare il controllo e la spedizione."],qc:["04 / CONTROLLO","Una foto è una prova, non un verdetto.","Usa una lista ripetibile e agisci entro la finestra di reso disponibile."],shipping:["05 / SPEDIZIONE","Imballa secondo la regola di addebito.","Stima peso reale e volumetrico, consolida con attenzione e usa la prova d’imballaggio quando serve."],faq:["06 / FAQ","Risposte brevi prima di spendere.","Domande comuni su foglio, magazzino, controllo e spedizione."],articles:["07 / NOTE","Guide lunghe contro gli errori costosi.","Articoli pratici che separano regole pubblicate e giudizio dell’acquirente."]},
};
