import type { Metadata } from "next";
import { ResourceShell } from "../components/ResourceShell";

export const metadata: Metadata = { title: "Superbuy Shipping Cost, Weight & Consolidation Guide", description: "A fact-checked Superbuy shipping guide covering the calculator, volumetric weight, deposit versus final charge, restrictions, consolidation and packaging.", alternates: { canonical: "/shipping/" } };

export default function ShippingPage() {
  return <ResourceShell eyebrow="Shipping cost" title="Estimate twice: before buying and after packing." intro="Superbuy’s official process separates the product payment from international delivery. The first estimate screens out impractical items; the second uses the intended parcel, current route eligibility and packaging choices." stats={[{ value: "100+", label: "shipping lines stated on official homepage" }, { value: "90 days", label: "official free storage" }, { value: "÷ 6,000", label: "air-cargo volume-weight example" }]}>
    <div className="content-grid">
      <article className="content-card"><span>Before ordering</span><h2>Use weight as a planning input</h2><p>Record an estimated item weight and consider whether the product is bulky, fragile, liquid, battery-powered or otherwise restricted on some routes.</p></article>
      <article className="content-card"><span>At the warehouse</span><h2>Consolidate with a purpose</h2><p>The official guide says stored items can be combined for overseas delivery and identifies 90 days of free storage. Group compatible items rather than waiting without a parcel plan.</p></article>
      <article className="content-card"><span>Before payment</span><h2>Compare eligible routes</h2><p>Review the estimated charge, delivery expectations, restrictions, insurance availability and packing needs after the intended parcel contents are selected.</p></article>
    </div>
    <div className="content-prose">
      <h2>Why the first estimate is not the final bill</h2><p>Superbuy’s published guide explains that the international shipping deposit is estimated from product weight, destination and the chosen shipping method. The final shipping fee is calculated using the package size and weight verified by the shipping company. The official guide says a difference between the deposit and final amount is returned to the user’s Superbuy account after shipment.</p>
      <p>The calculator also explains volume weight. For most air cargo in its example, volumetric weight in kilograms is length × width × height in centimetres divided by 6,000. A light but large parcel can therefore be charged above its scale weight. Treat that formula as a planning example, because individual routes may use different billing and eligibility rules.</p>
      <h2>Restrictions can remove a cheap route</h2><p>The current calculator separates general goods, textiles and leather, branded goods, liquids and powders, digital or electrical items, food and medicine, and other special categories. Its prohibited-item notice lists examples including perfume, simulation guns, banknotes, antiques, weapons, knives, gunpowder, drugs, lighters and high-risk chemicals. Superbuy’s User Guidance also says the interface recommends eligible routes for items with restrictions.</p>
      <p>That means route comparison should start with eligibility, not the lowest displayed number. A battery, liquid, famous-brand label, fragile form or food ingredient may reduce available choices. Destination rules and current notices can also change after an older guide or social-media screenshot was published.</p>
      <h2>Packaging changes the equation</h2><p>Removing unnecessary retail boxes can reduce dimensions, while reinforcement adds material and weight. Fragile items may justify stronger packaging even when it increases the charge. Suitable textiles may benefit from space-saving treatment, but shaped items can be damaged by compression. Choose services around the actual contents instead of repeating the same instruction for every parcel.</p>
      <div className="checklist"><div><i>✓</i><span>Destination and postal code confirmed</span></div><div><i>✓</i><span>Restricted-item labels reviewed</span></div><div><i>✓</i><span>Parcel contents selected for consolidation</span></div><div><i>✓</i><span>Estimated and chargeable weight understood</span></div><div><i>✓</i><span>Packaging and insurance choices recorded</span></div></div>
      <h2>Consolidate with a deadline and a compatibility plan</h2><p>The official guide states that stored items receive 90 days of free storage and can be consolidated. Consolidation can reduce repeated base charges, but a larger parcel may increase dimensional weight or eliminate a route. Track arrival dates, separate restricted goods when necessary and compare one large parcel against two intentional parcels before submission.</p>
      <div className="note-box"><b>Route information changes</b>Always use the current shipping calculator, destination and route notices immediately before submitting a parcel. A line mentioned in an older article may no longer be eligible, insured or competitively priced.</div>
    </div>
  </ResourceShell>;
}
