import type { Metadata } from "next";
import { ResourceShell } from "../components/ResourceShell";

export const metadata: Metadata = { title: "Superbuy QC Photos: Fact-Checked Inspection Guide", description: "Understand Superbuy's free QC photos, shopping-agent inspection limits, forwarding inspection differences and a category-specific review checklist.", alternates: { canonical: "/qc/" } };

export default function QCPage() {
  return <ResourceShell eyebrow="QC photos" title="Know what the warehouse checked—and what it did not." intro="Superbuy’s current homepage says three free QC photos are taken during warehouse inspection. Those images are useful evidence, but a small photo set cannot prove every material, measurement, internal component or hidden surface." stats={[{ value: "3", label: "free QC photos stated on official homepage" }, { value: "90 days", label: "official free storage window" }, { value: "Different", label: "forwarding inspection rules" }]}>
    <div className="content-grid">
      <article className="content-card"><span>Identity</span><h2>Is it the correct item?</h2><p>Match model, color, size label, quantity and included pieces. If the order is a set, check that every promised component is present.</p></article>
      <article className="content-card"><span>Construction</span><h2>Does the item look usable?</h2><p>Review seams, symmetry, hardware, closures, edges, print placement and visible damage under the available warehouse lighting.</p></article>
      <article className="content-card"><span>Fit evidence</span><h2>Do the measurements work?</h2><p>When fit matters, request or review a ruler photo and compare the measured garment—not only the label—with an item that already fits you.</p></article>
    </div>
    <div className="content-prose">
      <h2>Shopping-agent QC and forwarding inspection are not the same</h2><p>In the shopping-agent flow, Superbuy states that items are inspected after arrival and photographs are made available in the warehouse record. The company’s current forwarding guide is narrower: forwarded parcels are checked for restricted items by default, with no counting or professional quality inspection unless the user selects an inspection check. That difference is important when you bought the product yourself and only sent it to the warehouse.</p>
      <p>Superbuy also warns that 1688 purchases can follow different quality-control standards. Its 1688 guidance describes sampling inspection for eligible sellers and different after-sales conditions depending on the seller’s guarantees. Do not transfer a Taobao QC expectation to a wholesale order without checking the applicable order type and service.</p>
      <h2>A repeatable QC order</h2><p>Begin with facts that can make the entire order wrong: product identity, selected option and quantity. Then move to measurements and functional construction. Cosmetic details come last. This prevents spending time on a small stitch before noticing that the warehouse received the wrong size.</p>
      <div className="checklist"><div><i>1</i><span>Correct product, color, size and quantity</span></div><div><i>2</i><span>Front, back, sides and important close-ups are visible</span></div><div><i>3</i><span>Measurements are consistent with the intended fit</span></div><div><i>4</i><span>No obvious stains, holes, cracks or missing parts</span></div><div><i>5</i><span>Hardware, closures and printed details look aligned</span></div></div>
      <h2>Read the photographs in layers</h2><p>First compare the overall silhouette and color across every standard view. Warehouse lighting can shift color, so one overexposed image should not control the decision. Next inspect high-risk construction: shoe pair symmetry, sole attachment, garment seams, print alignment, bag handles, zippers, hardware, screen damage or missing accessories. Finally, ask whether the photographs actually show the detail you need.</p>
      <p>For clothing and footwear, measurements are usually more reliable than labels. Compare a ruler photo with an item you already own, using the same measurement method. If the seller size chart says one thing but the warehouse evidence suggests another, resolve that gap before international shipping.</p>
      <h2>Approve, question or use after-sales</h2><p>QC is not a universal pass/fail score. Approve when the correct item is present, measurements work and visible differences fall inside your tolerance. Ask for clarification or an available detailed-photo service when evidence is incomplete. Use the applicable after-sales process when the item is wrong, materially damaged or outside the accepted specification, while respecting the seller’s rules and time limits.</p>
      <div className="note-box"><b>Evidence limit</b>A previous buyer’s image or product-listing photo can teach you what to inspect, but it cannot prove the condition, measurements or exact option of the item stored for your order.</div>
    </div>
  </ResourceShell>;
}
