export const articleSlugs = ["hacoo-spreadsheet-guide", "hacoo-qc-photo-checklist", "hacoo-shipping-returns-guide", "hacoo-product-specification-checklist"] as const;
export type ArticleSlug = (typeof articleSlugs)[number];

export type ArticleRecord = {
  slug: ArticleSlug;
  title: string;
  description: string;
  readTime: string;
  updated: string;
  sections: { heading: string; paragraphs: string[] }[];
};

export const articles: Record<ArticleSlug, ArticleRecord> = {
  "hacoo-product-specification-checklist": {
    slug: "hacoo-product-specification-checklist",
    title: "Hacoo Product Specifications Checklist: Verify More Than Photos",
    description: "A field-by-field Hacoo product specification checklist for separating visible evidence, stated details, missing facts and pre-decision questions.",
    readTime: "11 min read",
    updated: "29 August 2026",
    sections: [
      { heading: "Why specifications need a separate checklist", paragraphs: ["The existing Hacoo QC photo guide explains what images can and cannot establish. A specification check answers a different question: what does the current page actually state about the exact candidate, and which decision fields remain missing? Hacoo describes itself as a lifestyle-discovery community in which independent creators publish content and connections. That context makes it important to distinguish a creator description, a visible image detail, a selected option and a formal policy statement. None should silently substitute for another. The aim is not to make a listing look complete. It is to create a compact record of supported facts, unknowns and questions before a candidate moves forward."] },
      { heading: "Freeze the identity before copying details", paragraphs: ["Record the final URL, displayed title, listing or content identifier when available, review date and exact selected option. Save enough context to identify the candidate again without relying on a thumbnail. Similar photographs may appear across posts or routes, while a destination can change after it is saved. Every specification must remain attached to this identity row. If a page redirects, the title changes or the option no longer exists, stop and re-establish identity before comparing any measurements, materials or included pieces. A technically working link proves access, not that it still represents the item you meant to assess."] },
      { heading: "Separate stated, visible and inferred information", paragraphs: ["Use three evidence labels. ‘Stated’ means the current page explicitly provides the detail. ‘Visible’ means the detail can be observed in one or more sufficiently clear images. ‘Inferred’ means the conclusion is only a reasonable interpretation. A zipper may be visible, but smooth operation is not. A woven surface may be visible, but exact fibre composition is not. A creator may call a shoe lightweight, but that is not a measured weight. Keep inferred details out of the confirmed column. This discipline prevents attractive photographs or confident captions from turning into unsupported product specifications."] },
      { heading: "Build a dimensions record for the category", paragraphs: ["Choose measurements that match the product's real use. Tops need chest, shoulder, sleeve and body length; bottoms need waist method, rise, thigh, inseam and leg opening; shoes need foot or internal-length guidance and relevant width context; bags need height, width, depth, strap range and opening dimensions. Record units and the measurement method. ‘Length 70’ is unusable without knowing centimetres or inches, garment or body, and the endpoints. When a field is absent, write ‘not stated.’ Never borrow a size chart or measurement from a similar-looking candidate."] },
      { heading: "Read material information without upgrading it", paragraphs: ["Copy material wording accurately and keep marketing phrases separate. ‘Cotton feel,’ ‘premium,’ ‘soft touch’ and ‘leather look’ are descriptions, not fibre percentages or material verification. If a composition is stated, note whether it applies to the shell, lining, filling, trim or outsole. Photographs can show texture and structure but not reliably establish fibre blend, coating, waterproof performance or durability. A useful record includes the stated specification, the visible support, and the unresolved practical question—such as breathability, stretch, lining or care—without inventing an answer."] },
      { heading: "Verify option, quantity and included pieces", paragraphs: ["Treat colour, size, bundle, quantity and accessories as one option block. Record the exact option text rather than a shortened memory label. A gallery may show several colours or styled accessories that are not included with every selection. Identify whether the price appears to refer to one unit, a set or an option-dependent bundle. For bags, note straps and pouches; for shoes, spare laces or boxes; for electronics, cables and adapters. If inclusion is not explicitly stated, mark it as unknown. An image containing two objects is not by itself proof that two units are supplied."] },
      { heading: "Check construction and functional features", paragraphs: ["List only features that affect the intended use: closure type, pocket count, lining, removable parts, adjustment range, sole pattern, ventilation, fastening and load-bearing attachment points. Confirm a feature with more than one view where perspective or styling could conceal it. Then separate presence from performance. A pocket can be visible without its usable depth being known. A hood can be shown without proving water resistance. A buckle can appear without a stated metal type. Turn every performance gap into a direct question or a reason to pause."] },
      { heading: "Record colour and finish with evidence limits", paragraphs: ["Use the displayed colour name and a neutral visual note, then record image conditions that may affect it. White balance, exposure, reflections, editing and screen settings can shift colour. Gloss, brushed surfaces and metallic finishes change across angles. Compare several views and look for a neutral reference, but do not publish an exact colour value unless a reliable source provides one. For outfit or category decisions, state the acceptable colour range and the consequence of mismatch. Colour uncertainty may be tolerable for a small accessory but decisive for a coordinated uniform or set."] },
      { heading: "Connect specifications to one intended use", paragraphs: ["A specification has value only when linked to a decision. Write the intended use, frequency and hard constraints before scoring the candidate. A commuter bag may require a secure closure, named capacity and strap range; a walking shoe may require internal length evidence, surface grip and room for the intended sock; a jacket may need to close over a measured layer. Mark every hard constraint pass, missing or fail. Do not average away a failure by adding decorative strengths. A candidate with excellent styling but unknown critical capacity remains unresolved."] },
      { heading: "Use a same-field comparison", paragraphs: ["Compare no more than three candidates using identical rows. If Candidate A states dimensions and B offers only a styled photograph, leave B blank rather than describing both as equally documented. Keep price and availability as dated snapshots, not specifications guaranteed into the future. The comparison should reveal evidence quality as well as product differences. A candidate can be visually appealing yet weakly documented. That may be an acceptable risk for a low-consequence decorative item, but it should be visible and intentional rather than hidden by a total score."] },
      { heading: "Turn missing fields into precise questions", paragraphs: ["A useful question names the exact option and requested fact: ‘For the black size M option, what is the flat chest width from underarm to underarm?’ is stronger than ‘Does it fit true to size?’ Ask whether the answer can realistically change the decision. If not, remove the field from the checklist. If a hard constraint cannot be verified through the current page or an appropriate official channel, pause or reject the candidate. Do not fill the gap from an unrelated review, another colour or a creator's general impression."] },
      { heading: "Final decision and recheck rule", paragraphs: ["Classify the record as ready, one-answer pending or archive. Ready means identity is stable, the exact option is recorded, every hard field passes and remaining uncertainty is acceptable. Pending means one answer could resolve the decision. Archive means identity, option or a hard specification fails or remains unverifiable. Before acting, reopen the final route and recheck the option, stated specifications and date-sensitive details. Save the comparison outcome without calling it a review or a guarantee. This checklist supports an evidence-led decision; it does not authenticate an item, promise quality or replace the current Hacoo interface and order-specific terms."] }
    ]
  },
  "hacoo-spreadsheet-guide": {
    slug: "hacoo-spreadsheet-guide",
    title: "Hacoo Spreadsheet Guide: How to Verify Links, Images and Listing IDs",
    description: "A practical method for using a Hacoo spreadsheet without confusing similar listings, stale links or unsupported product claims.",
    readTime: "8 min read",
    updated: "27 August 2026",
    sections: [
      { heading: "What people mean by a Hacoo spreadsheet", paragraphs: ["Hacoo’s official website describes Hacoo as an open content-sharing community built around lifestyle discovery, reviews and connections. The official pages reviewed for this guide do not present a public product spreadsheet. When shoppers search for a Hacoo spreadsheet, they are usually looking for something different: an independent, organized list of product routes that is easier to scan than an endless social feed. That distinction matters. A spreadsheet can help you discover and compare, but it is not an official Hacoo database, it does not prove that an item is available, and it cannot replace the current information on the live destination page."] },
      { heading: "Start with a narrow product intent", paragraphs: ["The fastest way to get lost is to begin with a vague phrase such as “best Hacoo finds.” Decide what you need before opening rows. A useful intent combines a category, an observable style and one decision constraint: low-top shoes with a simple outsole, a heavyweight hoodie with a measured chest width, or a small shoulder bag with visible hardware. Neutral descriptions are more reliable than brand-like wording because they focus the comparison on facts visible in the listing. They also make it easier to reject a row when the image, measurements or construction no longer match your original need."] },
      { heading: "The four fields every useful row needs", paragraphs: ["A maintained row should show at least four things: a category, the exact destination identifier, a lead image that matches the destination and the date the row was checked. Price can be included as an approximate reference, but it should never be presented as fixed. Stock, price, currency conversion and order-level charges can change after publication. The identifier is especially important because two products may use similar images or names. Save the ID before opening several tabs, then compare it again before acting. A row without an identifier or review date is a discovery hint, not reliable evidence."] },
      { heading: "Verify the image before reading the description", paragraphs: ["Open the destination and compare the first image with the spreadsheet card. Look at the overall silhouette, colour blocking, panel placement and visible accessories. Do not settle for “both are shoes” or “both are black hoodies.” A successful page load only proves that the URL works; it does not prove that the row still points to the intended item. If the main image is different, treat the route as mismatched even when the category is correct. This single check prevents one of the most common spreadsheet errors: a maintained-looking row that quietly redirects to a different product."] },
      { heading: "Use measurements instead of size labels", paragraphs: ["Size labels are comparison shortcuts, not universal measurements. For tops, record shoulder, chest, sleeve and body length when those values are available. For bottoms, look for waist, rise, thigh and inseam. For footwear, compare the stated foot-length guidance with a pair that already fits, and note whether the listing shows outsole or insole measurements. Measure a garment laid flat using the same method shown by the seller whenever possible. If the method is unclear, record the uncertainty instead of guessing. One careful measurement note is more useful than a row filled with unsupported fit claims."] },
      { heading: "Read photographs as evidence, not decoration", paragraphs: ["Product photography can answer specific questions when you inspect it methodically. Begin with shape and proportion, then symmetry, construction and visible defects. Zooming straight into labels or embroidery can distract from a distorted toe box, uneven panel or incorrect overall cut. Lighting may shift colour, and a wide-angle camera can exaggerate edges, so compare several angles. If a ruler or reference object appears, check whether it sits in the same plane as the product. Write down what the photograph establishes and what it cannot establish; long-term durability, material composition and authenticity cannot be proven by one attractive image."] },
      { heading: "Compare a small set, not dozens of tabs", paragraphs: ["A spreadsheet is most useful as a funnel. Open three to five candidates that meet the same intent, then remove any row with a mismatched image, missing measurements or unclear destination. Put the remaining candidates into a short comparison: current displayed price, useful measurements, visible construction, review date and unresolved questions. More tabs do not automatically improve a decision. They often increase the chance of mixing identifiers or remembering a feature from the wrong listing. A small, documented shortlist makes the final live-page check faster and provides a record if the destination changes later."] },
      { heading: "Treat prices and shipping figures as time-sensitive", paragraphs: ["The approximate USD amount shown by an independent index is orientation only. Confirm the live amount immediately before acting, and remember that product price is not the whole order cost. Hacoo’s official shipping page says receiving time is usually around 15–28 days, while its country groups range from 15–25 days for several European markets to 25–65 days for other countries. The same page says these are guidelines and not guaranteed delivery dates. A spreadsheet row should therefore avoid promising a final cost or arrival date. Record the date and source of every time-sensitive figure."] },
      { heading: "Recognize stale and low-quality spreadsheet rows", paragraphs: ["Warning signs include missing review dates, generic names that do not describe the image, copied promotional claims, prices presented as permanent and buttons that conceal the final destination. Another warning is volume without maintenance: thousands of rows sound impressive, but an unreviewed catalogue creates more wrong clicks than a smaller verified selection. Test several rows at random. If images repeatedly fail to match, identifiers are absent or links open unrelated categories, treat the entire sheet cautiously. Maintenance quality is a stronger trust signal than the headline number of finds."] },
      { heading: "Keep a simple verification log", paragraphs: ["For each shortlisted item, save the destination ID, the date checked, the lead-image match, relevant measurements and one sentence about visible construction. Add a screenshot only when it proves something that text cannot, such as a measurement diagram or a specific mismatch. Avoid copying customer images without permission. The log does not need to be elaborate; its purpose is to stop details from moving between similar listings and to make future rechecks quick. If the page later changes, you can identify exactly which part of the earlier decision is no longer supported."] },
      { heading: "Use the live search as the final step", paragraphs: ["After the spreadsheet narrows the category and style, use the live search or category route to check whether a better or more current listing exists. Search with neutral product clues or the saved identifier rather than an exaggerated marketing phrase. Reconfirm the image and price on the destination page. This site’s search form opens the designated live catalogue directly, while spreadsheet rows are independent editorial routes. That separation keeps discovery convenient without pretending the index controls inventory. If search results and the saved row disagree, the current destination should take priority."] },
      { heading: "Final checklist", paragraphs: ["Before deciding, confirm that the category matches your intent, the lead image matches the destination, the identifier is saved, measurements are useful, visible construction has been reviewed and the current price has been checked. Note the official shipping guidance without turning it into a promise. Keep evidence of the listing information you relied on and remove any candidate that requires too many assumptions. A good Hacoo spreadsheet does not make a decision for you. It reduces noise, exposes uncertainty and gives you a repeatable route from discovery to a better-informed live-page check."] }
    ]
  },
  "hacoo-qc-photo-checklist": {
    slug: "hacoo-qc-photo-checklist",
    title: "Hacoo QC Photo Checklist: 18 Checks Before You Decide",
    description: "A photo-led quality-control method for shoes, hoodies, jerseys and accessories, with clear limits on what images can prove.",
    readTime: "9 min read",
    updated: "27 August 2026",
    sections: [
      { heading: "Why a repeatable QC order matters", paragraphs: ["Quality control is more useful when every item is examined in the same order. Excitement encourages people to zoom into a logo or decorative detail while missing the shape, measurements or obvious damage that should decide the purchase first. Hacoo’s Trust Center emphasizes honest feedback, including negative details such as tight sizing or fabric that appears slightly transparent. That principle fits a strong QC process: record the visible strengths and flaws, do not hide inconvenient evidence, and do not turn one photograph into a claim the photograph cannot support. The checklist below moves from broad evidence to small details."] },
      { heading: "Checks 1–3: identity, silhouette and colour", paragraphs: ["First, confirm the photograph belongs to the same listing identifier you intend to open. Similar products and recycled captions can make an attractive image useless if the destination is wrong. Second, inspect the complete silhouette: height-to-width ratio, toe shape, shoulder line, hem shape or bag proportions. Third, compare colour across several images. Studio lighting, white balance and screen settings can shift colour, so look for consistency rather than an exact digital match. If only one heavily edited photograph exists, record colour as uncertain instead of treating it as a verified fact."] },
      { heading: "Checks 4–6: symmetry, alignment and proportions", paragraphs: ["Place the item mentally along a centre line. Compare left and right shoe panels, sleeve lengths, pocket positions, printed graphics and hardware placement. Small perspective changes can make one side appear larger, so use the straightest image available and confirm with another angle. Then compare the relative size of components: outsole thickness versus upper height, hood size versus shoulder width, or strap width versus bag body. These proportion checks often reveal a mismatch faster than examining tiny stitches. Avoid declaring a defect when the item is folded, tilted or photographed on an uneven surface."] },
      { heading: "Checks 7–9: measurements and scale", paragraphs: ["A ruler, measuring tape or known reference object turns a photograph into stronger evidence, but only when it is positioned correctly. Check whether the tape begins at zero, lies flat and follows the same measurement path described in the size chart. For clothing laid flat, doubling a chest width may approximate circumference, but only if that is the seller’s stated method. For bags and accessories, compare height, width and depth rather than relying on a model photograph. Camera distance can make foreground objects look larger, so prefer direct measurement images over lifestyle shots for size decisions."] },
      { heading: "Checks 10–12: seams, edges and closures", paragraphs: ["Trace major seam paths from beginning to end. Look for skipped stitches, loose thread clusters, puckering and abrupt changes in spacing. On printed or bonded edges, inspect lifting, cracking and uneven borders. Test visible closures conceptually: is a zipper track straight, are snaps aligned, and do buckles sit squarely? A still photograph cannot prove that a zipper moves smoothly, but it can reveal misalignment or damage worth questioning. For shoes, include the bond line where the upper meets the sole; for apparel, inspect high-stress areas such as underarms, pockets and crotch seams."] },
      { heading: "Checks 13–15: prints, embroidery and surface condition", paragraphs: ["Compare print placement with the garment centre, seams and pocket lines. Look for rippling, missing areas or colour bleed rather than judging only whether the design appears attractive. For embroidery, inspect density, loose threads and border consistency, while remembering that extreme zoom may exaggerate normal variation. Sweep the whole surface for stains, scratches, dents, glue residue, pulled fibres and pressure marks. Ask whether an apparent flaw could be packaging dust or reflected light. If a second angle does not resolve the question, label it as unresolved and request better evidence where that option exists."] },
      { heading: "Checks 16–18: completeness, packaging and final match", paragraphs: ["Confirm that visible accessories, laces, straps, removable parts or included pieces are present. Next, inspect packaging condition when photographs are available: crushing, moisture marks and torn protective material may affect what arrives even if the product itself looks correct. Finally, return to the destination page and repeat the identity check. The final image, identifier and selected option must still match the QC evidence. This last step prevents a careful review from being attached to the wrong colour, size or listing. Do not rely on memory after comparing several similar cards."] },
      { heading: "Footwear-specific review", paragraphs: ["For shoes, begin with the pair viewed together. Compare toe shape, heel height, panel symmetry and outsole curve. Then inspect each side, the top view, heel alignment and the sole pattern. Check whether the left and right shoe appear to be the same size and whether lace rows mirror each other. Close-ups of stitching and edge finishing are useful after the overall shape passes. A photograph cannot establish comfort, long-term sole adhesion or material composition. Use any length guidance carefully and compare it with a measured pair that already fits rather than choosing from the usual size label alone."] },
      { heading: "Hoodie and T-shirt review", paragraphs: ["For tops, check shoulder width, chest width, body length and sleeve length using the stated measurement method. Inspect whether the neckline sits evenly and whether the hem twists. Large prints should be centred relative to the garment, not merely centred within a cropped photograph. Examine the inside or fabric close-up if available, but avoid naming fibre content without a reliable source. For hoodies, compare hood volume, drawcord exits, pocket alignment and cuff shape. Sizing feedback can be helpful, but one reviewer’s preferred fit is not a universal rule; measurements remain the better comparison tool."] },
      { heading: "Jersey and accessory review", paragraphs: ["Jerseys require attention to panel joins, collar symmetry, number and name placement, and how graphics cross seams. Compare front and back proportions and record whether measurements refer to a flat garment. For bags, inspect strap anchors, zipper ends, base shape and hardware alignment. Small accessories need a scale reference because isolated product photos can make them appear larger. Do not infer metal type, waterproofing or carrying capacity from appearance alone. A useful QC note separates what is visible, what the listing states and what remains unknown."] },
      { heading: "How to use images responsibly in an article", paragraphs: ["Images strengthen a guide when each one proves a defined point. An annotated measurement, a side-by-side symmetry comparison or a close-up of a seam has more value than a decorative collage. Every image should have descriptive alternative text and a caption explaining what the reader should inspect. Use original, licensed or permitted material, and do not republish customer photographs without consent. If a screenshot is necessary, crop it to the relevant evidence and include the date and listing identifier. The written explanation should still make sense if an image fails to load."] },
      { heading: "Limits of photo-based QC", paragraphs: ["Photographs cannot reliably prove authenticity, exact material composition, odour, comfort, durability or how an item behaves after washing and wear. They can be edited, compressed or captured under misleading lighting. A responsible conclusion therefore uses confidence levels: verified from several clear views, likely but not confirmed, or unresolved. Avoid absolute language when the evidence is limited. The purpose of QC is not to manufacture certainty; it is to identify obvious problems, compare candidates consistently and make remaining uncertainty visible before a decision."] },
      { heading: "A concise decision rule", paragraphs: ["Reject the item when identity is unclear, the destination image does not match, important measurements are absent for a size-sensitive product, or photographs show a defect you would not accept. Pause when camera angle or lighting could explain the concern and better evidence may resolve it. Continue only when the overall shape, measurements, construction and selected option are consistent enough for your risk tolerance. Save the listing ID, review date and decisive photographs. That record is useful for comparison and for any later after-sale request, while still respecting that approval depends on the current official process."] }
    ]
  },
  "hacoo-shipping-returns-guide": {
    slug: "hacoo-shipping-returns-guide",
    title: "Hacoo Shipping and Returns Guide: Official Ranges, Tracking and Evidence",
    description: "A fact-checked explanation of Hacoo’s published delivery ranges, split parcels, address checks and 15-day after-sale window.",
    readTime: "8 min read",
    updated: "27 August 2026",
    sections: [
      { heading: "The official shipping range in context", paragraphs: ["Hacoo’s English shipping page says receiving time is usually about 15–28 days and explains that receiving time equals processing time plus shipping time. It then provides destination groups: 15–25 days for the United Kingdom, France, Germany and Italy; 15–30 days for Spain; and 25–65 days for other countries. These figures are useful planning ranges, not a promised arrival date. The same official page states that shipping times are guidelines and specific delivery dates are not guaranteed. Any article that converts these ranges into a certainty would misrepresent the source."] },
      { heading: "Processing and transport are different stages", paragraphs: ["The official page says normal order processing takes three to five business days. It also mentions that the fastest express shipping time can be five to seven working days. Processing happens before carrier movement and can include order confirmation, preparation or stock handling. A parcel that has not yet received meaningful tracking events may still be within processing rather than delayed in transit. When estimating an arrival window, keep processing and shipping separate, use business days where the source does, and let the current order-level estimate override a general guide when they differ."] },
      { heading: "Why delivery estimates can change", paragraphs: ["Hacoo notes that freight rules may change with logistics conditions and that regional or global disruption can slow delivery. It also says some products are shipped directly from overseas vendors, making delays difficult to avoid. Force majeure, carrier congestion, customs procedures, remote destinations and local final-mile capacity can all affect a parcel without changing the original product page. These possibilities should not be used as excuses for every delay, but they explain why a date range is more honest than a countdown. Keep the confirmation, tracking number and every material status update in one place."] },
      { heading: "Pre-orders, back-orders and split parcels", paragraphs: ["The official shipping page explains that if an order contains a pre-ordered or back-ordered item, available items may be shipped immediately and the unavailable items shipped later. A multi-item order can therefore arrive in more than one parcel. Before reporting missing contents, compare the received items with the order breakdown and check whether multiple tracking numbers or shipment notices exist. Photograph the parcel label and everything inside before discarding packaging. A partial delivery is not automatically a lost item, but it should be documented so that the remaining shipment can be identified accurately."] },
      { heading: "Check the address before processing advances", paragraphs: ["Hacoo’s official page places responsibility on the buyer to enter the correct shipping address and advises contacting support immediately when an error is discovered. The correction window may be short because processing is designed to move quickly. Check recipient name, house number, apartment or unit, postal code, city, country and telephone details before confirming. Do not assume a carrier can correct an incomplete address later. Save a screenshot of the submitted address and the time you contacted support if a correction is needed. Clear evidence is more useful than a general statement that the address was “almost right.”"] },
      { heading: "Read tracking as a sequence", paragraphs: ["Tracking is easiest to understand as stages: label or electronic information received, origin processing, export movement, destination processing, final-mile handoff and delivery. Not every carrier publishes all stages, and events may appear after a delay. Look for the last physical scan rather than repeatedly reading an unchanged estimated date. If a parcel changes carriers, save both tracking numbers. A long gap can justify a support question, but the relevant threshold depends on the route and official estimate. Compare the parcel’s actual age with the destination range instead of using another customer’s faster delivery as the standard."] },
      { heading: "When tracking says delivered", paragraphs: ["The official Hacoo shipping page says that when tracking reports delivery but the parcel is not present, the customer should report it to the relevant shipping carrier using the information on the tracking page. First check safe places, household members, building reception and any delivery photograph. Record the time, status wording and carrier reference before contacting the carrier. Do not edit or crop away identifying tracking details in your private evidence. If further support is needed, provide a concise timeline showing the delivery scan, the checks you completed and the carrier response."] },
      { heading: "The published 15-day after-sale window", paragraphs: ["Hacoo’s shipping page states that customers who are dissatisfied or encounter an issue can request after-sale support within 15 days of delivery. It also says customers must follow the refund instructions. This does not mean every request is automatically eligible or approved. The delivery date, evidence, current regional instructions and the specific issue matter. Treat 15 days as a prompt to inspect the order quickly and begin the official process when necessary, not as a guarantee of outcome. Recheck the current official wording when the issue occurs because policies can change."] },
      { heading: "Build evidence before opening a request", paragraphs: ["If the parcel appears damaged, photograph it before opening from several angles, including the label and damaged area. Record the unboxing in a continuous sequence when practical, then photograph the item, packaging and included parts. Compare the item with the saved listing image, identifier, selected option and measurements. Describe observable differences: a missing accessory, a 4 cm measurement discrepancy or a visible tear is more actionable than “bad quality.” Keep original files with timestamps and avoid filters. Good evidence does not guarantee approval, but it makes the request clear and reduces ambiguity."] },
      { heading: "Separate product dissatisfaction from shipping damage", paragraphs: ["A product that differs from expectations, an item damaged in transit, a parcel marked delivered but missing and an incorrect size selection are different problems. Each needs a different timeline and evidence set. Shipping damage begins with parcel condition and carrier handling. A product mismatch begins with the listing, selected option and received item. A delivered-but-missing case begins with the carrier scan and location checks. Separating these issues prevents a support request from becoming a long, confusing narrative. State one primary issue, attach the strongest evidence and answer follow-up questions directly."] },
      { heading: "Plan a lower-risk first order", paragraphs: ["A first order is easier to evaluate when it contains a small number of items with clear measurements and current images. Avoid combining many uncertain products, time-sensitive gifts and difficult-to-size items in one experiment. Confirm the live product amount and review the order-level shipping information before payment. Save the listing IDs and decisive screenshots. The objective is not to eliminate every risk—cross-border delivery always includes variables—but to keep the number of unknowns manageable and to learn how processing, tracking and delivery work on your route."] },
      { heading: "Practical timeline and final checklist", paragraphs: ["Before ordering, verify the address, selected options, live price, item images and measurements. During processing, save confirmation details and note whether any item is pre-ordered or back-ordered. In transit, follow the last physical scan and watch for a carrier handoff or split shipment. On delivery, photograph damaged packaging, check every item promptly and retain labels until the order is confirmed complete. If there is a problem, use the official process within the published 15-day window and provide dated, specific evidence. Always treat the official country ranges as guidance, not a guaranteed delivery promise."] }
    ]
  }
};

export const articleList = articleSlugs.map((slug) => articles[slug]);
