import type { Metadata } from "next";
import { getArticleList } from "./article-locales";
import { editorialUi } from "./editorial-ui";

export const languages = ["en", "es", "fr", "de", "it"] as const;
export type Lang = (typeof languages)[number];
export const pages = ["home", "spreadsheet", "finds", "categories", "faq", "shipping", "qc", "guide", "articles"] as const;
export type PageKey = (typeof pages)[number];
export const publicPages = ["home", "spreadsheet", "categories", "faq", "shipping", "qc", "guide", "articles"] as const;

const DEST = "https://cnfanshp.com";

const categoryLinks = ["/shoes/","/hoodies-sweaters/","/t-shirts/","/jackets/","/pants-shorts/","/headwear/","/accessories/","/jersey/"] as const;
const products = [
  ["6045","","/AllProducts/6045.html","/uploads/allimg/20260417/1-26041G55S9251.jpg","SHOES"],
  ["5974","","/AllProducts/5974.html","/uploads/allimg/20260417/1-26041G1101D39.webp","SWEATSHIRTS"],
  ["5976","","/AllProducts/5976.html","/uploads/allimg/20260417/1-26041G1121Q55.webp","T-SHIRTS"],
  ["5981","","/AllProducts/5981.html","/uploads/allimg/20260417/1-26041G1193O56.webp","JACKETS"],
  ["5983","","/AllProducts/5983.html","/uploads/allimg/20260417/1-26041G1212V39.webp","BOTTOMS"],
  ["5971","","/AllProducts/5971.html","/uploads/allimg/20260417/1-26041G10Fc05.webp","HEADWEAR"],
] as const;

type PageCopy = { kicker:string; title:string; intro:string; facts:string[]; cta:string };
type Copy = {
  nav:Record<Exclude<PageKey,"home">,string>; lang:string; search:string; hint:string; open:string; browse:string; listing:string;
  independent:string; disclaimer:string; updated:string; approx:string; section:[string,string,string,string]; categories:[string,string][];
  pages:Record<PageKey,PageCopy>;
};

const copy:Record<Lang,Copy> = {
en:{
 nav:{spreadsheet:"Spreadsheet",finds:"Finds",categories:"Categories",faq:"FAQ",shipping:"Shipping",qc:"QC",guide:"Guide",articles:"Articles"},lang:"Language",search:"Search live listings",hint:"Keyword, product clue or ID",open:"Open route",browse:"Browse live destination",listing:"Listing",independent:"Independent Hacoo research desk — not the official Hacoo website.",disclaimer:"Listing prices, availability and shipping estimates can change. Confirm the live destination page before acting.",updated:"Checked 10 Oct 2026",approx:"Approx. USD — confirm live amount",section:["Desk routes","Category index","Current find cards","Evidence notes"],
 categories:[["Shoes","Footwear routes and size-first checks"],["Sweatshirts","Layers, measurements and fabric notes"],["T-Shirts","Graphics, blanks and fit references"],["Jackets","Outerwear, structure and detail checks"],["Pants & Shorts","Waist, rise and inseam references"],["Headwear","Caps, beanies and sizing details"],["Accessories","Bags, small goods and add-ons"],["Jerseys","Team styles and measurement checks"]],
 pages:{
  home:{kicker:"HACOO / FIELD DESK 2026",title:"Hacoo finds, without the guesswork.",intro:"A bright, independent index for product discovery, QC decisions, shipping context and the questions people ask before opening a listing.",facts:["Hacoo describes itself as an open content-sharing community; this desk focuses on the practical product-search gap.","Every category, search and product action opens the designated live destination—no hidden platform detours.","Facts are dated and attributed; estimates are never presented as guarantees."],cta:"Start with the live finds"},
  spreadsheet:{kicker:"ROUTE 01 / SPREADSHEET",title:"A spreadsheet built like an evidence desk.",intro:"Use categories, identifiers and decision notes instead of scrolling an unexplained wall of links.",facts:["Start with category intent, then compare the exact lead image on the destination page.","Treat displayed USD figures as approximate until the live listing confirms the current amount.","Record size clues, image date and destination ID before shortlisting similar items."],cta:"Open spreadsheet finds"},
  finds:{kicker:"ROUTE 02 / FINDS",title:"Useful finds with a visible trail.",intro:"Each card keeps the lead image, destination and approximate price together so the click is predictable.",facts:["Cards use images served by the same destination as the product detail link.","Neutral listing names avoid inventing product claims that the source page does not verify.","A small reviewed set is more useful than a huge unmaintained link dump."],cta:"Browse current finds"},
  categories:{kicker:"ROUTE 03 / CATEGORIES",title:"Begin with what you actually need.",intro:"Category routes reduce search noise and give each product decision a clearer comparison set.",facts:["Footwear checks should begin with size references and outsole shape.","Apparel comparisons work better with shoulder, chest, length and fabric clues.","Accessories need scale, hardware and attachment-point checks before visual hype."],cta:"Choose a category"},
  faq:{kicker:"ROUTE 04 / FAQ",title:"Straight answers, careful boundaries.",intro:"The useful answer separates an official rule, an order estimate and a buyer decision.",facts:["Is this official? No. It is an independent research and routing site.","Are prices guaranteed? No. USD figures are approximate and the live page controls.","Are returns universal? No. Official Hacoo help pages describe eligibility, exclusions and approval steps."],cta:"Search a live listing"},
  shipping:{kicker:"ROUTE 05 / SHIPPING",title:"Read the timeline in stages.",intro:"Official Hacoo help material breaks delivery into preparation, shipping and final delivery—not one universal promise.",facts:["One official EU help page states 3–7 days preparation, 7–15 days shipping and 5–10 days final delivery: 15–28 days total.","Another official page shows slightly different processing ranges, so the order-level estimate should control.","An official fee FAQ says parcels above 3 kg add a charge per extra 0.5 kg; confirm the current regional rule before paying."],cta:"Plan a smaller first order"},
  qc:{kicker:"ROUTE 06 / QC",title:"Inspect evidence, not excitement.",intro:"A repeatable QC pass checks shape, measurements, symmetry, construction and visible flaws in that order.",facts:["Compare overall silhouette before zooming into labels or stitching.","Use a ruler or measurement reference; camera angle alone can distort proportion.","Save the listing ID with QC notes so two similar cards are not confused later."],cta:"Find an item to inspect"},
  guide:{kicker:"ROUTE 07 / GUIDE",title:"Build the decision before the parcel.",intro:"Search, verify, compare, estimate and only then decide—the sequence matters more than the hype.",facts:["Match the lead image and destination ID first.","Compare measurements and visible construction second.","Add item cost, possible shipping stages and return limits before deciding."],cta:"Begin the buying guide"},
  articles:{kicker:"HACOO / EN",title:editorialUi.en.title,intro:editorialUi.en.intro,facts:[],cta:editorialUi.en.all}
 }},
es:{
 nav:{spreadsheet:"Hoja",finds:"Hallazgos",categories:"Categorías",faq:"Preguntas",shipping:"Envío",qc:"Control QC",guide:"Guía",articles:"Artículos"},lang:"Idioma",search:"Buscar listados activos",hint:"Palabra clave, pista o ID",open:"Abrir ruta",browse:"Ver destino activo",listing:"Listado",independent:"Mesa independiente sobre Hacoo; no es el sitio oficial de Hacoo.",disclaimer:"Precios, disponibilidad y plazos pueden cambiar. Confirma siempre la página de destino.",updated:"Revisado el 10 oct 2026",approx:"USD aproximados; confirma el importe",section:["Rutas de la mesa","Índice de categorías","Fichas actuales","Notas verificables"],
 categories:[["Calzado","Rutas y comprobaciones de talla"],["Sudaderas","Medidas, capas y tejido"],["Camisetas","Gráficos, básicos y ajuste"],["Chaquetas","Estructura y detalles"],["Pantalones","Cintura, tiro y largo"],["Gorras","Talla y detalles"],["Accesorios","Bolsos y pequeños artículos"],["Camisetas deportivas","Estilos y medidas"]],
 pages:{
  home:{kicker:"HACOO / MESA 2026",title:"Hallazgos Hacoo sin adivinanzas.",intro:"Un índice independiente para descubrir productos, revisar QC, entender el envío y resolver dudas antes de abrir un listado.",facts:["Hacoo se define como una comunidad abierta de contenidos; esta mesa cubre la necesidad práctica de búsqueda de productos.","Cada categoría, búsqueda y producto abre el destino activo indicado, sin desvíos ocultos.","Los datos llevan fecha y atribución; las estimaciones nunca se presentan como garantías."],cta:"Empezar con los hallazgos"},
  spreadsheet:{kicker:"RUTA 01 / HOJA",title:"Una hoja organizada como mesa de pruebas.",intro:"Usa categorías, identificadores y notas en lugar de una pared de enlaces sin explicación.",facts:["Empieza por la categoría y compara la imagen principal exacta en el destino.","Considera los importes en USD aproximados hasta confirmarlos en el listado activo.","Anota talla, fecha de imagen e ID antes de comparar artículos similares."],cta:"Abrir los hallazgos"},
  finds:{kicker:"RUTA 02 / HALLAZGOS",title:"Hallazgos útiles con rastro visible.",intro:"Cada ficha une imagen, destino y precio aproximado para que el clic sea predecible.",facts:["Las imágenes proceden del mismo destino que el enlace de detalle.","Los nombres neutrales evitan afirmaciones que la fuente no confirma.","Una selección pequeña y revisada vale más que una lista abandonada."],cta:"Ver hallazgos actuales"},
  categories:{kicker:"RUTA 03 / CATEGORÍAS",title:"Empieza por lo que realmente necesitas.",intro:"Las rutas por categoría reducen ruido y crean grupos de comparación claros.",facts:["En calzado, empieza por talla, forma y suela.","En ropa, compara hombros, pecho, largo y tejido.","En accesorios, revisa escala, herrajes y puntos de unión."],cta:"Elegir categoría"},
  faq:{kicker:"RUTA 04 / PREGUNTAS",title:"Respuestas directas con límites claros.",intro:"Una respuesta útil separa la norma oficial, la estimación del pedido y la decisión del comprador.",facts:["¿Es oficial? No; es un sitio independiente de investigación y rutas.","¿El precio está garantizado? No; el listado activo manda.","¿Todas las devoluciones aplican? No; la ayuda oficial describe requisitos, exclusiones y aprobación."],cta:"Buscar un listado"},
  shipping:{kicker:"RUTA 05 / ENVÍO",title:"Lee el plazo por etapas.",intro:"La ayuda oficial divide la entrega entre preparación, transporte y última entrega.",facts:["Una página oficial europea indica 3–7 días de preparación, 7–15 de transporte y 5–10 de entrega final: 15–28 días.","Otra página oficial muestra rangos algo distintos; debe prevalecer la estimación del pedido.","Una FAQ oficial indica un recargo por cada 0,5 kg por encima de 3 kg; confirma la regla regional."],cta:"Planear un primer pedido pequeño"},
  qc:{kicker:"RUTA 06 / QC",title:"Inspecciona pruebas, no entusiasmo.",intro:"Una revisión repetible observa forma, medidas, simetría, construcción y defectos visibles.",facts:["Compara primero la silueta general.","Usa una referencia de medida; el ángulo de cámara distorsiona.","Guarda el ID junto a las notas QC para no mezclar artículos."],cta:"Buscar un artículo"},
  guide:{kicker:"RUTA 07 / GUÍA",title:"Decide antes de formar el paquete.",intro:"Busca, verifica, compara, calcula y solo entonces decide.",facts:["Comprueba imagen principal e ID.","Compara medidas y construcción visible.","Suma artículo, posibles fases de envío y límites de devolución."],cta:"Empezar la guía"},
  articles:{kicker:"HACOO / ES",title:editorialUi.es.title,intro:editorialUi.es.intro,facts:[],cta:editorialUi.es.all}
 }},
fr:{
 nav:{spreadsheet:"Tableur",finds:"Sélections",categories:"Catégories",faq:"FAQ",shipping:"Livraison",qc:"Contrôle QC",guide:"Guide",articles:"Articles"},lang:"Langue",search:"Rechercher les offres actives",hint:"Mot-clé, indice ou identifiant",open:"Ouvrir la route",browse:"Voir la destination",listing:"Offre",independent:"Bureau de recherche Hacoo indépendant — ce site n’est pas le site officiel.",disclaimer:"Prix, disponibilité et délais peuvent changer. Vérifiez la page de destination.",updated:"Vérifié le 10 octobre 2026",approx:"USD approximatifs — vérifier le montant",section:["Routes du bureau","Index des catégories","Fiches actuelles","Notes factuelles"],
 categories:[["Chaussures","Tailles, formes et routes"],["Sweats","Mesures, couches et tissus"],["T-shirts","Motifs, bases et coupe"],["Vestes","Structure et détails"],["Pantalons","Taille, fourche et longueur"],["Couvre-chefs","Tailles et détails"],["Accessoires","Sacs et petits articles"],["Maillots","Styles et mesures"]],
 pages:{
  home:{kicker:"HACOO / BUREAU 2026",title:"Les trouvailles Hacoo, sans deviner.",intro:"Un index indépendant pour trouver des produits, contrôler le QC, comprendre la livraison et préparer chaque clic.",facts:["Hacoo se présente comme une communauté ouverte de partage; ce bureau traite le besoin pratique de recherche produit.","Chaque catégorie, recherche et produit ouvre la destination active prévue, sans détour caché.","Les faits sont datés et attribués; les estimations ne sont jamais des garanties."],cta:"Commencer par les sélections"},
  spreadsheet:{kicker:"ROUTE 01 / TABLEUR",title:"Un tableur conçu comme un bureau de preuves.",intro:"Utilisez catégories, identifiants et notes plutôt qu’un mur de liens sans contexte.",facts:["Commencez par la catégorie et comparez l’image principale exacte.","Considérez les prix USD comme approximatifs jusqu’à vérification.","Notez taille, date d’image et identifiant avant de comparer."],cta:"Ouvrir les sélections"},
  finds:{kicker:"ROUTE 02 / SÉLECTIONS",title:"Des trouvailles avec une trace visible.",intro:"Chaque fiche garde ensemble image, destination et prix approximatif.",facts:["L’image vient de la même destination que la fiche produit.","Des noms neutres évitent les affirmations non vérifiées.","Une petite sélection entretenue vaut mieux qu’une immense liste abandonnée."],cta:"Voir les sélections"},
  categories:{kicker:"ROUTE 03 / CATÉGORIES",title:"Commencez par votre besoin réel.",intro:"Les catégories réduisent le bruit et créent de meilleurs groupes de comparaison.",facts:["Pour les chaussures, vérifiez taille, forme et semelle.","Pour les vêtements, comparez épaules, poitrine, longueur et tissu.","Pour les accessoires, contrôlez échelle, métal et attaches."],cta:"Choisir une catégorie"},
  faq:{kicker:"ROUTE 04 / FAQ",title:"Des réponses nettes, avec leurs limites.",intro:"Une bonne réponse distingue règle officielle, estimation de commande et décision personnelle.",facts:["Site officiel ? Non, c’est un bureau indépendant.","Prix garanti ? Non, la page active fait foi.","Retours universels ? Non, l’aide officielle prévoit conditions, exclusions et validation."],cta:"Rechercher une offre"},
  shipping:{kicker:"ROUTE 05 / LIVRAISON",title:"Lisez le délai par étapes.",intro:"L’aide officielle sépare préparation, transport et livraison finale.",facts:["Une aide européenne indique 3–7 jours de préparation, 7–15 de transport et 5–10 de livraison finale, soit 15–28 jours.","Une autre page officielle affiche des plages différentes; l’estimation de la commande doit primer.","Une FAQ officielle mentionne un supplément par 0,5 kg au-delà de 3 kg; vérifiez la règle régionale."],cta:"Préparer une petite première commande"},
  qc:{kicker:"ROUTE 06 / QC",title:"Inspectez les preuves, pas l’enthousiasme.",intro:"Un contrôle reproductible examine forme, mesures, symétrie, construction et défauts visibles.",facts:["Comparez d’abord la silhouette générale.","Utilisez une référence de mesure; l’angle déforme.","Conservez l’identifiant avec les notes QC."],cta:"Trouver un article"},
  guide:{kicker:"ROUTE 07 / GUIDE",title:"Construisez la décision avant le colis.",intro:"Cherchez, vérifiez, comparez, estimez, puis décidez.",facts:["Vérifiez image et identifiant.","Comparez mesures et construction visible.","Ajoutez coût, étapes de livraison et limites de retour."],cta:"Commencer le guide"},
  articles:{kicker:"HACOO / FR",title:editorialUi.fr.title,intro:editorialUi.fr.intro,facts:[],cta:editorialUi.fr.all}
 }},
de:{
 nav:{spreadsheet:"Tabelle",finds:"Funde",categories:"Kategorien",faq:"FAQ",shipping:"Versand",qc:"QC-Prüfung",guide:"Leitfaden",articles:"Artikel"},lang:"Sprache",search:"Aktive Angebote suchen",hint:"Suchwort, Hinweis oder ID",open:"Route öffnen",browse:"Aktives Ziel öffnen",listing:"Angebot",independent:"Unabhängiger Hacoo-Recherchebereich — keine offizielle Hacoo-Website.",disclaimer:"Preise, Bestand und Lieferzeiten können sich ändern. Die Zielseite ist maßgeblich.",updated:"Geprüft am 10. Okt. 2026",approx:"USD ungefähr — live bestätigen",section:["Bereichsrouten","Kategorieindex","Aktuelle Fundkarten","Faktennotizen"],
 categories:[["Schuhe","Größen, Formen und Routen"],["Sweatshirts","Maße, Lagen und Stoffe"],["T-Shirts","Grafiken, Basics und Passform"],["Jacken","Struktur und Details"],["Hosen","Bund, Leibhöhe und Länge"],["Kopfbedeckung","Größen und Details"],["Accessoires","Taschen und Kleinteile"],["Trikots","Styles und Maße"]],
 pages:{
  home:{kicker:"HACOO / FELDBÜRO 2026",title:"Hacoo-Funde ohne Rätselraten.",intro:"Ein unabhängiger Index für Produktsuche, QC-Entscheidungen, Versandkontext und Fragen vor dem Klick.",facts:["Hacoo beschreibt sich als offene Content-Community; dieses Büro schließt die praktische Produktsuchlücke.","Jede Kategorie, Suche und Produktkarte öffnet das festgelegte aktive Ziel ohne versteckte Umwege.","Fakten sind datiert und zugeordnet; Schätzungen sind keine Garantien."],cta:"Mit aktuellen Funden starten"},
  spreadsheet:{kicker:"ROUTE 01 / TABELLE",title:"Eine Tabelle wie ein Prüfplatz.",intro:"Kategorien, Kennungen und Entscheidungsnotizen ersetzen eine ungeklärte Linkwand.",facts:["Mit der Kategorie beginnen und das exakte Titelbild am Ziel prüfen.","USD-Angaben bis zur Live-Bestätigung als ungefähr behandeln.","Größe, Bilddatum und Ziel-ID vor dem Vergleich notieren."],cta:"Tabellenfunde öffnen"},
  finds:{kicker:"ROUTE 02 / FUNDE",title:"Nützliche Funde mit sichtbarer Spur.",intro:"Bild, Ziel und ungefährer Preis bleiben auf jeder Karte zusammen.",facts:["Das Bild stammt vom selben Ziel wie der Produktlink.","Neutrale Namen vermeiden unbelegte Behauptungen.","Eine kleine gepflegte Auswahl ist besser als eine riesige veraltete Liste."],cta:"Aktuelle Funde ansehen"},
  categories:{kicker:"ROUTE 03 / KATEGORIEN",title:"Beginne mit dem echten Bedarf.",intro:"Kategorien senken Suchrauschen und schaffen klare Vergleichsgruppen.",facts:["Bei Schuhen zuerst Größe, Form und Sohle prüfen.","Bei Kleidung Schulter, Brust, Länge und Stoff vergleichen.","Bei Accessoires Maßstab, Beschläge und Befestigungen prüfen."],cta:"Kategorie wählen"},
  faq:{kicker:"ROUTE 04 / FAQ",title:"Klare Antworten mit klaren Grenzen.",intro:"Nützliche Antworten trennen offizielle Regel, Bestellschätzung und Käuferentscheidung.",facts:["Offiziell? Nein, dies ist ein unabhängiger Recherchebereich.","Preis garantiert? Nein, die aktive Zielseite entscheidet.","Rückgabe immer möglich? Nein, die offizielle Hilfe nennt Bedingungen, Ausschlüsse und Freigaben."],cta:"Angebot suchen"},
  shipping:{kicker:"ROUTE 05 / VERSAND",title:"Die Zeit in Etappen lesen.",intro:"Offizielle Hilfe trennt Vorbereitung, Versand und letzte Zustellung.",facts:["Eine EU-Hilfeseite nennt 3–7 Tage Vorbereitung, 7–15 Versand und 5–10 letzte Zustellung: insgesamt 15–28 Tage.","Eine andere offizielle Seite nennt leicht andere Spannen; die Bestellschätzung ist maßgeblich.","Eine offizielle FAQ nennt über 3 kg einen Zuschlag je weitere 0,5 kg; regionale Regel prüfen."],cta:"Kleine erste Bestellung planen"},
  qc:{kicker:"ROUTE 06 / QC",title:"Belege prüfen, nicht Begeisterung.",intro:"Ein wiederholbarer QC-Check prüft Form, Maße, Symmetrie, Verarbeitung und sichtbare Mängel.",facts:["Zuerst die Gesamtsilhouette vergleichen.","Messreferenz nutzen; Kamerawinkel verzerren.","Ziel-ID zusammen mit QC-Notizen speichern."],cta:"Artikel zum Prüfen finden"},
  guide:{kicker:"ROUTE 07 / LEITFADEN",title:"Die Entscheidung vor dem Paket bauen.",intro:"Suchen, prüfen, vergleichen, schätzen und erst dann entscheiden.",facts:["Titelbild und Ziel-ID abgleichen.","Maße und sichtbare Verarbeitung vergleichen.","Artikel, Versandstufen und Rückgabegrenzen zusammenrechnen."],cta:"Leitfaden beginnen"},
  articles:{kicker:"HACOO / DE",title:editorialUi.de.title,intro:editorialUi.de.intro,facts:[],cta:editorialUi.de.all}
 }},
it:{
 nav:{spreadsheet:"Foglio",finds:"Selezioni",categories:"Categorie",faq:"FAQ",shipping:"Spedizione",qc:"Controllo QC",guide:"Guida",articles:"Articoli"},lang:"Lingua",search:"Cerca inserzioni attive",hint:"Parola chiave, indizio o ID",open:"Apri percorso",browse:"Apri destinazione",listing:"Inserzione",independent:"Desk di ricerca Hacoo indipendente — non è il sito ufficiale Hacoo.",disclaimer:"Prezzi, disponibilità e tempi possono cambiare. Verifica la pagina di destinazione.",updated:"Verificato il 10 ott 2026",approx:"USD approssimativi — verifica online",section:["Percorsi del desk","Indice categorie","Schede attuali","Note basate sui fatti"],
 categories:[["Scarpe","Taglie, forme e percorsi"],["Felpe","Misure, strati e tessuti"],["T-shirt","Grafiche, basi e vestibilità"],["Giacche","Struttura e dettagli"],["Pantaloni","Vita, cavallo e lunghezza"],["Copricapi","Taglie e dettagli"],["Accessori","Borse e piccoli articoli"],["Maglie sportive","Stili e misure"]],
 pages:{
  home:{kicker:"HACOO / DESK 2026",title:"Selezioni Hacoo senza supposizioni.",intro:"Un indice indipendente per scoprire prodotti, valutare QC, capire la spedizione e preparare ogni clic.",facts:["Hacoo si descrive come comunità aperta di condivisione; questo desk copre il bisogno pratico di ricerca prodotti.","Categorie, ricerche e prodotti aprono la destinazione attiva prevista, senza deviazioni nascoste.","I fatti sono datati e attribuiti; le stime non sono garanzie."],cta:"Inizia dalle selezioni"},
  spreadsheet:{kicker:"PERCORSO 01 / FOGLIO",title:"Un foglio costruito come desk di verifica.",intro:"Categorie, identificatori e note decisionali sostituiscono una parete di link senza contesto.",facts:["Parti dalla categoria e confronta l’immagine principale esatta.","Considera i valori USD approssimativi fino alla conferma online.","Registra taglia, data immagine e ID prima del confronto."],cta:"Apri le selezioni"},
  finds:{kicker:"PERCORSO 02 / SELEZIONI",title:"Selezioni utili con traccia visibile.",intro:"Ogni scheda mantiene insieme immagine, destinazione e prezzo approssimativo.",facts:["L’immagine proviene dalla stessa destinazione del link prodotto.","Nomi neutrali evitano affermazioni non verificate.","Una selezione piccola e curata vale più di migliaia di link abbandonati."],cta:"Vedi le selezioni"},
  categories:{kicker:"PERCORSO 03 / CATEGORIE",title:"Inizia da ciò che ti serve davvero.",intro:"Le categorie riducono il rumore e creano gruppi di confronto chiari.",facts:["Per le scarpe, controlla taglia, forma e suola.","Per l’abbigliamento, confronta spalle, torace, lunghezza e tessuto.","Per gli accessori, verifica scala, metalli e attacchi."],cta:"Scegli categoria"},
  faq:{kicker:"PERCORSO 04 / FAQ",title:"Risposte dirette, confini chiari.",intro:"Una risposta utile separa regola ufficiale, stima dell’ordine e decisione personale.",facts:["È ufficiale? No, è un desk indipendente.","Prezzo garantito? No, conta la pagina attiva.","Resi sempre validi? No, l’assistenza ufficiale indica requisiti, esclusioni e approvazione."],cta:"Cerca un’inserzione"},
  shipping:{kicker:"PERCORSO 05 / SPEDIZIONE",title:"Leggi i tempi per fasi.",intro:"L’assistenza ufficiale divide preparazione, trasporto e consegna finale.",facts:["Una pagina europea indica 3–7 giorni di preparazione, 7–15 di trasporto e 5–10 di consegna finale: 15–28 giorni.","Un’altra pagina ufficiale mostra intervalli diversi; deve prevalere la stima dell’ordine.","Una FAQ ufficiale indica un supplemento ogni 0,5 kg oltre 3 kg; verifica la regola regionale."],cta:"Pianifica un primo ordine piccolo"},
  qc:{kicker:"PERCORSO 06 / QC",title:"Controlla le prove, non l’entusiasmo.",intro:"Un controllo ripetibile esamina forma, misure, simmetria, costruzione e difetti visibili.",facts:["Confronta prima la silhouette generale.","Usa un riferimento di misura; l’angolo distorce.","Salva l’ID insieme alle note QC."],cta:"Trova un articolo"},
  guide:{kicker:"PERCORSO 07 / GUIDA",title:"Costruisci la decisione prima del pacco.",intro:"Cerca, verifica, confronta, stima e solo dopo decidi.",facts:["Abbina immagine principale e ID.","Confronta misure e costruzione visibile.","Somma articolo, fasi di spedizione e limiti di reso."],cta:"Inizia la guida"},
  articles:{kicker:"HACOO / IT",title:editorialUi.it.title,intro:editorialUi.it.intro,facts:[],cta:editorialUi.it.all}
 }}
};

export function routePath(lang:Lang,page:PageKey){const base=lang==="en"?"":`/${lang}`;return page==="home"?`${base}/`:`${base}/${page}/`;}
export function articleRoutePath(lang:Lang,slug:string){return lang==="en"?`/articles/${slug}/`:`/${lang}/articles/${slug}/`;}
export function parseRoute(slug:string[]):{lang:Lang;page:PageKey}|null{
 if(!slug?.length)return{lang:"en",page:"home"}; const first=slug[0] as Lang;
 if(languages.includes(first)&&first!=="en"){const page=(slug[1]||"home") as PageKey;return slug.length<=2&&publicPages.includes(page as (typeof publicPages)[number])?{lang:first,page}:null;}
 const page=first as PageKey;return slug.length===1&&page!=="home"&&publicPages.includes(page as (typeof publicPages)[number])?{lang:"en",page}:null;
}
export function validRouteParams(){return[...publicPages.filter(p=>p!=="home").map(p=>({slug:[p]})),...languages.filter(l=>l!=="en").flatMap(l=>publicPages.map(p=>({slug:p==="home"?[l]:[l,p]})))];}
const englishSeo:Record<PageKey,{title:string;description:string;keywords:string[]}>= {
 home:{title:"Hacoo Spreadsheet, Finds & Product Search Guide 2026",description:"Search Hacoo product routes and use independent 2026 guides for spreadsheets, shipping, sizing, tracking, returns and QC photo checks.",keywords:["Hacoo","Hacoo spreadsheet","Hacoo finds","Hacoo product search"]},
 spreadsheet:{title:"Hacoo Spreadsheet 2026: Product Links, IDs & Finds",description:"Browse an independent Hacoo spreadsheet and learn how to verify product links, destination images, listing IDs, measurements and stale routes.",keywords:["Hacoo spreadsheet","Hacoo spreadsheets","Hacoo product links","Hacoo finds"]},
 finds:{title:"Hacoo Finds 2026: Search and Verify Product Routes",description:"Browse Hacoo finds with direct destination routes, approximate prices and a repeatable method for checking images, IDs and availability.",keywords:["Hacoo finds","Hacoo product links","Hacoo products","Hacoo search"]},
 categories:{title:"Hacoo Categories: Shoes, Hoodies, Clothing & Accessories",description:"Browse Hacoo product categories with direct live routes and practical size, measurement and QC checks for each product type.",keywords:["Hacoo categories","Hacoo shoes","Hacoo hoodies","Hacoo clothing"]},
 faq:{title:"Hacoo FAQ 2026: Website, Shipping, Returns & Prices",description:"Get careful answers about the Hacoo website, spreadsheet, shipping estimates, returns, live prices and independent product links.",keywords:["Hacoo FAQ","Hacoo website","Hacoo shipping","Hacoo returns"]},
 shipping:{title:"Hacoo Shipping Time 2026: Spain, UK, Tracking & Returns",description:"Understand published Hacoo shipping times for Spain, the UK, France, Germany and Italy, plus tracking, split parcels and return evidence.",keywords:["Hacoo shipping time","Hacoo delivery time Spain","Hacoo tracking","Hacoo returns"]},
 qc:{title:"Hacoo QC Guide 2026: Photos, Shoes & Clothing Checks",description:"Use a repeatable Hacoo QC method for product photos, shoe shape, clothing measurements, seams, prints and visible defects.",keywords:["Hacoo QC","Hacoo QC photos","Hacoo shoe QC","Hacoo clothing QC"]},
 guide:{title:"Hacoo Guide 2026: Search, Size, Shipping & Order Checks",description:"A practical independent Hacoo guide covering product search, listing verification, sizing, shipping estimates, tracking and after-sale evidence.",keywords:["Hacoo guide","Hacoo size guide","Hacoo order guide","Hacoo product search"]},
 articles:{title:"Hacoo Guides 2026: Shipping, Sizing, Tracking & QC",description:"Read detailed Hacoo guides about spreadsheets, finding products, shipping by country, tracking, returns, sizing and QC photos.",keywords:["Hacoo guides","Hacoo shipping guide","Hacoo size guide","Hacoo tracking guide"]},
};
export function buildMetadata(lang:Lang,page:PageKey):Metadata{
 const c=copy[lang],p=c.pages[page],path=routePath(lang,page),alts=Object.fromEntries(languages.map(code=>[code,routePath(code,page)]));
 const seo=page==="articles"?{title:editorialUi[lang].title,description:editorialUi[lang].intro,keywords:[]}:lang==="en"?englishSeo[page]:{title:page==="home"?p.title:`Hacoo: ${c.nav[page as Exclude<PageKey,"home">]}`,description:p.intro,keywords:[]};
 return{title:seo.title,description:seo.description,keywords:seo.keywords,alternates:{canonical:path,languages:{...alts,"x-default":routePath("en",page)}},robots:{index:true,follow:true},openGraph:{title:seo.title,description:seo.description,url:path,type:"website"}};
}

function Brand(){return <span className="brand"><b>HACOO</b><i>Hacoos Shop</i></span>}

const pageGuides: Partial<Record<PageKey, string[]>> = {
 spreadsheet: ['hacoo-spreadsheet-guide','hacoo-links-not-working','find-products-on-hacoo'],
 categories: ['hacoo-product-specification-checklist','hacoo-size-guide'],
 shipping: ['hacoo-shipping-time-by-country','hacoo-tracking-not-updating','hacoo-delivered-but-not-received','hacoo-returns-refund-timeline'],
 qc: ['hacoo-qc-photo-checklist','hacoo-shoe-qc-guide','hacoo-clothing-qc-guide'],
 guide: ['hacoo-website-vs-app','find-products-on-hacoo','hacoo-size-guide','hacoo-returns-refund-timeline'],
 faq: ['hacoo-website-vs-app','hacoo-shipping-returns-guide','hacoo-returns-refund-timeline'],
};
export function SitePage({lang,page}:{lang:Lang;page:PageKey}){
 const c=copy[lang],t=editorialUi[lang],p=page==="articles"?{...c.pages.articles,title:t.title,intro:t.intro}:c.pages[page];
 const articleList=getArticleList(lang);
 const featuredArticles=["hacoo-links-not-working","hacoo-tracking-not-updating","hacoo-delivered-but-not-received","hacoo-shipping-returns-guide"].map(slug=>articleList.find(article=>article.slug===slug)).filter((article):article is NonNullable<typeof article>=>Boolean(article));
 const research=(pageGuides[page]||[]).map(slug=>articleList.find(article=>article.slug===slug)).filter((article):article is NonNullable<typeof article>=>Boolean(article));
 const schema={"@context":"https://schema.org","@type":page==="articles"?"CollectionPage":"WebPage",name:p.title,inLanguage:lang,url:`https://hacoos.shop${routePath(lang,page)}`,isPartOf:{"@type":"WebSite",name:"Hacoos Shop",url:"https://hacoos.shop/"},...(page==="articles"?{mainEntity:{"@type":"ItemList",itemListElement:articleList.map((article,i)=>({"@type":"ListItem",position:i+1,name:article.title,url:`https://hacoos.shop${articleRoutePath(lang,article.slug)}`}))}}:{})};
 if(page!=="home")return <main id="top">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  <div className="statusbar"><span>{c.independent}</span><span>{c.updated}</span></div>
  <header><a href={routePath(lang,"home")} aria-label="Hacoos Shop home"><Brand/></a>
   <details className="language"><summary>{lang.toUpperCase()} <span>⌄</span></summary><div>{languages.map(code=><a className={code===lang?"active":""} href={routePath(code,page)} hrefLang={code} key={code}>{code.toUpperCase()}</a>)}</div></details>
  </header>
  <nav className="function-bar" aria-label="Primary pages">{publicPages.filter(x=>x!=="home").map((key,i)=><a className={page===key?"active":""} href={routePath(lang,key)} key={key}><span>0{i+1}</span>{c.nav[key as Exclude<PageKey,"home">]}</a>)}</nav>
  <article className={`route-detail route-${page}`}>
   <div className="route-heading"><a href={routePath(lang,"home")}>← HACOO</a><p>{p.kicker}</p><h1>{p.title}</h1><div className="route-intro"><p>{p.intro}</p><a href={`${DEST}/AllProducts/`} target="_blank" rel="noreferrer">{p.cta} ↗</a></div></div>
   {page==="articles"?<div className="article-index">{articleList.map((article,i)=><article key={article.slug}><span>{t.article} {String(i+1).padStart(2,"0")} · {article.readTime}</span><h2>{article.title}</h2><p>{article.description}</p><a href={articleRoutePath(lang,article.slug)}>{t.read} →</a></article>)}</div>:<div className="route-notes">{p.facts.map((fact,i)=><section key={fact}><span>0{i+1}</span><h2>{c.nav[page]}</h2><p>{fact}</p></section>)}</div>}
   {research.length>0&&<div className="research-sections">{research.map((article,i)=><section key={article.slug}><span>{t.article} {String(i+1).padStart(2,"0")}</span><h2><a href={articleRoutePath(lang,article.slug)}>{article.title}</a></h2><p>{article.description}</p><a className="guide-read-link" href={articleRoutePath(lang,article.slug)}>{t.read} →</a></section>)}</div>}
   {page==="spreadsheet"&&<div className="route-products">{products.slice(0,3).map(([id,,href,img],i)=><a href={`${DEST}${href}`} target="_blank" rel="noreferrer" key={href}><img src={`${DEST}${img}`} alt={`${c.categories[i][0]} · ${c.listing} ${id}`} width="300" height="300" loading="lazy" decoding="async"/><div><span>{c.categories[i][0]}</span><h3>{c.listing} #{id}</h3><p>{t.price}</p></div></a>)}</div>}
   {page==="categories"&&<div className="category-grid route-category-grid">{c.categories.map(([name,note],i)=><a href={`${DEST}${categoryLinks[i]}`} target="_blank" rel="noreferrer" key={categoryLinks[i]}><span>0{i+1}</span><h3>{name}</h3><p>{note}</p><b>↗</b></a>)}</div>}
   <form className="search route-search" action={`${DEST}/search.html`} method="get" target="_blank"><label htmlFor="route-q">{c.search}</label><input type="hidden" name="channelid" value="2"/><div><input id="route-q" name="keywords" required minLength={1} maxLength={120} placeholder={c.hint}/><button>{c.search} ↗</button></div><p className="catalogue-note">{t.catalogueNote}</p></form>
  </article>
  <footer><Brand/><p>{c.independent}<br/>{c.disclaimer}</p><div>{languages.map(code=><a href={routePath(code,page)} hrefLang={code} key={code}>{code.toUpperCase()}</a>)}</div><small>© 2026 HACOOS.SHOP</small></footer>
 </main>;
 return <main id="top">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  <div className="statusbar"><span>{c.independent}</span><span>{c.updated}</span></div>
  <header><a href={routePath(lang,"home")} aria-label="Hacoos Shop home"><Brand/></a>
   <details className="language"><summary>{lang.toUpperCase()} <span>⌄</span></summary><div>{languages.map(code=><a className={code===lang?"active":""} href={routePath(code,page)} hrefLang={code} key={code}>{code.toUpperCase()}</a>)}</div></details>
  </header>
  <nav className="function-bar" aria-label="Primary pages">{publicPages.filter(x=>x!=="home").map((key,i)=><a href={routePath(lang,key)} key={key}><span>0{i+1}</span>{c.nav[key as Exclude<PageKey,"home">]}</a>)}</nav>
  <section className="hero"><div className="hero-main"><p className="kicker">{p.kicker}</p><h1>{p.title}</h1><p className="intro">{p.intro}</p>
   <form className="search" action={`${DEST}/search.html`} method="get" target="_blank"><label htmlFor="q">{c.search}</label><input type="hidden" name="channelid" value="2"/><div><input id="q" name="keywords" required minLength={1} maxLength={120} placeholder={c.hint}/><button>{c.search} ↗</button></div><p className="catalogue-note">{t.catalogueNote}</p></form></div>
   <div className="hero-gallery" aria-label="Current product edit">{products.slice(0,3).map(([id,,href,img],i)=><a className={`hero-shot shot-${i+1}`} href={`${DEST}${href}`} target="_blank" rel="noreferrer" key={href}><img src={`${DEST}${img}`} alt={`${c.categories[i][0]} · ${c.listing} ${id}`} width="640" height="640" loading={i===0?"eager":"lazy"} fetchPriority={i===0?"high":"auto"} decoding="async"/><span>0{i+1}</span></a>)}<p>{c.section[2]}<br/><i>2026</i></p></div>
   <aside className="desk-card"><span>{c.section[3]}</span><ol>{p.facts.map((fact,i)=><li key={fact}><b>0{i+1}</b><p>{fact}</p></li>)}</ol><a href={`${DEST}/AllProducts/`} target="_blank" rel="noreferrer">{p.cta} <span>↗</span></a></aside>
  </section>
  <div className="marquee"><span>{c.search} / {c.nav.qc} / {c.nav.shipping} / {c.nav.guide}</span><span>{c.search} / {c.nav.qc} / {c.nav.shipping} / {c.nav.guide}</span></div>
  <section className="editorial-cards"><div className="section-label"><span>01</span><h2>{c.nav.faq} / {c.nav.articles}</h2><p>{t.read}</p></div><div className="content-grid">
   <a className="content-card faq-card" href={routePath(lang,"faq")}><span>{c.nav.faq}</span><h3>{c.pages.faq.title}</h3><p>{c.pages.faq.intro}</p><ul>{c.pages.faq.facts.map(fact=><li key={fact}>{fact}</li>)}</ul><b>{c.open} →</b></a>
   <div className="content-card article-card"><span>{c.nav.articles}</span><h3>{t.title}</h3><p>{t.intro}</p><ol>{featuredArticles.map((article,i)=><li key={article.slug}><em>0{i+1}</em><a href={articleRoutePath(lang,article.slug)}>{article.title}</a></li>)}</ol><a className="article-hub-link" href={routePath(lang,"articles")}>{c.open} →</a></div>
  </div></section>
  <section className="category-section"><div className="section-label"><span>02</span><h2>{c.section[1]}</h2><p>{c.browse}</p></div><div className="category-grid">{c.categories.map(([name,note],i)=><a href={`${DEST}${categoryLinks[i]}`} target="_blank" rel="noreferrer" key={categoryLinks[i]}><span>0{i+1}</span><h3>{name}</h3><p>{note}</p><b>↗</b></a>)}</div></section>
  <section className="products"><div className="product-head"><div><span>03 / {c.section[2]}</span><h2>{p.cta}</h2></div><p>{t.price}</p></div><div className="product-grid">{products.map(([id,,href,img],i)=><a href={`${DEST}${href}`} target="_blank" rel="noreferrer" key={href}><div className="product-image"><img src={`${DEST}${img}`} alt={`${c.categories[i][0]} · ${c.listing} ${id}`} width="640" height="640" loading="lazy" decoding="async"/><span>{c.categories[i][0]}</span></div><div className="product-copy"><p>{c.listing} #{id}</p><strong>{t.price}</strong><b>{c.open} ↗</b></div></a>)}</div></section>
  <section className="evidence"><div className="section-label light"><span>04</span><h2>{c.section[3]}</h2><p>{c.updated}</p></div><div className="evidence-copy">{p.facts.map((fact,i)=><article key={fact}><span>{c.section[3]} {i+1}</span><p>{fact}</p></article>)}</div></section>
  <section className="final"><p>{c.section[0]}</p><h2>{p.cta}</h2><a href={`${DEST}/AllProducts/`} target="_blank" rel="noreferrer">{c.browse} ↗</a></section>
  <footer><Brand/><p>{c.independent}<br/>{c.disclaimer}</p><div>{languages.map(code=><a href={routePath(code,page)} hrefLang={code} key={code}>{code.toUpperCase()}</a>)}</div><small>© 2026 HACOOS.SHOP</small></footer>
 </main>;
}
