import type {SeoArticle} from "./seo-articles";
import type {Lang} from "./site-data";

export const storagePolicyArticle:SeoArticle={
slug:"joyagoo-warehouse-storage-policy-item-clocks-expiry-evidence",
title:"Joyagoo Warehouse Storage Policy: Item Clocks, Extensions and Expiry Evidence",
description:"Interpret the current Joyagoo warehouse storage policy with separate item and parcel clocks, dated evidence, extension records and an expiry-prevention workflow.",
meta:"STORAGE POLICY · 15 MIN",
sourceNote:"Official storage and shopping guidance checked September 4, 2026. Published periods and charges can change; the active warehouse or parcel record controls each transaction.",
quickFacts:["Item storage starts at Stored","Each item needs its own clock","Submitted parcels use another period","Extensions require a saved receipt","Silence after expiry creates serious risk"],
sections:[
{heading:"Read the policy as two separate clocks",paragraphs:["Joyagoo's current warehouse storage page describes one clock for individual items and another for a submitted parcel awaiting international-freight payment. The item clock begins when the order changes to Stored and currently carries a published 90-day free period. The parcel clock begins after parcel submission and before freight payment, with a published 30-day free period. Combining those rules into one vague 'warehouse deadline' can cause a buyer to watch the wrong event.","Treat every period as a policy snapshot checked on a particular date, not a permanent promise. Save the official wording and the live account record together. The help page explains the general rule; the warehouse or parcel screen shows which transaction, status and countdown are actually in front of the buyer. When the two do not align, preserve both and ask for clarification before the earlier defensible deadline."]},
{heading:"Find the item-level trigger",paragraphs:["The storage page says the free item period starts when the order status changes to 'Stored.' Joyagoo's separate order-status page uses 'Stored in Warehouse' for items that are stored and can be shipped during the free period. Record the exact label that appears in the account rather than forcing one page's capitalization or wording onto another. The important evidence is the transition into the stored state and its timestamp.","Seller dispatch, Stock Arrived and QC Completed belong to the item history, but they are not the storage trigger described on the current storage page. If the interface shows only a date, save the date, account locale and time zone and use a conservative internal deadline. Do not calculate from the purchase date or from another item that arrived in the same order group."]},
{heading:"Give each stored item its own row",paragraphs:["Items purchased together can arrive and become stored on different days. A late seller does not reset the clock of an earlier item, and a consolidation plan does not merge their histories. Build a ledger with order number, source listing, selected option, stored-status timestamp, published free-period end, displayed countdown, extension state and planned parcel group. Sort it by the earliest action deadline.","Use clear states: return decision open, keep confirmed, parcel planned, extension requested, parcel submitted or resolved. A vague note such as 'waiting for more items' hides the actual risk. The ledger should identify who owns the next action and when it must happen. That makes storage policy operational without turning it into a shipping-cost guide."]},
{heading:"Calculate a defensible item deadline",paragraphs:["For the currently published 90-day period, add 90 continuous days to the stored-status timestamp in the same time zone. Write both the calculated boundary and an earlier internal action date. The internal date should leave enough room to finish QC decisions, resolve a return question, select parcel contents and complete any necessary payment. It is a planning buffer, not an extension of the official period.","If a live countdown disagrees with the calculation, keep screenshots of the status, countdown and account time. Use the earlier boundary until the discrepancy is resolved. Do not announce that every calendar interpretation receives extra time. A defensible record states the source, date checked, arithmetic and uncertainty so that support can answer the transaction-specific question."]},
{heading:"Document an extension as a new policy event",paragraphs:["The storage page currently says an item extension costs 10 CNY for 30 days through 'Extend Storage.' That is a dated published term, not authority to assume the button, price or duration will always appear for every item. Before relying on it, open the exact warehouse record and save the option label, amount, currency, extension length and eligibility shown at that moment.","After payment, preserve the receipt, transaction time, affected order number and new displayed expiry. Do not infer success merely because the balance changed. Check that the extension attached to the intended item and that the deadline moved as expected. If several items need more time, verify each one separately; one extension record should not silently stand in for an entire parcel group."]},
{heading:"Do not confuse return and storage deadlines",paragraphs:["The QC return clock and warehouse storage clock answer different questions. The current return policy links the ordinary request window for eligible items to QC Completed, while the storage page starts free item storage at Stored. A long storage period does not reopen an expired return opportunity. Equally, an unresolved return should not be treated as a confirmed item ready for consolidation.","Keep both timestamps in the item row. Close the keep-or-return decision first, then decide whether to ship, wait or extend storage. If a return or exchange is still being negotiated, save the status and support instructions instead of assuming the storage clock pauses. Only a transaction-specific display or written answer can establish that effect."]},
{heading:"Start a new row when a parcel is submitted",paragraphs:["Once items are submitted as a parcel but international freight remains unpaid, the current storage page describes a separate 30-day free parcel-storage period. Record parcel number, included item numbers, submission timestamp, freight-status label, displayed amount, payment deadline and any cancellation or recalculation state. Do not carry the oldest item's 90-day calculation forward as if it controlled the submitted parcel.","The published order-status list includes Parcel Waiting to Pay and also says that a calculated shipping fee may require payment within a shorter displayed period. This means a buyer should not use the general 30-day parcel-storage period to ignore a transaction-specific payment instruction. Save both rules, follow the earlier active deadline and ask when the account presents an unresolved conflict."]},
{heading:"Treat abandonment language as a stop signal",paragraphs:["The current storage page states that goods may be treated as abandoned and destroyed when the relevant item or parcel period is exceeded without parcel submission, freight payment or communication. That is a serious consequence, but this guide should not guess the exact disposal moment for an individual case. The defensible response is to act before expiry and preserve evidence of any communication.","A last-minute message is not a guaranteed extension. Record the channel, timestamp, order or parcel number, question and reply. If payment or submission cannot be completed, request written transaction-specific instructions while the period remains open. Never advise a buyer to test the boundary by waiting for a warning notification that the published page does not promise."]},
{heading:"Run a weekly exception review",paragraphs:["Review the ledger at least weekly and filter for items with the earliest internal dates, missing stored timestamps, unresolved QC decisions, unconfirmed extensions and submitted parcels awaiting payment. Check the live account rather than merely reducing a number in a spreadsheet. A status change, extension receipt or parcel cancellation must become a new dated entry, preserving the older evidence instead of overwriting it.","Use red, amber and green as workflow labels, not risk guarantees. Red means action is due before the next review; amber means a required fact or confirmation is missing; green means the next action is scheduled with adequate evidence. Even a green item retains its original deadline and source because future seller, warehouse or parcel events can change the plan."]},
{heading:"Close with an auditable expiry-prevention record",paragraphs:["A complete record contains item or parcel identity, controlling status, trigger timestamp, time zone, published policy version, calculated boundary, earlier internal deadline, live countdown, extension option, receipt, communication and final resolution. Save only necessary transaction evidence and exclude private address or payment credentials from any shared copy. The record should let another person explain every date without inventing a policy.","The practical conclusion is narrow: separate item storage from parcel storage, calculate from the stated trigger and never let consolidation plans conceal the oldest deadline. Joyagoo's current published terms provide usable baselines—90 days for stored items, an optional 30-day item extension at 10 CNY, and 30 days for a submitted unpaid parcel—but buyers should recheck the live rule and their account before relying on any number."]}
]};

const make=(title:string,description:string,sourceNote:string,facts:string[],rows:[string,string,string][]):SeoArticle=>({slug:storagePolicyArticle.slug,title,description,meta:"STORAGE POLICY · 15 MIN",sourceNote,quickFacts:facts,sections:rows.map(([heading,a,b])=>({heading,paragraphs:[a,b]}))});

export const storagePolicyTranslations:Partial<Record<Lang,SeoArticle>>={
de:make("Joyagoo-Lagerrichtlinie: Artikeluhren, Verlängerung und Ablaufbelege","Interpretiere die aktuelle Lagerrichtlinie mit getrennten Artikel- und Paketuhren, datierten Belegen, Verlängerungen und einem Ablauf-Workflow.","Offizielle Lager- und Einkaufsanleitung am 4. September 2026 geprüft. Zeiten und Gebühren können sich ändern; der aktive Lager- oder Paketdatensatz entscheidet.",["Artikelzeit startet bei Stored","Jeder Artikel hat eine eigene Uhr","Eingereichte Pakete nutzen eine andere Frist","Verlängerung mit Beleg sichern","Schweigen nach Ablauf ist riskant"],[
["Zwei getrennte Uhren lesen","Die aktuelle Seite nennt 90 kostenlose Tage ab Stored für einzelne Artikel und 30 kostenlose Tage nach Paketeinreichung vor Frachtzahlung. Eine allgemeine Lagerfrist kann deshalb das falsche Ereignis überwachen.","Behandle jede Zahl als datierte Richtlinie. Speichere Hilfeseite und Live-Konto zusammen; bei Abweichung beide sichern und vor der früheren vertretbaren Grenze fragen."],
["Artikelauslöser finden","Die Lagerseite nennt Stored, die Statusseite Stored in Warehouse. Speichere den genauen Kontotext und Zeitstempel; entscheidend ist der Übergang in den gelagerten Zustand.","Seller Sent, Stock Arrived und QC Completed erklären die Historie, sind aber nicht der genannte Start. Bei reinem Datum Zeitzone und Sprache sichern und konservativ planen."],
["Für jeden Artikel eine Zeile","Gemeinsam gekaufte Artikel können an verschiedenen Tagen gespeichert werden. Später Verkäufer und Konsolidierung setzen frühere Uhren nicht zurück. Erfasse Nummer, Listing, Option, Start, Ende, Countdown, Verlängerung und Paketgruppe.","Nutze Rückgabe offen, behalten, Paket geplant, verlängert, eingereicht oder erledigt. Jede Zeile braucht Verantwortlichen, nächste Aktion und Termin."],
["Eine belastbare Grenze berechnen","Addiere aktuell 90 fortlaufende Tage in derselben Zeitzone und setze eine frühere interne Frist für QC, Rückfrage, Paketwahl und Zahlung. Der Puffer verlängert die Richtlinie nicht.","Bei Konflikt mit Countdown sichere Status, Anzeige und Kontouhr und verwende vorläufig die frühere Grenze. Dokumentiere Quelle, Prüfdatum, Rechnung und Unsicherheit."],
["Verlängerung als neues Ereignis","Veröffentlicht sind derzeit 10 CNY für 30 Tage über Extend Storage. Prüfe beim konkreten Artikel Button, Preis, Währung, Dauer und Berechtigung, statt dauerhafte Verfügbarkeit anzunehmen.","Nach Zahlung sichere Beleg, Zeit, Bestellnummer und neue Ablaufanzeige. Prüfe Zuordnung und verschobenes Datum pro Artikel; eine Verlängerung gilt nicht automatisch für die Gruppe."],
["Rückgabe und Lager trennen","Rückgabe startet laut aktueller Richtlinie bei QC Completed, Lagerzeit bei Stored. Lange Lagerung öffnet keine verstrichene Rückgabe, und ein offener Rückgabefall ist nicht konsolidierungsbereit.","Halte beide Zeiten fest. Schließe die Entscheidung vor Versand oder Verlängerung. Nimm kein Pausieren der Lageruhr ohne Anzeige oder schriftliche Fallauskunft an."],
["Bei Paketeinreichung neue Zeile","Für eingereichte, noch unbezahlte Pakete nennt die Seite 30 kostenlose Tage. Erfasse Paketnummer, Artikel, Einreichung, Frachtstatus, Betrag, Zahlungsfrist und Neuberechnung; die älteste Artikeluhr steuert das Paket nicht.","Statushinweise können eine kürzere Zahlungspflicht zeigen. Ignoriere sie nicht wegen der allgemeinen 30 Tage: sichere beide und folge bis zur Klärung der früheren aktiven Frist."],
["Aufgabetext als Stoppsignal","Die Seite warnt vor Aufgabe und Vernichtung nach Überschreitung ohne Einreichung, Zahlung oder Kommunikation. Rate keinen genauen Entsorgungszeitpunkt; handle vor Ablauf und sichere Kontaktbelege.","Eine Nachricht garantiert keine Verlängerung. Speichere Kanal, Zeit, Nummer, Frage und Antwort und verlasse dich nicht auf eine unversprochene Warnung."],
["Wöchentlich Ausnahmen prüfen","Filtere früheste interne Daten, fehlende Starts, offene QC-Entscheidungen, unbestätigte Verlängerungen und unbezahlte Pakete. Prüfe das Live-Konto und hänge neue Ereignisse an, statt Historie zu überschreiben.","Rot heißt vor nächster Prüfung handeln, gelb heißt Beleg fehlt, grün heißt geplant. Die Farben sind Workflow, keine Garantie; Originalfrist und Quelle bleiben erhalten."],
["Prüfbaren Ablaufdatensatz schließen","Vollständig sind Identität, Status, Zeit, Zone, Richtlinienversion, Grenze, interne Frist, Countdown, Verlängerung, Beleg, Kontakt und Ergebnis. Keine Adress- oder Zahlungsdaten öffentlich teilen.","Trenne Artikel- und Paketlagerung und plane nach der ältesten Frist. 90 Tage, 10 CNY für weitere 30 Tage und 30 Paket-Tage sind aktuelle Baselines, die live erneut geprüft werden müssen."]]),
es:make("Política de almacén Joyagoo: relojes por artículo, extensiones y vencimiento","Interpreta la política actual con relojes separados para artículo y paquete, pruebas fechadas, extensiones y prevención del vencimiento.","Guías oficiales comprobadas el 4 de septiembre de 2026. Los periodos y cargos pueden cambiar; manda el registro activo del artículo o paquete.",["El reloj empieza en Stored","Cada artículo tiene su plazo","El paquete tiene otro periodo","Guarda recibo de extensión","El silencio tras vencer es grave"],[
["Leer dos relojes separados","La página vigente publica 90 días gratis desde Stored para artículos y 30 tras enviar un paquete antes de pagar el flete. Un único “plazo de almacén” puede vigilar el evento equivocado.","Trata cada cifra como versión fechada. Guarda ayuda y cuenta activa; si difieren, conserva ambas y pregunta antes del límite más temprano."],
["Encontrar el inicio del artículo","La página dice Stored y la lista de estados Stored in Warehouse. Registra la etiqueta y hora exactas de la cuenta: importa la transición al estado almacenado.","Seller Sent, Stock Arrived y QC Completed son historia, no el inicio publicado. Si solo hay fecha, guarda zona e idioma y calcula con cautela."],
["Una fila por artículo","Artículos conjuntos pueden almacenarse en días distintos; un vendedor tardío y la consolidación no reinician otros relojes. Anota pedido, ficha, opción, inicio, fin, cuenta atrás, extensión y grupo.","Usa devolución abierta, conservar, paquete previsto, ampliado, enviado o resuelto. Define responsable, acción y fecha."],
["Calcular un límite defendible","Suma los 90 días continuos actuales en la misma zona y fija una fecha interna anterior para QC, dudas, selección y pago. Ese margen no extiende la política.","Si la cuenta atrás no coincide, guarda estado y hora y usa temporalmente el límite anterior. Documenta fuente, fecha, cálculo e incertidumbre."],
["Documentar la extensión","Hoy se publican 10 CNY por 30 días mediante Extend Storage. Verifica para el artículo etiqueta, precio, moneda, duración y elegibilidad antes de depender de ello.","Tras pagar guarda recibo, hora, pedido y nueva fecha. Comprueba que afectó al artículo correcto; una extensión no cubre automáticamente el grupo."],
["Separar devolución y almacenamiento","La devolución ordinaria usa QC Completed; el almacenamiento usa Stored. Mucho tiempo de almacén no reabre devolución y un caso abierto no está listo para consolidar.","Conserva ambos relojes. Decide antes de enviar o ampliar y no supongas pausa sin pantalla o respuesta escrita específica."],
["Nueva fila al enviar paquete","Para un paquete presentado y sin flete pagado se publican 30 días. Registra número, artículos, hora, estado, importe, fecha de pago y recálculo; no uses el reloj del artículo.","El estado puede mostrar un plazo de pago menor. No lo ignores por la regla general: conserva ambos y sigue el anterior hasta aclararlo."],
["Tomar el abandono como señal de parada","La política advierte abandono y destrucción tras vencer sin envío, pago o comunicación. No adivines el momento exacto; actúa antes y guarda el contacto.","Un mensaje no garantiza ampliación. Registra canal, hora, número, pregunta y respuesta; no esperes un aviso que no está prometido."],
["Revisión semanal de excepciones","Filtra fechas cercanas, inicios ausentes, QC abierto, extensión no confirmada y paquetes sin pagar. Revisa la cuenta y añade eventos sin borrar el historial.","Rojo exige acción, ámbar prueba pendiente y verde siguiente paso programado. Son etiquetas de trabajo, no garantías; conserva fuente y plazo."],
["Cerrar un registro auditable","Incluye identidad, estado, hora, zona, versión, límite, fecha interna, cuenta atrás, extensión, recibo, contacto y resultado, sin publicar dirección o credenciales.","Separa reloj de artículo y paquete y protege el más antiguo. Los 90 días, 10 CNY/30 días y 30 días de paquete son términos actuales que deben volver a comprobarse."]]),
fr:make("Politique de stockage Joyagoo : horloges article, prolongation et échéance","Interprétez la politique actuelle avec des horloges distinctes, des preuves datées, les prolongations et un processus anti-expiration.","Guides officiels vérifiés le 4 septembre 2026. Durées et frais peuvent changer ; la fiche active de l’article ou du colis décide.",["L’article commence à Stored","Chaque article a son horloge","Le colis suit une autre durée","Conserver le reçu d’extension","Le silence après échéance est risqué"],[
["Lire deux horloges distinctes","La page actuelle publie 90 jours gratuits depuis Stored pour l’article et 30 jours après soumission d’un colis avant fret. Une seule « échéance entrepôt » peut suivre le mauvais événement.","Traitez chaque chiffre comme version datée. Conservez aide et compte actif ; en cas d’écart, gardez les deux et demandez avant la limite la plus proche."],
["Trouver le déclencheur article","La page dit Stored et la liste d’états Stored in Warehouse. Sauvegardez libellé et heure exacts : le passage à l’état stocké est la preuve utile.","Seller Sent, Stock Arrived et QC Completed expliquent l’historique sans être le départ publié. Si seule la date apparaît, conservez fuseau et langue et restez prudent."],
["Une ligne par article","Des achats communs peuvent être stockés à des dates différentes ; vendeur tardif et consolidation ne réinitialisent rien. Notez commande, fiche, option, départ, fin, compte à rebours, extension et groupe.","Utilisez retour ouvert, garder, colis prévu, prolongé, soumis ou résolu. Nommez responsable, action suivante et échéance."],
["Calculer une limite défendable","Ajoutez les 90 jours continus actuels dans le même fuseau et créez une date interne antérieure pour QC, question, sélection et paiement. Ce tampon ne prolonge pas la règle.","Si le compte à rebours diffère, conservez état et heure et utilisez provisoirement la limite la plus proche. Notez source, date, calcul et incertitude."],
["Documenter la prolongation","La page publie aujourd’hui 10 CNY pour 30 jours via Extend Storage. Vérifiez libellé, prix, devise, durée et admissibilité sur l’article avant de compter dessus.","Après paiement, gardez reçu, heure, numéro et nouvelle échéance. Vérifiez l’article visé ; une extension ne vaut pas automatiquement pour tout le groupe."],
["Séparer retour et stockage","Le retour ordinaire dépend de QC Completed, le stockage de Stored. Une longue conservation ne rouvre pas un retour expiré et un retour ouvert n’est pas prêt à consolider.","Gardez les deux horloges. Décidez avant expédition ou prolongation et ne supposez aucune pause sans affichage ou réponse écrite propre au dossier."],
["Nouvelle ligne à la soumission du colis","Pour un colis soumis mais fret impayé, 30 jours sont publiés. Notez numéro, articles, heure, statut, montant, échéance et recalcul ; ne reportez pas l’horloge article.","Le statut peut demander un paiement plus tôt. Ne l’ignorez pas à cause des 30 jours généraux : gardez les deux et suivez la limite active la plus proche."],
["Traiter l’abandon comme arrêt","La page avertit d’un abandon et d’une destruction après dépassement sans soumission, paiement ou communication. N’inventez pas l’heure exacte ; agissez tôt et gardez le contact.","Un message ne garantit pas l’extension. Notez canal, heure, numéro, question et réponse ; n’attendez pas une alerte non promise."],
["Revoir les exceptions chaque semaine","Filtrez dates internes proches, départs manquants, QC ouvert, extensions non confirmées et colis impayés. Vérifiez le compte et ajoutez les événements sans écraser l’historique.","Rouge exige action, orange preuve manquante, vert action planifiée. Ce sont des repères, pas des garanties ; gardez source et date initiales."],
["Clore un dossier auditable","Incluez identité, statut, heure, fuseau, version, limite, date interne, compte à rebours, extension, reçu, contact et résultat, sans partager adresse ou identifiants.","Séparez article et colis et protégez la plus ancienne échéance. Les 90 jours, 10 CNY/30 jours et 30 jours colis sont des termes actuels à revérifier en direct."]]),
it:make("Politica di deposito Joyagoo: orologi articolo, estensioni e scadenza","Interpreta la politica attuale con orologi separati per articolo e pacco, prove datate, estensioni e prevenzione della scadenza.","Guide ufficiali controllate il 4 settembre 2026. Periodi e costi possono cambiare; decide il record attivo dell’articolo o pacco.",["L’articolo parte da Stored","Ogni articolo ha il suo orologio","Il pacco usa un altro periodo","Salva ricevuta di estensione","Il silenzio dopo scadenza è grave"],[
["Leggere due orologi separati","La pagina attuale pubblica 90 giorni gratis da Stored per l’articolo e 30 dopo invio del pacco prima del trasporto. Un’unica “scadenza deposito” può seguire l’evento sbagliato.","Tratta ogni numero come versione datata. Salva guida e account live; se divergono, conserva entrambi e chiedi prima del limite più vicino."],
["Trovare l’avvio articolo","La pagina dice Stored e gli stati Stored in Warehouse. Registra etichetta e ora esatte: la transizione allo stato immagazzinato è la prova utile.","Seller Sent, Stock Arrived e QC Completed descrivono la storia ma non l’avvio pubblicato. Se appare solo la data, salva fuso e lingua e pianifica prudente."],
["Una riga per articolo","Articoli comprati insieme possono essere stoccati in giorni diversi; venditore tardivo e consolidamento non azzerano altri orologi. Annota ordine, inserzione, opzione, inizio, fine, countdown, estensione e gruppo.","Usa reso aperto, tieni, pacco previsto, esteso, inviato o risolto. Definisci responsabile, azione e data."],
["Calcolare un limite difendibile","Aggiungi gli attuali 90 giorni continui nello stesso fuso e fissa una data interna precedente per QC, domande, selezione e pagamento. Il margine non estende la regola.","Se il countdown differisce, salva stato e ora e usa provvisoriamente il limite anteriore. Documenta fonte, data, calcolo e incertezza."],
["Documentare l’estensione","Oggi sono pubblicati 10 CNY per 30 giorni tramite Extend Storage. Verifica sull’articolo nome, prezzo, valuta, durata e idoneità prima di farci affidamento.","Dopo il pagamento salva ricevuta, ora, numero e nuova data. Conferma che riguardi l’articolo corretto; un’estensione non copre automaticamente il gruppo."],
["Separare reso e deposito","Il reso ordinario parte da QC Completed, il deposito da Stored. Molto tempo in magazzino non riapre il reso e un caso aperto non è pronto al consolidamento.","Conserva entrambi gli orologi. Decidi prima di spedire o estendere e non presumere pause senza schermata o risposta scritta specifica."],
["Nuova riga al pacco","Per un pacco inviato ma con trasporto non pagato sono pubblicati 30 giorni. Registra numero, articoli, ora, stato, importo, scadenza e ricalcolo; non usare l’orologio articolo.","Lo stato può mostrare un pagamento più breve. Non ignorarlo per i 30 giorni generali: salva entrambi e segui il limite attivo più vicino."],
["Abbandono come segnale di arresto","La pagina avverte di abbandono e distruzione dopo scadenza senza invio, pagamento o contatto. Non indovinare il momento; agisci prima e conserva la comunicazione.","Un messaggio non garantisce estensione. Registra canale, ora, numero, domanda e risposta; non aspettare un avviso non promesso."],
["Controllo settimanale eccezioni","Filtra date vicine, avvii mancanti, QC aperto, estensioni non confermate e pacchi non pagati. Controlla l’account e aggiungi eventi senza cancellare la storia.","Rosso richiede azione, ambra prova mancante, verde passo pianificato. Sono etichette operative, non garanzie; conserva fonte e scadenza."],
["Chiudere un record verificabile","Includi identità, stato, ora, fuso, versione, limite, data interna, countdown, estensione, ricevuta, contatto e risultato, senza condividere indirizzo o credenziali.","Separa articolo e pacco e proteggi la scadenza più vecchia. I 90 giorni, 10 CNY/30 giorni e 30 giorni pacco sono termini attuali da ricontrollare live."]])
};
