import type { SeoArticle } from "./seo-articles";

const sourceNote = "Official Joyagoo Shopping Guidance and Purchasing Instructions checked September 21, 2026. A spreadsheet is an independent discovery aid; the live seller listing and active Joyagoo order screen control each transaction.";

export const spreadsheetArticles: SeoArticle[] = [
  {
    slug: "how-to-use-joyagoo-spreadsheet-dead-links",
    title: "How to Use a Joyagoo Spreadsheet Without Opening Dead Product Links",
    description: "A practical workflow for screening Joyagoo spreadsheet rows, detecting stale destinations and preserving enough evidence to find a current replacement listing.",
    meta: "JOYAGOO SPREADSHEET WORKFLOW · 14 MIN",
    sourceNote,
    quickFacts: ["Treat every row as a lead", "Check the destination before comparing", "Save source IDs, not just redirects", "Reject unexplained option changes", "Recheck again before payment"],
    sections: [
      { heading: "Use the spreadsheet as a map, not a catalogue", paragraphs: [
        "A Joyagoo spreadsheet can reduce a large search problem to a manageable list of links, categories and short notes. That is useful, but it does not make the sheet a live seller database. Marketplace listings can be removed, redirected, edited or replaced after a row is published. Prices and variants can change without the spreadsheet owner receiving a notice. Start with the assumption that every row is a lead that still needs verification, not an offer that is ready to buy.",
        "This distinction prevents the most common failure: opening several rows, seeing one familiar image and treating the first working destination as the intended product. The correct destination must preserve the important identity signals from the row: marketplace, seller or shop when available, product ID, title meaning, main image, and relevant options. If those signals do not agree, the link is not verified merely because a page loads."
      ]},
      { heading: "Screen the row before opening it", paragraphs: [
        "Read the entire row first. Note the category, short product description, source marketplace, product ID, recorded price, date checked and any variant note. Some sheets expose only a redirect or agent link; in that case, copy the URL into a text field and look for the original marketplace host or numeric item identifier. A stable source ID is more valuable than a shortened address because it can survive a change in the redirect layer.",
        "Mark rows with missing dates, generic titles or no source identity as higher risk. They may still lead somewhere useful, but they require more work. Do not reject a row only because its recorded price is old, and do not trust it because the price looks precise. A price in a sheet is a snapshot. The active listing must show the current base price, selected-option price and domestic delivery field before those numbers become decision evidence."
      ]},
      { heading: "Classify what happens after the click", paragraphs: [
        "A link normally produces one of five outcomes: the intended listing opens; the listing opens but key options are unavailable; the marketplace redirects to a different item; the page reports deletion or no permission; or the agent cannot parse the source. Give each outcome a label. This is faster than repeatedly clicking the same broken address, and it creates a useful update record for the sheet instead of a vague note that the link does not work.",
        "A successful page load is only the first class, not the final approval. Compare title meaning, image, selected product family, seller identity and item ID. If the page is a replacement listing, treat it as a new candidate. A replacement may be perfectly usable, yet it has a different evidence history. Never transfer comments, QC expectations or seller assumptions from the old item to the new one without checking them again."
      ]},
      { heading: "Recover the original marketplace identity", paragraphs: [
        "Joyagoo's published shopping guidance says buyers can paste an original product link into its search field and that search can work with sources including Taobao, Tmall, JD, 1688, Yupoo and Weidian. That makes the original destination worth preserving. When a spreadsheet opens an intermediate page, record the final source host and item number before doing anything else. If the redirect fails later, those two fields provide a route for a fresh search.",
        "Do not manufacture an original link by changing random numbers in a URL. Marketplace identifiers have platform-specific formats, and a plausible-looking address can point to a different listing. Recover the ID from the row, redirect target or page data. If no reliable identifier remains, search by a distinctive title phrase or image and label the result as a possible replacement rather than the same listing. Evidence quality depends on that honest distinction."
      ]},
      { heading: "Verify options before judging the product", paragraphs: [
        "Dead-link problems are often option problems in disguise. The listing still exists, but the referenced colour, size, bundle or quantity no longer does. Open the option selectors and confirm that the combination you need is selectable. Read whether choosing it changes the image, product description, minimum quantity or price. On wholesale-style listings, the headline price may apply only to a quantity tier or a different specification.",
        "Write the chosen option in plain language rather than relying on its position in a menu. Sellers can reorder menus, and machine-translated labels may be ambiguous. Save a screenshot or concise note showing colour, size, version, quantity, unit price and domestic freight. If an option is visually similar but named differently, pause. A spreadsheet thumbnail cannot resolve whether two seller variants are equivalent."
      ]},
      { heading: "Use a replacement rule instead of guessing", paragraphs: [
        "A sensible replacement rule requires agreement on product function, visible design, material description when supplied, measurements or compatibility, included parts and commercial terms. Decide which fields are essential before searching. For shoes, the size system and shape may be essential; for electronics, model, plug and voltage matter; for an accessory, dimensions and included hardware may dominate. A lower price should not compensate for an unknown essential field.",
        "Keep the old and new product IDs side by side. Record why the old row failed, when the new listing was checked and which fields match or differ. This creates an audit trail that another reader can follow. It also prevents a replacement from silently overwriting the original history. If the seller page later changes again, the log shows which version supported the decision at the time."
      ]},
      { heading: "Hand a verified link into the order workflow", paragraphs: [
        "Once the destination and option are verified, use the live Joyagoo order interface. Official guidance instructs buyers to choose colour, size and quantity, then pay for the item and Chinese local shipping. Compare those order fields with the record you just made. If the parsed title, image, price or option differs, stop and correct the order rather than assuming the buyer agent will infer your intended variant from a spreadsheet note.",
        "For sources that cannot be searched normally, Joyagoo's guidance points to a DIY order flow. A DIY order needs more precise input, not less: source address, item identity, option, quantity, price and any seller instruction. Preserve the submitted details. They become the baseline for later order-status questions and warehouse QC, particularly when the source page is likely to disappear."
      ]},
      { heading: "Recheck at payment and again at QC", paragraphs: [
        "Verification expires. Reopen the destination immediately before product payment and confirm availability, selected variant, price, domestic freight and seller note. After the item reaches the warehouse, compare the QC photos with the saved listing record rather than with memory. Start with identity and option, then inspect condition. A spreadsheet image is a discovery cue; the saved live listing is the stronger comparison record.",
        "Use a simple final decision: proceed when source identity, current option and order fields agree; pause when one important field is unclear; replace the listing when the original is deleted or materially changed. This method does not eliminate dead links. It makes them cheap to detect and safe to replace, while preserving the evidence needed for a later return, support request or spreadsheet update.",
        "Keep this record with the order until the after-sales window has passed. A seller page that disappears after payment does not erase the option you selected, and a later spreadsheet correction should not rewrite the historical transaction. The saved ID, screenshot, order fields and QC timestamp let support compare the actual purchase with the evidence available at each stage.",
        "For repeated use, add a review date to every shortlist and clear candidates that have not been checked recently. Rechecking a smaller, evidence-rich shortlist is faster than maintaining dozens of assumed-working tabs. The real efficiency gain comes from knowing which links deserve another click and which have already failed a defined verification test."
      ]}
    ]
  },
  {
    slug: "joyagoo-product-links-taobao-weidian-1688",
    title: "Joyagoo Product Links from Taobao, Weidian and 1688: Verification Workflow",
    description: "Verify Taobao, Weidian and 1688 links without assuming that identical photos, translated titles or low displayed prices represent the same offer.",
    meta: "PRODUCT-LINK VERIFICATION · 15 MIN",
    sourceNote,
    quickFacts: ["Identify the source marketplace", "Preserve the product ID", "Interpret prices by option and quantity", "Check seller-specific evidence", "Submit exact order fields"],
    sections: [
      { heading: "Begin with the marketplace, not the thumbnail", paragraphs: [
        "Taobao, Weidian and 1688 links can show similar products while representing different commercial structures. A thumbnail copied across sellers does not prove that the listings share inventory, options or production. First identify the marketplace and seller page that owns the live offer. Then record the product ID and the date checked. These fields establish what you actually reviewed when a title, image or redirect changes later.",
        "Joyagoo's current Shopping Guidance lists Taobao, Tmall, JD, 1688, Yupoo and Weidian among supported search sources. Support for a source means the platform can help start an order; it does not certify the seller's claims or make the listing permanent. Verification remains a buyer task: understand the active source page, choose a specific variant and preserve evidence before submitting it."
      ]},
      { heading: "Read Taobao as a retail listing", paragraphs: [
        "A Taobao page commonly presents a retail product with several colour, size or bundle options. Confirm the selected combination rather than using the first visible price. Images can mix variants, lifestyle photography and detail shots. Match option text to the image that changes when you select it, then look for a size table, material note, included-parts statement and domestic delivery field. Record anything that would change your willingness to buy.",
        "Translation can flatten meaningful differences between option names. Save the original label beside your English interpretation, especially for sizes, versions and sets. If the listing uses a letter size, compare its measurements with a reference garment instead of treating the letter as universal. A Taobao link is verified only when the exact option in the intended quantity can be described clearly in the order."
      ]},
      { heading: "Treat Weidian seller context as listing-specific", paragraphs: [
        "A Weidian product page may be shared through a direct item URL, a shop page or an intermediary redirect. Preserve the item identifier and shop identity when visible. Do not infer reliability from the platform name, a seller nickname or a spreadsheet inclusion alone. Examine the current listing's option names, photographs, text and terms. Evidence from a different item in the same shop may provide context but does not prove this listing's condition or availability.",
        "When a Weidian link redirects, compare the final item ID with the one recorded in the spreadsheet. A shop may replace, duplicate or reorganize a listing. If the ID changes, classify the destination as a replacement and repeat the verification. This is especially important when old QC photos circulate beside new links; warehouse photos from one order and batch cannot authenticate another item."
      ]},
      { heading: "Interpret 1688 prices through quantity and specification", paragraphs: [
        "1688 is frequently used for wholesale or factory-oriented offers, so the lowest visible number may depend on quantity, specification or buyer level. Check minimum order quantity, unit tiers, variant-level price changes, packaging units and whether the seller permits a small order. A price copied into a spreadsheet can be accurate for one tier while being irrelevant to the quantity you plan to submit.",
        "Confirm whether an option represents one unit, a pair, a set, a sample or a carton. Read the dimensions and materials tied to that specification. If the listing requires seller confirmation, keep the field unresolved until the active order screen or agent communication confirms it. Never fill the gap by multiplying the headline price. An apparently exact total built on the wrong unit is worse than an openly pending estimate."
      ]},
      { heading: "Separate shared checks from marketplace-specific checks", paragraphs: [
        "Every link needs the same core record: marketplace, seller or shop, product ID, title meaning, selected option, quantity, live price, domestic freight and check date. Add marketplace-specific fields after that. Taobao often needs careful retail variant matching; Weidian needs strong item and shop identity; 1688 needs quantity-tier and unit interpretation. A single checklist works only when it leaves room for those different commercial structures.",
        "Use a four-state result for each field: confirmed, visible but ambiguous, requires agent or seller confirmation, or unavailable. This avoids turning a translation guess into a fact. A listing can still be a reasonable candidate with an unresolved field, but payment should wait if that field affects identity, compatibility, total quantity or a non-returnable choice."
      ]},
      { heading: "Submit the link without losing the evidence", paragraphs: [
        "Paste the original product link into the Joyagoo search or order flow and compare the parsed result with your source record. Official guidance says buyers then choose colour, size and quantity. Make those fields explicit. If the page displays a generic title or image after parsing, use the option details and saved source evidence to confirm that the order still points to the intended item.",
        "When normal parsing fails, the official guidance suggests DIY Orders for sources such as Yupoo, WeChat and Xianyu. A comparable principle applies to any manually described order: copy exact source information and avoid informal shorthand that only makes sense while the listing is open. The purchaser needs an instruction that remains unambiguous after translation, seller contact and time have separated the order from the spreadsheet row."
      ]},
      { heading: "Build the QC reference before the seller ships", paragraphs: [
        "Save the listing evidence immediately after payment: selected option, size or specification, quantity, key measurements, included parts and distinctive visual details. Later edits to the source page should not erase the reference. When warehouse QC appears, verify identity first. A good-looking product can still be the wrong colour, size, version or quantity, and a product matching the option can still have a condition issue.",
        "Request additional evidence only when it can change a decision. A measurement photo may resolve sizing; a close-up may resolve a visible mark; an image of included accessories may confirm completeness. Do not expect standard photos to prove material composition, authenticity or invisible function. The listing record defines what was ordered, while QC shows a limited sample of what arrived."
      ]},
      { heading: "Use a defensible approval rule", paragraphs: [
        "Approve the link for ordering when the source identity is stable, the exact option is available, quantity and price logic are understood, domestic freight is visible or clearly pending, and the Joyagoo order fields match. Pause when a required field is ambiguous. Reject or replace the link when the destination changes product family, hides the required variant, introduces an unexplained quantity rule or cannot be tied to the recorded item.",
        "This rule is intentionally stricter than checking whether the page opens. It produces a short but auditable chain from spreadsheet row to marketplace listing, from listing to order, and from order to QC reference. That chain is what makes product links useful over time. It also lets a spreadsheet editor correct one failed field without pretending that every source behaves the same way.",
        "When comparing marketplaces, keep the outcome neutral. Taobao is not automatically safer because its retail options look familiar, Weidian is not automatically risky because a link is shared directly, and 1688 is not automatically cheaper because it shows a lower tier. The evidence quality of the exact seller listing matters more than a platform stereotype.",
        "Finish by saving a compact decision note: chosen source, selected option, price basis, unresolved fields, evidence requested and next review time. This note helps the buyer resume after a delay and gives the warehouse comparison a reliable starting point. It is also the minimum useful context when a link needs to be reported or replaced.",
        "If the order spans more than one seller, keep a separate record for each listing. Combining products later in one international parcel does not merge their source identities, seller terms or QC clocks. Separate records make it possible to return one item, approve another and still plan consolidation without confusing which marketplace evidence belongs to which order."
      ]}
    ]
  },
  {
    slug: "joyagoo-spreadsheet-categories-shoes-hoodies-jackets-accessories",
    title: "Joyagoo Spreadsheet Categories: Shoes, Hoodies, Jackets and Accessories",
    description: "Use Joyagoo spreadsheet categories to narrow products, then apply category-specific checks for sizing, construction, included parts and packing risk.",
    meta: "CATEGORY SPREADSHEET GUIDE · 15 MIN",
    sourceNote,
    quickFacts: ["Category is a filter, not a verdict", "Shoes need system and length checks", "Clothing needs measurements", "Accessories need dimensions and parts", "Packing questions begin before payment"],
    sections: [
      { heading: "Let categories reduce search, not replace verification", paragraphs: [
        "A category column is valuable because it turns hundreds of mixed rows into a smaller set of relevant candidates. It can separate shoes, hoodies, jackets and accessories before you spend time opening listings. The label does not prove that an item fits the category perfectly, remains available or suits your use. Treat it as navigation. The live listing must still confirm the product, variant, measurements, materials and commercial terms.",
        "Good category use begins with an acceptance brief. Write what the item must do, the measurements that matter, the features that are optional and the evidence you expect at warehouse QC. Then use the spreadsheet to find candidates that appear capable of meeting that brief. This order protects against choosing a popular-looking row first and inventing requirements after the purchase."
      ]},
      { heading: "Shoes: convert size labels into comparable evidence", paragraphs: [
        "For shoes, a familiar size number is not enough. Identify the sizing system, check the seller's foot-length or insole guidance when supplied, and compare it with a shoe that already fits. Record the exact colourway and version because one listing can contain several visually similar options. Note whether a box or included accessories matter; those choices can change both completeness and parcel volume.",
        "Plan the warehouse check before ordering. Useful visible evidence can include the size tag, overall shape, both sides, outsole, heel, toe area, symmetry and included parts. Measurements can help when requested clearly, but perspective and tape placement affect interpretation. QC cannot guarantee long-term comfort, internal materials or authenticity. Its role is to compare observable arrival evidence with the option and requirements you saved."
      ]},
      { heading: "Hoodies: measure fit and define graphic tolerances", paragraphs: [
        "A hoodie category can mix pullovers, zip styles, lightweight tops and heavy fleece. Confirm garment type, fabric description, size chart and design option. Compare chest width, body length and sleeve measurement with a reference garment using the same measurement method. Letter sizes across sellers are not interchangeable. If the listing omits a measurement essential to fit, classify it as unresolved before payment.",
        "For printed or embroidered pieces, decide which visible details are decision-changing: placement, scale, centring, colour or obvious construction problems. Warehouse photos can show alignment and surface condition, but lighting can alter colour and folds can distort the graphic. Save the seller image and selected variant, then ask for a flat view or measurement only if that evidence would determine keep versus return."
      ]},
      { heading: "Jackets: check layering, closures and structure", paragraphs: [
        "Jackets introduce more interacting fields than a basic top. Decide whether the fit must allow a layer underneath, then compare chest, length, shoulder and sleeve measurements with an appropriate reference. Verify closure type, pocket layout, lining description, hood or collar configuration and selected colour. A spreadsheet thumbnail rarely shows every difference between jacket variants contained in one listing.",
        "Construction and packing also matter. Rigid panels, padded sections or protective hardware can increase volume, while compression may affect shape. Define which structure must be protected and whether removable elements should be included. At QC, check the overall silhouette, front and back, closures, pockets, visible seams and option identity. Do not infer waterproof performance or insulation level from appearance alone."
      ]},
      { heading: "Accessories: establish scale and included parts", paragraphs: [
        "Accessories is a broad category covering items whose images often hide scale. Record length, width, depth or compatible model as appropriate. Confirm material description without upgrading seller language into a guarantee. List every included strap, fastener, case, cable or small part that matters. A low displayed price can sometimes apply to one component rather than the complete arrangement shown in the main photograph.",
        "At warehouse arrival, ask whether standard views can confirm dimensions, hardware, visible surface condition and included parts. A ruler or tape photo is useful when scale changes the decision. For fragile surfaces or rigid shapes, pair the QC plan with a packing requirement. The item can arrive correctly at the warehouse and still face avoidable transit risk if its form is not protected."
      ]},
      { heading: "Compare candidates within a category fairly", paragraphs: [
        "Create a comparison table that uses the same fields for every candidate: product ID, seller, option, measurements, live price, domestic freight, evidence gaps and check date. Add category-specific fields after the common ones. This prevents a listing with attractive photography from winning simply because another seller supplied more honest but less polished information. Unknown values should remain visible rather than being scored as average.",
        "Do not rank candidates by spreadsheet inclusion, review count or headline price alone. Instead, eliminate those that fail a must-have condition, then compare the remaining evidence. A slightly higher listing with clear measurements and an unambiguous option may carry less decision risk than a cheaper listing that needs several assumptions. The goal is a defensible shortlist, not a universal best product."
      ]},
      { heading: "Move the category record into Joyagoo", paragraphs: [
        "Official Joyagoo guidance directs buyers to choose colour, size and quantity before adding an item or paying. Transfer the exact category record into those fields. Confirm that the parsed image and option text still represent the source listing. Pay attention to Chinese domestic shipping as a separate visible amount. If a required field cannot be selected or described, pause instead of hiding it in a general order remark.",
        "Keep the marketplace link and spreadsheet row after submission. Order statuses can show that purchasing, seller dispatch and warehouse arrival are separate stages; they do not prove that the correct variant was selected. The saved record gives the purchasing agent a clear reference if a seller asks a question, changes an option or cannot fulfil the original choice."
      ]},
      { heading: "Review QC with category-specific priorities", paragraphs: [
        "When QC completes, start with product identity, variant, quantity and visible size label. Then use the category checklist. Shoes emphasize shape and size evidence; hoodies emphasize measurements and graphic placement; jackets emphasize structure and closures; accessories emphasize dimensions and included parts. This sequence prevents cosmetic inspection from distracting you from a more fundamental mismatch.",
        "Act promptly because official guidance ties the return or exchange opportunity to the period after QC completion, subject to eligibility and seller conditions. Save the photos and decision. A useful spreadsheet can later record that the link was checked and which evidence was available, but it should not convert one warehouse sample into a permanent quality claim about the seller or category."
      ]},
      { heading: "Maintain categories without creating false confidence", paragraphs: [
        "Category pages should expose their limits. Show when rows were checked, retain source IDs, report dead or changed listings and avoid badges such as verified, authentic or best unless a narrow claim is explicitly defined and supported. If an item changes category or the seller replaces it, update the record rather than forcing it into the old description. Clean navigation is useful only when the underlying identity remains traceable.",
        "The resulting workflow is simple: define the need, filter by category, verify the live listing, compare consistent fields, submit exact options, and inspect category-relevant QC evidence. It improves speed without confusing convenience with proof. That is the appropriate role for Joyagoo spreadsheet categories: they organize attention while the buyer preserves responsibility for each live decision.",
        "A periodic category audit should also remove rows that no longer belong. If a jacket link now opens an accessory, or a shoe page retains only replacement laces, update both the category and availability state. Accurate removal is as valuable as adding more products because it protects users from false breadth and reduces wasted clicks.",
        "Finally, evaluate category performance by useful outcomes rather than row count. Track whether users reach working listings, whether options can be confirmed and whether the saved evidence supports QC. A shorter category with current IDs and clear variants produces more value than a large page whose links merely load."
      ]}
    ]
  },
  {
    slug: "joyagoo-link-not-working-deleted-listings-changed-ids",
    title: "Joyagoo Link Not Working: Deleted Listings, Changed IDs and Replacement Checks",
    description: "Diagnose a Joyagoo product link that fails, redirects or opens the wrong item, then document a safe replacement without transferring old assumptions.",
    meta: "BROKEN-LINK RECOVERY · 13 MIN",
    sourceNote,
    quickFacts: ["Name the failure type", "Preserve the original ID", "Do not trust a redirect blindly", "Treat replacements as new listings", "Report the evidence and date"],
    sections: [
      { heading: "Define what not working actually means", paragraphs: [
        "A Joyagoo link can fail in several different ways. The browser may show a deleted page, a marketplace login wall, a region restriction, an agent parsing error, an endless redirect or a live page for a different item. Record the visible outcome, final URL and check time. Calling all of these a dead link loses information that could determine whether the listing is gone, temporarily inaccessible or simply being opened through the wrong route.",
        "Test carefully without changing the commercial data. Open the spreadsheet link once, note the redirect chain and compare the final marketplace host and product ID with the row. Do not repeatedly submit the same broken order or create several carts. The purpose of diagnosis is to recover identity and decide the next safe step, not to force a page to load at any cost."
      ]},
      { heading: "Preserve the evidence before searching", paragraphs: [
        "Copy the original spreadsheet URL, any marketplace URL embedded in it, the product ID, seller or shop name, title, thumbnail, category, recorded option and last-check date. Even partial information can distinguish the intended item from a visually similar replacement. If the page still loads intermittently, save the relevant listing fields rather than the entire decorative page. Focus on information needed to reproduce the decision.",
        "A screenshot alone is not enough when its address and ID are missing. Conversely, an ID without a title or variant can identify a listing but not the option the reader intended. Keep both identity and commercial context. This record also protects the spreadsheet editor: a future update can explain why a row changed instead of silently substituting a new product under the old description."
      ]},
      { heading: "Recognize deletion, restriction and parsing failures", paragraphs: [
        "A deletion message or marketplace notice usually means the original offer is unavailable, but it may not reveal whether the seller removed it, the platform moderated it or access is restricted. State only what the page shows. A login or region wall means the destination could not be verified from that session; it does not prove deletion. A parsing failure means the agent could not interpret the link, not necessarily that the source page is invalid.",
        "Joyagoo's official guidance says original links can be pasted into search and lists several supported marketplaces. It also points to DIY Orders when products cannot be searched normally on sources such as Yupoo, WeChat and Xianyu. Use that route only when the source information is sufficiently complete. Manual submission cannot repair an unknown product identity or an ambiguous option."
      ]},
      { heading: "Detect changed IDs and wrong-item redirects", paragraphs: [
        "Some old links open a seller shop, a recommendation page or a newly assigned product. Compare item IDs, not just images. A seller may reuse similar photography across listings, and third parties may create redirects that point to current alternatives. If the final ID differs from the saved one, mark it as changed. The destination must be reviewed as a separate candidate even if the title and thumbnail look familiar.",
        "Look for material differences in category, specification, available sizes, bundles, quantity rules and seller identity. A redirect from one black hoodie to another black hoodie is still a product change. Old QC photos, review comments and recorded prices belong to the original item unless evidence explicitly links them to the replacement. Keeping this boundary avoids accidental claims that a new seller or batch has inherited an old record."
      ]},
      { heading: "Search for a replacement with explicit must-haves", paragraphs: [
        "Before searching, list the fields that cannot change: function, size range, dimensions, design details, compatible model, included parts or material description. Then identify fields that can vary, such as a minor colour shade or packaging. Search by the original product ID where appropriate, distinctive title phrases, shop context or image. A result is a candidate only until the must-have fields are confirmed.",
        "Avoid using price as the first replacement filter. A cheaper listing may represent a smaller quantity, different option or missing component. Compare live option price, domestic delivery, minimum quantity and seller notes after identity. If the replacement cannot meet one essential requirement, reject it even when it seems close. The cost of a wrong order is usually higher than the time saved by accepting an uncertain match."
      ]},
      { heading: "Rebuild the listing record from zero", paragraphs: [
        "For a replacement, create a fresh record with marketplace, new product ID, seller, current title, selected option, quantity, live price, domestic freight and date. Do not edit the old ID in place. Link the records with a short reason such as deleted listing, unavailable variant or wrong-item redirect. This preserves history while directing readers to the current candidate.",
        "Review the replacement's measurements, materials, included parts and visible images independently. Decide which warehouse evidence would be needed later. If a seller uses the same photographs as the old listing, treat that as a visual similarity, not proof of the same product or factory. The replacement becomes usable because its own fields are coherent, not because it resembles a row that once worked."
      ]},
      { heading: "Verify the replacement in the active order", paragraphs: [
        "Paste the current source link into Joyagoo and compare the parsed result with the new record. Select colour, size and quantity as directed by the official purchase flow. Confirm that the price and Chinese local shipping shown for the selected option make sense. If the agent interface changes the destination, option wording or image, stop and reconcile the difference before paying.",
        "For a manual order, describe the variant so a purchaser can act without seeing your spreadsheet. Include the source page, original labels when useful, quantity and any decision-critical seller note. Do not ask the agent to choose an equivalent model or best size unless you have defined the acceptable evidence. An instruction that delegates an undefined choice transfers risk rather than resolving it."
      ]},
      { heading: "Close the loop with a useful update log", paragraphs: [
        "Update the spreadsheet status with the date, failure class and replacement ID. Keep the old row as inactive when history matters, or point it to a versioned change log. The note should tell a future reader what was observed: deleted page, unavailable option, changed ID, parsing failure or access restriction. Avoid claiming the seller intentionally deceived buyers unless direct evidence supports that conclusion.",
        "Recheck the replacement before payment and use the saved listing record at QC. If it fails too, repeat the process rather than layering another unrecorded redirect. A robust spreadsheet is not one with zero broken links; no public index can guarantee that. It is one that detects failures quickly, preserves identity and makes every replacement traceable.",
        "Avoid sharing private account pages, cart tokens or order identifiers when reporting the failure. The public source URL, item ID, observed message and date are usually enough for editorial maintenance. If a problem appears only after login, describe it without publishing personal details and let another editor reproduce it independently.",
        "Use the same discipline for restored listings. If the old ID becomes available again, compare its current seller, options and terms with the archived record before reactivating the row. Restoration is a new check, not proof that the listing remained unchanged during the gap.",
        "Set an expiry for unresolved reports. A link that could not be accessed because of login, region or a temporary marketplace error should be checked again before being marked deleted. Record the second result and the test conditions. This small delay prevents avoidable churn while still removing destinations that consistently fail or no longer match the saved identity. A second editor or device can help distinguish a local access problem from a source-wide failure."
      ]}
    ]
  },
  {
    slug: "joyagoo-spreadsheet-qc-photos-workflow",
    title: "Joyagoo Spreadsheet and QC Photos: A Pre-Order Verification Workflow",
    description: "Turn a Joyagoo spreadsheet row into a listing evidence record and a focused QC plan before the seller sends the item to the warehouse.",
    meta: "SPREADSHEET TO QC · 15 MIN",
    sourceNote,
    quickFacts: ["QC starts before payment", "Save the selected listing", "Identity comes before condition", "Ask for decision-changing evidence", "Act from the QC timestamp"],
    sections: [
      { heading: "Plan QC before placing the order", paragraphs: [
        "Warehouse photographs are most useful when the buyer already knows what must be confirmed. If you wait until photos arrive, the original listing may have changed and the return clock may already be running. Use the spreadsheet row to start an evidence record before payment: source link, product ID, seller, option, measurements, included parts and the few visible details that would change your decision.",
        "This does not turn QC into a guarantee. Official Joyagoo guidance describes a general quality check after warehouse arrival and makes the images available in the order area. Photographs can show identity, visible condition and selected details. They cannot prove every material, hidden function, authenticity claim or future durability. A good plan asks only questions that the available evidence can answer."
      ]},
      { heading: "Convert the spreadsheet row into a listing baseline", paragraphs: [
        "A spreadsheet title and thumbnail are too small to support a return decision. Open the live destination and confirm marketplace, product ID, seller, selected colour, size or specification, quantity, price and domestic freight. Save the current size chart, important dimensions, included components and seller images tied to the selected option. Mark the date because those details can change after the order.",
        "Separate confirmed facts from assumptions. A selected option shown in the active listing is confirmed for that moment. A spreadsheet category is a navigation label. A material inferred from a photograph is an assumption. If a required measurement or component is not stated, list it as open. This baseline will later make it obvious which QC questions remain necessary."
      ]},
      { heading: "Define observable acceptance criteria", paragraphs: [
        "Write criteria in forms a warehouse image can test: correct colour label, selected size tag, complete quantity, visible dimensions within a stated tolerance, included strap, centred graphic, intact zipper or no obvious surface damage. Avoid vague requests such as good quality or looks authentic. Those phrases give the photographer no objective target and give the buyer no repeatable decision rule.",
        "Prioritize the criteria. An identity mismatch usually matters more than a removable thread. A missing component may make the item unusable, while a minor cosmetic variation may be acceptable at the price. Set keep, request-more-evidence and return conditions in advance. Precommitting reduces the temptation to rationalize a mismatch after waiting for the item to arrive."
      ]},
      { heading: "Submit exact options through Joyagoo", paragraphs: [
        "Joyagoo's Shopping Guidance says buyers select colour, size and quantity before adding an item or paying. Compare those fields with the listing baseline and do not rely on a spreadsheet row to supply them automatically. If the parsed option names differ from the source page, preserve both and resolve the mapping. A correct link with the wrong variant is still a wrong order.",
        "The same guidance explains that the product payment includes the item and Chinese local shipping, while the seller remains central to product fulfilment. Keep the submitted order details and any purchaser communication. They show which variant was requested if the seller later reports that an option is unavailable or proposes a substitution. Never accept an undefined replacement simply to keep the order moving."
      ]},
      { heading: "Read the order status as an evidence timeline", paragraphs: [
        "Order Processing, Purchased, Seller Sent, Stock Arrived and QC Completed refer to different stages. Record when meaningful changes occur. A listing baseline is created before payment; seller dispatch shows movement, not correctness; warehouse arrival confirms receipt, not condition; QC completion provides the visible evidence for review. Keeping these stages separate helps direct a question to the responsible party.",
        "Do not wait for every item in a future parcel before reviewing one completed QC set. Official guidance says buyers should check photos promptly and places the return or exchange opportunity after QC completion, subject to seller and item conditions. The relevant clock belongs to each order's status, not to your planned consolidation date."
      ]},
      { heading: "Review identity before workmanship", paragraphs: [
        "Begin with product family, selected colour, model or design, size tag, quantity and included parts. Compare them with the saved listing baseline. Only after identity matches should you inspect overall shape, symmetry, seams, hardware, print placement and visible damage. This order prevents attractive workmanship from hiding a wrong variant and prevents a correct variant from being rejected because of photographic lighting alone.",
        "Use side-by-side evidence, but account for perspective, compression and warehouse lighting. Colour differences on two screens are not conclusive. Measurements depend on tape placement and garment positioning. If the difference would change your decision, request a more controlled photo with a precise instruction. If it would not, do not consume time collecting decorative images."
      ]},
      { heading: "Request only decision-changing additional evidence", paragraphs: [
        "A focused request identifies the item, angle, feature and purpose: measure chest width flat from point to point; photograph the size tag clearly; show both sides of the zipper; place all included accessories in one frame. Joyagoo publishes a detailed-photo service for customized angles or measurements, while current public pages should be checked for the live fee and conditions. Avoid hard-coding a price into the decision.",
        "More photos do not automatically create more certainty. A close-up can reveal a mark but cannot prove long-term performance. A label image can confirm the visible label but not every authenticity claim. Stop requesting evidence when the remaining uncertainty is outside photographic reach. At that point the buyer must accept the limitation, seek seller clarification or return the item if eligible."
      ]},
      { heading: "Record the QC decision and feed it back carefully", paragraphs: [
        "Document the result as keep, request more evidence, exchange or return, with the supporting image and timestamp. A return request should identify the selected option and observable mismatch rather than offering a general statement of dissatisfaction. Preserve packaging and seller terms when eligibility depends on resalable condition. The evidence record makes a support conversation shorter and more specific.",
        "Update the spreadsheet only with claims the case supports. You can mark that a link worked on a date, that a listed option arrived in one order, or that a product ID changed. Do not convert one QC set into a permanent seller rating, batch guarantee or authenticity badge. The strongest workflow connects discovery, live listing, submitted order and warehouse evidence while keeping each layer's limits visible.",
        "After the decision, compare the result with the original acceptance criteria. If the evidence resolved the planned questions, the workflow worked even when the item was returned. If an important question could not be photographed, revise the next pre-order brief rather than asking for more of the same kind of image. This feedback improves future buying decisions without claiming that one sample predicts another.",
        "Archive the listing snapshot and QC images under the order date, not in a public product row that could expose private information. The spreadsheet needs only a limited status such as link checked or option changed. Detailed order evidence belongs with the buyer's record and should be shared with support only when it is relevant.",
        "Before parcel submission, review whether the kept item needs a specific packing note based on the category and QC result. This is a separate decision from product acceptance: a correct item can still require shape protection, moisture protection or careful grouping. Recording that handoff closes the workflow from discovery to a shipment-ready warehouse item.",
        "Keep the workflow proportionate to value and risk. A simple low-value accessory may need only identity, quantity and visible-condition checks, while a fitted garment or multi-part item justifies measurements and completeness evidence. Applying the same extensive request to every item adds cost and delay without improving the decisions that actually matter."
      ]}
    ]
  },
  {
    slug: "joyagoo-seller-listing-checklist-price-variant-domestic-shipping",
    title: "Joyagoo Seller Listing Checklist: Price, Variant, Domestic Shipping and Evidence",
    description: "Audit a seller listing before Joyagoo payment by separating base price, option price, quantity, China-side shipping and missing evidence.",
    meta: "SELLER LISTING CHECKLIST · 14 MIN",
    sourceNote,
    quickFacts: ["Headline price is not the total", "Variant names must be explicit", "Domestic shipping is separate", "Unknown fields stay unknown", "Save the evidence before paying"],
    sections: [
      { heading: "Audit the listing that controls the transaction", paragraphs: [
        "A spreadsheet can help you reach a seller page, but the current seller listing defines the product being offered. Open it before payment and capture the marketplace, product ID, shop, title, selected option, quantity and check date. Make sure the page is the intended destination rather than a shop home, recommendation result or replacement item. A familiar thumbnail is not enough to establish identity.",
        "Joyagoo's purchasing instructions explain that displayed products come from third-party shopping platforms rather than being sold by Joyagoo. That boundary matters. The seller controls the source listing, stock, dispatch and many after-sales conditions, while the agent helps execute the purchase. Your checklist should therefore separate seller claims from fields shown by the agent interface."
      ]},
      { heading: "Decompose the displayed price", paragraphs: [
        "Record the headline price, then select the exact variant and quantity to reveal the applicable product amount. Some pages show a range, a promotional figure, a deposit, a quantity tier or the cheapest accessory in the option set. Do not copy the lowest number into a budget until you can tie it to the intended specification. Note the currency and whether the amount is per unit, pair, set or batch.",
        "If the seller requires confirmation, mark the price as pending. An agent estimate or spreadsheet snapshot is not a seller commitment. Compare the live amount again in the Joyagoo order screen before paying. If the parsed price differs materially, investigate the option, quantity and source link rather than assuming a platform fee explains the gap. Misclassification at this stage contaminates every later cost comparison."
      ]},
      { heading: "Describe the variant so it cannot drift", paragraphs: [
        "Write the selected colour, size, model, version, bundle and quantity in plain language. Preserve original option text when translation could hide a distinction. Check whether choosing one field changes other fields, the main image or price. A seller may group multiple generations, materials or package contents under one listing. The product is not specified until the full combination is clear.",
        "Avoid requests such as same as photo when several photos appear. Reference the option label and identifying image or code. For size, record the seller's measurement table and the measurement method used for comparison. If an option is unavailable, do not let a purchaser select something close without your acceptance rule. A substitute is a new decision, not an administrative correction."
      ]},
      { heading: "Treat Chinese domestic shipping as its own field", paragraphs: [
        "Official Joyagoo Shopping Guidance states that the product payment covers the item and Chinese local shipping fee. The seller-to-warehouse charge is separate from later international freight. Capture whether the listing shows free domestic delivery, a fixed amount, a location-dependent estimate or a pending field. A spreadsheet price that omits it is incomplete but not necessarily wrong; it is a product snapshot, not a landed-cost quote.",
        "Domestic freight can also change with quantity, seller location or promotion. Verify it in the active order rather than using a number copied from another buyer. If it is unexpectedly high, check the quantity and selected option first. Keep the amount attached to the seller order, so it is not later confused with a Joyagoo service charge or international parcel cost."
      ]},
      { heading: "Check stock and seller notes without inventing certainty", paragraphs: [
        "A selectable option may still require seller confirmation. Look for dispatch notes, preorder language, customization, minimum quantities and restrictions on return or exchange. Record the note and its date. Do not convert an estimated dispatch statement into a guaranteed warehouse arrival date. The seller's performance and domestic carrier handoff are separate stages from the agent's purchase processing.",
        "When the listing is unclear, formulate one specific question. Ask whether the selected option is available, what a bundle contains or which measurement method applies. Avoid asking whether the product is good, genuine or recommended; those questions invite unsupported judgment. A useful answer must resolve a field that affects payment, compatibility or the later keep-return decision."
      ]},
      { heading: "Save evidence that survives listing edits", paragraphs: [
        "Keep the source URL and product ID with a compact capture of selected options, applicable price, domestic freight, size chart, included parts and critical seller notes. A full-page screenshot can be difficult to search later, so add a text summary. Store the check date. If the seller edits the listing after purchase, you will still have a clear reference for the submitted order and QC review.",
        "Label each item as official platform guidance, seller statement, visible listing field or buyer interpretation. This prevents a seller marketing phrase from being repeated as an agent guarantee. It also helps when sources disagree: preserve both records, identify the conflict and seek clarification before payment instead of silently choosing the interpretation you prefer."
      ]},
      { heading: "Reconcile the listing with the Joyagoo order", paragraphs: [
        "Paste the original link and compare the Joyagoo result with your record. Official guidance directs buyers to choose colour, size and quantity, then pay for the product and local shipping. Confirm that the order preserves the same source, option and quantity. If the interface displays a different image or translated title, rely on the full identity record rather than one text label, but pause if the mapping cannot be demonstrated.",
        "Review every amount under the correct category: goods, seller domestic freight and any separately selected service. International freight belongs to a later parcel stage. This classification makes the initial payment understandable and protects SEO guides from repeating the misleading claim that a spreadsheet price or free agent service means the entire transaction has no additional cost."
      ]},
      { heading: "Turn the checklist into a payment gate", paragraphs: [
        "Proceed only when source identity, exact variant, quantity, applicable price and domestic freight are confirmed or deliberately accepted as pending with a clear next step. Pause when a must-have measurement, included part or seller condition is ambiguous. Reject the listing when it redirects to another product, lacks the required option or uses a quantity rule incompatible with the order.",
        "After payment, preserve the record and use it at warehouse QC. The checklist does not predict product quality; it ensures that the order being inspected is the order you intended to place. That narrower promise is both achievable and valuable. It reduces avoidable mismatches while leaving seller performance, warehouse evidence and international shipping in their proper stages.",
        "Add a stop condition for customized, personalized or otherwise irreversible choices. Names, numbers, cut lengths and made-to-order specifications require stronger confirmation because ordinary return options may not apply. Save the seller's displayed condition and obtain clarification before authorizing purchase; do not rely on a generic spreadsheet description for an irreversible field.",
        "Keep promotions separate from product identity. A coupon or temporary seller discount can change the amount without changing the item, while an option switch can change both. Record the promotion date and the underlying variant price so a later comparison does not mistake an expired discount for a seller price increase.",
        "Use the completed checklist to write a concise purchasing note, not a narrative. Include source, exact option, quantity and only the clarifications that the selectors cannot express. A short, structured instruction is easier to translate and verify than a paragraph containing several alternatives. If the note still asks the purchaser to choose, the buyer has not finished the decision.",
        "Review the checklist when the order remains unpurchased for a meaningful period. Stock, promotions and seller notes can change while an item waits in processing. A fresh comparison should confirm that the source identity and selected commercial fields still hold before accepting a later purchase or seller-proposed adjustment. Date that recheck so it does not silently replace the original payment evidence."
      ]}
    ]
  },
  {
    slug: "joyagoo-size-colour-listing-measurement-qc-checks",
    title: "Joyagoo Size and Colour Checks Using Listings, Measurements and QC Evidence",
    description: "Compare size and colour across seller listings, saved measurements and warehouse QC without treating labels, lighting or one photo as proof.",
    meta: "SIZE & COLOUR EVIDENCE · 15 MIN",
    sourceNote,
    quickFacts: ["Size labels are seller-specific", "Use one measurement method", "Screens alter colour", "QC confirms visible evidence only", "Set tolerances before ordering"],
    sections: [
      { heading: "Replace familiar labels with a measurement record", paragraphs: [
        "Small, medium and large are seller labels, not universal dimensions. A shoe number also depends on the sizing system and seller guidance. Before choosing an option from a Joyagoo spreadsheet link, open the seller chart and identify the measurements relevant to the item. Compare them with a garment or shoe that already fits, using the same points and method. Record both the target and an acceptable range.",
        "Do not compare body circumference directly with a flat garment width without converting the measurement and allowing for ease. For shoes, distinguish foot length, insole length and outsole length. For jackets, account for the layer worn underneath. A documented method turns sizing from a guess into a reproducible comparison, even though seller measurements and warehouse measurements can still contain tolerance."
      ]},
      { heading: "Verify which chart belongs to the selected option", paragraphs: [
        "Listings can include several styles, batches or versions with different charts. Confirm that the chart applies to the exact variant selected. Check units, measurement orientation and whether the figures describe the product or a recommended body size. Save the chart and option together. A screenshot of a chart without the linked product ID and variant can become misleading after a seller edits the page.",
        "If two charts conflict, do not average them. Identify the current listing field, ask the seller or purchasing agent for clarification, and keep the answer with the order. Mark unresolved values openly. The purpose is not to force every listing into a clean table; it is to prevent a confident size selection based on evidence that belongs to another item."
      ]},
      { heading: "Define tolerance before seeing warehouse results", paragraphs: [
        "Manufactured items and manual measurements can vary. Decide what difference is acceptable for each dimension before ordering. A small change in a loose hoodie may be harmless, while the same numerical change in a fitted shoe or compatible accessory can be decisive. Write the tolerance beside the target and explain the use case. This prevents the decision threshold from moving after the item arrives.",
        "Keep tolerances realistic and observable. Warehouse tape placement, fabric tension and camera perspective can affect a reading. If a measurement falls close to the boundary, request a controlled repeat rather than declaring an immediate mismatch. If the result is clearly outside the range, preserve the listing chart and QC evidence for an exchange or return request, subject to eligibility."
      ]},
      { heading: "Treat colour as a range of evidence", paragraphs: [
        "Colour on a spreadsheet thumbnail, seller image and warehouse photo can differ because of lighting, white balance, compression and screen settings. Start with the seller's written option name and its associated image. Record whether the decision depends on a broad family such as navy versus black or on a subtle shade. The narrower the required shade, the weaker a single uncontrolled online image becomes as proof.",
        "Compare several views when available and look for consistent relationships with neutral objects, but do not claim exact colour calibration. If the wrong named option arrived, the label and order record are strong evidence. If the concern is a small tone difference, request a clearer image only when it can reasonably resolve the question. Some colour uncertainty must be accepted or avoided before purchase."
      ]},
      { heading: "Submit size and colour explicitly", paragraphs: [
        "Joyagoo's official purchase flow tells buyers to select colour, size and quantity. Confirm all three in the active order rather than assuming they transfer from a spreadsheet row. Preserve the original seller labels next to your interpretation. If an option name is truncated or translated differently, compare product ID, image and combination before paying. An unambiguous order is the foundation for any later mismatch claim.",
        "Do not place critical instructions only in a general remark when a structured selector exists. Use the selector, then add clarification if needed. If the selected combination changes the price or domestic freight, record the final fields. When the seller cannot supply it and proposes an alternative, reopen the acceptance brief. Similar colour or adjacent size is not automatically acceptable."
      ]},
      { heading: "Design a measurement request that can be repeated", paragraphs: [
        "Specify the item, measurement points, position and unit. For a garment, state that it should be laid flat and identify endpoints; for an accessory, define external or internal dimensions; for a shoe, state whether you need the visible insole or another reference. A vague request to measure the item can produce a technically correct photo that does not answer the fit question.",
        "Joyagoo publishes a detailed-photo service for custom views and measurements. Check the current order interface for the active fee and terms because public help pages can change. Request the smallest set of photos that resolves the decision. Multiple inconsistent measurements are less useful than one clear method repeated against the same seller dimension."
      ]},
      { heading: "Review QC in the right sequence", paragraphs: [
        "At QC, verify product identity, named colour option, size tag and quantity before measuring. Then compare requested dimensions with the saved chart and tolerance. Finally inspect visible condition and construction. If the tag is wrong, a good measurement may not resolve the order mismatch; if the tag is right but the measurement is outside tolerance, the photo and chart show a different kind of issue.",
        "Account for photographic limits. A dark item under warm light can appear brown; a curved tape can overstate length; a garment not laid flat can distort width. Ask for a repeat when technique is visibly inadequate and the result matters. Do not use a QC photo to infer hidden composition, colour fastness, comfort or future shrinkage. Those claims exceed the evidence."
      ]},
      { heading: "Make a time-aware keep or return decision", paragraphs: [
        "Official guidance instructs buyers to review QC promptly and describes a limited post-QC period for eligible return or exchange requests. Record the QC completion time and do not wait for unrelated warehouse items. Compare the observed mismatch with the preset tolerance, expected use, return eligibility and cost. A documented threshold supports a faster, more consistent decision than a general feeling that the item looks off.",
        "Keep the final record with the spreadsheet link, live listing, selected order fields and QC evidence. It can support a specific request and improve future sizing decisions. It cannot guarantee another batch or seller item. The method works because it separates labels, measurements, colour impressions and photographic limits instead of asking one image to prove everything at once.",
        "For future orders, compare outcomes only when the measurement method matches. A chest width taken at a different height or a shoe measurement taken from a different surface should not be entered in the same column without a note. Method consistency matters more than collecting a large number of figures, because inconsistent precision creates false confidence.",
        "Colour decisions also benefit from written boundaries. Record acceptable families and unacceptable substitutions before ordering, such as dark navy acceptable but black not acceptable. This is more actionable than a demand for an exact screen colour. It gives the buyer, purchaser and QC reviewer a shared rule while acknowledging that unmanaged photographs cannot provide laboratory colour matching.",
        "If the listing offers no usable size chart and fit is essential, the safest outcome may be to choose another listing. Warehouse measurements occur after seller dispatch and may leave only a limited after-sales path. Pre-order evidence should carry the decision whenever possible; QC is a final comparison point, not a substitute for missing seller information.",
        "For sets or multi-size orders, record each variant as a separate line even when the seller uses one product link. This prevents a correct total quantity from hiding one wrong size or colour. At QC, reconcile the count by option and attach any measurement evidence to the specific unit it describes."
      ]}
    ]
  },
  {
    slug: "joyagoo-spreadsheet-update-log-product-id-price-availability",
    title: "Joyagoo Spreadsheet Update Log: Product IDs, Prices and Availability Changes",
    description: "Build a transparent update log that records Joyagoo spreadsheet link identity, price snapshots, option availability and replacement history without false guarantees.",
    meta: "SPREADSHEET UPDATE LOG · 14 MIN",
    sourceNote,
    quickFacts: ["IDs anchor listing identity", "Prices need timestamps", "Availability is option-specific", "Replacements keep separate history", "Logs disclose uncertainty"],
    sections: [
      { heading: "Use the update log as evidence, not decoration", paragraphs: [
        "A useful spreadsheet update log explains what changed, when it was observed and which source supported the change. It does not simply display an updated badge. For each row, preserve marketplace, product ID, seller or shop, selected option context, observed price, availability state, last-check date and editor note. These fields let a reader understand the freshness and limits of the row before opening it.",
        "The log should never imply continuous monitoring unless continuous monitoring actually exists. A listing checked today can change tomorrow. Use language such as observed available on the stated date rather than in stock. This keeps the claim accurate and encourages the buyer to recheck the live seller page and active Joyagoo order before payment."
      ]},
      { heading: "Make product IDs the identity anchor", paragraphs: [
        "URLs can acquire tracking parameters, redirects or new agent wrappers while still pointing to the same marketplace item. A product ID helps normalize those variations. Store the original source host and ID separately from the convenient outbound link. When the final destination changes, compare the ID before treating the row as current. The title and thumbnail are secondary identity signals, not substitutes for the source identifier.",
        "If a source lacks a stable public ID, record the strongest available combination: shop, canonical address, title, option and image reference. State that identity confidence is lower. Do not invent an ID or reuse one from a similar product. A transparent incomplete record is safer than a precise-looking field that maps readers to the wrong listing."
      ]},
      { heading: "Record prices as scoped snapshots", paragraphs: [
        "Every recorded price needs currency, option, quantity or tier, and observation date. A headline range is different from the amount for a selected size or bundle. Chinese domestic shipping should have its own field because official Joyagoo guidance treats it as part of the initial product payment but distinct from the item price. International freight belongs to a later parcel decision and should not be merged into the row.",
        "When the price changes, append a dated observation or replace the visible snapshot while keeping history in the log. Do not label a difference as an increase or discount until the compared option and quantity match. A lower current headline can coexist with a higher intended-variant price. Good logs explain the basis of comparison and leave promotions or seller-specific pricing clearly time limited."
      ]},
      { heading: "Model availability at the option level", paragraphs: [
        "Available is too broad when a listing contains multiple variants. Record whether the page loads, whether the required colour and size can be selected, whether quantity is allowed, and whether the seller or agent still needs to confirm stock. A listing can be active while the only relevant option is unavailable. Conversely, a temporary access wall does not prove that every variant has been deleted.",
        "Use consistent states such as active and selectable, active but target option unavailable, seller confirmation required, redirected, inaccessible, or deleted message observed. Include the check date and, when helpful, a short evidence note. These states make reports comparable without pretending to know the seller's inventory system."
      ]},
      { heading: "Version replacements instead of overwriting history", paragraphs: [
        "When an original listing is deleted or materially changed, create a replacement record with its own product ID, seller, check date and evidence. Link it to the inactive row with a reason. Do not overwrite the old ID and keep old QC comments or prices attached. A replacement that uses the same images is still a separate listing and may represent different options, batches or seller obligations.",
        "Define the replacement criteria: same required function, compatible measurements, intended design, included parts and acceptable commercial terms. Record meaningful differences. This lets users decide whether the new candidate serves their need instead of presenting it as an invisible continuation. It also makes it possible to reverse the update if the original listing returns."
      ]},
      { heading: "Separate editorial checks from buyer verification", paragraphs: [
        "An editor can confirm that a destination loaded and that certain fields were visible on a date. The buyer must confirm the exact option, quantity, current price, domestic freight and seller terms for their order. Put this boundary near the spreadsheet and reflect it in the log. Avoid labels such as verified seller, authentic product or guaranteed link when the evidence only supports a narrower technical check.",
        "Joyagoo's published guidance supports pasting original product links and selecting colour, size and quantity. The spreadsheet can prepare those details, but the active order screen is the transaction checkpoint. A log entry should therefore point readers to the live recheck rather than encouraging one-click payment based on editorial metadata."
      ]},
      { heading: "Create a repeatable maintenance cycle", paragraphs: [
        "Prioritize rows by traffic, age, reported failure and commercial volatility. Check high-use or frequently changing rows more often than stable low-use references. During a review, verify destination, source ID, intended option, price basis and availability state. Record only actual changes and update the last-check field even when the row remains valid. This creates an honest maintenance history.",
        "Provide a broken-link report path that asks for row, observed problem, final destination and date without collecting private order data. Review reports before editing. One user's region or login error may not reproduce, while a changed ID affects everyone. The log should describe the confirmed scope instead of turning a single report into a universal outage."
      ]},
      { heading: "Use the log at order and QC stages", paragraphs: [
        "Before payment, compare the log with the live seller listing and Joyagoo order fields. If the row is old or a key field differs, treat the live evidence as controlling and submit an update. After warehouse arrival, compare QC with the saved buyer record, not with a later edited spreadsheet row. The log tracks public listing changes; it does not replace the transaction snapshot.",
        "A strong update system leaves a traceable path from old ID to new ID, from price snapshot to live option, and from availability observation to actual order choice. It improves click quality because readers reach current candidates with clear expectations. More importantly, it prevents freshness language from becoming a guarantee that no independent spreadsheet can keep.",
        "Publish a short change taxonomy so editors use the same meanings. Content change can describe title or image edits; commercial change can describe price, freight or quantity; option change can describe size or colour availability; identity change can describe a new item ID or seller. Consistent labels make the history searchable and reduce subjective notes.",
        "Do not backdate checks or update every row's date after a bulk formatting edit. A last-checked field should mean that a person or defined process verified the relevant destination and fields. Keep editorial formatting dates separate from commercial verification dates so readers can judge freshness honestly.",
        "Archive rather than delete when a row has meaningful history, but keep inactive rows out of normal product results. An archive supports audits and replacement links without sending users to known failures. If storage becomes large, retain the identity, dates and change reasons even when screenshots are removed according to the site's privacy and retention policy.",
        "Measure log quality with practical metrics: percentage of rows carrying source IDs, time to review a broken-link report, share of replacements with preserved history and outbound clicks that reach valid destinations. These measures reward accuracy and recovery. Raw row count and the appearance of constant freshness can encourage the opposite behaviour.",
        "Schedule rechecks according to evidence, not an arbitrary promise that every row is updated daily. Fast-changing listings and highly clicked categories deserve shorter intervals; stable references can be reviewed less often. Displaying the actual last-check date lets readers make that freshness judgment themselves."
      ]}
    ]
  }
];

export const spreadsheetArticleSlugs = spreadsheetArticles.map(article => article.slug);
