import type {SeoArticle} from "./seo-articles";
import type {Lang} from "./site-data";

export const returnMatrixArticle:SeoArticle={slug:"joyagoo-return-eligibility-matrix-seller-condition-packaging",title:"Joyagoo Return Eligibility Matrix: Seller Rules, Product Condition and Packaging",description:"Use a Joyagoo return eligibility matrix to separate the published request window from seller participation, product condition, packaging and evidence requirements.",meta:"RETURN POLICY MATRIX · 15 MIN",sourceNote:"Policy checked August 31, 2026 against Joyagoo's current public return and shopping guidance. The live order record, seller decision and current policy control an individual request.",quickFacts:["A time window is not automatic eligibility","Seller rules remain a gate","Resalable condition matters","Packaging changes can block a return","Evidence should match the stated reason"],sections:[
{heading:"Return eligibility is an intersection, not one promise",paragraphs:["Joyagoo's current public return page describes a five-day, 120-hour request period after an order reaches QC Completed for eligible products. That clock is important, but it is only one part of eligibility. The same public page also refers to seller participation, third-party platform rules, resalable product condition and packaging requirements. A request can therefore be timely and still fail another gate. Reading only the deadline produces a much broader promise than the published policy supports.","Use a matrix with five gates: request time, seller or marketplace support, product category, product condition, and packaging or included-part condition. Add a sixth column for the evidence you saved. A return is ready to submit only when the applicable gates are supported by current records. An unknown gate is not a yes. It is a reason to pause irreversible actions, preserve the item and ask a precise question while the request window remains open."]},
{heading:"Gate one: establish the official clock",paragraphs:["Save the exact timestamp when the order status changed to QC Completed. The policy ties the standard request period to that event, not to the day you eventually open the photos, not to the original payment date and not to the arrival of another item. Record the timestamp, its displayed time zone if available, and your own conservative deadline. If the interface shows a return button or countdown, capture that state as additional transaction evidence.","Do not wait for a planned consolidation, a second seller or a support conversation about an unrelated item. Each warehouse order can have its own clock. Submit or ask for clarification before the earliest defensible deadline. A missing return button can indicate that the ordinary period has passed, but it does not explain every reason for ineligibility. Preserve the screen and ask which gate failed rather than assuming the seller rejected the product for a specific reason."]},
{heading:"Gate two: identify the seller and marketplace rule",paragraphs:["The return service depends on the third-party seller and marketplace conditions. Joyagoo acts as the purchasing and communication bridge; it cannot create a seller return right that the source transaction did not provide. Before payment, save the source listing's return signal when visible. At QC, check the current order controls and any seller message. A generic platform statement should not replace the evidence attached to the exact product order.","Classify seller support as confirmed, denied or unknown. Confirmed should point to a current order control or written response, not an assumption based on another listing from the same shop. Denied should preserve the stated reason. Unknown requires an immediate question that names the order and product. The matrix prevents a broad phrase such as ‘five-day guarantee’ from hiding the seller-level condition that decides whether the ordinary procedure is available."]},
{heading:"Gate three: screen product-category exclusions",paragraphs:["Joyagoo's public return page lists categories and situations that may be unavailable for ordinary return, including customized goods, some hygiene-sensitive products, second-hand goods, food, publications in specified quantities, and products governed by additional seller rules. The published list should be rechecked because category wording can change. Do not extend one example to every item that sounds similar, and do not omit an exclusion because the product appears unused.","Before ordering a sensitive category, write one line: ‘ordinary return eligibility not assumed; confirm before payment.’ For customized text, removed tags, opened sealed goods or buyer-requested packaging changes, the safest decision occurs before the irreversible instruction. If the category is unclear, send the exact source description rather than a nickname. The matrix records the answer and avoids presenting a later exception as though it were standard protection."]},
{heading:"Gate four: preserve resalable product condition",paragraphs:["The policy connects ordinary return eligibility with a product remaining new and resalable under the seller's requirements. Warehouse QC lets the buyer inspect evidence; it is not permission to alter the product without consequence. Do not request tag removal, assembly, wear testing, personalization or another irreversible change before deciding whether the item will be kept. If staff must handle an item to photograph it, distinguish normal inspection from a buyer-requested alteration.","Record visible condition from the first warehouse photos and any additional evidence. If the return reason is a defect, identify the location and compare it with the saved listing or expected condition. If the return is preference-based, confirm that the item remains complete and unaltered. The matrix should not decide responsibility from appearance alone; it should show which condition facts are documented and which classification still belongs to the seller or platform."]},
{heading:"Gate five: keep packaging, tags and accessories intact",paragraphs:["Packaging is evidence and sometimes part of the seller's resalable-condition test. Save photos of the retail box, sealed wrap, tags, manuals, dust bags, spare parts and accessories that arrived. Do not discard or request removal until the keep-or-return decision is closed. A product can be physically undamaged yet fail a seller's return standard because a seal, tag, branded box or included component is missing.","Create an included-parts row in the matrix: expected, visible, missing, and altered. Use the source listing and warehouse images rather than memory. If packaging arrived damaged, document that before further handling and ask whether the condition affects the request. Do not promise that original packaging guarantees acceptance; it only removes one avoidable source of failure. The seller still controls the applicable standard and final classification."]},
{heading:"Separate defect, mismatch and preference reasons",paragraphs:["Return responsibility can change with the reason. A wrong selected variant, missing component or visible defect is not the same as a buyer deciding they no longer want a correctly supplied item. State the observed fact first: selected black size L, received label M; listing showed two straps, warehouse evidence shows one; surface tear visible at the left seam. Avoid conclusions such as counterfeit or unusable unless the evidence and policy support that classification.","For each reason, attach the most direct evidence: order summary, saved listing, label photo, measurement, overview or close-up. Then record who has classified the issue and what remains disputed. The matrix should never convert the buyer's allegation into a confirmed seller fault. Its job is to make the request reviewable and to preserve the distinction that can affect return freight, handling and refund deductions."]},
{heading:"Build a submission-ready evidence packet",paragraphs:["A useful packet contains order number, source listing, selected option, QC Completed timestamp, return-button state, reason code, relevant photos, packaging and included-parts record, seller message, and requested outcome. Redact personal account or payment data from anything shared outside support. Name files by order and evidence type rather than leaving a folder of screenshots with no connection to the claim.","Write the request in one paragraph: identify the order and selected option, describe the observable discrepancy or preference, state that the request is being submitted within the displayed period, confirm the product and packaging condition, and ask for the available procedure and current charges. This is more effective than claiming a guaranteed result. It gives the agent the facts needed to contact the seller and tells the buyer which missing response must be tracked."]},
{heading:"Read costs only after the case is classified",paragraphs:["Joyagoo's public pages explain that return shipping or service charges can apply and that responsibility may differ when a product issue is accepted. Do not turn an approximate public figure into a guaranteed transaction total. The specific domestic return freight can depend on the seller, carrier, product and case. Save every displayed amount and the label attached to it before approving the return.","Reconcile the refund as separate lines: product amount actually paid, seller-approved refund, domestic return freight, service or handling label, other documented deduction, and amount credited to the account balance. If the calculation does not reconcile, ask which policy condition produced each deduction. This article interprets eligibility; it does not promise a free return or calculate a universal refund."]},
{heading:"Use the matrix for four common outcomes",paragraphs:["Outcome one: timely request, participating seller, eligible category, unused item and intact packaging—the ordinary procedure can be requested, subject to review. Outcome two: timely request but custom-made product—the category gate may block ordinary return and seller negotiation controls the result. Outcome three: timely defect report with clear evidence but damaged packaging—the defect and packaging questions must be assessed separately. Outcome four: complete item but deadline passed—the ordinary clock gate is closed even though condition is good.","These examples are not decisions for a real order. They demonstrate why a single yes-or-no column is inadequate. Mark every gate and attach its source. If two sources conflict, preserve both and request written clarification before altering the item. The matrix earns its value by showing exactly where eligibility is confirmed, conditional, disputed or unknown."]},
{heading:"Close the record without turning policy into a guarantee",paragraphs:["After the seller or platform responds, save the decision, reason, approved procedure, required deadline, destination for the domestic return, tracking evidence and refund calculation. Follow the current order instructions rather than an old screenshot from another buyer. Keep packaging and shipment proof until the account credit is reconciled. If the request is denied, record which gate was cited instead of reducing the outcome to ‘return policy failed.’","The durable rule is simple: act quickly, but evaluate more than time. A Joyagoo return eligibility matrix keeps the 120-hour clock beside seller participation, category, condition, packaging and evidence. It helps buyers avoid preventable disqualification and submit a precise case, while respecting the central policy boundary: a published process is not an unconditional promise that every product or reason will be accepted."]}]};

const make=(title:string,description:string,sourceNote:string,quickFacts:string[],rows:[string,string,string][]):SeoArticle=>({slug:returnMatrixArticle.slug,title,description,meta:"RETURN MATRIX · 15 MIN",sourceNote,quickFacts,sections:rows.map(([heading,a,b])=>({heading,paragraphs:[a,b]}))});
export const returnMatrixTranslations:Partial<Record<Lang,SeoArticle>>={
de:make("Joyagoo Rückgabe-Matrix: Verkäufer, Zustand und Verpackung","Trenne Frist, Verkäuferregel, Kategorie, Zustand, Verpackung und Belege, bevor du eine Rückgabe als berechtigt behandelst.","Richtlinie am 31. August 2026 geprüft. Maßgeblich bleiben Live-Bestellung, Verkäuferentscheidung und aktuelle Regel.",["Frist allein reicht nicht","Verkäuferregel ist eigenes Tor","Wiederverkaufszustand zählt","Verpackung kann entscheiden","Beleg muss zum Grund passen"],[
["Berechtigung ist eine Schnittmenge","Die veröffentlichte Frist beträgt für berechtigte Produkte fünf Tage beziehungsweise 120 Stunden ab QC Completed. Zusätzlich gelten Verkäufer, Drittplattform, Kategorie, Zustand und Verpackung.","Nutze sechs Spalten: Zeit, Verkäufer, Kategorie, Zustand, Verpackung und Beleg. Unbekannt bedeutet nicht Ja, sondern Pause und konkrete Frage vor einer irreversiblen Änderung."],
["Tor eins: die Uhr bestimmen","Speichere den exakten QC-Completed-Zeitstempel, Zeitzone sowie Button oder Countdown. Zahlungsdatum und spätes Öffnen der Fotos starten die Frist nicht neu.","Behandle jede Lagerbestellung separat und warte nicht auf Konsolidierung. Fehlt der Button, sichere den Bildschirm und frage, welches Tor nicht erfüllt ist."],
["Tor zwei: Verkäuferregel","Der Drittverkäufer und Marktplatz bestimmen die Unterstützung. Joyagoo vermittelt, kann aber kein fehlendes Verkäuferrecht erzeugen. Sichere den Rückgabehinweis des genauen Angebots.","Markiere bestätigt, abgelehnt oder unbekannt. Ein anderer Artikel desselben Shops ist kein Beleg; eine unbekannte Regel verlangt sofort eine Anfrage zur konkreten Bestellung."],
["Tor drei: Kategorie","Die öffentliche Richtlinie nennt unter anderem Maßanfertigung, hygieneempfindliche Ware, gebrauchte Produkte, Lebensmittel, bestimmte Publikationen und weitere Verkäuferregeln.","Prüfe den aktuellen Wortlaut. Bei Personalisierung, geöffnetem Siegel oder entfernter Kennzeichnung muss die Entscheidung vor der irreversiblen Handlung fallen."],
["Tor vier: verkaufsfähiger Zustand","Die Ware muss nach Verkäufermaßstab neu und weiterverkaufbar bleiben. Entferne keine Tags, nutze sie nicht und fordere keine Veränderung an, bevor die Entscheidung abgeschlossen ist.","Dokumentiere Erstzustand und Defekt genau. Die Matrix zeigt Belege, entscheidet aber nicht eigenständig, ob Verkäufer oder Plattform den Fehler anerkennen."],
["Tor fünf: Verpackung und Zubehör","Box, Siegel, Tags, Anleitung, Beutel, Ersatzteile und Zubehör können zum Wiederverkaufszustand gehören. Bewahre alles bis zur Entscheidung auf.","Liste erwartet, sichtbar, fehlend und verändert. Originalverpackung garantiert nichts, beseitigt aber eine vermeidbare Ursache für Ablehnung."],
["Gründe sauber trennen","Falsche Variante, fehlendes Teil oder sichtbarer Defekt unterscheiden sich von einer Meinungsänderung. Beschreibe zuerst die beobachtbare Abweichung.","Ordne Bestellübersicht, Listing, Label, Maß oder Detailfoto zu und halte fest, wer die Einstufung bestätigt hat. Eine Behauptung ist noch kein Verkäuferfehler."],
["Ein Belegpaket bauen","Sammle Nummer, Listing, Option, QC-Zeit, Button, Grund, relevante Fotos, Verpackung, Zubehör, Verkäuferantwort und gewünschtes Ergebnis. Persönliche Daten bleiben privat.","Die Anfrage nennt Fakten, fristgerechte Einreichung, Zustand und gewünschtes Verfahren. Sie verlangt keine garantierte Annahme, sondern eine prüfbare nächste Aktion."],
["Kosten erst nach Einstufung lesen","Rückfracht oder Servicekosten können gelten; Verantwortung kann bei anerkanntem Produktproblem anders ausfallen. Speichere den aktuellen Betrag und sein Label.","Rechne Warenbetrag, bestätigte Erstattung, Rückfracht, Service und Gutschrift getrennt ab. Ein ungeklärter Abzug braucht die zugehörige Regelbedingung."],
["Vier Ergebnisse verstehen","Fristgerecht und vollständig kann den Standardprozess öffnen; Maßanfertigung kann ihn blockieren; Defekt und beschädigte Verpackung brauchen getrennte Bewertung; gute Ware nach Frist bleibt verspätet.","Die Beispiele entscheiden keine echte Bestellung. Markiere jedes Tor und bewahre widersprüchliche Quellen bis zur schriftlichen Klärung auf."],
["Den Datensatz schließen","Speichere Entscheidung, Grund, Verfahren, Frist, Rücksendetracking und Erstattung. Folge der aktuellen Anweisung und behalte Verpackungsnachweise bis zur Gutschrift.","Schnelles Handeln genügt nicht allein. Die Matrix verbindet 120 Stunden mit Verkäufer, Kategorie, Zustand, Verpackung und Belegen, ohne Akzeptanz zu garantieren."]]),
es:make("Matriz de elegibilidad de devolución Joyagoo","Separa plazo, vendedor, categoría, estado, embalaje y pruebas antes de considerar elegible una devolución.","Política revisada el 31 de agosto de 2026. Mandan el pedido activo, la decisión del vendedor y la norma actual.",["El plazo no basta","El vendedor es otra condición","Importa el estado revendible","El embalaje puede bloquear","La prueba debe corresponder"],[
["La elegibilidad es una intersección","La página publica cinco días o 120 horas desde QC Completed para artículos elegibles, pero también exige vendedor, plataforma, categoría, estado y embalaje.","Usa columnas para tiempo, vendedor, categoría, estado, embalaje y prueba. Desconocido no significa sí: pausa y pregunta antes de cambiar el artículo."],
["Puerta uno: fijar el reloj","Guarda la hora exacta de QC Completed, zona horaria, botón y cuenta atrás. Pagar o abrir las fotos después no reinicia el plazo.","Cada pedido tiene su reloj; no esperes a consolidar. Si desaparece el botón, guarda la pantalla y pregunta qué condición falló."],
["Puerta dos: regla del vendedor","El vendedor y el mercado controlan la participación. Joyagoo comunica, pero no crea un derecho que la transacción fuente no ofrecía.","Marca confirmado, rechazado o desconocido. Otro artículo de la tienda no sirve; pregunta de inmediato por el pedido exacto."],
["Puerta tres: categoría","La política menciona personalizados, ciertos productos higiénicos, segunda mano, alimentos, publicaciones y otras reglas del vendedor.","Revisa el texto actual. Personalizar, abrir un sello o quitar una etiqueta exige decidir antes de la acción irreversible."],
["Puerta cuatro: estado revendible","El artículo debe seguir nuevo y revendible según el vendedor. No quites etiquetas ni pidas cambios antes de cerrar la decisión.","Documenta el estado inicial y la diferencia. La matriz conserva hechos; vendedor o plataforma clasifican la responsabilidad."],
["Puerta cinco: embalaje","Caja, sellos, etiquetas, manuales, bolsas y accesorios pueden formar parte del estado. Conserva todo hasta la decisión.","Registra esperado, visible, ausente y modificado. Tener el embalaje no garantiza aceptación, pero evita un fallo prevenible."],
["Separar motivos","Variante errónea, pieza ausente o defecto no equivalen a cambiar de opinión. Describe el hecho observable antes de sacar conclusiones.","Adjunta resumen, anuncio, etiqueta, medida o foto y registra quién confirmó la clasificación. Una alegación no es todavía culpa del vendedor."],
["Preparar pruebas","Incluye pedido, anuncio, opción, hora QC, botón, motivo, fotos, embalaje, piezas, respuesta y resultado solicitado, sin datos personales públicos.","La solicitud explica hechos, plazo y estado y pide procedimiento y cargos actuales; no exige un resultado garantizado."],
["Leer costes tras clasificar","Puede haber devolución nacional o servicio, y la responsabilidad puede cambiar con un problema aceptado. Guarda importe y etiqueta actual.","Separa pago, reembolso aprobado, transporte, servicio y saldo. Un descuento sin explicación necesita la condición aplicable."],
["Cuatro resultados","Una solicitud puntual y completa puede entrar al proceso; un personalizado puede quedar fuera; defecto y caja dañada se valoran separados; buen estado fuera de plazo sigue tarde.","Son ejemplos, no decisiones reales. Marca cada condición y conserva conflictos hasta obtener aclaración escrita."],
["Cerrar el registro","Guarda decisión, motivo, procedimiento, plazo, tracking nacional y cálculo del saldo. Sigue la instrucción activa y conserva pruebas.","Actuar rápido no basta: la matriz une 120 horas, vendedor, categoría, estado, embalaje y pruebas sin prometer aceptación."]]),
fr:make("Matrice d'éligibilité au retour Joyagoo","Séparez délai, vendeur, catégorie, état, emballage et preuves avant de conclure qu'un retour est admissible.","Politique vérifiée le 31 août 2026. La commande active, le vendeur et la règle actuelle restent déterminants.",["Le délai ne suffit pas","Le vendeur est un filtre","L'état revendable compte","L'emballage peut bloquer","La preuve doit correspondre"],[
["Une intersection de conditions","La page indique cinq jours ou 120 heures après QC Completed pour les produits admissibles, avec aussi vendeur, plateforme, catégorie, état et emballage.","Utilisez six colonnes. Inconnu n'est pas oui : mettez en pause et demandez avant toute modification irréversible."],
["Filtre un : fixer l'horloge","Conservez l'heure exacte de QC Completed, fuseau, bouton et compte à rebours. Paiement et lecture tardive des photos ne redémarrent pas le délai.","Chaque commande a son horloge. N'attendez pas la consolidation ; si le bouton manque, demandez quelle condition n'est pas remplie."],
["Filtre deux : vendeur","Le vendeur et la place de marché participent selon leurs règles. Joyagoo communique mais ne crée pas un droit absent de la transaction source.","Classez confirmé, refusé ou inconnu. Un autre produit de la boutique n'est pas une preuve ; interrogez la commande exacte."],
["Filtre trois : catégorie","La politique cite notamment personnalisation, certains produits d'hygiène, occasion, aliments, publications et règles vendeur supplémentaires.","Relisez la liste active. Personnaliser, ouvrir un sceau ou retirer une étiquette exige une décision préalable."],
["Filtre quatre : état revendable","Le produit doit rester neuf et revendable selon le vendeur. Ne retirez rien et ne demandez aucune modification avant la décision.","Documentez l'état initial et le défaut. La matrice montre les preuves ; vendeur ou plateforme qualifient la responsabilité."],
["Filtre cinq : emballage","Boîte, sceaux, étiquettes, notices, sacs et accessoires peuvent compter. Gardez-les jusqu'à la clôture.","Notez attendu, visible, absent et modifié. L'emballage ne garantit pas l'acceptation mais élimine un échec évitable."],
["Séparer les motifs","Mauvaise variante, pièce manquante ou défaut diffèrent d'un changement d'avis. Décrivez d'abord le fait observable.","Joignez commande, fiche, étiquette, mesure ou photo et indiquez qui a confirmé la qualification. Une allégation n'est pas encore une faute vendeur."],
["Préparer le dossier","Rassemblez commande, fiche, option, heure QC, bouton, motif, photos, emballage, pièces, réponse et résultat, sans données privées publiques.","La demande expose faits, délai et état puis sollicite procédure et frais actuels, sans exiger une acceptation garantie."],
["Lire les coûts après qualification","Retour intérieur ou service peuvent s'appliquer ; la responsabilité peut changer si un problème est reconnu. Sauvegardez montant et libellé.","Séparez paiement, remboursement accepté, transport, service et solde. Toute déduction inconnue doit être reliée à une condition."],
["Quatre résultats","Un dossier ponctuel et complet peut suivre la procédure ; le sur-mesure peut être exclu ; défaut et boîte abîmée se jugent séparément ; un bon état après délai reste tardif.","Ces exemples ne décident aucune commande. Marquez chaque filtre et gardez les conflits jusqu'à clarification écrite."],
["Clore le dossier","Conservez décision, motif, procédure, délai, suivi intérieur et calcul. Suivez l'instruction active et gardez les preuves jusqu'au crédit.","Agir vite ne suffit pas : la matrice relie 120 heures, vendeur, catégorie, état, emballage et preuves sans garantie d'acceptation."]]),
it:make("Matrice di idoneità al reso Joyagoo","Separa scadenza, venditore, categoria, condizione, imballaggio e prove prima di considerare idoneo un reso.","Politica verificata il 31 agosto 2026. Contano ordine attivo, decisione del venditore e regola corrente.",["La scadenza non basta","Il venditore è un filtro","Conta la rivendibilità","L'imballo può bloccare","La prova deve corrispondere"],[
["Idoneità come intersezione","La pagina indica cinque giorni o 120 ore da QC Completed per prodotti idonei, insieme a venditore, piattaforma, categoria, condizione e imballaggio.","Usa sei colonne. Sconosciuto non significa sì: pausa e domanda prima di modifiche irreversibili."],
["Filtro uno: fissare l'orologio","Salva ora esatta di QC Completed, fuso, pulsante e conto alla rovescia. Pagamento o apertura tardiva delle foto non riavviano il termine.","Ogni ordine ha un proprio orologio. Non aspettare il consolidamento; se manca il pulsante, chiedi quale condizione non è soddisfatta."],
["Filtro due: venditore","Venditore e marketplace partecipano secondo le loro regole. Joyagoo comunica, ma non crea un diritto assente nella transazione originale.","Classifica confermato, negato o sconosciuto. Un altro articolo del negozio non prova nulla; chiedi subito per l'ordine esatto."],
["Filtro tre: categoria","La politica cita personalizzati, alcuni prodotti igienici, usato, alimenti, pubblicazioni e ulteriori regole del venditore.","Ricontrolla il testo. Personalizzare, aprire un sigillo o togliere un'etichetta richiede una decisione preventiva."],
["Filtro quattro: condizione","L'articolo deve restare nuovo e rivendibile secondo il venditore. Non togliere tag né chiedere cambiamenti prima di decidere.","Documenta stato iniziale e difetto. La matrice conserva prove; venditore o piattaforma classificano la responsabilità."],
["Filtro cinque: imballaggio","Scatola, sigilli, tag, manuali, sacchetti e accessori possono contare. Conserva tutto fino alla chiusura.","Registra atteso, visibile, mancante e modificato. L'imballo non garantisce accettazione ma elimina un errore evitabile."],
["Separare i motivi","Variante errata, pezzo mancante o difetto non equivalgono a un ripensamento. Descrivi prima il fatto osservabile.","Allega ordine, pagina, etichetta, misura o foto e indica chi ha confermato la categoria. Un'affermazione non è ancora colpa del venditore."],
["Preparare il pacchetto","Raccogli ordine, pagina, opzione, ora QC, pulsante, motivo, foto, imballo, parti, risposta e risultato, senza dati privati pubblici.","La richiesta espone fatti, termine e stato e chiede procedura e costi correnti senza pretendere accettazione garantita."],
["Leggere i costi dopo la classificazione","Possono valere trasporto interno o servizio; la responsabilità può cambiare con un problema accettato. Salva importo e descrizione.","Separa pagamento, rimborso approvato, trasporto, servizio e saldo. Una detrazione ignota richiede la relativa condizione."],
["Quattro esiti","Un caso puntuale e completo può seguire la procedura; un personalizzato può essere escluso; difetto e scatola danneggiata vanno separati; buone condizioni fuori termine restano tardive.","Sono esempi, non decisioni reali. Marca ogni filtro e conserva conflitti fino a chiarimento scritto."],
["Chiudere il record","Salva decisione, motivo, procedura, termine, tracking interno e calcolo. Segui l'istruzione attiva e conserva prove fino all'accredito.","Agire presto non basta: la matrice unisce 120 ore, venditore, categoria, condizione, imballo e prove senza promettere accettazione."]])};
