import type {SeoArticle} from "./seo-articles";
import type {Lang} from "./site-data";

export const returnClockArticle:SeoArticle={
slug:"joyagoo-five-day-return-clock-qc-timestamp-deadline",
title:"Joyagoo 5-Day Return Clock: Evidence, Status Timestamp and Decision Deadline",
description:"Calculate the Joyagoo 5-day return clock from QC Completed, preserve the controlling timestamp and act before the evidence or request deadline becomes uncertain.",
meta:"RETURN CLOCK · 14 MIN",
sourceNote:"The current public return policy links the ordinary request period for eligible products to QC Completed. Eligibility still depends on seller, category, condition, packaging and the live order controls.",
quickFacts:["The trigger is QC Completed","Five days equals 120 hours","Each order keeps its own clock","Save the displayed time zone","A timely request is not automatic approval"],
sections:[
{heading:"Start with the controlling event, not a convenient date",paragraphs:["Joyagoo's current public return policy describes a five-day, 120-hour request period for eligible products after the warehouse order reaches QC Completed. That wording makes the status change the controlling event. The clock does not wait for a buyer to open the photos, for another item to reach the warehouse or for a planned parcel to be assembled. Payment date, seller dispatch date and warehouse arrival can explain the history, but they do not replace the stated trigger.","Open the exact order record and preserve the first defensible QC Completed timestamp. Record the displayed date, time and time zone or interface locale. If the page shows only a date, treat the uncertainty conservatively and ask support for the precise deadline. Never calculate from memory or from a screenshot belonging to another buyer. The goal is a transaction-specific record that another person could use to reproduce the deadline." ]},
{heading:"Translate five days into one explicit deadline",paragraphs:["Five days means 120 continuous hours, not five later visits to the account and not necessarily five local calendar midnights. Add 120 hours to the controlling timestamp while keeping the same time zone. Write the result in an unambiguous format such as 2026-09-07 14:30 UTC+8. Then create an internal action deadline earlier than the calculated boundary so that evidence collection, translation or support delay does not consume the remaining time.","If the interface presents a countdown or return button, save it beside your calculation. The live control may reveal a platform interpretation that your manual arithmetic missed. When the two disagree, do not choose the more generous answer silently. Capture both, stop irreversible handling and ask which deadline applies to that order. A deadline ledger should expose uncertainty rather than turn it into a confident but unsupported promise." ]},
{heading:"Give every warehouse order its own row",paragraphs:["Items bought together can be dispatched by different sellers and reach QC Completed at different moments. Consolidation plans do not merge those return clocks. Create one row per warehouse order with order number, source listing, selected option, QC Completed timestamp, calculated boundary, button state and current decision. Sorting by the earliest action deadline makes the genuinely urgent item visible instead of letting a later arrival reset the mental clock for the group.","Use one of four decision states: keep, return, ask or evidence pending. Keep closes the ordinary review after the decisive checks pass. Return means the evidence packet is ready to submit. Ask identifies a specific policy or transaction question. Evidence pending names the exact photo, measurement or seller fact still missing. A vague status such as reviewing is dangerous because it gives no owner, next action or time limit." ]},
{heading:"Separate the clock from eligibility",paragraphs:["A request made within 120 hours is not automatically approved. Joyagoo's published return language also points to seller and marketplace participation, product exclusions, resalable condition and packaging. Treat time as one gate in a larger policy matrix. The clock tells you when to act; it does not decide whether the seller must accept the reason, who pays domestic return freight or what amount will ultimately be credited.","Record eligibility as confirmed, conditional, denied or unknown, and attach the source for that label. Do not infer confirmation from the presence of a countdown alone. Equally, do not assume a missing button proves a specific exclusion. Preserve the screen and ask which condition applies. This separation keeps the article's narrow purpose intact: calculate and document the decision window without rewriting a full return-eligibility guide." ]},
{heading:"Triage evidence in the order that protects time",paragraphs:["Begin with identity: product type, selected color, size, model, quantity and included parts. Next review visible condition and the exact issue that could change the keep-or-return decision. Only then request a targeted photo or measurement. A broad request for more pictures can use valuable hours without resolving the decisive fact. Every evidence request should name the location, view, reference and decision it will support.","For a mismatch, save the order summary and the warehouse label in the same record. For a visible defect, include an overview plus a close view and identify the location without exaggerating severity. For a preference return, preserve evidence that the item, tags, seals, box and accessories remain complete. Do not remove packaging or ask for irreversible handling while the decision is open. Evidence gathering should protect eligibility rather than create a new condition dispute." ]},
{heading:"Do not let consolidation hide an expiring decision",paragraphs:["Warehouse storage and parcel planning operate on a different schedule from the return request. Waiting for a second seller, a coupon, a route comparison or a fuller parcel can be sensible for shipping, but none of those tasks pauses the published QC-based clock. Place the earliest return deadline above the parcel-planning checklist and review it before approving box removal, reinforcement or another packaging instruction.","A practical rule is to close the return decision before treating the item as available for consolidation. If the buyer needs support clarification, submit the question while the clock is still open and save the submission timestamp. Do not promise that merely opening a support conversation extends the deadline; follow the live order instructions and any written response. The record should show what was asked, when it was asked and what action remains due." ]},
{heading:"Handle a missing button or conflicting display",paragraphs:["If the expected return control is absent, capture the full order status, QC Completed timestamp, current date and relevant product state. Refresh once, check the correct order and language version, and avoid repeated actions that could alter evidence. Then send a concise question referencing the order number and the displayed trigger. A missing control can reflect time, seller rules, category, workflow state or another condition; the screen alone does not establish which explanation is correct.","If one page shows a date while another shows a countdown, preserve both and note the time zone. Use the earlier defensible boundary as the internal stop time until Joyagoo provides transaction-specific clarification. Do not publish a universal workaround or claim that support can reopen every case. The proper risk response is a documented conflict, an early request and no irreversible change while the answer is pending." ]},
{heading:"Write a submission that proves timing without demanding a result",paragraphs:["A useful request states the order number, selected option, QC Completed timestamp, calculated boundary, observed issue or preference, supporting evidence and requested procedure. Add the submission time and the channel used. Say that the request is being made within the displayed period if your evidence supports that statement. Do not call the return guaranteed or describe the seller as responsible before the case has been classified.","Keep the timing claim separate from the product claim. One sentence can establish when the window began; another can describe what the warehouse evidence shows. Attach only the photographs and records needed for that reason, and keep personal payment or address data out of any public copy. This structure makes it easier to determine whether a disagreement concerns timeliness, eligibility, condition, responsibility or cost." ]},
{heading:"Audit the outcome against the original clock",paragraphs:["After a response, record whether the request was accepted, denied, redirected for more evidence or left pending. Save the stated reason, the next deadline, domestic return instructions, tracking requirement and any displayed deductions. The original QC Completed timestamp remains part of the record even if the case later moves to seller negotiation. It explains when the ordinary request was made and prevents a later support message from replacing the event history.","Reconcile the final account credit separately from the timing audit. Product amount, approved refund, return freight, service label and other documented deductions are different fields. This guide does not estimate those amounts. Its job is to maintain an evidence chain from trigger to submission and resolution, so that a buyer can ask a precise question if the displayed result does not match the recorded process." ]},
{heading:"Close with a reusable clock record",paragraphs:["A complete row contains order identity, source listing, exact option, QC Completed timestamp, time zone, 120-hour boundary, earlier internal deadline, button or countdown state, evidence request, submission timestamp and outcome. Keep the record until the refund or keep decision is fully reconciled. If the policy page changes later, preserve the version and check date used for the transaction rather than silently editing the historical calculation.","The durable lesson is narrow but important: act from the controlling status, calculate explicitly and leave time for uncertainty. The Joyagoo 5-day return clock is a decision deadline for eligible products, not a universal acceptance guarantee. A buyer who separates trigger, eligibility, evidence and result can move quickly without overstating the published rule—and can show exactly what happened if a deadline or status is disputed." ]}
]};

const make=(title:string,description:string,sourceNote:string,facts:string[],rows:[string,string,string][]):SeoArticle=>({slug:returnClockArticle.slug,title,description,meta:"RETURN CLOCK · 14 MIN",sourceNote,quickFacts:facts,sections:rows.map(([heading,a,b])=>({heading,paragraphs:[a,b]}))});

export const returnClockTranslations:Partial<Record<Lang,SeoArticle>>={
de:make("Joyagoo 5-Tage-Rückgabefrist: Belege, Statuszeit und Entscheidungsende","Berechne die Joyagoo-Rückgabefrist ab QC Completed, sichere den maßgeblichen Zeitstempel und handle vor einer unklaren Grenze.","Die aktuelle Richtlinie bindet den normalen Antrag für berechtigte Produkte an QC Completed. Verkäufer, Kategorie, Zustand, Verpackung und Live-Bestellung bleiben weitere Bedingungen.",["Auslöser ist QC Completed","Fünf Tage sind 120 Stunden","Jede Bestellung hat ihre Uhr","Zeitzone sichern","Pünktlich heißt nicht automatisch akzeptiert"],[
["Mit dem maßgeblichen Ereignis starten","Die veröffentlichte Richtlinie nennt für berechtigte Produkte fünf Tage beziehungsweise 120 Stunden nach QC Completed. Zahlung, Versand, Lagereingang oder späteres Öffnen der Fotos ersetzen diesen Auslöser nicht.","Öffne die konkrete Bestellung und sichere Datum, Uhrzeit und angezeigte Zeitzone. Zeigt die Oberfläche nur ein Datum, rechne konservativ und frage nach der genauen Grenze statt aus Erinnerung zu schätzen."],
["Eine eindeutige Frist schreiben","Addiere 120 fortlaufende Stunden zum Zeitstempel in derselben Zeitzone und notiere ein eindeutiges Format. Lege eine frühere interne Handlungsfrist fest, damit Belege und Support nicht die Restzeit aufbrauchen.","Speichere Countdown oder Rückgabebutton neben der Rechnung. Bei Widerspruch sichere beide Anzeigen, stoppe irreversible Änderungen und frage, welche Frist für diese Bestellung gilt."],
["Pro Lagerbestellung eine Zeile","Gemeinsam gekaufte Artikel können zu verschiedenen Zeiten QC Completed erreichen; Konsolidierung führt die Uhren nicht zusammen. Erfasse Nummer, Listing, Option, Zeitstempel, Grenze, Button und Entscheidung pro Bestellung.","Nutze behalten, zurückgeben, fragen oder Beleg fehlt. Ein Status wie in Prüfung ist zu ungenau, weil Eigentümer, nächste Aktion und Zeitgrenze fehlen."],
["Uhr und Berechtigung trennen","Eine Einreichung innerhalb von 120 Stunden wird nicht automatisch akzeptiert. Verkäufer, Marktplatz, Kategorie, Wiederverkaufszustand und Verpackung bleiben eigene Tore; Zeit sagt nur, wann gehandelt werden muss.","Markiere Berechtigung als bestätigt, bedingt, abgelehnt oder unbekannt und nenne den Beleg. Countdown beweist keine Zusage, fehlender Button beweist keine bestimmte Ausschlussregel."],
["Belege zeitsparend priorisieren","Prüfe zuerst Identität, Farbe, Größe, Modell, Menge und Zubehör, danach Zustand und entscheidenden Mangel. Fordere nur das Foto oder Maß an, das die Behalten-oder-Rückgabe-Entscheidung ändert.","Sichere bei Abweichung Bestellübersicht und Label, bei Defekt Übersicht und Detail. Verpackung, Tags, Siegel und Zubehör bleiben unverändert, solange die Entscheidung offen ist."],
["Konsolidierung darf die Frist nicht verdecken","Lager- und Paketplanung folgen einem anderen Zeitplan. Warten auf Verkäufer, Coupon, Route oder volle Sendung pausiert die QC-basierte Frist nicht. Stelle die früheste Grenze über die Verpackungsplanung.","Schließe die Rückgabeentscheidung vor der Konsolidierung. Frage früh und speichere die Einreichungszeit; eine Supportanfrage verlängert die Frist nicht automatisch."],
["Fehlenden Button oder Konflikt behandeln","Fehlt die Kontrolle, sichere Status, QC-Zeit, aktuelles Datum und Produktzustand. Prüfe Bestellung und Sprache und frage dann mit Bestellnummer nach. Der Bildschirm erklärt die Ursache nicht allein.","Bei Datum und Countdown bewahre beide samt Zeitzone auf und nutze intern die frühere vertretbare Grenze. Versprich keine universelle Wiederöffnung durch den Support."],
["Zeit belegen, Ergebnis nicht fordern","Nenne Nummer, Option, QC-Zeit, berechnete Grenze, beobachteten Grund, Belege, gewünschten Ablauf und Einreichungszeit. Behaupte weder Garantie noch Verkäuferverantwortung vor der Einstufung.","Trenne den Satz zur Frist vom Satz zum Produkt. So wird sichtbar, ob ein Streit Zeit, Berechtigung, Zustand, Verantwortung oder Kosten betrifft."],
["Ausgang gegen die Uhr prüfen","Speichere Annahme, Ablehnung, Zusatzbeleg oder offenen Fall sowie Grund, nächste Frist, Rücksendeanweisung und Abzüge. Der ursprüngliche QC-Zeitstempel bleibt Teil der Historie.","Gutschrift und Zeitaudit sind getrennt. Warenbetrag, Erstattung, Rückfracht und Service sind eigene Felder; dieser Leitfaden berechnet keine Beträge."],
["Einen wiederverwendbaren Datensatz schließen","Eine vollständige Zeile enthält Identität, Listing, Option, QC-Zeit, Zeitzone, 120-Stunden-Grenze, interne Frist, Button, Beleg, Einreichung und Ausgang. Bewahre sie bis zum Abschluss auf.","Handle vom maßgeblichen Status, rechne ausdrücklich und plane Unsicherheit ein. Die Frist ist ein Entscheidungsfenster für berechtigte Produkte, keine universelle Annahmegarantie."]]),
es:make("Reloj de devolución Joyagoo de 5 días: hora QC y fecha límite","Calcula las 120 horas desde QC Completed, conserva la hora que controla el plazo y actúa antes de que la prueba o el límite sean inciertos.","La política vigente vincula la solicitud ordinaria de productos elegibles con QC Completed. Vendedor, categoría, estado, embalaje y controles activos siguen siendo condiciones.",["El inicio es QC Completed","Cinco días son 120 horas","Cada pedido tiene su reloj","Guarda la zona horaria","A tiempo no significa aprobado"],[
["Empezar por el evento que manda","La política publicada indica cinco días o 120 horas después de QC Completed para productos elegibles. Pago, envío, llegada o apertura posterior de fotos no sustituyen ese evento.","Abre el pedido exacto y guarda fecha, hora y zona mostradas. Si solo aparece una fecha, calcula de forma conservadora y pregunta el límite preciso."],
["Escribir una fecha inequívoca","Suma 120 horas continuas en la misma zona y usa un formato sin ambigüedad. Crea además un límite interno anterior para que pruebas y soporte no agoten el margen.","Guarda cuenta atrás o botón junto al cálculo. Si discrepan, conserva ambos, evita cambios irreversibles y pregunta qué límite controla el pedido."],
["Una fila por pedido de almacén","Artículos comprados juntos pueden completar QC en momentos distintos; consolidar no une los relojes. Registra pedido, ficha, opción, hora, límite, botón y decisión.","Usa conservar, devolver, preguntar o prueba pendiente. Revisando es peligroso porque no define responsable, acción ni plazo."],
["Separar reloj y elegibilidad","Solicitar dentro de 120 horas no garantiza aprobación. Vendedor, mercado, categoría, estado revendible y embalaje siguen siendo condiciones independientes; el tiempo solo dice cuándo actuar.","Marca confirmado, condicionado, denegado o desconocido con su fuente. Una cuenta atrás no confirma aceptación y un botón ausente no explica la exclusión."],
["Priorizar la prueba útil","Comprueba identidad, color, talla, modelo, cantidad y accesorios antes del estado y del defecto decisivo. Pide solo la foto o medida que pueda cambiar la decisión.","Une resumen y etiqueta para una discrepancia, y vista general y detalle para un defecto. Mantén caja, sellos y etiquetas intactos mientras el caso siga abierto."],
["No ocultar el plazo con la consolidación","Almacén y paquete tienen otro calendario. Esperar otro vendedor, cupón, ruta o bulto no pausa el reloj basado en QC. Coloca el primer límite encima del plan de embalaje.","Cierra la decisión antes de consolidar. Pregunta temprano y guarda la hora; iniciar soporte no prolonga automáticamente el plazo."],
["Resolver botón ausente o conflicto","Si falta el control, conserva estado, hora QC, fecha actual y condición del producto. Verifica pedido e idioma y pregunta con el número exacto; la pantalla no prueba por sí sola la causa.","Si fecha y cuenta atrás difieren, conserva ambas con zona y usa internamente el límite anterior. No prometas que soporte reabrirá todos los casos."],
["Probar el tiempo sin exigir resultado","Incluye pedido, opción, hora QC, límite, motivo observable, pruebas, procedimiento solicitado y hora de envío. No declares garantía ni culpa antes de la clasificación.","Separa la frase temporal de la afirmación sobre el producto. Así se distingue un conflicto de plazo, elegibilidad, estado, responsabilidad o coste."],
["Auditar el resultado","Registra aceptación, rechazo, petición de pruebas o espera, con motivo, siguiente fecha, instrucciones y deducciones. La hora QC original permanece en la historia.","Crédito y auditoría temporal son campos distintos. Importe, devolución, transporte y servicio se concilian aparte; aquí no se estiman cantidades."],
["Cerrar un registro reutilizable","Guarda identidad, ficha, opción, hora y zona QC, límite de 120 horas, límite interno, control, pruebas, envío y resultado hasta cerrar el caso.","Actúa desde el estado controlador, calcula de forma explícita y reserva margen. El plazo es una ventana de decisión para artículos elegibles, no garantía universal."]]),
fr:make("Délai de retour Joyagoo de 5 jours : horodatage QC et échéance","Calculez les 120 heures depuis QC Completed, conservez l'horodatage déterminant et agissez avant que la preuve ou l'échéance ne devienne incertaine.","La politique actuelle relie la demande ordinaire des produits éligibles à QC Completed. Vendeur, catégorie, état, emballage et commandes actives restent des conditions.",["Le déclencheur est QC Completed","Cinq jours font 120 heures","Chaque commande a son horloge","Conserver le fuseau horaire","À temps ne signifie pas accepté"],[
["Partir de l'événement déterminant","La règle publiée indique cinq jours ou 120 heures après QC Completed pour les produits éligibles. Paiement, expédition, arrivée ou ouverture tardive des photos ne remplacent pas ce déclencheur.","Ouvrez la commande exacte et gardez date, heure et fuseau affichés. Si seule la date apparaît, calculez prudemment et demandez l'échéance exacte."],
["Écrire une échéance sans ambiguïté","Ajoutez 120 heures continues dans le même fuseau et utilisez un format explicite. Fixez une limite interne plus tôt afin que preuves et support ne consomment pas toute la marge.","Conservez compte à rebours ou bouton avec le calcul. En cas de conflit, gardez les deux, évitez les changements irréversibles et demandez quelle limite s'applique."],
["Une ligne par commande d'entrepôt","Des articles achetés ensemble peuvent finir le QC à des moments différents ; la consolidation ne fusionne pas leurs horloges. Notez commande, fiche, option, heure, limite, bouton et décision.","Utilisez garder, retourner, demander ou preuve en attente. En cours d'examen est trop vague sans responsable, action et heure limite."],
["Séparer horloge et éligibilité","Une demande dans les 120 heures n'est pas automatiquement acceptée. Vendeur, marché, catégorie, état revendable et emballage restent des portes distinctes ; l'horloge dit seulement quand agir.","Marquez confirmé, conditionnel, refusé ou inconnu avec sa source. Un compte à rebours ne garantit rien et l'absence de bouton n'explique pas l'exclusion."],
["Prioriser la preuve décisive","Vérifiez identité, couleur, taille, modèle, quantité et accessoires, puis l'état et le défaut qui changeraient la décision. Demandez uniquement la photo ou mesure utile.","Associez récapitulatif et étiquette pour une erreur, vue générale et détail pour un défaut. Gardez boîte, scellés et étiquettes intacts tant que la décision reste ouverte."],
["Ne pas masquer l'échéance par la consolidation","Stockage et colis suivent un autre calendrier. Attendre vendeur, coupon, ligne ou colis complet ne suspend pas l'horloge QC. Placez la première échéance au-dessus du plan d'emballage.","Fermez la décision avant consolidation. Questionnez tôt et conservez l'heure d'envoi ; ouvrir un ticket ne prolonge pas automatiquement le délai."],
["Gérer bouton absent ou affichage contradictoire","Si le contrôle manque, gardez statut, heure QC, date actuelle et état du produit. Vérifiez commande et langue puis posez une question avec le numéro exact ; l'écran seul n'indique pas la cause.","Si date et compte à rebours diffèrent, gardez les deux avec leur fuseau et utilisez la limite la plus proche. Ne promettez pas une réouverture universelle."],
["Prouver le moment sans exiger l'issue","Indiquez commande, option, heure QC, limite calculée, fait observé, preuves, procédure souhaitée et heure d'envoi. N'affirmez ni garantie ni faute avant classement.","Séparez la phrase sur le temps de celle sur le produit. On voit alors si le désaccord concerne délai, éligibilité, état, responsabilité ou coût."],
["Auditer l'issue","Notez acceptation, refus, preuve supplémentaire ou attente, puis raison, prochaine date, instructions et déductions. L'horodatage QC initial demeure dans l'historique.","Crédit et audit du temps sont distincts. Montant produit, remboursement, retour et service se rapprochent ailleurs ; ce guide ne les estime pas."],
["Fermer un dossier réutilisable","Gardez identité, fiche, option, heure et fuseau QC, limite de 120 heures, limite interne, contrôle, preuves, envoi et résultat jusqu'à clôture.","Agissez depuis le statut déterminant, calculez explicitement et prévoyez l'incertitude. Le délai est une fenêtre pour produit éligible, pas une garantie universelle."]]),
it:make("Finestra di reso Joyagoo di 5 giorni: orario QC e scadenza","Calcola le 120 ore da QC Completed, conserva l'orario determinante e agisci prima che prova o scadenza diventino incerte.","La politica attuale collega la richiesta ordinaria per prodotti idonei a QC Completed. Venditore, categoria, condizioni, imballo e controlli attivi restano requisiti.",["L'inizio è QC Completed","Cinque giorni sono 120 ore","Ogni ordine ha il suo orologio","Salva il fuso orario","In tempo non significa approvato"],[
["Partire dall'evento che controlla","La regola pubblicata indica cinque giorni o 120 ore dopo QC Completed per prodotti idonei. Pagamento, spedizione, arrivo o apertura tardiva delle foto non sostituiscono l'evento.","Apri l'ordine esatto e salva data, ora e fuso mostrati. Se compare solo una data, calcola in modo prudente e chiedi il limite preciso."],
["Scrivere una scadenza esplicita","Aggiungi 120 ore continue nello stesso fuso e usa un formato non ambiguo. Fissa una scadenza interna anticipata, così prove e assistenza non consumano il margine.","Salva conto alla rovescia o pulsante accanto al calcolo. Se divergono, conserva entrambi, evita modifiche irreversibili e chiedi quale limite vale."],
["Una riga per ordine di magazzino","Articoli acquistati insieme possono completare QC in momenti diversi; il consolidamento non unisce gli orologi. Registra ordine, inserzione, opzione, ora, limite, pulsante e decisione.","Usa tenere, restituire, chiedere o prova mancante. In esame è troppo vago senza responsabile, azione e orario."],
["Separare orologio e idoneità","Inviare entro 120 ore non garantisce approvazione. Venditore, mercato, categoria, condizione rivendibile e imballo restano porte distinte; il tempo dice solo quando agire.","Segna confermato, condizionato, negato o ignoto con la fonte. Un countdown non promette accettazione e un pulsante assente non spiega l'esclusione."],
["Dare priorità alla prova decisiva","Controlla identità, colore, taglia, modello, quantità e accessori, poi condizioni e difetto decisivo. Chiedi soltanto la foto o misura capace di cambiare la decisione.","Per un errore unisci riepilogo ed etichetta; per un difetto vista generale e dettaglio. Mantieni scatola, sigilli e tag mentre il caso è aperto."],
["Non nascondere la scadenza con il consolidamento","Magazzino e pacco seguono un altro calendario. Attendere venditore, coupon, linea o pacco pieno non sospende l'orologio QC. Metti il primo limite sopra il piano d'imballo.","Chiudi la decisione prima del consolidamento. Chiedi presto e salva l'ora; aprire assistenza non estende automaticamente il termine."],
["Gestire pulsante assente o conflitto","Se manca il controllo, salva stato, ora QC, data corrente e condizioni. Verifica ordine e lingua e chiedi con il numero esatto; lo schermo da solo non prova la causa.","Se data e countdown divergono, conserva entrambi col fuso e usa internamente il limite precedente. Non promettere riaperture universali."],
["Provare il tempo senza pretendere l'esito","Indica ordine, opzione, ora QC, limite, fatto osservato, prove, procedura richiesta e ora d'invio. Non dichiarare garanzia o responsabilità prima della classificazione.","Separa la frase temporale da quella sul prodotto. Così si distingue un conflitto di tempo, idoneità, condizione, responsabilità o costo."],
["Controllare l'esito","Registra accettazione, rifiuto, altra prova o attesa, con motivo, prossima scadenza, istruzioni e detrazioni. L'orario QC originale resta nella cronologia.","Credito e audit temporale sono separati. Importo, rimborso, reso e servizio si riconciliano a parte; questa guida non stima cifre."],
["Chiudere un record riutilizzabile","Conserva identità, pagina, opzione, ora e fuso QC, limite 120 ore, scadenza interna, controllo, prove, invio ed esito fino alla chiusura.","Agisci dallo stato determinante, calcola esplicitamente e lascia margine. La finestra riguarda prodotti idonei, non garantisce accettazione universale."]])
};
