export const languages = ["en", "de", "es", "fr", "it"] as const;
export type Lang = (typeof languages)[number];
export type TrustPageKey = "about" | "editorial-policy" | "fact-checking" | "contact" | "privacy" | "terms" | "independence";
export type PageKey = "home" | "spreadsheet" | "finds" | "guide" | "qc" | "shipping" | "faq" | "articles" | TrustPageKey | "joyagoo-warehouse-storage-policy-item-clocks-expiry-evidence" | "joyagoo-five-day-return-clock-qc-timestamp-deadline" | "joyagoo-return-eligibility-matrix-seller-condition-packaging" | "joyagoo-fee-policy-free-agent-service-transaction-costs" | "joyagoo-buying-fees-guide" | "joyagoo-qc-return-window-guide" | "joyagoo-warehouse-rehearsal-shipping-guide" | "volumetric-weight-guide" | "joyagoo-reviews-buyer-signals";
export const pageKeys: PageKey[] = ["home", "spreadsheet", "finds", "guide", "qc", "shipping", "faq", "articles", "about", "editorial-policy", "fact-checking", "contact", "privacy", "terms", "independence", "joyagoo-warehouse-storage-policy-item-clocks-expiry-evidence", "joyagoo-five-day-return-clock-qc-timestamp-deadline", "joyagoo-return-eligibility-matrix-seller-condition-packaging", "joyagoo-fee-policy-free-agent-service-transaction-costs", "joyagoo-buying-fees-guide", "joyagoo-qc-return-window-guide", "joyagoo-warehouse-rehearsal-shipping-guide", "volumetric-weight-guide", "joyagoo-reviews-buyer-signals"];
export const languageNames: Record<Lang, string> = { en: "English", de: "Deutsch", es: "Español", fr: "Français", it: "Italiano" };
export const uiText: Record<Lang, {home:string;primaryNav:string;mobileNav:string;listingSample:string;indexLabel:string;homeTitle:string}> = {
  en: {home:"Joyagoo home",primaryNav:"Primary navigation",mobileNav:"Mobile navigation",listingSample:"risk example",indexLabel:"POLICY INDEX",homeTitle:"Joyagoo Reviews, Fees & Buyer Policy Guide"},
  de: {home:"Joyagoo Startseite",primaryNav:"Hauptnavigation",mobileNav:"Mobile Navigation",listingSample:"Risikobeispiel",indexLabel:"REGELINDEX",homeTitle:"Joyagoo Bewertungen, Gebühren & Käuferrichtlinien"},
  es: {home:"Inicio de Joyagoo",primaryNav:"Navegación principal",mobileNav:"Navegación móvil",listingSample:"ejemplo de riesgo",indexLabel:"ÍNDICE DE POLÍTICAS",homeTitle:"Opiniones, tarifas y políticas de Joyagoo"},
  fr: {home:"Accueil Joyagoo",primaryNav:"Navigation principale",mobileNav:"Navigation mobile",listingSample:"exemple de risque",indexLabel:"INDEX DES RÈGLES",homeTitle:"Avis, frais et politiques acheteurs Joyagoo"},
  it: {home:"Home Joyagoo",primaryNav:"Navigazione principale",mobileNav:"Navigazione mobile",listingSample:"esempio di rischio",indexLabel:"INDICE REGOLE",homeTitle:"Recensioni, costi e regole Joyagoo"},
};
export const nav: Record<Lang, Record<string, string>> = {
  en: { spreadsheet: "Spreadsheet", finds: "Finds", guide: "Guide", qc: "QC", shipping: "Shipping", faq: "FAQ", articles: "Articles" },
  de: { spreadsheet: "Tabelle", finds: "Fundstücke", guide: "Anleitung", qc: "Qualitätscheck", shipping: "Versand", faq: "FAQ", articles: "Artikel" },
  es: { spreadsheet: "Hoja", finds: "Hallazgos", guide: "Guía", qc: "Control", shipping: "Envío", faq: "FAQ", articles: "Artículos" },
  fr: { spreadsheet: "Tableur", finds: "Sélections", guide: "Guide", qc: "Contrôle", shipping: "Livraison", faq: "FAQ", articles: "Articles" },
  it: { spreadsheet: "Foglio", finds: "Selezioni", guide: "Guida", qc: "Controllo", shipping: "Spedizione", faq: "FAQ", articles: "Articoli" },
};
export const copy = {
  en: { eyebrow:"Independent policy & risk desk",hero:["Read the rule.","Record the evidence.","Decide with limits."],lede:"An independent Joyagoo policy and buyer-risk guide covering fees, QC evidence, return eligibility, warehouse clocks, billable weight, shipping rules and public review signals.",search:"Check a product while applying the policy",placeholder:"Try: shoes, jacket, jersey...",searchButton:"Check products",productRoutes:"Risk examples by category",productHeading:"Apply the rule to the product in front of you.",verified:"Policy baseline",verifiedHeading:"Published rules first; buyer reports second.",verifiedText:"Joyagoo policies, seller eligibility, route rules and live charges can change. Re-check the current platform before every irreversible decision.",next:"Recommended policy reading",disclaimer:"Joyagoos is an independent buyer guide and is not affiliated with or operated by Joyagoo. Verify current policies, eligibility, routes and final charges before acting."},
  de: { eyebrow:"Unabhängige Regel- und Risikostelle",hero:["Regel lesen.","Beleg sichern.","Grenzen kennen."],lede:"Unabhängiger Joyagoo-Leitfaden zu Gebühren, QC-Belegen, Rückgabeberechtigung, Lagerfristen, Abrechnungsgewicht, Versandregeln und öffentlichen Bewertungssignalen.",search:"Produkt anhand der Regeln prüfen",placeholder:"Zum Beispiel: Schuhe, Jacke, Trikot...",searchButton:"Produkte prüfen",productRoutes:"Risikobeispiele nach Kategorie",productHeading:"Wende die Regel auf das konkrete Produkt an.",verified:"Regelbasis",verifiedHeading:"Zuerst veröffentlichte Regeln, dann Käuferberichte.",verifiedText:"Joyagoo-Regeln, Verkäuferberechtigung, Routen und Live-Kosten können sich ändern. Prüfe die Plattform vor jeder endgültigen Entscheidung.",next:"Empfohlene Richtlinien",disclaimer:"Joyagoos ist ein unabhängiger Käuferleitfaden und weder mit Joyagoo verbunden noch von Joyagoo betrieben. Prüfe aktuelle Regeln und Endkosten."},
  es: { eyebrow:"Mesa independiente de políticas y riesgo",hero:["Lee la regla.","Guarda la prueba.","Decide con límites."],lede:"Guía independiente sobre tarifas Joyagoo, pruebas QC, devoluciones, plazos de almacén, peso facturable, reglas de envío y señales de opiniones públicas.",search:"Revisar un producto aplicando la política",placeholder:"Prueba: zapatillas, chaqueta, camiseta...",searchButton:"Revisar productos",productRoutes:"Ejemplos de riesgo por categoría",productHeading:"Aplica la regla al producto concreto.",verified:"Base de políticas",verifiedHeading:"Primero las reglas publicadas; después los informes de compradores.",verifiedText:"Las políticas, la elegibilidad del vendedor, las rutas y los cargos activos pueden cambiar. Revisa la plataforma antes de cada decisión irreversible.",next:"Lecturas de política recomendadas",disclaimer:"Joyagoos es una guía independiente y no está afiliada ni operada por Joyagoo. Verifica políticas, elegibilidad, rutas y cargos actuales."},
  fr: { eyebrow:"Bureau indépendant des règles et risques",hero:["Lisez la règle.","Gardez la preuve.","Décidez avec limites."],lede:"Guide indépendant sur les frais Joyagoo, preuves QC, retours, délais d’entrepôt, poids facturable, règles d’expédition et signaux d’avis publics.",search:"Vérifier un produit avec la règle",placeholder:"Exemple : chaussures, veste, maillot...",searchButton:"Vérifier",productRoutes:"Exemples de risque par catégorie",productHeading:"Appliquez la règle au produit réel.",verified:"Base réglementaire",verifiedHeading:"Règles publiées d’abord, rapports clients ensuite.",verifiedText:"Les politiques, l’éligibilité vendeur, les lignes et frais actifs peuvent changer. Vérifiez la plateforme avant toute décision irréversible.",next:"Lectures recommandées",disclaimer:"Joyagoos est un guide indépendant, non affilié à Joyagoo et non exploité par Joyagoo. Vérifiez règles, éligibilité, lignes et frais actuels."},
  it: { eyebrow:"Osservatorio indipendente su regole e rischi",hero:["Leggi la regola.","Salva la prova.","Decidi con limiti."],lede:"Guida indipendente su costi Joyagoo, prove QC, resi, scadenze di magazzino, peso fatturabile, regole di spedizione e segnali delle recensioni pubbliche.",search:"Controlla un prodotto applicando la regola",placeholder:"Prova: scarpe, giacca, maglia...",searchButton:"Controlla",productRoutes:"Esempi di rischio per categoria",productHeading:"Applica la regola al prodotto reale.",verified:"Base delle regole",verifiedHeading:"Prima le regole pubblicate, poi i resoconti degli acquirenti.",verifiedText:"Politiche, idoneità del venditore, rotte e costi attivi possono cambiare. Controlla la piattaforma prima di ogni scelta irreversibile.",next:"Letture consigliate",disclaimer:"Joyagoos è una guida indipendente, non affiliata né gestita da Joyagoo. Verifica regole, idoneità, rotte e costi correnti."},
} satisfies Record<Lang, Record<string,string|string[]>>;
export const categories = [["Shoes","https://cnfanssp.com/shoes/","01"],["Sweatshirts","https://cnfanssp.com/hoodies-sweaters/","02"],["T-Shirts","https://cnfanssp.com/t-shirts/","03"],["Jackets","https://cnfanssp.com/jackets/","04"],["Pants / Shorts","https://cnfanssp.com/pants-shorts/","05"],["Accessories","https://cnfanssp.com/accessories/","06"]] as const;
export const products = [
  {name:"Accessories-60",type:"Accessories",href:"https://cnfanssp.com/AllProducts/6427.html",image:"/products/accessories.webp"},
  {name:"Shoes-60",type:"Shoes",href:"https://cnfanssp.com/AllProducts/6050.html",image:"/products/shoes.webp"},
  {name:"Jackets-60",type:"Jackets",href:"https://cnfanssp.com/AllProducts/6247.html",image:"/products/jacket.webp"},
  {name:"T-Shirts-60",type:"T-Shirts",href:"https://cnfanssp.com/AllProducts/6187.html",image:"/products/tshirt.webp"},
] as const;
export const facts = [["90 days","Free warehouse storage listed in published shopping guidance"],["5 days","Published QC return or exchange window, subject to seller and item conditions"],["20 CNY / 3 USD","Official help pages currently show two rehearsal-packing price formats"]] as const;
export const pageIntro: Record<Lang,Record<"spreadsheet"|"finds"|"guide"|"qc"|"shipping"|"faq"|"articles",[string,string,string]>> = {
  en:{spreadsheet:["01 / POLICY MATRIX","Joyagoo Fees, Returns & Warehouse Policy Index","Use this structured reference to separate product payment, seller eligibility, QC clocks, storage rules and shipping obligations."],finds:["02 / RISK EXAMPLES","Joyagoo Product Risk Examples by Category","These unchanged product samples now illustrate which policy and QC questions change by category; they are not rankings or recommendations."],guide:["03 / POLICY WORKFLOW","Joyagoo Buyer Policy Verification Guide","A decision flow for saving evidence, checking current rules, reading QC status and recording the reason for each action."],qc:["04 / QC & RETURNS","Joyagoo QC Evidence and 5-Day Return Guide","Interpret visible evidence, identify missing proof and check eligibility before the published 120-hour request window closes."],shipping:["05 / WAREHOUSE & SHIPPING","Joyagoo Shipping Cost, Weight and Warehouse Rules","Separate free-storage clocks, rehearsal information, route-specific billable weight, insurance limits and live freight charges."],faq:["06 / POLICY FAQ","Joyagoo Fees, Returns and Shipping FAQ","Direct answers about fees, seller responsibility, QC timing, storage, billable weight, insurance and tracking."],articles:["07 / POLICY RESEARCH","Joyagoo Reviews, Fees and Policy Research","Long-form analysis that distinguishes official rules, public buyer reports and independent editorial judgment."]},
  de:{spreadsheet:["01 / REGELMATRIX","Joyagoo Gebühren-, Rückgabe- und Lagerindex","Trenne Produktzahlung, Verkäuferberechtigung, QC-Fristen, Lagerregeln und Versandpflichten."],finds:["02 / RISIKOBEISPIELE","Joyagoo Produktrisiken nach Kategorie","Die unveränderten Beispiele zeigen kategoriespezifische Regel- und QC-Fragen; sie sind keine Rangliste oder Empfehlung."],guide:["03 / REGELABLAUF","Joyagoo Leitfaden zur Regelprüfung","Sichere Belege, prüfe aktuelle Regeln, lies QC-Status und dokumentiere jede Entscheidung."],qc:["04 / QC & RÜCKGABE","Joyagoo QC-Belege und 5-Tage-Rückgabe","Bewerte sichtbare Belege, fehlende Nachweise und Berechtigung vor Ende der 120 Stunden."],shipping:["05 / LAGER & VERSAND","Joyagoo Versandkosten, Gewicht und Lagerregeln","Trenne Lagerfristen, Probeverpackung, Routengewicht, Versicherung und Live-Fracht."],faq:["06 / REGEL-FAQ","Joyagoo Gebühren-, Rückgabe- und Versand-FAQ","Direkte Antworten zu Gebühren, Verkäuferpflicht, QC, Lagerung, Gewicht, Versicherung und Tracking."],articles:["07 / REGELRECHERCHE","Joyagoo Bewertungen, Gebühren und Richtlinien","Analysen trennen offizielle Regeln, öffentliche Käuferberichte und unabhängige Bewertung."]},
  es:{spreadsheet:["01 / MATRIZ DE POLÍTICAS","Índice Joyagoo de tarifas, devoluciones y almacén","Separa pago del producto, elegibilidad del vendedor, plazos QC, almacenamiento y obligaciones de envío."],finds:["02 / EJEMPLOS DE RIESGO","Riesgos de producto Joyagoo por categoría","Las muestras conservadas ilustran preguntas de política y QC; no son rankings ni recomendaciones."],guide:["03 / FLUJO DE POLÍTICAS","Guía para verificar políticas de Joyagoo","Guarda pruebas, comprueba reglas vigentes, interpreta estados QC y documenta cada decisión."],qc:["04 / QC Y DEVOLUCIONES","Pruebas QC Joyagoo y devolución en 5 días","Interpreta pruebas visibles, identifica lo que falta y confirma elegibilidad antes de las 120 horas."],shipping:["05 / ALMACÉN Y ENVÍO","Coste, peso y reglas de almacén Joyagoo","Distingue plazos, ensayo de embalaje, peso facturable, seguro y flete activo."],faq:["06 / FAQ DE POLÍTICAS","FAQ Joyagoo sobre tarifas, devoluciones y envío","Respuestas sobre tarifas, vendedor, QC, almacenamiento, peso, seguro y seguimiento."],articles:["07 / INVESTIGACIÓN","Opiniones, tarifas y políticas de Joyagoo","Análisis que separan reglas oficiales, informes públicos y criterio editorial independiente."]},
  fr:{spreadsheet:["01 / MATRICE DES RÈGLES","Index Joyagoo des frais, retours et entrepôt","Séparez paiement, éligibilité vendeur, délais QC, stockage et obligations d’expédition."],finds:["02 / EXEMPLES DE RISQUE","Risques produits Joyagoo par catégorie","Les exemples conservés illustrent les questions de règle et de QC; ce ne sont ni classements ni recommandations."],guide:["03 / PARCOURS DES RÈGLES","Guide de vérification des politiques Joyagoo","Conservez les preuves, vérifiez les règles, lisez le statut QC et documentez chaque décision."],qc:["04 / QC & RETOURS","Preuves QC Joyagoo et retour sous 5 jours","Interprétez les preuves, repérez les manques et vérifiez l’éligibilité avant la fin des 120 heures."],shipping:["05 / ENTREPÔT & LIVRAISON","Coût, poids et règles d’entrepôt Joyagoo","Distinguez délais, pré-emballage, poids facturable, assurance et fret actif."],faq:["06 / FAQ DES RÈGLES","FAQ Joyagoo sur frais, retours et livraison","Réponses sur frais, vendeur, QC, stockage, poids, assurance et suivi."],articles:["07 / RECHERCHE","Avis, frais et politiques Joyagoo","Analyses séparant règles officielles, rapports publics et jugement éditorial indépendant."]},
  it:{spreadsheet:["01 / MATRICE REGOLE","Indice Joyagoo di costi, resi e magazzino","Separa pagamento, idoneità del venditore, scadenze QC, deposito e obblighi di spedizione."],finds:["02 / ESEMPI DI RISCHIO","Rischi prodotto Joyagoo per categoria","Gli esempi conservati illustrano domande su regole e QC; non sono classifiche o raccomandazioni."],guide:["03 / PERCORSO REGOLE","Guida alla verifica delle politiche Joyagoo","Salva le prove, controlla le regole, leggi lo stato QC e documenta ogni decisione."],qc:["04 / QC E RESI","Prove QC Joyagoo e reso in 5 giorni","Interpreta le prove, individua ciò che manca e verifica l’idoneità prima delle 120 ore."],shipping:["05 / MAGAZZINO E SPEDIZIONE","Costi, peso e regole di magazzino Joyagoo","Distingui scadenze, prova imballo, peso fatturabile, assicurazione e costo attivo."],faq:["06 / FAQ REGOLE","FAQ Joyagoo su costi, resi e spedizione","Risposte su costi, venditore, QC, deposito, peso, assicurazione e tracking."],articles:["07 / RICERCA","Recensioni, costi e politiche Joyagoo","Analisi che separano regole ufficiali, resoconti pubblici e giudizio editoriale indipendente."]},
};
