import { extendArticles } from "./research.js";
import { applyParityArticles } from "./parity.js";
import { applyArticleParityBoost } from "./language-parity.js";
import { localizedRequirementsBriefArticles } from "./seo60-articles.js";
import { localizedUseCaseArticles } from "./seo60-use-case.js";

export const copy = {
  en: {
    menu: "Menu", searchStatus: "Search opens the matching source catalog in a new tab.", placeholder: "hoodie, sneakers, product link…", quick: "Browse:",
    issue: "THE FINDQC EDIT", issueNo: "ISSUE 01 · 2026", editorNote: "EDITOR'S NOTE", editorBody: "Start with the exact listing. Compare what is visible. Decide with evidence.",
    proofs: [["06", "source-matched finds"], ["05", "interface languages"], ["01:01", "image-to-link match"]], process: ["DISCOVER", "COMPARE", "CHECK QC", "OPEN EXACT LISTING"],
    findsIntro: "Every preview card uses the image from its exact destination page. Prices are approximate USD conversions and must be rechecked live.",
    priceNote: "Approx. USD conversion · verify live", productNames: ["Retro low-top sneakers", "Mohair knit sweater", "Minimal pullover hoodie", "Classic steel watch", "Collectible art figure", "Match-day jersey"], productCategories: ["Shoes", "Sweaters", "Hoodies", "Accessories", "Home & objects", "Jerseys"],
    methodKicker: "02 / METHOD", methodTitle: "Three checks before the click", methodLink: "Open the complete QC guide", method: [["Match identity", "Confirm item type, selected color, size label and included components before judging minor details."], ["Read the evidence", "Use multiple angles, measurements and repeated records. One attractive image is not a reliable sample."], ["Verify live", "Open the exact source page and recheck price, stock, route rules and destination restrictions before acting."]],
    fieldKicker: "03 / FIELD NOTE", fieldTitle: "How to read QC photos without guessing", fieldText: "A practical inspection sequence covering identity, angles, shape, alignment, color, measurements, defects, weight and the final ship-or-return decision.", readGuide: "Read the full guide", fieldCaption: "Look twice. Decide once.",
    findsPage: { eyebrow: "Exact-source product directory", title: "Product finds", intro: "Browse a compact research set or search the wider catalog. Every image and outbound action is matched to one exact destination page.", all: "All", empty: "No matching preview items. Use the search box to search the full source catalog." },
    qc: { eyebrow: "Inspection workflow", title: "QC field guide", intro: "Use the same order every time. It separates important evidence from visual noise and makes the final decision easier to explain.", cta: "Read the complete guide", card: "QC DECISION CARD", complete: "checks completed before shipping", checklist: "CHECKLIST", checklistTitle: "From item identity to final action", checks: [["Identity", "Item, variant, color and size"], ["Coverage", "Enough clear angles"], ["Shape", "Symmetry and proportions"], ["Construction", "Seams, hardware and edges"], ["Measurements", "Fit-critical dimensions"], ["Decision", "Ship, recheck, exchange or return"]], noteTitle: "Evidence, not a guarantee", note: "QC photos can reduce uncertainty but cannot prove authenticity, durability, import legality or final delivery condition. Verify current listing and destination rules." },
    shipping: { eyebrow: "Parcel planning", title: "Shipping notes", intro: "Estimate with both actual and volumetric weight, then verify the selected route after consolidation. The final parcel—not the product card—determines the billable shipment.", cards: [["Actual weight", "The measured parcel weight after packing. Added protection, cartons and consolidation materials can change it."], ["Volumetric weight", "A size-based calculation used by many routes. Large light boxes can cost more than compact heavier items."], ["Route restrictions", "Line availability depends on destination, item type, dimensions and current carrier rules."], ["Customs and tax", "Import rules differ by destination and can change. A previous parcel does not guarantee the same treatment."]], formula: "WORKING FORMULA", formulaTitle: "Billable weight = the larger eligible figure", actual: "Actual parcel weight", vs: "vs.", volume: "Route-calculated volumetric weight", formulaNote: "Use this as a planning principle only. Apply the divisor and rounding rules shown by the live shipping route." },
    articlesPage: { eyebrow: "Practical search and QC knowledge", title: "SEO articles & research guides", intro: "Independent, people-first articles with clear buttons to complete pages. Each guide focuses on a different search intent instead of repeating the same topic.", read: "Read complete article", updated: "Updated 27 August 2026" },
    article: { back: "All SEO articles", reviewed: "Reviewed 27 August 2026", independent: "Independent research", inGuide: "IN THIS GUIDE", summary: "The practical summary", browse: "Browse product finds", ready: "Ready to inspect a listing?", readyText: "Open an exact source page, then apply the checks from this guide to the visible evidence." },
    faqTitle: "Frequently asked questions", faqEyebrow: "Clear limits, useful answers", faqIntro: "What the research interface does, what the data means and what still needs to be verified live.", faqs: [["Does FindQC sell products?", "No. FindQC is an independent research interface. Product actions open an external source listing."], ["Are the displayed prices final?", "No. Preview prices are approximate USD conversions. Exchange rates, options, availability and fees can change."], ["Does a QC photo guarantee quality?", "No. It is visual evidence for one record and cannot prove hidden construction or future batch consistency."], ["Why does every card open a specific page?", "A product image should match its destination. Each card therefore uses the image from the exact page it opens."], ["Can I search with a product link?", "Yes. Paste a keyword, item ID or source link into the search box."], ["Is shipping information guaranteed?", "No. Routes, billable weight, fees, customs and delivery times depend on current conditions and destination rules."]],
    legal: { updated: "Last updated 27 August 2026", privacy: "Privacy", terms: "Terms and research disclaimer", privacyIntro: "This preview does not require an account and does not collect payment information.", termsIntro: "Use FindQC as a research aid, then verify every decision against the current source and destination rules.", privacySections: [["Preview data", "The search field sends the entered term to the external source catalog only when you submit it. This preview does not operate an account system, checkout or payment flow."], ["External destinations", "Outbound pages follow the destination site's own privacy practices. Review those terms before entering personal information."]], termsSections: [["Independent resource", "FindQC does not sell products, process orders, inspect goods or guarantee seller performance, product quality, stock, price, shipping, customs or delivery."], ["Research responsibility", "Images and historical records are references. Users must verify the live listing, route restrictions and applicable law before acting."]] },
    footer: "Independent product research. Listings, availability and prices can change; verify the live source before acting.", privacy: "Privacy", terms: "Terms"
  },
  de: {
    menu: "Menü", searchStatus: "Die Suche öffnet den passenden Quellkatalog in einem neuen Tab.", placeholder: "Hoodie, Sneaker, Produktlink…", quick: "Entdecken:", issue: "DIE FINDQC AUSWAHL", issueNo: "AUSGABE 01 · 2026", editorNote: "REDAKTIONSNOTIZ", editorBody: "Beginne mit dem exakten Angebot. Vergleiche sichtbare Details. Entscheide anhand von Belegen.",
    proofs: [["06", "passende Quellenfunde"], ["05", "Oberflächensprachen"], ["01:01", "Bild-Link-Zuordnung"]], process: ["ENTDECKEN", "VERGLEICHEN", "QC PRÜFEN", "EXAKTES ANGEBOT ÖFFNEN"],
    findsIntro: "Jede Vorschau verwendet das Bild ihrer exakten Zielseite. USD-Preise sind Näherungswerte und müssen live geprüft werden.", priceNote: "USD-Näherungswert · live prüfen", productNames: ["Retro-Low-Top-Sneaker", "Mohair-Strickpullover", "Minimalistischer Hoodie", "Klassische Stahluhr", "Sammelfigur", "Matchday-Trikot"], productCategories: ["Schuhe", "Pullover", "Hoodies", "Accessoires", "Wohnen & Objekte", "Trikots"],
    methodKicker: "02 / METHODE", methodTitle: "Drei Prüfungen vor dem Klick", methodLink: "Vollständigen QC-Leitfaden öffnen", method: [["Identität abgleichen", "Artikeltyp, Farbe, Größenetikett und enthaltene Teile zuerst bestätigen."], ["Belege lesen", "Mehrere Winkel, Maße und wiederkehrende Datensätze verwenden. Ein schönes Bild reicht nicht."], ["Live verifizieren", "Exakte Quellseite öffnen und Preis, Bestand, Versandregeln sowie Zielbeschränkungen erneut prüfen."]],
    fieldKicker: "03 / PRAXISNOTIZ", fieldTitle: "QC-Fotos lesen, ohne zu raten", fieldText: "Eine praktische Reihenfolge für Identität, Winkel, Form, Ausrichtung, Farbe, Maße, Mängel, Gewicht und die Versandentscheidung.", readGuide: "Vollständigen Leitfaden lesen", fieldCaption: "Zweimal ansehen. Einmal entscheiden.",
    findsPage: { eyebrow: "Produktverzeichnis mit exakter Quelle", title: "Produktfunde", intro: "Kompakte Auswahl durchsuchen oder den gesamten Katalog öffnen. Jedes Bild und jede Aktion führt zur passenden Zielseite.", all: "Alle", empty: "Keine passenden Vorschauartikel. Nutze die Suche für den vollständigen Quellkatalog." },
    qc: { eyebrow: "Prüfablauf", title: "QC-Leitfaden", intro: "Nutze immer dieselbe Reihenfolge. So trennst du wichtige Belege von visuellem Rauschen und kannst die Entscheidung erklären.", cta: "Vollständigen Leitfaden lesen", card: "QC-ENTSCHEIDUNGSKARTE", complete: "Prüfungen vor dem Versand", checklist: "CHECKLISTE", checklistTitle: "Von der Artikelidentität zur Entscheidung", checks: [["Identität", "Artikel, Variante, Farbe und Größe"], ["Abdeckung", "Genügend klare Perspektiven"], ["Form", "Symmetrie und Proportionen"], ["Verarbeitung", "Nähte, Beschläge und Kanten"], ["Maße", "Passformkritische Abmessungen"], ["Entscheidung", "Versenden, nachprüfen, tauschen oder zurückgeben"]], noteTitle: "Beleg, keine Garantie", note: "QC-Fotos reduzieren Unsicherheit, beweisen aber weder Echtheit noch Haltbarkeit, Einfuhrfähigkeit oder Lieferzustand. Angebot und Zielregeln live prüfen." },
    shipping: { eyebrow: "Paketplanung", title: "Versandhinweise", intro: "Tatsächliches und Volumengewicht schätzen und die Route nach der Konsolidierung erneut prüfen. Das fertige Paket bestimmt das abrechenbare Gewicht.", cards: [["Tatsächliches Gewicht", "Gemessenes Paketgewicht nach dem Verpacken. Schutz und Außenkarton können es verändern."], ["Volumengewicht", "Größenbasierte Berechnung vieler Routen. Große leichte Kartons können teurer sein."], ["Routenbeschränkungen", "Verfügbarkeit hängt von Ziel, Artikeltyp, Abmessungen und aktuellen Carrier-Regeln ab."], ["Zoll und Steuer", "Einfuhrregeln unterscheiden sich nach Ziel und können sich ändern."]], formula: "ARBEITSFORMEL", formulaTitle: "Abrechnungsgewicht = der größere zulässige Wert", actual: "Tatsächliches Paketgewicht", vs: "gegen", volume: "Berechnetes Volumengewicht", formulaNote: "Nur als Planungsprinzip nutzen. Divisor und Rundungsregeln der aktuellen Route anwenden." },
    articlesPage: { eyebrow: "Praxiswissen zu Suche und QC", title: "SEO-Artikel & Rechercheleitfäden", intro: "Eigenständige, nutzerorientierte Artikel mit klaren Schaltflächen zu vollständigen Seiten. Jeder Leitfaden deckt eine andere Suchabsicht ab.", read: "Vollständigen Artikel lesen", updated: "Aktualisiert am 27. August 2026" },
    article: { back: "Alle SEO-Artikel", reviewed: "Geprüft am 27. August 2026", independent: "Unabhängige Recherche", inGuide: "IN DIESEM LEITFADEN", summary: "Praxiszusammenfassung", browse: "Produktfunde ansehen", ready: "Bereit, ein Angebot zu prüfen?", readyText: "Öffne die exakte Quellseite und wende die Prüfungen dieses Leitfadens auf die sichtbaren Belege an." },
    faqTitle: "Häufig gestellte Fragen", faqEyebrow: "Klare Grenzen, nützliche Antworten", faqIntro: "Was die Oberfläche leistet, was die Daten bedeuten und was live geprüft werden muss.", faqs: [["Verkauft FindQC Produkte?", "Nein. FindQC ist eine unabhängige Rechercheoberfläche; Produktaktionen öffnen externe Quellangebote."], ["Sind die Preise endgültig?", "Nein. Es sind ungefähre USD-Umrechnungen; Wechselkurs, Optionen, Bestand und Gebühren können sich ändern."], ["Garantiert ein QC-Foto Qualität?", "Nein. Es ist ein visueller Beleg für einen Datensatz und beweist keine verborgene Verarbeitung."], ["Warum öffnet jede Karte eine bestimmte Seite?", "Bild und Ziel müssen zusammenpassen. Jede Karte nutzt daher das Bild der exakten Zielseite."], ["Kann ich mit einem Produktlink suchen?", "Ja. Füge Stichwort, Artikel-ID oder Quelllink in die Suche ein."], ["Sind Versandangaben garantiert?", "Nein. Route, Gewicht, Gebühren, Zoll und Laufzeit hängen von aktuellen Bedingungen ab."]],
    legal: { updated: "Aktualisiert am 27. August 2026", privacy: "Datenschutz", terms: "Bedingungen und Recherchehinweis", privacyIntro: "Diese Vorschau benötigt kein Konto und sammelt keine Zahlungsdaten.", termsIntro: "FindQC ist eine Recherchehilfe. Jede Entscheidung muss mit aktuellen Quellen und Zielregeln abgeglichen werden.", privacySections: [["Vorschaudaten", "Die Suche sendet den Begriff erst beim Absenden an den externen Quellkatalog. Diese Vorschau hat kein Konto-, Checkout- oder Zahlungssystem."], ["Externe Ziele", "Ausgehende Seiten folgen eigenen Datenschutzregeln. Prüfe sie vor der Eingabe persönlicher Daten."]], termsSections: [["Unabhängige Ressource", "FindQC verkauft keine Produkte, bearbeitet keine Bestellungen und garantiert weder Qualität, Bestand, Preis, Versand, Zoll noch Lieferung."], ["Verantwortung", "Bilder und historische Datensätze sind Referenzen. Live-Angebot, Routenregeln und geltendes Recht müssen geprüft werden."]] }, footer: "Unabhängige Produktrecherche. Angebote, Bestand und Preise können sich ändern; Quelle live prüfen.", privacy: "Datenschutz", terms: "Bedingungen"
  },
  es: {
    menu: "Menú", searchStatus: "La búsqueda abre el catálogo de origen en una pestaña nueva.", placeholder: "sudadera, zapatillas, enlace…", quick: "Explorar:", issue: "LA EDICIÓN FINDQC", issueNo: "EDICIÓN 01 · 2026", editorNote: "NOTA DEL EDITOR", editorBody: "Empieza por la ficha exacta. Compara lo visible. Decide con pruebas.", proofs: [["06", "hallazgos con fuente"], ["05", "idiomas de interfaz"], ["01:01", "coincidencia imagen-enlace"]], process: ["DESCUBRIR", "COMPARAR", "REVISAR QC", "ABRIR FICHA EXACTA"],
    findsIntro: "Cada tarjeta utiliza la imagen de su página de destino exacta. Los precios en USD son aproximados y deben revisarse en vivo.", priceNote: "Conversión USD aproximada · verificar", productNames: ["Zapatillas retro bajas", "Jersey de mohair", "Sudadera minimalista", "Reloj clásico de acero", "Figura de colección", "Camiseta de partido"], productCategories: ["Calzado", "Jerséis", "Sudaderas", "Accesorios", "Hogar y objetos", "Camisetas"],
    methodKicker: "02 / MÉTODO", methodTitle: "Tres revisiones antes del clic", methodLink: "Abrir la guía QC completa", method: [["Confirmar identidad", "Comprueba tipo, color, talla y componentes antes de juzgar detalles pequeños."], ["Leer las pruebas", "Usa varios ángulos, medidas y registros. Una sola foto atractiva no es una muestra fiable."], ["Verificar en vivo", "Abre la fuente exacta y revisa precio, stock, ruta y restricciones del destino."]], fieldKicker: "03 / NOTA PRÁCTICA", fieldTitle: "Cómo leer fotos QC sin adivinar", fieldText: "Una secuencia práctica para identidad, ángulos, forma, alineación, color, medidas, defectos, peso y decisión final.", readGuide: "Leer la guía completa", fieldCaption: "Mira dos veces. Decide una.",
    findsPage: { eyebrow: "Directorio con fuente exacta", title: "Productos", intro: "Explora una selección compacta o busca en el catálogo completo. Cada imagen y acción coincide con una página de destino exacta.", all: "Todos", empty: "No hay artículos coincidentes. Usa la búsqueda para el catálogo completo." },
    qc: { eyebrow: "Flujo de inspección", title: "Guía de QC", intro: "Sigue siempre el mismo orden. Así separas pruebas importantes del ruido visual y explicas mejor la decisión.", cta: "Leer la guía completa", card: "TARJETA DE DECISIÓN QC", complete: "comprobaciones antes del envío", checklist: "LISTA", checklistTitle: "De la identidad a la decisión final", checks: [["Identidad", "Artículo, variante, color y talla"], ["Cobertura", "Ángulos claros suficientes"], ["Forma", "Simetría y proporciones"], ["Construcción", "Costuras, herrajes y bordes"], ["Medidas", "Dimensiones críticas de ajuste"], ["Decisión", "Enviar, revisar, cambiar o devolver"]], noteTitle: "Prueba, no garantía", note: "Las fotos QC reducen incertidumbre, pero no prueban autenticidad, durabilidad, legalidad de importación ni estado final. Verifica la ficha y las reglas del destino." },
    shipping: { eyebrow: "Planificación del paquete", title: "Notas de envío", intro: "Calcula peso real y volumétrico y verifica la ruta tras consolidar. El paquete final determina el peso facturable.", cards: [["Peso real", "Peso medido tras embalar. Protección, caja y materiales pueden cambiarlo."], ["Peso volumétrico", "Cálculo por tamaño usado por muchas rutas. Una caja grande y ligera puede costar más."], ["Restricciones de ruta", "La disponibilidad depende del destino, tipo de artículo, medidas y reglas actuales."], ["Aduanas e impuestos", "Las normas de importación varían por destino y pueden cambiar."]], formula: "FÓRMULA DE TRABAJO", formulaTitle: "Peso facturable = la cifra admisible mayor", actual: "Peso real del paquete", vs: "frente a", volume: "Peso volumétrico calculado", formulaNote: "Úsalo solo para planificar. Aplica el divisor y redondeo de la ruta activa." },
    articlesPage: { eyebrow: "Conocimiento práctico de búsqueda y QC", title: "Artículos SEO y guías", intro: "Artículos independientes orientados a personas, con botones claros hacia páginas completas. Cada guía cubre una intención de búsqueda distinta.", read: "Leer artículo completo", updated: "Actualizado el 27 de agosto de 2026" }, article: { back: "Todos los artículos SEO", reviewed: "Revisado el 27 de agosto de 2026", independent: "Investigación independiente", inGuide: "EN ESTA GUÍA", summary: "Resumen práctico", browse: "Ver productos", ready: "¿Listo para revisar una ficha?", readyText: "Abre la página de origen exacta y aplica las comprobaciones de esta guía a las pruebas visibles." },
    faqTitle: "Preguntas frecuentes", faqEyebrow: "Límites claros, respuestas útiles", faqIntro: "Qué hace la interfaz, qué significan los datos y qué debe comprobarse en vivo.", faqs: [["¿FindQC vende productos?", "No. Es una interfaz independiente; las acciones abren fichas externas."], ["¿Los precios son finales?", "No. Son conversiones aproximadas a USD; cambio, opciones, stock y tarifas pueden variar."], ["¿Una foto QC garantiza calidad?", "No. Es una prueba visual de un registro y no demuestra construcción oculta."], ["¿Por qué cada tarjeta abre una página concreta?", "Imagen y destino deben coincidir; cada tarjeta usa la imagen de su destino exacto."], ["¿Puedo buscar con un enlace?", "Sí. Pega palabra clave, ID o enlace de origen."], ["¿La información de envío está garantizada?", "No. Ruta, peso, tarifas, aduanas y plazos dependen de condiciones actuales."]],
    legal: { updated: "Actualizado el 27 de agosto de 2026", privacy: "Privacidad", terms: "Términos y aviso de investigación", privacyIntro: "Esta vista previa no requiere cuenta ni recoge datos de pago.", termsIntro: "Usa FindQC como ayuda y verifica cada decisión con la fuente y reglas actuales.", privacySections: [["Datos de la vista previa", "La búsqueda envía el término al catálogo externo solo al pulsar enviar. No hay cuentas, pago ni checkout."], ["Destinos externos", "Las páginas externas aplican sus propias políticas. Revísalas antes de introducir datos personales."]], termsSections: [["Recurso independiente", "FindQC no vende, procesa pedidos ni garantiza calidad, stock, precio, envío, aduanas o entrega."], ["Responsabilidad", "Imágenes y registros históricos son referencias. Verifica ficha, ruta y legislación antes de actuar."]] }, footer: "Investigación independiente. Fichas, disponibilidad y precios pueden cambiar; verifica la fuente.", privacy: "Privacidad", terms: "Términos"
  },
  fr: {
    menu: "Menu", searchStatus: "La recherche ouvre le catalogue source dans un nouvel onglet.", placeholder: "sweat, baskets, lien produit…", quick: "Explorer :", issue: "LA SÉLECTION FINDQC", issueNo: "NUMÉRO 01 · 2026", editorNote: "NOTE DE LA RÉDACTION", editorBody: "Commencez par la fiche exacte. Comparez le visible. Décidez avec des preuves.", proofs: [["06", "sélections avec source"], ["05", "langues d’interface"], ["01:01", "correspondance image-lien"]], process: ["DÉCOUVRIR", "COMPARER", "VÉRIFIER LE QC", "OUVRIR LA FICHE EXACTE"],
    findsIntro: "Chaque carte reprend l’image de sa page de destination exacte. Les prix USD sont approximatifs et doivent être vérifiés en direct.", priceNote: "Conversion USD approximative · à vérifier", productNames: ["Baskets rétro basses", "Pull en mohair", "Sweat minimaliste", "Montre classique en acier", "Figurine de collection", "Maillot de match"], productCategories: ["Chaussures", "Pulls", "Sweats", "Accessoires", "Maison et objets", "Maillots"], methodKicker: "02 / MÉTHODE", methodTitle: "Trois contrôles avant le clic", methodLink: "Ouvrir le guide QC complet", method: [["Vérifier l’identité", "Confirmez type, couleur, taille et éléments inclus avant les petits détails."], ["Lire les preuves", "Utilisez plusieurs angles, mesures et relevés. Une belle photo ne suffit pas."], ["Vérifier en direct", "Ouvrez la source exacte et contrôlez prix, stock, itinéraire et restrictions."]], fieldKicker: "03 / NOTE PRATIQUE", fieldTitle: "Lire les photos QC sans deviner", fieldText: "Une méthode pour l’identité, les angles, la forme, l’alignement, la couleur, les mesures, les défauts, le poids et la décision.", readGuide: "Lire le guide complet", fieldCaption: "Regardez deux fois. Décidez une fois.",
    findsPage: { eyebrow: "Répertoire à source exacte", title: "Trouvailles", intro: "Parcourez une sélection ou recherchez le catalogue complet. Chaque image et chaque action correspondent à une destination exacte.", all: "Tout", empty: "Aucun article correspondant. Utilisez la recherche pour le catalogue complet." },
    qc: { eyebrow: "Méthode d’inspection", title: "Guide QC", intro: "Suivez toujours le même ordre pour séparer les preuves utiles du bruit visuel et expliquer la décision.", cta: "Lire le guide complet", card: "CARTE DE DÉCISION QC", complete: "contrôles avant expédition", checklist: "LISTE DE CONTRÔLE", checklistTitle: "De l’identité à la décision finale", checks: [["Identité", "Article, variante, couleur et taille"], ["Couverture", "Assez d’angles nets"], ["Forme", "Symétrie et proportions"], ["Fabrication", "Coutures, pièces et bords"], ["Mesures", "Dimensions essentielles"], ["Décision", "Expédier, vérifier, échanger ou retourner"]], noteTitle: "Une preuve, pas une garantie", note: "Les photos QC réduisent l’incertitude sans prouver authenticité, durabilité, légalité d’importation ou état final. Vérifiez la fiche et les règles de destination." },
    shipping: { eyebrow: "Préparation du colis", title: "Notes d’expédition", intro: "Estimez le poids réel et volumétrique, puis vérifiez la ligne après consolidation. Le colis final détermine le poids facturable.", cards: [["Poids réel", "Poids mesuré après emballage. Protection et carton peuvent le modifier."], ["Poids volumétrique", "Calcul basé sur la taille. Un grand carton léger peut coûter davantage."], ["Restrictions de ligne", "La disponibilité dépend de la destination, du type, des dimensions et des règles actuelles."], ["Douane et taxes", "Les règles d’importation varient selon la destination et peuvent changer."]], formula: "FORMULE DE TRAVAIL", formulaTitle: "Poids facturable = la valeur admissible la plus élevée", actual: "Poids réel du colis", vs: "contre", volume: "Poids volumétrique calculé", formulaNote: "Principe de planification uniquement. Appliquez le diviseur et les arrondis de la ligne active." },
    articlesPage: { eyebrow: "Connaissances pratiques de recherche et QC", title: "Articles SEO et guides", intro: "Des articles indépendants, centrés sur l’utilisateur, avec des boutons clairs vers les pages complètes. Chaque guide cible une intention distincte.", read: "Lire l’article complet", updated: "Mis à jour le 27 août 2026" }, article: { back: "Tous les articles SEO", reviewed: "Relu le 27 août 2026", independent: "Recherche indépendante", inGuide: "DANS CE GUIDE", summary: "Résumé pratique", browse: "Voir les trouvailles", ready: "Prêt à examiner une fiche ?", readyText: "Ouvrez la page source exacte et appliquez les contrôles du guide aux preuves visibles." },
    faqTitle: "Questions fréquentes", faqEyebrow: "Des limites claires, des réponses utiles", faqIntro: "Ce que fait l’interface, ce que signifient les données et ce qui reste à vérifier.", faqs: [["FindQC vend-il des produits ?", "Non. C’est une interface indépendante ; les actions ouvrent des fiches externes."], ["Les prix sont-ils définitifs ?", "Non. Ce sont des conversions USD approximatives ; taux, options, stock et frais changent."], ["Une photo QC garantit-elle la qualité ?", "Non. C’est une preuve visuelle d’un relevé, pas de la fabrication cachée."], ["Pourquoi chaque carte ouvre-t-elle une page précise ?", "L’image doit correspondre à la destination ; chaque carte reprend l’image de sa fiche exacte."], ["Puis-je chercher avec un lien ?", "Oui. Collez un mot-clé, un identifiant ou un lien source."], ["Les informations d’expédition sont-elles garanties ?", "Non. Ligne, poids, frais, douane et délais dépendent des conditions actuelles."]],
    legal: { updated: "Mis à jour le 27 août 2026", privacy: "Confidentialité", terms: "Conditions et avertissement", privacyIntro: "Cet aperçu ne demande pas de compte et ne collecte aucune donnée de paiement.", termsIntro: "Utilisez FindQC comme aide et vérifiez chaque décision avec les sources et règles actuelles.", privacySections: [["Données de l’aperçu", "Le terme n’est envoyé au catalogue externe qu’au moment de la recherche. Aucun compte, paiement ou panier n’est exploité."], ["Destinations externes", "Les pages externes appliquent leurs propres politiques. Consultez-les avant toute donnée personnelle."]], termsSections: [["Ressource indépendante", "FindQC ne vend pas, ne traite pas les commandes et ne garantit ni qualité, stock, prix, expédition, douane ou livraison."], ["Responsabilité", "Images et historiques sont des références. Vérifiez la fiche, les règles de ligne et la loi applicable."]] }, footer: "Recherche indépendante. Fiches, disponibilité et prix peuvent changer ; vérifiez la source.", privacy: "Confidentialité", terms: "Conditions"
  },
  it: {
    menu: "Menu", searchStatus: "La ricerca apre il catalogo sorgente in una nuova scheda.", placeholder: "felpa, sneakers, link prodotto…", quick: "Esplora:", issue: "LA SELEZIONE FINDQC", issueNo: "NUMERO 01 · 2026", editorNote: "NOTA EDITORIALE", editorBody: "Parti dalla scheda esatta. Confronta ciò che è visibile. Decidi con prove.", proofs: [["06", "prodotti con fonte"], ["05", "lingue dell’interfaccia"], ["01:01", "corrispondenza immagine-link"]], process: ["SCOPRI", "CONFRONTA", "CONTROLLA QC", "APRI LA SCHEDA ESATTA"],
    findsIntro: "Ogni anteprima usa l’immagine della propria pagina di destinazione. I prezzi USD sono approssimativi e vanno verificati dal vivo.", priceNote: "Conversione USD approssimativa · verifica", productNames: ["Sneakers rétro basse", "Maglione in mohair", "Felpa minimal", "Orologio classico in acciaio", "Figura da collezione", "Maglia da partita"], productCategories: ["Scarpe", "Maglioni", "Felpe", "Accessori", "Casa e oggetti", "Maglie"], methodKicker: "02 / METODO", methodTitle: "Tre controlli prima del clic", methodLink: "Apri la guida QC completa", method: [["Conferma l’identità", "Verifica tipo, colore, taglia e componenti prima dei piccoli dettagli."], ["Leggi le prove", "Usa più angoli, misure e registri. Una sola bella foto non basta."], ["Verifica dal vivo", "Apri la fonte esatta e ricontrolla prezzo, disponibilità, rotta e restrizioni."]], fieldKicker: "03 / NOTA PRATICA", fieldTitle: "Come leggere le foto QC senza indovinare", fieldText: "Una sequenza pratica per identità, angoli, forma, allineamento, colore, misure, difetti, peso e decisione finale.", readGuide: "Leggi la guida completa", fieldCaption: "Guarda due volte. Decidi una.",
    findsPage: { eyebrow: "Catalogo con fonte esatta", title: "Prodotti", intro: "Sfoglia una selezione compatta o cerca nel catalogo completo. Ogni immagine e azione corrisponde alla pagina di destinazione esatta.", all: "Tutti", empty: "Nessun prodotto corrispondente. Usa la ricerca per il catalogo completo." },
    qc: { eyebrow: "Flusso di controllo", title: "Guida QC", intro: "Usa sempre lo stesso ordine per separare le prove importanti dal rumore visivo e spiegare meglio la decisione.", cta: "Leggi la guida completa", card: "SCHEDA DECISIONE QC", complete: "controlli prima della spedizione", checklist: "CHECKLIST", checklistTitle: "Dall’identità alla decisione finale", checks: [["Identità", "Articolo, variante, colore e taglia"], ["Copertura", "Abbastanza angoli nitidi"], ["Forma", "Simmetria e proporzioni"], ["Costruzione", "Cuciture, hardware e bordi"], ["Misure", "Dimensioni critiche"], ["Decisione", "Spedisci, ricontrolla, cambia o restituisci"]], noteTitle: "Prova, non garanzia", note: "Le foto QC riducono l’incertezza ma non provano autenticità, durata, legalità d’importazione o stato finale. Verifica scheda e regole della destinazione." },
    shipping: { eyebrow: "Pianificazione del pacco", title: "Note di spedizione", intro: "Stima peso reale e volumetrico, poi verifica la rotta dopo il consolidamento. Il pacco finale determina il peso fatturabile.", cards: [["Peso reale", "Peso misurato dopo l’imballaggio. Protezioni e scatole possono cambiarlo."], ["Peso volumetrico", "Calcolo basato sulle dimensioni. Una scatola grande e leggera può costare di più."], ["Restrizioni di rotta", "La disponibilità dipende da destinazione, tipo, dimensioni e regole attuali."], ["Dogana e tasse", "Le regole d’importazione variano per destinazione e possono cambiare."]], formula: "FORMULA DI LAVORO", formulaTitle: "Peso fatturabile = il valore idoneo maggiore", actual: "Peso reale del pacco", vs: "contro", volume: "Peso volumetrico calcolato", formulaNote: "Usalo solo per pianificare. Applica divisore e arrotondamenti della rotta attiva." },
    articlesPage: { eyebrow: "Conoscenza pratica su ricerca e QC", title: "Articoli SEO e guide", intro: "Articoli indipendenti e utili, con pulsanti chiari verso pagine complete. Ogni guida copre un intento di ricerca diverso.", read: "Leggi l’articolo completo", updated: "Aggiornato il 27 agosto 2026" }, article: { back: "Tutti gli articoli SEO", reviewed: "Revisionato il 27 agosto 2026", independent: "Ricerca indipendente", inGuide: "IN QUESTA GUIDA", summary: "Riepilogo pratico", browse: "Vedi i prodotti", ready: "Pronto a controllare una scheda?", readyText: "Apri la pagina sorgente esatta e applica i controlli della guida alle prove visibili." },
    faqTitle: "Domande frequenti", faqEyebrow: "Limiti chiari, risposte utili", faqIntro: "Cosa fa l’interfaccia, cosa significano i dati e cosa va ancora verificato.", faqs: [["FindQC vende prodotti?", "No. È un’interfaccia indipendente; le azioni aprono schede esterne."], ["I prezzi sono finali?", "No. Sono conversioni USD approssimative; cambio, opzioni, stock e costi cambiano."], ["Una foto QC garantisce la qualità?", "No. È una prova visiva di un record, non della costruzione nascosta."], ["Perché ogni scheda apre una pagina specifica?", "Immagine e destinazione devono coincidere; ogni scheda usa l’immagine della pagina esatta."], ["Posso cercare con un link?", "Sì. Incolla parola chiave, ID o link sorgente."], ["Le informazioni di spedizione sono garantite?", "No. Rotta, peso, costi, dogana e tempi dipendono dalle condizioni attuali."]],
    legal: { updated: "Aggiornato il 27 agosto 2026", privacy: "Privacy", terms: "Termini e avvertenza", privacyIntro: "Questa anteprima non richiede account e non raccoglie dati di pagamento.", termsIntro: "Usa FindQC come supporto e verifica ogni decisione con fonti e regole attuali.", privacySections: [["Dati dell’anteprima", "Il termine viene inviato al catalogo esterno solo all’invio della ricerca. Non esistono account, checkout o pagamenti."], ["Destinazioni esterne", "Le pagine esterne seguono le proprie politiche. Consultale prima di inserire dati personali."]], termsSections: [["Risorsa indipendente", "FindQC non vende, non gestisce ordini e non garantisce qualità, stock, prezzo, spedizione, dogana o consegna."], ["Responsabilità", "Immagini e registri storici sono riferimenti. Verifica scheda, regole di rotta e legge applicabile."]] }, footer: "Ricerca indipendente. Schede, disponibilità e prezzi possono cambiare; verifica la fonte.", privacy: "Privacy", terms: "Termini"
  }
};

const enArticles = [
  { slug: "how-to-read-qc-photos", title: "How to Read QC Photos Without Guessing", description: "A repeatable inspection order for identity, coverage, shape, construction, measurements and the final ship-or-return decision.", readTime: "12 min read", summary: "Confirm the correct item first, check whether the photo set covers every critical area, compare shape before tiny details, use measurements for fit, and end with one explicit action.", sections: [
    ["Start with identity", "Confirm the product type, selected color, size label and included parts before hunting for small defects. Keep the live source listing beside the warehouse photos. If the wrong item or variant arrived, fine cosmetic details no longer change the decision. A consistent identity-first order also prevents reviewers from being distracted by lighting, packaging or one attractive angle."],
    ["Check photo coverage", "Useful evidence needs enough angles. Footwear normally needs both sides, front, heel, outsole, overhead view and size label. Clothing benefits from front, back, tags, graphics, cuffs, seams and measurements. When a critical area is blurred or missing, request a focused image before international shipping instead of assuming the hidden area is acceptable."],
    ["Read shape before logos", "Overall proportions often expose a problem faster than extreme zoom. Compare paired items on the same visual line and look at toe shape, panel position, sleeve length, pocket alignment or symmetry. Perspective can distort one frame, so confirm a suspected issue from another angle. A difference that disappears when the camera moves is more likely perspective than construction."],
    ["Use measurements correctly", "A size tag confirms what was packed, not how it fits. Compare chest width, garment length, waist, inseam or insole length with an item you already own. Use the same measurement method on both items. Rulers held above a curved surface can create false readings, so ask for a flat, focused measurement when the dimension controls fit."],
    ["Separate cosmetic and structural issues", "Loose threads, removable dust and packaging marks are not equivalent to open seams, broken hardware, missing parts or deep scratches. Decide in advance which defects justify an exchange or return. Structural damage, incorrect specifications and problems likely to worsen during shipping should carry more weight than variations visible only under heavy zoom."],
    ["Finish with one action", "End with ship, request another check, exchange or return—and record the reason in one sentence. QC photos reduce uncertainty but cannot prove authenticity, durability, import legality or final delivery condition. Verify the live listing, current service rules and destination law before spending money."]
  ]},
  { slug: "search-product-link-id-keyword", title: "Product Link, Item ID or Keyword? A Better Search Workflow", description: "Choose the search input that preserves the strongest match and avoid wasting time on broad, ambiguous results.", readTime: "10 min read", summary: "Use an exact source link when available, an item ID when the system recognizes it, and a precise keyword query only when no stronger identifier exists.", sections: [
    ["Rank inputs by precision", "An exact source link normally carries more identity than an item ID, and an item ID carries more identity than a generic keyword. Start with the strongest identifier you already have. Broad terms such as shoes or hoodie are useful for discovery, but poor for confirming one specific listing because many unrelated records can share those words."],
    ["Clean the source link", "Copy the direct product page rather than a tracking redirect, social share wrapper or image URL. Remove accidental spaces and check that the link opens the intended item in a normal browser. If the source page has changed or disappeared, preserve the title, selected option and screenshots before searching for a replacement."],
    ["Use item IDs carefully", "An item ID can be efficient when it belongs to the catalog being searched. Numbers from another marketplace, an order record or a warehouse system may refer to something else. Pair the ID with one visual or textual check—such as title, main image or selected variant—before assuming the result is exact."],
    ["Write discriminating keywords", "When no link or ID works, combine item type with the most distinctive visible attributes: material, silhouette, color family, graphic placement or model reference. Avoid stuffing every possible synonym into one query. Start narrow, inspect results, then remove one term at a time if nothing useful appears."],
    ["Confirm the destination", "A convincing thumbnail is not enough. Open the final page and compare the main image, options, visible construction and current availability. The destination of every FindQC card is deliberately matched to its displayed image, but users should still verify the live source because listings and inventory can change."],
    ["Keep a small research record", "Save the exact URL, item ID, date checked and the option that interested you. This makes later QC comparison easier and prevents confusion if the title or thumbnail changes. Historical research helps retrace a decision, but it never replaces the current listing."]
  ]},
  { slug: "actual-vs-volumetric-weight", title: "Actual vs Volumetric Weight: Plan a Parcel Before Shipping", description: "Understand the two weight figures that can affect international parcel cost and what to verify after consolidation.", readTime: "11 min read", summary: "Plan with both measured and dimensional weight, reduce avoidable volume where appropriate, then recalculate using the exact live route rules after packing.", sections: [
    ["Understand actual weight", "Actual weight is the measured mass of the packed parcel. It can change when items are consolidated, boxes are removed or protective material is added. A product-page estimate is not the final billable figure because the shipping parcel includes outer packaging and any services selected at the warehouse."],
    ["Understand volumetric weight", "Volumetric or dimensional weight converts package size into a weight-like number. A large light carton may therefore cost more than a smaller heavier one. The divisor and rounding method vary by route, so do not rely on one universal formula or an old successful parcel."],
    ["Identify volume drivers", "Shoe boxes, rigid packaging, oversized accessories and protective frames can create unused space. Removing packaging may reduce volume, but it can also reduce protection or resale value. Decide which packaging is essential before submitting the parcel rather than choosing the smallest box automatically."],
    ["Compare eligible routes", "A lower headline rate is not always the lower final price. Check weight bands, minimum charges, size limits, restricted-item rules, fuel or remote-area fees and destination availability. The same parcel can be calculated differently across routes, especially near a rounding boundary."],
    ["Recheck after consolidation", "Use single-item weights only for an early estimate. Once the warehouse has packed the final parcel, review measured weight and external dimensions again. If either figure looks implausible, request a reweigh or packaging photo before payment when the service supports it."],
    ["Treat customs separately", "Shipping weight does not determine customs treatment by itself. Declaration rules, taxes, prohibited items and documentation depend on destination law and current carrier policies. Verify the live route and official destination guidance; past delivery is not a guarantee of future treatment. Keep the commercial description, quantity and supporting records consistent with the actual contents, and never use a shipping-cost estimate as legal guidance. If the destination or carrier wording is unclear, pause and consult the current official rule before submitting the parcel. This final check belongs beside the cost calculation, but it remains a separate compliance decision."]
  ]}
];

const articleTranslations = {
  de: [
    { title: "QC-Fotos lesen, ohne zu raten", description: "Eine wiederholbare Prüfreihenfolge für Identität, Bildabdeckung, Form, Verarbeitung, Maße und die Versandentscheidung.", readTime: "12 Min. Lesezeit", summary: "Zuerst den richtigen Artikel bestätigen, dann Bildabdeckung, Form, Verarbeitung und Maße prüfen und mit einer eindeutigen Aktion abschließen.", sections: [["Mit der Identität beginnen", "Prüfe Artikeltyp, Farbe, Größenetikett und enthaltene Teile, bevor du kleine Mängel suchst. Halte das Live-Angebot neben den Lagerfotos offen. Ist Artikel oder Variante falsch, ändern feine kosmetische Details die Entscheidung nicht."], ["Bildabdeckung prüfen", "Gute Belege zeigen alle kritischen Bereiche aus mehreren Winkeln. Fehlt ein Bereich oder ist er unscharf, fordere vor dem internationalen Versand ein gezieltes Foto an."], ["Form vor Logos lesen", "Gesamtproportionen zeigen Probleme oft schneller als starker Zoom. Vergleiche Symmetrie, Paneele, Ärmellänge oder Taschen und bestätige Auffälligkeiten aus einem zweiten Winkel."], ["Maße richtig nutzen", "Ein Etikett bestätigt die gepackte Größe, nicht die Passform. Vergleiche flach gemessene Breite, Länge, Taille oder Einlegesohle mit einem eigenen Referenzstück."], ["Kosmetisch oder strukturell", "Lose Fäden und Staub sind nicht dasselbe wie offene Nähte, defekte Beschläge oder fehlende Teile. Strukturelle Schäden und falsche Spezifikationen wiegen schwerer."], ["Mit einer Aktion enden", "Wähle Versand, Nachprüfung, Umtausch oder Rückgabe und notiere den Grund. QC-Fotos reduzieren Unsicherheit, garantieren aber weder Echtheit noch Haltbarkeit oder Lieferung."]]},
    { title: "Produktlink, Artikel-ID oder Stichwort? Der bessere Suchablauf", description: "Wähle die Eingabe mit der stärksten Identität und vermeide breite, mehrdeutige Treffer.", readTime: "10 Min. Lesezeit", summary: "Nutze zuerst den exakten Quelllink, danach eine erkannte Artikel-ID und nur ohne stärkere Kennung eine präzise Stichwortsuche.", sections: [["Eingaben nach Präzision ordnen", "Ein direkter Produktlink enthält meist mehr Identität als eine ID, eine ID mehr als ein allgemeines Stichwort. Beginne mit der stärksten Kennung."], ["Quelllink bereinigen", "Kopiere die direkte Produktseite statt Tracking-Weiterleitung, Social-Wrapper oder Bild-URL. Prüfe, ob der Link den richtigen Artikel öffnet."], ["IDs vorsichtig verwenden", "Nummern aus anderen Marktplätzen, Bestellungen oder Lagersystemen können etwas anderes bedeuten. Gleiche Titel, Hauptbild oder Variante ab."], ["Unterscheidende Stichwörter", "Kombiniere Artikeltyp mit Material, Silhouette, Farbfamilie oder Motivposition. Starte eng und entferne Begriffe schrittweise."], ["Zielseite bestätigen", "Ein passendes Thumbnail genügt nicht. Öffne die Seite und vergleiche Hauptbild, Optionen, sichtbare Konstruktion und Bestand."], ["Recherche festhalten", "Speichere URL, ID, Prüfdatum und gewünschte Option. Das erleichtert den späteren QC-Vergleich, ersetzt aber nie das aktuelle Angebot."]]},
    { title: "Tatsächliches vs. Volumengewicht: Paket vor dem Versand planen", description: "Verstehe beide Gewichtswerte und prüfe sie nach der Konsolidierung erneut.", readTime: "11 Min. Lesezeit", summary: "Plane mit Mess- und Volumengewicht, reduziere unnötiges Volumen sinnvoll und rechne nach dem Packen mit den Live-Regeln der Route neu.", sections: [["Tatsächliches Gewicht", "Es ist die gemessene Masse des fertigen Pakets und ändert sich durch Konsolidierung, entfernte Kartons oder Schutzmaterial."], ["Volumengewicht", "Es wandelt Paketmaße in einen Gewichtswert um. Große leichte Kartons können dadurch teurer sein; Divisor und Rundung unterscheiden sich je Route."], ["Volumentreiber erkennen", "Schuhkartons, starre Verpackungen und Schutzrahmen erzeugen Leerraum. Entfernen kann Kosten senken, aber Schutz oder Wiederverkaufswert reduzieren."], ["Routen vergleichen", "Prüfe Gewichtsstufen, Mindestgebühren, Größenlimits, Beschränkungen und Zuschläge. Eine niedrige Grundrate ist nicht immer der niedrigste Endpreis."], ["Nach Konsolidierung prüfen", "Einzelgewichte sind nur frühe Schätzungen. Nach dem Packen gemessenes Gewicht und Außenmaße erneut kontrollieren und Unplausibles nachmessen lassen."], ["Zoll getrennt behandeln", "Gewicht allein bestimmt keine Zollbehandlung. Erklärung, Steuer und Verbote richten sich nach Zielrecht und aktuellen Carrier-Regeln."]]}],
  es: [
    { title: "Cómo leer fotos QC sin adivinar", description: "Un orden repetible para identidad, cobertura, forma, construcción, medidas y decisión final.", readTime: "12 min de lectura", summary: "Confirma el artículo correcto, revisa la cobertura, compara la forma antes de detalles mínimos, mide y termina con una acción explícita.", sections: [["Empieza por la identidad", "Comprueba tipo, color, talla y piezas incluidas antes de buscar defectos pequeños. Mantén abierta la ficha de origen junto a las fotos."], ["Revisa la cobertura", "Las pruebas útiles muestran las zonas críticas desde varios ángulos. Si falta una zona, solicita una foto enfocada antes del envío."], ["Lee la forma antes que los logotipos", "Las proporciones generales revelan problemas más rápido que un zoom extremo. Confirma cualquier diferencia desde otro ángulo."], ["Usa bien las medidas", "La etiqueta no demuestra ajuste. Compara medidas planas con una prenda o plantilla que ya tengas y usa el mismo método."], ["Distingue cosmético y estructural", "Polvo e hilos sueltos no equivalen a costuras abiertas, piezas rotas o componentes ausentes."], ["Termina con una acción", "Elige enviar, volver a revisar, cambiar o devolver y anota el motivo. Las fotos reducen incertidumbre, no garantizan autenticidad ni entrega."]]},
    { title: "¿Enlace, ID o palabra clave? Un mejor flujo de búsqueda", description: "Elige la entrada que conserva la coincidencia más fuerte y evita resultados ambiguos.", readTime: "10 min de lectura", summary: "Usa enlace exacto si existe, después un ID reconocido y palabras precisas solo cuando no haya identificador mejor.", sections: [["Ordena por precisión", "Un enlace directo suele aportar más identidad que un ID, y un ID más que una palabra genérica."], ["Limpia el enlace", "Copia la página directa, no un redireccionamiento, envoltorio social o URL de imagen. Comprueba que abre el artículo correcto."], ["Usa IDs con cuidado", "Números de otro mercado, pedido o almacén pueden referirse a otra cosa. Contrasta título, imagen o variante."], ["Escribe palabras distintivas", "Combina tipo con material, silueta, color o posición del gráfico. Empieza estrecho y elimina un término cada vez."], ["Confirma el destino", "Una miniatura convincente no basta. Abre la página y compara imagen, opciones, construcción y disponibilidad."], ["Guarda un registro", "Conserva URL, ID, fecha y opción. Facilita la comparación QC, pero no sustituye la ficha actual."]]},
    { title: "Peso real frente a volumétrico: planifica el paquete", description: "Comprende las dos cifras que pueden afectar al coste y qué revisar tras consolidar.", readTime: "11 min de lectura", summary: "Planifica con ambos pesos, reduce volumen evitable cuando convenga y recalcula con las reglas activas tras embalar.", sections: [["Peso real", "Es la masa medida del paquete terminado y cambia con consolidación, cajas retiradas y protección añadida."], ["Peso volumétrico", "Convierte dimensiones en una cifra de peso. Una caja grande y ligera puede costar más; divisor y redondeo varían."], ["Qué crea volumen", "Cajas de zapatos, embalajes rígidos y protectores generan espacio. Quitarlos puede reducir coste y también protección."], ["Compara rutas", "Revisa bandas, mínimos, límites, artículos restringidos y recargos. La tarifa inicial más baja no siempre gana."], ["Verifica tras consolidar", "Los pesos individuales son estimaciones. Revisa peso y medidas finales y pide un nuevo control si parecen improbables."], ["Separa aduanas", "El peso no determina por sí solo el trato aduanero. Declaración, impuestos y prohibiciones dependen del destino."]]}],
  fr: [
    { title: "Lire les photos QC sans deviner", description: "Un ordre reproductible pour l’identité, la couverture, la forme, la fabrication, les mesures et la décision.", readTime: "12 min de lecture", summary: "Confirmez d’abord le bon article, vérifiez la couverture, la forme, les mesures, puis terminez par une action explicite.", sections: [["Commencer par l’identité", "Vérifiez type, couleur, taille et éléments inclus avant les petits défauts. Gardez la fiche source ouverte à côté des photos."], ["Vérifier la couverture", "Les preuves utiles montrent toutes les zones critiques sous plusieurs angles. Demandez une photo ciblée si une zone manque."], ["Lire la forme avant les logos", "Les proportions générales révèlent souvent un problème plus vite qu’un zoom extrême. Confirmez depuis un second angle."], ["Bien utiliser les mesures", "L’étiquette ne prouve pas la coupe. Comparez des mesures à plat avec un article que vous possédez déjà."], ["Cosmétique ou structurel", "Poussière et fils libres ne valent pas une couture ouverte, une pièce cassée ou un élément manquant."], ["Finir par une action", "Choisissez expédier, revérifier, échanger ou retourner et notez la raison. Les photos réduisent l’incertitude sans garantir authenticité ou livraison."]]},
    { title: "Lien produit, identifiant ou mot-clé ? Une meilleure recherche", description: "Choisissez l’entrée qui conserve la correspondance la plus forte.", readTime: "10 min de lecture", summary: "Préférez le lien source exact, puis un identifiant reconnu, et utilisez des mots précis seulement sans meilleur repère.", sections: [["Classer par précision", "Un lien direct apporte généralement plus d’identité qu’un identifiant, lui-même plus précis qu’un mot générique."], ["Nettoyer le lien", "Copiez la page directe, pas une redirection de suivi, un partage social ou une URL d’image. Vérifiez l’article ouvert."], ["Utiliser les identifiants avec prudence", "Un numéro d’une autre place de marché, commande ou entrepôt peut désigner autre chose. Comparez titre, image ou variante."], ["Écrire des mots distinctifs", "Combinez type, matière, silhouette, couleur ou placement du motif. Commencez étroit et retirez un terme à la fois."], ["Confirmer la destination", "Une miniature convaincante ne suffit pas. Ouvrez la page et comparez image, options, construction et stock."], ["Conserver une trace", "Gardez URL, identifiant, date et option. Cela aide le QC ultérieur sans remplacer la fiche actuelle."]]},
    { title: "Poids réel ou volumétrique : préparer un colis", description: "Comprenez les deux chiffres qui peuvent affecter le coût et ce qu’il faut vérifier après consolidation.", readTime: "11 min de lecture", summary: "Planifiez avec les deux poids, réduisez le volume évitable avec discernement et recalculez selon la ligne active après emballage.", sections: [["Poids réel", "C’est la masse mesurée du colis fini. Consolidation, retrait des boîtes et protection peuvent la modifier."], ["Poids volumétrique", "Il convertit les dimensions en poids. Un grand carton léger peut coûter plus cher ; diviseur et arrondi varient."], ["Sources de volume", "Boîtes à chaussures, emballages rigides et protections créent du vide. Les retirer peut réduire coût et protection."], ["Comparer les lignes", "Vérifiez tranches, minimums, limites, restrictions et suppléments. Le tarif affiché le plus bas ne gagne pas toujours."], ["Revérifier après consolidation", "Les poids unitaires sont des estimations. Contrôlez poids et dimensions finaux et demandez une nouvelle mesure si nécessaire."], ["Traiter la douane séparément", "Le poids ne détermine pas seul la douane. Déclaration, taxes et interdictions dépendent de la destination."]]}],
  it: [
    { title: "Come leggere le foto QC senza indovinare", description: "Un ordine ripetibile per identità, copertura, forma, costruzione, misure e decisione finale.", readTime: "12 min di lettura", summary: "Conferma l’articolo corretto, controlla la copertura, confronta la forma prima dei dettagli, misura e termina con un’azione chiara.", sections: [["Parti dall’identità", "Controlla tipo, colore, taglia e parti incluse prima dei difetti minori. Tieni la scheda sorgente accanto alle foto."], ["Controlla la copertura", "Le prove utili mostrano ogni zona critica da più angoli. Se manca un’area, chiedi una foto mirata prima della spedizione."], ["Leggi la forma prima dei loghi", "Le proporzioni generali mostrano problemi più velocemente di uno zoom estremo. Conferma da un secondo angolo."], ["Usa bene le misure", "L’etichetta non prova la vestibilità. Confronta misure piatte con un capo o una soletta che possiedi."], ["Cosmetico o strutturale", "Polvere e fili sciolti non equivalgono a cuciture aperte, hardware rotto o parti mancanti."], ["Termina con un’azione", "Scegli spedisci, ricontrolla, cambia o restituisci e annota il motivo. Le foto riducono l’incertezza, non garantiscono autenticità o consegna."]]},
    { title: "Link, ID o parola chiave? Un flusso di ricerca migliore", description: "Scegli l’input che conserva la corrispondenza più forte ed evita risultati ambigui.", readTime: "10 min di lettura", summary: "Usa il link esatto, poi un ID riconosciuto e parole precise solo quando non esiste un identificatore migliore.", sections: [["Ordina per precisione", "Un link diretto contiene in genere più identità di un ID, e un ID più di una parola generica."], ["Pulisci il link", "Copia la pagina diretta, non redirect, wrapper social o URL immagine. Controlla che apra l’articolo corretto."], ["Usa gli ID con cautela", "Numeri di altri marketplace, ordini o magazzini possono indicare altro. Confronta titolo, immagine o variante."], ["Scrivi parole distintive", "Combina tipo, materiale, silhouette, colore o posizione grafica. Parti stretto e rimuovi un termine alla volta."], ["Conferma la destinazione", "Una miniatura convincente non basta. Apri la pagina e confronta immagine, opzioni, costruzione e stock."], ["Conserva un record", "Salva URL, ID, data e opzione. Aiuta il confronto QC, ma non sostituisce la scheda attuale."]]},
    { title: "Peso reale o volumetrico: pianifica il pacco", description: "Comprendi le due cifre che possono incidere sul costo e cosa verificare dopo il consolidamento.", readTime: "11 min di lettura", summary: "Pianifica con entrambi i pesi, riduci il volume evitabile con criterio e ricalcola con le regole attive dopo l’imballaggio.", sections: [["Peso reale", "È la massa misurata del pacco finito e cambia con consolidamento, rimozione di scatole e protezioni."], ["Peso volumetrico", "Converte le dimensioni in peso. Una scatola grande e leggera può costare di più; divisore e arrotondamento variano."], ["Fonti di volume", "Scatole, confezioni rigide e protezioni creano spazio vuoto. Rimuoverle può ridurre costo e protezione."], ["Confronta le rotte", "Controlla fasce, minimi, limiti, restrizioni e supplementi. La tariffa iniziale più bassa non sempre vince."], ["Ricontrolla dopo il consolidamento", "I pesi singoli sono stime. Verifica peso e dimensioni finali e chiedi una nuova misurazione se sembrano errati."], ["Tratta la dogana separatamente", "Il peso non determina da solo la dogana. Dichiarazione, tasse e divieti dipendono dalla destinazione."]]}]
};

const baseArticles = Object.fromEntries(Object.keys(copy).map((lang) => [lang, enArticles.map((article, index) => ({
  ...article,
  ...(lang === "en" ? {} : articleTranslations[lang][index]),
}))]));

const parityReadyArticles = Object.fromEntries(Object.keys(baseArticles).map((lang) => [lang, applyParityArticles(extendArticles(baseArticles[lang], lang), lang)]));

export const seoArticles = Object.fromEntries(Object.keys(parityReadyArticles).map((lang) => [
  lang,
  [...applyArticleParityBoost(parityReadyArticles[lang], lang, parityReadyArticles.en), localizedRequirementsBriefArticles[lang], localizedUseCaseArticles[lang]],
]));

export const categoryCopy = {
  en: {
    nav: "Categories", eyebrow: "Exact-source category directory", title: "Product categories", intro: "Browse six distinct product groups. Every category has its own internal page and a clearly marked button to the matching source category.", open: "Explore category", source: "Open source category", related: "Browse every category", noteTitle: "How to use a category page", note: "Use categories for discovery, then open the exact product listing before comparing QC evidence, price or availability.",
    names: ["Shoes", "Hoodies & sweaters", "T-shirts", "Jackets", "Accessories", "Jerseys"],
    descriptions: ["Low-top, running and casual footwear research with fit and construction checks.", "Pullover, knit and layered tops with measurement and material checkpoints.", "Graphic and basic tees organized around print placement, sizing and visible construction.", "Outerwear research covering silhouette, hardware, lining and packed volume.", "Watches, bags, small objects and other add-ons that need detail-focused inspection.", "Match-day and supporter styles with print, badge, color and sizing checks."]
  },
  de: {
    nav: "Kategorien", eyebrow: "Kategorieverzeichnis mit exakter Quelle", title: "Produktkategorien", intro: "Sechs eigenständige Produktgruppen. Jede Kategorie besitzt eine interne Seite und eine klar markierte Schaltfläche zur passenden Quellkategorie.", open: "Kategorie ansehen", source: "Quellkategorie öffnen", related: "Alle Kategorien durchsuchen", noteTitle: "Kategorie richtig nutzen", note: "Nutze Kategorien zur Entdeckung und öffne danach das exakte Produktangebot, bevor du QC-Belege, Preis oder Bestand vergleichst.",
    names: ["Schuhe", "Hoodies & Pullover", "T-Shirts", "Jacken", "Accessoires", "Trikots"],
    descriptions: ["Recherche zu Low-Tops, Lauf- und Freizeitschuhen mit Passform- und Verarbeitungsprüfung.", "Hoodies, Strick und Oberteile mit Maß- und Materialkontrollen.", "Grafik- und Basic-Shirts mit Fokus auf Druckposition, Größe und Verarbeitung.", "Outerwear mit Silhouette, Beschlägen, Futter und Packvolumen.", "Uhren, Taschen und kleine Objekte für detailorientierte Prüfung.", "Matchday- und Fanstyles mit Druck-, Badge-, Farb- und Größenkontrolle."]
  },
  es: {
    nav: "Categorías", eyebrow: "Directorio de categorías con fuente exacta", title: "Categorías de productos", intro: "Seis grupos de producto distintos. Cada categoría tiene una página interna y un botón claro hacia la categoría de origen correspondiente.", open: "Explorar categoría", source: "Abrir categoría de origen", related: "Ver todas las categorías", noteTitle: "Cómo usar una categoría", note: "Usa las categorías para descubrir y abre después la ficha exacta antes de comparar pruebas QC, precio o disponibilidad.",
    names: ["Calzado", "Sudaderas y jerséis", "Camisetas", "Chaquetas", "Accesorios", "Camisetas deportivas"],
    descriptions: ["Zapatillas bajas, running y calzado casual con controles de ajuste y construcción.", "Sudaderas, punto y capas con medidas y comprobación de materiales.", "Camisetas gráficas y básicas con impresión, talla y construcción visible.", "Prendas exteriores con silueta, herrajes, forro y volumen de embalaje.", "Relojes, bolsas y objetos pequeños que requieren inspección detallada.", "Estilos de partido y afición con impresión, escudo, color y talla."]
  },
  fr: {
    nav: "Catégories", eyebrow: "Répertoire de catégories à source exacte", title: "Catégories de produits", intro: "Six groupes distincts. Chaque catégorie possède une page interne et un bouton clair vers la catégorie source correspondante.", open: "Explorer la catégorie", source: "Ouvrir la catégorie source", related: "Voir toutes les catégories", noteTitle: "Bien utiliser une catégorie", note: "Utilisez les catégories pour découvrir, puis ouvrez la fiche exacte avant de comparer preuves QC, prix ou disponibilité.",
    names: ["Chaussures", "Sweats & pulls", "T-shirts", "Vestes", "Accessoires", "Maillots"],
    descriptions: ["Baskets basses, running et chaussures casual avec contrôles de coupe et fabrication.", "Sweats, mailles et couches avec mesures et vérification des matières.", "T-shirts graphiques et basiques : placement, taille et construction visible.", "Vêtements d’extérieur : silhouette, pièces, doublure et volume emballé.", "Montres, sacs et petits objets demandant une inspection détaillée.", "Styles de match et supporters avec impression, badge, couleur et taille."]
  },
  it: {
    nav: "Categorie", eyebrow: "Catalogo categorie con fonte esatta", title: "Categorie di prodotti", intro: "Sei gruppi di prodotto distinti. Ogni categoria ha una pagina interna e un pulsante chiaro verso la categoria sorgente corrispondente.", open: "Esplora categoria", source: "Apri categoria sorgente", related: "Vedi tutte le categorie", noteTitle: "Come usare una categoria", note: "Usa le categorie per scoprire prodotti, poi apri la scheda esatta prima di confrontare prove QC, prezzo o disponibilità.",
    names: ["Scarpe", "Felpe & maglioni", "T-shirt", "Giacche", "Accessori", "Maglie"],
    descriptions: ["Sneakers basse, running e calzature casual con controlli di vestibilità e costruzione.", "Felpe, maglieria e strati con misure e controlli dei materiali.", "T-shirt grafiche e basic con stampa, taglia e costruzione visibile.", "Capispalla con silhouette, hardware, fodera e volume imballato.", "Orologi, borse e piccoli oggetti che richiedono controlli di dettaglio.", "Stili da partita e tifoso con stampa, stemma, colore e taglia."]
  }
};
