export const articleParityBoost = {
  en: ["", "", ""],
  de: [
    "Nutze die Prüfung außerdem als zusammenhängenden Ablauf und nicht als Sammlung unabhängiger Nahaufnahmen. Beginne mit der Live-Quelle, schreibe die gewählte Option auf und ordne jedes Lagerbild diesem Ausgangspunkt zu. Lege danach eine kleine Liste der entscheidenden Bereiche an: Identität, vollständige Bildabdeckung, Gesamtform, symmetrische oder wiederholte Teile, Verarbeitung, Maße und Lieferumfang. Für jeden Bereich wird entweder eine sichtbare Beobachtung, eine fehlende Information oder eine konkrete Nachforderung notiert. Bei Schuhen bedeutet das beispielsweise, beide Seiten, Vorderseite, Ferse, Draufsicht, Außensohle, Größenetikett und eine klar durchgeführte Längenmessung gemeinsam zu lesen. Bei Kleidung gehören Vorder- und Rückseite, Innenetikett, Druck, Saum, Bündchen, Taschen, Beschläge und flache Maße zusammen. Ein Foto darf nicht außerhalb dieser Kette überbewertet werden. Ein schöner Winkel kann Form verbergen, ein starkes Zoom kann harmlose Fasern dramatisieren und ein schräg gehaltenes Lineal kann eine präzise wirkende, aber falsche Zahl erzeugen. Vergleiche deshalb mindestens zwei Perspektiven, prüfe neutrale Farbreferenzen und unterscheide sichtbare Tatsachen von Schlussfolgerungen. Schreibe zuerst ‘Naht an der linken Tasche endet sichtbar höher’ und erst danach, ob dies kosmetisch, funktional oder eine falsche Spezifikation ist. Wenn mehrere historische Datensätze vorhanden sind, suche nach wiederkehrenden Merkmalen, achte aber darauf, dass Quelllink, Option und Zeitraum tatsächlich zusammenpassen. Eine Wiederholung erhöht die Relevanz, garantiert jedoch keine neue Charge. Vor der Freigabe sollte eine zweite Person aus deinen Notizen denselben Entscheidungsweg nachvollziehen können. Wenn sie dazu Informationen erfinden müsste, fehlt noch ein Beleg. Schließe mit Aktion, Grund und Restunsicherheit ab. So bleibt QC eine dokumentierte Risikoreduktion und wird nicht zu einem unbelegten Echtheits-, Qualitäts- oder Lieferversprechen.",
    "Führe die Suche wie eine prüfbare Recherche und nicht wie ein endloses Durchklicken attraktiver Vorschaubilder. Der Ausgangspunkt wird vollständig gespeichert: direkte URL, endgültiges Weiterleitungsziel, Marktplatz, Artikelkennung, gewünschte Option, sichtbarer Titel und Prüfdatum. Suche zuerst mit dem stärksten Identifikator. Bei einem aktiven Produktlink wird nicht sofort der erste Treffer übernommen, sondern Zielseite, Hauptbild, Optionsbilder, Konstruktion, Farbe, Lieferumfang und Kennung werden verglichen. Stimmen einige Punkte, andere bleiben jedoch offen, lautet die Einordnung ‘wahrscheinlich gleicher Artikel’ und nicht ‘exakt’. Fällt der Link aus, bleibt der historische Datensatz getrennt. Suche danach mit der erkannten ID im richtigen Marktplatzkontext, mit einer unterscheidenden Material- oder Modellphrase und zuletzt mit einem möglichst unbearbeiteten Bild. Jede Änderung der Suchanfrage wird notiert, damit später klar ist, wodurch ein Kandidat in die Auswahl kam. Bildsuche erzeugt Kandidaten, keine kommerzielle Identität: zugeschnittene Fotos, entfernte Hintergründe, andere Farbvarianten und wiederverwendete Verkäuferbilder können eine hohe Ähnlichkeit vortäuschen. Verwende deshalb die vier festen Match-Stufen exakte Quelle, wahrscheinlich gleich, visuell ähnlich und ungeprüft. Ergänze zu jeder Stufe einen kurzen Grund und die nächste Aktion. Popularität, gespeicherte Funde, Seller-Score, Hauls oder einzelne Bewertungen können die Reihenfolge der Recherche beeinflussen, aber niemals die Identität beweisen. Vor Veröffentlichung werden Preis, Bestand, Option und aktives Ziel erneut geprüft. Wenn eine Seite später entfernt, umgeleitet oder wesentlich verändert wird, wird der Fund neu verifiziert, historisch gekennzeichnet oder entfernt. Ersetze niemals stillschweigend nur die URL durch ein ähnliches Angebot. Das Suchprotokoll mit Datum, Screenshot und Begründung schützt die Bild-zu-Link-Zuordnung, verhindert gemischte Datensätze und macht deutlich, wo eine Aussage sicher, wahrscheinlich oder weiterhin offen ist.",
    "Behandle die Versandplanung als Versionen eines Rechenblatts, die sich mit jedem Verpackungsschritt ändern. In der frühen Version stehen Artikelzahl, bekannte Einzelgewichte und die Frage, ob Verkaufsboxen enthalten sind. Dazu kommen ein kompaktes und ein geschütztes Verpackungsszenario. Diese Werte bilden nur eine Spanne, weil Außenkarton, Zwischenräume, Schutzecken und Konsolidierung noch nicht gemessen wurden. In der nächsten Version werden nach dem Packen die tatsächliche Masse sowie äußere Länge, Breite und Höhe eingetragen. Verwende für alle Routen genau dieses fertige Paket und trage pro Linie Divisor, Einheit, Rundungsfolge, Mindestbetrag, Gewichtsinkrement, Seitenlimit, Gesamtmaß, eingeschränkte Artikel, Zuschläge, Tracking und Versicherung ein. Das Volumengewicht wird erst mit der aktuell veröffentlichten Regel berechnet. Prüfe auch, ob einzelne Seiten vor der Multiplikation gerundet werden und welcher Wert anschließend als abrechenbar gilt. Entferne unzulässige Linien, bevor du Preise vergleichst. Ein niedriger Kilopreis kann nach Mindestgebühr, strenger Volumenrechnung oder Großpaketzuschlag teurer sein. Verpackungsänderungen werden bewusst bewertet: Eine weiche Textilie braucht meist weniger Struktur als Schuhe, empfindliche Figuren oder bewegliche Beschläge. ‘Box entfernen’ ist keine allgemeine Empfehlung, sondern eine Abwägung zwischen Volumen, Schutz und Präsentation. Wenn das gemessene Ergebnis stark von der Planung abweicht, kontrolliere Artikelzahl, Einheiten, äußere Maße, entfernte Verpackung und Zusatzleistungen und fordere nach Möglichkeit Nachwiegen oder Foto an. Zoll, Steuern, Deklaration und Einfuhrrecht bleiben getrennte Prüfungen anhand aktueller offizieller Ziel- und Carrier-Regeln. Speichere Angebotsdatum und verwendete Regel. Jede spätere Umpackung, Schutzänderung oder neue Route löst eine vollständige Neuberechnung aus. So bleibt die Seite eine nachvollziehbare Planungsmethode und verspricht weder einen dauerhaften Preis noch eine bestimmte Zoll- oder Lieferbehandlung."
  ],
  es: [
    "Convierte la revisión en un recorrido continuo y no en una colección de primeros planos aislados. Empieza por la fuente activa, anota la opción elegida y relaciona cada fotografía de almacén con ese punto de partida. Después crea una lista de áreas decisivas: identidad, cobertura, forma general, elementos simétricos, construcción, medidas y componentes incluidos. Para cada área registra una observación visible, una ausencia de información o una solicitud concreta. En calzado deben leerse juntos ambos laterales, frente, talón, vista superior, suela, etiqueta y medición clara. En ropa deben combinarse frente, espalda, etiquetas, gráfico, bajo, puños, bolsillos, herrajes y medidas planas. Ninguna imagen debe dominar fuera de esta cadena. Un ángulo atractivo puede ocultar la forma; un zoom extremo puede exagerar fibras inocuas; una regla inclinada puede producir una cifra falsa con aspecto preciso. Confirma detalles en dos perspectivas, busca referencias neutrales de color y separa hechos de conclusiones. Escribe primero ‘la costura del bolsillo izquierdo termina más arriba’ y decide después si es cosmético, funcional o una especificación incorrecta. Si existen varios registros históricos, busca patrones repetidos solo después de confirmar enlace, opción y periodo. La repetición aporta contexto, pero no garantiza el siguiente lote. Antes de aprobar, otra persona debería poder reproducir tu razonamiento usando las notas sin inventar información. Finaliza con acción, motivo e incertidumbre restante. Así el QC reduce riesgo de forma documentada sin convertirse en promesa de autenticidad, calidad total o entrega.",
    "Trata la búsqueda como una investigación reproducible, no como una sucesión infinita de miniaturas atractivas. Conserva URL directa, destino final, mercado, ID, opción, título visible y fecha. Empieza con el identificador más fuerte. Con un enlace activo, compara destino, imagen principal, miniaturas de opción, construcción, color, componentes e identificador antes de aceptar una coincidencia. Si algunos puntos encajan pero queda una laguna, utiliza ‘probablemente el mismo artículo’ y no ‘exacto’. Cuando el enlace muere, mantiene separado el registro histórico. Prueba después el ID en el mercado correcto, una frase distintiva de material o modelo y, por último, la imagen menos editada. Anota cada cambio de consulta para conocer por qué apareció un candidato. La búsqueda por imagen propone posibilidades, no identidad comercial: recortes, fondos eliminados, otros colores y fotografías reutilizadas pueden simular una coincidencia fuerte. Aplica cuatro niveles: fuente exacta, probablemente igual, visualmente similar y sin verificar. Añade una razón y la siguiente acción. Popularidad, guardados, puntuación del vendedor, hauls o reseñas individuales pueden priorizar la investigación, pero no demuestran identidad. Antes de publicar vuelve a revisar precio, stock, opción y destino. Si una ficha cambia, verifica de nuevo, márcala como histórica o retírala; no reemplaces silenciosamente la URL por un producto parecido. El registro con fecha, captura y justificación protege la relación imagen-enlace y evita mezclar datos.",
    "Gestiona la planificación del envío como versiones de una hoja de cálculo que cambian con cada paso de embalaje. La primera versión contiene cantidad, pesos conocidos y si incluyen cajas comerciales, más un escenario compacto y otro protegido. Es solo un intervalo porque el cartón exterior, los huecos y las protecciones todavía no se han medido. Tras consolidar, introduce masa real y largo, ancho y alto exteriores. Usa exactamente ese paquete terminado para todas las rutas y registra por línea divisor, unidades, redondeo, mínimo, incremento, límites, artículos restringidos, recargos, seguimiento y seguro. Calcula volumen únicamente con la regla actual y comprueba si cada lado se redondea antes de multiplicar. Elimina rutas no elegibles antes de comparar precios. Una tarifa menor por kilo puede terminar siendo más cara por mínimos o volumen. Valora cada cambio de embalaje según producto: una prenda blanda no necesita la misma estructura que zapatos, figuras delicadas o componentes móviles. Retirar cajas es una decisión entre volumen, protección y presentación. Si la medida final difiere mucho, revisa unidades, cantidad, dimensiones, embalaje retirado y servicios y solicita nueva medición cuando sea posible. Aduana, impuestos, declaración y legalidad se comprueban por separado con normas actuales. Guarda fecha y regla; cualquier reembalaje o cambio de ruta exige recalcular. De ese modo el artículo enseña un método verificable y no promete precio, aduana o entrega permanentes."
  ],
  fr: [
    "Transformez le contrôle en parcours continu plutôt qu’en collection de gros plans isolés. Partez de la source active, notez l’option choisie et rattachez chaque photo d’entrepôt à ce point de départ. Dressez ensuite la liste des zones décisives : identité, couverture, forme générale, éléments symétriques, fabrication, mesures et contenu. Pour chaque zone, inscrivez une observation visible, une information absente ou une demande précise. Pour des chaussures, les deux côtés, l’avant, le talon, le dessus, la semelle, l’étiquette et une mesure claire doivent être lus ensemble. Pour un vêtement, réunissez devant, dos, étiquettes, motif, ourlet, poignets, poches, pièces et mesures à plat. Aucune image ne doit dominer hors de cette chaîne. Un angle séduisant peut masquer la forme, un zoom extrême exagérer une fibre et une règle inclinée produire un chiffre faux mais précis en apparence. Confirmez sous deux perspectives, utilisez des références de couleur neutres et séparez faits et conclusions. Écrivez d’abord ‘la couture de la poche gauche se termine plus haut’, puis classez l’écart. Avec plusieurs dossiers historiques, cherchez les répétitions seulement après avoir vérifié lien, option et période. La répétition apporte du contexte sans garantir la prochaine série. Une seconde personne doit pouvoir reproduire la décision à partir des notes. Concluez par action, raison et incertitude restante, sans promesse d’authenticité, de qualité totale ou de livraison.",
    "Traitez la recherche comme une enquête reproductible, pas comme une suite infinie de miniatures attrayantes. Conservez URL directe, destination finale, place de marché, identifiant, option, titre visible et date. Commencez par le repère le plus fort. Avec un lien actif, comparez destination, image principale, miniatures d’option, construction, couleur, contenu et identifiant avant de conclure. Si plusieurs éléments concordent mais qu’une lacune demeure, utilisez ‘probablement le même article’ et non ‘exact’. Quand le lien disparaît, gardez le dossier historique séparé. Essayez ensuite l’identifiant dans le bon contexte, une expression distinctive de matière ou de modèle, puis l’image la moins modifiée. Notez chaque changement de requête afin de savoir pourquoi un candidat est apparu. La recherche par image propose des possibilités, pas une identité commerciale : recadrages, fonds supprimés, autres coloris et photos réutilisées peuvent simuler une forte correspondance. Appliquez quatre niveaux : source exacte, probablement identique, visuellement proche et non vérifié, avec raison et action suivante. Popularité, favoris, score vendeur, hauls ou avis individuels peuvent orienter l’ordre de recherche sans prouver l’identité. Avant publication, revérifiez prix, stock, option et destination. Si la fiche change, contrôlez, marquez historique ou retirez ; ne remplacez jamais silencieusement par un produit proche. Le journal daté protège la relation image-lien et évite les dossiers mélangés.",
    "Gérez la préparation d’expédition comme des versions successives d’une feuille de calcul. La première contient quantité, poids connus, présence des boîtes et deux scénarios, compact et protégé. Elle reste une fourchette, car carton extérieur, espaces et protections ne sont pas encore mesurés. Après consolidation, ajoutez masse réelle et longueur, largeur, hauteur externes. Utilisez exactement ce colis fini pour toutes les lignes et relevez diviseur, unités, arrondi, minimum, incrément, limites, articles restreints, suppléments, suivi et assurance. Calculez le volume uniquement avec la règle actuelle et vérifiez si chaque côté est arrondi avant multiplication. Éliminez les lignes non admissibles avant de comparer les prix. Un tarif au kilo inférieur peut coûter davantage après minimum ou volume. Évaluez l’emballage selon l’article : un textile souple n’a pas besoin de la même structure que des chaussures, une figurine fragile ou des pièces mobiles. Retirer une boîte arbitre entre volume, protection et présentation. Si la mesure finale s’écarte fortement, contrôlez unités, quantité, dimensions, emballage retiré et services, puis demandez une nouvelle mesure si possible. Douane, taxes, déclaration et légalité restent séparées et fondées sur les règles actuelles. Conservez date et règle ; tout réemballage ou changement de ligne impose un nouveau calcul. L’article enseigne ainsi une méthode vérifiable sans promettre prix, douane ou livraison."
  ],
  it: [
    "Trasforma il controllo in un percorso continuo e non in una raccolta di primi piani isolati. Parti dalla fonte attiva, annota l’opzione scelta e collega ogni foto di magazzino a quel punto di partenza. Crea poi un elenco delle aree decisive: identità, copertura, forma generale, elementi simmetrici, costruzione, misure e componenti. Per ogni area registra un’osservazione visibile, un’informazione mancante o una richiesta precisa. Per le scarpe vanno letti insieme entrambi i lati, davanti, tallone, vista dall’alto, suola, etichetta e misura chiara. Per l’abbigliamento combina davanti, dietro, etichette, grafica, orlo, polsini, tasche, hardware e misure piatte. Nessuna immagine deve dominare fuori da questa catena. Un angolo attraente può nascondere la forma, uno zoom estremo può ingigantire una fibra innocua e un righello inclinato può produrre un numero falso ma apparentemente preciso. Conferma da due prospettive, cerca riferimenti cromatici neutrali e separa fatti e conclusioni. Scrivi prima ‘la cucitura della tasca sinistra termina più in alto’ e poi valuta la gravità. Con più record storici cerca ripetizioni solo dopo aver verificato link, opzione e periodo. La ripetizione aggiunge contesto senza garantire il lotto successivo. Una seconda persona deve poter ricostruire la decisione dalle note. Chiudi con azione, motivo e incertezza residua, senza promettere autenticità, qualità totale o consegna.",
    "Tratta la ricerca come un’indagine riproducibile, non come una sequenza infinita di miniature interessanti. Conserva URL diretto, destinazione finale, marketplace, ID, opzione, titolo visibile e data. Inizia dall’identificatore più forte. Con un link attivo confronta destinazione, immagine principale, miniature delle opzioni, costruzione, colore, contenuto e ID prima di dichiarare un match. Se alcuni elementi coincidono ma resta una lacuna, usa ‘probabilmente lo stesso articolo’ e non ‘esatto’. Quando il link muore, mantieni separato il record storico. Prova poi l’ID nel contesto corretto, una frase distintiva di materiale o modello e infine l’immagine meno modificata. Annota ogni cambio di query per capire perché è apparso un candidato. La ricerca per immagine propone possibilità, non identità commerciale: ritagli, sfondi rimossi, altri colori e foto riutilizzate possono simulare una forte corrispondenza. Applica quattro livelli: fonte esatta, probabilmente uguale, visivamente simile e non verificato, con motivo e passo successivo. Popolarità, salvataggi, punteggio venditore, haul o singole recensioni possono ordinare la ricerca, ma non provano l’identità. Prima di pubblicare ricontrolla prezzo, stock, opzione e destinazione. Se la scheda cambia, verifica, segnala come storica o rimuovi; non sostituire in silenzio con un prodotto simile. Il registro datato protegge il rapporto immagine-link ed evita dati mescolati.",
    "Gestisci la pianificazione della spedizione come versioni successive di un foglio di calcolo. La prima contiene quantità, pesi noti, presenza delle scatole e due scenari, compatto e protetto. Rimane un intervallo perché cartone esterno, spazi e protezioni non sono ancora misurati. Dopo il consolidamento inserisci massa reale e lunghezza, larghezza e altezza esterne. Usa esattamente quel pacco finito per tutte le rotte e registra divisore, unità, arrotondamento, minimo, incremento, limiti, articoli ristretti, supplementi, tracking e assicurazione. Calcola il volume soltanto con la regola attuale e verifica se ogni lato viene arrotondato prima della moltiplicazione. Elimina le rotte non idonee prima di confrontare i prezzi. Una tariffa al chilo inferiore può costare di più dopo minimi o volume. Valuta l’imballaggio in base all’articolo: un tessuto morbido non richiede la stessa struttura di scarpe, figure fragili o parti mobili. Rimuovere una scatola bilancia volume, protezione e presentazione. Se la misura finale differisce molto, controlla unità, quantità, dimensioni, imballaggio rimosso e servizi e chiedi una nuova misura quando possibile. Dogana, tasse, dichiarazione e legalità restano controlli separati basati su regole attuali. Salva data e regola; ogni reimballaggio o cambio di rotta richiede un nuovo calcolo. L’articolo insegna così un metodo verificabile senza promettere prezzo, dogana o consegna."
  ]
};

const articleParityTail = {
  de: ["", "Behalte zusätzlich eine klare Stoppregel: Wenn weder aktive Quelle noch Option belastbar bestätigt werden können, endet die Aufgabe als Alternativensuche. Mehr ähnliche Ergebnisse erhöhen die Sicherheit nicht automatisch. Sie können andere Verkäufer, Varianten oder Zeiträume mischen. Ein transparent ungeklärter Status ist redaktionell stärker als eine exakte Behauptung, die nur durch die Menge ähnlicher Bilder überzeugend wirkt.", ""],
  es: ["", "", ""],
  fr: ["", "Ajoutez enfin une règle d’arrêt : sans source active ni option vérifiable, la tâche devient une recherche d’alternatives. Davantage de résultats proches n’augmente pas automatiquement la confiance et peut mélanger vendeurs, versions ou périodes. Un statut ouvert clairement indiqué vaut mieux qu’une correspondance exacte fabriquée par accumulation d’images similaires.", ""],
  it: ["Prima della decisione assegna a ogni area critica uno stato esplicito: verificata, incerta o non visibile. Questa distinzione impedisce che una fotografia mancante venga interpretata come assenza di difetto e rende chiaro quale controllo aggiuntivo può cambiare davvero l’azione finale.", "Mantieni anche una regola di arresto. Se non è possibile confermare una fonte attiva e l’opzione esatta, trasforma il compito in ricerca di alternative. Aggiungere molti risultati simili non aumenta automaticamente la fiducia: può mescolare venditori, versioni, colorazioni e periodi differenti. Conserva query, ID, destinazione e data per ogni candidato e spiega perché è stato accettato o scartato. Quando un risultato rimane ambiguo, usa l’etichetta non verificato invece di continuare finché appare una miniatura convincente. Un esito trasparente e incompleto è più utile di una corrispondenza esatta costruita sommando immagini che non condividono una provenienza dimostrabile.", "Dopo ogni preventivo annota inoltre quali dati erano misurati e quali soltanto stimati. Se il pacco, la protezione o la rotta cambiano, invalida il totale precedente e crea una nuova versione datata. Questa disciplina evita che un calcolo corretto per uno scenario venga riutilizzato come prezzo promesso per un pacco diverso."]
};

const globalArticleTail = {
  de: ["Ordne abschließend jede Aussage einer sichtbaren Quelle, einer Messung oder einer ausdrücklich genannten Unsicherheit zu. Diese letzte Redaktion verhindert, dass praktische Beobachtungen beim Schreiben zu absoluten Qualitätsurteilen werden. Sie verbessert zugleich die Lesbarkeit, weil der Nutzer sofort erkennt, welche Information überprüft wurde, welche noch fehlt und welche konkrete Handlung aus dem Befund folgt.", "Prüfe vor dem Speichern außerdem, ob Titel, Bild, Option und Ziel-URL dieselbe Identität beschreiben. Ein Treffer darf nicht nur innerhalb des Suchsystems plausibel wirken, sondern muss auf der geöffneten Zielseite nachvollziehbar bleiben. Notiere Veränderungen mit Datum, damit eine spätere Korrektur den ursprünglichen Rechercheweg nicht löscht und historische Daten klar von aktuellen Angaben getrennt bleiben.", "Führe zum Schluss eine Plausibilitätskontrolle durch: Passt die gemessene Masse zur Artikelzahl, passen die Außenmaße zum Verpackungsfoto und ist die gewählte Linie für Ziel und Inhalt wirklich verfügbar? Erst wenn diese Fragen beantwortet sind, wird aus der frühen Spanne eine belastbare Planung. Unbekannte Gebühren oder Regeln bleiben markiert und werden nicht durch Schätzwerte ersetzt."],
  es: ["Relaciona al final cada afirmación con una imagen visible, una medición o una incertidumbre declarada. Esta última revisión impide que observaciones prácticas se conviertan al redactar en juicios absolutos de calidad. También mejora la lectura porque muestra de inmediato qué se comprobó, qué falta y qué acción concreta se deriva del hallazgo.", "Antes de guardar, comprueba que título, imagen, opción y URL final describan la misma identidad. El resultado no solo debe parecer plausible dentro del buscador, sino seguir siendo verificable en la página abierta. Registra los cambios con fecha para que una corrección futura no borre el recorrido original y los datos históricos permanezcan separados de la información actual.", "Termina con una comprobación de plausibilidad: ¿coincide la masa con la cantidad, corresponden las dimensiones con la fotografía del embalaje y la línea está disponible para destino y contenido? Solo entonces el rango inicial se convierte en planificación útil. Tasas o reglas desconocidas permanecen marcadas y no se sustituyen por números inventados."],
  fr: ["Rattachez enfin chaque affirmation à une image visible, une mesure ou une incertitude déclarée. Cette dernière révision empêche des observations pratiques de devenir, lors de la rédaction, des jugements absolus de qualité. Elle améliore aussi la lecture en montrant immédiatement ce qui est vérifié, ce qui manque et l’action concrète qui découle du constat.", "Avant d’enregistrer, vérifiez que titre, image, option et URL finale décrivent la même identité. Le résultat doit rester vérifiable sur la destination ouverte, pas seulement sembler plausible dans le moteur. Datez les modifications afin qu’une correction future ne supprime pas le parcours d’origine et que les données historiques restent séparées des informations actuelles.", "Terminez par un contrôle de plausibilité : la masse correspond-elle au nombre d’articles, les dimensions à la photo d’emballage et la ligne au contenu ainsi qu’à la destination ? Ce n’est qu’alors que la première fourchette devient une planification utile. Les frais ou règles inconnus restent signalés et ne sont pas remplacés par des chiffres inventés."],
  it: ["Collega infine ogni affermazione a un’immagine visibile, una misura o un’incertezza dichiarata. Questa revisione impedisce che osservazioni pratiche diventino durante la scrittura giudizi assoluti di qualità. Migliora anche la lettura perché mostra subito cosa è stato verificato, cosa manca e quale azione concreta deriva dal risultato.", "Prima di salvare controlla che titolo, immagine, opzione e URL finale descrivano la stessa identità. Il risultato deve restare verificabile sulla destinazione aperta, non solo apparire plausibile nel motore. Data le modifiche affinché una correzione futura non cancelli il percorso originale e i dati storici restino separati dalle informazioni attuali.", "Concludi con un controllo di plausibilità: la massa corrisponde al numero di articoli, le dimensioni alla foto dell’imballaggio e la rotta è davvero disponibile per destinazione e contenuto? Solo allora l’intervallo iniziale diventa pianificazione utile. Costi o regole ignoti restano segnalati e non vengono sostituiti con numeri inventati."]
};

const exactArticleTail = {
  de: ["Dokumentiere dabei auch die konkrete Bildnummer oder Perspektive, auf die sich jede Beobachtung bezieht. Das verhindert, dass spätere Leser eine Aussage einem anderen Winkel oder einer anderen Variante zuordnen und macht Zusatzprüfungen wesentlich gezielter.", "Verknüpfe den veröffentlichten Treffer anschließend nur mit Seiten, die eine andere nächste Aufgabe lösen: QC lesen, Maße prüfen, Kategorie öffnen oder Paket planen. Dadurch bleibt die Suchseite auf Identität und Auffindbarkeit fokussiert, während andere Suchabsichten eigene vollständige Seiten behalten. Prüfe interne Links bei jeder Zieländerung mit, damit kein alter Anker zu einer neu etikettierten oder entfernten Karte führt.", "Bewahre zusätzlich die ursprüngliche und die endgültige Messversion getrennt auf. So ist sichtbar, welche Annahmen vor der Konsolidierung galten und welche Werte später tatsächlich gemessen wurden. Das verhindert, dass ein frühes Artikelgewicht oder geschätztes Volumen versehentlich als fertige Paketangabe erscheint, und erleichtert die Erklärung jeder Differenz im veröffentlichten Text."],
  es: ["", "Enlaza después el resultado solo con páginas que resuelvan una tarea siguiente diferente: leer QC, comprobar medidas, abrir categoría o planificar paquete. Así la página de búsqueda mantiene su intención de identidad y descubrimiento, mientras otras preguntas conservan páginas completas propias. Revisa también los enlaces internos cuando cambie un destino para que ninguna ancla antigua conduzca a una tarjeta reclasificada o retirada.", "Conserva por separado la versión inicial y la medición final. De este modo se ve qué supuestos existían antes de consolidar y qué cifras se midieron después, evitando que un peso de producto o volumen estimado aparezca por error como dato del paquete terminado."],
  fr: ["Indiquez aussi le numéro d’image ou l’angle précis associé à chaque observation. Cela empêche qu’un lecteur ultérieur rattache la remarque à une autre vue ou variante et rend toute demande complémentaire beaucoup plus ciblée.", "Reliez ensuite le résultat uniquement à des pages qui résolvent une autre étape : lire le QC, vérifier les mesures, ouvrir la catégorie ou préparer le colis. La page de recherche reste ainsi centrée sur identité et découverte, tandis que les autres intentions disposent de guides complets. Revérifiez également les liens internes lorsqu’une destination change afin qu’aucune ancienne ancre ne mène vers une carte reclassée ou retirée.", "Conservez séparément la version initiale et la mesure finale. On distingue ainsi les hypothèses avant consolidation des chiffres réellement obtenus ensuite. Cette séparation empêche qu’un poids produit ou un volume estimé soit présenté par erreur comme donnée du colis terminé et permet d’expliquer clairement tout écart dans le texte publié."],
  it: ["Indica anche il numero dell’immagine o l’angolo preciso a cui si riferisce ogni osservazione. In questo modo un lettore successivo non collegherà la nota a una vista o variante diversa e ogni richiesta aggiuntiva potrà essere formulata con maggiore precisione. Conserva inoltre la data del set fotografico e distingui immagini dirette, record storici e risultati simili, così il riepilogo finale mantiene separati i diversi livelli di prova.", "Collega poi il risultato soltanto a pagine che risolvono un passo successivo diverso: leggere il QC, controllare misure, aprire la categoria o pianificare il pacco. La pagina di ricerca resta concentrata su identità e scoperta, mentre gli altri intenti mantengono guide complete. Ricontrolla i link interni ogni volta che cambia una destinazione affinché nessuna vecchia ancora porti a una scheda riclassificata o rimossa. Registra anche chiave di ricerca e motivo del match per rendere ripetibile il percorso.", "Conserva separatamente la versione iniziale e la misura finale. In questo modo è chiaro quali ipotesi esistevano prima del consolidamento e quali valori sono stati misurati in seguito. La separazione impedisce che peso del prodotto o volume stimato vengano presentati per errore come dati del pacco terminato. Annota anche foto, imballaggio, unità e data della rotta, così ogni differenza può essere spiegata e ricalcolata senza trasformare una vecchia stima in una promessa attuale."]
};

const visualArticleTail = {
  de: ["Prüfe vor dem Abschluss auch, ob die Bildreihenfolge den Artikel vollständig abdeckt und ob sich eine Beobachtung auf das linke oder rechte Teil, die Vorder- oder Rückseite und die tatsächlich gewählte Variante bezieht. Halte den Unterschied zwischen sichtbarer Abweichung und vermuteter Ursache fest. So bleibt der Text auch für Leser verständlich, die das Produkt nicht kennen, und eine Nachforderung kann genau den fehlenden Bereich statt eines weiteren allgemeinen Fotos ansprechen.", "Halte bei jedem Kandidaten zusätzlich fest, welche stärkere Kennung noch fehlt und wodurch sie ersetzt werden könnte. Ein fehlender Quelllink kann möglicherweise durch eine bestätigte Artikel-ID ergänzt werden, eine unklare Option durch passende Variantenbilder und eine alte Seite durch eine neue aktive Quelle. Bleibt diese Lücke offen, ändert mehr Suchvolumen nichts am Match-Level. Diese explizite Lückenanalyse verhindert, dass lange Recherche automatisch mit hoher Sicherheit verwechselt wird, und macht die veröffentlichte Einordnung für Leser und spätere Aktualisierungen nachvollziehbar.", "Kontrolliere in der finalen Version außerdem, ob Maße und Gewicht mit derselben Paketstufe verknüpft sind. Ein fertiger Außenkarton darf nicht mit Produktmaßen oder einem Lagereingangsgewicht kombiniert werden. Notiere zu jeder Route, wann sie geprüft wurde und für welches Ziel sie galt. Wenn ein Wert nur als Beispiel dient, kennzeichne ihn als Rechenweg und nicht als aktuellen Preis. Diese letzte Trennung hält die Anleitung praktisch, ohne wechselnde Routenbedingungen in dauerhafte Aussagen umzuwandeln."],
  es: ["", "Registra también qué identificador fuerte sigue faltando y con qué prueba podría sustituirse. Un enlace ausente puede complementarse con un ID confirmado, una opción poco clara con miniaturas coherentes y una página antigua con una nueva fuente activa. Si la laguna continúa, más resultados no elevan el nivel. Explicar esta carencia evita confundir una búsqueda larga con alta certeza y facilita futuras actualizaciones.", "Comprueba además que dimensiones y peso pertenecen a la misma fase del paquete. No combines cartón terminado con medidas de producto o peso de entrada. Anota fecha y destino de cada ruta. Si una cifra solo ilustra el método, preséntala como ejemplo y no como precio actual, manteniendo separadas la enseñanza y la cotización."],
  fr: ["Avant de conclure, vérifiez que l’ordre des images couvre réellement l’article et que chaque remarque désigne le côté, la face et l’option concernés. Distinguez l’écart visible de sa cause supposée. Le texte reste ainsi compréhensible pour un lecteur qui ne connaît pas le produit et toute demande supplémentaire vise la zone manquante plutôt qu’une nouvelle photo générale.", "Notez aussi quel identifiant fort manque encore et quelle preuve pourrait le remplacer. Un lien absent peut parfois être complété par un ID confirmé, une option floue par des miniatures cohérentes et une ancienne page par une nouvelle source active. Si la lacune demeure, davantage de résultats n’augmente pas le niveau de correspondance. Cette analyse évite de confondre recherche longue et forte certitude.", "Vérifiez enfin que dimensions et poids appartiennent à la même étape du colis. Ne combinez pas carton terminé avec mesures produit ou poids d’entrée. Datez chaque ligne et précisez la destination. Si une valeur illustre seulement la méthode, présentez-la comme exemple et non comme prix actuel afin de séparer clairement apprentissage et devis."],
  it: ["Prima di concludere verifica che l’ordine delle immagini copra davvero l’articolo e che ogni nota indichi lato, fronte o retro e opzione interessata. Separa la differenza visibile dalla causa ipotizzata. Il testo resta così chiaro anche per chi non conosce il prodotto e ogni richiesta aggiuntiva può mirare alla zona mancante invece di ottenere un’altra fotografia generica.", "Annota anche quale identificatore forte manca ancora e quale prova potrebbe sostituirlo. Un link assente può essere integrato da un ID confermato, un’opzione poco chiara da miniature coerenti e una vecchia pagina da una nuova fonte attiva. Se la lacuna rimane, più risultati non aumentano il livello di match. Questa analisi evita di confondere una ricerca lunga con alta certezza e rende più semplici gli aggiornamenti futuri.", "Controlla infine che dimensioni e peso appartengano alla stessa fase del pacco. Non combinare il cartone terminato con misure del prodotto o peso d’ingresso. Data ogni rotta e indica la destinazione. Se un valore serve soltanto a mostrare il metodo, presentalo come esempio e non come prezzo attuale, separando chiaramente istruzione e preventivo."]
};

export const pageParityTail = {
  en: { finds: "", categories: "", qc: "", shipping: "", articles: "" },
  de: { finds: "Prüfe zusätzlich, ob der aktuelle Zieltext noch dieselbe Variante beschreibt und ob alle internen Verweise weiterhin auf die verifizierte Seite führen. Diese Kontrolle hält das Verzeichnis auch nach späteren Angebotsänderungen konsistent. Notiere bei jeder erneuten Prüfung, ob Bild, Preis, Option und Verfügbarkeit unverändert, aktualisiert oder nicht mehr nachweisbar sind. Dadurch bleibt auch die Startseite in der deutschen Version vollständig und erklärt nicht nur den Fund, sondern ebenso seinen Wartungsstatus und den nächsten sinnvollen Schritt.", categories: "", qc: "", shipping: "Speichere außerdem das Datum jedes Angebots und markiere unbekannte Gebühren deutlich. So bleibt eine Methode auch dann korrekt, wenn eine konkrete Linie später andere Werte verwendet. Rechne nach jeder Änderung erneut.", articles: "Ein regelmäßiger Faktencheck entscheidet, ob eine Seite aktualisiert, historisch gekennzeichnet oder entfernt werden muss. Die Entscheidung wird mit Datum dokumentiert." },
  es: { finds: "", categories: "", qc: "", shipping: "Registra también la fecha de cada cotización y marca claramente tarifas desconocidas para que el método siga siendo correcto cuando cambie una línea.", articles: "" },
  fr: { finds: "", categories: "", qc: "", shipping: "Datez également chaque devis et signalez clairement les frais inconnus afin que la méthode reste valable lorsque la ligne évolue.", articles: "" },
  it: { finds: "Controlla inoltre che il testo della destinazione descriva ancora la stessa variante e che i link interni portino alla pagina verificata. Questo mantiene coerente il catalogo dopo cambiamenti successivi.", categories: "", qc: "Una nota finale deve indicare quale prova manca ancora e se può cambiare la decisione.", shipping: "Registra anche la data di ogni preventivo e segnala chiaramente i costi ignoti, così il metodo resta valido quando una rotta cambia.", articles: "Un controllo periodico decide se aggiornare, segnare come storica o rimuovere una pagina." }
};

export const legalParityBoost = {
  en: { privacy: "", terms: "" },
  de: { privacy: "Diese Vorschau speichert keine Benutzerkonten oder Zahlungsdaten. Beim Öffnen externer Ziele gelten deren eigene Datenschutzregeln; prüfe sie, bevor du persönliche Angaben eingibst. Suchbegriffe werden erst beim Absenden an das externe Ziel übergeben.", terms: "Alle Inhalte dienen der unabhängigen Recherche. Bilder, Preise, Bestand, Gewicht, Maße, Versand und historische Datensätze können sich ändern oder von Dritten stammen. Prüfe Live-Quelle, Route und geltendes Zielrecht vor einer Entscheidung." },
  es: { privacy: "La vista previa no guarda cuentas ni datos de pago. Los destinos externos aplican sus propias políticas; revísalas antes de introducir información personal. La consulta solo se envía cuando ejecutas la búsqueda.", terms: "El contenido sirve para investigación independiente. Imágenes, precios, stock, peso, medidas, envío y registros históricos pueden cambiar o proceder de terceros. Verifica fuente activa, ruta y normativa del destino antes de decidir." },
  fr: { privacy: "Cette préversion ne conserve ni compte ni paiement. Les destinations externes appliquent leurs propres règles ; consultez-les avant de saisir des données personnelles. La requête n’est transmise qu’au lancement de la recherche.", terms: "Le contenu sert à la recherche indépendante. Images, prix, stock, poids, dimensions, expédition et historiques peuvent évoluer ou venir de tiers. Vérifiez source active, ligne et droit de destination avant toute décision." },
  it: { privacy: "L’anteprima non conserva account o dati di pagamento. Le destinazioni esterne applicano regole proprie; consultale prima di inserire dati personali. La query viene trasmessa solo quando avvii la ricerca.", terms: "Il contenuto serve alla ricerca indipendente. Immagini, prezzi, stock, peso, misure, spedizione e record storici possono cambiare o provenire da terzi. Verifica fonte attiva, rotta e regole della destinazione prima di decidere." }
};

export const pageParityBoost = {
  en: {
    finds: "Use the directory to narrow candidates, then verify the exact destination, option and date. Historical evidence and visual similarity remain separate confidence levels.",
    categories: "A category organizes product-specific checks. It does not prove identity, current stock or quality without an exact live listing and relevant evidence.",
    qc: "A complete review records what is visible, what is missing, how confident the observation is and which warehouse action follows.",
    shipping: "Keep early estimates separate from the finished parcel. Recalculate with the current eligible route after every packing or measurement change.",
    articles: "Each guide answers one task, keeps changing facts time-stamped and links to the next useful verification step."
  },
  de: {
    finds: "Nutze das Verzeichnis zuerst zur Eingrenzung und öffne anschließend die genaue Zielseite. Vergleiche Hauptbild, sichtbare Konstruktion, Option, Artikelkennung und Prüfdatum. Ein historischer QC-Datensatz kann zeigen, wie eine frühere Einheit aussah, bestätigt aber weder aktuellen Bestand noch eine gleiche neue Charge. Ein visuell ähnlicher Treffer bleibt eine Entdeckungshilfe, bis Quelle und Option belastbar zusammenpassen. Halte deshalb exakte Quelle, wahrscheinlich gleich, visuell ähnlich und ungeprüft getrennt. Speichere bei jedem Fund Ziel, Option, Datum und einen kurzen Grund. Wird eine Seite entfernt, umgeleitet oder geändert, verifiziere neu, kennzeichne sie als historisch oder entferne die Karte. Ein überzeugendes Vorschaubild darf nie wichtiger sein als das tatsächlich geöffnete Angebot.",
    categories: "Eine Kategorie ordnet unterschiedliche Prüfprioritäten, beweist jedoch keine Produktidentität. Bei Schuhen stehen Form, Paarvergleich, Sohlenverbindung und Länge im Vordergrund; bei Kleidung flache Maße, Stoff, Druck, Nähte und Beschläge; bei Accessoires Kanten, Verschlüsse, bewegliche Teile und Lieferumfang. Speichere immer den genauen Quelllink, die ausgewählte Option und das Prüfdatum. Titel, Vorschaubild, Preis und Bestand können sich ändern, während alte Bilder anderswo sichtbar bleiben. Aufrufe, Trends oder Bewertungen helfen bei der Auswahl dessen, was zuerst untersucht wird, ersetzen aber weder exakten Match noch vollständige Bildabdeckung. Öffne deshalb nach der Kategorie immer das aktive Einzelangebot und trenne Entdeckung, Beleg und Kaufentscheidung.",
    qc: "Eine vollständige Prüfung dokumentiert nicht nur gefundene Mängel, sondern auch fehlende Perspektiven und die Sicherheit jeder Aussage. Beginne mit Identität und Option, kontrolliere anschließend Abdeckung, Gesamtform, wiederholte Elemente, Verarbeitung, Maße und Lieferumfang. Beschreibe Sichtbares neutral, bevor du es als kosmetisch, funktional oder falsche Spezifikation einordnest. Licht, Perspektive und Kompression können Farbe und Proportionen verändern, deshalb werden wichtige Punkte aus mindestens zwei Blickwinkeln bestätigt. Wenn ein Bereich fehlt, lautet der Status ‘nicht sichtbar’ und nicht ‘fehlerfrei’. Schließe mit Versand, Zusatzfoto, Umtausch oder Rückgabe sowie einem kurzen Grund. QC bleibt damit ein nachvollziehbarer Beleg für eine dokumentierte Einheit und keine Echtheits-, Haltbarkeits- oder Liefergarantie.",
    shipping: "Trenne Artikelgewicht, Lagereingangsgewicht und fertiges konsolidiertes Paket. Notiere zu jeder Zahl, ob Verkaufsverpackung, Außenkarton und Schutz enthalten sind. Vor der Konsolidierung ist nur eine Spanne sinnvoll; nach dem Packen werden tatsächliche Masse sowie äußere Länge, Breite und Höhe erneut geprüft. Wende Divisor, Einheit, Rundung, Mindestbetrag und Größenlimits der aktuell gewählten Route an und vergleiche dasselbe Endpaket über alle zulässigen Linien. Berücksichtige Zuschläge, eingeschränkte Artikel, Tracking und Versicherung. Jede entfernte Box, zusätzliche Schutzlage oder neue Route kann das Ergebnis ändern und verlangt eine Neuberechnung. Zoll, Steuern und Einfuhrrecht bleiben eine getrennte Kontrolle anhand aktueller offizieller Ziel- und Carrier-Regeln.",
    articles: "Jeder Leitfaden beantwortet eine klar abgegrenzte Aufgabe statt denselben Hauptbegriff auf mehreren Seiten zu wiederholen. Die Artikel zeigen überprüfbare Schritte: Quelle sichern, Option vergleichen, Bildabdeckung prüfen, Maße einordnen, Paket neu berechnen und Entscheidung dokumentieren. Veränderliche Angaben wie Preis, Bestand, Rückgabefrist oder Routenregel werden als zeitgebunden behandelt und vor einer Aktualisierung erneut geprüft. Interne Links führen zum nächsten sinnvollen Arbeitsschritt, nicht nur zu einer weiteren Seite mit demselben Keyword. Kundenstimmen werden von Plattformfakten getrennt und einzelne öffentliche Beiträge ausdrücklich als Anekdoten behandelt. Dadurch bleibt der Inhalt nützlich, nachvollziehbar und redaktionell wartbar."
  },
  es: {
    finds: "Utiliza el directorio para reducir candidatos y después abre el destino exacto. Compara imagen principal, construcción visible, opción, identificador y fecha. Un QC histórico muestra una unidad anterior, pero no confirma stock ni lote nuevo idéntico. Un resultado visualmente parecido sigue siendo descubrimiento hasta que fuente y opción coincidan. Mantén separados fuente exacta, probablemente igual, visualmente similar y sin verificar. Guarda destino, opción, fecha y motivo. Si la página cambia, vuelve a verificar, marca como histórica o retira la tarjeta. Una miniatura convincente nunca debe pesar más que la ficha realmente abierta.",
    categories: "Una categoría organiza prioridades distintas, pero no demuestra identidad. En calzado importan forma, comparación del par, unión de suela y longitud; en ropa, medidas planas, tejido, impresión, costuras y herrajes; en accesorios, bordes, cierres, piezas móviles y contenido. Guarda enlace exacto, opción y fecha. Título, miniatura, precio y stock pueden cambiar mientras una imagen antigua permanece visible. Vistas, tendencias o reseñas ayudan a decidir qué investigar primero, pero no sustituyen coincidencia exacta ni cobertura QC completa. Después de explorar una categoría abre siempre la ficha activa y separa descubrimiento, prueba y decisión.",
    qc: "Una revisión completa documenta defectos, ángulos ausentes y confianza. Empieza por identidad y opción; sigue con cobertura, forma, elementos repetidos, construcción, medidas y componentes. Describe lo visible antes de clasificarlo como cosmético, funcional o especificación incorrecta. Luz, perspectiva y compresión alteran color y proporciones, por lo que los puntos importantes se confirman en dos vistas. Si falta una zona, marca ‘no visible’, no ‘perfecta’. Termina con enviar, pedir foto, cambiar o devolver y escribe el motivo. Así el QC sigue siendo evidencia rastreable de una unidad documentada, no garantía de autenticidad, duración o entrega.",
    shipping: "Separa peso del artículo, entrada de almacén y paquete consolidado. Anota si cada cifra incluye caja comercial, cartón exterior y protección. Antes de consolidar solo existe un rango; después revisa masa real y dimensiones exteriores. Aplica divisor, unidades, redondeo, mínimo y límites de la ruta activa y compara el mismo paquete en todas las líneas elegibles. Incluye recargos, restricciones, seguimiento y seguro. Cada caja retirada, protección añadida o cambio de ruta exige recalcular. Aduana, impuestos y legalidad se comprueban por separado mediante reglas actuales de destino y transportista.",
    articles: "Cada guía responde una tarea definida y evita repetir el mismo término principal en varias páginas. Explica pasos verificables: conservar fuente, comparar opción, revisar cobertura, interpretar medidas, recalcular el paquete y documentar la decisión. Precio, stock, devoluciones o reglas de ruta se tratan como datos fechados y se revisan antes de actualizar. Los enlaces internos conducen al siguiente trabajo útil, no solo a otra página con la misma palabra. Las experiencias de clientes se separan de hechos de plataforma y cada comentario público individual se presenta como anecdótico."
  },
  fr: {
    finds: "Utilisez le répertoire pour réduire les candidats, puis ouvrez la destination exacte. Comparez image principale, construction visible, option, identifiant et date. Un QC historique montre une unité passée sans confirmer stock ni nouvelle série identique. Un résultat visuellement proche reste une piste tant que source et option ne correspondent pas. Séparez source exacte, probablement identique, visuellement proche et non vérifié. Conservez destination, option, date et raison. Si la page change, revérifiez, marquez historique ou retirez la carte. Une miniature convaincante ne doit jamais peser plus que la fiche réellement ouverte.",
    categories: "Une catégorie organise des priorités sans prouver l’identité. Pour les chaussures : forme, paire, jonction de semelle et longueur ; pour les vêtements : mesures à plat, tissu, impression, coutures et pièces ; pour les accessoires : bords, fermoirs, éléments mobiles et contenu. Gardez lien exact, option et date. Titre, miniature, prix et stock peuvent changer tandis qu’une ancienne image reste visible. Vues, tendances et avis aident à choisir quoi examiner d’abord sans remplacer une correspondance exacte ou une couverture QC complète. Après la catégorie, ouvrez toujours la fiche active et séparez découverte, preuve et décision.",
    qc: "Une revue complète documente défauts, angles absents et niveau de confiance. Commencez par identité et option, puis couverture, forme, éléments répétés, fabrication, mesures et contenu. Décrivez ce qui est visible avant de classer en cosmétique, fonctionnel ou mauvaise spécification. Lumière, perspective et compression modifient couleurs et proportions ; confirmez les points importants dans deux vues. Si une zone manque, écrivez ‘non visible’, pas ‘parfaite’. Terminez par expédier, demander une photo, échanger ou retourner avec la raison. Le QC reste ainsi une preuve traçable d’une unité documentée, non une garantie d’authenticité, de durée ou de livraison.",
    shipping: "Séparez poids produit, entrée entrepôt et colis consolidé. Notez si chaque chiffre comprend boîte commerciale, carton extérieur et protection. Avant consolidation, utilisez une fourchette ; après emballage, contrôlez masse et dimensions externes. Appliquez diviseur, unités, arrondi, minimum et limites de la ligne active, puis comparez le même colis sur toutes les lignes admissibles. Ajoutez suppléments, restrictions, suivi et assurance. Toute boîte retirée, protection ajoutée ou nouvelle ligne impose un recalcul. Douane, taxes et légalité restent un contrôle séparé fondé sur les règles actuelles de destination et de transporteur.",
    articles: "Chaque guide répond à une tâche distincte au lieu de répéter le même terme principal sur plusieurs pages. Il présente des étapes vérifiables : conserver la source, comparer l’option, contrôler la couverture, interpréter les mesures, recalculer le colis et documenter la décision. Prix, stock, retours et règles de ligne sont datés et revérifiés avant mise à jour. Les liens internes conduisent à l’étape utile suivante. Les expériences clients sont séparées des faits de plateforme et chaque commentaire public individuel reste présenté comme anecdotique."
  },
  it: {
    finds: "Usa il catalogo per ridurre i candidati e poi apri la destinazione esatta. Confronta immagine principale, costruzione visibile, opzione, ID e data. Un QC storico mostra un’unità precedente ma non conferma stock o lotto nuovo identico. Un risultato visivamente simile resta scoperta finché fonte e opzione non coincidono. Separa fonte esatta, probabilmente uguale, visivamente simile e non verificato. Salva destinazione, opzione, data e motivo. Se la pagina cambia, ricontrolla, segnala come storica o rimuovi la scheda. Una miniatura convincente non deve mai contare più della pagina realmente aperta.",
    categories: "Una categoria organizza priorità diverse senza provare identità. Per le scarpe contano forma, confronto del paio, unione della suola e lunghezza; per l’abbigliamento misure piatte, tessuto, stampa, cuciture e hardware; per gli accessori bordi, chiusure, parti mobili e contenuto. Conserva link esatto, opzione e data. Titolo, miniatura, prezzo e stock possono cambiare mentre una vecchia immagine rimane visibile. Visite, trend e recensioni aiutano a decidere cosa controllare prima, ma non sostituiscono match esatto o copertura QC completa. Dopo la categoria apri sempre la scheda attiva e separa scoperta, prova e decisione.",
    qc: "Una revisione completa documenta difetti, angoli mancanti e livello di fiducia. Inizia da identità e opzione, poi copertura, forma, elementi ripetuti, costruzione, misure e contenuto. Descrivi ciò che è visibile prima di classificarlo come cosmetico, funzionale o specifica errata. Luce, prospettiva e compressione cambiano colori e proporzioni; conferma i punti importanti in due viste. Se manca una zona, scrivi ‘non visibile’, non ‘perfetta’. Concludi con spedisci, chiedi foto, cambia o restituisci e annota il motivo. Il QC resta così prova tracciabile di un’unità documentata, non garanzia di autenticità, durata o consegna.",
    shipping: "Separa peso del prodotto, ingresso in magazzino e pacco consolidato. Annota se ogni cifra comprende confezione commerciale, cartone esterno e protezione. Prima del consolidamento usa un intervallo; dopo l’imballaggio controlla massa e dimensioni esterne. Applica divisore, unità, arrotondamento, minimo e limiti della rotta attiva e confronta lo stesso pacco su tutte le linee idonee. Includi supplementi, restrizioni, tracking e assicurazione. Ogni scatola rimossa, protezione aggiunta o cambio di rotta richiede un nuovo calcolo. Dogana, tasse e legalità restano un controllo separato basato sulle regole attuali.",
    articles: "Ogni guida risponde a un compito distinto invece di ripetere lo stesso termine principale su più pagine. Presenta passaggi verificabili: salvare fonte, confrontare opzione, controllare copertura, interpretare misure, ricalcolare pacco e documentare decisione. Prezzo, stock, resi e regole di rotta sono datati e ricontrollati prima dell’aggiornamento. I link interni portano al passo utile successivo. Le esperienze clienti restano separate dai fatti della piattaforma e ogni singolo commento pubblico viene indicato come aneddotico."
  }
};

function readableUnits(text) {
  const sentences = text.match(/[^.!?。！？]+(?:[.!?。！？]+|$)/gu)?.map((sentence) => sentence.trim()).filter(Boolean) || [];
  return sentences.flatMap((sentence) => {
    if (sentence.length <= 520) return [sentence];
    const clauses = sentence.split(/(?<=[,;:，；：])\s*/u).map((clause) => clause.trim()).filter(Boolean);
    if (clauses.length > 1) return clauses;
    const words = sentence.split(/\s+/u);
    const chunks = [];
    for (let index = 0; index < words.length; index += 55) chunks.push(words.slice(index, index + 55).join(" "));
    return chunks;
  });
}

export function applyArticleParityBoost(articles, lang, englishArticles) {
  if (lang === "en") return articles;
  return articles.map((article, index) => {
    const sections = article.sections.map((section) => [...section]);
    const extra = `${articleParityBoost[lang][index]} ${articleParityTail[lang][index]} ${globalArticleTail[lang][index]} ${exactArticleTail[lang][index]} ${visualArticleTail[lang][index]}`.trim();
    const additions = Array.from({ length: sections.length }, () => []);
    const targetLengths = englishArticles[index].sections.map((section) => section[1].length);
    const projectedLengths = sections.map((section) => section[1].length);

    // Fill the visibly short localized sections first, using the matching
    // English section as a layout target. This keeps all translated content but
    // avoids hiding almost all extra depth in the final few sections.
    readableUnits(extra).forEach((unit) => {
      const deficient = projectedLengths
        .map((length, sectionIndex) => ({ sectionIndex, ratio: length / Math.max(targetLengths[sectionIndex], 1) }))
        .filter(({ ratio }) => ratio < 0.95)
        .sort((a, b) => a.ratio - b.ratio);
      const sectionIndex = deficient.length
        ? deficient[0].sectionIndex
        : projectedLengths.indexOf(Math.min(...projectedLengths));
      additions[sectionIndex].push(unit);
      projectedLengths[sectionIndex] += unit.length + 1;
    });

    sections.forEach((section, sectionIndex) => {
      section[1] = `${section[1]} ${additions[sectionIndex].join(" ")}`.trim();
    });
    return { ...article, sections };
  });
}
