const parityExtensions = {
  en: [
    [
      ["Worked example: reviewing footwear", "Begin by matching the selected color and size label to the live source page, then confirm that the pair is shown together. Compare toe shape, heel height, panel position and outsole alignment using straight-on and overhead views. Follow the sole attachment around both shoes and separate removable surface marks from open gaps or structural damage. Measure the insole or outsole only when the method is visible. End by recording whether the evidence supports shipping, a targeted heel or size photo, an exchange, or a return."],
      ["Worked example: reviewing a garment", "Confirm the garment type, color, printed version and tagged size before judging construction. Inspect front and back at full length, then move to collar, cuffs, hem, pockets, print edges, hardware and interior labels. Compare flat chest width and length with a garment that already fits, using the same measurement points. Treat camera color as uncertain unless neutral references agree across images. Record repeated seam or print issues separately from folds caused by packing, then choose one clear warehouse action."],
      ["When the evidence conflicts", "Conflicting records are a reason to narrow the claim, not average everything into certainty. Check whether the records share the same source listing, option, seller and time period. Give more weight to direct, recent, well-lit evidence with complete angles than to a cropped historical image. If one measurement conflicts with the label or visible scale, request a repeat. If identity remains unresolved, classify the result as similar or unverified. Never transfer a defect rate or quality promise from mixed products."],
      ["Final pre-shipment evidence review", "Before approving international shipping, confirm that every item and option is correct, all fit-critical measurements are acceptable, important surfaces and components are visible, and no functional damage is left unexplained. Check that requested follow-up photos were actually answered. Write accepted cosmetic variation and remaining uncertainty in the record. Then verify the current source listing, return window, route restrictions and destination rules. This final review cannot guarantee the future, but it makes the decision traceable and prevents missing evidence from being mistaken for good evidence."]
    ],
    [
      ["Worked example: starting from a live link", "Open the direct source link and save the resolved URL, item identifier, selected option and checked date. Search with the full link first. If a likely record appears, compare the destination, main image, option thumbnails, title and visible construction before calling it exact. Open multiple records to check whether they belong to the same item group or only resemble it. If the source changes during research, preserve the old evidence and repeat the live check rather than silently combining two versions."],
      ["Worked example: recovering a dead link", "When the original page no longer resolves, keep its item ID, title, screenshot, option and marketplace context. Try the recognized ID, then a distinctive phrase, and finally the least edited product image. Treat every result as a candidate until an active destination confirms the same specifications. A historical QC record can still show measurements or construction, but it cannot prove stock. If no active exact source survives, publish the outcome as an alternative-discovery workflow instead of presenting a visually similar listing as the original."],
      ["Use an explicit match taxonomy", "Label results with four levels: exact source, likely same item, visually similar and unverified. Exact source requires a consistent live destination and option. Likely same item has strong shared identifiers but a remaining gap. Visually similar is useful for browsing but cannot inherit QC conclusions. Unverified means the available evidence is insufficient. Apply the label in article copy, product notes and internal data. This vocabulary is more honest than unsupported percentage scores and helps readers understand whether to compare, request evidence, open the source or discard the result."],
      ["Maintain freshness and editorial records", "For every published find, retain the query, resolved link, option, match level, verification date and one sentence explaining the decision. Recheck live availability, price and option before publication and again before a material update. Remove or relabel cards whose destination no longer supports the claim. Keep screenshots as dated evidence, not permanent truth. This editorial record makes later corrections easier, protects image-to-link accuracy and gives search content a real maintenance process instead of allowing old pages to accumulate unsupported statements."]
    ],
    [
      ["Worked example: estimate before consolidation", "Start with the available item weights and note whether each value includes retail packaging. Add a reasonable packaging range rather than pretending the warehouse carton is already known. Create one compact scenario and one protected scenario, then calculate dimensional weight only after choosing a current route rule. Compare both scenarios with the route's measured-weight policy, minimum and rounding. The result is a planning range, not a quote. Use it to decide which packaging instructions are worth requesting before the final parcel is built."],
      ["Worked example: review the finished parcel", "After consolidation, match the parcel photo to the expected item count and packaging request. Record measured mass and external length, width and height, including visible bulges or corner protection. Recalculate with the exact active divisor, units and rounding sequence. Compare the result with the live quote and investigate large differences. A reweigh or packaging photo is most useful before payment. Do not substitute an old route example: destination availability, restrictions, fees and calculation rules may have changed."],
      ["Compare service, not only the headline rate", "A useful route table includes eligibility, billable basis, weight increment, minimum charge, size limits, restricted items, surcharges, tracking, insurance conditions and the current total. Remove ineligible lines first. Compare the same finished parcel across every remaining row. Consider whether removing a box changes a rounding boundary enough to justify lower protection. Mark unknown information instead of inventing it. The cheapest displayed rate is not necessarily the lowest payable or most suitable option once the complete rule is applied."],
      ["Separate shipping arithmetic from compliance", "Parcel weight and dimensions help estimate transport cost; they do not determine import legality, declaration requirements or tax treatment. Verify contents, descriptions, quantity and documentation against current destination and carrier guidance. Keep that check beside—but separate from—the cost worksheet. Save the quote and rule date, because past delivery does not guarantee future treatment. Before payment, confirm item list, packaging, measured data, route, restrictions and declared information. If a value or rule remains unclear, pause rather than turning an estimate into a factual promise."]
    ]
  ],
  de: [
    [
      ["Praxisbeispiel: Schuhe prüfen", "Beginne mit der exakten Identität: gewählte Farbe, Größenetikett, Artikelvariante und Lieferumfang müssen zum aktuellen Quellangebot passen. Prüfe danach, ob beide Schuhe gemeinsam und aus vergleichbaren Winkeln gezeigt werden. Vergleiche Zehenform, Fersenhöhe, Paneelposition, Ösenabstände und Außensohlenlinie in Front-, Seiten- und Draufsicht. Folge der Verbindung zwischen Obermaterial und Sohle einmal vollständig um beide Schuhe. Unterscheide abwischbare Spuren oder Verpackungsdruck von offenen Klebestellen, Rissen oder sichtbarer struktureller Beschädigung. Nutze eine Einlegesohlen- oder Außensohlenmessung nur, wenn Nullpunkt, Endpunkt und Lineal klar erkennbar sind. Schließe mit einer konkreten Aktion: versenden, ein gezieltes Fersen- oder Größenfoto anfordern, umtauschen oder zurückgeben. Notiere außerdem, welche kleine optische Abweichung bewusst akzeptiert wurde."],
      ["Praxisbeispiel: Kleidung prüfen", "Bestätige zunächst Kleidungsart, Farbe, Druckversion, Etikettgröße und eventuell enthaltene Teile. Betrachte Vorder- und Rückseite vollständig, bevor du in Details zoomst. Prüfe anschließend Kragen, Bündchen, Saum, Taschen, Druckkanten, Reißverschluss, Knöpfe, Nähte und Innenetiketten. Vergleiche flache Brustweite, Länge, Schulter oder Taille mit einem gut sitzenden eigenen Kleidungsstück und verwende dabei dieselben Messpunkte. Farbe bleibt unsicher, wenn Lagerlicht und Weißabgleich zwischen Bildern wechseln; neutrale Etiketten oder ein einheitlicher Hintergrund helfen bei der Einordnung. Trenne wiederkehrende Naht- oder Druckprobleme von Falten, die durch Verpackung entstanden sind. Beende die Prüfung mit genau einer Lageraktion und einem kurzen Grund, damit später nachvollziehbar bleibt, welche sichtbaren Belege die Entscheidung getragen haben."],
      ["Wenn sich Belege widersprechen", "Widersprüchliche Datensätze sollten die Aussage enger machen, nicht durch einen Durchschnitt künstliche Sicherheit erzeugen. Prüfe zuerst, ob alle Bilder wirklich zum selben Marktplatz, Quelllink, Verkäufer, Artikel, zur selben Option und zu einem vergleichbaren Zeitraum gehören. Direkte, aktuelle, scharfe und vollständig abgedeckte Aufnahmen wiegen stärker als ein zugeschnittener historischer Screenshot ohne klaren Ursprung. Widerspricht eine Messung dem Größenetikett oder der sichtbaren Skala, fordere eine Wiederholung mit flach liegendem Artikel und eindeutigem Lineal an. Bleibt die Identität offen, kennzeichne den Treffer als wahrscheinlich gleich, ähnlich oder ungeprüft. Übertrage niemals eine Fehlerhäufigkeit, Größenempfehlung oder Qualitätszusage von gemischten Produkten. Die richtige Reaktion auf schwache Daten ist geringere Sicherheit und ein klarer nächster Prüfschritt."],
      ["Letzte Prüfung vor internationalem Versand", "Vor der Freigabe müssen Artikel, Variante, Farbe, Größe und Lieferumfang stimmen. Alle passformkritischen Maße sollten im akzeptablen Bereich liegen, wichtige Oberflächen und Bauteile sichtbar sein und funktionale Schäden geklärt werden. Kontrolliere, ob angeforderte Zusatzbilder tatsächlich die genannte Stelle, den richtigen Winkel und die gewünschte Messung beantworten. Halte akzeptierte kosmetische Abweichungen sowie verbleibende Unsicherheit schriftlich fest. Öffne danach noch einmal das aktuelle Quellangebot und prüfe Bestand, Option, Rückgabefrist, Routenbeschränkungen und Zielregeln. Diese Abschlussprüfung garantiert weder Haltbarkeit noch Zustellung, schafft aber eine nachvollziehbare Entscheidung. Fehlende Bilder dürfen nicht als fehlerfreie Bereiche behandelt werden; wenn ein entscheidender Punkt offen bleibt, ist eine gezielte Nachprüfung sinnvoller als eine vorschnelle Versandfreigabe."]
    ],
    [
      ["Praxisbeispiel: mit einem aktiven Link beginnen", "Öffne die direkte Produktseite und speichere die endgültig aufgelöste URL, Artikelkennung, gewünschte Option und das Prüfdatum. Suche zuerst mit dem vollständigen Link. Erscheint ein wahrscheinlicher QC-Datensatz, vergleiche Zielseite, Hauptbild, Optionsbilder, Titel, sichtbare Konstruktion und Größen- oder Farbkennzeichnung, bevor du ihn als exakte Quelle bezeichnest. Öffne mehrere Datensätze und prüfe, ob sie wirklich derselben Artikelgruppe zugeordnet werden können oder lediglich ähnlich aussehen. Wird das Quellangebot während der Recherche geändert, bewahre alte Screenshots und das ursprüngliche Datum, führe aber eine neue Live-Prüfung durch. Kombiniere nicht stillschweigend alte und neue Versionen. Ein direkter Link liefert die stärkste Ausgangsidentität, ersetzt jedoch nicht die Kontrolle der konkreten Option und der aktuellen Zielseite."],
      ["Praxisbeispiel: einen toten Link rekonstruieren", "Wenn die ursprüngliche Produktseite nicht mehr öffnet, sichere Artikel-ID, Titel, Screenshot, gewählte Option, Marktplatz und vorhandene Datumsangaben. Suche zuerst mit einer erkannten ID im passenden Marktplatzkontext, danach mit einer unterscheidenden Modell-, Material- oder Konstruktionsphrase und zuletzt mit dem am wenigsten bearbeiteten Produktbild. Jeder Treffer bleibt ein Kandidat, bis eine aktive Zielseite dieselben sichtbaren Spezifikationen bestätigt. Historische QC-Fotos können weiterhin Maße, Verarbeitung oder wiederkehrende Probleme zeigen, beweisen aber weder aktuellen Bestand noch eine identische neue Charge. Überlebt keine aktive exakte Quelle, beschreibe das Ergebnis als Suche nach Alternativen. Ein ähnlich aussehendes Angebot darf nicht allein wegen eines überzeugenden Vorschaubildes als Original ausgegeben werden."],
      ["Eine klare Match-Taxonomie verwenden", "Nutze vier feste Stufen: exakte Quelle, wahrscheinlich gleicher Artikel, visuell ähnlich und ungeprüft. Eine exakte Quelle verlangt eine konsistente aktive Zielseite, passende Kennung und dieselbe Option. Wahrscheinlich gleich bedeutet, dass starke gemeinsame Merkmale vorhanden sind, aber eine überprüfbare Lücke bleibt. Visuell ähnliche Ergebnisse unterstützen die Entdeckung, dürfen jedoch keine QC-Aussage eines anderen Angebots übernehmen. Ungeprüft heißt, dass die vorhandenen Daten für eine belastbare Einordnung nicht reichen. Verwende diese Bezeichnungen in Artikeln, Produktnotizen und internen Datensätzen. Sie sind ehrlicher als erfundene Prozentwerte und geben dem Leser eine konkrete nächste Aktion: Quelle öffnen, Option vergleichen, Zusatzbeleg anfordern oder Kandidat verwerfen. Suchranking wird dadurch nicht fälschlich zu einer Tatsachenbehauptung."],
      ["Aktualität und redaktionelle Nachweise pflegen", "Speichere für jeden veröffentlichten Fund Suchanfrage oder URL, endgültiges Ziel, ausgewählte Option, Match-Stufe, Prüfdatum und einen Begründungssatz. Prüfe vor Veröffentlichung und vor einer wesentlichen Aktualisierung erneut Bestand, Preis, Varianten und Zielseite. Entferne oder kennzeichne Karten neu, wenn das Ziel die ursprüngliche Aussage nicht mehr unterstützt. Screenshots sind datierte Nachweise und keine dauerhafte Wahrheit. Ein solches Protokoll verhindert doppelte Arbeit, schützt die Bild-zu-Link-Zuordnung und erleichtert Korrekturen. Es zeigt außerdem, dass die Seite aktiv gepflegt wird, statt alte Produktdaten unbegrenzt weiterzugeben. Wo ein Datum fehlt oder die Herkunft eines Bildes unklar wird, sollte die Sicherheit der Formulierung reduziert und der nächste Live-Check dokumentiert werden." ]
    ],
    [
      ["Praxisbeispiel: vor der Konsolidierung schätzen", "Beginne mit den verfügbaren Einzelgewichten und notiere bei jedem Wert, ob Verkaufsverpackung enthalten ist. Ergänze eine realistische Spanne für Außenkarton und Schutzmaterial, statt so zu tun, als sei das Endpaket bereits bekannt. Erstelle ein kompaktes und ein stärker geschütztes Volumenszenario. Erst nachdem eine aktuell verfügbare Route ausgewählt wurde, setzt du deren Divisor, Einheit, Rundung und Mindestregeln ein. Vergleiche beide Szenarien mit dem tatsächlichen Gewicht nach der Abrechnungslogik der Route. Das Ergebnis ist eine Planungsspanne, kein verbindliches Angebot. Es hilft zu entscheiden, ob Schuhkartons, starre Verpackungen oder zusätzliche Schutzmaßnahmen entfernt beziehungsweise beibehalten werden sollen. Die endgültige Kostenentscheidung wartet auf die gemessenen Daten des konsolidierten Pakets."],
      ["Praxisbeispiel: das fertige Paket prüfen", "Gleiche nach der Konsolidierung das Paketfoto mit erwarteter Artikelzahl und den Verpackungsanweisungen ab. Notiere gemessene Masse sowie äußere Länge, Breite und Höhe einschließlich sichtbarer Wölbungen, Eckschützer oder überstehender Bereiche. Rechne mit Divisor, Einheiten und Rundungsfolge der aktuell ausgewählten Linie neu. Vergleiche das Ergebnis mit der Live-Quote und untersuche größere Abweichungen. Ein Nachwiegen oder ein zusätzliches Verpackungsfoto ist vor Zahlung am wertvollsten. Verwende keine alte Route als Beleg, denn Verfügbarkeit, Größenlimits, Sperrgutregeln, Zuschläge und Berechnungsweise können sich nach Ziel und Zeitpunkt ändern. Wenn Maße unplausibel wirken, prüfe auch, ob Zentimeter und Zoll oder Gramm und Kilogramm verwechselt wurden, bevor du eine falsche Kostenannahme veröffentlichst."],
      ["Gesamte Leistung statt Grundpreis vergleichen", "Eine brauchbare Routentabelle enthält Zulässigkeit, Abrechnungsbasis, Gewichtsinkrement, Mindestpreis, Größenlimits, eingeschränkte Artikel, Zuschläge, Tracking, Versicherungsbedingungen und den aktuellen Gesamtbetrag. Entferne zuerst alle unzulässigen Linien und vergleiche dann dasselbe fertige Paket in jeder verbleibenden Zeile. Prüfe, ob das Entfernen einer Verpackung eine Rundungsgrenze tatsächlich verändert und ob die mögliche Ersparnis den Verlust an Schutz rechtfertigt. Unbekannte Angaben werden markiert, nicht erfunden. Der niedrigste angezeigte Kilopreis ist nach Mindestbetrag, strenger Volumenrechnung oder Großpaketzuschlag nicht automatisch die günstigste oder passendste Option. Speichere das Quotendatum, damit spätere Änderungen nicht wie ein Widerspruch zu einem zeitlosen Preisversprechen wirken."],
      ["Versandrechnung und Compliance trennen", "Gewicht und Maße helfen bei der Berechnung von Transportkosten, bestimmen aber weder Einfuhrlegalität noch Deklarationspflichten oder Steuerbehandlung. Prüfe Inhalt, Beschreibung, Menge und erforderliche Unterlagen anhand aktueller Ziel- und Carrier-Hinweise. Halte diese Kontrolle neben, aber getrennt von der Kostentabelle. Speichere Datum und verwendete Regel, weil eine frühere erfolgreiche Zustellung keine zukünftige Behandlung garantiert. Vor Zahlung müssen Artikelliste, Verpackung, gemessene Daten, Route, Beschränkungen und Deklarationsangaben zusammenpassen. Bleibt eine Zahl oder Vorschrift unklar, pausiere und fordere Klärung an. Eine Planungsspanne darf nicht in eine Preis-, Zoll- oder Zustellgarantie umformuliert werden, nur weil sie für eine frühere Sendung ungefähr gestimmt hat."]
    ]
  ],
  es: [
    [
      ["Ejemplo práctico: revisar calzado", "Empieza por la identidad exacta: color elegido, etiqueta de talla, variante y componentes deben coincidir con la ficha de origen activa. Después comprueba que ambos zapatos aparecen juntos y desde ángulos comparables. Revisa forma de la puntera, altura del talón, posición de paneles, separación de ojales y línea de la suela en vistas frontal, lateral y superior. Sigue toda la unión entre empeine y suela para separar polvo, marcas de embalaje o restos removibles de huecos abiertos, grietas o daño estructural. Usa una medida de plantilla o suela solo cuando se vean claramente el inicio, el final y la regla. Termina con una acción concreta: enviar, pedir una foto dirigida del talón o de la talla, cambiar o devolver. Anota también qué variación cosmética menor aceptas conscientemente."],
      ["Ejemplo práctico: revisar una prenda", "Confirma tipo de prenda, color, versión del gráfico, talla de etiqueta y piezas incluidas antes de analizar la construcción. Observa frente y espalda completos y luego revisa cuello, puños, bajo, bolsillos, bordes de impresión, cremallera, botones, costuras y etiquetas interiores. Compara ancho de pecho, largo, hombros o cintura en plano con una prenda propia que te quede bien, utilizando los mismos puntos de medición. Considera incierto el color si cambian la iluminación y el balance de blancos; una etiqueta neutra o un fondo constante ayuda. Separa defectos repetidos de costura o impresión de arrugas creadas por el embalaje. Finaliza con una sola acción de almacén y una razón breve para que la decisión pueda reconstruirse más adelante a partir de pruebas visibles."],
      ["Cuando las pruebas se contradicen", "Los registros contradictorios deben reducir el alcance de la conclusión, no convertirse en una certeza artificial mediante un promedio. Comprueba si las imágenes pertenecen al mismo mercado, enlace, vendedor, artículo, opción y periodo. Da más peso a pruebas directas, recientes, nítidas y con ángulos completos que a una captura histórica recortada sin origen claro. Si una medida contradice la etiqueta o la escala visible, solicita una repetición con la prenda plana y la regla bien colocada. Si la identidad sigue abierta, clasifica el resultado como probablemente igual, visualmente similar o sin verificar. No transfieras tasas de defectos, recomendaciones de talla o promesas de calidad entre productos mezclados. La respuesta correcta a datos débiles es declarar menos confianza y definir el siguiente control necesario."],
      ["Revisión final antes del envío internacional", "Antes de aprobar el envío, confirma artículo, variante, color, talla y componentes. Todas las medidas críticas de ajuste deben estar dentro del rango aceptado, las superficies y piezas importantes deben ser visibles y cualquier daño funcional debe estar explicado. Comprueba que las fotos adicionales solicitadas respondan realmente a la zona, ángulo y medición pedidos. Registra variaciones cosméticas aceptadas e incertidumbre restante. Abre de nuevo la ficha activa para revisar opción, disponibilidad, ventana de devolución, restricciones de ruta y reglas del destino. Esta revisión no garantiza durabilidad ni entrega, pero hace la decisión rastreable. Una zona que no aparece en las fotos no debe tratarse como una zona perfecta; si un punto decisivo sigue oculto, pide una comprobación dirigida antes de enviar." ]
    ],
    [
      ["Ejemplo práctico: empezar con un enlace activo", "Abre la página directa y guarda la URL final resuelta, identificador, opción elegida y fecha de revisión. Busca primero con el enlace completo. Si aparece un registro probable, compara destino, imagen principal, miniaturas de opciones, título, construcción visible y etiquetas antes de llamarlo fuente exacta. Abre varios registros para comprobar si pertenecen al mismo grupo o solo tienen un aspecto parecido. Si la ficha cambia durante la investigación, conserva la prueba anterior y su fecha, pero repite la verificación en vivo; no combines en silencio versiones antiguas y nuevas. Un enlace directo conserva la mejor identidad inicial, aunque todavía debes confirmar que la opción concreta y la página actual son coherentes con las fotos que utilizas para decidir."],
      ["Ejemplo práctico: recuperar un enlace muerto", "Cuando la página original ya no abre, conserva ID, título, captura, opción, mercado y fechas disponibles. Prueba primero el identificador reconocido dentro del contexto correcto, después una frase distintiva de modelo, material o construcción y, por último, la imagen menos editada. Todo resultado sigue siendo candidato hasta que una ficha activa confirme las mismas especificaciones visibles. Un QC histórico puede enseñar medidas, fabricación o problemas repetidos, pero no demuestra stock ni un lote nuevo idéntico. Si no sobrevive una fuente exacta activa, presenta el resultado como descubrimiento de alternativas. Una ficha visualmente cercana nunca debe ocupar el lugar de la original solo porque su miniatura o fotografía de vendedor resulte convincente."],
      ["Aplicar una taxonomía de coincidencia", "Utiliza cuatro niveles: fuente exacta, probablemente el mismo artículo, visualmente similar y sin verificar. La fuente exacta exige destino activo consistente, identificador coherente y misma opción. Probablemente igual indica señales compartidas fuertes con alguna laguna pendiente. Un resultado visualmente similar sirve para explorar, pero no puede heredar conclusiones QC de otra ficha. Sin verificar significa que la prueba disponible no permite una clasificación sólida. Usa estas etiquetas en artículos, notas y datos internos. Son más honestas que porcentajes inventados y explican la siguiente acción: abrir la fuente, comparar opciones, solicitar evidencia o descartar. De esta forma la posición de un buscador no se transforma en una afirmación factual sobre identidad, calidad o disponibilidad."],
      ["Mantener vigencia y registro editorial", "Para cada producto publicado guarda consulta o URL, destino resuelto, opción, nivel de coincidencia, fecha y una frase de justificación. Revisa disponibilidad, precio, variantes y destino antes de publicar y antes de una actualización importante. Elimina o reclasifica tarjetas cuando la página ya no sostenga la afirmación original. Las capturas son pruebas fechadas, no verdad permanente. Este registro evita trabajo duplicado, protege la relación imagen-enlace y facilita correcciones. También demuestra mantenimiento real en lugar de permitir que páginas antiguas acumulen datos sin respaldo. Cuando falte la fecha o el origen de una imagen deje de ser claro, reduce la seguridad del texto y documenta la siguiente comprobación en vivo que deberá realizarse." ]
    ],
    [
      ["Ejemplo práctico: estimar antes de consolidar", "Empieza con los pesos disponibles y anota si cada cifra incluye embalaje comercial. Añade un intervalo razonable para caja exterior y protección, sin fingir que el paquete final ya existe. Crea un escenario compacto y otro más protegido. Solo después de escoger una ruta actualmente disponible debes aplicar su divisor, unidades, redondeo y mínimos. Compara ambos escenarios con el peso real según la política facturable de esa línea. El resultado es un rango de planificación, no una cotización. Sirve para decidir si merece la pena pedir retirada de cajas rígidas, embalajes de calzado o protección adicional. La decisión de coste definitiva debe esperar al peso y las dimensiones medidos después de la consolidación."],
      ["Ejemplo práctico: revisar el paquete terminado", "Después de consolidar, compara la foto del paquete con el número esperado de artículos y las instrucciones de embalaje. Registra masa medida y largo, ancho y alto exteriores, incluyendo bultos, esquinas reforzadas o zonas que sobresalen. Recalcula con divisor, unidades y secuencia de redondeo de la ruta activa. Contrasta el resultado con la cotización y analiza diferencias grandes. Una nueva pesada o foto adicional resulta más útil antes del pago. No uses como prueba una ruta antigua, porque disponibilidad, límites, recargos y cálculo pueden cambiar. Si las medidas parecen imposibles, comprueba también que no se hayan mezclado centímetros con pulgadas o gramos con kilogramos antes de publicar una estimación equivocada."],
      ["Comparar el servicio completo", "Una tabla útil incluye elegibilidad, base facturable, incremento, mínimo, límites de tamaño, artículos restringidos, recargos, seguimiento, seguro y total actual. Elimina primero las líneas que no admiten el paquete y compara el mismo paquete final en las restantes. Comprueba si retirar una caja realmente cambia un escalón de redondeo y si el ahorro compensa la pérdida de protección. Marca lo desconocido en vez de inventarlo. La tarifa por kilogramo más baja no siempre produce el menor importe ni la opción adecuada después de aplicar mínimos, volumen o recargos. Guarda la fecha de la cotización para que cambios posteriores no parezcan contradicciones de una promesa permanente."],
      ["Separar cálculo y cumplimiento", "Peso y dimensiones ayudan a estimar transporte, pero no determinan legalidad de importación, declaración o impuestos. Verifica contenido, descripción, cantidad y documentación con reglas actuales del destino y del transportista. Mantén esta revisión junto a la hoja de costes, pero como decisión independiente. Guarda fecha y regla utilizada; una entrega anterior no garantiza el mismo tratamiento futuro. Antes de pagar deben coincidir lista de artículos, embalaje, datos medidos, ruta, restricciones y declaración. Si una cifra o norma sigue sin estar clara, detente y solicita aclaración. Un rango de planificación no debe convertirse en garantía de precio, aduana o entrega solo porque se aproximó a un envío previo." ]
    ]
  ],
  fr: [
    [
      ["Exemple pratique : contrôler des chaussures", "Commencez par l’identité exacte : couleur choisie, étiquette de taille, variante et éléments inclus doivent correspondre à la fiche source active. Vérifiez ensuite que les deux chaussures apparaissent ensemble sous des angles comparables. Comparez forme de l’avant, hauteur du talon, position des empiècements, espacement des œillets et ligne de semelle en vues frontale, latérale et supérieure. Suivez toute la jonction entre tige et semelle afin de distinguer poussière, pression d’emballage ou trace amovible d’un espace ouvert, d’une fissure ou d’un dommage structurel. N’utilisez une mesure de semelle intérieure ou extérieure que si début, fin et règle sont visibles. Terminez par une action : expédier, demander une photo ciblée, échanger ou retourner, puis notez la variation cosmétique éventuellement acceptée."],
      ["Exemple pratique : contrôler un vêtement", "Confirmez le type, la couleur, la version du motif, la taille indiquée et les éléments inclus avant d’évaluer la fabrication. Observez d’abord le devant et le dos en entier, puis le col, les poignets, l’ourlet, les poches, les bords d’impression, la fermeture, les boutons, les coutures et les étiquettes intérieures. Comparez largeur de poitrine, longueur, épaules ou taille à plat avec un vêtement personnel bien ajusté en utilisant les mêmes points. La couleur reste incertaine si lumière et balance des blancs changent ; une étiquette neutre aide. Séparez défauts répétés et plis d’emballage. Concluez par une seule action d’entrepôt et une raison courte afin que la décision puisse être reconstruite à partir de preuves visibles."],
      ["Quand les preuves se contredisent", "Des dossiers contradictoires doivent réduire la portée de la conclusion, pas créer une certitude artificielle par moyenne. Vérifiez qu’ils partagent place de marché, lien, vendeur, article, option et période. Accordez plus de poids à une preuve directe, récente, nette et complète qu’à une capture historique recadrée sans provenance claire. Si une mesure contredit l’étiquette ou l’échelle visible, demandez une répétition avec l’article à plat et la règle correctement placée. Si l’identité reste ouverte, classez le résultat comme probablement identique, visuellement proche ou non vérifié. Ne transférez jamais taux de défaut, conseil de taille ou promesse de qualité entre produits mélangés. Face à des données faibles, la bonne réponse consiste à réduire la confiance et à définir le prochain contrôle nécessaire."],
      ["Dernière revue avant expédition internationale", "Avant d’autoriser l’expédition, confirmez article, variante, couleur, taille et contenu. Toutes les mesures décisives pour la coupe doivent être acceptables, les surfaces et composants importants visibles, et tout dommage fonctionnel expliqué. Vérifiez que les photos supplémentaires répondent réellement à la zone, à l’angle et à la mesure demandés. Notez les variations cosmétiques acceptées et l’incertitude restante. Rouvrez ensuite la fiche active pour contrôler option, disponibilité, délai de retour, restrictions de ligne et règles de destination. Cette revue ne garantit ni durée ni livraison, mais rend la décision traçable. Une zone absente des images ne doit jamais être considérée comme parfaite ; si un point décisif reste caché, demandez une preuve ciblée avant d’expédier." ]
    ],
    [
      ["Exemple pratique : partir d’un lien actif", "Ouvrez la page directe et conservez l’URL finale, l’identifiant, l’option choisie et la date. Recherchez d’abord avec le lien complet. Si un dossier probable apparaît, comparez destination, image principale, miniatures d’options, titre, construction et étiquettes avant de parler de source exacte. Ouvrez plusieurs dossiers pour vérifier s’ils appartiennent au même groupe ou se ressemblent seulement. Si la fiche change pendant la recherche, gardez l’ancienne preuve et sa date, mais recommencez la vérification en direct ; ne mélangez pas silencieusement les versions. Le lien direct conserve la meilleure identité initiale, mais il faut encore confirmer que l’option précise et la page actuelle correspondent aux photos utilisées pour décider."],
      ["Exemple pratique : récupérer un lien mort", "Lorsque la page originale ne répond plus, conservez identifiant, titre, capture, option, place de marché et dates disponibles. Essayez d’abord l’identifiant reconnu dans le bon contexte, ensuite une expression distinctive de modèle, matière ou construction, puis l’image la moins modifiée. Chaque résultat reste un candidat jusqu’à ce qu’une destination active confirme les mêmes caractéristiques visibles. Un ancien QC peut renseigner mesures, fabrication ou problèmes répétés sans prouver stock ou série identique. Si aucune source exacte active ne subsiste, présentez le résultat comme découverte d’alternatives. Une fiche proche ne doit jamais remplacer l’original uniquement parce que sa miniature ou sa photographie vendeur paraît convaincante."],
      ["Appliquer une taxonomie de correspondance", "Utilisez quatre niveaux : source exacte, probablement le même article, visuellement proche et non vérifié. La source exacte exige une destination active cohérente, un identifiant compatible et la même option. Probablement identique signale des indices forts avec une lacune encore ouverte. Un résultat visuellement proche sert à découvrir, mais ne peut hériter des conclusions QC d’une autre fiche. Non vérifié signifie que les données ne suffisent pas. Employez ces étiquettes dans articles, notes et données internes. Elles sont plus honnêtes que des pourcentages inventés et indiquent l’étape suivante : ouvrir, comparer, demander une preuve ou écarter. Ainsi, un classement de recherche ne devient jamais une affirmation factuelle sur identité, qualité ou disponibilité."],
      ["Maintenir l’actualité et le dossier éditorial", "Pour chaque trouvaille publiée, conservez requête ou URL, destination résolue, option, niveau de correspondance, date et phrase de justification. Revérifiez disponibilité, prix, variantes et destination avant publication et avant toute mise à jour importante. Supprimez ou reclassez les cartes dont la page ne soutient plus l’affirmation. Les captures sont des preuves datées, pas une vérité permanente. Ce journal évite le travail en double, protège la relation image-lien et facilite les corrections. Il démontre également un entretien réel plutôt qu’une accumulation de données obsolètes. Si la date manque ou si la provenance d’une image devient floue, réduisez la certitude du texte et documentez le prochain contrôle en direct." ]
    ],
    [
      ["Exemple pratique : estimer avant consolidation", "Commencez avec les poids disponibles et notez si chacun comprend l’emballage commercial. Ajoutez une fourchette raisonnable pour carton extérieur et protection sans prétendre que le colis final existe déjà. Créez un scénario compact et un scénario plus protégé. Ce n’est qu’après avoir choisi une ligne actuellement disponible que vous appliquez son diviseur, ses unités, son arrondi et ses minimums. Comparez les deux scénarios au poids réel selon la politique facturable. Le résultat est une plage de planification, pas un devis. Elle aide à décider si le retrait de boîtes rigides ou l’ajout de protection mérite d’être demandé. La décision finale attend les mesures prises après consolidation."],
      ["Exemple pratique : revoir le colis fini", "Après consolidation, comparez la photo du colis au nombre d’articles et aux instructions prévues. Relevez masse mesurée et longueur, largeur, hauteur extérieures, y compris renflements, coins renforcés et parties saillantes. Recalculez avec diviseur, unités et séquence d’arrondi de la ligne active. Comparez au devis et examinez tout écart important. Une nouvelle pesée ou une photo supplémentaire est plus utile avant paiement. N’utilisez pas une ancienne ligne comme preuve : disponibilité, limites, suppléments et calcul peuvent changer. Si les mesures semblent impossibles, vérifiez aussi qu’aucune confusion n’existe entre centimètres et pouces ou grammes et kilogrammes avant de publier une estimation erronée."],
      ["Comparer le service complet", "Un tableau utile inclut admissibilité, base facturable, incrément, minimum, limites de taille, articles restreints, suppléments, suivi, assurance et total actuel. Éliminez d’abord les lignes incompatibles et comparez le même colis fini sur les autres. Vérifiez si retirer une boîte change réellement un palier et si l’économie compense la protection perdue. Marquez les inconnues au lieu de les inventer. Le tarif au kilogramme le plus bas n’est pas forcément le montant final le plus faible après minimum, volume ou supplément. Conservez la date du devis afin qu’une évolution ultérieure ne ressemble pas à la contradiction d’une promesse permanente."],
      ["Séparer calcul et conformité", "Poids et dimensions aident à estimer le transport sans déterminer légalité d’importation, déclaration ou fiscalité. Vérifiez contenu, description, quantité et documents avec les règles actuelles de destination et de transporteur. Gardez ce contrôle à côté de la feuille de coûts, mais comme décision séparée. Conservez date et règle utilisées ; une livraison passée ne garantit pas le même traitement futur. Avant paiement, liste, emballage, données mesurées, ligne, restrictions et déclaration doivent être cohérents. Si un chiffre ou une règle reste flou, arrêtez-vous et demandez une clarification. Une fourchette de planification ne doit pas devenir une garantie de prix, de douane ou de livraison." ]
    ]
  ],
  it: [
    [
      ["Esempio pratico: controllare le scarpe", "Inizia dall’identità esatta: colore scelto, etichetta della taglia, variante e componenti devono corrispondere alla scheda sorgente attiva. Controlla poi che entrambe le scarpe siano mostrate insieme e da angoli comparabili. Confronta forma della punta, altezza del tallone, posizione dei pannelli, distanza degli occhielli e linea della suola nelle viste frontale, laterale e dall’alto. Segui tutta la giunzione fra tomaia e suola per distinguere polvere, pressione dell’imballaggio o segni removibili da spazi aperti, crepe o danni strutturali. Usa una misura di soletta o suola solo quando inizio, fine e righello sono chiari. Termina con un’azione: spedisci, chiedi una foto mirata, cambia o restituisci, annotando anche la variazione cosmetica che decidi di accettare."],
      ["Esempio pratico: controllare un capo", "Conferma tipo, colore, versione della grafica, taglia indicata e parti incluse prima di valutare la costruzione. Osserva davanti e dietro per intero, poi colletto, polsini, orlo, tasche, bordi della stampa, zip, bottoni, cuciture ed etichette interne. Confronta larghezza del petto, lunghezza, spalle o vita a capo disteso con un indumento che ti veste bene, usando gli stessi punti di misura. Il colore resta incerto se luce e bilanciamento del bianco cambiano; un’etichetta neutra aiuta. Separa difetti ripetuti da pieghe di imballaggio. Concludi con una sola azione di magazzino e un motivo breve, così la decisione rimane ricostruibile dalle prove visibili."],
      ["Quando le prove sono in conflitto", "Record contraddittori devono restringere la conclusione, non creare certezza artificiale tramite una media. Controlla che condividano marketplace, link, venditore, articolo, opzione e periodo. Dai più peso a prove dirette, recenti, nitide e complete che a uno screenshot storico ritagliato senza origine chiara. Se una misura contraddice l’etichetta o la scala visibile, chiedi una ripetizione con il capo disteso e il righello ben posizionato. Se l’identità resta aperta, classifica il risultato come probabilmente uguale, visivamente simile o non verificato. Non trasferire tassi di difetto, consigli di taglia o promesse di qualità fra prodotti mescolati. Con dati deboli, la risposta corretta è ridurre la fiducia e definire il prossimo controllo necessario."],
      ["Revisione finale prima della spedizione", "Prima di autorizzare la spedizione internazionale, conferma articolo, variante, colore, taglia e contenuto. Tutte le misure decisive devono essere accettabili, superfici e componenti importanti visibili e ogni danno funzionale chiarito. Verifica che le foto aggiuntive rispondano davvero a zona, angolo e misura richiesti. Registra variazioni cosmetiche accettate e incertezza residua. Riapri poi la scheda attiva per controllare opzione, disponibilità, finestra di reso, restrizioni di rotta e regole di destinazione. Questa revisione non garantisce durata o consegna, ma rende la decisione tracciabile. Una zona assente dalle immagini non va considerata perfetta; se un punto decisivo resta nascosto, chiedi una prova mirata." ]
    ],
    [
      ["Esempio pratico: partire da un link attivo", "Apri la pagina diretta e salva URL finale, identificatore, opzione scelta e data. Cerca prima con il link completo. Se appare un record probabile, confronta destinazione, immagine principale, miniature delle opzioni, titolo, costruzione ed etichette prima di chiamarlo fonte esatta. Apri più record per verificare se appartengono allo stesso gruppo o se sono soltanto simili. Se la scheda cambia durante la ricerca, conserva la prova precedente e la data, ma ripeti il controllo dal vivo; non combinare in silenzio versioni vecchie e nuove. Un link diretto conserva l’identità iniziale più forte, ma devi ancora confermare che l’opzione precisa e la pagina attuale corrispondano alle foto usate per decidere."],
      ["Esempio pratico: recuperare un link morto", "Quando la pagina originale non si apre più, conserva ID, titolo, screenshot, opzione, marketplace e date disponibili. Prova prima l’identificatore riconosciuto nel contesto corretto, poi una frase distintiva di modello, materiale o costruzione e infine l’immagine meno modificata. Ogni risultato resta un candidato finché una destinazione attiva non conferma le stesse specifiche visibili. Un vecchio QC può mostrare misure, costruzione o problemi ripetuti senza provare stock o lotto identico. Se non rimane una fonte esatta attiva, presenta il risultato come scoperta di alternative. Una scheda simile non deve sostituire l’originale solo perché miniatura o foto del venditore sembrano convincenti."],
      ["Applicare una tassonomia di corrispondenza", "Usa quattro livelli: fonte esatta, probabilmente lo stesso articolo, visivamente simile e non verificato. La fonte esatta richiede una destinazione attiva coerente, un identificatore compatibile e la stessa opzione. Probabilmente uguale indica segnali forti con una lacuna ancora aperta. Un risultato visivamente simile serve a scoprire, ma non può ereditare conclusioni QC di un’altra scheda. Non verificato significa che le prove non bastano. Utilizza queste etichette in articoli, note e dati interni. Sono più oneste di percentuali inventate e indicano il prossimo passo: aprire, confrontare, chiedere prove o scartare. Così un ranking di ricerca non diventa un’affermazione fattuale su identità, qualità o disponibilità."],
      ["Mantenere attualità e registro editoriale", "Per ogni prodotto pubblicato conserva query o URL, destinazione risolta, opzione, livello di match, data e una frase di motivazione. Ricontrolla disponibilità, prezzo, varianti e destinazione prima della pubblicazione e prima di un aggiornamento importante. Rimuovi o riclassifica le schede quando la pagina non sostiene più l’affermazione. Gli screenshot sono prove datate, non verità permanenti. Questo registro evita lavoro duplicato, protegge la relazione immagine-link e facilita correzioni. Dimostra inoltre manutenzione reale invece di lasciare accumulare dati obsoleti. Se manca la data o l’origine di un’immagine diventa poco chiara, riduci la sicurezza del testo e documenta il prossimo controllo dal vivo." ]
    ],
    [
      ["Esempio pratico: stimare prima del consolidamento", "Inizia dai pesi disponibili e annota se ogni valore include la confezione commerciale. Aggiungi un intervallo ragionevole per cartone esterno e protezione senza fingere che il pacco finale esista già. Crea uno scenario compatto e uno più protetto. Solo dopo aver scelto una rotta attualmente disponibile applica divisore, unità, arrotondamento e minimi. Confronta entrambi gli scenari con il peso reale secondo la politica fatturabile. Il risultato è un intervallo di pianificazione, non un preventivo. Serve a decidere se chiedere la rimozione di scatole rigide o l’aggiunta di protezione. La decisione finale sul costo deve attendere peso e dimensioni misurati dopo il consolidamento."],
      ["Esempio pratico: controllare il pacco finito", "Dopo il consolidamento confronta la foto del pacco con numero di articoli e istruzioni di imballaggio. Registra massa misurata e lunghezza, larghezza e altezza esterne, includendo rigonfiamenti, angoli rinforzati e sporgenze. Ricalcola con divisore, unità e sequenza di arrotondamento della rotta attiva. Confronta il risultato con il preventivo e indaga differenze importanti. Una nuova pesata o foto aggiuntiva è più utile prima del pagamento. Non usare una vecchia rotta come prova, perché disponibilità, limiti, supplementi e calcolo possono cambiare. Se le misure sembrano impossibili, verifica anche che centimetri e pollici o grammi e chilogrammi non siano stati confusi."],
      ["Confrontare il servizio completo", "Una tabella utile include idoneità, base fatturabile, incremento, minimo, limiti dimensionali, articoli ristretti, supplementi, tracking, assicurazione e totale attuale. Elimina prima le rotte non ammesse e confronta lo stesso pacco finale sulle restanti. Controlla se rimuovere una scatola cambia davvero uno scaglione e se il risparmio compensa la protezione persa. Segna gli elementi ignoti invece di inventarli. La tariffa al chilogrammo più bassa non garantisce il totale minore dopo minimi, volume o supplementi. Conserva la data del preventivo affinché cambiamenti successivi non sembrino contraddire una promessa permanente."],
      ["Separare calcolo e conformità", "Peso e dimensioni aiutano a stimare il trasporto, ma non determinano legalità d’importazione, dichiarazione o imposte. Verifica contenuto, descrizione, quantità e documenti con regole attuali di destinazione e vettore. Mantieni questo controllo accanto al foglio costi, ma come decisione separata. Conserva data e regola utilizzate; una consegna passata non garantisce lo stesso trattamento futuro. Prima di pagare devono coincidere lista, imballaggio, dati misurati, rotta, restrizioni e dichiarazione. Se un valore o una regola resta poco chiaro, fermati e chiedi chiarimento. Un intervallo di pianificazione non deve diventare garanzia di prezzo, dogana o consegna." ]
    ]
  ]
};

const finalParity = {
  en: [
    [["Use an evidence table", "For every critical area, record the expected detail, visible observation, image reference, confidence and action. The table keeps missing evidence visible and prevents a strong photo from cancelling an unrelated defect."], ["Keep the conclusion inside the evidence", "State exactly what the record supports: visible condition of one documented unit at a given time. Do not convert that into authenticity, durability, batch consistency, legality or delivery guarantees."]],
    [["Build internal links around the next task", "Link exact-source research to QC reading, measurements, shipping and the relevant category instead of repeating one generic keyword on every page. Each link should answer what the reader needs next."], ["Retire unsupported results", "When a destination disappears or changes materially, recheck, relabel or remove the card. Keeping a dated historical note is acceptable; leaving an outdated exact-match claim without evidence is not."]],
    [["Keep a dated calculation worksheet", "Store parcel stage, mass, dimensions, route rule, divisor, rounding, minimum, surcharges and quote date. A reproducible worksheet is more useful than an isolated total that cannot be checked later."], ["Publish planning guidance, not promises", "Explain which inputs change the result and tell readers where live verification is required. Avoid fixed route claims unless they were checked for the stated destination and date and can be maintained."]]
  ],
  de: [
    [["Eine Belegtabelle verwenden", "Erstelle für jeden kritischen Bereich eine Zeile mit erwartetem Merkmal, sichtbarer Beobachtung, Bildreferenz, Sicherheitsstufe und nächster Aktion. Bei Schuhen können das Identität, Größenetikett, Paarvergleich, Zehenform, Fersenlinie, Sohlenverbindung und Messung sein; bei Kleidung Variante, flache Maße, Druckposition, Nähte, Beschläge und Innenetiketten. Markiere fehlende Perspektiven ausdrücklich als fehlend. So kann ein starkes Hauptbild keinen unabhängigen Mangel überdecken und eine leere Stelle wird nicht versehentlich als fehlerfrei interpretiert. Nutze neutrale Formulierungen und trenne Beobachtung von Bewertung. Ergänze bei jeder Nachforderung, welches neue Foto oder Maß die Unsicherheit tatsächlich reduzieren soll. Die Tabelle dient nicht dazu, eine künstliche Punktzahl zu erzeugen, sondern macht sichtbar, warum du versendest, nachprüfst, umtauschst oder zurückgibst. Sie hilft außerdem, spätere Chargen zu vergleichen, ohne alte Aufnahmen als dauerhafte Produkteigenschaft zu behandeln."], ["Die Schlussfolgerung innerhalb der Belege halten", "Formuliere nur, was die vorhandenen Bilder und Daten unterstützen: den sichtbaren Zustand einer dokumentierten Einheit zu einem bestimmten Zeitpunkt. Aus sauberen Nähten oder einer passenden Messung folgt keine garantierte Echtheit, Haltbarkeit oder Gleichheit der nächsten Charge. Ein historisches Foto beweist weder aktuellen Bestand noch den Zustand des Artikels, der später bestellt wird. Gewicht und Maße von Drittquellen bleiben prüfbedürftige Referenzen. Wenn ein Bereich fehlt, schreibe ‘nicht sichtbar’ statt ‘kein Problem’. Wenn Licht oder Perspektive eine Aussage schwächen, nenne diese Einschränkung. Vermeide absolute Qualitätsurteile und beschreibe stattdessen konkrete sichtbare Merkmale, wiederkehrende Muster und verbleibende Unsicherheit. Diese Begrenzung macht den Text glaubwürdiger und schützt die Seite davor, aus Suchergebnissen, Bewertungen oder einem attraktiven Vorschaubild Versprechen abzuleiten, die der Datensatz nicht tragen kann." ]],
    [["Interne Links nach dem nächsten Arbeitsschritt bauen", "Verbinde eine Seite nicht nur deshalb mit einer anderen, weil beide dasselbe Hauptkeyword enthalten. Frage, welchen Schritt der Leser nach der aktuellen Aufgabe benötigt. Ein Fund mit exakter Quelle sollte zu einer Anleitung für QC-Bilder, Messungen oder zur passenden Produktkategorie führen. Ein Artikel über tote Links kann zu Bildsuche und Match-Stufen verweisen. Eine Größenprüfung kann anschließend zur Versand- und Konsolidierungsplanung führen. Verwende klare Ankertexte, die das Ziel benennen, und vermeide auf jeder Seite denselben generischen Begriff. Dadurch entsteht eine nachvollziehbare Informationsarchitektur: entdecken, Identität sichern, Belege prüfen, Maße einordnen, Paket planen und Live-Quelle öffnen. Diese Struktur reduziert interne Konkurrenz zwischen Seiten und gibt Suchmaschinen unterschiedliche, klar abgegrenzte Suchabsichten. Ein interner Link sollte also eine echte Nutzerfrage beantworten und nicht lediglich die Anzahl der Verweise erhöhen."], ["Nicht mehr gestützte Treffer entfernen", "Prüfe veröffentlichte Produktkarten regelmäßig darauf, ob Zielseite, Bild, Option und Aussage noch zusammenpassen. Wird ein Angebot entfernt, umgeleitet oder wesentlich verändert, gibt es drei ehrliche Möglichkeiten: erneut verifizieren, als historischen Datensatz kennzeichnen oder den Treffer entfernen. Ändere niemals nur die Ziel-URL zu einem ähnlich aussehenden Produkt und lasse die alte Beschreibung unverändert. Wenn ein historischer Hinweis erhalten bleibt, nenne Prüfdatum und erkläre, dass Verfügbarkeit und Chargengleichheit nicht bestätigt sind. Speichere intern den Grund der Änderung und den neuen Match-Status. Dadurch werden alte Seiten nicht zu Sammlungen unbelegter Behauptungen. Aktualisierung bedeutet nicht, ständig neue Wörter hinzuzufügen; wichtiger ist, falsche Exaktheit zu korrigieren, tote Wege zu beseitigen und den Leser weiterhin zu einer aktiven, überprüfbaren Quelle zu führen." ]],
    [["Ein datiertes Rechenblatt führen", "Speichere für jede Paketplanung Messstufe, Artikelzahl, Verpackungsannahme, gemessene Masse, äußere Maße, Einheit, aktive Route, Divisor, Rundungsfolge, Mindestbetrag, Zuschläge und Angebotsdatum. Trenne frühe Artikelgewichte vom späteren konsolidierten Paket. Berechne Volumengewicht mit denselben endgültigen Maßen für jede zulässige Linie und notiere, welcher Wert nach der jeweiligen Regel abrechenbar wird. Markiere unbekannte Angaben und ersetze sie erst nach Live-Prüfung. Ein reproduzierbares Rechenblatt ist wertvoller als ein einzelner Endbetrag, dessen Herkunft später niemand erklären kann. Bewahre außerdem Verpackungsfoto und besondere Anweisungen auf, wenn sie die Größe beeinflussen. So lässt sich feststellen, ob eine Abweichung aus Schutzmaterial, entfernten Boxen, Rundung, Mindestpreis oder einem Messfehler stammt, ohne eine ältere Schätzung fälschlich als aktuelle Quote darzustellen."], ["Planung erklären, keine Versprechen veröffentlichen", "Ein guter Versandartikel zeigt, welche Eingaben das Ergebnis verändern und an welcher Stelle eine Live-Prüfung nötig ist. Er kann tatsächliches und volumetrisches Gewicht, Verpackungsszenarien, Rundungsgrenzen und Routentabellen erklären, sollte aber keinen universellen Divisor oder dauerhaft gültigen Preis behaupten. Feste Aussagen zu Verfügbarkeit, Laufzeit, Versicherung, Zoll oder Einschränkungen benötigen Ziel, Datum und überprüfbare aktuelle Quelle. Schreibe bei Beispielen ausdrücklich, dass sie die Methode zeigen und keine Quote darstellen. Trenne Transportkosten von Steuer- und Einfuhrfragen. Fordere den Leser auf, nach Konsolidierung mit den echten Außenmaßen neu zu rechnen. Diese Form ist für SEO nützlich, weil sie eine konkrete Aufgabe vollständig beantwortet, ohne aus veränderlichen Carrier-Regeln eine zeitlose Zusage zu machen. Aktualisiere oder entferne Werte, wenn sie nicht mehr live bestätigt werden können." ]]
  ],
  es: [
    [["Usar una tabla de pruebas", "Crea una fila para cada zona crítica con detalle esperado, observación visible, referencia de imagen, nivel de confianza y acción siguiente. En calzado puede incluir identidad, talla, comparación del par, puntera, talón, unión de suela y medición; en ropa, variante, medidas planas, impresión, costuras, herrajes y etiquetas. Marca expresamente los ángulos ausentes. Así una foto principal atractiva no puede cancelar un defecto independiente y una zona vacía no se interpreta como perfecta. Usa lenguaje neutral y separa observación de valoración. Para cada solicitud adicional, explica qué foto o medida reduciría realmente la incertidumbre. La tabla no debe fabricar una puntuación, sino mostrar por qué decides enviar, volver a comprobar, cambiar o devolver. También permite comparar registros futuros sin tratar imágenes antiguas como una propiedad permanente del producto."], ["Mantener la conclusión dentro de la prueba", "Afirma solo lo que sostienen imágenes y datos: el estado visible de una unidad documentada en un momento concreto. Costuras limpias o una medida correcta no garantizan autenticidad, durabilidad ni igualdad del siguiente lote. Una foto histórica no demuestra stock ni condición de una compra futura. Peso y dimensiones de terceros siguen siendo referencias que deben parecer plausibles. Si una zona falta, escribe ‘no visible’ en lugar de ‘sin problemas’. Si luz o perspectiva debilitan la lectura, declara esa limitación. Evita juicios absolutos de calidad y describe características concretas, patrones repetidos e incertidumbre. Este límite aumenta la credibilidad y evita que el sitio convierta resultados de búsqueda, comentarios o miniaturas atractivas en promesas que el registro no puede justificar." ]],
    [["Construir enlaces internos según la siguiente tarea", "No enlaces páginas únicamente porque repiten la misma palabra clave. Pregunta qué necesita hacer el lector después. Un hallazgo con fuente exacta puede conducir a lectura de QC, mediciones o categoría correspondiente. Un artículo sobre enlaces muertos puede continuar con búsqueda por imagen y niveles de coincidencia. Una guía de talla puede enlazar después con consolidación y envío. Utiliza textos de enlace que nombren el destino y evita repetir el mismo término genérico en todo el sitio. Así se forma una arquitectura lógica: descubrir, conservar identidad, revisar pruebas, interpretar medidas, planificar paquete y abrir fuente activa. Esta separación reduce competencia interna entre páginas y ofrece a Google intenciones distintas. Cada enlace debe resolver una pregunta real del usuario, no aumentar artificialmente el número de enlaces."], ["Retirar resultados sin respaldo", "Revisa regularmente si destino, imagen, opción y afirmación siguen coincidiendo. Cuando una ficha se elimina, redirige o cambia de forma importante, vuelve a verificar, márcala como histórica o retírala. Nunca sustituyas únicamente la URL por un artículo parecido dejando la descripción antigua. Si conservas una nota histórica, muestra la fecha y explica que disponibilidad y lote no están confirmados. Guarda internamente el motivo del cambio y el nuevo nivel de coincidencia. De esta manera las páginas antiguas no se convierten en colecciones de afirmaciones sin pruebas. Actualizar no significa añadir palabras sin fin: significa corregir falsa exactitud, eliminar caminos muertos y mantener una ruta hacia una fuente activa y verificable." ]],
    [["Mantener una hoja de cálculo fechada", "Guarda fase de medición, número de artículos, supuesto de embalaje, masa, dimensiones exteriores, unidades, ruta activa, divisor, secuencia de redondeo, mínimo, recargos y fecha de cotización. Separa los pesos tempranos del artículo del paquete consolidado. Calcula el volumen con las mismas medidas finales para cada línea elegible y anota qué valor resulta facturable. Marca los datos desconocidos y sustitúyelos solo después de la verificación en vivo. Una hoja reproducible vale más que un total aislado cuya procedencia nadie puede explicar. Conserva también la foto del paquete y las instrucciones que afectan al tamaño. Así podrás saber si una diferencia procede de protección, cajas retiradas, redondeo, mínimo o error de medición sin presentar una estimación antigua como precio actual."], ["Publicar orientación, no promesas", "Un artículo útil explica qué variables cambian el resultado y dónde hace falta comprobar en vivo. Puede enseñar peso real y volumétrico, escenarios de embalaje, escalones de redondeo y tablas de rutas, pero no debe declarar un divisor universal ni un precio permanente. Las afirmaciones fijas sobre disponibilidad, plazo, seguro, aduana o restricciones necesitan destino, fecha y fuente actual verificable. Identifica los ejemplos como método, no como cotización. Separa costes de transporte de impuestos y legalidad. Indica que se debe recalcular tras consolidar con medidas exteriores reales. Este enfoque responde completamente a una tarea de búsqueda sin convertir reglas cambiantes en garantías. Actualiza o elimina cualquier dato que ya no pueda confirmarse en la página activa." ]]
  ],
  fr: [
    [["Utiliser un tableau de preuves", "Créez une ligne par zone critique avec détail attendu, observation visible, référence d’image, niveau de confiance et action suivante. Pour des chaussures : identité, taille, comparaison de la paire, avant, talon, jonction de semelle et mesure ; pour un vêtement : variante, mesures à plat, impression, coutures, pièces et étiquettes. Marquez explicitement les angles absents. Ainsi, une belle image principale n’efface pas un défaut indépendant et une zone vide n’est pas interprétée comme parfaite. Utilisez un langage neutre et séparez observation et jugement. Pour chaque demande supplémentaire, précisez quelle photo ou mesure réduira réellement l’incertitude. Le tableau ne sert pas à fabriquer une note, mais à expliquer pourquoi expédier, revérifier, échanger ou retourner. Il facilite aussi la comparaison future sans transformer d’anciennes images en propriété permanente."], ["Garder la conclusion dans les limites de la preuve", "Affirmez uniquement ce que montrent images et données : l’état visible d’une unité documentée à une date donnée. Des coutures propres ou une mesure correcte ne garantissent ni authenticité, ni durée, ni série suivante identique. Une photo historique ne prouve pas le stock ni l’état d’un futur achat. Poids et dimensions tiers restent des références à contrôler. Si une zone manque, écrivez ‘non visible’ plutôt que ‘sans problème’. Si lumière ou perspective affaiblissent l’analyse, mentionnez-le. Évitez les jugements absolus de qualité et décrivez caractéristiques concrètes, répétitions et incertitude. Cette limite renforce la crédibilité et empêche de transformer résultats, commentaires ou miniatures en promesses que le dossier ne peut soutenir." ]],
    [["Construire les liens internes autour de l’étape suivante", "Ne reliez pas deux pages uniquement parce qu’elles répètent le même mot-clé. Demandez ce que le lecteur doit faire ensuite. Une trouvaille à source exacte peut mener vers la lecture QC, les mesures ou la catégorie correspondante. Un article sur un lien mort peut continuer vers recherche par image et niveaux de correspondance. Un guide de taille peut ensuite conduire à consolidation et expédition. Utilisez des ancres qui nomment clairement la destination et évitez le même terme générique partout. Vous créez ainsi une architecture logique : découvrir, conserver l’identité, contrôler les preuves, interpréter les mesures, préparer le colis et ouvrir la source active. Cette séparation limite la concurrence interne et donne aux moteurs des intentions distinctes. Chaque lien doit répondre à une vraie question, pas simplement augmenter le nombre de liens."], ["Retirer les résultats non soutenus", "Revérifiez régulièrement que destination, image, option et affirmation correspondent encore. Lorsqu’une fiche disparaît, redirige ou change fortement, vérifiez de nouveau, marquez-la comme historique ou retirez-la. Ne remplacez jamais seulement l’URL par un produit proche tout en conservant l’ancienne description. Si une note historique reste, affichez la date et précisez que disponibilité et série ne sont pas confirmées. Conservez en interne la raison de la modification et le nouveau niveau de correspondance. Ainsi, les anciennes pages ne deviennent pas des collections d’affirmations sans preuve. Mettre à jour ne signifie pas ajouter sans fin du texte : cela signifie corriger la fausse exactitude, supprimer les chemins morts et maintenir une route vers une source active et vérifiable." ]],
    [["Conserver une feuille de calcul datée", "Enregistrez étape de mesure, nombre d’articles, hypothèse d’emballage, masse, dimensions externes, unités, ligne active, diviseur, ordre d’arrondi, minimum, suppléments et date du devis. Séparez les poids précoces du produit du colis consolidé. Calculez le volume avec les mêmes dimensions finales pour chaque ligne admissible et notez la valeur facturable. Marquez les inconnues et remplacez-les seulement après vérification directe. Une feuille reproductible vaut mieux qu’un total isolé dont l’origine devient impossible à expliquer. Gardez également la photo du colis et les instructions qui influencent sa taille. Vous pourrez ainsi déterminer si un écart vient de la protection, des boîtes retirées, de l’arrondi, du minimum ou d’une erreur, sans présenter une ancienne estimation comme prix actuel."], ["Publier une méthode, pas une promesse", "Un bon article explique quelles entrées modifient le résultat et où une vérification en direct est nécessaire. Il peut enseigner poids réel et volumétrique, scénarios d’emballage, paliers d’arrondi et comparaison de lignes, sans annoncer un diviseur universel ni un prix permanent. Toute affirmation fixe sur disponibilité, délai, assurance, douane ou restrictions exige destination, date et source actuelle vérifiable. Présentez les exemples comme méthode, non comme devis. Séparez coût de transport, fiscalité et légalité. Demandez un nouveau calcul après consolidation avec les dimensions externes réelles. Cette forme répond complètement à une intention de recherche sans transformer des règles variables en garantie. Mettez à jour ou retirez les valeurs impossibles à confirmer." ]]
  ],
  it: [
    [["Usare una tabella delle prove", "Crea una riga per ogni area critica con dettaglio previsto, osservazione visibile, riferimento dell’immagine, livello di fiducia e azione successiva. Per le scarpe: identità, taglia, confronto del paio, punta, tallone, giunzione della suola e misura; per l’abbigliamento: variante, misure piatte, stampa, cuciture, hardware ed etichette. Segna esplicitamente gli angoli mancanti. Così una bella immagine principale non cancella un difetto indipendente e una zona vuota non viene interpretata come perfetta. Usa linguaggio neutrale e separa osservazione e giudizio. Per ogni richiesta aggiuntiva specifica quale foto o misura ridurrà davvero l’incertezza. La tabella non deve creare un punteggio artificiale, ma mostrare perché spedisci, ricontrolli, cambi o restituisci. Aiuta inoltre a confrontare record futuri senza trattare vecchie immagini come proprietà permanente."], ["Tenere la conclusione entro le prove", "Afferma solo ciò che immagini e dati sostengono: la condizione visibile di un’unità documentata in un momento preciso. Cuciture pulite o una misura corretta non garantiscono autenticità, durata o lotto successivo identico. Una foto storica non prova stock o condizione di un acquisto futuro. Peso e dimensioni di terzi restano riferimenti da controllare. Se manca una zona, scrivi ‘non visibile’ invece di ‘nessun problema’. Se luce o prospettiva indeboliscono l’analisi, dichiaralo. Evita giudizi assoluti di qualità e descrivi caratteristiche concrete, schemi ripetuti e incertezza. Questo limite aumenta la credibilità e impedisce di trasformare risultati di ricerca, commenti o miniature in promesse che il record non può sostenere." ]],
    [["Costruire link interni sul passo successivo", "Non collegare due pagine solo perché ripetono la stessa parola chiave. Chiedi cosa deve fare il lettore dopo. Un prodotto con fonte esatta può portare alla lettura QC, alle misure o alla categoria corretta. Un articolo su un link morto può continuare con ricerca per immagine e livelli di corrispondenza. Una guida alla taglia può poi collegare consolidamento e spedizione. Usa testi di collegamento che nominano chiaramente la destinazione ed evita lo stesso termine generico ovunque. Nasce così un’architettura logica: scoprire, conservare identità, controllare prove, interpretare misure, pianificare pacco e aprire fonte attiva. Questa separazione riduce la concorrenza interna e offre ai motori intenti distinti. Ogni link deve risolvere una domanda reale, non soltanto aumentare il numero di collegamenti."], ["Rimuovere risultati non più supportati", "Controlla regolarmente che destinazione, immagine, opzione e affermazione coincidano ancora. Quando una scheda scompare, reindirizza o cambia molto, verifica di nuovo, segnala come storica oppure rimuovi. Non sostituire soltanto l’URL con un prodotto simile lasciando la descrizione precedente. Se conservi una nota storica, mostra la data e spiega che disponibilità e lotto non sono confermati. Registra internamente motivo della modifica e nuovo livello di match. Così le vecchie pagine non diventano raccolte di affermazioni prive di prova. Aggiornare non significa aggiungere testo senza fine: significa correggere falsa precisione, eliminare percorsi morti e mantenere una via verso una fonte attiva e verificabile." ]],
    [["Conservare un foglio di calcolo datato", "Registra fase della misura, numero di articoli, ipotesi di imballaggio, massa, dimensioni esterne, unità, rotta attiva, divisore, ordine di arrotondamento, minimo, supplementi e data del preventivo. Separa i pesi iniziali del prodotto dal pacco consolidato. Calcola il volume con le stesse dimensioni finali per ogni rotta idonea e annota quale valore diventa fatturabile. Segna i dati ignoti e sostituiscili solo dopo controllo dal vivo. Un foglio riproducibile vale più di un totale isolato di cui poi nessuno sa spiegare l’origine. Conserva anche foto del pacco e istruzioni che influenzano la dimensione. Potrai capire se una differenza deriva da protezione, scatole rimosse, arrotondamento, minimo o errore senza presentare una vecchia stima come prezzo attuale."], ["Pubblicare una guida, non una promessa", "Un articolo utile spiega quali input cambiano il risultato e dove serve una verifica dal vivo. Può insegnare peso reale e volumetrico, scenari di imballaggio, scaglioni di arrotondamento e confronto delle rotte, ma non deve dichiarare divisore universale o prezzo permanente. Affermazioni fisse su disponibilità, tempi, assicurazione, dogana o restrizioni richiedono destinazione, data e fonte attuale verificabile. Presenta gli esempi come metodo, non preventivo. Separa costi di trasporto, tasse e legalità. Chiedi di ricalcolare dopo il consolidamento con le dimensioni esterne reali. Questa forma risponde completamente all’intento di ricerca senza trasformare regole variabili in garanzie. Aggiorna o rimuovi valori non più confermabili." ]]
  ]
};

const readTimes = {
  en: ["23 min read", "23 min read", "22 min read"],
  de: ["23 Min. Lesezeit", "23 Min. Lesezeit", "22 Min. Lesezeit"],
  es: ["23 min de lectura", "23 min de lectura", "22 min de lectura"],
  fr: ["23 min de lecture", "23 min de lecture", "22 min de lecture"],
  it: ["23 min di lettura", "23 min di lettura", "22 min di lettura"]
};

const shippingAppendix = {
  en: ["Recheck whenever the parcel changes", "Any repack, removed box, added protection or route change can alter mass, dimensions, eligibility and billable weight. Repeat the calculation with the newest parcel data and save the revised date. Do not carry an earlier total into checkout after a physical or policy change. The final usable estimate is the one based on the finished parcel and the currently selected eligible route."],
  de: ["Bei jeder Paketänderung neu prüfen", "Jedes Umpacken, jede entfernte Verkaufsbox, zusätzlicher Schutz und jeder Routenwechsel kann Masse, Außenmaße, Zulässigkeit und Abrechnungsgewicht verändern. Rechne deshalb nach einer physischen Änderung mit den neuesten Paketdaten vollständig neu und speichere das aktualisierte Datum. Übernimm keinen früheren Gesamtbetrag in den Checkout, wenn Verpackung oder Regel inzwischen anders sind. Kontrolliere auch, ob eine neue Abmessung eine Rundungsgrenze, ein Seitenlimit oder einen Großpaketzuschlag auslöst. Die letzte brauchbare Schätzung ist immer diejenige, die auf dem fertigen Paket und der aktuell ausgewählten zulässigen Linie basiert. Wenn das Lager nachträglich Schutz ergänzt oder entfernt, gehört dieser Schritt erneut in das Rechenblatt, bevor bezahlt wird."],
  es: ["Recalcular cada vez que cambie el paquete", "Cualquier reembalaje, caja retirada, protección añadida o cambio de ruta puede modificar masa, dimensiones exteriores, elegibilidad y peso facturable. Repite todo el cálculo con los datos más recientes y guarda la nueva fecha. No lleves al checkout un total anterior cuando el paquete físico o la regla ya ha cambiado. Comprueba además si una nueva medida cruza un escalón de redondeo, un límite lateral o un recargo por gran volumen. La última estimación útil es siempre la basada en el paquete terminado y en la ruta elegible seleccionada en ese momento. Si el almacén añade o elimina protección después, registra el cambio y vuelve a verificar antes de pagar."],
  fr: ["Recalculer après chaque modification du colis", "Tout nouvel emballage, retrait de boîte, ajout de protection ou changement de ligne peut modifier masse, dimensions externes, admissibilité et poids facturable. Reprenez le calcul avec les données les plus récentes et sauvegardez la nouvelle date. N’utilisez pas au paiement un ancien total si le colis physique ou la règle a changé. Vérifiez aussi si une nouvelle mesure franchit un palier d’arrondi, une limite de côté ou un supplément grand colis. La dernière estimation utile est celle fondée sur le colis terminé et la ligne admissible actuellement choisie. Si l’entrepôt ajoute ou retire ensuite une protection, consignez le changement et contrôlez de nouveau avant paiement."],
  it: ["Ricalcolare dopo ogni modifica del pacco", "Ogni nuovo imballaggio, scatola rimossa, protezione aggiunta o cambio di rotta può modificare massa, dimensioni esterne, idoneità e peso fatturabile. Ripeti l’intero calcolo con i dati più recenti e salva la nuova data. Non portare al checkout un totale precedente se il pacco fisico o la regola sono cambiati. Controlla inoltre se una nuova misura supera uno scaglione di arrotondamento, un limite laterale o un supplemento per pacco voluminoso. L’ultima stima utile è sempre quella basata sul pacco finito e sulla rotta idonea selezionata in quel momento. Se il magazzino aggiunge o rimuove protezione in seguito, registra la modifica e verifica ancora prima del pagamento."]
};

export function applyParityArticles(articles, lang) {
  return articles.map((article, index) => ({
    ...article,
    readTime: readTimes[lang][index],
    sections: [...article.sections, ...parityExtensions[lang][index], ...finalParity[lang][index], ...(index === 2 ? [shippingAppendix[lang]] : [])]
  }));
}
