import { seoDetails } from "./seo-updates";
import type { Lang, ArticleSlug } from "./site-data";
import type { LocalizedArticle } from "./localized-articles";

const returnNotes = {
  en: ["The public refund policy describes a general 15-day window after receipt for eligible requests. Open your order promptly to confirm its deadline, product eligibility and required steps. A refund request, its approval and receipt of money are separate stages. Do not assume every opened or used product qualifies, or that a different size will be exchanged directly.", "The reviewed refund page says opened or activated electronics may be excluded; certain appliances need their original unopened seal. Underwear, cosmetics and some personal-care products have restrictions, with wrong-item or quality issues handled through the stated request process. Read the exact order conditions before removing labels, washing or modifying anything. Keep packaging and relevant evidence."],
  de: ["Die öffentliche Erstattungsrichtlinie nennt grundsätzlich 15 Tage nach Erhalt für berechtigte Anträge. Prüfe frühzeitig Frist, Produktberechtigung und notwendige Schritte deiner Bestellung. Antrag, Genehmigung und Geldeingang sind getrennte Phasen. Nicht jeder geöffnete oder benutzte Artikel ist berechtigt; eine andere Größe wird nicht automatisch direkt umgetauscht.", "Geöffnete oder aktivierte Elektronik kann laut geprüfter Seite ausgeschlossen sein; bestimmte Geräte benötigen die ungeöffnete Originalversiegelung. Für Unterwäsche, Kosmetik und einige Pflegeprodukte gelten Einschränkungen, wobei falsche Ware oder Qualitätsprobleme über den beschriebenen Antrag behandelt werden. Prüfe die konkreten Bedingungen vor Entfernen von Etiketten, Waschen oder Änderungen. Behalte Verpackung und Nachweise."],
  es: ["La política pública describe generalmente 15 días desde la recepción para solicitudes admisibles. Revisa pronto plazo, elegibilidad y pasos del pedido. Solicitar, aprobar y recibir el dinero son etapas distintas. No presupongas que todo artículo abierto o usado cumple, ni que otra talla se cambie directamente.", "La página revisada limita devoluciones de electrónica abierta o activada y exige el sello original sin abrir para ciertos aparatos. Ropa interior, cosméticos y algunos productos de cuidado tienen restricciones, con artículos equivocados o problemas de calidad tratados mediante la solicitud indicada. Lee las condiciones antes de quitar etiquetas, lavar o modificar. Conserva embalaje y pruebas."],
  fr: ["La politique publique décrit généralement 15 jours après réception pour les demandes admissibles. Vérifiez rapidement échéance, admissibilité et étapes dans votre commande. Demande, accord et réception des fonds sont distincts. Tout article ouvert ou utilisé n’est pas nécessairement admissible ; une autre taille n’est pas automatiquement échangée directement.", "La page consultée limite les retours d’électronique ouverte ou activée et exige le sceau d’origine intact pour certains appareils. Sous-vêtements, cosmétiques et certains soins ont des restrictions, avec traitement des erreurs d’article ou problèmes de qualité par la procédure indiquée. Lisez les conditions avant retrait d’étiquettes, lavage ou modification. Gardez emballage et preuves."],
  it: ["La politica pubblica descrive generalmente 15 giorni dal ricevimento per richieste ammissibili. Controlla presto termine, idoneità e passaggi dell’ordine. Richiesta, approvazione e accredito sono fasi diverse. Non presumere che ogni articolo aperto o usato sia idoneo o che una taglia diversa venga cambiata direttamente.", "La pagina consultata limita resi di elettronica aperta o attivata e richiede il sigillo originale intatto per alcuni apparecchi. Intimo, cosmetici e certi prodotti personali hanno restrizioni, con articoli errati o problemi di qualità gestiti dalla procedura indicata. Leggi le condizioni prima di togliere etichette, lavare o modificare. Conserva imballaggi e prove."],
} as const;
const titles = {
  en: ["Hacoo Shipping and Returns: Costs, Deadlines and Evidence", "How to Read Hacoo Reviews: Ratings, Context and Limits"],
  de: ["Hacoo Versand und Retouren: Kosten, Fristen und Belege", "Hacoo-Bewertungen verstehen: Sterne, Kontext und Grenzen"],
  es: ["Envíos y devoluciones Hacoo: costes, plazos y pruebas", "Cómo leer reseñas Hacoo: notas, contexto y límites"],
  fr: ["Livraison et retours Hacoo : frais, délais et preuves", "Lire les avis Hacoo : notes, contexte et limites"],
  it: ["Spedizione e resi Hacoo: costi, scadenze e prove", "Leggere recensioni Hacoo: voti, contesto e limiti"],
};
export function updateExistingArticles(all: Record<Lang, Record<ArticleSlug, LocalizedArticle>>) {
  for (const lang of Object.keys(all) as Lang[]) {
    const d = seoDetails[lang], a = all[lang]["hacoo-shipping-and-returns-guide"];
    a.title = titles[lang][0]; a.excerpt = ({en:"Check Hacoo shipping costs, delivery estimates, return deadlines and refund steps. Learn which order details and photos to keep before requesting help.",de:"Hacoo-Versandkosten, Lieferzeiten, Retourenfristen und Erstattung prüfen. Welche Bestelldaten und Fotos du für eine Anfrage aufbewahren solltest.",es:"Consulta gastos y plazos de envío Hacoo, devoluciones y reembolsos. Qué datos del pedido y fotografías guardar antes de pedir ayuda.",fr:"Vérifiez frais et délais Hacoo, conditions de retour et remboursement. Les informations de commande et photos à conserver avant une demande.",it:"Controlla costi e tempi Hacoo, scadenze dei resi e rimborso. Quali dati dell’ordine e foto conservare prima di richiedere assistenza."})[lang]; a.sourceNote = d.reference; a.sources = []; a.modified = "2026-10-10";
    a.sections = a.sections.map(([h, text], i) => [h, ({0:d.region, 1:d.timing, 3:d.cost[1], 4:returnNotes[lang][0], 5:returnNotes[lang][1], 7:d.instructions[1]} as Record<number,string>)[i] || text]);
    a.sections = [...a.sections, d.refund];
    const reviews = all[lang]["hacoo-reviews-what-users-report"];
    reviews.title = titles[lang][1];
    reviews.sourceNote = ({en:"Ratings and review counts in this article are historical observations from 28 August 2026, not current ratings. Use the method below and recheck the date, region and source before relying on any score.",de:"Bewertungen und Anzahlen dieses Artikels sind historische Beobachtungen vom 28. August 2026, keine aktuellen Werte. Prüfe Datum, Region und Quelle erneut, bevor du einen Wert verwendest.",es:"Las notas y cantidades de reseñas son observaciones históricas del 28 de agosto de 2026, no valores actuales. Revisa fecha, región y fuente antes de utilizar una puntuación.",fr:"Les notes et nombres d’avis sont des observations historiques du 28 août 2026, pas des valeurs actuelles. Revérifiez date, région et source avant de vous appuyer sur un score.",it:"Voti e quantità di recensioni sono osservazioni storiche del 28 agosto 2026, non valori attuali. Ricontrolla data, regione e fonte prima di usare un punteggio."})[lang];
    reviews.modified = "2026-10-10";
  }
}
