import type { ArticleText } from "./localized-articles";
import type { Lang } from "./site-data";

export const hvSlug = "hacoo-product-decision-matrix" as const;

const sources = [
  { name: "Hacoo — Trust Center", url: "https://www.hacoo.app/en-US/trust-center", supports: { en: "Official platform, community, creator and trust context", de: "Offizieller Plattform-, Community-, Creator- und Vertrauenskontext", es: "Contexto oficial de plataforma, comunidad, creadores y confianza", fr: "Contexte officiel de plateforme, communauté, créateurs et confiance", it: "Contesto ufficiale su piattaforma, community, creator e fiducia" } },
  { name: "Hacoo — Terms of Service", url: "https://www.hacoo.app/en-US/pages/terms-of-service", supports: { en: "Limits of independent creator and user-generated information", de: "Grenzen unabhängiger Creator- und Nutzerinformationen", es: "Límites de la información de creadores y usuarios", fr: "Limites des informations de créateurs et d’utilisateurs", it: "Limiti delle informazioni di creator e utenti" } },
] as const;

const en = {
  title: "Hacoo Product Decision Matrix: Compare a Shortlist Without Guessing",
  excerpt: "A weighted, evidence-aware way to compare Hacoo candidates after discovery—and to keep no-buy as a valid result.",
  keyword: "Hacoo product decision matrix",
  sourceNote: "Platform-role and evidence boundaries checked against Hacoo Trust Center and Terms of Service on 29 August 2026.",
  image: "/products/cnfanssp-travis-hoodie.webp",
  imageAlt: "Clothing candidate illustrating a post-shortlist Hacoo product decision matrix",
  imageCaption: "A shortlist starts the decision. The matrix tests each candidate against the same need, evidence standard and failure gates.",
  sources,
  sections: [
    ["Use the matrix only after you have a real shortlist", `A Hacoo product decision matrix is not another discovery feed. Use it after you have narrowed the field to two or three candidates that could plausibly solve the same wardrobe need. Write the need at the top: perhaps a lightweight everyday layer that fits over a T-shirt, a compact bag for a specific carry list, or shoes for a walking-heavy trip. Add the non-negotiable constraints—measurement, colour family, closure, capacity, deadline or maximum payable amount—that made each candidate eligible. If two products serve different jobs, do not force them into one score. Either choose the job first or build separate matrices. This protects the comparison from a common bias: letting the most dramatic image win even though it solves a different problem. Hacoo publicly describes a lifestyle discovery and shopping community with user and creator content. Inspiration is useful at the shortlist stage, but a final decision requires your own consistent criteria.`],
    ["Set pass-fail gates before assigning points", `Some requirements should never be averaged. Put them in a gate row and mark each candidate pass, unknown or fail. A required garment measurement below your minimum is a fail. A missing measurement is unknown, not an optimistic pass. A bag without evidence that it fits the necessary laptop size is unknown. A hard event date outside a sensible delivery buffer is a fail for that use case, even if every style score is high. Confirm the exact option and real destination before evaluating a gate, because colour, bundle, size, price and availability can change together. Stop a candidate when it fails a true non-negotiable. Do not let ten points for appearance cancel one failure that makes the item unusable. This is the first difference between a decision matrix and an unsupported “best Hacoo finds” ranking: the matrix can eliminate an attractive candidate and can leave every candidate rejected.`],
    ["Weight criteria by consequence, not excitement", `After gates, choose four to six scored criteria. Give the most decision-relevant factors the largest weights, and make all weights total 100. For an everyday jacket, you might use fit evidence 30, intended-use performance 25, compatibility with existing clothes 20, material information 15 and total-cost confidence 10. For a small bag, capacity evidence could replace fit. A decorative detail might deserve five points, not thirty, unless it is central to the brief. Write the weights before looking at candidate totals. Otherwise it is easy to change the rules so that a favourite wins. Weight represents consequence: how much does this factor change whether the item will actually be used? It does not represent how much text or social attention the product received. Keep price as one factor rather than the entire matrix, and assess the current exact option rather than an advertised starting price.`],
    ["Score evidence confidence separately from product appeal", `Use a simple 0–5 performance score, then add a separate confidence label. A score of five means the available evidence strongly meets your stated criterion; zero means it clearly does not. Confidence can be high, medium or low depending on the quality and recency of evidence. Measurements attached to the exact option are stronger than a general size label. Several consistent current images are stronger than one cropped creator post. A material specification is stronger than words such as “premium feel.” Hacoo's terms make clear that user and creator content is independent and may be inaccurate or outdated, so a confident creator statement does not become an official product fact. Do not award performance points for information that is merely absent. Mark the factor unknown or use a conservative score, then show the confidence label beside the total. A high total built on weak evidence is not equivalent to a slightly lower total built on clear facts.`],
    ["Calculate the weighted result without hiding uncertainty", `The arithmetic is straightforward: criterion weight multiplied by the candidate's score, divided by five. Suppose Candidate A receives 4/5 for fit evidence at weight 30; that contributes 24 points. If intended-use performance is 3/5 at weight 25, it adds 15. Continue across the row and sum to a maximum of 100. Candidate B may score 78 against A's 74, but the four-point gap is not decisive if B has low confidence on the highest-weight criterion. Add an uncertainty flag for every unknown worth at least 15 weight points. You can also calculate a range: treat an unknown as zero for the lower bound and as the best defensible score for the upper bound. A wide range means more evidence could change the winner. The matrix is a thinking aid, not a laboratory measurement; do not add decimal precision that the product evidence cannot support.`],
    ["Run a wardrobe compatibility check after the score", `A product can win its own matrix and still duplicate what you already own. List three real outfits or use situations in which the candidate would appear. Name the shoes, bottoms, layer or items carried rather than writing “goes with everything.” Check colour interaction, proportions, season, care burden and repetition. A hoodie intended for travel should work with the outerwear and bag already selected. A bag should accommodate the actual carry list and suit the planned transport. Shoes should match the walking conditions and the trouser shapes you use most. Deduct no arbitrary “wardrobe points”; instead, add a pass-fail question: can I name at least three credible uses without buying another supporting item? This keeps the decision centred on wardrobe value rather than novelty. If the answer is no, return to the original brief or reject the candidate.`],
    ["Use tie-breakers that reveal the safer choice", `When totals are close, compare the candidates in this order: fewer failed or unknown gates, stronger evidence on the highest-weight criterion, lower consequence if the assumption is wrong, and easier compatibility with the existing wardrobe. Only then use preference as the tie-breaker. Consider two jackets with near-identical scores. One has precise measurements and ordinary styling; the other looks more distinctive but lacks the chest width needed to judge layering. The first is the safer current decision. That does not prove higher quality; it means the available evidence supports the defined need more clearly. Save the date, exact option and reason for the tie-break. If new information arrives, update the affected row rather than rewriting the whole conclusion. A transparent revision is a strength because live listings and user-generated information can change.`],
    ["Keep no-buy and recheck as legitimate outcomes", `Finish with one of four outcomes: choose A, choose B, recheck a named missing fact, or buy neither. Set a minimum result before calculation—for example, every gate must pass and the weighted score must reach 70 with no low-confidence unknown in a 20-point criterion. The number is your rule, not a platform guarantee. If no candidate reaches it, preserve the wardrobe need and wait for better evidence or a better candidate. Before acting, reopen the exact live option and verify that the facts used by the matrix still apply. Record one sentence explaining the decision: “Candidate A meets the travel-layer brief because its recorded measurements, compatible outfits and closure evidence pass my gates.” If the sentence requires authenticity, quality, price or delivery claims that the evidence cannot support, revise it. A good Hacoo product decision matrix reduces motivated guessing; it does not manufacture certainty.`],
  ] as const,
};

const translations: Record<Exclude<Lang, "en">, ArticleText> = {
  de: { title: "Hacoo Produkt-Entscheidungsmatrix: eine Auswahlliste ohne Raten vergleichen", excerpt: "Ein gewichteter, belegorientierter Vergleich nach der Entdeckung – mit Nichtkauf als gültigem Ergebnis.", keyword: "Hacoo Produkt-Entscheidungsmatrix", sourceNote: "Plattformrolle und Beleggrenzen am 29. August 2026 anhand Trust Center und Nutzungsbedingungen geprüft.", imageAlt: "Kleidungskandidat als Beispiel für eine Hacoo Entscheidungsmatrix", imageCaption: "Die Auswahlliste startet die Entscheidung; die Matrix prüft jeden Kandidaten nach Bedarf, Belegen und Ausschlusskriterien.", sections: [
    ["Die Matrix erst nach einer echten Auswahlliste nutzen", "Vergleiche zwei oder drei Kandidaten, die denselben Garderobenbedarf lösen. Schreibe Zweck und Muss-Kriterien wie Maß, Farbe, Verschluss, Kapazität, Termin oder Höchstbetrag oben hin. Produkte mit verschiedenen Aufgaben gehören in getrennte Matrizen. Hacoo beschreibt eine Lifestyle-Entdeckungs- und Shopping-Community; Inspiration hilft beim Finden, nicht als fertige Entscheidung."],
    ["Ausschlusskriterien vor Punkten festlegen", "Markiere Muss-Kriterien als bestanden, unbekannt oder nicht bestanden. Ein fehlendes Maß bleibt unbekannt; ein Termin ohne realistischen Puffer kann scheitern. Prüfe Option und Zielregion. Ein echter Ausschluss darf nicht durch Stilpunkte aufgehoben werden, und alle Kandidaten dürfen ausscheiden."],
    ["Nach Konsequenz statt Begeisterung gewichten", "Wähle vier bis sechs Kriterien mit zusammen 100 Punkten, etwa Passformbelege 30, Einsatzzweck 25, Garderobenkompatibilität 20, Materialangaben 15 und Kostensicherheit 10. Gewichte vor den Summen festlegen; Preis ist ein Faktor und bezieht sich auf die genaue Option."],
    ["Belegsicherheit getrennt bewerten", "Vergib 0–5 Leistungspunkte und zusätzlich hohe, mittlere oder niedrige Sicherheit. Exakte Maße sind stärker als Größenbuchstaben; mehrere aktuelle Bilder stärker als ein zugeschnittener Creator-Post. Nutzer- und Creator-Inhalte sind keine offiziellen Produktfakten. Fehlende Angaben erhalten keine optimistischen Punkte."],
    ["Gewichtet rechnen und Unsicherheit zeigen", "Gewicht mal Punktzahl geteilt durch fünf ergibt den Beitrag. 4/5 bei Gewicht 30 sind 24 Punkte. Kennzeichne Unbekanntes ab 15 Gewichtspunkten und nutze bei Bedarf Unter- und Obergrenzen. Ein kleiner Abstand mit schwachen Belegen bestimmt keinen Sieger; vermeide falsche Dezimalpräzision."],
    ["Garderobenkompatibilität prüfen", "Nenne drei reale Outfits oder Nutzungen mit vorhandenen Schuhen, Hosen, Jacken oder Inhalt. Prüfe Farbe, Proportion, Saison und Pflege. Die Frage lautet: Gibt es drei glaubhafte Nutzungen ohne weitere Käufe? Wenn nein, Bedarf neu prüfen oder Kandidat ablehnen."],
    ["Sichere Tie-Breaker verwenden", "Bei engem Ergebnis zählen zuerst weniger unbekannte Gates, stärkere Belege beim höchsten Gewicht, geringere Folgen einer falschen Annahme und bessere vorhandene Kombinationen. Erst danach entscheidet Geschmack. Datum, Option und Begründung speichern und nur betroffene Zeilen aktualisieren."],
    ["Nichtkauf und Nachprüfung zulassen", "Ende mit A, B, gezielter Nachprüfung oder keinem Kauf. Definiere vorher Mindestwert und Belegregel. Öffne die genaue Option erneut und schreibe einen Satz, warum sie den Bedarf erfüllt. Erfordert der Satz unbelegte Echtheits-, Qualitäts-, Preis- oder Lieferzusagen, überarbeite ihn."],
  ] },
  es: { title: "Matriz de decisión de productos Hacoo: compara una lista sin adivinar", excerpt: "Comparación ponderada y basada en pruebas tras el descubrimiento, con no comprar como resultado válido.", keyword: "matriz de decisión de productos Hacoo", sourceNote: "Función de la plataforma y límites de evidencia revisados en Trust Center y Términos el 29 de agosto de 2026.", imageAlt: "Candidato de ropa que ilustra una matriz de decisión Hacoo", imageCaption: "La lista inicia la decisión; la matriz prueba cada candidato con la misma necesidad, evidencia y filtros.", sections: [
    ["Usa la matriz después de una lista real", "Compara dos o tres candidatos para la misma necesidad de armario. Escribe uso y requisitos como medida, color, cierre, capacidad, fecha o importe máximo. Si cumplen trabajos distintos, usa matrices separadas. Hacoo describe una comunidad lifestyle de descubrimiento y compras; la inspiración sirve para encontrar, no para decidir sola."],
    ["Fija filtros de aprobado antes de puntuar", "Marca cada requisito imprescindible como aprobado, desconocido o fallido. Una medida ausente sigue desconocida; una fecha sin margen puede fallar. Confirma opción y destino. Un fallo real no se compensa con puntos de estilo y todos los candidatos pueden quedar rechazados."],
    ["Pondera por consecuencia, no emoción", "Elige cuatro a seis criterios que sumen 100: ajuste 30, uso 25, compatibilidad 20, material 15 y confianza de coste 10, por ejemplo. Define pesos antes de ver totales. El precio es un factor y debe corresponder a la opción exacta."],
    ["Separa resultado y confianza", "Puntúa 0–5 y añade confianza alta, media o baja. Medidas exactas superan etiquetas; varias imágenes actuales superan una publicación recortada. El contenido de usuarios o creadores no se vuelve hecho oficial. No otorgues puntos optimistas a datos ausentes."],
    ["Calcula sin ocultar incertidumbre", "Multiplica peso por nota y divide entre cinco: 4/5 con peso 30 aporta 24. Señala desconocidos de 15 puntos o más y usa rango inferior y superior si pueden cambiar el ganador. Una diferencia pequeña con pruebas débiles no es decisiva; evita precisión decimal falsa."],
    ["Comprueba compatibilidad con el armario", "Nombra tres conjuntos o usos reales con zapatos, pantalones, capas o contenido que ya tienes. Revisa color, proporción, temporada y cuidado. ¿Hay tres usos creíbles sin comprar apoyo adicional? Si no, vuelve a la necesidad o rechaza."],
    ["Desempata por seguridad", "Primero menos filtros desconocidos, mejor evidencia en el mayor peso, menor consecuencia de error y mejor compatibilidad. El gusto queda al final. Guarda fecha, opción y razón; si llega información nueva, actualiza la fila afectada."],
    ["Acepta revisar o no comprar", "Termina con A, B, revisar un dato concreto o ninguno. Define antes un mínimo y una regla de confianza. Reabre la opción y explica en una frase por qué cumple la necesidad. Si exige promesas no probadas de autenticidad, calidad, precio o entrega, corrígela."],
  ] },
  fr: { title: "Matrice de décision produit Hacoo : comparer une liste sans deviner", excerpt: "Une comparaison pondérée et consciente des preuves après la découverte, avec le non-achat comme résultat valable.", keyword: "matrice de décision produit Hacoo", sourceNote: "Rôle de la plateforme et limites des preuves vérifiés dans Trust Center et Conditions le 29 août 2026.", imageAlt: "Candidat vêtement illustrant une matrice de décision Hacoo", imageCaption: "La liste lance la décision; la matrice teste chaque candidat selon le même besoin, les mêmes preuves et filtres.", sections: [
    ["Utiliser la matrice après une vraie présélection", "Comparez deux ou trois candidats répondant au même besoin. Notez usage et contraintes: mesure, couleur, fermeture, capacité, date ou montant maximum. Des fonctions différentes exigent des matrices séparées. Hacoo décrit une communauté lifestyle de découverte et d'achat; l'inspiration aide à trouver, pas à décider seule."],
    ["Fixer les critères éliminatoires avant les points", "Marquez chaque exigence comme réussie, inconnue ou échouée. Une mesure absente reste inconnue; un délai sans marge peut échouer. Confirmez option et destination. Un échec essentiel ne se compense pas par le style et tous les candidats peuvent être rejetés."],
    ["Pondérer par conséquence, pas par excitation", "Choisissez quatre à six critères totalisant 100, par exemple coupe 30, usage 25, compatibilité 20, matière 15 et confiance coût 10. Fixez les poids avant les totaux. Le prix est un facteur lié à l'option exacte."],
    ["Séparer performance et confiance", "Notez 0–5 puis confiance haute, moyenne ou faible. Les mesures exactes valent plus qu'une taille; plusieurs images récentes plus qu'un post recadré. Le contenu utilisateur ou créateur n'est pas un fait officiel. N'accordez pas de points optimistes aux données absentes."],
    ["Calculer sans cacher l'incertitude", "Poids multiplié par note divisé par cinq: 4/5 à poids 30 donne 24. Signalez chaque inconnue de 15 points ou plus et utilisez une fourchette si elle peut changer le gagnant. Un faible écart avec preuves faibles n'est pas décisif; évitez les décimales artificielles."],
    ["Vérifier la compatibilité garde-robe", "Nommez trois tenues ou usages avec chaussures, bas, couches ou contenu déjà possédés. Vérifiez couleur, proportion, saison et entretien. Trois usages crédibles sans achat complémentaire? Sinon, revoyez le besoin ou rejetez."],
    ["Départager par la sécurité", "D'abord moins de filtres inconnus, meilleures preuves au poids principal, moindre conséquence d'erreur et meilleure compatibilité. Le goût vient ensuite. Gardez date, option et raison; mettez à jour seulement la ligne touchée."],
    ["Accepter la revérification ou le non-achat", "Terminez par A, B, vérification d'un fait précis ou aucun achat. Fixez seuil et règle de confiance avant calcul. Rouvrez l'option et justifiez-la en une phrase. Si elle dépend d'une promesse non prouvée d'authenticité, qualité, prix ou livraison, révisez."],
  ] },
  it: { title: "Matrice decisionale Hacoo: confrontare una lista senza indovinare", excerpt: "Un confronto ponderato e consapevole delle prove dopo la scoperta, con il non acquisto come risultato valido.", keyword: "matrice decisionale prodotti Hacoo", sourceNote: "Ruolo della piattaforma e limiti delle prove verificati in Trust Center e Termini il 29 agosto 2026.", imageAlt: "Candidato di abbigliamento che illustra una matrice decisionale Hacoo", imageCaption: "La lista avvia la decisione; la matrice prova ogni candidato con lo stesso bisogno, prove e filtri.", sections: [
    ["Usare la matrice dopo una vera shortlist", "Confronta due o tre candidati per lo stesso bisogno. Scrivi uso e vincoli: misura, colore, chiusura, capacità, data o importo massimo. Funzioni diverse richiedono matrici separate. Hacoo descrive una community lifestyle di scoperta e acquisto; l'ispirazione aiuta a trovare, non decide da sola."],
    ["Fissare i criteri eliminatori prima dei punti", "Segna ogni requisito come superato, sconosciuto o fallito. Una misura assente resta sconosciuta; una scadenza senza margine può fallire. Conferma opzione e destinazione. Un fallimento essenziale non si compensa con lo stile e tutti i candidati possono essere respinti."],
    ["Pesare per conseguenza, non entusiasmo", "Scegli quattro-sei criteri per un totale di 100, ad esempio vestibilità 30, uso 25, compatibilità 20, materiale 15 e fiducia costo 10. Fissa i pesi prima dei totali. Il prezzo è un fattore riferito all'opzione esatta."],
    ["Separare risultato e fiducia", "Assegna 0–5 e fiducia alta, media o bassa. Misure esatte valgono più di etichette; più immagini attuali più di un post ritagliato. Il contenuto di utenti o creator non diventa fatto ufficiale. Non dare punti ottimistici ai dati assenti."],
    ["Calcolare senza nascondere l'incertezza", "Peso per voto diviso cinque: 4/5 con peso 30 dà 24. Segnala ignoti da 15 punti e usa un intervallo se possono cambiare il vincitore. Un piccolo divario con prove deboli non è decisivo; evita decimali fittizi."],
    ["Controllare la compatibilità col guardaroba", "Nomina tre outfit o usi reali con scarpe, pantaloni, strati o contenuto già presenti. Verifica colore, proporzione, stagione e cura. Ci sono tre usi credibili senza altri acquisti? Se no, rivedi il bisogno o respingi."],
    ["Spareggiare con il criterio più sicuro", "Prima meno filtri ignoti, prove migliori sul peso maggiore, conseguenze minori di un errore e compatibilità più facile. Il gusto viene dopo. Salva data, opzione e motivo; aggiorna solo la riga coinvolta."],
    ["Accettare ricontrollo o non acquisto", "Concludi con A, B, verifica di un fatto preciso o nessun acquisto. Definisci soglia e regola di fiducia prima. Riapri l'opzione e giustifica in una frase. Se dipende da promesse non provate di autenticità, qualità, prezzo o consegna, rivedila."],
  ] },
};

export const hvArticle = en;
export const hvArticleTexts: Record<Lang, ArticleText> = { en, ...translations };
