import type { ArticleText } from "./localized-articles";
import type { Lang } from "./site-data";

export const hvUseCaseSlug = "hacoo-use-case-must-have-criteria" as const;

const en = {
  title: "Hacoo Must-Have Criteria: Turn One Use Case Into a Fair Comparison",
  excerpt: "Convert one real use case into pass-or-fail criteria after you already have a Hacoo shortlist, without letting the most attractive candidate rewrite the need.",
  keyword: "Hacoo must-have criteria",
  sourceNote: "Platform identity and user-content evidence limits were rechecked against current Hacoo public materials on 18 September 2026.",
  image: "/products/cnfanssp-travis-hoodie.webp",
  imageAlt: "Clothing candidate used to illustrate Hacoo must-have criteria after a shortlist exists",
  imageCaption: "Begin with one intended use, then test every shortlisted candidate against the same observable requirements.",
  sources: [] as const,
  sections: [
    ["Freeze one real use case before comparing candidates", `This method begins after two or three Hacoo candidates have already been found. Do not reopen discovery or ask which product looks most exciting. Write one sentence describing the job the purchase must perform: “a light outer layer for a cool, wet commute that fits over one sweatshirt,” “a compact bag for a tablet, bottle and daily essentials,” or “shoes for several hours of city walking.” Include the user, setting, frequency and constraint that would make the product useful. A candidate suitable for a festival outfit may not satisfy a daily commute, even when both are jackets. Hacoo currently describes itself as a content-sharing community built around ideas, creators and personal experience. That material can inspire a shortlist, but it does not define your requirement. Lock the use case before reading more captions or reviews so a persuasive image cannot quietly change the task. If the use case contains two unrelated jobs, split it into two decisions rather than forcing one product to do everything.`],
    ["Translate the use case into observable must-haves", `Turn the sentence into four to seven conditions that can be checked on the exact candidate. Use nouns, numbers or visible functions instead of praise words. “Fits over my reference sweatshirt” is testable when you record the sweatshirt width and the candidate garment measurement; “comfortable” is not testable from a listing. “Holds a 28-centimetre tablet and closes fully” is clearer than “roomy.” A useful list may include minimum internal dimensions, required closure, exact colour family, selected quantity, compatible model, maximum garment length or a hard budget ceiling for the item. Keep preference out of this first pass. Decorative details, trend appeal and a favourite shade belong later unless the use case truly fails without them. A must-have has a consequence: if the condition is not met, the product cannot perform the named job. If you cannot explain the consequence, rewrite the item as a preference or remove it.`],
    ["Define the evidence that can satisfy each criterion", `A criterion is only useful when you state what evidence counts. For a measurement, require a current chart or visible specification tied to the exact size. For capacity, require dimensions or a clear internal layout rather than a styled photograph. For a phone case, require the precise device model and cut-out arrangement. For a set, require a written contents list rather than assuming every object in a promotional image is included. Hacoo’s public intellectual-property guidance says content and links can come from independent creators and users; that means a creator statement is not automatically an official product specification. Record evidence as direct, indirect or missing. Direct evidence answers the criterion for the chosen variant. Indirect evidence suggests an answer but leaves an important assumption. Missing evidence supplies none. This is not a quality score and does not prove authenticity or performance. It simply stops an unsupported statement from being treated as a passed requirement.`],
    ["Apply the criteria to exact variants, not broad listings", `A Hacoo listing can contain several colours, sizes, bundles or versions. Compare the option you could actually choose, not an average impression of the whole page. Copy the exact option label beside each candidate and note whether selecting it changes the image, displayed specification, contents or price. A size chart shown elsewhere on the page may not clearly apply to every version. A bag photograph may show a long strap although the selected bundle does not list one. A low starting price may refer to a smaller or incomplete option. When the evidence cannot be tied to the variant, mark the criterion unknown. Do not borrow an answer from another candidate or a visually similar product. The comparison remains fair only when every row asks the same question of the same level of product identity. If a candidate has disappeared or changed since the shortlist was made, remove it or rebuild its record before scoring anything else.`],
    ["Use pass, unknown and fail before any weighted score", `Create a table with one row per must-have and one column per candidate. Allow only three results: pass, unknown or fail. Pass means the required evidence supports the condition for the exact variant. Fail means the evidence clearly contradicts it. Unknown means the necessary fact is absent, ambiguous or detached from the selected option. Do not convert unknown into half a pass merely because you prefer the design. Add a short evidence note and the date checked to every result. Then apply the rule consistently: a true fail eliminates the candidate, while a high-consequence unknown pauses the decision until the fact is resolved. This gate comes before price points, style scores or weighted preferences. It prevents a product from winning with attractive secondary details while missing the reason for the purchase. The table may eliminate every candidate. That is a valid result and evidence that the shortlist, not the criteria, needs to change.`],
    ["Keep preferences separate and deliberately lower priority", `Only after a candidate passes the must-have gate should you compare nice-to-haves. These may include a preferred shade within the acceptable colour family, a pocket arrangement, a decorative finish or a lower current item price. Write them in a separate section and rank them rather than quietly promoting them to requirements. This protects the original use case from choice overload. It also makes trade-offs readable: Candidate A and Candidate B both meet the commute requirement, but A has clearer care information while B has the preferred colour. The reader can now choose consciously instead of pretending the colour determined function. Do not award extra points for vague terms such as “premium,” “viral” or “best seller” unless the term supplies evidence for a stated need—which it usually does not. Popularity, creator enthusiasm and polished photography can influence preference, but they cannot repair a failed dimension, incompatible model or missing included part.`],
    ["Finish with a short decision statement and a stop rule", `End the comparison with one sentence that names the use case, the selected candidate and the evidence supporting every must-have. For example: “Candidate B remains because its recorded width supports the planned layer, the selected option lists the required closure, and the current dimensions fit the carry limit.” If the sentence needs an unsupported claim about material performance, comfort, quality, authenticity, delivery or future availability, the decision is not ready. Write the unresolved fact instead. Set a stop rule as well: choose a passing candidate only when every high-consequence criterion has direct evidence; otherwise request clarification, wait for better information or choose none. Reopen the exact live option immediately before acting because pages, variants and prices can change. This final check does not guarantee an outcome. It shows that the choice still matches the requirement you fixed before comparison and that uncertainty has not been disguised as confidence.`],
  ] as const,
};

const translations: Record<Exclude<Lang, "en">, ArticleText> = {
  de: {
    title: "Hacoo-Musskriterien: einen Anwendungsfall fair vergleichen",
    excerpt: "Einen konkreten Einsatz nach der Vorauswahl in klare Musskriterien übersetzen, ohne dass der attraktivste Kandidat den Bedarf verändert.",
    keyword: "Hacoo Musskriterien",
    sourceNote: "Plattformidentität und Grenzen nutzergenerierter Inhalte wurden am 18. September 2026 anhand aktueller öffentlicher Hacoo-Unterlagen geprüft.",
    imageAlt: "Kleidungskandidat als Beispiel für Hacoo-Musskriterien nach einer Vorauswahl",
    imageCaption: "Mit einem Einsatzzweck beginnen und alle Kandidaten an denselben beobachtbaren Anforderungen prüfen.",
    sections: [
      ["Vor dem Vergleich einen realen Einsatzzweck festschreiben", `Diese Methode beginnt erst, wenn bereits zwei oder drei Hacoo-Kandidaten vorliegen. Öffne die Suche nicht erneut und frage nicht, welches Produkt am spannendsten wirkt. Formuliere einen Satz über die konkrete Aufgabe: eine leichte Außenschicht für einen kühlen, nassen Arbeitsweg über einem Sweatshirt, eine kompakte Tasche für Tablet, Flasche und Alltagsgegenstände oder Schuhe für mehrere Stunden Stadtweg. Nenne Nutzer, Umgebung, Häufigkeit und die Bedingung, die den Artikel brauchbar macht. Eine Jacke für ein Festival erfüllt nicht automatisch den täglichen Arbeitsweg. Hacoo beschreibt sich aktuell als Content-Community rund um Ideen, Creator und persönliche Erfahrungen. Das kann eine Vorauswahl inspirieren, definiert aber nicht deinen Bedarf. Sperre den Einsatzzweck, bevor du weitere Bildtexte oder Bewertungen liest, damit ein starkes Bild die Aufgabe nicht unbemerkt ändert. Enthält der Satz zwei unabhängige Aufgaben, trenne sie in zwei Entscheidungen.`],
      ["Den Einsatzzweck in beobachtbare Musskriterien übersetzen", `Forme den Satz in vier bis sieben Bedingungen um, die sich an der exakten Variante prüfen lassen. Nutze Substantive, Zahlen oder sichtbare Funktionen statt Lob. „Passt über mein Referenz-Sweatshirt“ ist prüfbar, wenn dessen Breite und das Kleidungsmaß des Kandidaten notiert sind; „bequem“ lässt sich aus einer Produktseite nicht belegen. „Nimmt ein 28-Zentimeter-Tablet auf und lässt sich vollständig schließen“ ist klarer als „geräumig“. Die Liste kann Mindestinnenmaße, erforderlichen Verschluss, genaue Farbfamilie, Stückzahl, kompatibles Modell, maximale Länge oder eine harte Artikelpreisgrenze enthalten. Vorlieben bleiben zunächst draußen. Dekor, Trendwirkung und Lieblingsfarbe folgen später, sofern die Aufgabe ohne sie nicht wirklich scheitert. Ein Musskriterium hat eine Folge: Wird es nicht erfüllt, kann der Artikel die benannte Aufgabe nicht leisten. Lässt sich diese Folge nicht erklären, wird das Kriterium zur Vorliebe oder entfällt.`],
      ["Festlegen, welcher Beleg ein Kriterium erfüllt", `Ein Kriterium ist nur nützlich, wenn vorher feststeht, welcher Nachweis genügt. Bei Maßen braucht es eine aktuelle Tabelle oder sichtbare Spezifikation für die genaue Größe. Bei Kapazität zählen Abmessungen oder eine klare Innenaufteilung, nicht nur ein inszeniertes Foto. Eine Handyhülle benötigt das genaue Gerätemodell und passende Ausschnitte. Bei Sets gilt eine schriftliche Inhaltsliste; nicht jedes Objekt im Werbebild ist automatisch enthalten. Hacoos öffentliche Hinweise zum geistigen Eigentum erklären, dass Inhalte und Links von unabhängigen Creatorn und Nutzern stammen können. Eine Creator-Aussage ist daher nicht automatisch eine offizielle Produktspezifikation. Markiere Nachweise als direkt, indirekt oder fehlend. Direkt beantwortet die Frage für die gewählte Variante, indirekt lässt eine wesentliche Annahme offen, fehlend liefert keine Antwort. Das ist keine Qualitätswertung und beweist weder Echtheit noch Leistung. Es verhindert lediglich, dass eine unbelegte Aussage als erfüllte Anforderung gilt.`],
      ["Exakte Varianten statt ganzer Angebote vergleichen", `Ein Hacoo-Angebot kann mehrere Farben, Größen, Sets oder Versionen enthalten. Vergleiche die tatsächlich wählbare Option, nicht den Gesamteindruck der Seite. Kopiere die genaue Optionsbezeichnung zu jedem Kandidaten und notiere, ob Auswahl, Bild, Spezifikation, Inhalt oder Preis wechseln. Eine irgendwo angezeigte Größentabelle muss nicht eindeutig für jede Version gelten. Ein Taschenfoto kann einen langen Gurt zeigen, obwohl das ausgewählte Set ihn nicht aufführt. Ein niedriger Einstiegspreis kann zu einer kleineren oder unvollständigen Option gehören. Lässt sich der Nachweis nicht der Variante zuordnen, bleibt das Kriterium unbekannt. Übernimm keine Antwort von einem anderen Kandidaten oder ähnlich aussehenden Produkt. Fair bleibt der Vergleich nur, wenn jede Zeile dieselbe Frage auf derselben Identitätsebene stellt. Ist ein Kandidat verschwunden oder seit der Vorauswahl verändert, entferne ihn oder baue seinen Datensatz neu auf.`],
      ["Vor jeder Gewichtung bestanden, unbekannt oder nicht bestanden nutzen", `Erstelle eine Tabelle mit einer Zeile je Musskriterium und einer Spalte je Kandidat. Erlaubt sind nur bestanden, unbekannt und nicht bestanden. Bestanden bedeutet, dass der Nachweis die Bedingung für die exakte Variante stützt. Nicht bestanden bedeutet einen klaren Widerspruch. Unbekannt gilt bei fehlenden, mehrdeutigen oder von der Option gelösten Angaben. Mache daraus keinen halben Erfolg, nur weil dir das Design gefällt. Ergänze zu jedem Ergebnis eine kurze Belegnotiz und das Prüfdatum. Danach gilt die Regel konsequent: Ein echtes Scheitern entfernt den Kandidaten; ein folgenschweres Unbekannt stoppt die Entscheidung bis zur Klärung. Diese Schranke kommt vor Preis-, Stil- oder Gewichtungspunkten. So gewinnt kein Produkt mit attraktiven Nebendetails, obwohl es den Kaufgrund verfehlt. Die Tabelle darf alle Kandidaten ausschließen; dann muss die Vorauswahl geändert werden, nicht die Kriterien.`],
      ["Vorlieben getrennt und bewusst niedriger priorisieren", `Erst nach bestandener Mussprüfung werden Wunschmerkmale verglichen. Dazu gehören ein bevorzugter Farbton innerhalb der akzeptierten Farbfamilie, Taschenanordnung, dekoratives Finish oder ein niedrigerer aktueller Artikelpreis. Schreibe sie in einen eigenen Abschnitt und ordne sie, statt sie unbemerkt zu Anforderungen zu machen. Das schützt den Einsatzzweck vor Auswahlüberlastung und zeigt den Tausch klar: A und B erfüllen den Arbeitsweg, A besitzt aber klarere Pflegeangaben, B die Lieblingsfarbe. Nun ist die Wahl bewusst, ohne die Farbe als Funktion auszugeben. Vergib keine Zusatzpunkte für Begriffe wie „Premium“, „viral“ oder „Bestseller“, sofern sie keinen Beleg für den Bedarf liefern. Popularität, Creator-Begeisterung und perfekte Bilder dürfen eine Vorliebe beeinflussen, reparieren aber kein falsches Maß, inkompatibles Modell oder fehlendes Teil.`],
      ["Mit Entscheidungssatz und Stopregel enden", `Beende den Vergleich mit einem Satz, der Einsatzzweck, Kandidat und Beleg für jedes Muss nennt. Beispiel: „B bleibt, weil die notierte Breite die geplante Schicht erlaubt, die gewählte Option den Verschluss aufführt und die aktuellen Maße das Tragelimit einhalten.“ Braucht der Satz unbelegte Aussagen zu Materialleistung, Komfort, Qualität, Echtheit, Lieferung oder künftiger Verfügbarkeit, ist die Entscheidung nicht fertig. Nenne stattdessen die offene Tatsache. Lege außerdem eine Stopregel fest: Nur wählen, wenn alle folgenreichen Kriterien direkt belegt sind; sonst nachfragen, auf bessere Angaben warten oder keinen Kandidaten wählen. Öffne die genaue Live-Option unmittelbar vor dem Handeln erneut, da Seiten, Varianten und Preise wechseln. Diese Schlussprüfung garantiert nichts. Sie zeigt, dass die Wahl noch zur vorher festgeschriebenen Anforderung passt und Unsicherheit nicht als Gewissheit erscheint.`],
    ],
  },
  es: {
    title: "Criterios imprescindibles de Hacoo: compara un caso de uso con justicia",
    excerpt: "Convierte un uso real en criterios de aprobado o descarte después de crear la lista, sin dejar que el candidato más atractivo cambie la necesidad.",
    keyword: "criterios imprescindibles Hacoo",
    sourceNote: "La identidad de la plataforma y los límites del contenido de usuarios se revisaron en fuentes públicas actuales de Hacoo el 18 de septiembre de 2026.",
    imageAlt: "Prenda candidata que ilustra criterios imprescindibles de Hacoo después de crear una lista",
    imageCaption: "Empieza por un uso previsto y somete cada candidato a los mismos requisitos observables.",
    sections: [
      ["Fija un único caso de uso real antes de comparar", `Este método empieza cuando ya existen dos o tres candidatos de Hacoo. No reabras la fase de descubrimiento ni preguntes cuál resulta más llamativo. Escribe una frase sobre el trabajo que debe cumplir la compra: una capa ligera para un trayecto frío y húmedo sobre una sudadera, una bolsa compacta para tableta, botella y objetos diarios, o calzado para varias horas caminando por ciudad. Incluye usuario, entorno, frecuencia y restricción que hacen útil el artículo. Una chaqueta adecuada para un festival no satisface necesariamente el trayecto diario. Hacoo se describe actualmente como una comunidad de contenidos basada en ideas, creadores y experiencias personales. Ese material puede inspirar la preselección, pero no define tu requisito. Bloquea el caso antes de leer más pies de foto o reseñas para que una imagen persuasiva no cambie la tarea. Si el caso contiene dos trabajos independientes, crea dos decisiones.`],
      ["Convierte el uso en requisitos imprescindibles observables", `Transforma la frase en cuatro a siete condiciones comprobables en la variante exacta. Usa sustantivos, números o funciones visibles, no elogios. “Cabe sobre mi sudadera de referencia” puede verificarse al anotar el ancho de esa prenda y la medida del candidato; “cómodo” no se demuestra en una ficha. “Admite una tableta de 28 centímetros y se cierra por completo” es más claro que “espacioso”. La lista puede incluir dimensión interior mínima, cierre obligatorio, familia de color, cantidad, modelo compatible, largo máximo o límite estricto del precio del artículo. Las preferencias quedan fuera en esta primera pasada. Adornos, atractivo de tendencia y tono favorito vienen después salvo que el uso fracase realmente sin ellos. Un imprescindible tiene una consecuencia: si no se cumple, el producto no realiza el trabajo nombrado. Si no puedes explicar esa consecuencia, conviértelo en preferencia o elimínalo.`],
      ["Define qué prueba puede satisfacer cada criterio", `Un criterio solo sirve si declaras qué evidencia cuenta. Para una medida, exige una tabla actual o especificación visible vinculada a la talla exacta. Para capacidad, dimensiones o distribución interior, no una foto de estilo. Una funda necesita el modelo preciso del dispositivo y la posición de los recortes. Un conjunto necesita una lista escrita de contenido; no supongas que todos los objetos de la imagen promocional están incluidos. La guía pública de propiedad intelectual de Hacoo señala que contenidos y enlaces pueden proceder de creadores y usuarios independientes, por lo que una afirmación de un creador no es automáticamente una especificación oficial. Registra la prueba como directa, indirecta o ausente. Directa responde para la variante elegida; indirecta deja una suposición importante; ausente no responde. No es una nota de calidad ni prueba autenticidad o rendimiento. Solo evita aprobar un requisito con una afirmación sin respaldo.`],
      ["Compara variantes exactas, no fichas completas", `Una ficha de Hacoo puede contener varios colores, tallas, paquetes o versiones. Compara la opción que realmente podrías seleccionar, no una impresión media de la página. Copia la etiqueta exacta junto a cada candidato y anota si al elegirla cambian imagen, especificación, contenido o precio. Una tabla de tallas situada en otra zona quizá no se aplique claramente a todas las versiones. La foto de un bolso puede mostrar correa larga aunque el paquete elegido no la enumere. Un precio inicial bajo puede pertenecer a una opción pequeña o incompleta. Si la evidencia no puede vincularse a la variante, marca desconocido. No tomes la respuesta de otro candidato o de un producto parecido. La comparación solo es justa si cada fila formula la misma pregunta al mismo nivel de identidad. Si un candidato desapareció o cambió, elimínalo o reconstruye su registro antes de puntuar.`],
      ["Usa aprobado, desconocido y fallido antes de ponderar", `Crea una tabla con una fila por imprescindible y una columna por candidato. Solo admite aprobado, desconocido o fallido. Aprobado significa que la prueba respalda la condición para la variante exacta. Fallido significa que la contradice. Desconocido corresponde a un dato ausente, ambiguo o separado de la opción. No lo conviertas en medio aprobado porque prefieres el diseño. Añade una nota de evidencia y la fecha de revisión a cada resultado. Aplica después la regla de forma uniforme: un fallo real elimina al candidato; un desconocido de gran consecuencia detiene la decisión hasta aclararlo. Esta puerta va antes de los puntos de precio, estilo o preferencias ponderadas. Evita que un producto gane con detalles secundarios mientras omite la razón de compra. La tabla puede descartar todos los candidatos; eso indica que debe cambiar la lista, no los criterios.`],
      ["Mantén las preferencias separadas y con menor prioridad", `Solo después de superar los imprescindibles compara los deseos: un tono preferido dentro de la familia aceptable, distribución de bolsillos, acabado decorativo o precio actual menor. Escríbelos aparte y ordénalos en lugar de elevarlos silenciosamente a requisito. Así se protege el uso frente a la sobrecarga de opciones y se leen los intercambios: A y B cumplen el trayecto, pero A ofrece instrucciones de cuidado más claras y B el color preferido. La elección ya es consciente sin fingir que el color determina la función. No sumes puntos por palabras como “premium”, “viral” o “más vendido” salvo que aporten evidencia de una necesidad, algo poco habitual. Popularidad, entusiasmo de creadores y fotografía pulida pueden influir en gusto, pero no corrigen una dimensión fallida, un modelo incompatible o una pieza ausente.`],
      ["Termina con una frase de decisión y una regla de parada", `Cierra con una frase que nombre caso de uso, candidato y prueba de cada imprescindible: “B continúa porque el ancho registrado admite la capa prevista, la opción elegida enumera el cierre y las dimensiones actuales respetan el límite de carga”. Si requiere una afirmación no respaldada sobre material, comodidad, calidad, autenticidad, entrega o disponibilidad futura, la decisión no está lista. Escribe el dato sin resolver. Añade una regla: elige solo si todos los criterios de gran consecuencia tienen prueba directa; de lo contrario, pide aclaración, espera mejor información o elige ninguno. Reabre la opción exacta justo antes de actuar porque páginas, variantes y precios cambian. Esta última comprobación no garantiza el resultado. Demuestra que la elección aún corresponde a la necesidad fijada y que la incertidumbre no se disfraza de seguridad.`],
    ],
  },
  fr: {
    title: "Critères indispensables Hacoo : comparer équitablement un usage réel",
    excerpt: "Transformer un usage concret en critères éliminatoires après la présélection, sans laisser le candidat le plus séduisant redéfinir le besoin.",
    keyword: "critères indispensables Hacoo",
    sourceNote: "L’identité de la plateforme et les limites des contenus utilisateurs ont été revérifiées dans les documents publics Hacoo le 18 septembre 2026.",
    imageAlt: "Vêtement candidat illustrant les critères indispensables Hacoo après une présélection",
    imageCaption: "Partir d’un usage prévu, puis tester chaque candidat avec les mêmes exigences observables.",
    sections: [
      ["Figer un usage réel avant de comparer", `Cette méthode commence lorsque deux ou trois candidats Hacoo existent déjà. Ne relancez pas la découverte et ne demandez pas lequel paraît le plus spectaculaire. Écrivez une phrase sur la tâche à accomplir : une couche légère pour un trajet frais et humide portée sur un sweat, un sac compact pour tablette, bouteille et objets quotidiens, ou des chaussures pour plusieurs heures de marche urbaine. Ajoutez utilisateur, contexte, fréquence et contrainte qui rendent l’article utile. Une veste adaptée à un festival ne répond pas nécessairement au trajet quotidien. Hacoo se présente actuellement comme une communauté de partage de contenus fondée sur les idées, les créateurs et les expériences personnelles. Cela peut inspirer la présélection, mais ne définit pas votre besoin. Verrouillez l’usage avant de lire d’autres légendes ou avis afin qu’une image persuasive ne modifie pas discrètement la tâche. Si deux fonctions indépendantes apparaissent, créez deux décisions.`],
      ["Transformer l’usage en exigences indispensables observables", `Convertissez la phrase en quatre à sept conditions vérifiables sur la variante exacte. Utilisez des noms, des nombres ou des fonctions visibles, pas des éloges. « Passe sur mon sweat de référence » devient vérifiable avec la largeur du sweat et la mesure du vêtement candidat ; « confortable » ne se prouve pas sur une fiche. « Contient une tablette de 28 centimètres et se ferme complètement » est plus clair que « spacieux ». La liste peut inclure dimensions intérieures minimales, fermeture obligatoire, famille de couleur, quantité, modèle compatible, longueur maximale ou plafond strict du prix de l’article. Les préférences restent dehors à ce stade. Détails décoratifs, effet de mode et nuance favorite viennent ensuite, sauf si l’usage échoue réellement sans eux. Une exigence a une conséquence : sans elle, le produit ne remplit pas la tâche. Si cette conséquence est inexplicable, classez le point en préférence ou retirez-le.`],
      ["Définir la preuve qui peut satisfaire chaque critère", `Un critère n’est utile que si la preuve acceptable est définie. Pour une mesure, exigez un tableau actuel ou une spécification visible liée à la taille exacte. Pour la capacité, utilisez dimensions ou organisation intérieure claire plutôt qu’une photo mise en scène. Une coque exige le modèle précis et la disposition des ouvertures. Un ensemble exige une liste écrite du contenu : tous les objets d’une image promotionnelle ne sont pas nécessairement inclus. Les indications publiques de Hacoo sur la propriété intellectuelle précisent que contenus et liens peuvent venir de créateurs et utilisateurs indépendants ; une déclaration de créateur n’est donc pas automatiquement une spécification officielle. Classez la preuve en directe, indirecte ou absente. Directe répond pour la variante choisie, indirecte conserve une hypothèse importante, absente ne répond pas. Ce n’est ni une note de qualité ni une preuve d’authenticité ou de performance. Cela empêche seulement une affirmation sans support de valider l’exigence.`],
      ["Comparer des variantes exactes, pas des fiches générales", `Une fiche Hacoo peut réunir plusieurs couleurs, tailles, lots ou versions. Comparez l’option réellement sélectionnable, pas l’impression moyenne de la page. Copiez son libellé exact auprès de chaque candidat et notez si le choix change image, spécification, contenu ou prix. Un tableau de tailles ailleurs sur la page ne s’applique pas forcément clairement à chaque version. Une photo de sac peut montrer une longue sangle que le lot choisi ne mentionne pas. Un prix d’appel bas peut correspondre à une option plus petite ou incomplète. Si la preuve ne peut être rattachée à la variante, marquez inconnu. N’empruntez pas la réponse d’un autre candidat ou d’un produit visuellement proche. La comparaison reste équitable seulement si chaque ligne pose la même question au même niveau d’identité. Si un candidat a disparu ou changé, retirez-le ou reconstruisez son dossier avant tout score.`],
      ["Utiliser réussite, inconnu et échec avant toute pondération", `Créez un tableau avec une ligne par exigence et une colonne par candidat. Trois résultats seulement : réussite, inconnu ou échec. Réussite signifie que la preuve soutient la condition pour la variante exacte. Échec signifie qu’elle la contredit clairement. Inconnu correspond à une information absente, ambiguë ou détachée de l’option. Ne transformez pas inconnu en demi-réussite parce que le design vous plaît. Ajoutez une note de preuve et la date de vérification à chaque résultat. Appliquez ensuite la règle : un véritable échec élimine le candidat ; un inconnu à forte conséquence suspend la décision. Cette porte précède points de prix, style ou préférences pondérées. Elle empêche un produit de gagner grâce à des détails secondaires tout en ratant la raison d’achat. Tous les candidats peuvent être éliminés ; il faut alors changer la présélection, pas les critères.`],
      ["Séparer les préférences et réduire délibérément leur priorité", `Comparez les souhaits seulement après le passage des exigences : nuance préférée dans la gamme acceptable, disposition des poches, finition décorative ou prix actuel inférieur. Inscrivez-les séparément et classez-les au lieu de les promouvoir silencieusement. L’usage initial résiste ainsi à la surcharge de choix et le compromis devient lisible : A et B remplissent la fonction de trajet, mais A donne des consignes d’entretien plus claires et B offre la couleur favorite. Le choix est conscient sans prétendre que la couleur détermine la fonction. N’ajoutez pas de points pour « premium », « viral » ou « meilleure vente » sauf si ces mots apportent une preuve du besoin, ce qui est rare. Popularité, enthousiasme de créateur et photographie soignée influencent une préférence, mais ne corrigent pas une dimension insuffisante, un modèle incompatible ou une pièce manquante.`],
      ["Terminer par une phrase de décision et une règle d’arrêt", `Finissez par une phrase nommant usage, candidat et preuve de chaque indispensable : « B reste parce que sa largeur enregistrée autorise la couche prévue, l’option choisie mentionne la fermeture requise et les dimensions actuelles respectent la limite de transport. » Si cette phrase nécessite une affirmation non étayée sur performance du matériau, confort, qualité, authenticité, livraison ou disponibilité future, la décision n’est pas prête. Écrivez plutôt le fait manquant. Fixez aussi une règle : choisir seulement si chaque critère à forte conséquence possède une preuve directe ; sinon demander une précision, attendre de meilleures informations ou ne rien choisir. Rouvrez l’option exacte juste avant d’agir, car pages, variantes et prix évoluent. Ce contrôle final ne garantit rien. Il montre que le choix correspond toujours au besoin fixé et que l’incertitude n’a pas été maquillée en certitude.`],
    ],
  },
  it: {
    title: "Criteri indispensabili Hacoo: confrontare correttamente un caso d’uso",
    excerpt: "Trasforma un uso reale in criteri di esclusione dopo la shortlist, senza lasciare che il candidato più attraente riscriva il bisogno.",
    keyword: "criteri indispensabili Hacoo",
    sourceNote: "Identità della piattaforma e limiti dei contenuti utente sono stati ricontrollati sui materiali pubblici Hacoo il 18 settembre 2026.",
    imageAlt: "Capo candidato che illustra i criteri indispensabili Hacoo dopo una shortlist",
    imageCaption: "Partire da un uso previsto e verificare ogni candidato con gli stessi requisiti osservabili.",
    sections: [
      ["Fissare un unico caso d’uso reale prima del confronto", `Questo metodo inizia quando esistono già due o tre candidati Hacoo. Non riaprire la scoperta e non chiedere quale prodotto sembri più emozionante. Scrivi una frase sul compito dell’acquisto: uno strato leggero per un tragitto fresco e bagnato sopra una felpa, una borsa compatta per tablet, bottiglia e oggetti quotidiani, oppure scarpe per diverse ore di cammino urbano. Includi utente, ambiente, frequenza e vincolo che rendono utile l’articolo. Una giacca per un festival non soddisfa necessariamente il tragitto giornaliero. Hacoo si descrive oggi come comunità di condivisione di contenuti basata su idee, creator ed esperienze personali. Quel materiale può ispirare la shortlist, ma non definisce il tuo requisito. Blocca il caso d’uso prima di leggere altre didascalie o recensioni, così un’immagine persuasiva non cambia il compito. Se contiene due funzioni indipendenti, crea due decisioni separate.`],
      ["Tradurre l’uso in requisiti indispensabili osservabili", `Trasforma la frase in quattro-sette condizioni verificabili sulla variante esatta. Usa nomi, numeri o funzioni visibili invece di elogi. “Entra sopra la mia felpa di riferimento” è verificabile quando registri la larghezza della felpa e la misura del candidato; “comodo” non si dimostra dalla scheda. “Contiene un tablet da 28 centimetri e si chiude completamente” è più chiaro di “capiente”. L’elenco può includere dimensioni interne minime, chiusura obbligatoria, famiglia cromatica, quantità, modello compatibile, lunghezza massima o tetto rigido del prezzo dell’articolo. Le preferenze restano fuori al primo passaggio. Dettagli decorativi, tendenza e tonalità favorita vengono dopo, salvo che l’uso fallisca davvero senza di essi. Un indispensabile ha una conseguenza: se manca, il prodotto non svolge il compito. Se non sai spiegare la conseguenza, trasformalo in preferenza o rimuovilo.`],
      ["Definire la prova che soddisfa ogni criterio", `Un criterio serve solo se dichiari quale prova conta. Per una misura, richiedi tabella attuale o specifica visibile collegata alla taglia esatta. Per la capacità, dimensioni o disposizione interna chiara, non una foto ambientata. Una custodia richiede modello preciso e posizione dei ritagli. Un set richiede l’elenco scritto del contenuto: non presumere che ogni oggetto nell’immagine promozionale sia incluso. Le indicazioni pubbliche Hacoo sulla proprietà intellettuale affermano che contenuti e link possono provenire da creator e utenti indipendenti; quindi una dichiarazione di un creator non è automaticamente una specifica ufficiale. Registra la prova come diretta, indiretta o assente. Diretta risponde per la variante scelta, indiretta lascia un’assunzione importante, assente non risponde. Non è un voto di qualità e non dimostra autenticità o prestazioni. Impedisce soltanto che un’affermazione senza supporto venga trattata come requisito superato.`],
      ["Confrontare varianti esatte, non inserzioni generiche", `Una scheda Hacoo può contenere colori, taglie, pacchetti o versioni differenti. Confronta l’opzione che potresti davvero selezionare, non la media impressione della pagina. Copia l’etichetta esatta accanto al candidato e annota se la scelta cambia immagine, specifica, contenuto o prezzo. Una tabella taglie altrove potrebbe non applicarsi chiaramente a ogni versione. La foto di una borsa può mostrare una tracolla lunga che il bundle selezionato non elenca. Un prezzo iniziale basso può riferirsi a un’opzione più piccola o incompleta. Se la prova non si collega alla variante, segna sconosciuto. Non prendere la risposta da un altro candidato o da un prodotto simile. Il confronto è equo solo quando ogni riga pone la stessa domanda allo stesso livello di identità. Se un candidato è scomparso o cambiato, rimuovilo o ricostruisci il record prima di assegnare punti.`],
      ["Usare superato, sconosciuto e fallito prima dei pesi", `Crea una tabella con una riga per ogni indispensabile e una colonna per candidato. Consenti solo superato, sconosciuto o fallito. Superato significa che la prova sostiene la condizione per la variante esatta. Fallito significa che la contraddice. Sconosciuto indica informazione assente, ambigua o separata dall’opzione. Non trasformarlo in mezzo superato perché preferisci il design. Aggiungi una breve nota di prova e la data a ogni risultato. Poi applica la regola con coerenza: un fallimento reale elimina il candidato; uno sconosciuto ad alta conseguenza mette in pausa la decisione. Questa soglia precede punti di prezzo, stile o preferenze pesate. Evita che un prodotto vinca grazie a dettagli secondari pur mancando il motivo dell’acquisto. La tabella può eliminare tutti i candidati: in quel caso cambia la shortlist, non i criteri.`],
      ["Tenere separate le preferenze e abbassarne la priorità", `Solo dopo il superamento degli indispensabili confronta i desideri: tonalità preferita nella famiglia accettabile, disposizione delle tasche, finitura decorativa o prezzo attuale più basso. Scrivili in una sezione separata e ordinali, senza promuoverli in silenzio a requisiti. Questo protegge il caso d’uso dal sovraccarico di scelta e rende leggibile lo scambio: A e B soddisfano il tragitto, ma A ha istruzioni di cura più chiare e B il colore preferito. Ora la scelta è consapevole senza fingere che il colore determini la funzione. Non dare punti extra a termini come “premium”, “virale” o “best seller” se non forniscono una prova del bisogno, cosa rara. Popolarità, entusiasmo dei creator e fotografia curata influenzano una preferenza, ma non riparano una dimensione errata, un modello incompatibile o un pezzo mancante.`],
      ["Concludere con una frase decisionale e una regola di stop", `Chiudi con una frase che nomina uso, candidato e prova per ogni indispensabile: “B resta perché la larghezza registrata consente lo strato previsto, l’opzione elenca la chiusura necessaria e le dimensioni attuali rispettano il limite di trasporto.” Se la frase richiede affermazioni non provate su prestazioni del materiale, comfort, qualità, autenticità, consegna o disponibilità futura, la decisione non è pronta. Scrivi invece il fatto irrisolto. Definisci anche una regola: scegli solo quando ogni criterio ad alta conseguenza ha prova diretta; altrimenti chiedi chiarimenti, attendi informazioni migliori o non scegliere nessuno. Riapri l’opzione esatta subito prima di agire perché pagine, varianti e prezzi cambiano. Il controllo finale non garantisce un esito. Dimostra che la scelta corrisponde ancora al requisito fissato e che l’incertezza non è stata mascherata da sicurezza.`],
    ],
  },
};

export const hvUseCaseArticle = en;
export const hvUseCaseTexts: Record<Lang, ArticleText> = { en, ...translations };
