import type { CoreRouteKey, Lang } from "./site-data";

type Pair = readonly [string, string];
type PageKey = Exclude<CoreRouteKey, "">;

export type LocaleContent = {
  common: {
    menu: string; explore: string; sourcePrice: string; minutes: string; researchSuffix: string; nextStep: string;
    testWorkflow: string; shippingFacts: string; returnsFacts: string; whatsapp: string; home: string;
    sourcesMethodology: string; checked: string;
  };
  home: {
    newCheck: string; imageTitleUrl: string; accessoryCaption: string; howItWorks: string; workflow: string;
    noClaims: string; categoryIndex: string; findsIndex: string; priceNote: string; methodIndex: string;
    articlesIndex: string; faqIndex: string; faqText: string;
  };
  pageInfo: Record<PageKey, { eyebrow: string; title: string; text: string }>;
  spreadsheet: { searchLabel: string; searchTitle: string; headingIndex: string; headingTitle: string; headingText: string; asideLabel: string; asideTitle: string; asideText: string; items: Pair[]; source: string };
  finds: { headingIndex: string; headingTitle: string; headingText: string; priceNote: string; asideLabel: string; asideTitle: string; asideText: string; items: Pair[] };
  qc: { asideLabel: string; asideTitle: string; asideText: string; items: Pair[]; source: string };
  shipping: { facts: Pair[]; asideLabel: string; asideTitle: string; asideText: string; items: Pair[]; source: string };
  returns: { facts: Pair[]; asideLabel: string; asideTitle: string; asideText: string; items: Pair[]; source: string };
  categories: string[];
  productCategories: Record<string, string>;
  faq: Pair[];
};

const en: LocaleContent = {
  common: { menu: "MENU", explore: "Explore", sourcePrice: "source price", minutes: "10–12 MIN", researchSuffix: "Official facts, third-party review signals and editorial advice are identified separately. Live policies and listings can change.", nextStep: "NEXT STEP", testWorkflow: "Test the workflow on a live listing.", shippingFacts: "Shipping facts", returnsFacts: "Returns facts", whatsapp: "Contact on WhatsApp", home: "Home", sourcesMethodology: "Sources and methodology", checked: "Checked" },
  home: { newCheck: "NEW CHECK", imageTitleUrl: "Image + title + exact URL", accessoryCaption: "Accessories / 02", howItWorks: "HOW IT WORKS", workflow: "Find → verify\ninspect → plan", noClaims: "No invented totals. No official-sounding claims.", categoryIndex: "01 / CATEGORIES", findsIndex: "02 / CURATED FINDS", priceNote: "USD amounts are planning references. Confirm the selected option, live price, delivery and payment total on the destination page.", methodIndex: "03 / METHOD", articlesIndex: "04 / ARTICLES", faqIndex: "05 / FAQ", faqText: "Clear answers based on public platform guidance and cautious listing checks." },
  pageInfo: {
    spreadsheet: { eyebrow: "HACOO SPREADSHEET 2026", title: "Search less. Verify more.", text: "Hacoo describes itself as a community-driven content and discovery platform. This independent spreadsheet turns that discovery intent into exact category and product destinations—not an official Hacoo catalogue." },
    finds: { eyebrow: "CURATED HACOO FINDS", title: "A smaller list with a reason to click.", text: "Every card pairs the destination’s current first image, exact product title, source price, USD planning estimate and direct product-detail URL." },
    "qc-guide": { eyebrow: "QC PHOTO GUIDE", title: "Look for evidence, not reassurance.", text: "A practical review sequence built around the same evidence Hacoo’s official return guidance requests for size, quality, breakage, wrong-item and missing-item claims." },
    shipping: { eyebrow: "HACOO SHIPPING", title: "Plan with ranges, not promises.", text: "Official Hacoo pages publish country coverage and several delivery ranges. This page preserves the differences instead of compressing them into one guaranteed date." },
    returns: { eyebrow: "HACOO RETURNS", title: "Know the window before you need it.", text: "Official guidance says eligible products generally need a return request within 15 days after delivery, lists excluded free-return categories and states that exchanges are not currently supported." },
    articles: { eyebrow: "HACOO RESEARCH LIBRARY", title: "One question per guide.", text: "Focused, human-readable articles about spreadsheets, link checking, delivery and returns." },
    faq: { eyebrow: "HACOO FAQ", title: "Plain answers. Visible limits.", text: "No inflated product totals and no claim of affiliation—just the checks a user should make." },
  },
  spreadsheet: { searchLabel: "LIVE CATALOG SEARCH", searchTitle: "Use a specific product phrase.", headingIndex: "EXACT CATEGORY ROUTES", headingTitle: "Browse the destination, not a generic homepage.", headingText: "Each card below opens the matching category on the live main catalogue.", asideLabel: "SPREADSHEET / METHOD", asideTitle: "What this index can—and cannot—prove.", asideText: "Hacoo’s terms place responsibility for user-generated content with independent creators. A spreadsheet is therefore a discovery tool, not an official endorsement.", items: [["Use an exact destination", "A category card opens its matching category; a product card opens one exact product-detail page."], ["Compare image and title", "A working URL is not enough. The current first image and product title must still match the source card."], ["Check country and region", "Hacoo states support for 28 countries but names 27 on the current official list. Verify actual availability in the app."], ["Keep uncertainty visible", "Checked dates, USD estimates and independent status should be labelled rather than presented as permanent guarantees."]], source: "Sources checked: Hacoo About Us, Terms of Service, official delivery-area Help Center and main catalogue routes · 28 August 2026." },
  finds: { headingIndex: "MATCHED PRODUCT DESTINATIONS", headingTitle: "First image, title and URL checked together.", headingText: "These cards use the current first image from the exact destination page. USD values are planning conversions from the displayed source price.", priceNote: "Conversion reference: CN¥6.75 = US$1, checked 28 August 2026. Re-check the selected option, live source price and payable amount. If the destination image or product has changed, do not continue from the card.", asideLabel: "FINDS / VERIFICATION", asideTitle: "A small catalogue can be more useful.", asideText: "Product volume is not a quality signal. A usable card must preserve the relationship between discovery and live destination.", items: [["Exact detail page", "No product card redirects to the homepage, a generic search or another platform."], ["Matching first image", "The image served here is the first product image from the same destination page."], ["Visible source price", "The original CNY figure stays visible beside the USD planning estimate."], ["Current option check", "The destination remains authoritative for colour, size, variant, inventory and final price."]] },
  qc: { asideLabel: "QC / 01—07", asideTitle: "A repeatable inspection order", asideText: "Start wide, then move closer. Hacoo’s return page requests specific evidence for different problem types, so photograph what identifies the order as well as the defect.", items: [["Confirm the ordered variant", "Match colour, size, version and quantity before judging any detail."], ["Check overall shape", "Look for distortion, asymmetry, uneven panels and proportions that disagree with the listing."], ["Inspect construction", "Zoom into seams, stitching, edges, fasteners and joins. Ask for another angle when an area is hidden."], ["Read labels and bag barcode", "For a size issue, official guidance asks for the size label, barcode on the product bag and an explanation of where fit is wrong."], ["Compare colour and measurements", "Lighting changes colour. Use listed measurements and a ruler photo for critical dimensions."], ["Record damage with context", "For breakage, photograph the outer package, product bag and damaged area before discarding packaging."], ["Classify the issue", "Wrong product, missing item, wrong parcel and description problems require different supporting images and order records."]], source: "Source checked: Hacoo Help Center return policy and return-process guidance · 28 August 2026." },
  shipping: { facts: [["28*", "countries stated; 27 currently named on the official list"], ["15–28", "days broad Help Center total-delivery reference"], ["15–65", "days across country ranges on the website shipping page"]], asideLabel: "SHIPPING / FACT CHECK", asideTitle: "The official pages provide more than one range.", asideText: "The Help Center breaks delivery into 3–7 days preparation, 7–15 days shipping and 5–10 days final delivery. The website separately lists 15–25 days for the UK, France, Germany and Italy; 15–30 for Spain; and 25–65 for other countries.", items: [["Confirm address eligibility", "Enter the actual destination and check whether the item and current route are available."], ["Read time as a guideline", "Both official pages say or imply that timing can change; do not turn the fastest figure into a promise."], ["Expect possible split parcels", "The website says available items may ship before pre-order or back-order products in the same order."], ["Compare the complete cost", "Include delivery, payment conversion, applicable tax and option surcharges."], ["Correct an address quickly", "Official guidance says the buyer is responsible for address accuracy and should contact support immediately if it is wrong."], ["Keep order and tracking records", "Save the selected variant, current estimate, parcel status and support communication."]], source: "Sources checked: Hacoo Shipping & Delivery and EU Help Center delivery-time / supported-area pages · 28 August 2026." },
  returns: { facts: [["15", "days after receipt for eligible return requests"], ["NO", "exchange service currently stated"], ["$30", "maximum shipping compensation stated for confirmed Hacoo-responsibility cases"]], asideLabel: "RETURNS / EVIDENCE", asideTitle: "Document the issue before use.", asideText: "Official guidance excludes some categories from free return and says used, washed, modified or label-free products may be rejected. Order-specific rules remain the final check.", items: [["Open the current order terms", "Check the product and order interface for eligibility, deadline and required steps."], ["Know common exclusions", "Beauty after opening; underwear, swimwear, leggings and lingerie; jewellery/luxury goods; and listed electronics may not qualify for free return."], ["Photograph the package", "Capture outer packaging, shipping label, product bag and condition before discarding anything."], ["Show the complete item", "Take a full view plus close-ups of the defect, incorrect option or missing part."], ["Get approval before shipping", "The official page says unapproved returns may not be accepted and pickup service is not currently supported."], ["Keep cost expectations realistic", "Customer-reason returns can leave the customer responsible for return shipping/customs; original shipping fees are stated as non-refundable."], ["Do not expect an exchange", "The current policy says exchange service is not supported; a different size may require a return and new order."]], source: "Sources checked: Hacoo Help Center return policy and ‘How to return the products?’ · 28 August 2026." },
  categories: ["Shoes", "Hoodies", "T-Shirts", "Jackets", "Pants / Shorts", "Headwear", "Accessories", "Short Sets", "Electronics", "Other Finds", "Jerseys"],
  productCategories: { Shoes: "Shoes", Accessories: "Accessories", "Other Stuff": "Other Stuff", "T-Shirts": "T-Shirts", Hoodies: "Hoodies" },
  faq: [["Is this the official Hacoo website?", "No. Hacoo VIP is an independent research and discovery guide. It does not claim affiliation with Hacoo. Live product, payment and policy details must be checked on the destination page."], ["What is a Hacoo spreadsheet?", "It is a curated index that groups product discoveries, search terms and checking advice. It should shorten discovery time, but it cannot guarantee seller quality, inventory or delivery."], ["Are the prices fixed?", "No. USD figures are planning references. Product price, options, exchange rate, delivery and promotions can change on the live page."], ["How should I use QC photos?", "Compare the ordered variant and measurements first, then inspect overall shape, stitching, symmetry, labels, colour and visible damage. Ask for another image when a critical area is unclear."], ["Where does Hacoo deliver?", "The official help page states 28 supported countries but currently names 27: 22 in Europe plus the United States, Mexico, Canada, Brazil and Australia. Verify actual item and address availability in the app."], ["How long can delivery take?", "The Help Center gives a broad 15–28 day total reference. The website shipping page separately lists 15–25 days for the UK, France, Germany and Italy; 15–30 for Spain; and 25–65 for other countries. These are guidelines, not guarantees."], ["What should I know about returns?", "Official guidance says eligible return requests are generally made within 15 days after receipt. Some categories do not qualify for free return, exchanges are not currently offered, and evidence requirements differ by problem type."], ["What evidence can a return require?", "Depending on the issue, Hacoo may ask for the size label, product-bag barcode, outer package, shipping label, invoice, full product image and close-up of the defect or missing part."], ["Is Hacoo an online shop or a community platform?", "Hacoo’s current About Us and Terms describe a community-driven content-sharing and discovery ecosystem connecting users and independent creators. Its public pages also provide shipping and after-sales guidance. This site is an independent link index, not Hacoo."]],
};

const de: LocaleContent = {
  common: { menu: "MENÜ", explore: "Entdecken", sourcePrice: "Quellpreis", minutes: "10–12 MIN.", researchSuffix: "Offizielle Fakten, Signale aus Drittanbieter-Bewertungen und redaktionelle Hinweise werden getrennt gekennzeichnet. Aktuelle Richtlinien und Angebote können sich ändern.", nextStep: "NÄCHSTER SCHRITT", testWorkflow: "Teste den Ablauf an einem aktuellen Angebot.", shippingFacts: "Versandfakten", returnsFacts: "Retourenfakten", whatsapp: "Kontakt über WhatsApp", home: "Start", sourcesMethodology: "Quellen und Methodik", checked: "Geprüft" },
  home: { newCheck: "NEU GEPRÜFT", imageTitleUrl: "Bild + Titel + exakte URL", accessoryCaption: "Accessoires / 02", howItWorks: "SO FUNKTIONIERT ES", workflow: "Finden → prüfen\nkontrollieren → planen", noClaims: "Keine erfundenen Zahlen. Keine amtlich klingenden Behauptungen.", categoryIndex: "01 / KATEGORIEN", findsIndex: "02 / KURATIERTE FUNDE", priceNote: "USD-Beträge sind Planungswerte. Prüfe gewählte Option, Live-Preis, Versand und Zahlungsbetrag auf der Zielseite.", methodIndex: "03 / METHODE", articlesIndex: "04 / ARTIKEL", faqIndex: "05 / FAQ", faqText: "Klare Antworten auf Basis öffentlicher Plattformangaben und vorsichtiger Angebotsprüfung." },
  pageInfo: {
    spreadsheet: { eyebrow: "HACOO-TABELLE 2026", title: "Weniger suchen. Mehr prüfen.", text: "Hacoo beschreibt sich als gemeinschaftsgetriebene Plattform für Inhalte und Entdeckungen. Diese unabhängige Tabelle führt zu exakten Kategorie- und Produktzielen – sie ist kein offizieller Hacoo-Katalog." },
    finds: { eyebrow: "KURATIERTE HACOO-FUNDE", title: "Eine kleinere Liste mit gutem Klickgrund.", text: "Jede Karte verbindet das aktuelle erste Bild der Zielseite, den exakten Produkttitel, Quellpreis, USD-Planungswert und die direkte Detail-URL." },
    "qc-guide": { eyebrow: "QC-FOTO-GUIDE", title: "Suche Belege, keine Beruhigung.", text: "Eine praktische Prüfreihenfolge auf Grundlage der Nachweise, die Hacoos offizielle Retourenhilfe bei Größe, Qualität, Bruch, falschem oder fehlendem Artikel verlangt." },
    shipping: { eyebrow: "HACOO-VERSAND", title: "Mit Spannen planen, nicht mit Versprechen.", text: "Offizielle Hacoo-Seiten nennen Länderabdeckung und mehrere Lieferzeiträume. Diese Seite erhält die Unterschiede, statt daraus ein garantiertes Datum zu machen." },
    returns: { eyebrow: "HACOO-RETOUREN", title: "Kenne die Frist, bevor du sie brauchst.", text: "Laut offizieller Hilfe müssen berechtigte Retouren in der Regel innerhalb von 15 Tagen nach Erhalt beantragt werden; sie nennt Ausschlüsse und weist darauf hin, dass Umtausch derzeit nicht unterstützt wird." },
    articles: { eyebrow: "HACOO-RECHERCHEBIBLIOTHEK", title: "Eine Frage pro Guide.", text: "Fokussierte, verständliche Beiträge über Tabellen, Linkprüfung, Lieferung und Retouren." },
    faq: { eyebrow: "HACOO FAQ", title: "Klare Antworten. Sichtbare Grenzen.", text: "Keine überhöhten Produktzahlen und keine angebliche Verbindung – nur nachvollziehbare Prüfungen." },
  },
  spreadsheet: { searchLabel: "LIVE-KATALOGSUCHE", searchTitle: "Verwende einen konkreten Produktbegriff.", headingIndex: "EXAKTE KATEGORIEZIELE", headingTitle: "Öffne das Ziel, nicht irgendeine Startseite.", headingText: "Jede Karte öffnet die passende Kategorie im aktuellen Hauptkatalog.", asideLabel: "TABELLE / METHODE", asideTitle: "Was dieser Index belegen kann – und was nicht.", asideText: "Hacoos Bedingungen legen die Verantwortung für nutzergenerierte Inhalte bei unabhängigen Erstellern fest. Eine Tabelle ist deshalb ein Entdeckungswerkzeug, keine offizielle Empfehlung.", items: [["Exaktes Ziel verwenden", "Eine Kategorienkarte öffnet die passende Kategorie; eine Produktkarte genau eine Produktdetailseite."], ["Bild und Titel vergleichen", "Eine funktionierende URL reicht nicht. Aktuelles erstes Bild und Produkttitel müssen weiterhin zur Quellkarte passen."], ["Land und Region prüfen", "Hacoo spricht von 28 unterstützten Ländern, nennt aktuell aber 27. Prüfe die tatsächliche Verfügbarkeit in der App."], ["Unsicherheit sichtbar lassen", "Prüfdatum, USD-Schätzungen und unabhängiger Status müssen gekennzeichnet sein, statt als dauerhafte Garantie zu erscheinen."]], source: "Geprüfte Quellen: Hacoo Über uns, Nutzungsbedingungen, offizielles Hilfezentrum zu Liefergebieten und Hauptkatalog-Routen · 28. August 2026." },
  finds: { headingIndex: "ABGEGLICHENE PRODUKTZIELE", headingTitle: "Erstes Bild, Titel und URL gemeinsam geprüft.", headingText: "Diese Karten verwenden das aktuelle erste Bild der exakten Zielseite. USD-Werte sind Planungsumrechnungen des angezeigten Quellpreises.", priceNote: "Umrechnungsreferenz: CN¥6,75 = 1 US$, geprüft am 28. August 2026. Prüfe Option, Live-Quellpreis und Endbetrag erneut. Hat sich Bild oder Produkt geändert, fahre nicht über diese Karte fort.", asideLabel: "FUNDE / PRÜFUNG", asideTitle: "Ein kleiner Katalog kann nützlicher sein.", asideText: "Produktmenge ist kein Qualitätssignal. Eine brauchbare Karte muss den Zusammenhang zwischen Fund und Live-Ziel erhalten.", items: [["Exakte Detailseite", "Keine Produktkarte leitet zur Startseite, einer allgemeinen Suche oder einer anderen Plattform weiter."], ["Passendes erstes Bild", "Das hier gezeigte Bild ist das erste Produktbild derselben Zielseite."], ["Sichtbarer Quellpreis", "Der ursprüngliche CNY-Betrag bleibt neben der USD-Planungsschätzung sichtbar."], ["Aktuelle Option prüfen", "Die Zielseite bleibt maßgeblich für Farbe, Größe, Variante, Bestand und Endpreis."]] },
  qc: { asideLabel: "QC / 01—07", asideTitle: "Eine wiederholbare Prüfreihenfolge", asideText: "Beginne mit der Gesamtansicht und gehe dann ins Detail. Hacoos Retourenseite verlangt je nach Problem unterschiedliche Belege; fotografiere daher sowohl die Bestellzuordnung als auch den Fehler.", items: [["Bestellte Variante bestätigen", "Farbe, Größe, Version und Menge abgleichen, bevor Details bewertet werden."], ["Gesamtform prüfen", "Auf Verformung, Asymmetrie, ungleichmäßige Flächen und abweichende Proportionen achten."], ["Verarbeitung untersuchen", "Nähte, Kanten, Verschlüsse und Verbindungen vergrößern. Bei verdeckten Stellen um einen weiteren Winkel bitten."], ["Etikett und Beutelbarcode lesen", "Bei Größenproblemen verlangt die offizielle Hilfe Größenetikett, Barcode des Produktbeutels und eine Erklärung zur falschen Passform."], ["Farbe und Maße vergleichen", "Licht verändert Farben. Für kritische Maße Angaben und ein Linealfoto nutzen."], ["Schaden im Zusammenhang dokumentieren", "Bei Bruch Außenverpackung, Produktbeutel und Schaden fotografieren, bevor Verpackung entsorgt wird."], ["Problem einordnen", "Falscher Artikel, fehlender Inhalt, falsches Paket und Beschreibungsabweichung brauchen unterschiedliche Bilder und Bestellbelege."]], source: "Geprüfte Quelle: Hacoo Help Center, Retourenrichtlinie und Retourenablauf · 28. August 2026." },
  shipping: { facts: [["28*", "Länder angegeben; 27 derzeit in der offiziellen Liste genannt"], ["15–28", "Tage als breite Gesamtreferenz im Help Center"], ["15–65", "Tage über die Länderspannen der Versandseite"]], asideLabel: "VERSAND / FAKTENCHECK", asideTitle: "Die offiziellen Seiten nennen mehr als eine Spanne.", asideText: "Das Help Center gliedert in 3–7 Tage Vorbereitung, 7–15 Tage Versand und 5–10 Tage letzte Zustellung. Die Website nennt separat 15–25 Tage für UK, Frankreich, Deutschland und Italien, 15–30 für Spanien sowie 25–65 für andere Länder.", items: [["Adresse auf Eignung prüfen", "Tatsächliches Ziel eingeben und kontrollieren, ob Artikel und Route verfügbar sind."], ["Zeit als Richtwert lesen", "Beide offiziellen Seiten zeigen, dass Zeiten schwanken; aus dem schnellsten Wert kein Versprechen machen."], ["Geteilte Pakete einkalkulieren", "Verfügbare Artikel können laut Website vor Vorbestellungs- oder Nachlieferartikeln derselben Bestellung versandt werden."], ["Gesamtkosten vergleichen", "Versand, Zahlungsumrechnung, anwendbare Steuern und Optionsaufschläge einbeziehen."], ["Adresse schnell korrigieren", "Laut offizieller Hilfe ist der Käufer für die Richtigkeit verantwortlich und soll bei Fehlern sofort den Support kontaktieren."], ["Bestell- und Trackingdaten behalten", "Gewählte Variante, Schätzung, Paketstatus und Supportkommunikation sichern."]], source: "Geprüfte Quellen: Hacoo Shipping & Delivery sowie EU Help Center zu Lieferzeit und Liefergebieten · 28. August 2026." },
  returns: { facts: [["15", "Tage nach Erhalt für berechtigte Retourenanträge"], ["NEIN", "Umtauschservice laut aktueller Angabe"], ["$30", "maximale Versandkostenerstattung bei bestätigter Hacoo-Verantwortung"]], asideLabel: "RETOUREN / NACHWEISE", asideTitle: "Dokumentiere das Problem vor der Nutzung.", asideText: "Offizielle Angaben schließen einige Kategorien von kostenloser Rückgabe aus; benutzte, gewaschene, veränderte oder etikettlose Ware kann abgelehnt werden. Die bestellspezifische Regel ist entscheidend.", items: [["Aktuelle Bestellbedingungen öffnen", "In Produkt- und Bestellansicht Berechtigung, Frist und notwendige Schritte prüfen."], ["Häufige Ausschlüsse kennen", "Geöffnete Beautyartikel; Unterwäsche, Bademode, Leggings und Lingerie; Schmuck/Luxuswaren sowie gelistete Elektronik können von kostenloser Rückgabe ausgeschlossen sein."], ["Paket fotografieren", "Außenverpackung, Versandetikett, Produktbeutel und Zustand festhalten, bevor etwas entsorgt wird."], ["Kompletten Artikel zeigen", "Gesamtansicht sowie Nahaufnahmen des Fehlers, der falschen Option oder des fehlenden Teils aufnehmen."], ["Vor Versand genehmigen lassen", "Unbestätigte Retouren werden laut offizieller Seite möglicherweise nicht angenommen; Abholung wird derzeit nicht angeboten."], ["Kosten realistisch einschätzen", "Bei Rückgabe aus Kundengründen können Rückversand/Zoll beim Kunden bleiben; ursprüngliche Versandkosten gelten als nicht erstattbar."], ["Keinen Umtausch erwarten", "Derzeit wird kein Umtausch unterstützt; eine andere Größe kann Retoure und Neubestellung verlangen."]], source: "Geprüfte Quellen: Hacoo Help Center Retourenrichtlinie und „Wie werden Produkte zurückgegeben?“ · 28. August 2026." },
  categories: ["Schuhe", "Hoodies", "T-Shirts", "Jacken", "Hosen / Shorts", "Kopfbedeckungen", "Accessoires", "Shorts-Sets", "Elektronik", "Weitere Funde", "Trikots"],
  productCategories: { Shoes: "Schuhe", Accessories: "Accessoires", "Other Stuff": "Sonstiges", "T-Shirts": "T-Shirts", Hoodies: "Hoodies" },
  faq: [["Ist dies die offizielle Hacoo-Website?", "Nein. Hacoo VIP ist ein unabhängiger Recherche- und Entdeckungsratgeber und behauptet keine Verbindung zu Hacoo. Produkt-, Zahlungs- und Richtliniendetails müssen auf der Zielseite geprüft werden."], ["Was ist eine Hacoo-Tabelle?", "Ein kuratierter Index, der Produktfunde, Suchbegriffe und Prüftipps bündelt. Er verkürzt die Suche, garantiert aber weder Verkäuferqualität noch Bestand oder Lieferung."], ["Sind die Preise fest?", "Nein. USD-Werte dienen der Planung. Produktpreis, Optionen, Wechselkurs, Lieferung und Aktionen können sich auf der Live-Seite ändern."], ["Wie nutze ich QC-Fotos?", "Zuerst bestellte Variante und Maße abgleichen, dann Gesamtform, Nähte, Symmetrie, Etiketten, Farbe und sichtbare Schäden prüfen. Bei unklaren Bereichen ein weiteres Bild anfordern."], ["Wohin liefert Hacoo?", "Die offizielle Hilfe nennt 28 unterstützte Länder, führt derzeit aber 27 auf: 22 in Europa sowie USA, Mexiko, Kanada, Brasilien und Australien. Artikel- und Adressverfügbarkeit in der App prüfen."], ["Wie lange kann die Lieferung dauern?", "Das Help Center nennt 15–28 Tage als breite Gesamtreferenz. Die Versandseite nennt separat 15–25 Tage für UK, Frankreich, Deutschland und Italien, 15–30 für Spanien und 25–65 für andere Länder. Das sind Richtwerte, keine Garantien."], ["Was ist bei Retouren wichtig?", "Berechtigte Anträge werden laut offizieller Hilfe in der Regel innerhalb von 15 Tagen nach Erhalt gestellt. Manche Kategorien sind von kostenloser Rückgabe ausgeschlossen, Umtausch wird nicht angeboten und Nachweise unterscheiden sich je nach Problem."], ["Welche Nachweise können verlangt werden?", "Je nach Fall kann Hacoo Größenetikett, Produktbeutel-Barcode, Außenpaket, Versandetikett, Rechnung, Gesamtbild und Nahaufnahme des Fehlers oder fehlenden Teils verlangen."], ["Ist Hacoo Shop oder Community-Plattform?", "Hacoos aktuelle Seiten Über uns und Bedingungen beschreiben ein gemeinschaftsgetriebenes Ökosystem für Inhalte und Entdeckungen, das Nutzer und unabhängige Creator verbindet. Öffentliche Seiten bieten außerdem Versand- und Kundendiensthinweise. Diese Website ist ein unabhängiger Linkindex."]],
};

const es: LocaleContent = {
  common: { menu: "MENÚ", explore: "Explorar", sourcePrice: "precio de origen", minutes: "10–12 MIN", researchSuffix: "Los hechos oficiales, las señales de reseñas externas y el consejo editorial se identifican por separado. Las políticas y fichas activas pueden cambiar.", nextStep: "SIGUIENTE PASO", testWorkflow: "Prueba el proceso con una ficha activa.", shippingFacts: "Datos de envío", returnsFacts: "Datos de devoluciones", whatsapp: "Contactar por WhatsApp", home: "Inicio", sourcesMethodology: "Fuentes y metodología", checked: "Revisado" },
  home: { newCheck: "NUEVA REVISIÓN", imageTitleUrl: "Imagen + título + URL exacta", accessoryCaption: "Accesorios / 02", howItWorks: "CÓMO FUNCIONA", workflow: "Buscar → verificar\ninspeccionar → planificar", noClaims: "Sin cifras inventadas ni afirmaciones con apariencia oficial.", categoryIndex: "01 / CATEGORÍAS", findsIndex: "02 / HALLAZGOS SELECCIONADOS", priceNote: "Los importes en USD son referencias de planificación. Confirma opción, precio activo, entrega y total de pago en la página de destino.", methodIndex: "03 / MÉTODO", articlesIndex: "04 / ARTÍCULOS", faqIndex: "05 / FAQ", faqText: "Respuestas claras basadas en información pública de la plataforma y comprobaciones prudentes." },
  pageInfo: {
    spreadsheet: { eyebrow: "HOJA HACOO 2026", title: "Busca menos. Verifica más.", text: "Hacoo se describe como una plataforma comunitaria de contenido y descubrimiento. Esta hoja independiente convierte esa intención en destinos exactos de categorías y productos; no es un catálogo oficial de Hacoo." },
    finds: { eyebrow: "HALLAZGOS HACOO SELECCIONADOS", title: "Una lista menor con motivos para hacer clic.", text: "Cada tarjeta reúne la primera imagen actual del destino, título exacto, precio de origen, estimación en USD y URL directa de detalle." },
    "qc-guide": { eyebrow: "GUÍA DE FOTOS QC", title: "Busca pruebas, no tranquilidad.", text: "Secuencia práctica basada en las pruebas que la guía oficial de devoluciones de Hacoo pide para talla, calidad, rotura, artículo incorrecto o faltante." },
    shipping: { eyebrow: "ENVÍOS HACOO", title: "Planifica con rangos, no promesas.", text: "Las páginas oficiales publican cobertura y varios plazos. Aquí se conservan las diferencias sin convertirlas en una fecha garantizada." },
    returns: { eyebrow: "DEVOLUCIONES HACOO", title: "Conoce el plazo antes de necesitarlo.", text: "La guía oficial indica que los productos aptos suelen requerir solicitud en los 15 días posteriores a la entrega, enumera exclusiones y dice que no hay cambios actualmente." },
    articles: { eyebrow: "BIBLIOTECA DE INVESTIGACIÓN HACOO", title: "Una pregunta por guía.", text: "Artículos claros y centrados en hojas, verificación de enlaces, entrega y devoluciones." },
    faq: { eyebrow: "FAQ HACOO", title: "Respuestas directas. Límites visibles.", text: "Sin cifras infladas ni afiliación fingida: solo comprobaciones que el usuario puede repetir." },
  },
  spreadsheet: { searchLabel: "BÚSQUEDA EN CATÁLOGO ACTIVO", searchTitle: "Usa una frase de producto concreta.", headingIndex: "RUTAS DE CATEGORÍA EXACTAS", headingTitle: "Abre el destino, no una portada genérica.", headingText: "Cada tarjeta abre la categoría correspondiente del catálogo principal activo.", asideLabel: "HOJA / MÉTODO", asideTitle: "Lo que este índice puede demostrar y lo que no.", asideText: "Los términos de Hacoo atribuyen a creadores independientes la responsabilidad del contenido generado por usuarios. Una hoja es una herramienta de descubrimiento, no una aprobación oficial.", items: [["Usa un destino exacto", "Una tarjeta de categoría abre su categoría; una de producto abre una única ficha de detalle."], ["Compara imagen y título", "No basta con que funcione la URL. La primera imagen y el título actuales deben seguir coincidiendo con la tarjeta."], ["Comprueba país y región", "Hacoo afirma admitir 28 países, pero la lista oficial actual nombra 27. Verifica la disponibilidad real en la app."], ["Haz visible la incertidumbre", "Fecha de revisión, estimaciones USD y carácter independiente deben etiquetarse, no presentarse como garantías permanentes."]], source: "Fuentes revisadas: Sobre Hacoo, Términos de servicio, Centro de ayuda oficial sobre zonas de entrega y rutas del catálogo principal · 28 de agosto de 2026." },
  finds: { headingIndex: "DESTINOS DE PRODUCTO COINCIDENTES", headingTitle: "Primera imagen, título y URL revisados juntos.", headingText: "Las tarjetas usan la primera imagen actual de la página de destino exacta. Los USD son conversiones orientativas del precio de origen mostrado.", priceNote: "Referencia: CN¥6,75 = US$1, revisada el 28 de agosto de 2026. Vuelve a comprobar opción, precio de origen y total. Si cambió la imagen o el producto de destino, no continúes desde la tarjeta.", asideLabel: "HALLAZGOS / VERIFICACIÓN", asideTitle: "Un catálogo pequeño puede resultar más útil.", asideText: "El volumen no es señal de calidad. Una tarjeta útil conserva la relación entre descubrimiento y destino activo.", items: [["Ficha exacta", "Ninguna tarjeta conduce a la portada, una búsqueda genérica u otra plataforma."], ["Primera imagen coincidente", "La imagen mostrada aquí es la primera imagen del mismo destino."], ["Precio de origen visible", "La cifra CNY original permanece junto a la estimación en USD."], ["Comprobación de opción actual", "La página de destino manda sobre color, talla, variante, inventario y precio final."]] },
  qc: { asideLabel: "QC / 01—07", asideTitle: "Un orden de inspección repetible", asideText: "Empieza por la vista general y acércate después. La página de devoluciones pide pruebas distintas según el problema; fotografía lo que identifica el pedido y también el defecto.", items: [["Confirma la variante pedida", "Compara color, talla, versión y cantidad antes de juzgar detalles."], ["Revisa la forma general", "Busca deformación, asimetría, paneles irregulares y proporciones distintas de la ficha."], ["Inspecciona la confección", "Amplía costuras, bordes, cierres y uniones. Pide otro ángulo si algo queda oculto."], ["Lee etiquetas y código de bolsa", "Para talla, la guía oficial pide etiqueta, código de la bolsa y explicación de dónde queda grande o pequeño."], ["Compara color y medidas", "La luz altera el color. Usa medidas publicadas y una foto con regla para dimensiones críticas."], ["Documenta el daño con contexto", "En roturas, fotografía embalaje exterior, bolsa y zona dañada antes de desechar nada."], ["Clasifica el problema", "Producto incorrecto, artículo faltante, paquete equivocado y descripción inexacta requieren imágenes y registros distintos."]], source: "Fuente revisada: política y proceso de devolución del Centro de ayuda de Hacoo · 28 de agosto de 2026." },
  shipping: { facts: [["28*", "países indicados; la lista oficial actual nombra 27"], ["15–28", "días como referencia total amplia del Centro de ayuda"], ["15–65", "días en los rangos por país de la página de envíos"]], asideLabel: "ENVÍO / VERIFICACIÓN", asideTitle: "Las páginas oficiales ofrecen más de un rango.", asideText: "El Centro de ayuda divide la entrega en 3–7 días de preparación, 7–15 de envío y 5–10 de reparto final. La web indica aparte 15–25 días para Reino Unido, Francia, Alemania e Italia; 15–30 para España; y 25–65 para otros países.", items: [["Confirma la dirección admitida", "Introduce el destino real y comprueba si el artículo y la ruta están disponibles."], ["Lee el plazo como orientación", "Ambas páginas muestran que puede cambiar; no conviertas el valor más rápido en promesa."], ["Prevé paquetes separados", "La web dice que artículos disponibles pueden enviarse antes que reservas o reposiciones del mismo pedido."], ["Compara el coste completo", "Incluye entrega, conversión de pago, impuestos aplicables y suplementos de opción."], ["Corrige pronto una dirección", "La guía oficial responsabiliza al comprador de su exactitud y pide contactar de inmediato con soporte si hay error."], ["Guarda pedido y seguimiento", "Conserva variante, estimación, estado de cada paquete y comunicaciones con soporte."]], source: "Fuentes revisadas: Shipping & Delivery de Hacoo y Centro de ayuda UE sobre plazos y zonas · 28 de agosto de 2026." },
  returns: { facts: [["15", "días tras la recepción para solicitudes aptas"], ["NO", "hay servicio de cambio según la política actual"], ["$30", "compensación máxima de envío en casos atribuidos a Hacoo"]], asideLabel: "DEVOLUCIONES / PRUEBAS", asideTitle: "Documenta el problema antes de usar el artículo.", asideText: "La guía oficial excluye algunas categorías de la devolución gratuita y avisa de que productos usados, lavados, modificados o sin etiqueta pueden rechazarse. Las condiciones del pedido son la revisión final.", items: [["Abre las condiciones del pedido", "Comprueba elegibilidad, fecha límite y pasos en las pantallas del producto y pedido."], ["Conoce exclusiones habituales", "Belleza abierta; ropa interior, baño, leggings y lencería; joyería/lujo; y electrónica indicada pueden quedar fuera de devolución gratuita."], ["Fotografía el paquete", "Captura embalaje exterior, etiqueta de envío, bolsa del producto y estado antes de tirar nada."], ["Muestra el artículo completo", "Haz una vista general y primeros planos del defecto, opción incorrecta o parte faltante."], ["Obtén aprobación antes de enviar", "La página dice que devoluciones no aprobadas pueden rechazarse y que no hay recogida actualmente."], ["Sé realista con los costes", "Si el motivo es del cliente, este puede pagar devolución/aduanas; el envío original figura como no reembolsable."], ["No esperes un cambio", "La política actual no admite cambios; otra talla puede exigir devolución y nuevo pedido."]], source: "Fuentes revisadas: política de devolución de Hacoo y ‘¿Cómo devolver los productos?’ · 28 de agosto de 2026." },
  categories: ["Calzado", "Sudaderas", "Camisetas", "Chaquetas", "Pantalones / Shorts", "Gorras y sombreros", "Accesorios", "Conjuntos cortos", "Electrónica", "Otros hallazgos", "Camisetas deportivas"],
  productCategories: { Shoes: "Calzado", Accessories: "Accesorios", "Other Stuff": "Otros artículos", "T-Shirts": "Camisetas", Hoodies: "Sudaderas" },
  faq: [["¿Es esta la web oficial de Hacoo?", "No. Hacoo VIP es una guía independiente de investigación y descubrimiento; no afirma estar afiliada a Hacoo. Producto, pago y políticas deben revisarse en el destino."], ["¿Qué es una hoja Hacoo?", "Es un índice seleccionado de hallazgos, términos de búsqueda y consejos de comprobación. Reduce tiempo, pero no garantiza vendedor, inventario ni entrega."], ["¿Los precios son fijos?", "No. Los USD son referencias. Precio, opciones, cambio, entrega y promociones pueden variar en la página activa."], ["¿Cómo uso fotos QC?", "Compara primero variante y medidas; luego forma, costuras, simetría, etiquetas, color y daños. Pide otra imagen si una zona crítica no se ve."], ["¿Dónde entrega Hacoo?", "La ayuda oficial afirma 28 países pero nombra 27: 22 europeos más Estados Unidos, México, Canadá, Brasil y Australia. Verifica artículo y dirección en la app."], ["¿Cuánto puede tardar?", "El Centro de ayuda da 15–28 días como referencia amplia. La página de envíos indica 15–25 para Reino Unido, Francia, Alemania e Italia; 15–30 para España; y 25–65 para otros países. Son orientaciones, no garantías."], ["¿Qué debo saber de devoluciones?", "La guía oficial suele exigir solicitud en 15 días. Algunas categorías no tienen devolución gratuita, no se ofrecen cambios y las pruebas dependen del problema."], ["¿Qué pruebas pueden pedir?", "Según el caso: etiqueta de talla, código de bolsa, paquete exterior, etiqueta de envío, factura, foto completa y detalle del defecto o falta."], ["¿Hacoo es tienda o comunidad?", "Sobre nosotros y los Términos actuales describen un ecosistema comunitario de contenido y descubrimiento entre usuarios y creadores. Sus páginas públicas también explican envío y posventa. Este sitio es un índice independiente."]],
};

const fr: LocaleContent = {
  common: { menu: "MENU", explore: "Explorer", sourcePrice: "prix source", minutes: "10–12 MIN", researchSuffix: "Les faits officiels, signaux d’avis tiers et conseils éditoriaux sont distingués. Les politiques et annonces en ligne peuvent évoluer.", nextStep: "ÉTAPE SUIVANTE", testWorkflow: "Testez la méthode sur une annonce en ligne.", shippingFacts: "Faits de livraison", returnsFacts: "Faits de retour", whatsapp: "Contacter sur WhatsApp", home: "Accueil", sourcesMethodology: "Sources et méthode", checked: "Vérifié" },
  home: { newCheck: "NOUVEAU CONTRÔLE", imageTitleUrl: "Image + titre + URL exacte", accessoryCaption: "Accessoires / 02", howItWorks: "COMMENT ÇA MARCHE", workflow: "Trouver → vérifier\ninspecter → planifier", noClaims: "Aucun total inventé. Aucune formulation faussement officielle.", categoryIndex: "01 / CATÉGORIES", findsIndex: "02 / SÉLECTIONS VÉRIFIÉES", priceNote: "Les montants USD sont des repères. Confirmez l’option, le prix en direct, la livraison et le total sur la page de destination.", methodIndex: "03 / MÉTHODE", articlesIndex: "04 / ARTICLES", faqIndex: "05 / FAQ", faqText: "Des réponses claires fondées sur les informations publiques et un contrôle prudent des annonces." },
  pageInfo: {
    spreadsheet: { eyebrow: "TABLEUR HACOO 2026", title: "Cherchez moins. Vérifiez davantage.", text: "Hacoo se présente comme une plateforme communautaire de contenu et de découverte. Ce tableur indépendant transforme cette intention en destinations exactes de catégories et produits ; ce n’est pas un catalogue officiel Hacoo." },
    finds: { eyebrow: "SÉLECTIONS HACOO VÉRIFIÉES", title: "Une liste plus courte, avec une raison de cliquer.", text: "Chaque carte associe la première image actuelle de la destination, le titre exact, le prix source, une estimation USD et l’URL directe du produit." },
    "qc-guide": { eyebrow: "GUIDE PHOTOS QC", title: "Cherchez des preuves, pas du réconfort.", text: "Une séquence pratique inspirée des justificatifs demandés par le guide officiel Hacoo pour taille, qualité, casse, mauvais article et article manquant." },
    shipping: { eyebrow: "LIVRAISON HACOO", title: "Planifiez avec des fourchettes, pas des promesses.", text: "Les pages officielles publient une couverture et plusieurs délais. Cette page conserve leurs différences au lieu de fabriquer une date garantie." },
    returns: { eyebrow: "RETOURS HACOO", title: "Connaissez le délai avant d’en avoir besoin.", text: "Le guide officiel indique généralement une demande sous 15 jours après réception pour les articles éligibles, cite les exclusions et précise que l’échange n’est pas proposé actuellement." },
    articles: { eyebrow: "BIBLIOTHÈQUE DE RECHERCHE HACOO", title: "Une question par guide.", text: "Des articles ciblés et lisibles sur les tableurs, les liens, la livraison et les retours." },
    faq: { eyebrow: "FAQ HACOO", title: "Réponses simples. Limites visibles.", text: "Aucun volume gonflé ni affiliation prétendue : uniquement des vérifications reproductibles." },
  },
  spreadsheet: { searchLabel: "RECHERCHE CATALOGUE EN DIRECT", searchTitle: "Employez une expression produit précise.", headingIndex: "DESTINATIONS DE CATÉGORIE EXACTES", headingTitle: "Ouvrez la destination, pas un accueil générique.", headingText: "Chaque carte ouvre la catégorie correspondante du catalogue principal en ligne.", asideLabel: "TABLEUR / MÉTHODE", asideTitle: "Ce que cet index peut prouver — et ce qu’il ne peut pas.", asideText: "Les conditions Hacoo attribuent la responsabilité des contenus utilisateurs aux créateurs indépendants. Un tableur est donc un outil de découverte, pas une recommandation officielle.", items: [["Utiliser une destination exacte", "Une carte catégorie ouvre sa catégorie ; une carte produit ouvre une fiche produit précise."], ["Comparer image et titre", "Une URL fonctionnelle ne suffit pas. La première image et le titre actuels doivent encore correspondre à la carte source."], ["Vérifier pays et région", "Hacoo annonce 28 pays mais la liste officielle actuelle en nomme 27. Vérifiez la disponibilité réelle dans l’application."], ["Montrer l’incertitude", "Date de contrôle, estimation USD et statut indépendant doivent être indiqués, pas présentés comme garanties permanentes."]], source: "Sources vérifiées : À propos, Conditions d’utilisation, Centre d’aide officiel sur les zones de livraison et routes du catalogue principal · 28 août 2026." },
  finds: { headingIndex: "DESTINATIONS PRODUIT APPARIÉES", headingTitle: "Première image, titre et URL vérifiés ensemble.", headingText: "Ces cartes utilisent la première image actuelle de la destination exacte. Les USD sont des conversions indicatives du prix source affiché.", priceNote: "Référence : CN¥6,75 = 1 US$, vérifiée le 28 août 2026. Revérifiez option, prix source et total. Si l’image ou le produit a changé, ne poursuivez pas depuis la carte.", asideLabel: "SÉLECTIONS / VÉRIFICATION", asideTitle: "Un petit catalogue peut être plus utile.", asideText: "Le volume n’est pas un signal de qualité. Une carte utile conserve le lien entre découverte et destination en direct.", items: [["Fiche exacte", "Aucune carte ne renvoie vers l’accueil, une recherche générique ou une autre plateforme."], ["Première image correspondante", "L’image affichée ici est la première image produit de la même destination."], ["Prix source visible", "Le montant CNY d’origine reste visible à côté de l’estimation USD."], ["Option actuelle à vérifier", "La destination reste la référence pour couleur, taille, variante, stock et prix final."]] },
  qc: { asideLabel: "QC / 01—07", asideTitle: "Un ordre d’inspection répétable", asideText: "Commencez par la vue générale, puis rapprochez-vous. La page de retours Hacoo demande des preuves différentes selon le problème ; photographiez l’identification de la commande et le défaut.", items: [["Confirmer la variante commandée", "Comparer couleur, taille, version et quantité avant d’évaluer les détails."], ["Contrôler la forme générale", "Repérer déformation, asymétrie, panneaux irréguliers et proportions différentes de l’annonce."], ["Inspecter la fabrication", "Agrandir coutures, bords, attaches et jonctions. Demander un autre angle si une zone est cachée."], ["Lire étiquette et code du sachet", "Pour un problème de taille, le guide demande l’étiquette, le code-barres du sachet et une explication de l’ajustement."], ["Comparer couleur et mesures", "L’éclairage modifie la couleur. Utiliser les mesures publiées et une photo avec règle pour les dimensions critiques."], ["Documenter les dommages en contexte", "En cas de casse, photographier emballage extérieur, sachet et zone endommagée avant de jeter quoi que ce soit."], ["Classer le problème", "Mauvais produit, article manquant, mauvais colis et écart de description exigent des images et dossiers différents."]], source: "Source vérifiée : politique et procédure de retour du Centre d’aide Hacoo · 28 août 2026." },
  shipping: { facts: [["28*", "pays annoncés ; 27 actuellement nommés dans la liste officielle"], ["15–28", "jours, référence globale du Centre d’aide"], ["15–65", "jours dans les fourchettes par pays de la page livraison"]], asideLabel: "LIVRAISON / VÉRIFICATION", asideTitle: "Les pages officielles donnent plusieurs fourchettes.", asideText: "Le Centre d’aide répartit 3–7 jours de préparation, 7–15 d’expédition et 5–10 de livraison finale. Le site indique séparément 15–25 jours pour Royaume-Uni, France, Allemagne et Italie ; 15–30 pour l’Espagne ; 25–65 pour les autres pays.", items: [["Confirmer l’éligibilité de l’adresse", "Saisir la destination réelle et vérifier la disponibilité de l’article et de l’itinéraire."], ["Lire le délai comme une indication", "Les deux pages montrent qu’il peut varier ; ne pas transformer la valeur la plus rapide en promesse."], ["Prévoir des colis séparés", "Le site précise que les articles disponibles peuvent partir avant les précommandes ou réassorts de la même commande."], ["Comparer le coût complet", "Inclure livraison, conversion du paiement, taxe applicable et suppléments d’option."], ["Corriger vite une adresse", "Le guide officiel rend l’acheteur responsable de l’exactitude et invite à contacter immédiatement l’assistance en cas d’erreur."], ["Conserver commande et suivi", "Garder variante, estimation, état de chaque colis et échanges avec l’assistance."]], source: "Sources vérifiées : Hacoo Shipping & Delivery et Centre d’aide UE sur délais et zones · 28 août 2026." },
  returns: { facts: [["15", "jours après réception pour une demande éligible"], ["NON", "service d’échange selon la politique actuelle"], ["$30", "compensation de transport maximale si responsabilité Hacoo confirmée"]], asideLabel: "RETOURS / PREUVES", asideTitle: "Documentez le problème avant utilisation.", asideText: "Le guide officiel exclut certaines catégories du retour gratuit et indique qu’un article utilisé, lavé, modifié ou sans étiquette peut être refusé. Les conditions de la commande restent déterminantes.", items: [["Ouvrir les conditions de commande", "Vérifier éligibilité, échéance et étapes dans les interfaces produit et commande."], ["Connaître les exclusions fréquentes", "Beauté ouverte ; sous-vêtements, bain, leggings et lingerie ; bijoux/luxe ; et électronique citée peuvent être exclus du retour gratuit."], ["Photographier le colis", "Capturer emballage extérieur, étiquette d’expédition, sachet produit et état avant de jeter."], ["Montrer l’article complet", "Faire une vue entière puis des gros plans du défaut, de l’option erronée ou de la pièce manquante."], ["Obtenir l’accord avant l’envoi", "La page indique qu’un retour non approuvé peut être refusé et qu’aucune collecte n’est proposée actuellement."], ["Rester réaliste sur les coûts", "Pour un motif client, retour/douane peuvent rester à sa charge ; les frais initiaux sont indiqués non remboursables."], ["Ne pas attendre un échange", "La politique actuelle ne propose pas d’échange ; une autre taille peut demander retour puis nouvelle commande."]], source: "Sources vérifiées : politique de retour Hacoo et « Comment retourner les produits ? » · 28 août 2026." },
  categories: ["Chaussures", "Sweats", "T-shirts", "Vestes", "Pantalons / Shorts", "Couvre-chefs", "Accessoires", "Ensembles courts", "Électronique", "Autres sélections", "Maillots"],
  productCategories: { Shoes: "Chaussures", Accessories: "Accessoires", "Other Stuff": "Autres articles", "T-Shirts": "T-shirts", Hoodies: "Sweats" },
  faq: [["Est-ce le site officiel Hacoo ?", "Non. Hacoo VIP est un guide indépendant de recherche et découverte, sans prétendre être affilié à Hacoo. Produit, paiement et politiques doivent être vérifiés sur la destination."], ["Qu’est-ce qu’un tableur Hacoo ?", "Un index organisé de produits, termes de recherche et conseils de contrôle. Il raccourcit la découverte sans garantir vendeur, stock ou livraison."], ["Les prix sont-ils fixes ?", "Non. Les USD sont des repères. Prix, options, change, livraison et promotions peuvent évoluer sur la page en direct."], ["Comment utiliser les photos QC ?", "Comparer d’abord variante et mesures, puis forme, coutures, symétrie, étiquettes, couleur et dommages. Demander une autre image si une zone critique est floue."], ["Où Hacoo livre-t-il ?", "L’aide officielle annonce 28 pays mais en nomme 27 : 22 en Europe plus États-Unis, Mexique, Canada, Brésil et Australie. Vérifier article et adresse dans l’app."], ["Combien de temps peut prendre la livraison ?", "Le Centre d’aide donne 15–28 jours comme référence large. La page livraison indique 15–25 pour Royaume-Uni, France, Allemagne et Italie ; 15–30 pour l’Espagne ; 25–65 pour les autres. Ce sont des indications, pas des garanties."], ["Que savoir sur les retours ?", "Le guide officiel demande généralement une requête sous 15 jours. Certaines catégories n’ont pas de retour gratuit, l’échange n’est pas proposé et les preuves varient selon le problème."], ["Quelles preuves peuvent être demandées ?", "Selon le cas : étiquette de taille, code du sachet, colis extérieur, étiquette d’envoi, facture, vue complète et gros plan du défaut ou élément manquant."], ["Hacoo est-il une boutique ou une communauté ?", "Les pages À propos et Conditions actuelles décrivent un écosystème communautaire de contenu et découverte reliant utilisateurs et créateurs. Des pages publiques traitent aussi livraison et après-vente. Ce site est un index indépendant."]],
};

const it: LocaleContent = {
  common: { menu: "MENU", explore: "Esplora", sourcePrice: "prezzo origine", minutes: "10–12 MIN", researchSuffix: "Fatti ufficiali, segnali da recensioni di terzi e consigli editoriali sono indicati separatamente. Politiche e inserzioni attive possono cambiare.", nextStep: "PASSO SUCCESSIVO", testWorkflow: "Prova il metodo su un’inserzione attiva.", shippingFacts: "Dati spedizione", returnsFacts: "Dati resi", whatsapp: "Contatta su WhatsApp", home: "Home", sourcesMethodology: "Fonti e metodologia", checked: "Controllato" },
  home: { newCheck: "NUOVO CONTROLLO", imageTitleUrl: "Immagine + titolo + URL esatto", accessoryCaption: "Accessori / 02", howItWorks: "COME FUNZIONA", workflow: "Trova → verifica\ncontrolla → pianifica", noClaims: "Nessun totale inventato. Nessuna affermazione dal tono ufficiale.", categoryIndex: "01 / CATEGORIE", findsIndex: "02 / SCOPERTE SELEZIONATE", priceNote: "Gli importi USD sono riferimenti di pianificazione. Conferma opzione, prezzo attivo, consegna e totale sulla pagina di destinazione.", methodIndex: "03 / METODO", articlesIndex: "04 / ARTICOLI", faqIndex: "05 / FAQ", faqText: "Risposte chiare basate su informazioni pubbliche e verifiche prudenti delle inserzioni." },
  pageInfo: {
    spreadsheet: { eyebrow: "FOGLIO HACOO 2026", title: "Cerca meno. Verifica di più.", text: "Hacoo si descrive come piattaforma comunitaria di contenuti e scoperta. Questo foglio indipendente trasforma tale intento in destinazioni esatte di categorie e prodotti; non è un catalogo ufficiale Hacoo." },
    finds: { eyebrow: "SCOPERTE HACOO SELEZIONATE", title: "Una lista più piccola con un motivo per cliccare.", text: "Ogni scheda unisce prima immagine attuale della destinazione, titolo esatto, prezzo origine, stima USD e URL diretto del dettaglio." },
    "qc-guide": { eyebrow: "GUIDA FOTO QC", title: "Cerca prove, non rassicurazioni.", text: "Una sequenza pratica basata sulle prove richieste dalla guida resi ufficiale Hacoo per taglia, qualità, rottura, articolo errato o mancante." },
    shipping: { eyebrow: "SPEDIZIONE HACOO", title: "Pianifica con intervalli, non promesse.", text: "Le pagine ufficiali pubblicano copertura e diversi tempi. Questa pagina mantiene le differenze senza trasformarle in una data garantita." },
    returns: { eyebrow: "RESI HACOO", title: "Conosci la finestra prima di averne bisogno.", text: "La guida ufficiale indica in genere una richiesta entro 15 giorni dalla consegna per i prodotti idonei, elenca esclusioni e dice che il cambio non è attualmente supportato." },
    articles: { eyebrow: "BIBLIOTECA DI RICERCA HACOO", title: "Una domanda per guida.", text: "Articoli mirati e leggibili su fogli, controllo link, consegna e resi." },
    faq: { eyebrow: "FAQ HACOO", title: "Risposte semplici. Limiti visibili.", text: "Niente totali gonfiati o affiliazioni dichiarate: solo controlli ripetibili." },
  },
  spreadsheet: { searchLabel: "RICERCA CATALOGO ATTIVO", searchTitle: "Usa una frase prodotto specifica.", headingIndex: "DESTINAZIONI CATEGORIA ESATTE", headingTitle: "Apri la destinazione, non una home generica.", headingText: "Ogni scheda apre la categoria corrispondente nel catalogo principale attivo.", asideLabel: "FOGLIO / METODO", asideTitle: "Cosa questo indice può provare — e cosa no.", asideText: "I termini Hacoo attribuiscono ai creator indipendenti la responsabilità dei contenuti utente. Un foglio è quindi uno strumento di scoperta, non un’approvazione ufficiale.", items: [["Usa una destinazione esatta", "Una scheda categoria apre la categoria corrispondente; una scheda prodotto apre una singola pagina dettaglio."], ["Confronta immagine e titolo", "Non basta un URL funzionante. Prima immagine e titolo attuali devono ancora corrispondere alla scheda fonte."], ["Controlla paese e regione", "Hacoo dichiara 28 paesi supportati, ma l’elenco ufficiale attuale ne nomina 27. Verifica la disponibilità reale nell’app."], ["Mantieni visibile l’incertezza", "Data di verifica, stime USD e stato indipendente vanno etichettati, non presentati come garanzie permanenti."]], source: "Fonti verificate: Chi siamo, Termini di servizio, Centro assistenza ufficiale sulle aree di consegna e rotte del catalogo principale · 28 agosto 2026." },
  finds: { headingIndex: "DESTINAZIONI PRODOTTO ABBINATE", headingTitle: "Prima immagine, titolo e URL verificati insieme.", headingText: "Queste schede usano la prima immagine attuale della pagina esatta. Gli USD sono conversioni indicative del prezzo origine mostrato.", priceNote: "Riferimento: CN¥6,75 = US$1, verificato il 28 agosto 2026. Ricontrolla opzione, prezzo origine e totale. Se immagine o prodotto sono cambiati, non proseguire dalla scheda.", asideLabel: "SCOPERTE / VERIFICA", asideTitle: "Un piccolo catalogo può essere più utile.", asideText: "Il volume non indica qualità. Una scheda utile mantiene il rapporto tra scoperta e destinazione attiva.", items: [["Pagina dettaglio esatta", "Nessuna scheda rimanda alla home, a una ricerca generica o a un’altra piattaforma."], ["Prima immagine corrispondente", "L’immagine mostrata qui è la prima immagine prodotto della stessa destinazione."], ["Prezzo origine visibile", "La cifra CNY originale resta accanto alla stima USD."], ["Controllo opzione attuale", "La destinazione resta autorevole per colore, taglia, variante, scorte e prezzo finale."]] },
  qc: { asideLabel: "QC / 01—07", asideTitle: "Un ordine di ispezione ripetibile", asideText: "Inizia dalla vista generale e poi avvicinati. La pagina resi Hacoo richiede prove diverse secondo il problema; fotografa ciò che identifica l’ordine e il difetto.", items: [["Conferma la variante ordinata", "Confronta colore, taglia, versione e quantità prima di valutare i dettagli."], ["Controlla la forma generale", "Cerca deformazioni, asimmetria, pannelli irregolari e proporzioni diverse dall’inserzione."], ["Esamina la costruzione", "Ingrandisci cuciture, bordi, chiusure e giunzioni. Chiedi un’altra angolazione se una zona è nascosta."], ["Leggi etichetta e codice busta", "Per problemi di taglia, la guida ufficiale chiede etichetta, barcode della busta e spiegazione della vestibilità errata."], ["Confronta colore e misure", "La luce cambia il colore. Usa misure indicate e foto con righello per dimensioni critiche."], ["Documenta il danno nel contesto", "Per rotture, fotografa imballo esterno, busta e zona danneggiata prima di eliminare l’imballaggio."], ["Classifica il problema", "Prodotto errato, articolo mancante, pacco sbagliato e descrizione inesatta richiedono immagini e registri diversi."]], source: "Fonte verificata: politica e procedura resi del Centro assistenza Hacoo · 28 agosto 2026." },
  shipping: { facts: [["28*", "paesi dichiarati; 27 attualmente nominati nell’elenco ufficiale"], ["15–28", "giorni come riferimento totale ampio del Centro assistenza"], ["15–65", "giorni negli intervalli per paese della pagina spedizioni"]], asideLabel: "SPEDIZIONE / VERIFICA", asideTitle: "Le pagine ufficiali forniscono più intervalli.", asideText: "Il Centro assistenza divide 3–7 giorni di preparazione, 7–15 di spedizione e 5–10 di consegna finale. Il sito indica separatamente 15–25 giorni per Regno Unito, Francia, Germania e Italia; 15–30 per Spagna; 25–65 per altri paesi.", items: [["Conferma l’idoneità dell’indirizzo", "Inserisci la destinazione reale e controlla disponibilità di articolo e rotta."], ["Leggi il tempo come indicazione", "Entrambe le pagine mostrano che può cambiare; non trasformare il valore più rapido in promessa."], ["Prevedi pacchi separati", "Il sito dice che articoli disponibili possono partire prima di preordini o riassortimenti dello stesso ordine."], ["Confronta il costo completo", "Includi consegna, conversione pagamento, imposte applicabili e supplementi opzione."], ["Correggi subito un indirizzo", "La guida ufficiale rende l’acquirente responsabile dell’esattezza e invita a contattare subito l’assistenza in caso di errore."], ["Conserva ordine e tracciamento", "Salva variante, stima, stato di ogni pacco e comunicazioni con l’assistenza."]], source: "Fonti verificate: Hacoo Shipping & Delivery e Centro assistenza UE su tempi e aree · 28 agosto 2026." },
  returns: { facts: [["15", "giorni dal ricevimento per richieste idonee"], ["NO", "servizio di cambio secondo la politica attuale"], ["$30", "rimborso massimo spedizione nei casi attribuiti a Hacoo"]], asideLabel: "RESI / PROVE", asideTitle: "Documenta il problema prima dell’uso.", asideText: "La guida ufficiale esclude alcune categorie dal reso gratuito e dice che prodotti usati, lavati, modificati o senza etichetta possono essere rifiutati. Le regole del singolo ordine restano decisive.", items: [["Apri le condizioni dell’ordine", "Controlla idoneità, scadenza e passaggi nelle schermate prodotto e ordine."], ["Conosci le esclusioni comuni", "Beauty aperto; intimo, costumi, leggings e lingerie; gioielli/lusso; ed elettronica indicata possono essere esclusi dal reso gratuito."], ["Fotografa il pacco", "Riprendi imballo esterno, etichetta spedizione, busta prodotto e condizioni prima di buttare."], ["Mostra l’articolo completo", "Scatta una vista intera e primi piani del difetto, opzione errata o parte mancante."], ["Ottieni approvazione prima dell’invio", "La pagina dice che resi non approvati possono essere rifiutati e che il ritiro non è supportato."], ["Mantieni realistiche le aspettative sui costi", "Per motivi del cliente, spedizione reso/dogana possono restare a suo carico; le spese iniziali risultano non rimborsabili."], ["Non aspettarti un cambio", "La politica attuale non supporta cambi; un’altra taglia può richiedere reso e nuovo ordine."]], source: "Fonti verificate: politica resi Hacoo e ‘Come restituire i prodotti?’ · 28 agosto 2026." },
  categories: ["Scarpe", "Felpe", "T-shirt", "Giacche", "Pantaloni / Shorts", "Copricapi", "Accessori", "Completi corti", "Elettronica", "Altre scoperte", "Maglie sportive"],
  productCategories: { Shoes: "Scarpe", Accessories: "Accessori", "Other Stuff": "Altri articoli", "T-Shirts": "T-shirt", Hoodies: "Felpe" },
  faq: [["È il sito ufficiale Hacoo?", "No. Hacoo VIP è una guida indipendente di ricerca e scoperta e non dichiara affiliazione a Hacoo. Prodotto, pagamento e politiche vanno controllati sulla destinazione."], ["Cos’è un foglio Hacoo?", "Un indice selezionato che raggruppa prodotti, termini di ricerca e consigli di controllo. Riduce il tempo, ma non garantisce venditore, scorte o consegna."], ["I prezzi sono fissi?", "No. Gli USD sono riferimenti. Prezzo, opzioni, cambio, consegna e promozioni possono variare nella pagina attiva."], ["Come uso le foto QC?", "Confronta prima variante e misure, poi forma, cuciture, simmetria, etichette, colore e danni. Chiedi un’altra immagine se una zona critica non è chiara."], ["Dove consegna Hacoo?", "L’aiuto ufficiale dichiara 28 paesi ma ne nomina 27: 22 europei più Stati Uniti, Messico, Canada, Brasile e Australia. Verifica articolo e indirizzo nell’app."], ["Quanto può durare la consegna?", "Il Centro assistenza indica 15–28 giorni come riferimento ampio. La pagina spedizioni indica 15–25 per Regno Unito, Francia, Germania e Italia; 15–30 per Spagna; 25–65 per altri paesi. Sono linee guida, non garanzie."], ["Cosa sapere sui resi?", "La guida ufficiale richiede in genere domanda entro 15 giorni. Alcune categorie non hanno reso gratuito, non sono offerti cambi e le prove dipendono dal problema."], ["Quali prove possono chiedere?", "Secondo il caso: etichetta taglia, barcode busta, pacco esterno, etichetta spedizione, fattura, foto completa e dettaglio del difetto o parte mancante."], ["Hacoo è negozio o community?", "Le attuali pagine Chi siamo e Termini descrivono un ecosistema comunitario di contenuti e scoperta tra utenti e creator. Le pagine pubbliche spiegano anche spedizione e post-vendita. Questo sito è un indice indipendente."]],
};

export const localizedContent: Record<Lang, LocaleContent> = { en, de, es, fr, it };
