export type Lang = "en" | "de" | "es" | "fr" | "it";

export const languages: { code: Lang; label: string; short: string }[] = [
  { code: "en", label: "English", short: "EN" },
  { code: "de", label: "Deutsch", short: "DE" },
  { code: "es", label: "Español", short: "ES" },
  { code: "fr", label: "Français", short: "FR" },
  { code: "it", label: "Italiano", short: "IT" },
];

export const coreRouteKeys = ["", "spreadsheet", "finds", "qc-guide", "shipping", "returns", "articles", "faq"] as const;
export const trustRouteKeys = ["about", "contact", "editorial-policy", "sources-policy", "corrections-policy", "privacy", "terms"] as const;
export const routeKeys = [...coreRouteKeys, ...trustRouteKeys] as const;
export type CoreRouteKey = (typeof coreRouteKeys)[number];
export type TrustRouteKey = (typeof trustRouteKeys)[number];
export type RouteKey = (typeof routeKeys)[number];

export const articleSlugs = ["how-to-use-hacoo-spreadsheet", "how-to-check-hacoo-links", "hacoo-shipping-and-returns-guide", "hacoo-reviews-what-users-report", "hacoo-product-decision-matrix"] as const;
export type ArticleSlug = (typeof articleSlugs)[number];

export function localizedPath(lang: Lang, path = "") {
  const clean = path.replace(/^\/+|\/+$/g, "");
  const prefix = lang === "en" ? "" : `/${lang}`;
  return `${prefix}/${clean}`.replace(/\/$/, "") || "/";
}

export const copy = {
  en: { nav: ["Home", "Spreadsheet", "Finds", "QC Guide", "Shipping", "Returns", "Articles", "FAQ"], heroEyebrow: "Independent Hacoo decision hub · Updated August 2026", heroTitle: "Compare Hacoo finds before you choose.", heroText: "Build a practical shortlist from matched product pages, compare the details that change the decision, and use QC, delivery and returns evidence before you continue.", search: "Search live products", placeholder: "Try sneakers, hoodie, jersey…", open: "Open live catalog", proof: ["Links checked", "USD planning", "Independent guide"], categoriesTitle: "Start with a category", categoriesText: "Every category opens a focused search on the live catalog—no unrelated platform links.", findsTitle: "Editor’s current shortlist", findsText: "Use the image and title as your first comparison, then confirm the live listing, variants and price before continuing.", methodTitle: "A comparison workflow for any Hacoo link", methodText: "A shortlist narrows the choice; it does not prove quality. Re-check the listing and seller information at the time you buy.", steps: [["Find", "Search by a specific item or category instead of relying on vague trend labels."], ["Compare", "Compare the image, title, options, measurements and latest listing status."], ["Inspect", "Use QC photos to check shape, stitching, labels, color and visible damage."], ["Decide", "Review delivery availability, total cost and current returns conditions before payment."]], articlesTitle: "Research notes, not filler", articlesText: "Guides are separated by search intent so each page answers one real question in depth.", faqTitle: "Questions people ask before opening a link", disclaimer: "Independent guide. Not Hacoo and not endorsed by Hacoo. Availability, price and policies can change; verify the live interface before paying.", updated: "Checked 28 August 2026", read: "Read guide", browse: "Browse all", result: "Open product" },
  de: { nav: ["Start", "Tabelle", "Funde", "QC-Guide", "Versand", "Retouren", "Artikel", "FAQ"], heroEyebrow: "Unabhängiger Hacoo-Ratgeber · Aktualisiert August 2026", heroTitle: "Eine Hacoo-Tabelle, die beim Entscheiden hilft.", heroText: "Entdecke kuratierte Modekategorien und nutze praktische Checklisten für QC, Lieferung und Retouren, bevor du eine Live-Produktseite öffnest.", search: "Live-Produkte suchen", placeholder: "Sneaker, Hoodie, Trikot…", open: "Live-Katalog öffnen", proof: ["Links geprüft", "USD-Planung", "Unabhängig"], categoriesTitle: "Mit einer Kategorie starten", categoriesText: "Jede Kategorie öffnet eine fokussierte Suche im Live-Katalog.", findsTitle: "Aktuelle Auswahl", findsText: "Vergleiche zuerst Bild und Titel und prüfe dann Varianten, Preis und Verfügbarkeit.", methodTitle: "Hacoo-Links sicherer verwenden", methodText: "Eine Tabelle hilft beim Entdecken, ist aber kein Qualitätsnachweis. Prüfe jedes Angebot erneut.", steps: [["Finden", "Suche nach einem konkreten Artikel oder einer Kategorie."], ["Prüfen", "Vergleiche Bild, Titel, Optionen, Maße und Status."], ["QC", "Prüfe Form, Nähte, Etiketten, Farbe und Schäden."], ["Planen", "Kontrolliere Lieferbarkeit, Gesamtkosten und Retourenbedingungen."]], articlesTitle: "Nützliche Recherche", articlesText: "Jede Anleitung beantwortet eine klare Suchfrage.", faqTitle: "Fragen vor dem Öffnen eines Links", disclaimer: "Unabhängiger Guide. Nicht Hacoo und nicht von Hacoo unterstützt. Preise und Regeln können sich ändern.", updated: "Geprüft am 28. August 2026", read: "Guide lesen", browse: "Alle ansehen", result: "Produkt öffnen" },
  es: { nav: ["Inicio", "Hoja", "Hallazgos", "Guía QC", "Envíos", "Devoluciones", "Artículos", "FAQ"], heroEyebrow: "Guía independiente de Hacoo · Actualizada en agosto de 2026", heroTitle: "Una hoja de Hacoo pensada para decidir mejor.", heroText: "Explora categorías seleccionadas y usa listas prácticas de QC, entrega y devoluciones antes de abrir una ficha activa.", search: "Buscar productos", placeholder: "Zapatillas, sudadera, camiseta…", open: "Abrir catálogo", proof: ["Enlaces revisados", "Precios en USD", "Guía independiente"], categoriesTitle: "Empieza por una categoría", categoriesText: "Cada categoría abre una búsqueda específica en el catálogo activo.", findsTitle: "Selección actual", findsText: "Compara imagen y título y después confirma variantes, precio y disponibilidad.", methodTitle: "Una forma más segura de usar enlaces", methodText: "Una hoja ayuda a descubrir; no demuestra la calidad. Revisa cada ficha al comprar.", steps: [["Buscar", "Usa un artículo o categoría concreta."], ["Verificar", "Compara imagen, título, opciones, medidas y estado."], ["Inspeccionar", "Revisa forma, costuras, etiquetas, color y daños."], ["Planificar", "Comprueba entrega, coste total y condiciones de devolución."]], articlesTitle: "Investigación útil", articlesText: "Cada guía responde una intención de búsqueda concreta.", faqTitle: "Preguntas antes de abrir un enlace", disclaimer: "Guía independiente. No es Hacoo ni está respaldada por Hacoo. Los precios y las políticas pueden cambiar.", updated: "Revisado el 28 de agosto de 2026", read: "Leer guía", browse: "Ver todo", result: "Abrir producto" },
  fr: { nav: ["Accueil", "Tableur", "Sélections", "Guide QC", "Livraison", "Retours", "Articles", "FAQ"], heroEyebrow: "Guide Hacoo indépendant · Mis à jour en août 2026", heroTitle: "Un tableur Hacoo conçu pour mieux décider.", heroText: "Explorez des catégories mode et utilisez des listes QC, livraison et retour avant d’ouvrir une fiche en ligne.", search: "Rechercher les produits", placeholder: "Baskets, sweat, maillot…", open: "Ouvrir le catalogue", proof: ["Liens vérifiés", "Repères USD", "Guide indépendant"], categoriesTitle: "Commencer par une catégorie", categoriesText: "Chaque catégorie ouvre une recherche ciblée dans le catalogue actif.", findsTitle: "Sélection actuelle", findsText: "Comparez l’image et le titre, puis vérifiez variantes, prix et disponibilité.", methodTitle: "Mieux utiliser un lien Hacoo", methodText: "Un tableur aide à découvrir, mais ne garantit pas la qualité. Revérifiez chaque fiche.", steps: [["Trouver", "Recherchez un article ou une catégorie précise."], ["Vérifier", "Comparez image, titre, options, mesures et statut."], ["Inspecter", "Contrôlez forme, coutures, étiquettes, couleur et défauts."], ["Planifier", "Vérifiez livraison, coût total et conditions de retour."]], articlesTitle: "Des recherches utiles", articlesText: "Chaque guide répond à une vraie question de recherche.", faqTitle: "Questions avant d’ouvrir un lien", disclaimer: "Guide indépendant. Ni Hacoo ni approuvé par Hacoo. Prix et politiques peuvent changer.", updated: "Vérifié le 28 août 2026", read: "Lire le guide", browse: "Tout voir", result: "Ouvrir le produit" },
  it: { nav: ["Home", "Foglio", "Scoperte", "Guida QC", "Spedizione", "Resi", "Articoli", "FAQ"], heroEyebrow: "Guida Hacoo indipendente · Aggiornata agosto 2026", heroTitle: "Un foglio Hacoo creato per decidere meglio.", heroText: "Esplora categorie moda selezionate e usa checklist QC, consegna e resi prima di aprire una scheda attiva.", search: "Cerca prodotti", placeholder: "Sneaker, felpa, maglia…", open: "Apri il catalogo", proof: ["Link controllati", "Stime USD", "Guida indipendente"], categoriesTitle: "Parti da una categoria", categoriesText: "Ogni categoria apre una ricerca mirata nel catalogo attivo.", findsTitle: "Selezione attuale", findsText: "Confronta immagine e titolo, poi conferma varianti, prezzo e disponibilità.", methodTitle: "Usare meglio un link Hacoo", methodText: "Un foglio aiuta a scoprire, ma non prova la qualità. Ricontrolla ogni inserzione.", steps: [["Trova", "Cerca un articolo o una categoria specifica."], ["Verifica", "Confronta immagine, titolo, opzioni, misure e stato."], ["Controlla", "Esamina forma, cuciture, etichette, colore e danni."], ["Pianifica", "Verifica consegna, costo totale e condizioni di reso."]], articlesTitle: "Ricerca utile", articlesText: "Ogni guida risponde a una domanda di ricerca precisa.", faqTitle: "Domande prima di aprire un link", disclaimer: "Guida indipendente. Non è Hacoo e non è approvata da Hacoo. Prezzi e regole possono cambiare.", updated: "Controllato il 28 agosto 2026", read: "Leggi guida", browse: "Vedi tutto", result: "Apri prodotto" },
} as const;

export const decisionCopy = {
  en: { heroEyebrow: "Independent Hacoo decision hub · Updated August 2026", heroTitle: "Compare Hacoo finds before you choose.", heroText: "Build a practical shortlist from matched product pages, compare the details that change the decision, and use QC, delivery and returns evidence before you continue.", findsTitle: "Editor’s current shortlist", findsText: "Use the image and title as your first comparison, then confirm the live listing, variants and price before continuing.", methodTitle: "A comparison workflow for any Hacoo link", methodText: "A shortlist narrows the choice; it does not prove quality. Re-check the live listing and seller information when you buy.", steps: [["Find", "Search for a specific item or category instead of relying on vague trend labels."], ["Compare", "Compare image, title, options, measurements and current listing status."], ["Inspect", "Use QC photos to check shape, stitching, labels, colour and visible damage."], ["Decide", "Review delivery availability, total cost and current returns conditions before payment."]] },
  de: { heroEyebrow: "Unabhängiger Hacoo-Entscheidungsratgeber · Aktualisiert August 2026", heroTitle: "Hacoo-Funde vergleichen, bevor du auswählst.", heroText: "Erstelle aus geprüften Produktseiten eine praktische Auswahlliste, vergleiche entscheidende Details und nutze QC-, Liefer- und Retourenbelege.", findsTitle: "Aktuelle redaktionelle Auswahlliste", findsText: "Vergleiche zuerst Bild und Titel und bestätige danach Live-Angebot, Varianten und Preis.", methodTitle: "Ein Vergleichsablauf für jeden Hacoo-Link", methodText: "Eine Auswahlliste grenzt die Wahl ein, beweist aber keine Qualität. Prüfe Angebot und Verkäufer beim Kauf erneut.", steps: [["Finden", "Suche nach einem konkreten Artikel oder einer Kategorie."], ["Vergleichen", "Vergleiche Bild, Titel, Optionen, Maße und aktuellen Status."], ["Prüfen", "Kontrolliere auf QC-Fotos Form, Nähte, Etiketten, Farbe und Schäden."], ["Entscheiden", "Prüfe Lieferbarkeit, Gesamtkosten und aktuelle Retourenbedingungen."]] },
  es: { heroEyebrow: "Guía independiente para decidir en Hacoo · Actualizada en agosto de 2026", heroTitle: "Compara hallazgos de Hacoo antes de elegir.", heroText: "Crea una lista útil con fichas verificadas, compara los detalles que cambian la decisión y revisa pruebas de QC, entrega y devolución.", findsTitle: "Lista editorial actual", findsText: "Compara primero imagen y título y confirma después la ficha activa, las variantes y el precio.", methodTitle: "Un proceso comparativo para cualquier enlace de Hacoo", methodText: "Una lista reduce opciones, pero no demuestra la calidad. Revisa de nuevo la ficha y el vendedor al comprar.", steps: [["Buscar", "Busca un artículo o una categoría concreta."], ["Comparar", "Compara imagen, título, opciones, medidas y estado actual."], ["Inspeccionar", "Revisa forma, costuras, etiquetas, color y daños en las fotos QC."], ["Decidir", "Comprueba entrega, coste total y condiciones actuales de devolución."]] },
  fr: { heroEyebrow: "Guide de décision Hacoo indépendant · Mis à jour en août 2026", heroTitle: "Comparez les sélections Hacoo avant de choisir.", heroText: "Créez une liste pratique à partir de fiches vérifiées, comparez les détails décisifs et consultez les preuves QC, livraison et retour.", findsTitle: "Liste éditoriale actuelle", findsText: "Comparez d’abord l’image et le titre, puis confirmez la fiche, les variantes et le prix en direct.", methodTitle: "Une méthode de comparaison pour chaque lien Hacoo", methodText: "Une liste réduit le choix sans prouver la qualité. Revérifiez la fiche et le vendeur au moment de l’achat.", steps: [["Trouver", "Recherchez un article ou une catégorie précise."], ["Comparer", "Comparez image, titre, options, mesures et statut actuel."], ["Inspecter", "Contrôlez forme, coutures, étiquettes, couleur et défauts sur les photos QC."], ["Décider", "Vérifiez livraison, coût total et conditions de retour actuelles."]] },
  it: { heroEyebrow: "Guida indipendente alle decisioni Hacoo · Aggiornata agosto 2026", heroTitle: "Confronta le proposte Hacoo prima di scegliere.", heroText: "Crea una lista pratica da schede verificate, confronta i dettagli decisivi e consulta prove QC, consegna e reso.", findsTitle: "Lista editoriale attuale", findsText: "Confronta prima immagine e titolo, poi conferma scheda, varianti e prezzo in tempo reale.", methodTitle: "Un metodo di confronto per ogni link Hacoo", methodText: "Una lista restringe la scelta ma non prova la qualità. Ricontrolla scheda e venditore al momento dell’acquisto.", steps: [["Trova", "Cerca un articolo o una categoria specifica."], ["Confronta", "Confronta immagine, titolo, opzioni, misure e stato attuale."], ["Controlla", "Esamina forma, cuciture, etichette, colore e danni nelle foto QC."], ["Decidi", "Verifica consegna, costo totale e condizioni di reso attuali."]] },
} as const;

export const categories = [
  ["Shoes", "https://cnfanssp.com/shoes/", "01"],
  ["Hoodies", "https://cnfanssp.com/hoodies-sweaters/", "02"],
  ["T-Shirts", "https://cnfanssp.com/t-shirts/", "03"],
  ["Jackets", "https://cnfanssp.com/jackets/", "04"],
  ["Pants / Shorts", "https://cnfanssp.com/pants-shorts/", "05"],
  ["Headwear", "https://cnfanssp.com/headwear/", "06"],
  ["Accessories", "https://cnfanssp.com/accessories/", "07"],
  ["Short Sets", "https://cnfanssp.com/short-sets/", "08"],
  ["Electronics", "https://cnfanssp.com/electronics/", "09"],
  ["Other Finds", "https://cnfanssp.com/other-stuff/", "10"],
  ["Jerseys", "https://cnfanssp.com/jersey/", "11"],
] as const;

export const products = [
  { title: "Shoes-2", category: "Shoes", price: "$43.00", image: "/products/cnfanssp-shoes-2.jpg", id: "5992", sourcePrice: "CN¥290" },
  { title: "PRADA Backpacks Bags — 10+ styles", category: "Other Stuff", price: "$51.11", image: "/products/cnfanssp-prada-backpack.webp", id: "5978", sourcePrice: "CN¥345" },
  { title: "Chrome Hearts T-shirt", category: "T-Shirts", price: "$13.19", image: "/products/cnfanssp-chrome-tshirt.jpg", id: "5971", sourcePrice: "CN¥89" },
  { title: "Travis Scott Hoodie", category: "Hoodies", price: "$27.41", image: "/products/cnfanssp-travis-hoodie.webp", id: "5940", sourcePrice: "CN¥185" },
] as const;

export const faq = [
  ["Is this the official Hacoo website?", "No. Hacoo VIP is an independent research and discovery guide. It does not claim affiliation with Hacoo. Live product, payment and policy details must be checked on the destination page."],
  ["What is a Hacoo spreadsheet?", "It is a curated index that groups product discoveries, search terms and checking advice. It should shorten discovery time, but it cannot guarantee seller quality, inventory or delivery."],
  ["Are the prices fixed?", "No. USD figures are planning references. Product price, options, exchange rate, delivery and promotions can change on the live page."],
  ["How should I use QC photos?", "Compare the ordered variant and measurements first, then inspect overall shape, stitching, symmetry, labels, color and visible damage. Ask for another image when a critical area is unclear."],
  ["Where does Hacoo deliver?", "The official help page states 28 supported countries but currently names 27: 22 in Europe plus the United States, Mexico, Canada, Brazil and Australia. Verify actual item and address availability in the app."],
  ["How long can delivery take?", "The Help Center gives a broad 15–28 day total reference. The website shipping page separately lists 15–25 days for the UK, France, Germany and Italy; 15–30 for Spain; and 25–65 for other countries. These are guidelines, not guarantees."],
  ["What should I know about returns?", "Official guidance says eligible return requests are generally made within 15 days after receipt. Some categories do not qualify for free return, exchanges are not currently offered, and evidence requirements differ by problem type."],
  ["What evidence can a return require?", "Depending on the issue, Hacoo may ask for the size label, product-bag barcode, outer package, shipping label, invoice, full product image and close-up of the defect or missing part."],
  ["Is Hacoo an online shop or a community platform?", "Hacoo’s current About Us and Terms describe a community-driven content-sharing and discovery ecosystem connecting users and independent creators. Its public pages also provide shipping and after-sales guidance. This site is an independent link index, not Hacoo."],
] as const;
