import type { Lang, TrustRouteKey } from "./site-data";

export type TrustPage = {
  eyebrow: string;
  title: string;
  intro: string;
  sections: readonly { title: string; text: string }[];
};

export const trustNav: Record<Lang, Record<TrustRouteKey, string>> = {
  en: { about: "About", contact: "Contact", "editorial-policy": "Editorial policy", "sources-policy": "Sources policy", "corrections-policy": "Corrections", privacy: "Privacy", terms: "Terms" },
  de: { about: "Über uns", contact: "Kontakt", "editorial-policy": "Redaktionsrichtlinie", "sources-policy": "Quellenrichtlinie", "corrections-policy": "Korrekturen", privacy: "Datenschutz", terms: "Bedingungen" },
  es: { about: "Quiénes somos", contact: "Contacto", "editorial-policy": "Política editorial", "sources-policy": "Política de fuentes", "corrections-policy": "Correcciones", privacy: "Privacidad", terms: "Condiciones" },
  fr: { about: "À propos", contact: "Contact", "editorial-policy": "Politique éditoriale", "sources-policy": "Politique des sources", "corrections-policy": "Corrections", privacy: "Confidentialité", terms: "Conditions" },
  it: { about: "Chi siamo", contact: "Contatti", "editorial-policy": "Politica editoriale", "sources-policy": "Politica delle fonti", "corrections-policy": "Correzioni", privacy: "Privacy", terms: "Termini" },
};

export const trustContent: Record<Lang, Record<TrustRouteKey, TrustPage>> = {
  en: {
    about: { eyebrow: "INDEPENDENT RESEARCH", title: "About Hacoo VIP", intro: "Hacoo VIP is an independent comparison and decision guide. It is not Hacoo, does not represent Hacoo and does not sell the products shown on this site.", sections: [{ title: "What we do", text: "We organise live catalogue destinations into practical shortlists and compare the details that affect a decision: current image and title, option, source price, measurements, listing status, delivery range and return evidence. Product and category buttons continue to the corresponding page on cnfanssp.com." }, { title: "What we do not claim", text: "A working link is not proof of stock, quality, authenticity or delivery. Prices and availability can change. We identify official platform statements, third-party review signals and our own checking advice separately, and we show the date of each material check." }, { title: "Our editorial lane", text: "This site concentrates on product comparison, shortlist building and decision matrices. Spreadsheet, QC, shipping and returns pages remain supporting tools rather than claims that Hacoo VIP is an official catalogue or service." }] },
    contact: { eyebrow: "CONTACT", title: "Contact the independent editor", intro: "Report a broken link, mismatched product card, factual error or unclear source. Please identify the page URL and the detail that should be checked.", sections: [{ title: "Editorial and correction requests", text: "Use the WhatsApp contact button on this site and include the Hacoo VIP page, the current destination page, what changed and the date you saw it. Screenshots are helpful when a product image, title, option or regional result differs." }, { title: "Order support", text: "Hacoo VIP cannot access Hacoo accounts, orders, payments, tracking or refunds. For an account or order problem, use the current support route inside the Hacoo app or the official Hacoo website. Never send passwords or full payment details to this site." }] },
    "editorial-policy": { eyebrow: "EDITORIAL STANDARD", title: "Editorial policy", intro: "Our pages are written for a reader making a real decision, not to display internal keyword instructions or manufacture certainty.", sections: [{ title: "Separation of evidence", text: "Official Hacoo statements are described as platform statements and linked when they support a material fact. App-store or review-platform observations are labelled as third-party signals. Product-card checks and decision advice are our independent editorial work." }, { title: "Human review before publication", text: "We check the corresponding official platform page again before advancing an article cycle. We remove internal keyword, target-length and drafting notes from the public article. Search terms may guide topic selection, but they do not replace a useful answer." }, { title: "Commercial links", text: "Category and product links can lead to cnfanssp.com and may contain referral parameters. That relationship does not change our obligation to show uncertainty, identify the destination and avoid invented totals or official-sounding claims." }] },
    "sources-policy": { eyebrow: "SOURCE STANDARD", title: "Sources policy", intro: "Every material policy, timing or rating statement should be traceable to a named, clickable source and a check date.", sections: [{ title: "Source order", text: "We prefer Hacoo’s current official pages and Help Center for platform policy. For app ratings we use the relevant Google Play or Apple storefront. Review sites can show recurring customer themes, but they are not treated as official policy or proof about one product." }, { title: "Conflicts and changing pages", text: "When official pages publish different delivery ranges, we retain the difference instead of selecting the most attractive number. If a page changes by country, device or date, we state that limitation and ask the reader to verify the live interface." }, { title: "Images", text: "Product images are used to help the reader match a card to its destination. An image does not verify materials, condition or authenticity. We add a descriptive caption when an image materially supports the checking method." }] },
    "corrections-policy": { eyebrow: "CORRECTIONS", title: "Corrections policy", intro: "A correction should make the current page more accurate without hiding what was checked or silently changing an unrelated section.", sections: [{ title: "What to report", text: "Send the exact Hacoo VIP URL, the affected sentence or card, the supporting source and the date observed. For product mismatches, include the destination URL and identify whether the image, title, option, price, category or availability changed." }, { title: "How we respond", text: "We reproduce the issue, check the most authoritative available source and correct the page when the evidence supports a change. Material updates receive an accurate last-modified date; unrelated sitemap dates are not refreshed." }, { title: "What may be removed", text: "A product card may be removed only when the destination cannot be verified or the relationship between the card and destination is no longer reliable. Existing modules and language versions are not reduced simply to make a page look shorter." }] },
    privacy: { eyebrow: "PRIVACY", title: "Privacy notice", intro: "Hacoo VIP is a public informational site. It does not provide Hacoo account login, checkout or order-management forms.", sections: [{ title: "Technical data", text: "The hosting and security provider may process normal request data such as IP address, browser information, requested URL and time to deliver and protect the site. We do not ask visitors to submit passwords or payment details." }, { title: "External destinations", text: "Search, catalogue, product and WhatsApp actions open external services. Those services process data under their own policies. Review the destination and its privacy terms before sending information or completing a transaction." }, { title: "Contact data", text: "If you contact the editor, send only the information needed to reproduce the editorial issue. Do not include account credentials, full payment information or unnecessary personal documents." }] },
    terms: { eyebrow: "SITE TERMS", title: "Terms of use", intro: "By using Hacoo VIP, you acknowledge that it is an independent research and comparison guide, not Hacoo and not the seller or payment provider for linked products.", sections: [{ title: "Informational use", text: "Prices, currency conversions, delivery ranges, ratings and listing status are time-stamped planning information rather than guarantees. The live destination, selected option, checkout and order-specific terms remain authoritative for a purchase." }, { title: "Outbound links", text: "Links can open cnfanssp.com, Hacoo, app stores, review sites or WhatsApp. Availability and content on those services are outside Hacoo VIP’s control. Referral parameters may be present on catalogue links." }, { title: "Responsible use", text: "Use the comparison and evidence checklists to make your own decision. Do not rely on this site for legal, financial or account-specific advice, and do not infer product authenticity or quality from inclusion in a shortlist." }] },
  },
  de: {
    about: { eyebrow: "UNABHÄNGIGE RECHERCHE", title: "Über Hacoo VIP", intro: "Hacoo VIP ist ein unabhängiger Vergleichs- und Entscheidungsratgeber. Die Website ist weder Hacoo noch dessen Vertreter oder Verkäufer.", sections: [{ title: "Unser Zweck", text: "Wir ordnen aktuelle Katalogziele in Auswahllisten und vergleichen Bild, Titel, Option, Quellpreis, Maße, Angebotsstatus, Lieferzeitraum und Retourenbelege. Produkt- und Kategorietasten führen zur passenden Seite auf cnfanssp.com." }, { title: "Keine Garantie", text: "Ein funktionierender Link belegt weder Bestand, Qualität, Echtheit noch Lieferung. Wir trennen offizielle Angaben, Drittanbieter-Signale und eigene Prüfratschläge und nennen das Prüfdatum." }, { title: "Redaktioneller Schwerpunkt", text: "Hacoo VIP konzentriert sich auf Produktvergleich, Auswahllisten und Entscheidungskriterien. Tabelle, QC, Versand und Retouren bleiben unterstützende Werkzeuge." }] },
    contact: { eyebrow: "KONTAKT", title: "Kontakt zur unabhängigen Redaktion", intro: "Melde defekte Links, unpassende Produktkarten, Sachfehler oder unklare Quellen mit der genauen Seiten-URL.", sections: [{ title: "Korrekturen", text: "Nutze die WhatsApp-Schaltfläche und sende Hacoo-VIP-Seite, aktuelle Zielseite, Änderung und Beobachtungsdatum. Screenshots helfen bei Bild-, Titel-, Options- oder Regionsabweichungen." }, { title: "Bestellhilfe", text: "Hacoo VIP hat keinen Zugriff auf Hacoo-Konten, Bestellungen, Zahlungen oder Erstattungen. Nutze dafür den aktuellen offiziellen Supportweg und sende uns niemals Passwörter oder Zahlungsdaten." }] },
    "editorial-policy": { eyebrow: "REDAKTIONSSTANDARD", title: "Redaktionsrichtlinie", intro: "Unsere Texte helfen bei einer echten Entscheidung und zeigen keine internen Keyword- oder Längenvorgaben.", sections: [{ title: "Belege trennen", text: "Offizielle Hacoo-Angaben werden verlinkt; App-Store- und Bewertungsdaten bleiben Drittanbieter-Signale. Produktprüfungen und Entscheidungshilfen sind unsere unabhängige Redaktion." }, { title: "Prüfung vor Veröffentlichung", text: "Vor jeder neuen Artikelphase prüfen wir die passende offizielle Plattformseite erneut. Suchbegriffe steuern die Themenwahl, ersetzen aber keine nützliche Antwort." }, { title: "Kommerzielle Links", text: "Links zu cnfanssp.com können Referral-Parameter enthalten. Deshalb bleiben Unsicherheiten, Ziel und unabhängiger Status sichtbar." }] },
    "sources-policy": { eyebrow: "QUELLENSTANDARD", title: "Quellenrichtlinie", intro: "Wesentliche Richtlinien-, Zeit- und Bewertungsangaben müssen zu einer benannten, anklickbaren Quelle mit Prüfdatum führen.", sections: [{ title: "Quellenfolge", text: "Für Richtlinien bevorzugen wir aktuelle offizielle Hacoo-Seiten; für App-Bewertungen den jeweiligen Store. Bewertungsportale zeigen Themen, aber keine offizielle Regel oder Produktgarantie." }, { title: "Widersprüche", text: "Unterschiedliche offizielle Lieferzeiträume bleiben sichtbar. Länder-, Geräte- und Datumsunterschiede werden gekennzeichnet." }, { title: "Bilder", text: "Bilder helfen beim Abgleich von Karte und Zielseite, belegen aber weder Material, Zustand noch Echtheit." }] },
    "corrections-policy": { eyebrow: "KORREKTUREN", title: "Korrekturrichtlinie", intro: "Korrekturen verbessern die betroffene Seite, ohne Prüfverlauf oder andere Bereiche still zu verändern.", sections: [{ title: "Meldung", text: "Sende URL, betroffene Stelle, Quelle und Datum. Bei Produkten nenne Bild, Titel, Option, Preis, Kategorie oder Verfügbarkeit." }, { title: "Bearbeitung", text: "Wir reproduzieren den Fehler, prüfen die beste Quelle und korrigieren bei ausreichendem Beleg. Nur wesentlich geänderte URLs erhalten ein neues lastmod-Datum." }, { title: "Entfernung", text: "Eine Karte wird nur entfernt, wenn Ziel oder Zuordnung nicht mehr verifizierbar sind. Module und Sprachversionen werden nicht zum Kürzen entfernt." }] },
    privacy: { eyebrow: "DATENSCHUTZ", title: "Datenschutzhinweis", intro: "Hacoo VIP ist eine öffentliche Informationsseite ohne Hacoo-Login, Checkout oder Bestellverwaltung.", sections: [{ title: "Technische Daten", text: "Hosting und Sicherheit können übliche Anfragedaten wie IP, Browser, URL und Zeit verarbeiten. Wir fragen nicht nach Passwörtern oder Zahlungsdaten." }, { title: "Externe Ziele", text: "Suche, Katalog, Produkte und WhatsApp öffnen externe Dienste mit eigenen Datenschutzregeln." }, { title: "Kontakt", text: "Sende nur Daten, die zur Prüfung eines Redaktionsfehlers nötig sind, keine Zugangsdaten oder unnötigen Dokumente." }] },
    terms: { eyebrow: "NUTZUNGSBEDINGUNGEN", title: "Bedingungen", intro: "Hacoo VIP ist ein unabhängiger Ratgeber und weder Hacoo noch Verkäufer oder Zahlungsanbieter.", sections: [{ title: "Information", text: "Preise, Umrechnung, Lieferzeiten, Bewertungen und Angebotsstatus sind datierte Planungswerte ohne Garantie. Maßgeblich bleibt die Live-Zielseite." }, { title: "Externe Links", text: "Links können cnfanssp.com, Hacoo, App-Stores, Bewertungsseiten oder WhatsApp öffnen und Referral-Parameter enthalten." }, { title: "Eigenverantwortung", text: "Nutze Vergleiche und Checklisten für deine Entscheidung; die Aufnahme in eine Liste beweist weder Echtheit noch Qualität." }] },
  },
  es: {
    about: { eyebrow: "INVESTIGACIÓN INDEPENDIENTE", title: "Acerca de Hacoo VIP", intro: "Hacoo VIP es una guía independiente de comparación y decisión. No es Hacoo, no lo representa y no vende los productos mostrados.", sections: [{ title: "Qué hacemos", text: "Organizamos destinos activos en listas útiles y comparamos imagen, título, opción, precio original, medidas, estado, entrega y pruebas de devolución. Los botones llevan a la página correspondiente de cnfanssp.com." }, { title: "Qué no garantizamos", text: "Un enlace activo no demuestra stock, calidad, autenticidad ni entrega. Separamos hechos oficiales, señales de terceros y consejos editoriales e indicamos la fecha de revisión." }, { title: "Enfoque editorial", text: "El sitio se centra en comparación, listas y criterios de decisión. Hoja, QC, envío y devoluciones son herramientas de apoyo." }] },
    contact: { eyebrow: "CONTACTO", title: "Contacta con el editor independiente", intro: "Informa de enlaces rotos, fichas que no coinciden, errores o fuentes poco claras indicando la URL exacta.", sections: [{ title: "Correcciones", text: "Usa WhatsApp e incluye la página de Hacoo VIP, el destino actual, el cambio y la fecha. Las capturas ayudan con diferencias de imagen, título, opción o región." }, { title: "Ayuda con pedidos", text: "Hacoo VIP no accede a cuentas, pedidos, pagos o reembolsos. Usa el soporte oficial actual y no nos envíes contraseñas ni datos completos de pago." }] },
    "editorial-policy": { eyebrow: "NORMA EDITORIAL", title: "Política editorial", intro: "Los textos ayudan a tomar decisiones reales y no muestran instrucciones internas de palabras clave o extensión.", sections: [{ title: "Separación de pruebas", text: "Enlazamos las declaraciones oficiales; tiendas de aplicaciones y reseñas son señales de terceros. Las comprobaciones y consejos son trabajo editorial independiente." }, { title: "Revisión humana", text: "Antes de avanzar un ciclo volvemos a comprobar la página oficial correspondiente. Las búsquedas orientan el tema, pero no sustituyen una respuesta útil." }, { title: "Enlaces comerciales", text: "Los enlaces a cnfanssp.com pueden llevar parámetros de referencia; mantenemos visibles el destino, los límites y la independencia." }] },
    "sources-policy": { eyebrow: "NORMA DE FUENTES", title: "Política de fuentes", intro: "Cada dato importante sobre políticas, plazos o valoraciones debe llevar a una fuente identificada, accesible y fechada.", sections: [{ title: "Prioridad", text: "Preferimos páginas oficiales de Hacoo para políticas y las tiendas correspondientes para valoraciones. Las webs de reseñas muestran temas, no normas oficiales ni pruebas de un producto." }, { title: "Diferencias", text: "Conservamos rangos oficiales diferentes y señalamos cambios por país, dispositivo o fecha." }, { title: "Imágenes", text: "Las imágenes ayudan a relacionar ficha y destino, pero no prueban material, estado o autenticidad." }] },
    "corrections-policy": { eyebrow: "CORRECCIONES", title: "Política de correcciones", intro: "Una corrección mejora la página afectada sin ocultar la revisión ni cambiar secciones no relacionadas.", sections: [{ title: "Qué enviar", text: "Envía URL, detalle, fuente y fecha. Para productos, indica imagen, título, opción, precio, categoría o disponibilidad." }, { title: "Proceso", text: "Reproducimos el problema, comprobamos la mejor fuente y corregimos con pruebas. Solo las URL modificadas de forma relevante cambian lastmod." }, { title: "Eliminación", text: "Solo retiramos una ficha cuando no puede verificarse. No reducimos módulos o idiomas para acortar la página." }] },
    privacy: { eyebrow: "PRIVACIDAD", title: "Aviso de privacidad", intro: "Hacoo VIP es un sitio informativo público sin acceso a Hacoo, pago o gestión de pedidos.", sections: [{ title: "Datos técnicos", text: "El alojamiento y la seguridad pueden procesar IP, navegador, URL y hora. No solicitamos contraseñas ni datos de pago." }, { title: "Servicios externos", text: "Búsqueda, catálogo, productos y WhatsApp abren servicios externos con sus propias políticas." }, { title: "Contacto", text: "Envía solo lo necesario para reproducir un error editorial, nunca credenciales o documentos innecesarios." }] },
    terms: { eyebrow: "CONDICIONES", title: "Condiciones de uso", intro: "Hacoo VIP es una guía independiente y no es Hacoo, vendedor ni proveedor de pago.", sections: [{ title: "Información", text: "Precios, cambios, entregas, valoraciones y estado son referencias fechadas, no garantías. La página activa es la autoridad final." }, { title: "Enlaces", text: "Los enlaces pueden abrir cnfanssp.com, Hacoo, tiendas, reseñas o WhatsApp y contener parámetros de referencia." }, { title: "Uso responsable", text: "Usa comparaciones y listas para tu decisión; aparecer en una selección no prueba autenticidad ni calidad." }] },
  },
  fr: {
    about: { eyebrow: "RECHERCHE INDÉPENDANTE", title: "À propos de Hacoo VIP", intro: "Hacoo VIP est un guide indépendant de comparaison et de décision. Il ne représente pas Hacoo et ne vend pas les produits affichés.", sections: [{ title: "Notre travail", text: "Nous organisons des destinations actives en listes utiles et comparons image, titre, option, prix source, mesures, statut, livraison et preuves de retour. Les boutons mènent à la page correspondante de cnfanssp.com." }, { title: "Nos limites", text: "Un lien actif ne prouve ni stock, qualité, authenticité ou livraison. Nous séparons faits officiels, signaux tiers et conseils éditoriaux avec une date de vérification." }, { title: "Axe éditorial", text: "Le site se concentre sur la comparaison, les listes et les critères de décision. Tableur, QC, livraison et retours restent des outils d’appui." }] },
    contact: { eyebrow: "CONTACT", title: "Contacter l’éditeur indépendant", intro: "Signalez un lien cassé, une fiche incohérente, une erreur ou une source imprécise avec l’URL exacte.", sections: [{ title: "Corrections", text: "Utilisez WhatsApp et joignez page Hacoo VIP, destination actuelle, changement et date. Les captures aident pour image, titre, option ou région." }, { title: "Aide aux commandes", text: "Hacoo VIP n’accède pas aux comptes, commandes, paiements ou remboursements. Utilisez l’assistance officielle et ne nous envoyez jamais de mot de passe ou de données de paiement." }] },
    "editorial-policy": { eyebrow: "NORME ÉDITORIALE", title: "Politique éditoriale", intro: "Nos textes répondent à une décision réelle et n’affichent pas d’instructions internes de mot-clé ou de longueur.", sections: [{ title: "Séparer les preuves", text: "Les déclarations officielles sont liées; stores et avis restent des signaux tiers. Vérifications et conseils sont notre travail indépendant." }, { title: "Relecture humaine", text: "Avant chaque nouveau cycle, nous revérifions la page officielle concernée. Les recherches orientent le sujet sans remplacer une réponse utile." }, { title: "Liens commerciaux", text: "Les liens cnfanssp.com peuvent contenir des paramètres de recommandation; destination, limites et indépendance restent visibles." }] },
    "sources-policy": { eyebrow: "NORME DES SOURCES", title: "Politique des sources", intro: "Tout fait important de politique, délai ou note doit mener à une source nommée, cliquable et datée.", sections: [{ title: "Priorité", text: "Nous privilégions Hacoo pour les politiques et les stores concernés pour les notes. Les plateformes d’avis montrent des thèmes, pas une règle officielle ou la preuve d’un produit." }, { title: "Écarts", text: "Nous conservons les plages officielles différentes et signalons les variations par pays, appareil ou date." }, { title: "Images", text: "Les images relient carte et destination sans prouver matière, état ou authenticité." }] },
    "corrections-policy": { eyebrow: "CORRECTIONS", title: "Politique de correction", intro: "Une correction améliore la page concernée sans masquer le contrôle ni modifier des sections sans rapport.", sections: [{ title: "Signalement", text: "Envoyez URL, passage, source et date. Pour un produit, précisez image, titre, option, prix, catégorie ou disponibilité." }, { title: "Traitement", text: "Nous reproduisons, vérifions la meilleure source et corrigeons avec preuve. Seules les URL réellement modifiées changent de lastmod." }, { title: "Retrait", text: "Une fiche n’est retirée que si elle n’est plus vérifiable. Modules et langues ne sont pas supprimés pour raccourcir." }] },
    privacy: { eyebrow: "CONFIDENTIALITÉ", title: "Avis de confidentialité", intro: "Hacoo VIP est un site public d’information sans connexion Hacoo, paiement ou gestion de commande.", sections: [{ title: "Données techniques", text: "Hébergement et sécurité peuvent traiter IP, navigateur, URL et heure. Nous ne demandons ni mot de passe ni paiement." }, { title: "Services externes", text: "Recherche, catalogue, produits et WhatsApp ouvrent des services soumis à leurs propres politiques." }, { title: "Contact", text: "N’envoyez que le nécessaire pour reproduire une erreur éditoriale, jamais d’identifiants ou de documents inutiles." }] },
    terms: { eyebrow: "CONDITIONS", title: "Conditions d’utilisation", intro: "Hacoo VIP est un guide indépendant et n’est ni Hacoo, ni vendeur, ni prestataire de paiement.", sections: [{ title: "Information", text: "Prix, conversion, livraison, notes et statut sont des repères datés sans garantie. La destination active reste déterminante." }, { title: "Liens externes", text: "Les liens peuvent ouvrir cnfanssp.com, Hacoo, stores, avis ou WhatsApp et contenir des paramètres de recommandation." }, { title: "Usage responsable", text: "Utilisez comparaisons et listes pour décider; une sélection ne prouve ni authenticité ni qualité." }] },
  },
  it: {
    about: { eyebrow: "RICERCA INDIPENDENTE", title: "Informazioni su Hacoo VIP", intro: "Hacoo VIP è una guida indipendente al confronto e alla decisione. Non è Hacoo, non lo rappresenta e non vende i prodotti mostrati.", sections: [{ title: "Cosa facciamo", text: "Organizziamo destinazioni attive in liste pratiche e confrontiamo immagine, titolo, opzione, prezzo fonte, misure, stato, consegna e prove di reso. I pulsanti aprono la pagina corrispondente su cnfanssp.com." }, { title: "Cosa non garantiamo", text: "Un link attivo non prova disponibilità, qualità, autenticità o consegna. Separiamo fatti ufficiali, segnali terzi e consigli editoriali con data di controllo." }, { title: "Focus editoriale", text: "Il sito si concentra su confronto, liste e criteri decisionali. Foglio, QC, spedizione e resi restano strumenti di supporto." }] },
    contact: { eyebrow: "CONTATTI", title: "Contatta l’editor indipendente", intro: "Segnala link interrotti, schede non corrispondenti, errori o fonti poco chiare indicando l’URL esatto.", sections: [{ title: "Correzioni", text: "Usa WhatsApp e includi pagina Hacoo VIP, destinazione attuale, modifica e data. Le schermate aiutano per immagine, titolo, opzione o regione." }, { title: "Assistenza ordini", text: "Hacoo VIP non accede ad account, ordini, pagamenti o rimborsi. Usa il supporto ufficiale e non inviarci password o dati di pagamento." }] },
    "editorial-policy": { eyebrow: "STANDARD EDITORIALE", title: "Politica editoriale", intro: "I testi aiutano una decisione reale e non mostrano istruzioni interne su parole chiave o lunghezza.", sections: [{ title: "Separare le prove", text: "Le dichiarazioni ufficiali sono collegate; store e recensioni restano segnali terzi. Controlli e consigli sono lavoro editoriale indipendente." }, { title: "Revisione umana", text: "Prima di avanzare un ciclo ricontrolliamo la pagina ufficiale pertinente. Le ricerche guidano il tema ma non sostituiscono una risposta utile." }, { title: "Link commerciali", text: "I link cnfanssp.com possono includere parametri referral; destinazione, limiti e indipendenza restano visibili." }] },
    "sources-policy": { eyebrow: "STANDARD DELLE FONTI", title: "Politica delle fonti", intro: "Ogni dato importante su regole, tempi o valutazioni deve portare a una fonte nominata, cliccabile e datata.", sections: [{ title: "Priorità", text: "Preferiamo Hacoo per le politiche e gli store pertinenti per le valutazioni. I siti di recensioni mostrano temi, non regole ufficiali o prove su un prodotto." }, { title: "Differenze", text: "Manteniamo intervalli ufficiali diversi e segnaliamo variazioni per paese, dispositivo o data." }, { title: "Immagini", text: "Le immagini collegano scheda e destinazione ma non provano materiale, condizione o autenticità." }] },
    "corrections-policy": { eyebrow: "CORREZIONI", title: "Politica delle correzioni", intro: "Una correzione migliora la pagina interessata senza nascondere il controllo o cambiare sezioni non correlate.", sections: [{ title: "Segnalazione", text: "Invia URL, dettaglio, fonte e data. Per i prodotti specifica immagine, titolo, opzione, prezzo, categoria o disponibilità." }, { title: "Procedura", text: "Riproduciamo il problema, controlliamo la fonte migliore e correggiamo con prove. Solo gli URL modificati davvero cambiano lastmod." }, { title: "Rimozione", text: "Una scheda viene rimossa solo se non è più verificabile. Moduli e lingue non vengono ridotti per accorciare." }] },
    privacy: { eyebrow: "PRIVACY", title: "Informativa sulla privacy", intro: "Hacoo VIP è un sito informativo pubblico senza login Hacoo, pagamento o gestione ordini.", sections: [{ title: "Dati tecnici", text: "Hosting e sicurezza possono trattare IP, browser, URL e ora. Non chiediamo password o dati di pagamento." }, { title: "Servizi esterni", text: "Ricerca, catalogo, prodotti e WhatsApp aprono servizi con politiche proprie." }, { title: "Contatto", text: "Invia solo quanto serve a riprodurre un errore editoriale, mai credenziali o documenti non necessari." }] },
    terms: { eyebrow: "TERMINI", title: "Termini di utilizzo", intro: "Hacoo VIP è una guida indipendente e non è Hacoo, venditore o fornitore di pagamenti.", sections: [{ title: "Informazioni", text: "Prezzi, conversioni, consegne, valutazioni e stato sono riferimenti datati, non garanzie. Fa fede la destinazione attiva." }, { title: "Link esterni", text: "I link possono aprire cnfanssp.com, Hacoo, store, recensioni o WhatsApp e includere parametri referral." }, { title: "Uso responsabile", text: "Usa confronti e liste per decidere; l’inclusione non prova autenticità o qualità." }] },
  },
};
