import { CategoryCard } from "@/components/Cards";
import { categories, categoryResearch } from "../data";
import { languageAlternates } from "../i18n";
import { createPageMetadata } from "../seo";

export const metadata = createPageMetadata({ title: "Hacoo Finds Categories & Verified Product Links", description: "Browse focused Hacoo finds routes for shoes, headwear, hoodies, T-shirts, jackets, pants, accessories and electronics, with current title-and-image-matched references.", path: "/categories", alternates: languageAlternates("/categories", "en") });

export default function CategoriesPage() {
  return <><section className="page-hero simple-hero"><div className="wrap"><span className="section-label">Category directory</span><h1>Find the closest<br/><em>product route.</em></h1><p>Eight focused starting points, each with a purpose-built checklist and a direct route into current destination catalog information.</p></div></section><section className="section wrap"><div className="category-grid">{categories.map((c,i)=><CategoryCard category={c} index={i} key={c.slug}/>)}</div></section>
    <section className="soft-section"><div className="wrap story-grid"><div><span className="section-label">Choose by evidence</span><h2>Different products need different checks.</h2></div><div><p className="large-copy">A category route is more useful than one endless spreadsheet when it makes the first comparison point obvious.</p><p>Footwear begins with internal length and shape. Clothing begins with flat garment measurements. Accessories need reliable dimensions, while electronics require an exact model and compatibility check. Every route leads to current external catalog information, but Hacoos remains an independent research guide and does not process transactions.</p><p>Use the directory to narrow the product type, read the relevant checklist, then verify the selected option on the destination page. The catalog routes below were checked on August 26, 2026; individual products, prices and stock can change.</p></div></div></section>
    <section className="section wrap"><div className="section-heading"><div><span className="section-label">At a glance</span><h2>Start with the right reference.</h2></div><p>This table shows the first useful comparison and the detail that still needs a live-page check.</p></div><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Category</th><th>Compare first</th><th>Verify live</th></tr></thead><tbody>{categories.map((category)=><tr key={category.slug}><th><a href={`/categories/${category.slug}`}>{category.name}</a></th><td>{categoryResearch[category.slug].primaryCheck}</td><td>{categoryResearch[category.slug].liveCheck}</td></tr>)}</tbody></table></div></section></>;
}
