import type { Metadata } from "next";
import Link from "next/link";
import { EditorialPage } from "../../components/EditorialPage";

export const metadata: Metadata = { title: "How to Read QC Photos: Complete Checklist | FindQCs", description: "A practical QC photo checklist covering product match, measurements, shape, stitching, materials, labels, color and visible defects.", alternates: { canonical: "/guides/qc-photo-checklist" } };

const faq = [
  ["How many QC photos are enough?", "There is no universal number. You need enough angles to see the front, back, sides, key details, size label and any area where a defect is likely."],
  ["Can warehouse lighting change color?", "Yes. White balance, exposure and nearby surfaces can all affect perceived color. Compare several photos and use a neutral reference where possible."],
  ["Should I reject an item because of one uneven photo?", "Not automatically. First determine whether the problem is the item, its position on the table, the camera angle or lens distortion. Ask for a clearer angle when the distinction matters."],
];

export default function Checklist(){
  const schema = { "@context":"https://schema.org", "@type":"Article", headline:"How to Read QC Photos Before You Buy", description:"A practical, repeatable QC photo inspection checklist.", author:{"@type":"Organization",name:"FindQCs"}, mainEntityOfPage:"https://findqcs.net/guides/qc-photo-checklist" };
  const faqSchema = { "@context":"https://schema.org", "@type":"FAQPage", mainEntity:faq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}})) };
  return <EditorialPage eyebrow="QC GUIDE / 12 MIN READ" title="How to read QC photos before you buy." intro="A QC photo is evidence, not a verdict. This checklist helps you separate visible facts from assumptions and inspect the same details in the same order every time.">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>
    <div className="article-layout"><aside className="toc"><strong>ON THIS PAGE</strong><a href="#match">1. Match the order</a><a href="#overview">2. Start wide</a><a href="#details">3. Inspect details</a><a href="#measure">4. Measure fit</a><a href="#color">5. Judge color</a><a href="#decision">6. Make a decision</a></aside>
    <div className="prose">
      <p className="lead">The most common QC mistake is zooming in on a logo before confirming that the photographed item is even the correct model, color and size. A reliable review moves from basic identity to overall construction and only then to small details.</p>
      <h2 id="match">1. Match the photographed item to the order</h2>
      <p>Begin with information that should be unambiguous. Compare the order or listing with the size label, color, model details and visible accessories. Check whether the requested variation matches the photographed variation. If a seller offers several materials or batches under one link, confirm which one reached the warehouse.</p>
      <p>Do not rely on the product title alone. Marketplace titles may contain several colors, models or promotional terms. The selected option and the physical label are usually more useful. For footwear, look for the size tag on the box and the item. For clothing, inspect the neck, waist or care label where available. A correct label does not prove that the item itself is correct, but a wrong label is an immediate reason to stop.</p>
      <div className="check-block"><strong>Identity check</strong><ul><li>Correct link or product ID</li><li>Correct color and variation</li><li>Correct ordered size</li><li>Expected quantity and accessories</li><li>Matching left and right items where applicable</li></ul></div>
      <h2 id="overview">2. Start with the overall shape</h2>
      <p>Before inspecting stitching, look at the product from a normal viewing distance. Ask whether the silhouette, proportions and construction appear internally consistent. For a garment, compare the shoulders, sleeve lengths, hem and side seams. For shoes, compare the two toe boxes, heel heights, panel lines and sole shape. For a bag, compare the left and right sides, handles, flap and hardware placement.</p>
      <p>Symmetry matters, but the photograph itself can create apparent asymmetry. An item may be folded, loosely laced or placed at an angle. Wide-angle phone cameras make objects near the edge of the frame look stretched. Use a straight, centered photograph for proportion checks whenever possible. If the only useful image is angled, treat shape conclusions as provisional.</p>
      <h2 id="details">3. Inspect construction and visible details</h2>
      <p>Now move closer. Follow a fixed path so you do not overlook an area: front, right side, back, left side, top and bottom. Inspect seams for skipped stitches, loose thread, large changes in stitch spacing and puckering. Check whether panels meet cleanly and whether printed or embroidered elements are reasonably aligned with nearby seams.</p>
      <p>Material appearance is more difficult. A photo may show texture, grain, weave or thickness, but it cannot reliably establish fiber composition, coating durability or how the material feels. Use material observations as comparisons with other photographs, not as laboratory proof. A glossy surface under direct warehouse light may look different under normal indoor light.</p>
      <p>Labels and packaging are often overvalued. They can help confirm model, size and care information, but they should not override obvious problems with the item itself. Packaging damage may be unimportant when the product is unaffected; conversely, perfect packaging does not compensate for incorrect measurements or construction.</p>
      <div className="check-block"><strong>Visible defect scan</strong><ul><li>Stains, marks, scratches or glue residue</li><li>Tears, holes, dents or damaged edges</li><li>Loose, missing or misaligned hardware</li><li>Uneven prints, embroidery or panel placement</li><li>Broken zippers, snaps or closures visible in the images</li></ul></div>
      <h2 id="measure">4. Use measurements instead of size labels</h2>
      <p>A letter size is not a measurement. Two items marked “M” can have very different chest width, length or sleeve length. Translate the warehouse measurement into the same method you use at home. If the photo shows a garment laid flat, compare it with a similar garment laid flat—not with a body circumference or a stretched measurement.</p>
      <p>Check where the ruler begins and ends. A tape that is curved, floating above the fabric or not aligned with the edge can produce a misleading number. For shoes, confirm whether the measurement is the insole length, outsole length or stated label size. These numbers are not interchangeable. Allow for small measurement variation, but treat a large difference from the selected size as a factual mismatch.</p>
      <h2 id="color">5. Judge color with caution</h2>
      <p>Warehouse lighting, camera white balance, exposure and screen settings can all change color. Look for a neutral object in the frame, such as a grey card, white background or ruler. If the supposedly white background looks blue or yellow, the product color is probably shifted in the same direction.</p>
      <p>Compare several images taken from different angles. If the color remains consistently different from the listing after accounting for lighting, record it as a possible mismatch. If one photograph looks wrong while the others look reasonable, the photograph is the more likely source of the difference. Requesting one additional image in neutral light can be more useful than arguing from a single compressed screenshot.</p>
      <h2 id="decision">6. Turn observations into a decision</h2>
      <p>Separate findings into three groups: confirmed facts, likely issues and unknowns. “The size label shows 42 instead of 43” is a confirmed fact. “The left shoe may be slightly taller” is a likely issue that needs a straighter photo. “The material will last for years” is unknown because the photos cannot answer it.</p>
      <p>Then decide which facts matter to you. A loose thread may be easy to trim; a wrong size, damaged closure or large measurement error is harder to correct. The purpose of QC is not to find a perfect object under extreme magnification. It is to identify meaningful differences before the next step becomes more expensive or difficult.</p>
      <h2>Final 60-second checklist</h2>
      <h2>Keep a simple evidence log</h2><p>A short written record makes repeated QC review more accurate. Save the item ID, selected variation, date, the photos reviewed and the specific observation that affected your decision. Use neutral descriptions such as “right sleeve measures approximately 2 cm shorter in the supplied photo” rather than “bad quality.” Neutral language can be checked again when a clearer image appears.</p><p>The log also prevents hindsight from changing the story. If the item later arrives and looks different under normal light, you can compare the outcome with what the warehouse images actually showed. Over several purchases, this teaches you which photo conditions, product categories and measurement differences matter most to you. It is more useful than copying another buyer’s tolerance because QC decisions are partly personal.</p>
      <ol><li>Confirm product, color, size and quantity.</li><li>Compare the overall silhouette from a centered angle.</li><li>Check symmetry and major construction lines.</li><li>Inspect seams, print, embroidery, hardware and edges.</li><li>Look for stains, damage and missing parts.</li><li>Read measurement photos carefully.</li><li>Compare color across more than one image.</li><li>Separate facts from assumptions.</li><li>Request another photo when the decision depends on an unclear angle.</li><li>Open the source listing again before making the final choice.</li></ol>
      <div className="article-faq"><h2>Frequently asked questions</h2>{faq.map(([q,a])=><div key={q}><h3>{q}</h3><p>{a}</p></div>)}</div>
      <Link className="article-cta" href="/categories">Browse product categories <span>→</span></Link>
    </div></div>
  </EditorialPage>;
}
