import type { Locale, TrustRouteName } from "./site-data";

export type TrustPage = {
  title: string;
  description: string;
  kicker: string;
  intro: string;
  sections: { heading: string; paragraphs: string[]; bullets?: string[] }[];
};

const en: Record<TrustRouteName, TrustPage> = {
  about: {
    title: "About HacooVIP",
    description: "Who publishes HacooVIP, what this independent research site covers and where its responsibility ends.",
    kicker: "INDEPENDENT PUBLISHER",
    intro: "HacooVIP is an independent product-research publisher. It is not Hacoo, does not represent Hacoo and does not process accounts, orders, payments, returns or support requests.",
    sections: [
      { heading: "What we publish", paragraphs: ["We help readers define product requirements before browsing, understand dated public information about the Hacoo app and follow clearly labelled routes to a separate live product catalogue. Independent product indexes are described as independent; they are never presented as an official Hacoo spreadsheet."], bullets: ["Product-research briefs and checklists", "Dated app and policy facts", "Clearly labelled independent product routes"] },
      { heading: "Where our role ends", paragraphs: ["We cannot see a reader's Hacoo account, order record, payment or private messages. Platform-specific actions belong in the official app or its current support route. A working product link is not a quality, authenticity, price, stock or delivery guarantee."] },
    ],
  },
  "editorial-policy": {
    title: "Editorial Policy",
    description: "How HacooVIP separates official facts, public reports, independent analysis and product-route guidance.",
    kicker: "PUBLISHING STANDARD",
    intro: "Every page should make it clear what is an official statement, what comes from a dated third-party record and what is our own practical interpretation.",
    sections: [
      { heading: "Evidence before conclusions", paragraphs: ["Platform identity, features, policies and changing figures are checked against current primary sources before publication. Public reviews are treated as individual reports, not universal outcomes. Unknown details remain unknown rather than being filled with assumptions."], bullets: ["One clear reader question per guide", "Dates and regions attached to changing claims", "No invented orders, quotes, ratings or first-person experience"] },
      { heading: "Commercial boundaries", paragraphs: ["Product and category routes may lead to the approved live catalogue. Their presence explains where a reader can continue checking a product; it is not proof that an item is suitable. Editorial copy does not promise authenticity, seller reliability, delivery performance or a guaranteed result."] },
    ],
  },
  sources: {
    title: "Sources & Fact-Checking",
    description: "The source hierarchy, dating rules and verification method used by HacooVIP research guides.",
    kicker: "SOURCE METHOD",
    intro: "Current official pages are the starting point for platform facts. App-store records and traceable public reports can add context when their date, region and limitations are visible.",
    sections: [
      { heading: "Source order", paragraphs: ["For app identity and policies, we prefer Hacoo's current public pages and the live Apple or Google store listing. For customer-experience analysis, we use multiple accessible reports and separate their claims from official wording."], bullets: ["Official platform and policy pages", "Current app-store records", "Dated, traceable public reports", "Independent editorial interpretation"] },
      { heading: "Changing information", paragraphs: ["Ratings, review counts, app versions, policies, prices, stock and delivery options can change. We attach a check date when a changing figure matters and direct readers to verify the current source before acting. Old pages are corrected rather than silently treated as timeless facts."] },
    ],
  },
  corrections: {
    title: "Corrections Policy",
    description: "How HacooVIP identifies, records and fixes factual, translation and product-route errors.",
    kicker: "CORRECTION STANDARD",
    intro: "A correction should fix the exact claim without hiding what changed or refreshing unrelated dates across the site.",
    sections: [
      { heading: "What we correct", paragraphs: ["We correct factual errors, stale dynamic figures, broken or mismatched routes, translation mistakes, incorrect language metadata and statements that blur the line between Hacoo and this independent site."], bullets: ["Record the affected URL and wording", "Recheck the current primary source", "Update the claim and its check date", "Retest every language and destination"] },
      { heading: "What we do not do", paragraphs: ["We do not manufacture a new conclusion to protect an older article, erase a valid historical date or change a product route without checking its current destination. Material corrections should be visible in the page's reviewed date or publication record."] },
    ],
  },
  contact: {
    title: "Contact Boundaries",
    description: "The correct route for editorial corrections, Hacoo account support and product-catalogue questions.",
    kicker: "RIGHT QUESTION, RIGHT OWNER",
    intro: "HacooVIP is not a customer-service channel. Do not send passwords, payment details, addresses, order numbers, tracking records or private account information to an independent guide.",
    sections: [
      { heading: "Editorial issues", paragraphs: ["For an editorial correction, keep the page URL, the exact sentence or route, the current source and the date you checked it. This site does not currently run a public message form, so it does not pretend to collect or resolve private cases."], bullets: ["Page or product-route URL", "Exact wording or mismatch", "Current source and check date", "No personal or transaction data"] },
      { heading: "Accounts and orders", paragraphs: ["Questions about a Hacoo account, app feature, payment, order, delivery, cancellation, return or refund must use the support path shown in the current official app or official public contact page. Product-catalogue transactions belong to the destination shown after the user leaves this site."] },
    ],
  },
  privacy: {
    title: "Privacy Notice",
    description: "What data this static guide does and does not request, plus the boundaries of external searches and links.",
    kicker: "MINIMAL DATA",
    intro: "HacooVIP does not offer accounts, checkout or an order-support form. The site is designed so readers can browse its public pages without submitting personal information here.",
    sections: [
      { heading: "Technical requests", paragraphs: ["Our hosting and security provider may process ordinary request data such as an IP address, browser type, requested URL and security events to deliver and protect the site. We do not ask readers to place passwords, payment data, addresses or order details into this site."] },
      { heading: "External destinations", paragraphs: ["The search field and product, category or catalogue controls open a separate destination. That destination's privacy terms apply after the visitor leaves HacooVIP. Review the destination before entering personal or payment information."], bullets: ["No HacooVIP account", "No HacooVIP checkout", "No private order-support intake", "External sites apply their own policies"] },
    ],
  },
  terms: {
    title: "Terms of Use",
    description: "The informational scope, independence and third-party-link limits that apply when using HacooVIP.",
    kicker: "USE OF THIS GUIDE",
    intro: "HacooVIP provides independent informational content and product-research tools. Using the site does not create an account, agency relationship, purchase agreement or guarantee from HacooVIP.",
    sections: [
      { heading: "Information, not a promise", paragraphs: ["Content is prepared from sources available on its check date. It is not legal, financial or professional advice and does not guarantee product quality, authenticity, availability, price, fit, shipping or a return outcome. Verify important details on the live destination."], bullets: ["No official affiliation with Hacoo", "No order or payment processing", "No product or delivery guarantee", "No control over third-party changes"] },
      { heading: "Responsible use", paragraphs: ["Do not misuse the site, attempt to interfere with its operation or treat an independent index as proof of a product claim. Third-party names remain the property of their owners. These terms may be updated when the site's functions or legal requirements change."] },
    ],
  },
};

const de: Record<TrustRouteName, TrustPage> = {
  about: { title: "Über HacooVIP", description: "Wer HacooVIP veröffentlicht, was diese unabhängige Recherche abdeckt und wo ihre Verantwortung endet.", kicker: "UNABHÄNGIGER HERAUSGEBER", intro: "HacooVIP ist ein unabhängiger Herausgeber für Produktrecherche. Die Website ist nicht Hacoo, vertritt Hacoo nicht und bearbeitet keine Konten, Bestellungen, Zahlungen, Retouren oder Supportfälle.", sections: [{ heading: "Was wir veröffentlichen", paragraphs: ["Wir helfen, Produktanforderungen vor der Suche festzulegen, datierte öffentliche Informationen zur Hacoo-App einzuordnen und klar gekennzeichneten Links zu einem getrennten Live-Katalog zu folgen. Unabhängige Produktindizes werden nie als offizielle Hacoo-Tabelle dargestellt."], bullets: ["Recherche-Briefings und Checklisten", "Datierte App- und Richtlinienfakten", "Klar gekennzeichnete unabhängige Produktrouten"] }, { heading: "Wo unsere Rolle endet", paragraphs: ["Wir sehen keine Hacoo-Konten, Bestellungen, Zahlungen oder privaten Nachrichten. Plattformaktionen gehören in die offizielle App. Ein funktionierender Link garantiert weder Qualität, Echtheit, Preis, Bestand noch Lieferung."] }] },
  "editorial-policy": { title: "Redaktionsrichtlinie", description: "Wie HacooVIP offizielle Fakten, öffentliche Berichte, Analyse und Produktrouten trennt.", kicker: "PUBLIKATIONSSTANDARD", intro: "Jede Seite soll klar unterscheiden, was offizielle Aussage, datierter Fremdbeleg oder unsere praktische Einordnung ist.", sections: [{ heading: "Belege vor Schlussfolgerungen", paragraphs: ["Identität, Funktionen, Richtlinien und veränderliche Zahlen werden vor der Veröffentlichung anhand aktueller Primärquellen geprüft. Öffentliche Bewertungen sind Einzelberichte, keine allgemeinen Ergebnisse. Unbekanntes bleibt unbekannt."], bullets: ["Eine klare Leserfrage pro Leitfaden", "Datum und Region bei veränderlichen Angaben", "Keine erfundenen Bestellungen, Zitate oder Erfahrungen"] }, { heading: "Kommerzielle Grenzen", paragraphs: ["Produkt- und Kategorielinks können zum genehmigten Live-Katalog führen. Ihre Aufnahme ist kein Beweis für Eignung, Echtheit, Verkäuferzuverlässigkeit oder Lieferleistung."] }] },
  sources: { title: "Quellen & Faktenprüfung", description: "Quellenhierarchie, Datierungsregeln und Prüfmethode von HacooVIP.", kicker: "QUELLENMETHODE", intro: "Aktuelle offizielle Seiten sind der Ausgangspunkt für Plattformfakten. App-Store-Einträge und nachvollziehbare Berichte ergänzen Kontext, wenn Datum, Region und Grenzen sichtbar sind.", sections: [{ heading: "Quellenreihenfolge", paragraphs: ["Für App-Identität und Richtlinien bevorzugen wir aktuelle Hacoo-Seiten und Live-Einträge bei Apple oder Google. Kundenerfahrungen werden aus mehreren zugänglichen Berichten ausgewertet und von offiziellen Aussagen getrennt."], bullets: ["Offizielle Plattform- und Richtlinienseiten", "Aktuelle App-Store-Einträge", "Datierte, nachvollziehbare Berichte", "Unabhängige Einordnung"] }, { heading: "Veränderliche Informationen", paragraphs: ["Bewertungen, App-Versionen, Richtlinien, Preise, Bestand und Lieferoptionen können sich ändern. Wichtige variable Angaben erhalten ein Prüfdatum und sollen vor einer Entscheidung erneut kontrolliert werden."] }] },
  corrections: { title: "Korrekturrichtlinie", description: "Wie HacooVIP Sach-, Übersetzungs- und Linkfehler erkennt und behebt.", kicker: "KORREKTURSTANDARD", intro: "Eine Korrektur behebt die genaue Aussage, ohne die Änderung zu verstecken oder fremde Seitendaten zu aktualisieren.", sections: [{ heading: "Was wir korrigieren", paragraphs: ["Wir korrigieren Sachfehler, veraltete dynamische Zahlen, defekte oder falsche Links, Übersetzungsfehler, falsche Sprachmetadaten und Aussagen, die Hacoo mit dieser unabhängigen Website verwechseln."], bullets: ["Betroffene URL und Aussage festhalten", "Aktuelle Primärquelle prüfen", "Aussage und Prüfdatum aktualisieren", "Alle Sprachen und Ziele testen"] }, { heading: "Was wir nicht tun", paragraphs: ["Wir erfinden keine neue Schlussfolgerung, um einen alten Artikel zu schützen, löschen kein gültiges historisches Datum und ändern keine Produktroute ohne Zielprüfung."] }] },
  contact: { title: "Kontaktgrenzen", description: "Der richtige Weg für redaktionelle Korrekturen, Hacoo-Support und Katalogfragen.", kicker: "RICHTIGE FRAGE, RICHTIGE STELLE", intro: "HacooVIP ist kein Kundendienst. Senden Sie keine Passwörter, Zahlungsdaten, Adressen, Bestellnummern, Sendungsdaten oder privaten Kontoinformationen an einen unabhängigen Leitfaden.", sections: [{ heading: "Redaktionelle Hinweise", paragraphs: ["Für eine Korrektur werden Seiten-URL, genaue Aussage oder Link, aktuelle Quelle und Prüfdatum benötigt. Diese Website betreibt derzeit kein öffentliches Nachrichtenformular und gibt daher nicht vor, private Fälle zu bearbeiten."], bullets: ["Seiten- oder Produktrouten-URL", "Genaue Aussage oder Abweichung", "Aktuelle Quelle und Datum", "Keine Personen- oder Transaktionsdaten"] }, { heading: "Konten und Bestellungen", paragraphs: ["Fragen zu Hacoo-Konten, App-Funktionen, Zahlungen, Bestellungen, Lieferungen, Stornierungen, Retouren oder Erstattungen gehören zum Supportweg der aktuellen offiziellen App."] }] },
  privacy: { title: "Datenschutzhinweis", description: "Welche Daten dieser statische Leitfaden nicht anfordert und welche Grenzen für externe Links gelten.", kicker: "MINIMALE DATEN", intro: "HacooVIP bietet weder Konten noch Checkout oder ein Bestellsupport-Formular. Öffentliche Seiten können ohne Eingabe personenbezogener Daten genutzt werden.", sections: [{ heading: "Technische Anfragen", paragraphs: ["Hosting- und Sicherheitsanbieter können übliche Anfragedaten wie IP-Adresse, Browsertyp, URL und Sicherheitsereignisse zur Auslieferung und zum Schutz der Website verarbeiten. Wir fragen keine Passwörter, Zahlungsdaten, Adressen oder Bestelldetails ab."] }, { heading: "Externe Ziele", paragraphs: ["Suche, Produkt-, Kategorie- und Kataloglinks öffnen ein getrenntes Ziel. Nach dem Verlassen von HacooVIP gelten dessen Datenschutzbedingungen."], bullets: ["Kein HacooVIP-Konto", "Kein HacooVIP-Checkout", "Keine private Bestellannahme", "Externe Websites haben eigene Regeln"] }] },
  terms: { title: "Nutzungsbedingungen", description: "Informationsumfang, Unabhängigkeit und Grenzen externer Links bei HacooVIP.", kicker: "NUTZUNG DIESES LEITFADENS", intro: "HacooVIP stellt unabhängige Informationen und Recherchehilfen bereit. Die Nutzung begründet kein Konto, keine Vertretung, keinen Kaufvertrag und keine Garantie durch HacooVIP.", sections: [{ heading: "Information, kein Versprechen", paragraphs: ["Inhalte beruhen auf den am Prüfdatum verfügbaren Quellen. Sie garantieren weder Qualität, Echtheit, Verfügbarkeit, Preis, Passform, Lieferung noch Retourenergebnis. Wichtige Angaben sind am Live-Ziel zu prüfen."], bullets: ["Keine offizielle Hacoo-Verbindung", "Keine Bestell- oder Zahlungsabwicklung", "Keine Produkt- oder Liefergarantie", "Keine Kontrolle über Drittanbieteränderungen"] }, { heading: "Verantwortliche Nutzung", paragraphs: ["Stören oder missbrauchen Sie die Website nicht und behandeln Sie einen unabhängigen Index nicht als Beweis für Produktangaben. Namen Dritter bleiben Eigentum ihrer Inhaber."] }] },
};

const es: Record<TrustRouteName, TrustPage> = {
  about: { title: "Acerca de HacooVIP", description: "Quién publica HacooVIP, qué cubre y dónde termina su responsabilidad.", kicker: "EDITOR INDEPENDIENTE", intro: "HacooVIP es un medio independiente de investigación de productos. No es Hacoo, no lo representa ni gestiona cuentas, pedidos, pagos, devoluciones o soporte.", sections: [{ heading: "Qué publicamos", paragraphs: ["Ayudamos a definir requisitos antes de buscar, interpretar información pública fechada sobre la app Hacoo y seguir rutas claramente identificadas hacia un catálogo independiente. Nunca presentamos un índice externo como hoja oficial de Hacoo."], bullets: ["Fichas de requisitos y listas de control", "Datos fechados de la app y sus políticas", "Rutas de producto independientes y claras"] }, { heading: "Dónde termina nuestro papel", paragraphs: ["No vemos cuentas, pedidos, pagos ni mensajes privados de Hacoo. Las acciones de plataforma corresponden a la app oficial. Un enlace activo no garantiza calidad, autenticidad, precio, stock o entrega."] }] },
  "editorial-policy": { title: "Política editorial", description: "Cómo separamos hechos oficiales, informes públicos, análisis y rutas de producto.", kicker: "ESTÁNDAR DE PUBLICACIÓN", intro: "Cada página debe distinguir una afirmación oficial, un registro externo fechado y nuestra interpretación práctica.", sections: [{ heading: "Pruebas antes que conclusiones", paragraphs: ["La identidad, funciones, políticas y cifras variables se comprueban en fuentes primarias actuales. Las reseñas públicas son experiencias individuales, no resultados universales. Lo desconocido no se completa con suposiciones."], bullets: ["Una pregunta clara por guía", "Fecha y región en datos variables", "Sin pedidos, citas ni experiencias inventadas"] }, { heading: "Límites comerciales", paragraphs: ["Las rutas de producto y categoría pueden llevar al catálogo aprobado. Su presencia no demuestra idoneidad, autenticidad, fiabilidad del vendedor o rendimiento de entrega."] }] },
  sources: { title: "Fuentes y verificación", description: "Jerarquía de fuentes, fechas y método de verificación de HacooVIP.", kicker: "MÉTODO DE FUENTES", intro: "Las páginas oficiales actuales son el punto de partida. Las tiendas de apps y los informes trazables añaden contexto cuando se indican fecha, región y límites.", sections: [{ heading: "Orden de fuentes", paragraphs: ["Para identidad y políticas preferimos las páginas actuales de Hacoo y las fichas activas de Apple o Google. Para experiencias analizamos varios informes accesibles y los separamos del texto oficial."], bullets: ["Páginas oficiales", "Fichas actuales de apps", "Informes fechados y trazables", "Análisis editorial independiente"] }, { heading: "Información cambiante", paragraphs: ["Valoraciones, versiones, políticas, precios, stock y opciones de entrega cambian. Indicamos la fecha cuando importa y pedimos verificar la fuente actual antes de actuar."] }] },
  corrections: { title: "Política de correcciones", description: "Cómo detectamos y corregimos errores factuales, de traducción y de enlaces.", kicker: "ESTÁNDAR DE CORRECCIÓN", intro: "Una corrección repara la afirmación exacta sin ocultar el cambio ni renovar fechas ajenas.", sections: [{ heading: "Qué corregimos", paragraphs: ["Corregimos errores, cifras variables obsoletas, rutas rotas o equivocadas, malas traducciones, metadatos de idioma incorrectos y frases que confunden Hacoo con este sitio independiente."], bullets: ["Registrar URL y texto afectados", "Revisar la fuente primaria actual", "Actualizar afirmación y fecha", "Probar idiomas y destinos"] }, { heading: "Qué no hacemos", paragraphs: ["No inventamos una conclusión para proteger un artículo antiguo, no borramos fechas históricas válidas ni cambiamos una ruta sin revisar su destino."] }] },
  contact: { title: "Límites de contacto", description: "La vía correcta para correcciones, soporte de Hacoo y cuestiones del catálogo.", kicker: "LA PREGUNTA AL RESPONSABLE CORRECTO", intro: "HacooVIP no es atención al cliente. No envíes contraseñas, pagos, direcciones, pedidos, seguimiento ni datos privados a una guía independiente.", sections: [{ heading: "Asuntos editoriales", paragraphs: ["Una corrección necesita URL, frase o ruta exacta, fuente actual y fecha. Este sitio no ofrece ahora un formulario público y no finge gestionar casos privados."], bullets: ["URL de página o producto", "Texto o discrepancia exacta", "Fuente y fecha actuales", "Sin datos personales o de compra"] }, { heading: "Cuentas y pedidos", paragraphs: ["Las consultas sobre cuenta, app, pago, pedido, entrega, cancelación, devolución o reembolso deben usar el soporte mostrado en la app oficial actual."] }] },
  privacy: { title: "Aviso de privacidad", description: "Qué datos no solicita esta guía y qué ocurre al abrir destinos externos.", kicker: "DATOS MÍNIMOS", intro: "HacooVIP no ofrece cuentas, pago ni formularios de soporte. Sus páginas públicas pueden leerse sin entregar aquí información personal.", sections: [{ heading: "Solicitudes técnicas", paragraphs: ["El proveedor de alojamiento y seguridad puede procesar datos normales de solicitud, como IP, navegador, URL y eventos de seguridad, para servir y proteger el sitio. No pedimos contraseñas, pagos, direcciones o pedidos."] }, { heading: "Destinos externos", paragraphs: ["La búsqueda y los controles de producto, categoría o catálogo abren otro destino. Tras salir de HacooVIP se aplica su propia privacidad."], bullets: ["Sin cuenta HacooVIP", "Sin checkout HacooVIP", "Sin recepción de casos privados", "Cada destino aplica sus reglas"] }] },
  terms: { title: "Términos de uso", description: "Alcance informativo, independencia y límites de enlaces externos de HacooVIP.", kicker: "USO DE ESTA GUÍA", intro: "HacooVIP ofrece contenido independiente y herramientas de investigación. Usarlo no crea cuenta, representación, compra ni garantía de HacooVIP.", sections: [{ heading: "Información, no promesa", paragraphs: ["El contenido se basa en fuentes disponibles en su fecha de revisión. No garantiza calidad, autenticidad, disponibilidad, precio, ajuste, envío o devolución. Verifica lo importante en el destino activo."], bullets: ["Sin afiliación oficial con Hacoo", "Sin procesar pedidos o pagos", "Sin garantía de producto o entrega", "Sin control sobre cambios externos"] }, { heading: "Uso responsable", paragraphs: ["No interfieras con el sitio ni trates un índice independiente como prueba de una afirmación de producto. Los nombres de terceros pertenecen a sus titulares."] }] },
};

const fr: Record<TrustRouteName, TrustPage> = {
  about: { title: "À propos de HacooVIP", description: "Qui publie HacooVIP, ce que couvre ce site indépendant et où s'arrête sa responsabilité.", kicker: "ÉDITEUR INDÉPENDANT", intro: "HacooVIP est un éditeur indépendant consacré à la recherche produit. Il n'est pas Hacoo, ne le représente pas et ne gère aucun compte, commande, paiement, retour ou demande d'assistance.", sections: [{ heading: "Ce que nous publions", paragraphs: ["Nous aidons à définir les besoins avant la recherche, à comprendre des informations publiques datées sur l'app Hacoo et à suivre des liens clairement identifiés vers un catalogue distinct. Un index indépendant n'est jamais présenté comme un tableur officiel Hacoo."], bullets: ["Fiches de besoins et listes de contrôle", "Faits datés sur l'app et les politiques", "Liens produits indépendants clairement signalés"] }, { heading: "La limite de notre rôle", paragraphs: ["Nous ne voyons aucun compte, commande, paiement ou message privé Hacoo. Les actions de plateforme relèvent de l'app officielle. Un lien actif ne garantit ni qualité, authenticité, prix, stock ni livraison."] }] },
  "editorial-policy": { title: "Politique éditoriale", description: "Comment HacooVIP sépare faits officiels, retours publics, analyse et liens produits.", kicker: "NORME DE PUBLICATION", intro: "Chaque page doit distinguer une déclaration officielle, une source externe datée et notre interprétation pratique.", sections: [{ heading: "Les preuves avant les conclusions", paragraphs: ["Identité, fonctions, politiques et chiffres variables sont vérifiés dans des sources primaires actuelles. Les avis publics restent des expériences individuelles. Une information inconnue n'est pas remplacée par une supposition."], bullets: ["Une question claire par guide", "Date et région pour les données variables", "Aucune commande, citation ou expérience inventée"] }, { heading: "Limites commerciales", paragraphs: ["Les liens produit et catégorie peuvent mener au catalogue approuvé. Leur présence ne prouve ni l'adéquation, l'authenticité, la fiabilité du vendeur ni la livraison."] }] },
  sources: { title: "Sources et vérification", description: "Hiérarchie des sources, datation et méthode de vérification de HacooVIP.", kicker: "MÉTHODE DES SOURCES", intro: "Les pages officielles actuelles constituent le point de départ. Les fiches d'app et les rapports traçables ajoutent du contexte lorsque date, région et limites sont visibles.", sections: [{ heading: "Ordre des sources", paragraphs: ["Pour l'identité et les politiques, nous privilégions les pages Hacoo actuelles et les fiches Apple ou Google actives. Les expériences clients sont analysées à partir de plusieurs rapports accessibles et séparées du discours officiel."], bullets: ["Pages officielles", "Fiches actuelles des apps", "Rapports datés et traçables", "Analyse éditoriale indépendante"] }, { heading: "Informations changeantes", paragraphs: ["Notes, versions, politiques, prix, stock et livraison peuvent changer. Nous indiquons la date lorsqu'elle compte et demandons de vérifier la source actuelle avant d'agir."] }] },
  corrections: { title: "Politique de correction", description: "Comment HacooVIP corrige les erreurs factuelles, de traduction et de liens.", kicker: "NORME DE CORRECTION", intro: "Une correction répare l'affirmation exacte sans masquer le changement ni actualiser des dates sans rapport.", sections: [{ heading: "Ce que nous corrigeons", paragraphs: ["Nous corrigeons les erreurs factuelles, chiffres périmés, liens brisés ou inadéquats, mauvaises traductions, métadonnées de langue erronées et formulations confondant Hacoo avec ce site indépendant."], bullets: ["Noter l'URL et le texte concernés", "Revérifier la source primaire", "Modifier l'affirmation et la date", "Tester chaque langue et destination"] }, { heading: "Ce que nous ne faisons pas", paragraphs: ["Nous n'inventons pas une conclusion pour protéger un ancien article, n'effaçons pas une date historique valide et ne changeons pas un lien sans vérifier sa destination."] }] },
  contact: { title: "Limites de contact", description: "La bonne voie pour les corrections, l'assistance Hacoo et les questions de catalogue.", kicker: "LA BONNE QUESTION AU BON RESPONSABLE", intro: "HacooVIP n'est pas un service client. N'envoyez jamais mots de passe, paiements, adresses, commandes, suivis ou données privées à un guide indépendant.", sections: [{ heading: "Questions éditoriales", paragraphs: ["Une correction nécessite l'URL, la phrase ou le lien exact, la source actuelle et la date. Ce site ne propose pas actuellement de formulaire public et ne prétend donc pas traiter des dossiers privés."], bullets: ["URL de page ou de produit", "Texte ou écart exact", "Source et date actuelles", "Aucune donnée personnelle"] }, { heading: "Comptes et commandes", paragraphs: ["Les questions de compte, app, paiement, commande, livraison, annulation, retour ou remboursement doivent suivre l'assistance affichée dans l'app officielle actuelle."] }] },
  privacy: { title: "Avis de confidentialité", description: "Les données que ce guide ne demande pas et les limites des destinations externes.", kicker: "DONNÉES MINIMALES", intro: "HacooVIP ne propose ni compte, ni paiement, ni formulaire d'assistance. Ses pages publiques se consultent sans fournir ici de données personnelles.", sections: [{ heading: "Requêtes techniques", paragraphs: ["L'hébergeur et le fournisseur de sécurité peuvent traiter les données techniques ordinaires — IP, navigateur, URL et événements de sécurité — pour servir et protéger le site. Nous ne demandons ni mots de passe, paiements, adresses ou commandes."] }, { heading: "Destinations externes", paragraphs: ["La recherche et les liens produit, catégorie ou catalogue ouvrent un site distinct. Après avoir quitté HacooVIP, sa propre politique s'applique."], bullets: ["Aucun compte HacooVIP", "Aucun paiement HacooVIP", "Aucune collecte de dossiers privés", "Chaque destination a ses règles"] }] },
  terms: { title: "Conditions d'utilisation", description: "Portée informative, indépendance et limites des liens externes de HacooVIP.", kicker: "UTILISATION DE CE GUIDE", intro: "HacooVIP fournit des informations indépendantes et des outils de recherche. Son utilisation ne crée aucun compte, mandat, achat ou garantie de HacooVIP.", sections: [{ heading: "Une information, pas une promesse", paragraphs: ["Le contenu repose sur les sources disponibles à sa date de contrôle. Il ne garantit ni qualité, authenticité, disponibilité, prix, taille, livraison ou retour. Vérifiez les détails importants sur la destination active."], bullets: ["Aucune affiliation officielle avec Hacoo", "Aucune commande ou paiement", "Aucune garantie produit ou livraison", "Aucun contrôle des changements externes"] }, { heading: "Usage responsable", paragraphs: ["N'interférez pas avec le site et ne considérez pas un index indépendant comme la preuve d'une affirmation produit. Les noms de tiers appartiennent à leurs propriétaires."] }] },
};

const it: Record<TrustRouteName, TrustPage> = {
  about: { title: "Chi è HacooVIP", description: "Chi pubblica HacooVIP, cosa copre questo sito indipendente e dove termina la sua responsabilità.", kicker: "EDITORE INDIPENDENTE", intro: "HacooVIP è un editore indipendente dedicato alla ricerca dei prodotti. Non è Hacoo, non lo rappresenta e non gestisce account, ordini, pagamenti, resi o assistenza.", sections: [{ heading: "Cosa pubblichiamo", paragraphs: ["Aiutiamo a definire i requisiti prima della ricerca, a comprendere informazioni pubbliche datate sull'app Hacoo e a seguire percorsi chiaramente indicati verso un catalogo separato. Un indice indipendente non viene mai presentato come foglio ufficiale Hacoo."], bullets: ["Schede dei requisiti e checklist", "Dati datati su app e politiche", "Percorsi prodotto indipendenti e chiari"] }, { heading: "Dove finisce il nostro ruolo", paragraphs: ["Non vediamo account, ordini, pagamenti o messaggi privati Hacoo. Le azioni di piattaforma spettano all'app ufficiale. Un link attivo non garantisce qualità, autenticità, prezzo, disponibilità o consegna."] }] },
  "editorial-policy": { title: "Politica editoriale", description: "Come HacooVIP separa fatti ufficiali, segnalazioni pubbliche, analisi e percorsi prodotto.", kicker: "STANDARD DI PUBBLICAZIONE", intro: "Ogni pagina deve distinguere una dichiarazione ufficiale, una fonte esterna datata e la nostra interpretazione pratica.", sections: [{ heading: "Prove prima delle conclusioni", paragraphs: ["Identità, funzioni, politiche e cifre variabili vengono verificate su fonti primarie attuali. Le recensioni pubbliche sono esperienze individuali, non risultati universali. Ciò che non è noto resta tale."], bullets: ["Una domanda chiara per guida", "Data e regione per dati variabili", "Nessun ordine, citazione o esperienza inventata"] }, { heading: "Confini commerciali", paragraphs: ["I percorsi di prodotto e categoria possono condurre al catalogo approvato. La loro presenza non dimostra idoneità, autenticità, affidabilità del venditore o prestazioni di consegna."] }] },
  sources: { title: "Fonti e verifica dei fatti", description: "Gerarchia delle fonti, regole sulle date e metodo di verifica di HacooVIP.", kicker: "METODO DELLE FONTI", intro: "Le pagine ufficiali attuali sono il punto di partenza. Le schede degli app store e le segnalazioni tracciabili aggiungono contesto quando mostrano data, regione e limiti.", sections: [{ heading: "Ordine delle fonti", paragraphs: ["Per identità e politiche preferiamo le pagine Hacoo attuali e le schede live Apple o Google. Per le esperienze analizziamo più segnalazioni accessibili, tenendole separate dal testo ufficiale."], bullets: ["Pagine ufficiali", "Schede app aggiornate", "Segnalazioni datate e tracciabili", "Analisi editoriale indipendente"] }, { heading: "Informazioni variabili", paragraphs: ["Valutazioni, versioni, politiche, prezzi, disponibilità e consegne possono cambiare. Indichiamo la data quando conta e chiediamo di verificare la fonte attuale prima di agire."] }] },
  corrections: { title: "Politica delle correzioni", description: "Come HacooVIP corregge errori di fatto, traduzione e collegamento.", kicker: "STANDARD DI CORREZIONE", intro: "Una correzione sistema l'affermazione precisa senza nascondere il cambiamento o aggiornare date non coinvolte.", sections: [{ heading: "Cosa correggiamo", paragraphs: ["Correggiamo errori, cifre dinamiche obsolete, percorsi rotti o errati, traduzioni sbagliate, metadati linguistici non corretti e frasi che confondono Hacoo con questo sito indipendente."], bullets: ["Registrare URL e testo coinvolti", "Ricontrollare la fonte primaria", "Aggiornare affermazione e data", "Testare lingue e destinazioni"] }, { heading: "Cosa non facciamo", paragraphs: ["Non inventiamo conclusioni per proteggere un vecchio articolo, non cancelliamo una data storica valida e non cambiamo un percorso senza verificarne la destinazione."] }] },
  contact: { title: "Limiti di contatto", description: "Il percorso corretto per correzioni, assistenza Hacoo e domande sul catalogo.", kicker: "LA DOMANDA AL RESPONSABILE GIUSTO", intro: "HacooVIP non è assistenza clienti. Non inviare password, pagamenti, indirizzi, ordini, tracciamenti o dati privati a una guida indipendente.", sections: [{ heading: "Questioni editoriali", paragraphs: ["Per una correzione servono URL, frase o percorso preciso, fonte attuale e data. Il sito non dispone ora di un modulo pubblico e non finge quindi di gestire casi privati."], bullets: ["URL di pagina o prodotto", "Testo o difformità precisa", "Fonte e data attuali", "Nessun dato personale o d'acquisto"] }, { heading: "Account e ordini", paragraphs: ["Le domande su account, app, pagamento, ordine, consegna, annullamento, reso o rimborso devono usare l'assistenza indicata nell'app ufficiale attuale."] }] },
  privacy: { title: "Informativa sulla privacy", description: "Quali dati questa guida non richiede e i limiti delle destinazioni esterne.", kicker: "DATI MINIMI", intro: "HacooVIP non offre account, checkout o moduli di assistenza. Le pagine pubbliche possono essere lette senza fornire qui dati personali.", sections: [{ heading: "Richieste tecniche", paragraphs: ["Il fornitore di hosting e sicurezza può trattare normali dati di richiesta, come IP, browser, URL ed eventi di sicurezza, per fornire e proteggere il sito. Non chiediamo password, pagamenti, indirizzi o ordini."] }, { heading: "Destinazioni esterne", paragraphs: ["La ricerca e i controlli di prodotto, categoria o catalogo aprono un sito separato. Dopo aver lasciato HacooVIP si applicano le sue condizioni privacy."], bullets: ["Nessun account HacooVIP", "Nessun checkout HacooVIP", "Nessuna raccolta di casi privati", "Ogni destinazione ha le proprie regole"] }] },
  terms: { title: "Condizioni d'uso", description: "Ambito informativo, indipendenza e limiti dei link esterni di HacooVIP.", kicker: "USO DI QUESTA GUIDA", intro: "HacooVIP offre contenuti indipendenti e strumenti di ricerca. L'uso non crea un account, un rapporto di agenzia, un acquisto o una garanzia HacooVIP.", sections: [{ heading: "Informazione, non promessa", paragraphs: ["I contenuti usano le fonti disponibili alla data di controllo. Non garantiscono qualità, autenticità, disponibilità, prezzo, vestibilità, consegna o reso. Verifica i dettagli importanti sulla destinazione live."], bullets: ["Nessuna affiliazione ufficiale con Hacoo", "Nessuna gestione di ordini o pagamenti", "Nessuna garanzia su prodotto o consegna", "Nessun controllo sui cambiamenti esterni"] }, { heading: "Uso responsabile", paragraphs: ["Non interferire con il sito e non trattare un indice indipendente come prova di una dichiarazione sul prodotto. I nomi di terzi appartengono ai rispettivi titolari."] }] },
};

const pages: Record<Locale, Record<TrustRouteName, TrustPage>> = { en, de, es, fr, it };

export function getTrustPage(locale: Locale, page: TrustRouteName) {
  return pages[locale][page];
}
