import type { Lang } from "@/lib/site-data";

type FactSet = { label: string; checked: string; items: string[] };

export const officialFacts: Record<Lang, Record<string, FactSet>> = {
  en: {
    spreadsheet: { label: "Official context", checked: "Checked · 28 Aug 2026", items: ["Hacoo describes itself as a community-driven discovery and content-sharing platform.", "Its terms say creator content may be inaccurate, outdated, downgraded or removed.", "A ‘Hacoo spreadsheet’ is an independent discovery index—not an official Hacoo product feed."] },
    finds: { label: "What the app officially supports", checked: "Checked · 28 Aug 2026", items: ["The App Store description says users can share content and rate products, brands and services.", "The UK App Store lists the app in 25 languages and identifies user-generated content, messaging and social features.", "Product visibility and live details should always be rechecked before relying on a saved route."] },
    guide: { label: "Official order flow", checked: "Hacoo Help Center", items: ["Open the Hacoo app and log in.", "Select items and add them to the cart.", "Complete checkout and payment in the app; this independent guide does not process orders."] },
    qc: { label: "Evidence standard", checked: "Hacoo Trust Center · 2026", items: ["Hacoo says reviews should include honest flaws such as tight fit or fabric transparency.", "Fit comments are personal evidence; measurements remain more reliable for sizing.", "Photos cannot prove authenticity, hidden construction or long-term durability."] },
    shipping: { label: "Published delivery guidance", checked: "Official page checked · 28 Aug 2026", items: ["Usual receiving time: about 15–28 days; processing is normally 3–5 business days.", "UK, France, Germany and Italy: 15–25 days. Spain: 15–30 days.", "Other countries: 25–65 days. Hacoo describes these windows as guidelines, not guarantees."] },
    articles: { label: "Editorial standard", checked: "Sources reviewed · 28 Aug 2026", items: ["Official policy pages establish platform rules, delivery windows and after-sales steps.", "App Store, Google Play and Trustpilot ratings are presented separately with dates.", "Company claims, customer reports and independent analysis are never blended into one fact."] },
    faq: { label: "Current policy snapshot", checked: "Official Help Center", items: ["Eligible returns must be started within 15 days after delivery through in-app customer service.", "Hacoo’s help material says exchanges are not supported; the stated route is return/refund and repurchase.", "Evidence requirements vary by issue, so current order-specific instructions take priority."] },
  },
  de: {
    spreadsheet: { label: "Offizieller Kontext", checked: "Geprüft · 28. Aug. 2026", items: ["Hacoo beschreibt sich als Community-Plattform für Entdeckung und Inhalte.", "Laut Nutzungsbedingungen können Creator-Inhalte veraltet, fehlerhaft, herabgestuft oder entfernt werden.", "Eine Hacoo-Tabelle ist ein unabhängiger Index, kein offizieller Produktfeed."] },
    finds: { label: "Offizielle App-Funktionen", checked: "Geprüft · 28. Aug. 2026", items: ["Die App-Store-Beschreibung nennt Inhalte sowie Bewertungen von Produkten, Marken und Diensten.", "Im UK App Store werden 25 Sprachen, nutzergenerierte Inhalte, Nachrichten und Social-Funktionen genannt.", "Live-Details vor Nutzung eines gespeicherten Weges erneut prüfen."] },
    guide: { label: "Offizieller Bestellablauf", checked: "Hacoo Help Center", items: ["Hacoo-App öffnen und anmelden.", "Artikel auswählen und in den Warenkorb legen.", "Checkout und Zahlung erfolgen in der App; dieser Guide nimmt keine Bestellung an."] },
    qc: { label: "Standard für Nachweise", checked: "Hacoo Trust Center · 2026", items: ["Hacoo betont ehrliche Fehler wie enge Passform oder transparenten Stoff.", "Passform-Kommentare sind persönliche Erfahrungen; Maße sind verlässlicher.", "Fotos beweisen weder Echtheit noch versteckte Verarbeitung oder Haltbarkeit."] },
    shipping: { label: "Veröffentlichte Lieferangaben", checked: "Geprüft · 28. Aug. 2026", items: ["Üblicher Empfang: etwa 15–28 Tage; Bearbeitung meist 3–5 Werktage.", "UK, Frankreich, Deutschland, Italien: 15–25 Tage. Spanien: 15–30 Tage.", "Andere Länder: 25–65 Tage. Diese Angaben sind Richtwerte, keine Garantien."] },
    articles: { label: "Redaktioneller Standard", checked: "Quellen geprüft · 28. Aug. 2026", items: ["Offizielle Richtlinien liefern Regeln, Lieferangaben und Nachverkaufsschritte.", "App Store, Google Play und Trustpilot werden getrennt und datiert gezeigt.", "Unternehmensaussagen, Nutzerberichte und Analyse bleiben klar getrennt."] },
    faq: { label: "Aktueller Richtlinienstand", checked: "Offizielles Help Center", items: ["Berechtigte Rückgaben müssen innerhalb von 15 Tagen nach Zustellung über den App-Support begonnen werden.", "Laut Hacoo werden Umtausche nicht unterstützt; beschrieben ist Rückgabe/Erstattung und Neukauf.", "Nachweise hängen vom Problem ab; aktuelle Auftragsanweisungen haben Vorrang."] },
  },
  es: {
    spreadsheet: { label: "Contexto oficial", checked: "Revisado · 28 ago. 2026", items: ["Hacoo se define como plataforma comunitaria de descubrimiento y contenido.", "Sus términos indican que el contenido puede quedar desactualizado, ser incorrecto, degradado o eliminado.", "Una hoja Hacoo es un índice independiente, no un feed oficial."] },
    finds: { label: "Funciones oficiales", checked: "Revisado · 28 ago. 2026", items: ["La descripción de App Store permite compartir contenido y valorar productos, marcas y servicios.", "La ficha británica enumera 25 idiomas, contenido de usuarios, mensajería y funciones sociales.", "Los datos actuales deben comprobarse antes de usar una ruta guardada."] },
    guide: { label: "Flujo oficial de pedido", checked: "Centro de ayuda Hacoo", items: ["Abre la aplicación e inicia sesión.", "Selecciona artículos y añádelos al carrito.", "El pago se completa en la aplicación; esta guía no procesa pedidos."] },
    qc: { label: "Estándar de evidencia", checked: "Trust Center Hacoo · 2026", items: ["Hacoo destaca reseñas con defectos reales, como ajuste estrecho o tejido transparente.", "Los comentarios de talla son experiencias personales; las medidas son más fiables.", "Las fotos no prueban autenticidad, construcción oculta ni durabilidad."] },
    shipping: { label: "Plazos publicados", checked: "Revisado · 28 ago. 2026", items: ["Recepción habitual: 15–28 días; preparación normalmente 3–5 días laborables.", "Reino Unido, Francia, Alemania e Italia: 15–25 días. España: 15–30 días.", "Otros países: 25–65 días. Son orientaciones, no garantías."] },
    articles: { label: "Estándar editorial", checked: "Fuentes revisadas · 28 ago. 2026", items: ["Las políticas oficiales respaldan reglas, plazos y procesos posventa.", "App Store, Google Play y Trustpilot se presentan por separado y con fecha.", "Afirmaciones de empresa, testimonios y análisis no se mezclan."] },
    faq: { label: "Resumen de política", checked: "Centro de ayuda oficial", items: ["Las devoluciones elegibles deben iniciarse en los 15 días posteriores a la entrega mediante soporte en la app.", "Hacoo indica que no ofrece cambio: describe devolución/reembolso y nueva compra.", "Las pruebas dependen del problema; prevalecen las instrucciones actuales del pedido."] },
  },
  fr: {
    spreadsheet: { label: "Contexte officiel", checked: "Vérifié · 28 août 2026", items: ["Hacoo se présente comme une plateforme communautaire de découverte et de contenu.", "Ses conditions indiquent que le contenu peut être erroné, obsolète, déclassé ou supprimé.", "Un tableau Hacoo est un index indépendant, pas un flux officiel."] },
    finds: { label: "Fonctions officielles", checked: "Vérifié · 28 août 2026", items: ["La fiche App Store mentionne le partage et l’évaluation de produits, marques et services.", "La fiche britannique indique 25 langues, contenu utilisateur, messagerie et fonctions sociales.", "Les détails en direct doivent être revérifiés avant d’utiliser un lien enregistré."] },
    guide: { label: "Parcours de commande officiel", checked: "Centre d’aide Hacoo", items: ["Ouvrir l’application et se connecter.", "Sélectionner les articles et les ajouter au panier.", "Paiement et validation se font dans l’application ; ce guide ne traite aucune commande."] },
    qc: { label: "Niveau de preuve", checked: "Trust Center Hacoo · 2026", items: ["Hacoo met en avant les avis qui signalent des défauts réels, comme une coupe serrée ou un tissu transparent.", "Les avis de taille restent personnels ; les mesures sont plus fiables.", "Les photos ne prouvent ni authenticité, ni construction cachée, ni durabilité."] },
    shipping: { label: "Délais publiés", checked: "Vérifié · 28 août 2026", items: ["Réception habituelle : 15–28 jours ; traitement généralement 3–5 jours ouvrés.", "R.-U., France, Allemagne et Italie : 15–25 jours. Espagne : 15–30 jours.", "Autres pays : 25–65 jours. Ce sont des indications, pas des garanties."] },
    articles: { label: "Norme éditoriale", checked: "Sources vérifiées · 28 août 2026", items: ["Les pages officielles établissent règles, délais et étapes après-vente.", "App Store, Google Play et Trustpilot sont présentés séparément et datés.", "Déclarations de l’entreprise, témoignages et analyse restent distincts."] },
    faq: { label: "État actuel des règles", checked: "Centre d’aide officiel", items: ["Les retours éligibles doivent être lancés dans les 15 jours après livraison via le support de l’application.", "Hacoo indique ne pas proposer d’échange : retour/remboursement puis nouvel achat.", "Les preuves varient selon le problème ; les instructions actuelles de commande priment."] },
  },
  it: {
    spreadsheet: { label: "Contesto ufficiale", checked: "Verificato · 28 ago. 2026", items: ["Hacoo si descrive come piattaforma comunitaria di scoperta e contenuti.", "I termini dicono che i contenuti possono essere errati, obsoleti, declassati o rimossi.", "Un foglio Hacoo è un indice indipendente, non un feed ufficiale."] },
    finds: { label: "Funzioni ufficiali", checked: "Verificato · 28 ago. 2026", items: ["La descrizione App Store cita condivisione e valutazione di prodotti, marchi e servizi.", "La scheda UK elenca 25 lingue, contenuti degli utenti, messaggi e funzioni social.", "I dettagli live vanno ricontrollati prima di usare un percorso salvato."] },
    guide: { label: "Flusso d’ordine ufficiale", checked: "Centro assistenza Hacoo", items: ["Apri l’app e accedi.", "Seleziona articoli e aggiungili al carrello.", "Checkout e pagamento avvengono nell’app; questa guida non gestisce ordini."] },
    qc: { label: "Standard delle prove", checked: "Trust Center Hacoo · 2026", items: ["Hacoo valorizza recensioni con difetti reali, come vestibilità stretta o tessuto trasparente.", "I commenti sulla taglia sono personali; le misure sono più affidabili.", "Le foto non provano autenticità, costruzione nascosta o durata."] },
    shipping: { label: "Tempi pubblicati", checked: "Verificato · 28 ago. 2026", items: ["Ricezione abituale: 15–28 giorni; preparazione normalmente 3–5 giorni lavorativi.", "Regno Unito, Francia, Germania e Italia: 15–25 giorni. Spagna: 15–30 giorni.", "Altri paesi: 25–65 giorni. Sono linee guida, non garanzie."] },
    articles: { label: "Standard editoriale", checked: "Fonti verificate · 28 ago. 2026", items: ["Le pagine ufficiali stabiliscono regole, tempi e passaggi post-vendita.", "App Store, Google Play e Trustpilot sono presentati separatamente e con data.", "Dichiarazioni aziendali, esperienze e analisi restano distinte."] },
    faq: { label: "Politica attuale", checked: "Centro assistenza ufficiale", items: ["I resi idonei vanno avviati entro 15 giorni dalla consegna tramite assistenza in-app.", "Hacoo dichiara di non supportare cambi: descrive reso/rimborso e nuovo acquisto.", "Le prove dipendono dal problema; prevalgono le istruzioni attuali dell’ordine."] },
  },
};
