export const pageParitySupplements = {
  de: {
    spreadsheet: "Jeder Eintrag wird mit Prüfdatum, ausgewählter Variante, sichtbarer Währung und Zieltyp dokumentiert. Eine erreichbare URL reicht nicht: Bild, Produkttitel und Zielseite müssen denselben Artikel zeigen. Geänderte oder entfernte Creator-Inhalte werden nicht als weiterhin verfügbar dargestellt. Vor der Nutzung wird die Live-Prüfung wiederholt, weil Preise, Optionen und Veröffentlichungen wechseln können. So bleibt der Index eine überprüfbare Entscheidungshilfe und wird nicht mit einem offiziellen Hacoo-Katalog verwechselt. Auch die ursprüngliche Kategorie bleibt nachvollziehbar.",
    finds: "Wähle zunächst zwei oder drei passende Kandidaten und öffne erst danach weitere Ergebnisse. Notiere, welche Variante du verglichen hast, und behandle jeden USD-Preis als datierte Referenz. Wenn Karte und Ziel nicht mehr übereinstimmen, nutze die Kategorie als neuen Ausgangspunkt, statt einen nur ähnlich aussehenden Artikel zu akzeptieren. Dieser Ablauf hält die Auswahl klein, aktuell und auf dem Smartphone nachvollziehbar.",
    guide: "Der offizielle Ablauf endet mit Auswahl, Warenkorb, Checkout und Zahlung in der Hacoo-App. Dieser unabhängige Guide übernimmt keinen dieser Schritte. Er hilft nur beim Finden, Abgleichen und Dokumentieren. Kontrolliere vor dem Checkout außerdem Land, Adresse, Variante, sichtbaren Preis und aktuelle Regel. Speichere keine persönlichen Daten öffentlich und behandle frühere Screenshots als historischen Hinweis, nicht als aktuelle Zusage.",
    qc: "Nutze mehrere Ansichten und markiere verdeckte Bereiche als unbekannt. Perspektive, Beleuchtung und Kompression können Form, Farbe und kleine Nähte verändern. Größenhinweise werden mit echten Maßen eines vorhandenen Artikels verglichen. Ein sichtbarer Mangel kann dokumentiert werden; fehlende Sichtbarkeit beweist dagegen keine perfekte Verarbeitung. QC-Fotos reduzieren nur die sichtbare Unsicherheit und ersetzen weder Materialprüfung noch Langzeiterfahrung.",
    shipping: "Hacoo veröffentlicht üblicherweise 15–28 Tage, mit 15–25 Tagen für UK, Frankreich, Deutschland und Italien, 15–30 für Spanien und 25–65 für andere Länder. Bearbeitung wird normalerweise mit 3–5 Werktagen angegeben. Diese Bereiche sind Richtwerte. Dokumentiere Zahlung, Versand, ersten Carrier-Scan und Zustellung getrennt, damit Bearbeitungs- und Transportzeit nicht vermischt werden. Für berechtigte Rückgaben gilt laut Hilfe ein 15-Tage-Fenster ab Zustellung.",
    articles: "Die Artikel verwenden offizielle Hacoo-Richtlinien als Grundlage und kennzeichnen Unternehmensangaben ausdrücklich als solche. Öffentliche Bewertungen von App Store, Google Play und Trustpilot werden getrennt, mit Datum und Bewertungszahl dargestellt. Persönliche Kundenerfahrungen bleiben persönliche Berichte. Jede Sprachversion enthält denselben Prüfweg, dieselben Grenzen und dieselben nächsten Schritte; eine Sprachwahl darf weder Fakten noch Warnhinweise entfernen.",
    faq: "Für eine konkrete Entscheidung gilt immer die aktuell geöffnete Seite. Prüfe Variante, Währung, Zielland, Adresse und Bestellstatus, bevor du dich auf eine gespeicherte Information verlässt. Hacoo nennt für berechtigte Rückgaben 15 Tage nach Zustellung und verweist auf den In-App-Support; direkter Umtausch wird laut Hilfe nicht angeboten. Erforderliche Nachweise können je nach Problem variieren, deshalb haben auftragsbezogene Anweisungen Vorrang."
  },
  es: {
    spreadsheet: "Cada entrada conserva fecha de revisión, variante, moneda visible y tipo de destino. Que una URL responda no es suficiente: imagen, título y ficha deben representar el mismo artículo. Si el contenido de un creador cambia o desaparece, no se presenta como todavía disponible. La comprobación se repite justo antes de utilizar la ruta porque precios, opciones y publicaciones pueden variar. Así el índice sigue siendo una ayuda verificable y no se confunde con un catálogo oficial de Hacoo.",
    finds: "Elige primero dos o tres candidatos y no abras más hasta terminar la comparación. Anota la variante revisada y trata cualquier precio en USD como referencia fechada. Si tarjeta y destino dejan de coincidir, vuelve a la categoría en vez de aceptar un producto simplemente parecido. Este método mantiene la selección pequeña, actual y fácil de revisar desde el móvil, además de mostrar con claridad qué fuente live respalda cada elección.",
    guide: "El flujo oficial continúa en la app con selección, carrito, checkout y pago; esta guía independiente no realiza esos pasos. Su función es buscar, comparar y documentar. Antes del checkout confirma también país, dirección, variante, precio visible y norma vigente. No publiques datos personales y considera capturas antiguas como contexto histórico, nunca como promesa actual. Una decisión útil separa lo observado, lo estimado y lo que todavía necesita una comprobación live.",
    qc: "Utiliza varias vistas y marca como desconocidas las zonas ocultas. Perspectiva, luz y compresión pueden alterar forma, color y pequeñas costuras. Los comentarios de talla se comparan con medidas reales de una prenda propia. Un defecto visible puede documentarse, pero no ver un problema no demuestra fabricación perfecta. Las fotos QC reducen incertidumbre visual; no sustituyen inspección de material, construcción interna, uso prolongado ni una prueba de autenticidad.",
    shipping: "Hacoo publica normalmente 15–28 días: 15–25 para Reino Unido, Francia, Alemania e Italia; 15–30 para España; y 25–65 para otros países. El procesamiento suele figurar como 3–5 días laborables. Son rangos orientativos. Registra por separado pago, expedición, primer escaneo y entrega para no mezclar preparación y transporte. La ayuda oficial sitúa las devoluciones elegibles dentro de 15 días desde la entrega y dirige al soporte de la app.",
    articles: "Los artículos parten de políticas oficiales de Hacoo y etiquetan claramente las declaraciones de la empresa. Las puntuaciones de App Store, Google Play y Trustpilot se mantienen separadas, con fecha y volumen; los testimonios de clientes siguen siendo experiencias personales. Todas las versiones lingüísticas conservan método, límites, datos y siguientes comprobaciones. Cambiar idioma no debe retirar una advertencia, una fuente o una parte de la conclusión.",
    faq: "Para una decisión concreta prevalece siempre la página abierta en ese momento. Comprueba variante, moneda, país, dirección y estado del pedido antes de depender de un dato guardado. La ayuda de Hacoo indica 15 días desde la entrega para devoluciones elegibles y remite al soporte en la app; también señala que no existe intercambio directo. Las pruebas dependen del problema, de modo que las instrucciones de la orden actual tienen prioridad.",
  },
  fr: {
    spreadsheet: "Chaque entrée conserve date de contrôle, variante, devise visible et type de destination. Une URL accessible ne suffit pas : image, titre et fiche doivent représenter le même article. Si le contenu d’un créateur change ou disparaît, il n’est pas présenté comme encore disponible. La vérification est répétée juste avant utilisation, car prix, options et publications évoluent. L’index reste ainsi une aide vérifiable sans être confondu avec un catalogue officiel Hacoo.",
    finds: "Sélectionnez d’abord deux ou trois candidats et terminez leur comparaison avant d’en ouvrir davantage. Notez la variante examinée et traitez tout prix USD comme référence datée. Si carte et destination ne correspondent plus, revenez à la catégorie plutôt que d’accepter un produit seulement similaire. Cette méthode garde la sélection courte, actuelle et lisible sur mobile, tout en montrant quelle source en direct soutient chaque choix.",
    guide: "Le parcours officiel continue dans l’application avec sélection, panier, checkout et paiement ; ce guide indépendant n’effectue aucune de ces étapes. Il sert à trouver, comparer et documenter. Avant le checkout, confirmez pays, adresse, variante, prix visible et règle actuelle. Ne publiez pas de données personnelles et considérez les anciennes captures comme contexte historique, jamais comme promesse. Séparez toujours faits observés, estimations et éléments restant à vérifier en direct.",
    qc: "Utilisez plusieurs vues et marquez comme inconnues les zones cachées. Perspective, lumière et compression peuvent modifier forme, couleur et petites coutures. Les commentaires de taille sont comparés à des mesures réelles d’un article personnel. Un défaut visible peut être documenté, mais l’absence de défaut visible ne prouve pas une fabrication parfaite. Les photos QC réduisent l’incertitude visuelle sans remplacer contrôle matière, construction interne, usage prolongé ou preuve d’authenticité.",
    shipping: "Hacoo publie habituellement 15–28 jours : 15–25 pour Royaume-Uni, France, Allemagne et Italie, 15–30 pour Espagne et 25–65 pour les autres pays. Le traitement est généralement annoncé à 3–5 jours ouvrés. Ce sont des fourchettes indicatives. Notez séparément paiement, expédition, premier scan et livraison afin de distinguer préparation et transport. L’aide officielle fixe les retours éligibles dans les 15 jours suivant la livraison via le support de l’application.",
    articles: "Les articles s’appuient sur les règles officielles de Hacoo et identifient clairement les déclarations de l’entreprise. Les notes App Store, Google Play et Trustpilot restent séparées avec date et volume ; les témoignages clients demeurent des expériences personnelles. Toutes les langues conservent méthode, limites, données et prochaines vérifications. Changer de langue ne doit supprimer ni avertissement, ni source, ni partie de conclusion.",
    faq: "Pour une décision concrète, la page actuellement ouverte reste prioritaire. Vérifiez variante, devise, pays, adresse et état de commande avant de dépendre d’une donnée sauvegardée. L’aide Hacoo indique 15 jours après livraison pour les retours éligibles via le support de l’application et précise qu’un échange direct n’est pas proposé. Les justificatifs varient selon le problème ; les instructions propres à la commande passent donc en premier.",
  },
  it: {
    spreadsheet: "Ogni voce conserva data di controllo, variante, valuta visibile e tipo di destinazione. Un URL raggiungibile non basta: immagine, titolo e pagina devono descrivere lo stesso articolo. Se un contenuto del creator cambia o scompare, non viene presentato come ancora disponibile. La verifica si ripete subito prima dell’uso perché prezzi, opzioni e pubblicazioni possono cambiare. L’indice resta così una guida verificabile e non viene confuso con un catalogo ufficiale Hacoo. Anche categoria iniziale e termine usato restano documentati.",
    finds: "Scegli prima due o tre candidati e completa il confronto prima di aprirne altri. Annota la variante esaminata e tratta ogni prezzo USD come riferimento datato. Se scheda e destinazione non coincidono più, torna alla categoria invece di accettare un prodotto soltanto simile. Questo metodo mantiene la selezione piccola, aggiornata e leggibile da mobile, mostrando quale fonte live sostiene ogni scelta.",
    guide: "Il percorso ufficiale continua nell’app con selezione, carrello, checkout e pagamento; questa guida indipendente non esegue nessuna di queste fasi. Serve a trovare, confrontare e documentare. Prima del checkout conferma Paese, indirizzo, variante, prezzo visibile e regola corrente. Non pubblicare dati personali e considera vecchi screenshot come contesto storico, mai come promessa. Separa fatti osservati, stime e punti che richiedono ancora una verifica live.",
    qc: "Usa più viste e segna come sconosciute le aree nascoste. Prospettiva, luce e compressione possono cambiare forma, colore e piccole cuciture. I commenti sulla taglia vanno confrontati con misure reali di un capo proprio. Un difetto visibile può essere documentato, ma non vedere un problema non dimostra lavorazione perfetta. Le foto QC riducono l’incertezza visiva senza sostituire controllo del materiale, costruzione interna, uso prolungato o prova di autenticità.",
    shipping: "Hacoo pubblica normalmente 15–28 giorni: 15–25 per Regno Unito, Francia, Germania e Italia, 15–30 per la Spagna e 25–65 per altri Paesi. L’elaborazione è generalmente indicata in 3–5 giorni lavorativi. Sono intervalli orientativi. Registra separatamente pagamento, spedizione, prima scansione e consegna per distinguere preparazione e trasporto. L’assistenza ufficiale colloca i resi idonei entro 15 giorni dalla consegna tramite supporto nell’app.",
    articles: "Gli articoli partono dalle regole ufficiali di Hacoo e identificano chiaramente le dichiarazioni dell’azienda. Le valutazioni di App Store, Google Play e Trustpilot restano separate con data e volume; i racconti dei clienti rimangono esperienze personali. Tutte le lingue conservano metodo, limiti, dati e controlli successivi. Cambiare lingua non deve rimuovere un’avvertenza, una fonte o una parte della conclusione.",
    faq: "Per una decisione concreta prevale sempre la pagina aperta in quel momento. Controlla variante, valuta, Paese, indirizzo e stato dell’ordine prima di affidarti a un dato salvato. L’assistenza Hacoo indica 15 giorni dalla consegna per i resi idonei tramite supporto nell’app e afferma che non è previsto cambio diretto. Le prove cambiano secondo il problema, quindi le istruzioni dello specifico ordine hanno priorità."
  }
} as const;
