import type { SiteLanguage } from "./i18n";

type ArticleCopy = {
  title: string;
  description: string;
  updated: string;
  read: string;
  sections: readonly (readonly [string, string])[];
  sources: readonly { title: string; href: string }[];
};

const sources: ArticleCopy["sources"] = [];

export const germanyDestinationArticleByLanguage: Record<SiteLanguage, ArticleCopy> = {
  en: {
    title: "Joyagoo Germany Guide: Build a Destination-Ready Order Record",
    description: "Prepare Joyagoo product options, measurements, German address fields and a reviewable order record without guessing freight, tax or delivery times.",
    updated: "September 8, 2026",
    read: "14 min read",
    sections: [
      ["Define what destination-ready means", "A destination-ready record is not a promise that a product can use a particular route to Germany. It is a working file that lets a buyer transfer the intended item, option and recipient details into the live Joyagoo flow without relying on memory. Joyagoo's public interface currently offers German as a language and EUR as a display currency, while its shopping guidance tells buyers to choose color, size and quantity before payment. Those features make the interface easier to read; they do not freeze a listing, set a final exchange rate or prove that a parcel is eligible for Germany. Start with a simple scope statement: this record identifies the product, preserves the seller's original option wording, explains the buyer's intended choice, and prepares address fields for later validation. Keep freight, customs, tax and delivery estimates outside the record until the live parcel screen provides current data. That separation prevents a useful language guide from becoming an unsupported cost quote."],
      ["Keep the source wording beside the German note", "Machine translation is helpful for orientation, but an option selector is an instruction, not ordinary prose. Save the seller's exact visible text before translating it. Put the original term in the first column, a German working meaning in the second, and the evidence for that meaning in the third. Evidence can be the option image, a measurement chart, a model number, a seller description or a direct clarification recorded in the order. If two translations remain plausible, label the field unresolved rather than choosing the more attractive interpretation. Keep numbers, model codes, material percentages and version names unchanged unless the source itself changes. For example, do not translate a model suffix as a color or convert a pack count into a size. The objective is not elegant German copy; it is an order note that another person can compare with the live listing character by character and understand where uncertainty remains."],
      ["Separate color, size, version and quantity", "Build four independent fields even when the seller combines them in one line. Color records the exact option label and a plain-language description, but a thumbnail is only a visual clue because lighting and image processing can shift appearance. Size records the printed system—such as CN, EU, UK, US or a seller-specific label—plus the actual measurements used for comparison. Version records model, edition, material, package type or another product distinction. Quantity records both the number of order units and what one unit contains. A listing that says 'two-piece set' may still use quantity one at checkout. Never copy the lowest displayed price into this section as proof of the chosen variant. Instead, review the current order summary after selection. The final four-field line should be readable without the product image: exact color text; size label and measurement basis; version identifier; order quantity and pieces per unit."],
      ["Use measurements without inventing a size conversion", "A German buyer may recognize EU labels, but the presence of an EU number does not guarantee a familiar fit. Record the seller's measurement chart, the unit shown and the measurement endpoints. For clothing, identify whether width is measured flat and whether a chest figure is a half-width or circumference. For shoes, distinguish the printed size from foot length, insole length and internal shoe length; they are related but not interchangeable. Convert centimetres and millimetres only with transparent arithmetic, and retain the original value beside the conversion. Compare the listing with a personally owned item measured in the same way. If the chart omits a decisive field, write a targeted question rather than filling the gap with a generic conversion table. A useful line reads: seller label 43; chart foot-length range as displayed; buyer comparison method; unresolved tolerance. It does not say 'EU 43 always fits.' This keeps the decision evidence-based and prevents translation from becoming a fit guarantee."],
      ["Prepare German recipient fields as structured data", "Keep private address information in the buyer's own record, never in a public post or shared spreadsheet. For a normal German house address, prepare separate fields for recipient name, street, house number, any necessary address addition, five-digit postal code, locality, country and a reachable contact method if the live form requires one. Deutsche Post guidance places the recipient name above street and house number, followed by postal code and locality. DHL also warns that a missing or incorrect street, house number, postal code or recognizable recipient name can cause a return. Treat those points as address-quality checks, not as a guarantee that an international parcel will be delivered. Do not force a Packstation or post-office format into an ordinary home-address field. Those services have special requirements and may not be supported by the selected international carrier. Use them only when the live route explicitly accepts the format and the buyer has the required account identifiers."],
      ["Run a two-stage review before each payment", "Joyagoo's current shopping guidance separates product payment from the later international-parcel step. Use that separation as two review gates. Before product payment, compare the live item title, source destination, selected color, size, version, quantity, seller note and Chinese domestic-delivery field with the working record. If the page redirects, an option disappears or the order summary changes, stop and update the record. Do not assume a saved link or translated label is still current. Before parcel payment, reopen the recipient record and compare it with the address preview, destination, product list and any live restrictions shown for the actual parcel. Shipping price, route availability, billable weight, insurance and delivery estimate belong to this second gate and must be read from the current account. A field is complete only when it matches the live summary; a blank or inferred field remains an open question. This procedure reduces silent substitutions without pretending to eliminate seller, carrier or customs risk."],
      ["Use status changes as evidence checkpoints", "The official order-status guide describes stages including payment pending, order processing, purchased, seller sent, stock arrived, QC completed and stored in warehouse. Save the exact status and timestamp when it changes. Each stage answers a different question: purchased supports that the buying step occurred; seller sent supports that the seller dispatched toward the warehouse; stock arrived supports warehouse receipt; QC completed makes the received-item evidence available for review. None of those labels guarantees the next event by a fixed time. At QC, compare the warehouse item with the four-field option record before studying workmanship. Confirm product identity, visible color, size label, version cues, quantity and included parts. If a measurement or label is decisive and unclear, write one targeted request using both the original term and the German explanation. Preserve the reply with its date. The result is a traceable chain from seller wording to submitted option to received-item evidence, not a collection of disconnected screenshots."],
      ["Finish with a compact handoff checklist", "Before closing the file, verify twelve items: current product destination saved; check date recorded; original title preserved; color exact; size system named; measurement basis recorded; version unambiguous; quantity and pack contents separated; seller note copied; product-stage summary matched; private German address fields validated; and unresolved questions clearly marked. Add a short decision line: proceed, wait for clarification, choose another option or remove the item. Do not write 'verified' when only some fields were checked. If the file will be shared with support, remove unrelated products, payment data, full addresses and account identifiers; include only the evidence needed for the specific question. Recheck the live interface before every consequential action because languages, currencies, listings and operational fields can change. A good Joyagoo Germany guide does not predict the cheapest route or fastest delivery. It gives the buyer a disciplined, language-safe record that makes product and destination choices reviewable before money or a parcel moves."],
    ],
    sources,
  },
  zh: {
    title: "Joyagoo 德国使用指南：建立可核对的目的地下单记录",
    description: "整理商品规格、尺寸、德国地址字段和可复查的下单记录，不猜测运费、税费或送达时间。",
    updated: "2026年9月8日",
    read: "阅读约14分钟",
    sections: [
      ["先界定“目的地准备完成”", "“目的地准备完成”并不表示某件商品一定能走某条德国线路，而是指买家有一份工作记录，能把商品、规格和收件信息准确带入当前 Joyagoo 流程，而不依赖记忆。Joyagoo 当前公开界面提供德语和 EUR 显示货币，官方购物指引要求付款前选择颜色、尺码和数量。这些功能方便阅读，但不会锁定商品页面、固定汇率，也不能证明包裹符合德国线路条件。先写清范围：记录商品身份，保留卖家原始规格文字，说明买家的选择，并为之后验证地址字段做准备。运费、海关、税费和时效应留到实时包裹页面出现当前数据后再判断。这样，语言记录就不会被误写成没有依据的价格承诺。"],
      ["德语说明旁保留原始文字", "机器翻译可以帮助理解方向，但规格选择器属于下单指令，不是普通文案。翻译前先保存卖家页面上可见的完整原文。第一列放原词，第二列放德语工作含义，第三列写支撑这个解释的证据，例如规格图片、尺寸表、型号、卖家说明或订单中的明确回复。如果仍有两种合理解释，就标记为“未解决”，不要挑选看起来更吸引人的含义。数字、型号后缀、材料比例和版本名应保持原样，除非来源本身改变。不要把型号后缀翻成颜色，也不要把包装数量当作尺码。目标不是写出漂亮的德语，而是让另一人能逐字对照当前商品页，并看清哪些地方仍有不确定性。"],
      ["把颜色、尺码、版本和数量分开", "即使卖家把多个规格写在同一行，也应拆成四个独立字段。颜色要记录准确选项文字和通俗说明，但缩略图只是视觉线索，灯光和图像处理可能改变观感。尺码要保存 CN、EU、UK、US 或卖家自定义体系，并写明用于比较的实际尺寸。版本记录型号、批次、材料、包装类型或其他商品差异。数量要同时写下单单位数和每个单位包含几件；“两件套”在结账时仍可能选择数量一。不要把页面最低价当作所选规格的价格证明，应在选择后核对当前订单摘要。最终记录即使没有图片也应读得懂：准确颜色文字；尺码标签与测量依据；版本标识；下单数量与每单位件数。"],
      ["使用测量值，不虚构尺码换算", "德国买家熟悉 EU 尺码，但出现 EU 数字不代表一定符合熟悉的版型。保存卖家尺寸表、显示单位和测量起止点。服装要说明宽度是否平铺测量，胸围数字是半宽还是周长。鞋类要区分标注尺码、脚长、鞋垫长和鞋内长，它们相关但不能互换。厘米与毫米换算要写出透明算法，并保留原值。用同一方法测量自己已有且合身的商品，再进行比较。如果尺寸表缺少关键字段，提出有针对性的问题，不要用通用换算表填补空白。有效记录可以写：卖家标签 43、页面展示的脚长范围、个人对比方法、尚未确认的误差；不能写成“EU 43 一定合脚”。这样才能让翻译保持证据属性，而不是变成合身保证。"],
      ["把德国收件信息拆成结构化字段", "完整地址只能保存在买家自己的私密记录里，绝不能放进公开帖子或共享表格。普通德国住宅地址应分开准备：收件人姓名、街道、门牌号、必要的地址补充、五位邮编、城市、国家，以及实时表单要求时可联系的方式。Deutsche Post 的规则把收件人放在街道和门牌号之上，下一行是邮编和城市；DHL 也提示，街道、门牌号、邮编错误或缺失，或收件人姓名无法识别，都可能导致退回。这些是地址质量检查，不是国际包裹必然送达的保证。不要把 Packstation 或邮局自提格式强行塞进普通住宅地址字段；它们有专门要求，也未必被所选国际承运商接受。只有实时线路明确支持且买家具备相应账户标识时才使用。"],
      ["在两次付款前分别复核", "Joyagoo 当前购物指引把商品付款与后续国际包裹阶段分开，因此可设置两个检查门。商品付款前，用工作记录逐项核对实时标题、来源目标页、颜色、尺码、版本、数量、卖家备注和中国境内运费字段。页面发生跳转、规格消失或订单摘要变化时，应停止并更新记录，不能假设旧链接或旧译名仍有效。包裹付款前，再用收件记录核对地址预览、目的地、商品清单，以及真实包裹页面显示的限制。运价、线路可用性、计费重量、保险和预计时效只属于第二阶段，必须以当前账户为准。字段只有与实时摘要一致才算完成；空白或推断内容仍是待解决问题。这个流程能减少无声替换，但不会假装消除卖家、承运商或海关风险。"],
      ["把状态变化作为证据节点", "官方订单状态说明列出待付款、处理中、已购买、卖家已发货、到仓、QC 完成和已入库等阶段。每次变化都保存准确状态和时间。各状态回答的问题不同：已购买说明采购步骤发生；卖家已发货说明商品正前往仓库；到仓说明仓库收到；QC 完成表示到货证据可以审核。任何状态都不保证下一步在固定时间发生。审核 QC 时，先用四字段规格记录确认商品身份、可见颜色、尺码标签、版本线索、数量和配件，再检查做工。关键尺寸或标签不清楚时，用原始词加德语说明写一个明确请求，并保存带日期的回复。最终形成从卖家文字到下单选择再到到货证据的链条，而不是一堆彼此无关的截图。"],
      ["用简洁交接清单收尾", "关闭记录前确认十二项：保存当前商品目标页；记录核查日期；保留原始标题；颜色准确；尺码体系明确；测量依据已写；版本无歧义；数量与套装件数分开；卖家备注已复制；商品阶段摘要一致；德国私密地址字段已验证；未解决问题有清楚标记。再写一行决定：继续、等待解释、改选规格或移除商品。只核对部分字段时，不要写“已验证”。如果要把记录发给客服，应删除无关商品、付款数据、完整地址和账户标识，只保留解决当前问题所需的证据。每次关键操作前都重新查看实时界面，因为语言、货币、商品和流程字段会变化。好的德国指南不预测最低运费或最快送达，而是提供一份语言安全、可复查的决定记录。"],
    ],
    sources,
  },
  de: {
    title: "Joyagoo Deutschland: Einen versandbereiten Bestellnachweis aufbauen",
    description: "Produktoptionen, Maße und deutsche Adressfelder nachvollziehbar vorbereiten – ohne Fracht, Steuern oder Laufzeiten zu erraten.",
    updated: "8. September 2026",
    read: "14 Min. Lesezeit",
    sections: [
      ["Was „zielbereit“ hier bedeutet", "Ein zielbereiter Datensatz ist keine Zusage, dass ein Produkt über eine bestimmte Route nach Deutschland versandt werden kann. Er ist eine Arbeitsakte, mit der Produkt, Variante und Empfängerdaten ohne Gedächtnislücken in den aktuellen Joyagoo-Ablauf übertragen werden. Die öffentliche Oberfläche bietet derzeit Deutsch und EUR als Anzeigewährung; die Einkaufsanleitung verlangt vor der Zahlung Farbe, Größe und Menge. Das erleichtert die Bedienung, friert aber weder Angebot noch Wechselkurs ein und beweist keine Routenzulassung. Formuliere deshalb den Zweck: Produkt identifizieren, ursprüngliche Optionsbegriffe bewahren, die beabsichtigte Wahl erklären und Adressfelder für die spätere Prüfung vorbereiten. Fracht, Zoll, Steuern und Laufzeit bleiben außerhalb dieser Akte, bis der aktuelle Paketbildschirm belastbare Angaben zeigt. So wird aus einer Sprachhilfe kein unbelegtes Kostenversprechen."],
      ["Originalbegriff und deutsche Notiz nebeneinander", "Maschinelle Übersetzung hilft bei der Orientierung, doch ein Variantenfeld ist eine Bestellanweisung. Speichere zuerst den vollständig sichtbaren Verkäufertext. Spalte eins enthält den Originalbegriff, Spalte zwei die deutsche Arbeitsbedeutung, Spalte drei den Beleg: Variantenbild, Maßtabelle, Modellnummer, Beschreibung oder dokumentierte Rückfrage. Bleiben zwei Deutungen möglich, markiere das Feld als offen, statt die attraktivere zu wählen. Zahlen, Modellcodes, Materialanteile und Versionsnamen bleiben unverändert, sofern sich die Quelle nicht ändert. Ein Suffix darf nicht versehentlich zur Farbe und eine Packungsmenge nicht zur Größe werden. Ziel ist keine elegante Übersetzung, sondern eine Notiz, die eine zweite Person Zeichen für Zeichen mit dem Live-Angebot vergleichen kann und in der Unsicherheit sichtbar bleibt."],
      ["Farbe, Größe, Version und Menge trennen", "Lege vier einzelne Felder an, auch wenn der Verkäufer alles in einer Zeile kombiniert. Farbe enthält den exakten Optionsnamen und eine verständliche Beschreibung; das Vorschaubild bleibt nur ein Hinweis, weil Licht und Bildbearbeitung den Eindruck verändern. Größe enthält das angegebene System – etwa CN, EU, UK, US oder eine Verkäuferkennzeichnung – und die Vergleichsmaße. Version erfasst Modell, Ausgabe, Material, Packungsart oder eine andere Produktabgrenzung. Menge erfasst Bestelleinheiten und Inhalt je Einheit; ein Zweier-Set kann an der Kasse trotzdem Menge eins sein. Der niedrigste Seitenpreis ist kein Beleg für die gewählte Variante. Prüfe stattdessen nach der Auswahl die aktuelle Zusammenfassung. Die fertige Zeile muss ohne Bild verständlich sein: Farbtext; Größenlabel samt Messbasis; Versionskennung; Bestellmenge und Stückzahl je Einheit."],
      ["Messen, ohne Größen umzurechnen", "Eine EU-Zahl wirkt vertraut, garantiert aber keine vertraute Passform. Speichere Maßtabelle, Einheit und Messpunkte. Bei Kleidung muss klar sein, ob flach gemessen wird und ob ein Brustwert halbe Breite oder Umfang bedeutet. Bei Schuhen sind aufgedruckte Größe, Fußlänge, Einlegesohlenlänge und Innenlänge zu unterscheiden. Rechne Zentimeter und Millimeter nur transparent um und behalte den Originalwert. Vergleiche mit einem eigenen, gut passenden Artikel, der auf dieselbe Weise gemessen wurde. Fehlt ein entscheidendes Maß, formuliere eine gezielte Frage, statt die Lücke mit einer allgemeinen Tabelle zu füllen. Ein brauchbarer Eintrag nennt Verkäufergröße 43, den angezeigten Fußlängenbereich, die Vergleichsmethode und eine offene Toleranz. Er behauptet nicht, EU 43 passe immer. So bleibt Übersetzung Beleg und wird nicht zur Passformgarantie."],
      ["Deutsche Empfängerfelder strukturiert vorbereiten", "Private Adressdaten gehören ausschließlich in die eigene Akte, nie in öffentliche Beiträge oder geteilte Tabellen. Für eine normale Hausanschrift werden Empfängername, Straße, Hausnummer, nötiger Adresszusatz, fünfstellige Postleitzahl, Ort, Land und – falls im Live-Formular verlangt – eine erreichbare Kontaktmöglichkeit getrennt erfasst. Deutsche Post ordnet den Namen über Straße und Hausnummer sowie darunter Postleitzahl und Ort an. DHL weist darauf hin, dass fehlende oder falsche Straße, Hausnummer, Postleitzahl oder ein nicht erkennbarer Empfängername zur Rücksendung führen können. Das sind Qualitätsprüfungen, keine Zustellgarantie. Eine Packstation oder Postfiliale darf nicht wie eine gewöhnliche Hausanschrift eingetragen werden; dafür gelten besondere Felder und Kennungen, die nicht jede internationale Route akzeptiert. Nutze sie nur, wenn die aktuelle Route das Format ausdrücklich unterstützt und die erforderlichen Kundendaten vorhanden sind."],
      ["Zwei Prüfungen vor den Zahlungen", "Die aktuelle Joyagoo-Anleitung trennt Produktzahlung und späteren internationalen Paketvorgang. Nutze diese Trennung als zwei Kontrollpunkte. Vor der Produktzahlung vergleichst du Live-Titel, Zielseite, Farbe, Größe, Version, Menge, Verkäuferhinweis und chinesische Inlandszustellung mit der Akte. Bei Weiterleitung, verschwundener Option oder geänderter Zusammenfassung wird gestoppt und aktualisiert. Gespeicherte Links und übersetzte Bezeichnungen sind nicht automatisch aktuell. Vor der Paketzahlung vergleichst du Empfängerdaten mit Adressvorschau, Ziel, Warenliste und den für das tatsächliche Paket sichtbaren Einschränkungen. Frachtpreis, Routenverfügbarkeit, Abrechnungsgewicht, Versicherung und Laufzeitschätzung gehören nur hierher und müssen live gelesen werden. Ein Feld ist erst vollständig, wenn es mit der aktuellen Zusammenfassung übereinstimmt; Leerstellen und Annahmen bleiben offene Fragen."],
      ["Statusänderungen als Belegpunkte", "Die offizielle Statushilfe nennt unter anderem ausstehende Zahlung, Bearbeitung, gekauft, vom Verkäufer versandt, im Lager eingetroffen, QC abgeschlossen und eingelagert. Speichere genauen Wortlaut und Zeitstempel. Jeder Status beantwortet eine andere Frage: „gekauft“ belegt den Kaufschritt, „Verkäufer versandt“ die Absendung zum Lager, „eingetroffen“ den Wareneingang und „QC abgeschlossen“ die Verfügbarkeit der Artikelbelege. Keiner verspricht den nächsten Schritt zu einer festen Zeit. Vergleiche beim QC zuerst Produktidentität, sichtbare Farbe, Größenlabel, Versionsmerkmale, Menge und enthaltene Teile mit dem Vier-Felder-Datensatz, bevor du Verarbeitung bewertest. Ist ein entscheidendes Maß oder Etikett unklar, stelle eine gezielte Frage mit Originalbegriff und deutscher Erklärung und speichere die datierte Antwort. So entsteht eine nachvollziehbare Kette statt einer losen Screenshot-Sammlung."],
      ["Mit einer kompakten Übergabeliste abschließen", "Prüfe zwölf Punkte: aktuelle Produktadresse, Prüftag, Originaltitel, exakte Farbe, benanntes Größensystem, Messbasis, eindeutige Version, getrennte Menge und Packungsinhalt, Verkäuferhinweis, abgeglichene Produktzusammenfassung, geprüfte private Deutschland-Adresse und markierte offene Fragen. Ergänze eine Entscheidung: fortfahren, Klärung abwarten, andere Option wählen oder Artikel entfernen. Schreibe nicht „verifiziert“, wenn nur ein Teil kontrolliert wurde. Wird die Akte an den Support gegeben, entferne fremde Produkte, Zahlungsdaten, vollständige Adressen und Kontokennungen; übrig bleibt nur der nötige Beleg. Prüfe die Live-Oberfläche vor jeder wichtigen Aktion erneut, denn Sprachen, Währungen, Angebote und Felder können sich ändern. Ein guter Deutschland-Guide verspricht weder billigste Route noch schnellste Zustellung, sondern schafft einen sprachsicheren, überprüfbaren Arbeitsnachweis."],
    ],
    sources,
  },
  pl: {
    title: "Joyagoo dla Niemiec: przygotuj sprawdzalny zapis zamówienia",
    description: "Uporządkuj warianty, wymiary i niemieckie pola adresowe bez zgadywania frachtu, podatków ani czasu dostawy.",
    updated: "8 września 2026",
    read: "14 min czytania",
    sections: [
      ["Co oznacza gotowość do wysyłki", "Gotowy zapis nie gwarantuje, że produkt może skorzystać z określonej trasy do Niemiec. To roboczy dokument pozwalający przenieść produkt, wariant i dane odbiorcy do aktualnego procesu Joyagoo bez polegania na pamięci. Publiczny interfejs oferuje obecnie język niemiecki i EUR jako walutę wyświetlania, a instrukcja zakupowa wymaga wyboru koloru, rozmiaru i ilości przed płatnością. Ułatwia to odczyt, ale nie zamraża oferty ani kursu i nie potwierdza dostępności trasy. Zapisz zakres: identyfikacja produktu, zachowanie oryginalnych nazw opcji, objaśnienie wyboru kupującego i przygotowanie pól adresowych. Fracht, cło, podatki i czas pozostają poza dokumentem, dopóki bieżący ekran paczki nie pokaże danych. Dzięki temu pomoc językowa nie staje się obietnicą kosztu."],
      ["Zachowaj oryginał obok niemieckiej notatki", "Tłumaczenie maszynowe pomaga się zorientować, lecz pole wariantu jest instrukcją zamówienia. Najpierw zapisz cały widoczny tekst sprzedawcy. W pierwszej kolumnie umieść oryginał, w drugiej niemieckie znaczenie robocze, a w trzeciej dowód: zdjęcie opcji, tabelę wymiarów, numer modelu, opis lub odpowiedź sprzedawcy. Jeśli możliwe są dwa znaczenia, oznacz pole jako nierozstrzygnięte. Nie zmieniaj liczb, kodów, procentów materiału ani nazw wersji. Nie tłumacz sufiksu modelu jako koloru ani liczby sztuk jako rozmiaru. Celem nie jest elegancki niemiecki, lecz notatka, którą inna osoba porówna znak po znaku z aktualną ofertą i zobaczy pozostałą niepewność."],
      ["Rozdziel kolor, rozmiar, wersję i ilość", "Utwórz cztery pola, nawet gdy sprzedawca łączy je w jednym wierszu. Kolor zawiera dokładną nazwę i zwykły opis, ale miniatura pozostaje wskazówką, bo światło zmienia wygląd. Rozmiar zachowuje system CN, EU, UK, US lub oznaczenie sprzedawcy oraz pomiary. Wersja obejmuje model, edycję, materiał, typ opakowania lub inną różnicę. Ilość zapisuje jednostki zamówienia i zawartość każdej jednostki; zestaw dwóch sztuk może mieć przy kasie ilość jeden. Najniższa cena nie dowodzi ceny wybranego wariantu — po wyborze sprawdź podsumowanie. Gotowy wiersz ma działać bez zdjęcia: dokładny kolor; etykieta rozmiaru i podstawa pomiaru; identyfikator wersji; ilość zamówienia i liczba sztuk w jednostce."],
      ["Mierz bez wymyślania konwersji", "Znany numer EU nie gwarantuje znanego dopasowania. Zapisz tabelę, jednostkę i punkty pomiaru. Przy odzieży ustal, czy mierzono na płasko oraz czy obwód klatki oznacza szerokość połówkową czy pełny obwód. Przy obuwiu rozróżniaj rozmiar z etykiety, długość stopy, wkładki i wnętrza. Przeliczaj centymetry i milimetry jawnie, zachowując oryginał. Porównuj z własną dobrze dopasowaną rzeczą mierzoną tak samo. Jeśli brakuje kluczowej wartości, zadaj konkretne pytanie zamiast używać ogólnej tabeli. Dobry zapis podaje rozmiar sprzedawcy 43, widoczny zakres długości stopy, metodę porównania i nieustaloną tolerancję; nie twierdzi, że EU 43 zawsze pasuje. Tłumaczenie pozostaje wtedy dowodem, a nie gwarancją."],
      ["Przygotuj niemieckie pola odbiorcy", "Prywatny adres przechowuj wyłącznie we własnym dokumencie, nigdy w publicznym poście ani arkuszu. Dla zwykłego adresu domowego rozdziel imię i nazwisko, ulicę, numer domu, potrzebne uzupełnienie, pięciocyfrowy kod, miejscowość, kraj i kontakt wymagany przez aktywny formularz. Deutsche Post umieszcza nazwę odbiorcy nad ulicą i numerem, a niżej kod i miejscowość. DHL ostrzega, że brak lub błąd ulicy, numeru, kodu albo nierozpoznawalna nazwa odbiorcy mogą spowodować zwrot. To kontrola jakości adresu, nie obietnica doręczenia przesyłki międzynarodowej. Nie wpisuj formatu Packstation lub placówki jak zwykłego adresu; wymaga specjalnych pól i identyfikatorów, których wybrany przewoźnik może nie obsługiwać. Używaj go tylko przy wyraźnym wsparciu trasy."],
      ["Dwie bramki kontroli przed płatnością", "Aktualna instrukcja Joyagoo oddziela płatność za produkt od późniejszej paczki międzynarodowej. Przed pierwszą płatnością porównaj tytuł, stronę docelową, kolor, rozmiar, wersję, ilość, notatkę sprzedawcy i dostawę krajową w Chinach z dokumentem. Po przekierowaniu, zniknięciu opcji lub zmianie podsumowania zatrzymaj proces i zaktualizuj zapis. Stary link ani tłumaczenie nie są automatycznie aktualne. Przed płatnością za paczkę porównaj rekord odbiorcy z podglądem adresu, krajem, listą produktów i ograniczeniami widocznymi dla rzeczywistej paczki. Cena, trasa, waga rozliczeniowa, ubezpieczenie i szacowany czas należą do drugiej bramki i muszą pochodzić z aktywnego konta. Pole jest ukończone dopiero po zgodności z podsumowaniem; puste i założone dane pozostają pytaniami."],
      ["Statusy jako punkty dowodowe", "Oficjalna pomoc wymienia m.in. oczekiwanie na płatność, przetwarzanie, zakup, wysłanie przez sprzedawcę, przyjęcie, zakończenie QC i magazynowanie. Zapisuj dokładny status i czas. Zakup potwierdza krok kupna, wysłanie — ruch do magazynu, przyjęcie — odbiór, a QC — dostępność dowodów otrzymanego produktu. Żaden status nie gwarantuje następnego zdarzenia w stałym terminie. Podczas QC najpierw porównaj tożsamość, widoczny kolor, etykietę rozmiaru, wersję, ilość i części z czterema polami, a dopiero potem wykonanie. Niejasny kluczowy wymiar lub etykietę wyjaśnij jednym pytaniem zawierającym oryginalny termin i niemieckie objaśnienie. Zachowaj odpowiedź i datę, tworząc ciąg dowodów zamiast luźnych zrzutów."],
      ["Zamknij dokument krótką listą", "Sprawdź dwanaście punktów: aktualny adres produktu, data kontroli, oryginalny tytuł, dokładny kolor, nazwany system rozmiarów, podstawa pomiaru, jednoznaczna wersja, oddzielona ilość i zawartość zestawu, notatka sprzedawcy, zgodne podsumowanie produktu, sprawdzone prywatne pola adresu w Niemczech oraz zaznaczone pytania. Dodaj decyzję: kontynuuj, czekaj na wyjaśnienie, wybierz inną opcję albo usuń produkt. Nie pisz „zweryfikowano”, gdy sprawdzono tylko część. Przed wysłaniem do wsparcia usuń inne produkty, dane płatnicze, pełny adres i identyfikatory konta. Przed ważną czynnością ponownie sprawdź interfejs, ponieważ języki, waluty i pola się zmieniają. Dobry przewodnik daje bezpieczny językowo, kontrolowalny zapis, a nie obietnicę ceny czy czasu."],
    ],
    sources,
  },
  es: {
    title: "Joyagoo para Alemania: crea un registro de pedido listo para el destino",
    description: "Prepara opciones, medidas y campos de dirección alemana sin inventar flete, impuestos ni plazos.",
    updated: "8 de septiembre de 2026",
    read: "14 min de lectura",
    sections: [
      ["Qué significa estar listo para el destino", "Un registro listo para el destino no promete que un producto pueda usar una ruta concreta hacia Alemania. Es un archivo de trabajo que permite trasladar artículo, variante y datos del destinatario al flujo actual de Joyagoo sin depender de la memoria. La interfaz pública ofrece actualmente alemán y EUR como moneda de visualización, y la guía de compra indica elegir color, talla y cantidad antes de pagar. Esto facilita la lectura, pero no congela el anuncio ni el cambio y tampoco demuestra la elegibilidad de una ruta. Define el alcance: identificar el producto, conservar el texto original de las opciones, explicar la elección del comprador y preparar los campos de dirección para revisarlos después. Deja flete, aduanas, impuestos y plazos fuera hasta que la pantalla activa del paquete muestre datos actuales. Así una ayuda lingüística no se convierte en una promesa de costes sin respaldo."],
      ["Conserva el original junto a la nota alemana", "La traducción automática orienta, pero un selector de variante es una instrucción de pedido. Guarda primero todo el texto visible del vendedor. Coloca el término original en una columna, su significado de trabajo en alemán en otra y la evidencia en una tercera: imagen de opción, tabla de medidas, modelo, descripción o aclaración documentada. Si quedan dos interpretaciones posibles, marca el campo como pendiente. Mantén números, códigos, porcentajes y nombres de versión sin cambios. No conviertas un sufijo de modelo en color ni el número de piezas en talla. El objetivo no es redactar alemán elegante, sino crear una nota que otra persona pueda comparar carácter por carácter con la ficha activa y que muestre claramente la incertidumbre restante."],
      ["Separa color, talla, versión y cantidad", "Crea cuatro campos independientes aunque el vendedor los combine. Color conserva el nombre exacto y una descripción común; la miniatura solo es una pista porque la luz altera la apariencia. Talla guarda el sistema CN, EU, UK, US o propio del vendedor y las medidas usadas. Versión recoge modelo, edición, material, tipo de paquete u otra diferencia. Cantidad distingue unidades de pedido y piezas por unidad; un conjunto de dos puede comprarse con cantidad uno. El precio más bajo no demuestra el precio de la variante elegida: revisa el resumen tras seleccionar. La línea final debe entenderse sin imagen: texto exacto de color; etiqueta y base de medida; identificador de versión; cantidad pedida y piezas por unidad."],
      ["Usa medidas sin inventar conversiones", "Un número EU familiar no garantiza un ajuste familiar. Guarda la tabla, la unidad y los extremos de medición. En ropa aclara si se mide en plano y si el pecho es media anchura o contorno. En calzado separa talla impresa, longitud del pie, plantilla y espacio interior. Convierte centímetros y milímetros con una operación visible y conserva el valor original. Compara con una prenda propia que ajuste bien y esté medida igual. Si falta un dato decisivo, formula una pregunta concreta en vez de completar el hueco con una tabla genérica. Un registro útil dice talla del vendedor 43, rango de pie mostrado, método de comparación y tolerancia pendiente; no afirma que EU 43 siempre encaje. Así la traducción sigue siendo evidencia y no garantía de ajuste."],
      ["Estructura los campos del destinatario alemán", "Guarda la dirección privada solo en el registro del comprador, nunca en publicaciones o hojas compartidas. Para un domicilio alemán normal separa nombre, calle, número, complemento necesario, código postal de cinco dígitos, localidad, país y contacto si el formulario activo lo exige. Deutsche Post sitúa el destinatario sobre calle y número, seguido de código y localidad. DHL advierte que una calle, número o código ausente o incorrecto, o un nombre no reconocible, puede causar devolución. Son comprobaciones de calidad, no una garantía de entrega internacional. No fuerces un formato Packstation u oficina postal en campos de domicilio; requiere datos especiales que la ruta elegida puede no aceptar. Úsalo solo cuando el flujo actual lo admita expresamente y el comprador tenga los identificadores necesarios."],
      ["Haz dos revisiones antes de pagar", "La guía actual separa el pago del producto del paquete internacional posterior. Antes del primer pago compara título activo, destino, color, talla, versión, cantidad, nota y transporte nacional chino con el registro. Si hay redirección, desaparece una opción o cambia el resumen, detente y actualiza. Un enlace guardado o una traducción antigua no siguen vigentes por defecto. Antes de pagar el paquete, compara el registro del destinatario con la vista previa de dirección, país, lista de artículos y restricciones del paquete real. Precio, disponibilidad de ruta, peso facturable, seguro y plazo estimado pertenecen a esta segunda puerta y deben leerse en la cuenta actual. Un campo solo está completo si coincide con el resumen; vacíos e inferencias siguen siendo preguntas abiertas. El método reduce sustituciones silenciosas sin negar riesgos de vendedor, transportista o aduana."],
      ["Usa los estados como puntos de evidencia", "La guía oficial incluye pago pendiente, procesamiento, comprado, enviado por el vendedor, llegada, QC completado y almacenado. Guarda el texto exacto y la hora. Comprado acredita el paso de compra; enviado acredita el movimiento hacia el almacén; llegada, la recepción; y QC, la disponibilidad de pruebas del artículo recibido. Ningún estado promete el siguiente evento a una hora fija. En QC compara primero identidad, color visible, etiqueta de talla, señales de versión, cantidad y piezas incluidas con el registro de cuatro campos; después revisa acabados. Si una medida o etiqueta decisiva no se ve, plantea una solicitud concreta con término original y explicación alemana, y conserva la respuesta fechada. Así se forma una cadena desde el texto del vendedor hasta la opción enviada y la evidencia recibida, no una carpeta de capturas desconectadas."],
      ["Termina con una lista de entrega compacta", "Confirma doce elementos: destino actual del producto; fecha de revisión; título original; color exacto; sistema de talla; base de medida; versión inequívoca; cantidad y contenido separados; nota copiada; resumen de producto coincidente; campos privados de dirección alemana revisados; dudas marcadas. Añade una decisión: seguir, esperar aclaración, cambiar opción o retirar artículo. No escribas “verificado” si solo comprobaste una parte. Para compartir con soporte elimina otros productos, pagos, dirección completa e identificadores de cuenta; incluye solo la prueba necesaria. Revisa el flujo vivo antes de cada acción importante porque idiomas, monedas, anuncios y campos cambian. Una buena guía para Alemania no promete la ruta más barata ni la entrega más rápida: ofrece un registro lingüísticamente seguro y revisable."],
    ],
    sources,
  },
  it: {
    title: "Joyagoo per la Germania: crea un registro d’ordine pronto per la destinazione",
    description: "Prepara opzioni, misure e campi dell’indirizzo tedesco senza inventare costi, imposte o tempi.",
    updated: "8 settembre 2026",
    read: "14 min di lettura",
    sections: [
      ["Cosa significa essere pronti per la destinazione", "Un registro pronto per la destinazione non promette che un prodotto possa usare una specifica rotta verso la Germania. È un file di lavoro per trasferire articolo, variante e dati del destinatario nel flusso Joyagoo corrente senza affidarsi alla memoria. L’interfaccia pubblica offre attualmente il tedesco e l’EUR come valuta visualizzata; la guida acquisti richiede colore, taglia e quantità prima del pagamento. Ciò aiuta la lettura, ma non blocca inserzione o cambio e non prova l’idoneità di una rotta. Definisci lo scopo: identificare il prodotto, conservare i termini originali, spiegare la scelta e preparare i campi dell’indirizzo. Lascia trasporto, dogana, imposte e tempi fuori dal registro finché la schermata attiva del pacco non mostra dati correnti. Una guida linguistica non diventa così una promessa di costo priva di base."],
      ["Mantieni l’originale accanto alla nota tedesca", "La traduzione automatica orienta, ma un selettore di variante è un’istruzione d’ordine. Salva prima tutto il testo visibile del venditore. Metti il termine originale nella prima colonna, il significato operativo tedesco nella seconda e la prova nella terza: immagine dell’opzione, tabella misure, modello, descrizione o chiarimento documentato. Se restano due interpretazioni, segna il campo come aperto. Non cambiare numeri, codici, percentuali o nomi di versione. Non trasformare un suffisso modello in colore né il numero di pezzi in taglia. Lo scopo non è un tedesco elegante, ma una nota che un’altra persona possa confrontare carattere per carattere con l’inserzione attiva e che renda visibile ogni incertezza."],
      ["Separa colore, taglia, versione e quantità", "Crea quattro campi anche se il venditore li unisce. Colore conserva nome esatto e descrizione semplice; la miniatura resta un indizio perché luce e trattamento cambiano l’aspetto. Taglia salva il sistema CN, EU, UK, US o del venditore e le misure. Versione registra modello, edizione, materiale, confezione o altra differenza. Quantità distingue unità ordinate e pezzi per unità; un set da due può avere quantità uno al checkout. Il prezzo più basso non prova quello della variante: controlla il riepilogo dopo la selezione. La riga finale deve funzionare senza immagine: testo colore; etichetta e base di misura; identificatore versione; quantità ordinata e pezzi per unità."],
      ["Usa misure senza inventare conversioni", "Un numero EU familiare non garantisce una vestibilità familiare. Salva tabella, unità e punti di misura. Per gli abiti chiarisci se la misura è in piano e se il torace indica mezza larghezza o circonferenza. Per le scarpe distingui taglia stampata, lunghezza del piede, soletta e interno. Converti centimetri e millimetri in modo trasparente conservando l’originale. Confronta con un articolo proprio che veste bene e misurato nello stesso modo. Se manca un dato decisivo, fai una domanda mirata invece di usare una tabella generica. Un buon record indica etichetta 43, intervallo del piede mostrato, metodo di confronto e tolleranza aperta; non dice che EU 43 veste sempre. La traduzione resta una prova, non una garanzia."],
      ["Struttura i campi del destinatario tedesco", "Conserva l’indirizzo privato solo nel record personale, mai in post o fogli condivisi. Per una normale abitazione tedesca separa nome, via, numero civico, eventuale aggiunta, CAP a cinque cifre, località, paese e contatto se richiesto dal modulo attivo. Deutsche Post dispone il nome sopra via e numero e poi CAP e località. DHL avverte che via, numero o CAP mancanti o errati, o un nome non riconoscibile, possono causare il reso. Sono controlli di qualità, non garanzia di consegna internazionale. Non inserire Packstation o ufficio postale come normale domicilio: servono campi e identificatori speciali che la rotta scelta potrebbe non accettare. Usali solo se il flusso corrente li supporta espressamente e il compratore possiede i dati richiesti."],
      ["Esegui due controlli prima dei pagamenti", "La guida Joyagoo separa il pagamento del prodotto dal successivo pacco internazionale. Prima del primo pagamento confronta titolo, destinazione, colore, taglia, versione, quantità, nota e consegna nazionale cinese con il record. Se la pagina reindirizza, scompare un’opzione o cambia il riepilogo, fermati e aggiorna. Link salvati e traduzioni non sono automaticamente attuali. Prima di pagare il pacco, confronta il record destinatario con anteprima indirizzo, paese, articoli e restrizioni del pacco reale. Prezzo, rotta, peso fatturabile, assicurazione e stima dei tempi appartengono alla seconda verifica e vanno letti nel conto corrente. Un campo è completo solo se coincide con il riepilogo; vuoti e inferenze restano domande. Il metodo riduce sostituzioni silenziose senza negare i rischi di venditore, vettore e dogana."],
      ["Usa gli stati come punti di prova", "La guida ufficiale include pagamento in attesa, elaborazione, acquistato, spedito dal venditore, arrivato, QC completato e immagazzinato. Salva testo e orario esatti. Acquistato prova il passaggio d’acquisto; spedito il movimento verso il magazzino; arrivato la ricezione; QC la disponibilità delle prove del prodotto ricevuto. Nessuno garantisce il prossimo evento entro un’ora fissa. Al QC confronta prima identità, colore visibile, etichetta taglia, versione, quantità e parti incluse con i quattro campi, poi valuta la fattura. Se misura o etichetta decisive sono poco chiare, invia una richiesta mirata con termine originale e spiegazione tedesca e conserva la risposta datata. Nasce così una catena verificabile, non una raccolta di screenshot scollegati."],
      ["Chiudi con una lista di consegna compatta", "Controlla dodici elementi: destinazione prodotto corrente; data; titolo originale; colore esatto; sistema taglia; base di misura; versione chiara; quantità e contenuto separati; nota venditore; riepilogo prodotto coerente; campi privati dell’indirizzo tedesco verificati; domande segnate. Aggiungi la decisione: procedere, attendere chiarimento, cambiare opzione o rimuovere. Non scrivere “verificato” se hai controllato solo una parte. Per il supporto elimina altri prodotti, pagamenti, indirizzo completo e identificatori; condividi solo la prova necessaria. Ricontrolla l’interfaccia prima di ogni azione importante perché lingua, valuta e campi cambiano. Una buona guida non promette rotta economica o consegna rapida, ma fornisce un record sicuro e revisionabile."],
    ],
    sources,
  },
  fr: {
    title: "Joyagoo pour l’Allemagne : créer un dossier de commande prêt pour la destination",
    description: "Préparez options, mesures et champs d’adresse allemands sans inventer fret, taxes ni délais.",
    updated: "8 septembre 2026",
    read: "14 min de lecture",
    sections: [
      ["Définir la préparation à la destination", "Un dossier prêt pour la destination ne promet pas qu’un produit puisse emprunter une route précise vers l’Allemagne. C’est un fichier de travail permettant de transférer article, variante et données du destinataire dans le flux Joyagoo actuel sans dépendre de la mémoire. L’interface publique propose actuellement l’allemand et l’EUR comme devise d’affichage ; le guide d’achat demande couleur, taille et quantité avant paiement. Cela facilite la lecture, mais ne bloque ni annonce ni taux et ne prouve aucune admissibilité de route. Définissez le périmètre : identifier le produit, conserver les termes d’option d’origine, expliquer le choix et préparer les champs d’adresse. Laissez fret, douane, taxes et délais hors du dossier jusqu’à ce que l’écran actif du colis fournisse des données actuelles. Une aide linguistique ne devient donc pas une promesse de coût sans preuve."],
      ["Conserver l’original près de la note allemande", "La traduction automatique aide à s’orienter, mais un sélecteur de variante constitue une instruction. Enregistrez d’abord tout le texte visible du vendeur. Placez le terme original dans une colonne, le sens de travail allemand dans la deuxième et la preuve dans la troisième : image d’option, tableau de mesures, modèle, description ou clarification documentée. Si deux interprétations restent possibles, marquez le champ comme ouvert. Ne modifiez ni nombres, codes, pourcentages ni noms de version. Ne transformez pas un suffixe modèle en couleur ou un nombre de pièces en taille. Le but n’est pas une prose allemande élégante, mais une note qu’une autre personne peut comparer caractère par caractère à la fiche active tout en voyant l’incertitude restante."],
      ["Séparer couleur, taille, version et quantité", "Créez quatre champs même si le vendeur les regroupe. Couleur conserve le libellé exact et une description simple ; la vignette reste un indice puisque l’éclairage modifie l’apparence. Taille garde le système CN, EU, UK, US ou vendeur ainsi que les mesures. Version consigne modèle, édition, matière, conditionnement ou autre différence. Quantité distingue unités commandées et pièces par unité ; un lot de deux peut utiliser quantité un. Le prix minimal ne prouve pas celui de la variante choisie : vérifiez le récapitulatif après sélection. La ligne finale doit être lisible sans image : texte couleur exact ; étiquette et base de mesure ; identifiant version ; quantité commandée et pièces par unité."],
      ["Mesurer sans inventer de conversion", "Un numéro EU familier ne garantit pas une coupe familière. Conservez tableau, unité et points de mesure. Pour un vêtement, précisez mesure à plat et largeur ou circonférence de poitrine. Pour une chaussure, séparez taille imprimée, longueur du pied, semelle intérieure et longueur interne. Convertissez centimètres et millimètres de façon transparente en gardant l’original. Comparez avec un article personnel bien ajusté et mesuré de la même manière. Si une valeur décisive manque, posez une question ciblée au lieu d’utiliser une table générique. Un bon dossier indique étiquette vendeur 43, plage de pied affichée, méthode de comparaison et tolérance ouverte ; il ne dit pas que EU 43 convient toujours. La traduction demeure alors une preuve, pas une garantie."],
      ["Structurer les champs du destinataire allemand", "Gardez l’adresse privée uniquement dans le dossier personnel, jamais dans une publication ou un tableau partagé. Pour un domicile allemand normal, séparez nom, rue, numéro, complément nécessaire, code postal à cinq chiffres, localité, pays et contact si le formulaire actif l’exige. Deutsche Post place le nom au-dessus de la rue et du numéro, puis le code et la localité. DHL prévient qu’une rue, un numéro ou un code absent ou erroné, ou un nom non identifiable, peut entraîner un retour. Ce sont des contrôles de qualité, pas une garantie de livraison internationale. Ne forcez pas le format Packstation ou bureau de poste dans une adresse résidentielle ; il nécessite des champs et identifiants particuliers que la route peut refuser. Utilisez-le seulement si le flux actuel l’accepte explicitement."],
      ["Effectuer deux contrôles avant paiement", "Le guide Joyagoo sépare le paiement produit du colis international ultérieur. Avant le premier paiement, comparez titre actif, destination, couleur, taille, version, quantité, note et livraison intérieure chinoise au dossier. En cas de redirection, d’option disparue ou de résumé modifié, arrêtez et actualisez. Un lien ou une traduction enregistrés ne restent pas automatiquement valides. Avant le paiement du colis, comparez le dossier destinataire avec aperçu d’adresse, pays, produits et restrictions du colis réel. Prix, route, poids facturable, assurance et délai estimé appartiennent à ce second contrôle et doivent venir du compte actuel. Un champ n’est complet que s’il correspond au résumé ; blancs et déductions restent ouverts. Le processus réduit les substitutions silencieuses sans nier les risques vendeur, transporteur ou douane."],
      ["Utiliser les statuts comme jalons de preuve", "Le guide officiel comprend paiement en attente, traitement, acheté, envoyé par le vendeur, arrivé, QC terminé et stocké. Enregistrez libellé exact et heure. Acheté prouve l’étape d’achat ; envoyé, le départ vers l’entrepôt ; arrivé, la réception ; QC, la disponibilité des preuves de l’article reçu. Aucun ne promet l’événement suivant à heure fixe. Au QC, comparez d’abord identité, couleur visible, étiquette de taille, version, quantité et pièces incluses au dossier à quatre champs, puis la fabrication. Si une mesure ou étiquette décisive est floue, formulez une demande ciblée avec terme d’origine et explication allemande, puis gardez la réponse datée. Vous obtenez une chaîne traçable plutôt qu’un ensemble de captures sans lien."],
      ["Terminer par une liste de transmission compacte", "Vérifiez douze éléments : destination produit actuelle ; date ; titre original ; couleur exacte ; système de taille ; base de mesure ; version claire ; quantité et contenu séparés ; note vendeur ; résumé produit concordant ; champs privés d’adresse allemande contrôlés ; questions marquées. Ajoutez une décision : continuer, attendre une précision, changer d’option ou retirer. N’écrivez pas « vérifié » si seule une partie l’est. Pour le support, retirez autres produits, paiements, adresse complète et identifiants ; ne fournissez que la preuve utile. Revérifiez l’interface avant chaque action importante, car langues, devises, offres et champs changent. Un bon guide Allemagne ne promet ni route la moins chère ni livraison la plus rapide : il produit un dossier linguistiquement sûr et révisable."],
    ],
    sources,
  },
  pt: {
    title: "Joyagoo para a Alemanha: crie um registo de encomenda pronto para o destino",
    description: "Prepare opções, medidas e campos de morada alemães sem inventar frete, impostos ou prazos.",
    updated: "8 de setembro de 2026",
    read: "14 min de leitura",
    sections: [
      ["Defina o que significa estar pronto para o destino", "Um registo pronto para o destino não promete que um produto possa usar uma rota específica para a Alemanha. É um ficheiro de trabalho para transferir artigo, variante e dados do destinatário para o fluxo atual da Joyagoo sem depender da memória. A interface pública oferece atualmente alemão e EUR como moeda de apresentação, e o guia de compras pede cor, tamanho e quantidade antes do pagamento. Isto facilita a leitura, mas não congela anúncio ou câmbio e não prova elegibilidade de rota. Defina o âmbito: identificar o produto, preservar os termos originais, explicar a escolha e preparar os campos da morada. Deixe frete, alfândega, impostos e prazos fora até o ecrã ativo do pacote mostrar dados atuais. Assim, uma ajuda linguística não se torna uma promessa de custo sem prova."],
      ["Guarde o original junto da nota alemã", "A tradução automática orienta, mas um seletor de variante é uma instrução de compra. Primeiro guarde todo o texto visível do vendedor. Use uma coluna para o original, outra para o significado de trabalho em alemão e uma terceira para a prova: imagem da opção, tabela de medidas, modelo, descrição ou esclarecimento documentado. Se duas interpretações continuarem possíveis, marque o campo como aberto. Não altere números, códigos, percentagens nem nomes de versão. Não transforme um sufixo de modelo numa cor nem o número de peças num tamanho. O objetivo não é alemão elegante, mas uma nota que outra pessoa possa comparar carácter a carácter com a página ativa e que revele a incerteza restante."],
      ["Separe cor, tamanho, versão e quantidade", "Crie quatro campos mesmo quando o vendedor os combina. Cor conserva o nome exato e uma descrição simples; a miniatura é apenas pista porque a luz altera a aparência. Tamanho guarda o sistema CN, EU, UK, US ou do vendedor e as medidas usadas. Versão regista modelo, edição, material, embalagem ou outra diferença. Quantidade separa unidades encomendadas e peças por unidade; um conjunto de duas pode usar quantidade um. O preço mínimo não prova o da variante escolhida: confira o resumo depois da seleção. A linha final deve ser entendida sem imagem: texto exato da cor; etiqueta e base de medição; identificador da versão; quantidade pedida e peças por unidade."],
      ["Use medidas sem inventar conversões", "Um número EU familiar não garante um ajuste familiar. Guarde tabela, unidade e pontos de medição. Em roupa, esclareça se a medição é plana e se peito significa meia largura ou circunferência. Em calçado, distinga tamanho impresso, comprimento do pé, palmilha e interior. Converta centímetros e milímetros de forma transparente, mantendo o original. Compare com um artigo próprio que assente bem e seja medido do mesmo modo. Se faltar um valor decisivo, faça uma pergunta dirigida em vez de usar tabela genérica. Um bom registo indica etiqueta 43, intervalo de pé mostrado, método de comparação e tolerância aberta; não afirma que EU 43 serve sempre. A tradução permanece prova, não garantia."],
      ["Estruture os campos do destinatário alemão", "Mantenha a morada privada apenas no registo pessoal, nunca em publicações ou folhas partilhadas. Para uma residência alemã normal, separe nome, rua, número, complemento, código postal de cinco dígitos, localidade, país e contacto se o formulário ativo pedir. A Deutsche Post coloca o nome acima da rua e número e depois código e localidade. A DHL avisa que rua, número ou código ausentes ou errados, ou nome não reconhecível, podem causar devolução. São controlos de qualidade, não garantia de entrega internacional. Não use Packstation ou estação postal como morada comum; exigem campos e identificadores especiais que a rota pode não aceitar. Utilize-os apenas se o fluxo atual apoiar expressamente o formato e o comprador tiver os dados necessários."],
      ["Faça duas revisões antes dos pagamentos", "O guia atual separa pagamento do produto e pacote internacional posterior. Antes do primeiro pagamento, compare título, destino, cor, tamanho, versão, quantidade, nota e entrega doméstica chinesa com o registo. Se houver redirecionamento, desaparecer uma opção ou mudar o resumo, pare e atualize. Um link guardado ou uma tradução antiga não permanecem atuais automaticamente. Antes de pagar o pacote, compare o registo do destinatário com pré-visualização da morada, país, artigos e restrições do pacote real. Preço, rota, peso faturável, seguro e prazo estimado pertencem à segunda revisão e devem vir da conta atual. Um campo só fica completo quando coincide com o resumo; vazios e inferências permanecem perguntas. O método reduz substituições silenciosas sem negar riscos de vendedor, transportadora ou alfândega."],
      ["Use estados como pontos de prova", "O guia oficial inclui pagamento pendente, processamento, comprado, enviado pelo vendedor, chegada, QC concluído e armazenado. Guarde texto e hora exatos. Comprado prova a etapa da compra; enviado prova movimento para o armazém; chegada prova receção; QC disponibiliza provas do artigo recebido. Nenhum promete o próximo evento num prazo fixo. No QC, compare primeiro identidade, cor visível, etiqueta de tamanho, versão, quantidade e peças incluídas com os quatro campos; depois examine o acabamento. Se medida ou etiqueta decisivas estiverem pouco claras, faça um pedido específico com o termo original e a explicação alemã e guarde a resposta datada. Assim forma uma cadeia rastreável, não um conjunto de capturas desligadas."],
      ["Termine com uma lista compacta", "Confirme doze itens: destino atual do produto; data; título original; cor exata; sistema de tamanho; base da medição; versão clara; quantidade e conteúdo separados; nota do vendedor; resumo coincidente; campos privados da morada alemã verificados; dúvidas marcadas. Acrescente a decisão: prosseguir, aguardar, mudar opção ou remover. Não escreva “verificado” quando só parte foi revista. Para o apoio, remova outros produtos, pagamentos, morada completa e identificadores; partilhe apenas a prova necessária. Reveja a interface antes de cada ação importante porque idiomas, moedas, anúncios e campos mudam. Um bom guia para a Alemanha não promete a rota mais barata nem a entrega mais rápida: oferece um registo seguro na linguagem e auditável."],
    ],
    sources,
  },
  ro: {
    title: "Joyagoo pentru Germania: creează o fișă de comandă pregătită pentru destinație",
    description: "Pregătește opțiunile, măsurile și câmpurile adresei germane fără estimări inventate de cost sau timp.",
    updated: "8 septembrie 2026",
    read: "14 min de citit",
    sections: [
      ["Definește ce înseamnă pregătit pentru destinație", "O fișă pregătită nu promite că produsul poate folosi o anumită rută spre Germania. Este un document de lucru pentru transferul articolului, variantei și datelor destinatarului în fluxul Joyagoo actual, fără memorie. Interfața publică oferă acum limba germană și EUR ca monedă afișată, iar ghidul cere culoare, mărime și cantitate înainte de plată. Acestea ajută lectura, dar nu îngheață oferta sau cursul și nu dovedesc eligibilitatea rutei. Notează scopul: identificarea produsului, păstrarea termenilor originali, explicarea alegerii și pregătirea câmpurilor adresei. Lasă transportul, vama, taxele și timpul în afara fișei până când ecranul activ al coletului oferă date curente. Astfel, ajutorul lingvistic nu devine o promisiune de cost fără suport."],
      ["Păstrează originalul lângă nota germană", "Traducerea automată ajută orientarea, dar selectorul de variantă este instrucțiune. Salvează întâi textul complet al vânzătorului. Pune originalul în prima coloană, sensul german de lucru în a doua și dovada în a treia: imaginea opțiunii, tabelul, modelul, descrierea sau clarificarea documentată. Dacă două sensuri rămân posibile, marchează câmpul nerezolvat. Nu modifica numere, coduri, procente sau nume de versiune. Nu transforma un sufix de model în culoare ori numărul de piese în mărime. Scopul nu este o germană elegantă, ci o notă comparabilă caracter cu caracter cu oferta live, care arată incertitudinea rămasă."],
      ["Separă culoarea, mărimea, versiunea și cantitatea", "Creează patru câmpuri chiar dacă vânzătorul le combină. Culoarea păstrează eticheta exactă și o descriere simplă; miniatura este doar indiciu, deoarece lumina schimbă aspectul. Mărimea păstrează sistemul CN, EU, UK, US sau al vânzătorului și măsurile. Versiunea notează modelul, ediția, materialul, ambalajul sau altă diferență. Cantitatea separă unitățile comandate de piesele per unitate; un set de două poate avea cantitate unu. Prețul minim nu dovedește prețul variantei: verifică rezumatul după selecție. Linia finală trebuie înțeleasă fără imagine: text culoare; etichetă și bază de măsurare; identificator versiune; cantitate și piese per unitate."],
      ["Folosește măsuri fără conversii inventate", "Un număr EU cunoscut nu garantează o potrivire cunoscută. Salvează tabelul, unitatea și capetele măsurării. Pentru haine, clarifică măsurarea pe plan și dacă pieptul este jumătate de lățime ori circumferință. Pentru pantofi, separă mărimea tipărită, lungimea piciorului, branțului și interiorului. Convertește transparent centimetri și milimetri, păstrând originalul. Compară cu un articol propriu potrivit, măsurat identic. Dacă lipsește valoarea decisivă, formulează o întrebare țintită, nu folosi un tabel generic. O fișă utilă spune eticheta 43, intervalul piciorului afișat, metoda și toleranța deschisă; nu spune că EU 43 se potrivește mereu. Traducerea rămâne dovadă, nu garanție."],
      ["Pregătește structurat câmpurile destinatarului german", "Adresa privată rămâne doar în documentul cumpărătorului, niciodată într-o postare sau foaie distribuită. Pentru o adresă germană obișnuită separă numele, strada, numărul, completarea, codul poștal de cinci cifre, localitatea, țara și contactul cerut de formular. Deutsche Post așază numele deasupra străzii și numărului, apoi codul și localitatea. DHL avertizează că strada, numărul sau codul lipsă ori greșit și numele nerecunoscut pot duce la retur. Sunt controale de calitate, nu garanții de livrare internațională. Nu forța formatul Packstation sau oficiu într-o adresă de casă; cere câmpuri și identificatori speciali pe care ruta poate să nu-i accepte. Folosește-l numai dacă fluxul actual îl susține explicit."],
      ["Fă două verificări înainte de plăți", "Ghidul Joyagoo separă plata produsului de coletul internațional ulterior. Înaintea primei plăți, compară titlul, destinația, culoarea, mărimea, versiunea, cantitatea, nota și livrarea internă chineză cu fișa. Dacă pagina redirecționează, dispare o opțiune sau rezumatul se schimbă, oprește și actualizează. Un link ori o traducere salvată nu rămân automat actuale. Înaintea plății coletului, compară fișa destinatarului cu previzualizarea adresei, țara, articolele și restricțiile coletului real. Prețul, ruta, greutatea taxabilă, asigurarea și timpul estimat aparțin celei de-a doua verificări și trebuie citite live. Câmpul este complet doar când coincide; golurile și presupunerile rămân întrebări. Metoda reduce înlocuirile tăcute fără a nega riscurile."],
      ["Folosește stările ca puncte de dovadă", "Ghidul oficial include plată în așteptare, procesare, cumpărat, trimis de vânzător, sosit, QC finalizat și depozitat. Salvează textul și ora exacte. Cumpărat dovedește pasul achiziției; trimis arată mișcarea spre depozit; sosit confirmă recepția; QC oferă dovezile articolului primit. Niciuna nu garantează următorul eveniment la un timp fix. La QC compară mai întâi identitatea, culoarea vizibilă, eticheta mărimii, versiunea, cantitatea și piesele cu cele patru câmpuri, apoi execuția. Dacă o măsură sau etichetă decisivă este neclară, trimite o cerere țintită cu termenul original și explicația germană și păstrează răspunsul datat. Rezultă un lanț trasabil, nu capturi fără legătură."],
      ["Încheie cu o listă compactă", "Confirmă douăsprezece elemente: destinația produsului; data; titlul original; culoarea exactă; sistemul mărimii; baza măsurării; versiunea clară; cantitatea și conținutul separate; nota vânzătorului; rezumatul potrivit; câmpurile private ale adresei germane; întrebările marcate. Adaugă decizia: continuă, așteaptă clarificarea, schimbă opțiunea sau elimină produsul. Nu scrie „verificat” dacă ai controlat doar o parte. Pentru suport elimină alte produse, date de plată, adresa completă și identificatorii; include doar dovada necesară. Reverifică interfața înainte de fiecare acțiune importantă, fiindcă limbile, monedele și câmpurile se schimbă. Un ghid bun oferă un document sigur lingvistic și verificabil, nu o promisiune de cost sau timp."],
    ],
    sources,
  },
  sv: {
    title: "Joyagoo för Tyskland: bygg ett destinationsklart beställningsunderlag",
    description: "Förbered alternativ, mått och tyska adressfält utan att gissa frakt, skatt eller leveranstid.",
    updated: "8 september 2026",
    read: "14 min läsning",
    sections: [
      ["Definiera vad destinationsklart betyder", "Ett destinationsklart underlag lovar inte att en produkt kan använda en viss rutt till Tyskland. Det är en arbetsfil som överför produkt, variant och mottagaruppgifter till det aktuella Joyagoo-flödet utan att förlita sig på minnet. Det offentliga gränssnittet erbjuder nu tyska och EUR som visningsvaluta, medan shoppingguiden kräver färg, storlek och antal före betalning. Det gör läsningen enklare men låser inte annons eller växelkurs och bevisar inte ruttbehörighet. Skriv ett tydligt syfte: identifiera produkten, bevara säljarens ursprungliga alternativ, förklara köparens val och förbered adressfälten. Lämna frakt, tull, skatt och tid utanför tills den aktiva paketsidan visar aktuella uppgifter. Då blir språkstödet inte ett obelagt kostnadslöfte."],
      ["Behåll originalet bredvid den tyska noten", "Maskinöversättning ger orientering, men ett variantval är en beställningsinstruktion. Spara först hela den synliga säljartexten. Lägg originalet i första kolumnen, den tyska arbetsbetydelsen i nästa och beviset i den tredje: variantbild, måttabell, modellnummer, beskrivning eller dokumenterat svar. Om två tolkningar kvarstår markeras fältet som olöst. Ändra inte siffror, koder, materialprocent eller versionsnamn. Gör inte ett modellsuffix till färg eller ett packantal till storlek. Målet är inte elegant tyska utan en not som någon annan kan jämföra tecken för tecken mot den aktiva annonsen och där osäkerheten syns."],
      ["Separera färg, storlek, version och antal", "Skapa fyra fält även om säljaren kombinerar dem. Färg sparar exakt alternativnamn och enkel beskrivning; miniatyren är bara en ledtråd eftersom ljus förändrar utseendet. Storlek sparar systemet CN, EU, UK, US eller säljarens eget samt måtten. Version registrerar modell, utgåva, material, pakettyp eller annan skillnad. Antal skiljer orderenheter från delar per enhet; ett tvådelat set kan ha antal ett. Det lägsta priset bevisar inte variantens pris: kontrollera sammanfattningen efter valet. Slutraden ska förstås utan bild: färgtext; storleksetikett och mätgrund; versions-ID; beställt antal och delar per enhet."],
      ["Använd mått utan påhittad omvandling", "Ett bekant EU-nummer garanterar inte bekant passform. Spara tabell, enhet och mätpunkter. För kläder anges om måttet är plant och om bröst betyder halvbredd eller omkrets. För skor skiljs tryckt storlek, fotlängd, innersula och invändig längd åt. Omvandla centimeter och millimeter öppet och behåll originalet. Jämför med ett eget plagg som passar och mäts på samma sätt. Saknas ett avgörande värde ska en riktad fråga ställas, inte en generell tabell fylla luckan. En bra post anger säljarstorlek 43, visat fotintervall, jämförelsemetod och öppen tolerans; den säger inte att EU 43 alltid passar. Översättningen förblir bevis, inte garanti."],
      ["Förbered tyska mottagarfält strukturerat", "Privata adressuppgifter sparas bara i köparens egen fil, aldrig i offentliga inlägg eller delade ark. För en vanlig tysk bostadsadress separeras mottagarnamn, gata, husnummer, nödvändigt tillägg, femsiffrigt postnummer, ort, land och kontakt om formuläret kräver det. Deutsche Post placerar namnet ovanför gata och nummer, följt av postnummer och ort. DHL varnar att saknad eller fel gata, nummer eller kod, eller ett oidentifierbart mottagarnamn, kan leda till retur. Det är kvalitetskontroller, inte leveransgaranti. Tvinga inte Packstation eller postkontor in i en bostadsadress; de kräver särskilda fält och ID som rutten kanske inte accepterar. Använd bara formatet när det aktuella flödet uttryckligen stöder det."],
      ["Gör två kontroller före betalning", "Joyagoos aktuella guide skiljer produktbetalning från det senare internationella paketet. Före första betalningen jämförs aktiv titel, destination, färg, storlek, version, antal, säljarnot och kinesisk inrikesleverans med filen. Vid omdirigering, försvunnet val eller ändrad sammanfattning stoppas processen och posten uppdateras. En sparad länk eller översättning är inte automatiskt aktuell. Före paketbetalningen jämförs mottagarposten med adressförhandsvisning, land, varulista och begränsningar för det verkliga paketet. Pris, rutt, debiterbar vikt, försäkring och tidsuppskattning hör till andra kontrollen och måste läsas live. Ett fält är klart först när det matchar sammanfattningen; tomrum och antaganden förblir frågor. Metoden minskar tysta byten utan att förneka säljar-, transport- eller tullrisk."],
      ["Använd statusar som bevispunkter", "Den officiella statusguiden omfattar väntande betalning, bearbetning, köpt, skickat av säljaren, anlänt, QC klart och lagrat. Spara exakt text och tid. Köpt stöder inköpssteget; skickat stöder rörelse mot lagret; anlänt stöder mottagning; QC gör mottagningsbevis tillgängliga. Ingen status garanterar nästa händelse vid en fast tid. Vid QC jämförs först identitet, synlig färg, storleksetikett, versionsdrag, antal och delar med de fyra fälten, därefter utförandet. Om ett avgörande mått eller märke är oklart, skicka en riktad begäran med originaltermen och den tyska förklaringen och spara det daterade svaret. Då skapas en spårbar kedja i stället för lösa skärmbilder."],
      ["Avsluta med en kompakt checklista", "Kontrollera tolv saker: aktuell produktdestination; kontrolltid; originaltitel; exakt färg; namngivet storlekssystem; mätgrund; tydlig version; separat antal och packinnehåll; säljarnot; matchad produktsammanfattning; granskade privata tyska adressfält; märkta frågor. Lägg till beslutet: fortsätt, invänta svar, byt alternativ eller ta bort. Skriv inte ”verifierad” när bara en del är kontrollerad. Inför supportdelning tas andra produkter, betalningar, full adress och konto-ID bort; endast nödvändigt bevis följer med. Kontrollera livegränssnittet före varje viktig åtgärd eftersom språk, valutor, annonser och fält ändras. En bra Tysklandsguide lovar inte billigast rutt eller snabbast leverans utan ger ett språksäkert och granskningsbart arbetsunderlag."],
    ],
    sources,
  },
};

export const germanyDestinationArticleSlug = "joyagoo-germany-destination-ready-order-record" as const;
