import type { Article } from "./article-content";
import type { CorePriorityArticleKey } from "./priority-article-content";
import type { Locale } from "./site-data";

type TranslatedLocale = Exclude<Locale, "en">;

export const priorityArticleTranslations: Record<TranslatedLocale, Record<CorePriorityArticleKey, Article>> = {
  de: {
    "articles/hacoo-codes-product-id-guide": {
      minutes: 10,
      sections: [
        { heading: "Hacoo-Code und Hacoo-Link lösen verschiedene Probleme", paragraphs: ["Eine geteilte URL ist ein Weg, eine Produkt-ID ist ein Identifikator. Links können gekürzt, kopiert, umgeleitet oder ersetzt werden; die gespeicherten Ziffern liefern einen zweiten Vergleichswert. Weder eine ladende URL noch ein Suchtreffer für eine Nummer beweist allein, dass das aktuelle Produkt stimmt. Nutze den Code, um einen Kandidaten zu finden, und kontrolliere anschließend am Live-Ziel, was der Datensatz heute darstellt. Die ID ist ein Anker, aber keine Zusage zu Bestand, Qualität, Preis oder Variante."] },
        { heading: "Den Identifikator vor allen anderen Angaben sichern", paragraphs: ["Suche auf der aktuellen Zielseite nach der ausdrücklich als Produkt- oder Artikel-ID bezeichneten Nummer. Kopiere sie ohne Leerzeichen oder Zusätze als Text. Ist keine klare ID sichtbar, speichere End-URL und Seitentitel und markiere die ID als unbekannt, statt Preis, Style-Nummer oder Bilddatei zu erraten. Halte die ID in einer eigenen Tabellenspalte, damit keine wissenschaftliche Schreibweise oder versehentliche Rundung entsteht, und vergleiche jede Ziffer mit der Quelle."], bullets: ["Produkt-ID als Text", "Endgültige Ziel-URL", "Aktueller Seitentitel", "Prüfdatum und Region"] },
        { heading: "Fünf Felder für einen verifizierten Code abgleichen", paragraphs: ["Vergleiche Produkt-ID, aktuellen Titel, erstes Bild, gewählte Variante und Quellpreis. Die ID ordnet den Datensatz zu; Titel und Bild erkennen ein verändertes Ziel; die Variante bestätigt Farbe, Größe, Bundle oder Stil; der Preis ist ein Warnsignal. Verwende eindeutige Statuswerte wie verifiziert, geändert, nicht verfügbar, regional begrenzt oder Prüfung nötig. Wenn ID und Bild stimmen, die gewünschte Farbe aber fehlt, ist die Zeile nicht vollständig verifiziert—dieser konkrete Hinweis ist hilfreicher als ein erzwungenes Ja oder Nein."] },
        { heading: "Live-Routen prüfen, ohne ihre Aussage zu übertreiben", paragraphs: ["Am 17. September 2026 antworteten alle acht Ziel-URLs im aktuellen Index erfolgreich. Die Route 3842 zeigte AMIRI MA-1 Sneakers mit ID 7638942248; Route 24 zeigte ein 6PM-Hoodie-Set mit ID 7572947321. Das stützt die Zuordnung von Route und ID, garantiert aber weder Lagerbestand noch dauerhafte Verfügbarkeit. Trenne Serverantwort, gerenderten Titel, ID-Abgleich, Variantenprüfung und Kaufentscheidung. Erst die Kombination der relevanten Ebenen rechtfertigt den jeweiligen Status."] },
        { heading: "Varianten als Datensätze innerhalb des Datensatzes behandeln", paragraphs: ["Eine Produkt-ID kann mehrere Farben, Stile oder Bundles enthalten. Speichere deshalb die genaue Variantenbezeichnung, eine kurze visuelle Beschreibung und den Preis nach der Auswahl. Der günstigste Standardpreis gehört nicht zwangsläufig zum Bild in einer Tabelle. Größen und Maße bleiben getrennte Felder: Die ID identifiziert das Angebot, nicht die Passform. Für einen robusten Kurzverweis kombiniere ID, Variante und ein unterscheidendes Merkmal oder Maß."] },
        { heading: "Nachweise nicht auf einen Ersatzcode übertragen", paragraphs: ["Verschwindet der ursprüngliche Datensatz, erhält ein ähnlich aussehender Treffer eine neue Zeile mit eigener ID, Datum, Bildern, Preis und Notizen. Übernimm keine Bewertungen, Maße oder Qualitätsaussagen des alten Eintrags. Suche zuerst die bekannte ID und danach eine neutrale Beschreibung plus Kategorie. Vergleiche Proportionen und Varianten vor dem Preis. Wenn kein Kandidat die Identitätsfelder erfüllt, ist nicht verfügbar die ehrlichere und nützlichere Kennzeichnung."] },
        { heading: "Eine wiederholbare Code-Routine aufbauen", paragraphs: ["Erfasse für jeden Fund ID, End-URL, Titel, erstes Bild, Variante, Quellpreis, Region und Prüfdatum. Öffne die gespeicherte URL in einer sauberen Sitzung und suche die ID im eigenen Index, um Dubletten zu finden. Aktualisiere das Prüfdatum erst nach dem vollständigen Vergleich und bewahre den vorherigen Status in einer Änderungsnotiz. So grenzt der Code die Suche ein, die Live-Seite liefert aktuelle Belege und die Historie erklärt Veränderungen."], bullets: ["ID ermitteln", "End-URL speichern", "Titel, Bild, Variante und Preis vergleichen", "Region, Datum und Status notieren", "Ersatz-ID als neue Zeile anlegen"] },
      ],
      takeaways: ["Code als Anker, nicht als Garantie nutzen.", "ID, Titel, Bild, Variante und Preis gemeinsam prüfen.", "Unklare Ergebnisse sichtbar kennzeichnen.", "Ersatz-IDs in neuen Zeilen führen.", "Prüfdatum nur nach vollständigem Vergleich ändern."],
    },
    "articles/hacoo-links-not-working": {
      minutes: 10,
      sections: [
        { heading: "Zuerst klären, was nicht funktioniert", paragraphs: ["Ein Link kann gar nicht laden, zur Startseite springen, ein anderes Produkt zeigen, die erwartete Variante verlieren oder nur auf einem Gerät bzw. in einer Region scheitern. Notiere Fehlerart, endgültige Browseradresse, Gerät oder App, reale Lieferregion und Zeitpunkt. Klicke nicht wiederholt auf unbekannte Kurzlinks. Bewahre die ursprüngliche URL als Text, folge der Weiterleitung einmal in einem normalen Browser und gib auf unbekannten Domains keine Zugangsdaten ein."] },
        { heading: "Die stärksten Belege aus dem alten Link retten", paragraphs: ["Suche Produkt-ID, alten Titel, Bild, Variantenname, Preis und Datum in URL, Tabellenzeile, Screenshot oder Nachricht. Kennzeichne unvollständige Angaben ehrlich. Ein Screenshot zeigt Form und Farbe, aber nicht das aktuelle Ziel; ein Spitzname ist zu schwach. Öffnet der Link ein anderes Produkt, vergleiche dessen ID mit der gespeicherten. Eine andere ID bedeutet veränderte Route; gleiche ID bei verändertem Bild oder Titel bedeutet geänderten Datensatz, der weiter geprüft werden muss."], bullets: ["Original- und End-URL", "Gespeicherte Produkt-ID", "Alter Titel und Bild", "Erwartete Variante", "Region, Gerät und Zeitpunkt"] },
        { heading: "Gerät, App und Region als Ursache ausschließen", paragraphs: ["Teste die Originalroute einmal im aktuellen Browser und einmal in der vorgesehenen App oder Umgebung mit dem echten Zielland. Funktioniert sie nur im Browser, kann die In-App-Ansicht die Ursache sein; ändert sie sich mit dem Land, kennzeichne sie als regional begrenzt. Nutze keine falsche Adresse, kein fremdes Konto und kein VPN, um einen Katalog zu erzwingen, der für die reale Lieferung nicht gilt. Gute Pflege beschreibt die Grenze des Tests."] },
        { heading: "In einer Reihenfolge suchen, die Fehlzuordnungen begrenzt", paragraphs: ["Suche zuerst die exakte ID, danach einen kurzen neutralen Titel plus Kategorie und ein markantes Merkmal. Vergleiche Kandidaten anhand von erstem Bild, Silhouette, Optionen, Preis und eigener ID. Ein ähnlicher Treffer mit anderer Nummer ist ein möglicher Ersatz, nicht das wiedergefundene Original. Bleiben mehrere Kandidaten übrig, ist Prüfung nötig besser als eine Vermutung, die später von weiteren Tabellen kopiert wird."] },
        { heading: "Einen Ersatz als neues Ziel verifizieren", paragraphs: ["Der Ersatz muss den Fünf-Felder-Test bestehen: aktuelle ID, Titel, erstes Bild, gewünschte Variante und Quellpreis. Lege ein neues Prüfdatum und die Region ab. Übertrage keine Bewertungen, Verkaufszahlen, Maße oder Lieferangaben vom alten Datensatz. Behalte die alte URL in der Historie und verknüpfe beide Zeilen neutral. Überschreibe die alte ID nicht, denn sonst verschwindet der Grund für die Änderung."] },
        { heading: "Wissen, wann die Suche enden sollte", paragraphs: ["Beende die Suche, wenn ein unscharfes Bild, eine generische Beschreibung und ein erinnerter Preis Kandidaten nicht eindeutig unterscheiden. Markiere den Eintrag als nicht verfügbar oder Prüfung nötig und liste die fehlenden Belege. Stoppe ebenfalls, wenn eine unbekannte Domain Login, Zahlung oder eine fremde App verlangt. Kehre zu bekannten Kategoriepfaden zurück und prüfe die Domain. Eine sichere aktuelle URL muss Ziel, Identität und Option sichtbar erklären lassen."] },
        { heading: "Eine siebenstufige Wiederherstellung nutzen", paragraphs: ["Alte URL bewahren, Fehler klassifizieren, ID und Bildbelege extrahieren, Umgebung und Region testen, exakte ID suchen, Identitätsfelder vergleichen und jede Ersatzroute als neue Zeile dokumentieren. Öffne die neue URL abschließend in einer sauberen Sitzung und setze erst dann das Prüfdatum. So erhalten Leser bei der Suche nach nicht funktionierenden Hacoo-Links einen Diagnoseweg statt einer weiteren ungeprüften Linkliste."], bullets: ["Bewahren", "Klassifizieren", "Extrahieren", "Testen", "Suchen", "Vergleichen", "Dokumentieren"] },
      ],
      takeaways: ["Fehler zuerst klassifizieren.", "Alte URL und ID erhalten.", "Mit realer Region testen.", "Andere ID als Ersatz behandeln.", "Bei unzureichenden Belegen stoppen."],
    },
    "articles/hacoo-spreadsheet-verify-links": {
      minutes: 11,
      sections: [
        { heading: "Eine gute Hacoo-Tabelle ist ein Prüfprotokoll", paragraphs: ["Eine lange Linkliste beweist keine Pflege. Jede Zeile sollte zeigen, welcher Datensatz gemeint war, welches Ziel beobachtet wurde und wann sowie in welcher Region der Vergleich stattfand. Eine Jahreszahl im Dateinamen macht alte Zeilen nicht aktuell; Frische entsteht durch ein dokumentiertes Prüfdatum pro Zeile. Ein älterer Eintrag kann wertvoll bleiben, wenn Route, ID, Bild und Variante gerade erneut geprüft wurden."] },
        { heading: "Ein Schema verwenden, das Identität bewahrt", paragraphs: ["Pflichtspalten sind Status, Produkt-ID, End-URL, aktueller Titel, Kategorie, Bildreferenz, gewünschte Variante, Quellpreis, Währung, Prüfdatum, Region und Notiz. ID und URL bleiben sichtbar und als Text gespeichert. Trenne Quellpreis und Umrechnung und nutze eine Zeile pro Produktdatensatz und Variante. Optionale Maße, Belegdatum und frühere URL helfen; unklare Rankings, verborgene IDs und abhängige Formeln nicht."], bullets: ["Status und ID", "End-URL und Titel", "Bild und Variante", "Quellpreis und Währung", "Datum, Region und Notizen"] },
        { heading: "Das Endziel statt der Button-Beschriftung prüfen", paragraphs: ["Öffne jeden Link und speichere die Adresse nach erwarteten Weiterleitungen. Prüfe Hostname und tatsächliches Linkziel, denn ein Button kann eine fremde oder gekürzte URL verbergen. Eine erfolgreiche Serverantwort reicht nicht: Die Seite muss die erwartete ID, den Titel, das Bild und die Option zeigen. Teste die bereinigte End-URL in einer sauberen Sitzung und speichere niemals Konto-Token oder private Sitzungswerte."] },
        { heading: "Den gleichen Fünf-Felder-Test auf jede Zeile anwenden", paragraphs: ["Vergleiche ID, Titel, erstes Bild, ausgewählte Variante und Quellpreis. Verwende kontrollierte Werte: verifiziert, geändert, nicht verfügbar, regional begrenzt oder Prüfung nötig. Trenne Link-Erreichbarkeit und Produktübereinstimmung, denn ein erreichbarer Link kann zum falschen Artikel führen. Notizen sollten konkret benennen, was fehlt oder sich geändert hat; das macht die nächste Prüfung schneller."] },
        { heading: "In Stapeln prüfen, ohne den Standard zu senken", paragraphs: ["Beginne mit häufig geklickten, prominenten oder lange ungeprüften Zeilen. Automatische Statusprüfungen dürfen Kandidaten markieren, aber nur der Feldvergleich bestätigt das Produkt. Bearbeite fehlgeschlagene Zeilen in einem zweiten Durchgang: zuerst ID, dann Titel und Merkmale. Ein Ersatz erhält eine neue Zeile; die alte behält ihre Historie. Größere Korrekturen gehören mit Datum in ein Änderungsprotokoll."] },
        { heading: "Klicks so messen, dass sie interpretierbar sind", paragraphs: ["Nutze klare Linktexte wie passenden Eintrag öffnen und zeige Titel, ID und Status daneben. Erfasse ausgehende Klicks mit Ziel, Produkt-ID und Seitenpfad, jedoch ohne persönliche oder Kontodaten. Klickrate allein ist kein Erfolg: Viele Klicks auf falsche Ziele sind schlecht. Betrachte sie zusammen mit Engagement, Wiederkehr und Linkmeldungen und reagiere bei wenig Traffic auf wiederkehrende Muster statt auf einen einzelnen Tag."] },
        { heading: "Mit Versionshistorie und Prüfregel veröffentlichen", paragraphs: ["Entferne vor Veröffentlichung doppelte IDs, teste sichtbare Ziele, kontrolliere Pflichtfelder und die mobile Darstellung und führe ein datiertes Änderungsprotokoll. Prüfe stark geklickte Zeilen häufiger. Ändere das Prüfdatum nie automatisch nach einer bloßen Serverantwort; speichere dafür ein eigenes Feld. Das Datum muss einen vollständigen Identitäts- und Variantenvergleich bedeuten. Eine kleinere transparente Tabelle ist nützlicher als tausende undurchsichtige Links."], bullets: ["IDs deduplizieren", "Ziele testen", "Pflichtfelder prüfen", "Mobile Ansicht kontrollieren", "Änderungsprotokoll veröffentlichen"] },
      ],
      takeaways: ["Jede Zeile als prüfbaren Datensatz behandeln.", "IDs und End-URLs sichtbar speichern.", "Erreichbarkeit und Übereinstimmung trennen.", "Ersatz-IDs als neue Zeilen anlegen.", "Prüfdatum nur nach Vollkontrolle ändern."],
    },
  },
  fr: {
    "articles/hacoo-codes-product-id-guide": {
      minutes: 10,
      sections: [
        { heading: "Un code Hacoo et un lien Hacoo ne servent pas au même usage", paragraphs: ["Une URL partagée est un itinéraire; l’identifiant produit désigne un enregistrement. Les liens peuvent être raccourcis, copiés, redirigés ou remplacés, tandis que les chiffres conservés offrent une seconde valeur de comparaison. Ni une URL qui charge ni un résultat trouvé par numéro ne prouve seul que le produit actuel correspond. Utilisez le code pour retrouver un candidat, puis vérifiez sur la destination en direct ce que l’enregistrement représente aujourd’hui. L’identifiant est un repère, pas une garantie de stock, de qualité, de prix ou de variante."] },
        { heading: "Relever l’identifiant avant toute autre donnée", paragraphs: ["Repérez sur la page actuelle le numéro explicitement présenté comme identifiant du produit ou de l’article. Copiez-le en texte brut, sans espaces ni libellé. Si aucun identifiant clair n’apparaît, enregistrez l’URL finale et le titre et notez identifiant inconnu au lieu de deviner à partir d’un prix ou d’un fichier image. Conservez-le dans une colonne dédiée pour éviter l’arrondi ou la notation scientifique, puis comparez chaque chiffre à la source."], bullets: ["Identifiant en texte brut", "URL finale", "Titre actuel", "Date et région du contrôle"] },
        { heading: "Comparer cinq champs avant de déclarer un code vérifié", paragraphs: ["Contrôlez l’identifiant, le titre actuel, la première image, la variante sélectionnée et le prix source. L’identifiant fixe le dossier; titre et image détectent un changement; la variante confirme couleur, taille, lot ou style; le prix sert de signal d’alerte. Utilisez des statuts précis: vérifié, modifié, indisponible, limité par région ou à revoir. Si l’identifiant et l’image correspondent mais que la couleur a disparu, décrivez ce désaccord au lieu de forcer une réponse binaire."] },
        { heading: "Contrôler les routes réelles sans exagérer leur portée", paragraphs: ["Le 17 septembre 2026, les huit URL de l’index ont répondu correctement. La route 3842 affichait AMIRI MA-1 Sneakers avec l’identifiant 7638942248 et la route 24 un ensemble 6PM avec l’identifiant 7572947321. Cela confirme l’association route-identifiant au moment du test, sans garantir les tailles ni la permanence. Distinguez réponse du serveur, contenu rendu, correspondance d’identifiant, variante et décision finale."] },
        { heading: "Traiter les variantes comme des fiches dans la fiche", paragraphs: ["Un identifiant peut regrouper plusieurs couleurs, styles ou lots. Enregistrez le libellé exact de la variante, une description visuelle et le prix après sélection. Le prix le plus bas n’est pas forcément celui de l’image partagée. Gardez les mesures séparées: l’identifiant décrit la fiche, pas la coupe. Pour un repère robuste, associez identifiant, variante et une mesure ou caractéristique distinctive."] },
        { heading: "Ne pas transférer les preuves vers un code de remplacement", paragraphs: ["Si la fiche d’origine disparaît, créez une nouvelle ligne pour tout résultat ressemblant, avec son identifiant, sa date, ses images, son prix et ses notes. Ne transférez ni avis, ni mesures, ni affirmations de qualité. Recherchez d’abord le code connu, puis une description neutre et la catégorie. Comparez proportions et variantes avant le prix. Si aucun candidat ne satisfait les champs d’identité, le statut indisponible est plus utile qu’un remplacement douteux."] },
        { heading: "Adopter une routine reproductible centrée sur le code", paragraphs: ["Pour chaque trouvaille, relevez identifiant, URL finale, titre, première image, variante, prix source, région et date. Testez l’URL dans une session propre et recherchez l’identifiant dans votre index pour repérer les doublons. Ne modifiez la date qu’après le contrôle complet et gardez l’ancien statut dans l’historique. Le code resserre la recherche, la page en direct fournit les preuves et l’historique explique le changement."], bullets: ["Relever l’identifiant", "Enregistrer l’URL finale", "Comparer titre, image, variante et prix", "Noter région, date et statut", "Créer une ligne pour tout nouvel identifiant"] },
      ],
      takeaways: ["Le code est un repère, pas une garantie.", "Vérifier ensemble identifiant, titre, image, variante et prix.", "Signaler les résultats ambigus.", "Créer une ligne pour tout remplacement.", "Changer la date après un contrôle complet."],
    },
    "articles/hacoo-links-not-working": {
      minutes: 10,
      sections: [
        { heading: "Définir d’abord ce qui ne fonctionne pas", paragraphs: ["Un lien peut ne pas charger, revenir à l’accueil, ouvrir un autre produit, perdre la variante attendue ou différer selon appareil et région. Notez le symptôme, l’adresse finale, l’appareil ou l’application, la vraie région de livraison et l’heure. Ne cliquez pas en boucle sur des raccourcis inconnus. Conservez l’URL d’origine en texte, développez-la une fois dans un navigateur normal et ne saisissez jamais vos identifiants sur un domaine inattendu."] },
        { heading: "Récupérer les preuves les plus solides de l’ancien lien", paragraphs: ["Cherchez identifiant, ancien titre, image, variante, prix et date dans l’URL, le tableur, la capture ou le message. Une capture confirme une forme mais pas la destination actuelle; un surnom reste trop vague. Si le lien ouvre un autre article, comparez son identifiant à celui sauvegardé. Un numéro différent indique une route modifiée; le même numéro avec un autre titre ou visuel indique une fiche modifiée à examiner."], bullets: ["URL d’origine et finale", "Identifiant sauvegardé", "Ancien titre et image", "Variante attendue", "Région, appareil et heure"] },
        { heading: "Écarter les différences d’appareil, d’application et de région", paragraphs: ["Testez une fois la route dans le navigateur actuel et dans l’environnement prévu avec le pays réel. Un fonctionnement limité au navigateur peut signaler un souci de vue intégrée; un changement selon le pays mérite le statut limité par région. N’utilisez ni fausse adresse, ni compte prêté, ni VPN pour forcer un catalogue inutilisable à la vraie destination. Documentez la limite du test."] },
        { heading: "Chercher dans un ordre qui réduit les faux rapprochements", paragraphs: ["Recherchez d’abord l’identifiant exact, puis une description générique courte, la catégorie et un trait distinctif. Comparez première image, silhouette, options, prix et identifiant propre du candidat. Une fiche ressemblante portant un autre numéro est un remplacement possible, pas l’original retrouvé. Si plusieurs candidats restent plausibles, choisissez à revoir plutôt qu’une supposition destinée à être recopiée."] },
        { heading: "Vérifier un remplacement comme une nouvelle destination", paragraphs: ["Le remplacement doit réussir le contrôle des cinq champs: identifiant, titre, première image, variante et prix source. Ajoutez date et région. Ne transférez ni avis, ni ventes, ni mesures, ni délais de l’ancienne fiche. Conservez l’ancienne URL dans l’historique et reliez les lignes par une note neutre. N’écrasez jamais l’ancien identifiant, qui explique la modification."] },
        { heading: "Savoir quand arrêter la recherche", paragraphs: ["Arrêtez lorsqu’une image floue, une description générique et un prix approximatif ne distinguent pas les candidats. Marquez indisponible ou à revoir et listez les éléments manquants. Arrêtez aussi si un domaine inconnu exige connexion, paiement ou installation inattendue. Revenez aux catégories connues et vérifiez le domaine. Une URL sûre doit permettre d’expliquer la destination, l’identité et l’option à partir de preuves visibles."] },
        { heading: "Suivre une procédure de récupération en sept étapes", paragraphs: ["Préservez l’URL, classez l’échec, extrayez identifiant et preuves visuelles, testez environnement et région, recherchez le code exact, comparez les champs et documentez le remplacement dans une nouvelle ligne. Ouvrez enfin la nouvelle URL en session propre avant de dater le contrôle. Les lecteurs obtiennent ainsi une méthode de diagnostic plutôt qu’une autre liste de liens non vérifiés."], bullets: ["Préserver", "Classer", "Extraire", "Tester", "Rechercher", "Comparer", "Documenter"] },
      ],
      takeaways: ["Classer l’échec avant de chercher.", "Conserver URL et identifiant.", "Tester dans la vraie région.", "Traiter un autre identifiant comme remplacement.", "S’arrêter si les preuves sont insuffisantes."],
    },
    "articles/hacoo-spreadsheet-verify-links": {
      minutes: 11,
      sections: [
        { heading: "Un bon tableur Hacoo est un journal d’audit", paragraphs: ["Une longue liste n’apporte aucune preuve de contrôle. Chaque ligne doit indiquer la fiche visée, la destination observée, la date et la région de comparaison. L’année dans le titre ne rend pas une ligne actuelle; la fraîcheur se documente ligne par ligne. Une ancienne entrée reste utile si route, identifiant, image et variante viennent d’être revérifiés."] },
        { heading: "Employer un schéma qui préserve l’identité", paragraphs: ["Prévoyez statut, identifiant, URL finale, titre, catégorie, image, variante, prix source, devise, date, région et note. Gardez identifiant et URL visibles en texte; séparez prix source et conversion; utilisez une ligne par fiche et variante. Mesures, date des avis et ancienne URL peuvent aider. Évitez scores vagues, cellules fusionnées, identifiants cachés et formules dépendant de services inconnus."], bullets: ["Statut et identifiant", "URL finale et titre", "Image et variante", "Prix source et devise", "Date, région et notes"] },
        { heading: "Vérifier la destination finale, pas le texte du bouton", paragraphs: ["Ouvrez chaque lien et relevez l’adresse après les redirections attendues. Contrôlez le domaine et la vraie cible, car un bouton peut masquer une URL raccourcie. Une réponse serveur ne suffit pas: la page doit montrer l’identifiant, le titre, l’image et l’option attendus. Testez l’URL finale dans une session propre et ne stockez jamais jetons de compte ou valeurs de session privées."] },
        { heading: "Appliquer le même contrôle des cinq champs à chaque ligne", paragraphs: ["Comparez identifiant, titre, première image, variante et prix source. Utilisez vérifié, modifié, indisponible, limité par région ou à revoir. Séparez santé du lien et correspondance du produit: une URL active peut ouvrir le mauvais article. Les notes doivent nommer précisément ce qui manque ou a changé afin d’accélérer le prochain audit."] },
        { heading: "Auditer par lots sans abaisser le niveau", paragraphs: ["Commencez par les lignes cliquées, visibles ou anciennes. Un test automatique peut signaler des candidats, mais seul le contrôle d’identité valide le produit. Traitez ensuite les échecs: identifiant d’abord, puis titre et traits distinctifs. Un remplacement reçoit une nouvelle ligne; l’ancienne garde son historique. Toute correction large doit figurer dans un journal daté."] },
        { heading: "Mesurer des clics interprétables", paragraphs: ["Utilisez un libellé d’action précis et affichez titre, identifiant et statut près du lien. Mesurez les clics sortants avec destination, ID et chemin de page, sans donnée personnelle. Un taux élevé vers de mauvaises destinations reste un échec. Croisez clics, engagement, retours et signalements et, sur un petit volume, attendez des motifs répétés plutôt que de réagir à une journée."] },
        { heading: "Publier avec historique et règle de recontrôle", paragraphs: ["Avant publication, dédupliquez les identifiants, testez les cibles visibles, contrôlez les champs et la version mobile, puis tenez un journal daté. Revérifiez plus souvent les lignes populaires. Ne changez jamais automatiquement la date après une simple réponse serveur; gardez un champ séparé. La date de contrôle doit signifier qu’identité et variante ont été comparées."], bullets: ["Dédupliquer les identifiants", "Tester les cibles", "Contrôler les champs", "Vérifier sur mobile", "Publier un journal daté"] },
      ],
      takeaways: ["Traiter chaque ligne comme un dossier auditable.", "Afficher identifiants et URL finales.", "Séparer santé du lien et correspondance.", "Créer une ligne pour chaque remplacement.", "Dater après le contrôle complet."],
    },
  },
  es: {
    "articles/hacoo-codes-product-id-guide": {
      minutes: 10,
      sections: [
        { heading: "Un código de Hacoo y un enlace resuelven problemas distintos", paragraphs: ["Una URL compartida es una ruta y el ID de producto identifica un registro. Los enlaces pueden acortarse, copiarse, redirigirse o sustituirse; los dígitos guardados ofrecen otro valor para comparar. Ni una URL que carga ni un resultado encontrado por número demuestra por sí solo que el producto actual coincida. Usa el código para localizar un candidato y verifica en el destino activo qué representa hoy. El ID es una referencia, no una garantía de stock, calidad, precio o variante."] },
        { heading: "Localiza el identificador antes de copiar otros datos", paragraphs: ["Busca el número que la página presenta explícitamente como ID de producto o artículo. Cópialo como texto, sin espacios ni etiquetas. Si no aparece uno claro, guarda la URL final y el título y marca ID desconocido en vez de deducirlo de un precio o nombre de imagen. Conserva el número en su propia columna para evitar redondeos o notación científica y coteja cada dígito con la fuente."], bullets: ["ID como texto", "URL final", "Título actual", "Fecha y región"] },
        { heading: "Compara cinco campos antes de marcar el código como verificado", paragraphs: ["Comprueba ID, título actual, primera imagen, variante seleccionada y precio original. El ID fija el registro; título e imagen detectan cambios; la variante confirma color, talla, lote o estilo; el precio funciona como alerta. Usa estados controlados: verificado, cambiado, no disponible, limitado por región o pendiente. Si ID e imagen coinciden pero falta el color esperado, explica esa diferencia en vez de forzar un sí o un no."] },
        { heading: "Comprueba rutas reales sin exagerar lo que demuestran", paragraphs: ["El 17 de septiembre de 2026 respondieron correctamente las ocho URL del índice. La ruta 3842 mostraba AMIRI MA-1 Sneakers con ID 7638942248 y la ruta 24 un conjunto 6PM con ID 7572947321. Esto respalda la relación entre ruta e ID en ese momento, pero no garantiza tallas ni permanencia. Separa respuesta del servidor, contenido visible, coincidencia del ID, variante y decisión final."] },
        { heading: "Trata las variantes como registros dentro del registro", paragraphs: ["Un ID puede agrupar colores, estilos o lotes. Guarda el nombre exacto de la variante, una descripción visual y el precio tras seleccionarla. El precio mínimo no tiene por qué corresponder a la imagen compartida. Mantén las medidas aparte: el ID identifica la ficha, no el ajuste. Una referencia compacta y resistente combina ID, variante y una medida o rasgo distintivo."] },
        { heading: "No transfieras pruebas a un código sustituto", paragraphs: ["Si desaparece la ficha original, cualquier resultado parecido debe ocupar una fila nueva con su propio ID, fecha, imágenes, precio y notas. No copies reseñas, medidas ni afirmaciones de calidad. Busca primero el código conocido y luego una descripción neutra con la categoría. Compara proporciones y variantes antes que el precio. Si ningún candidato supera los campos de identidad, no disponible es el estado más honesto."] },
        { heading: "Crea una rutina repetible basada en códigos", paragraphs: ["Registra ID, URL final, título, primera imagen, variante, precio original, región y fecha. Abre la URL en una sesión limpia y busca el ID en tu índice para detectar duplicados. Cambia la fecha solo después de comparar todos los campos y conserva el estado anterior en el historial. Así el código acota la búsqueda, la página activa aporta pruebas y el registro de cambios explica la evolución."], bullets: ["Localizar el ID", "Guardar la URL final", "Comparar título, imagen, variante y precio", "Anotar región, fecha y estado", "Crear una fila para cada ID sustituto"] },
      ],
      takeaways: ["Usa el código como referencia, no garantía.", "Verifica juntos ID, título, imagen, variante y precio.", "Marca los resultados ambiguos.", "Crea filas nuevas para sustitutos.", "Actualiza la fecha tras la revisión completa."],
    },
    "articles/hacoo-links-not-working": {
      minutes: 10,
      sections: [
        { heading: "Define primero qué significa que no funciona", paragraphs: ["Un enlace puede no cargar, volver al inicio, abrir otro producto, perder la variante esperada o cambiar según dispositivo y región. Anota el síntoma, la dirección final, el navegador o app, la región real de entrega y la hora. No pulses repetidamente acortadores desconocidos. Conserva la URL original como texto, expándela una vez en un navegador normal y nunca introduzcas credenciales en un dominio inesperado."] },
        { heading: "Recupera las pruebas más sólidas del enlace antiguo", paragraphs: ["Busca ID, título anterior, imagen, variante, precio y fecha en la URL, hoja, captura o mensaje. Una captura confirma forma y color, no el destino actual; un apodo es demasiado débil. Si el enlace abre otro artículo, compara su ID con el guardado. Un número distinto indica una ruta cambiada; el mismo ID con otro título o imagen indica una ficha modificada que exige revisión."], bullets: ["URL original y final", "ID guardado", "Título e imagen anteriores", "Variante esperada", "Región, dispositivo y hora"] },
        { heading: "Descarta diferencias de dispositivo, app y región", paragraphs: ["Prueba la ruta una vez en el navegador actual y otra en el entorno previsto con el país real. Si solo funciona en navegador, puede fallar la vista integrada; si cambia por país, usa limitado por región. No emplees una dirección falsa, cuenta prestada o VPN para forzar un catálogo que no sirve para la entrega real. Documentar el límite es mejor que declarar el producto universalmente disponible o ausente."] },
        { heading: "Busca en un orden que reduzca coincidencias falsas", paragraphs: ["Empieza por el ID exacto; después usa una descripción breve, categoría y rasgo distintivo. Compara primera imagen, silueta, opciones, precio e ID propio del candidato. Una ficha parecida con otro número es un posible sustituto, no el original recuperado. Si quedan varios candidatos, pendiente de revisión es preferible a una conjetura que otras hojas podrían copiar."] },
        { heading: "Verifica un sustituto como destino nuevo", paragraphs: ["El sustituto debe superar el control de ID, título, primera imagen, variante y precio original. Añade fecha y región. No transfieras reseñas, ventas, medidas ni plazos de la ficha anterior. Conserva la URL vieja en el historial y conecta ambas filas con una nota neutral. No sobrescribas el ID antiguo porque perderías la explicación del cambio."] },
        { heading: "Reconoce cuándo debes dejar de buscar", paragraphs: ["Detente si una imagen borrosa, una descripción genérica y un precio aproximado no distinguen candidatos. Marca no disponible o pendiente y enumera las pruebas que faltan. Detente también si un dominio extraño pide inicio de sesión, pago o una app inesperada. Vuelve a rutas conocidas y verifica el dominio. Una URL segura permite explicar destino, identidad y opción mediante datos visibles."] },
        { heading: "Usa una recuperación de siete pasos", paragraphs: ["Conserva la URL, clasifica el fallo, extrae ID y pruebas visuales, prueba entorno y región, busca el código exacto, compara los campos y documenta cualquier sustituto en una fila nueva. Abre al final la URL nueva en una sesión limpia y solo entonces fecha la revisión. El lector recibe así un proceso de diagnóstico y no otra lista de enlaces sin comprobar."], bullets: ["Conservar", "Clasificar", "Extraer", "Probar", "Buscar", "Comparar", "Documentar"] },
      ],
      takeaways: ["Clasifica el fallo antes de buscar.", "Conserva URL e ID.", "Prueba con la región real.", "Otro ID significa sustituto.", "Detente si faltan pruebas."],
    },
    "articles/hacoo-spreadsheet-verify-links": {
      minutes: 11,
      sections: [
        { heading: "Una hoja útil es un registro de auditoría", paragraphs: ["Una lista larga no demuestra que sus destinos se revisen. Cada fila debe indicar qué registro se pretendía, qué destino se observó, cuándo y en qué región. El año del título no vuelve actuales las filas; la vigencia se documenta individualmente. Una entrada antigua sigue siendo útil si su ruta, ID, imagen y variante acaban de revisarse."] },
        { heading: "Usa un esquema que conserve la identidad", paragraphs: ["Incluye estado, ID, URL final, título, categoría, imagen, variante, precio original, moneda, fecha, región y notas. Mantén ID y URL visibles como texto, separa el precio fuente de la conversión y usa una fila por ficha y variante. Medidas, fecha de reseñas y URL anterior pueden ayudar. Evita puntuaciones vagas, celdas combinadas, identificadores ocultos y fórmulas dependientes de servicios desconocidos."], bullets: ["Estado e ID", "URL final y título", "Imagen y variante", "Precio y moneda", "Fecha, región y notas"] },
        { heading: "Verifica el destino final y no el texto del botón", paragraphs: ["Abre cada enlace y registra la dirección tras las redirecciones esperadas. Comprueba dominio y objetivo real, porque un botón puede ocultar un acortador. Una respuesta del servidor no basta: la página debe mostrar ID, título, imagen y opción esperados. Prueba la URL final en una sesión limpia y nunca guardes tokens de cuenta ni datos privados de sesión."] },
        { heading: "Aplica el mismo control de cinco campos a cada fila", paragraphs: ["Compara ID, título, primera imagen, variante y precio original. Usa estados como verificado, cambiado, no disponible, limitado por región o pendiente. Separa salud del enlace y coincidencia del producto: una URL activa puede llevar al artículo equivocado. Las notas deben nombrar exactamente qué falta o cambió para facilitar la auditoría siguiente."] },
        { heading: "Audita por lotes sin bajar el nivel", paragraphs: ["Empieza por filas con clics, visibles o antiguas. Un control automático puede señalar candidatos, pero solo la comparación de identidad valida el producto. Revisa después los fallos: primero ID, luego título y rasgos. Cada sustituto recibe una fila nueva y la antigua conserva su historial. Las correcciones amplias deben constar en un registro fechado."] },
        { heading: "Mide clics que puedas interpretar", paragraphs: ["Usa textos de acción claros y muestra título, ID y estado junto al enlace. Registra clics salientes con destino, ID y ruta de página, sin datos personales. Una tasa alta hacia destinos erróneos no es éxito. Analiza clics junto a interacción, retornos y avisos y, con poco tráfico, espera patrones repetidos antes de reaccionar a un solo día."] },
        { heading: "Publica con historial y regla de revisión", paragraphs: ["Antes de publicar, elimina IDs duplicados, prueba objetivos visibles, revisa campos obligatorios y móvil y mantén un registro fechado. Revisa con mayor frecuencia las filas populares. Nunca cambies automáticamente la fecha tras una simple respuesta del servidor; usa otro campo para eso. La fecha de revisión debe significar que se compararon identidad y variante."], bullets: ["Eliminar IDs duplicados", "Probar objetivos", "Revisar campos", "Comprobar móvil", "Publicar un historial"] },
      ],
      takeaways: ["Trata cada fila como registro auditable.", "Muestra ID y URL final.", "Separa salud y coincidencia.", "Crea filas nuevas para sustitutos.", "Fecha tras la revisión completa."],
    },
  },
  it: {
    "articles/hacoo-codes-product-id-guide": {
      minutes: 10,
      sections: [
        { heading: "Un codice Hacoo e un link risolvono problemi diversi", paragraphs: ["Un URL condiviso è un percorso; l’ID prodotto identifica un record. I link possono essere abbreviati, copiati, reindirizzati o sostituiti, mentre le cifre salvate offrono un secondo valore da confrontare. Né una pagina che si apre né un risultato trovato per numero dimostra da solo la corrispondenza attuale. Usa il codice per trovare un candidato, poi verifica sulla destinazione live cosa rappresenta oggi. L’ID è un riferimento, non una garanzia di disponibilità, qualità, prezzo o variante."] },
        { heading: "Trova l’identificatore prima di copiare il resto", paragraphs: ["Individua il numero indicato esplicitamente come ID del prodotto o dell’articolo. Copialo come testo, senza spazi o etichette. Se non esiste un ID chiaro, salva URL finale e titolo e segna ID sconosciuto invece di dedurlo da prezzo o nome immagine. Usa una colonna dedicata per evitare arrotondamenti o notazione scientifica e confronta ogni cifra con la fonte."], bullets: ["ID come testo", "URL finale", "Titolo attuale", "Data e regione"] },
        { heading: "Confronta cinque campi prima di dichiarare verificato il codice", paragraphs: ["Controlla ID, titolo attuale, prima immagine, variante selezionata e prezzo di origine. L’ID definisce il record; titolo e immagine rivelano cambi; la variante conferma colore, taglia, set o stile; il prezzo è un segnale. Usa stati controllati: verificato, modificato, non disponibile, limitato per regione o da rivedere. Se ID e immagine coincidono ma manca il colore, descrivi il disaccordo invece di forzare un sì o no."] },
        { heading: "Controlla i percorsi reali senza esagerarne il significato", paragraphs: ["Il 17 settembre 2026 tutti gli otto URL dell’indice hanno risposto correttamente. Il percorso 3842 mostrava AMIRI MA-1 Sneakers con ID 7638942248 e il percorso 24 un set 6PM con ID 7572947321. Questo conferma la relazione tra percorso e ID al momento del test, ma non garantisce taglie o permanenza. Distingui risposta server, contenuto visibile, corrispondenza ID, variante e decisione finale."] },
        { heading: "Tratta le varianti come record nel record", paragraphs: ["Un ID può raggruppare colori, stili o set diversi. Salva il nome esatto della variante, una descrizione visiva e il prezzo dopo la selezione. Il prezzo più basso non appartiene necessariamente all’immagine condivisa. Mantieni separate le misure: l’ID identifica la scheda, non la vestibilità. Un riferimento compatto combina ID, variante e una misura o caratteristica distintiva."] },
        { heading: "Non trasferire prove a un codice sostitutivo", paragraphs: ["Se il record originale scompare, crea una nuova riga per ogni risultato simile con ID, data, immagini, prezzo e note propri. Non copiare recensioni, misure o giudizi di qualità. Cerca prima il codice noto, poi una descrizione neutra e la categoria. Confronta proporzioni e varianti prima del prezzo. Se nessun candidato supera i campi d’identità, non disponibile è più utile di un sostituto incerto."] },
        { heading: "Crea una routine ripetibile basata sul codice", paragraphs: ["Per ogni scoperta registra ID, URL finale, titolo, prima immagine, variante, prezzo, regione e data. Apri l’URL in una sessione pulita e cerca l’ID nel tuo indice per trovare duplicati. Aggiorna la data solo dopo il confronto completo e conserva lo stato precedente nello storico. Il codice restringe la ricerca, la pagina live fornisce prove e lo storico spiega i cambiamenti."], bullets: ["Individuare l’ID", "Salvare l’URL finale", "Confrontare titolo, immagine, variante e prezzo", "Annotare regione, data e stato", "Creare una riga per ogni ID sostitutivo"] },
      ],
      takeaways: ["Usa il codice come riferimento, non garanzia.", "Verifica insieme ID, titolo, immagine, variante e prezzo.", "Segnala i risultati ambigui.", "Crea nuove righe per i sostituti.", "Aggiorna la data dopo il controllo completo."],
    },
    "articles/hacoo-links-not-working": {
      minutes: 10,
      sections: [
        { heading: "Definisci prima cosa significa non funzionante", paragraphs: ["Un link può non caricarsi, tornare alla home, aprire un altro prodotto, perdere la variante attesa o cambiare per dispositivo e regione. Annota sintomo, indirizzo finale, browser o app, regione reale di consegna e ora. Non cliccare ripetutamente abbreviazioni sconosciute. Conserva l’URL originale come testo, espandilo una volta in un browser normale e non inserire credenziali su domini inattesi."] },
        { heading: "Recupera le prove più forti dal vecchio link", paragraphs: ["Cerca ID, vecchio titolo, immagine, variante, prezzo e data nell’URL, nel foglio, nello screenshot o nel messaggio. Uno screenshot conferma forma e colore, non la destinazione attuale; un soprannome è troppo debole. Se il link apre un altro articolo, confronta l’ID con quello salvato. Un numero diverso indica un percorso cambiato; lo stesso ID con titolo o immagine diversi indica una scheda modificata da esaminare."], bullets: ["URL originale e finale", "ID salvato", "Titolo e immagine precedenti", "Variante attesa", "Regione, dispositivo e ora"] },
        { heading: "Escludi differenze di dispositivo, app e regione", paragraphs: ["Prova il percorso nel browser corrente e nell’ambiente previsto con il paese reale. Se funziona solo nel browser può essere un problema della vista integrata; se cambia per paese usa limitato per regione. Non usare indirizzi falsi, account prestati o VPN per forzare un catalogo inutilizzabile per la destinazione reale. Documenta il limite della prova."] },
        { heading: "Cerca in un ordine che riduce le false corrispondenze", paragraphs: ["Inizia dall’ID esatto, poi usa una breve descrizione generica, categoria e tratto distintivo. Confronta prima immagine, silhouette, opzioni, prezzo e ID del candidato. Una scheda simile con altro numero è un possibile sostituto, non l’originale ritrovato. Se restano più candidati, da rivedere è meglio di un’ipotesi destinata a essere ricopiata."] },
        { heading: "Verifica un sostituto come nuova destinazione", paragraphs: ["Il sostituto deve superare il controllo di ID, titolo, prima immagine, variante e prezzo. Aggiungi data e regione. Non trasferire recensioni, vendite, misure o tempi dalla vecchia scheda. Conserva il vecchio URL nello storico e collega le righe con una nota neutra. Non sovrascrivere l’ID precedente, altrimenti perdi la spiegazione del cambiamento."] },
        { heading: "Sappi quando interrompere la ricerca", paragraphs: ["Fermati se immagine sfocata, descrizione generica e prezzo approssimativo non distinguono i candidati. Segna non disponibile o da rivedere ed elenca le prove mancanti. Fermati anche se un dominio sconosciuto chiede login, pagamento o installazioni inattese. Torna ai percorsi noti e verifica il dominio. Un URL sicuro permette di spiegare destinazione, identità e opzione con prove visibili."] },
        { heading: "Usa un recupero in sette passaggi", paragraphs: ["Conserva l’URL, classifica l’errore, estrai ID e prove visive, prova ambiente e regione, cerca il codice esatto, confronta i campi e documenta il sostituto in una nuova riga. Apri infine il nuovo URL in una sessione pulita e solo allora data il controllo. Il lettore ottiene un processo diagnostico, non un’altra lista non verificata."], bullets: ["Conservare", "Classificare", "Estrarre", "Provare", "Cercare", "Confrontare", "Documentare"] },
      ],
      takeaways: ["Classifica l’errore prima di cercare.", "Conserva URL e ID.", "Prova con la regione reale.", "Un altro ID è un sostituto.", "Fermati se mancano prove."],
    },
    "articles/hacoo-spreadsheet-verify-links": {
      minutes: 11,
      sections: [
        { heading: "Un foglio utile è un registro di verifica", paragraphs: ["Una lista lunga non dimostra che le destinazioni siano controllate. Ogni riga deve indicare il record previsto, il target osservato, quando e in quale regione. L’anno nel titolo non rende attuali le righe; la freschezza si documenta singolarmente. Un record vecchio resta utile se percorso, ID, immagine e variante sono appena stati ricontrollati."] },
        { heading: "Usa uno schema che conserva l’identità", paragraphs: ["Includi stato, ID, URL finale, titolo, categoria, immagine, variante, prezzo, valuta, data, regione e note. Mantieni ID e URL visibili come testo, separa prezzo fonte e conversione e usa una riga per scheda e variante. Misure, data delle recensioni e URL precedente possono aiutare. Evita punteggi vaghi, celle unite, ID nascosti e formule dipendenti da servizi sconosciuti."], bullets: ["Stato e ID", "URL finale e titolo", "Immagine e variante", "Prezzo e valuta", "Data, regione e note"] },
        { heading: "Verifica la destinazione finale, non il testo del pulsante", paragraphs: ["Apri ogni link e registra l’indirizzo dopo i reindirizzamenti previsti. Controlla dominio e target reale, perché un pulsante può nascondere un URL abbreviato. Una risposta del server non basta: la pagina deve mostrare ID, titolo, immagine e opzione attesi. Prova l’URL finale in una sessione pulita e non salvare token di account o dati privati."] },
        { heading: "Applica lo stesso controllo a cinque campi", paragraphs: ["Confronta ID, titolo, prima immagine, variante e prezzo. Usa verificato, modificato, non disponibile, limitato per regione o da rivedere. Separa salute del link e corrispondenza prodotto: un URL attivo può aprire l’articolo sbagliato. Le note devono indicare con precisione cosa manca o è cambiato, facilitando il controllo successivo."] },
        { heading: "Controlla in gruppi senza abbassare lo standard", paragraphs: ["Inizia dalle righe cliccate, visibili o vecchie. Un controllo automatico può segnalare candidati, ma solo il confronto d’identità verifica il prodotto. Esamina poi gli errori: prima ID, quindi titolo e caratteristiche. Ogni sostituto riceve una nuova riga e la vecchia conserva lo storico. Le correzioni ampie vanno annotate con data."] },
        { heading: "Misura clic interpretabili", paragraphs: ["Usa testi d’azione chiari e mostra titolo, ID e stato vicino al link. Registra i clic esterni con destinazione, ID e percorso pagina, senza dati personali. Molti clic verso target errati non sono successo. Analizza clic insieme a coinvolgimento, ritorni e segnalazioni e, con poco traffico, aspetta schemi ripetuti prima di reagire a un solo giorno."] },
        { heading: "Pubblica con storico e regola di ricontrollo", paragraphs: ["Prima di pubblicare elimina ID duplicati, prova i target visibili, controlla campi obbligatori e mobile e mantieni un registro datato. Ricontrolla più spesso le righe popolari. Non cambiare automaticamente la data dopo una semplice risposta server; usa un campo diverso. La data di verifica deve significare che identità e variante sono state confrontate."], bullets: ["Eliminare ID duplicati", "Provare i target", "Controllare i campi", "Verificare su mobile", "Pubblicare lo storico"] },
      ],
      takeaways: ["Tratta ogni riga come record verificabile.", "Mostra ID e URL finali.", "Separa salute e corrispondenza.", "Crea nuove righe per i sostituti.", "Data dopo il controllo completo."],
    },
  },
};
