import type { Locale } from './site-data';

// Editorial changes informed by GSC page performance, 9 Sep–6 Oct 2026.
// A content revision date is not a live inventory or product-route verification date.
export const contentRevision = '2026-10-10';
export const refresh = {
  en: {
    shippingTitle: 'Hacoo Shipping: Delivery Time, Cost & Tracking',
    shippingIntro: 'Check Hacoo delivery estimates, shipping costs and tracking stages. Learn what to record before paying and what to do when an order is delayed.',
    qcTitle: 'Hacoo QC Photos: A Practical Inspection Checklist',
    qcIntro: 'Check the exact item, stitching, measurements and defects in Hacoo QC photos. Keep useful evidence before buying and when a delivery differs.',
    sheetTitle: 'Hacoo Spreadsheet: Product Links, IDs & Categories',
    sheetIntro: 'Browse product links with IDs and USD reference prices. Search the external catalog, compare the exact option and use our link-verification checklist.',
    qcArticleTitle: 'How to Check Hacoo QC Photos: Size, Stitching & Defects',
    qcArticleIntro: 'A step-by-step photo inspection method: confirm the item, compare measurements, inspect construction and record evidence for a clear decision.',
    codesTitle: 'Hacoo Product Codes: Find and Verify a Listing ID',
    codesIntro: 'Understand product IDs and listing routes, then compare the current item and option. This guide covers product references rather than discount coupons.',
    contents: 'On this page', next: 'Choose your next step', catalog: 'External product catalog',
    catalogNote: 'This search opens an independent external catalog. Its product IDs are not guaranteed to work in the official Hacoo app. Prices are USD reference amounts; confirm the current option and total at the destination.',
    browse: 'Browse product links', sourceNote: 'Editorial guidance and public Hacoo help pages reviewed 10 October 2026. Order-specific instructions take priority; this site does not handle orders, shipping or refunds.',
    sources: ['Hacoo — Shipping & Delivery; EU Help Center shipping articles.', 'Hacoo — Return & Refund Policy; Contact Us.', 'The practical record-keeping and inspection steps are independent editorial guidance.'],
    productNote: 'Reference listing', updated: 'Guides updated 10 October 2026', badge: 'Independent product research and guides',
    priceQuestion: 'What do the USD prices include?', priceAnswer: 'They are reference product amounts, not checkout totals. Check the selected option, delivery, taxes and current payment amount on the destination page.',
    shippingAnswer: 'Public Hacoo pages give general estimates that vary by destination. Follow the delivery window in your order and distinguish preparation, transport and local delivery; no general range guarantees an arrival date.',
    sections: {
      shipping: [
        ['How long does Hacoo delivery take?', 'Hacoo’s public shipping information gives a general 15–28 day estimate, while its destination table lists different ranges. These are guidance, not guaranteed arrival dates. Check the estimate shown for your destination and actual order before relying on a delivery date.', 'Keep preparation, carrier acceptance, international transport and local delivery separate. Do not add published stage ranges as if they were guaranteed sequential deadlines. If you need an item for an event, the shortest advertised example is not a safe planning assumption.'],
        ['How much does Hacoo shipping cost?', 'There is no single shipping charge verified for every cart and country. Read the current charge at checkout after choosing the real destination and exact items. Record the product subtotal, delivery fee, any displayed taxes, discounts and final total separately.', 'The USD amounts on our product cards are reference item prices. They do not quote Hacoo shipping and do not include a delivery promise. Our catalog links lead to an external service with its own checkout and shipping terms.'],
        ['Track the shipment and respond to exceptions', 'Use the shipment number inside the order, not the product ID printed on a listing. Compare the latest carrier event with the order’s delivery window. A fulfilment-hub message identifies a handling stage; its name alone cannot tell you the arrival day.', 'If the window has passed, send support the order number, shipment number, last event and date, and the displayed estimate. For delivered-but-missing or returned-to-sender events, use the specific steps in the tracking guide below.'],
      ],
      'qc-guide': [
        ['Start with identity, then inspect quality', 'Match the product ID, exact option, colour and included pieces before judging photographs. A polished image of another version is not evidence for the item you selected. Treat seller images and customer photos as different evidence sources.', 'Work from an overall view to construction details and measurements. Photos cannot establish authenticity, hidden materials or how an item will wear. Record what is visible, what differs from the description and what remains unknown.'],
        ['Keep photographs that support a decision', 'Use front, back and side views for proportions; close-ups for stitching, closures and edges; and a flat measuring tape for dimensions. Compare with an item you own using the same measurement method.', 'After delivery, keep an overall image, a view locating the issue and a sharp detail before washing or altering the item. Save original files and the order’s selected option. Use the photo guide and returns guide for the next step.'],
      ],
      spreadsheet: [
        ['Use the spreadsheet as a starting record', 'Search by a known product ID or a short descriptive phrase. Compare the first image, category, selected option and current destination before saving a candidate. A copied row is not a guarantee of availability.', 'Product IDs belong to their source catalog. Keep the source and ID together; a numeric page route is not necessarily the product identifier. Use categories for discovery, then move to the exact listing for comparison.'],
        ['Keep one record per product and option', 'Save the current URL, identifier, option, measurements and actual check date. Keep alternatives as separate records rather than silently replacing the item behind an old recommendation.', 'Read the link-verification guide for a fuller workflow. For an empty app search, use the search troubleshooting article; for a redirect or wrong destination, use the broken-link guide.'],
      ],
    },
    articleAdditions: {
      'articles/find-product-links': ['Separate the app from an external catalog', 'Record whether the link belongs to the official app or an independent catalog before searching its identifier. A catalog page number and a product ID may be different values, and neither is an order-tracking number. Our search opens the external catalog identified on the search form.', 'If the official app returns no results, test a simple description and your real destination before assuming the link has expired. If the URL opens a different item, compare the current identifier and selected option; retain the old evidence as unresolved instead of silently substituting another product.'],
      'articles/read-qc-photos': ['Turn the inspection into a clear decision', 'Use three outcomes: enough visible evidence to continue, a specific question that needs another photo, or a mismatch that stops the comparison. Write the observation behind that outcome. For example, a missing measurement is a request for evidence, while a different product ID requires identity checking before any quality judgement.', 'After receipt, connect the photos to the order and selected option. Keep the overall view, defect location and close-up together, with original files. Use the order-specific return instructions for deadlines and submission; a QC judgement is not automatic refund approval.'],
    },
  },
  de: {
    shippingTitle: 'Hacoo Versand: Lieferzeit, Versandkosten und Tracking', shippingIntro: 'Prüfe Hacoo-Lieferzeiten, Versandkosten und Sendungsstatus. Erfahre, welche Angaben vor dem Kauf und bei Verzögerungen wichtig sind.',
    qcTitle: 'Hacoo QC-Fotos: Checkliste für Maße und Verarbeitung', qcIntro: 'Prüfe Artikel, Nähte, Maße und sichtbare Fehler. Sichere brauchbare Belege vor dem Kauf und bei Abweichungen nach der Lieferung.',
    sheetTitle: 'Hacoo Spreadsheet: Produktlinks, IDs und Kategorien', sheetIntro: 'Produktlinks mit IDs und USD-Referenzpreisen durchsuchen, Varianten vergleichen und Einträge anhand einer klaren Checkliste prüfen.',
    qcArticleTitle: 'Hacoo QC-Fotos prüfen: Größe, Nähte und Mängel', qcArticleIntro: 'Schrittweise Fotos prüfen: Artikel bestätigen, Maße vergleichen, Verarbeitung ansehen und nachvollziehbare Belege sichern.',
    codesTitle: 'Hacoo Produktcodes: Listing-ID finden und prüfen', codesIntro: 'Produkt-IDs und Seitenrouten unterscheiden und aktuelle Varianten vergleichen. Dieser Ratgeber behandelt Produktreferenzen, keine Rabattcodes.',
    contents: 'In diesem Artikel', next: 'Den nächsten Schritt wählen', catalog: 'Externer Produktkatalog',
    catalogNote: 'Diese Suche öffnet einen unabhängigen externen Katalog. Dessen IDs funktionieren nicht garantiert in der offiziellen Hacoo-App. Preise sind USD-Referenzbeträge; aktuelle Variante und Gesamtsumme am Ziel prüfen.',
    browse: 'Produktlinks durchsuchen', sourceNote: 'Redaktionelle Hinweise und öffentliche Hacoo-Hilfeseiten geprüft am 10. Oktober 2026. Bestellbezogene Anweisungen haben Vorrang. Diese Website bearbeitet keine Bestellungen, Lieferungen oder Erstattungen.',
    sources: ['Hacoo — Shipping & Delivery; Versandartikel des EU Help Center.', 'Hacoo — Return & Refund Policy; Contact Us.', 'Dokumentations- und Prüfschritte sind unabhängige redaktionelle Hinweise.'],
    productNote: 'Referenzeintrag', updated: 'Ratgeber aktualisiert am 10. Oktober 2026', badge: 'Unabhängige Produktrecherche und Ratgeber',
    priceQuestion: 'Was enthalten die USD-Preise?', priceAnswer: 'Es sind Referenzpreise für Artikel, keine Endbeträge. Prüfe Variante, Versand, Steuern und aktuellen Zahlbetrag auf der Zielseite.',
    shippingAnswer: 'Öffentliche Hacoo-Seiten nennen je nach Ziel unterschiedliche Schätzungen. Nutze das Lieferfenster deiner Bestellung und trenne Vorbereitung, Transport und Zustellung. Eine allgemeine Spanne garantiert keinen Ankunftstag.',
    sections: {
      shipping: [
        ['Wie lange dauert die Hacoo-Lieferung?', 'Die öffentliche Versandinformation nennt allgemein 15–28 Tage, während die Ländertabelle abweichende Spannen enthält. Das sind Richtwerte, keine garantierten Termine. Prüfe die Schätzung für dein echtes Ziel und deine Bestellung.', 'Trenne Vorbereitung, Annahme durch den Zusteller, internationalen Transport und lokale Zustellung. Addiere veröffentlichte Phasen nicht zu garantierten Fristen. Für einen festen Anlass ist das kürzeste genannte Beispiel keine verlässliche Planung.'],
        ['Wie hoch sind die Hacoo-Versandkosten?', 'Eine einheitliche Gebühr für jeden Warenkorb und jedes Land ist nicht verifiziert. Prüfe den aktuellen Betrag beim Bezahlen nach Auswahl von echtem Ziel und Artikeln. Notiere Warenwert, Versand, ausgewiesene Steuern, Rabatte und Endbetrag getrennt.', 'Unsere USD-Beträge sind Artikelreferenzpreise. Sie nennen keine Hacoo-Versandgebühr und enthalten keine Lieferzusage. Die Kataloglinks führen zu einem externen Dienst mit eigenen Zahlungs- und Versandbedingungen.'],
        ['Sendung verfolgen und auf Ausnahmen reagieren', 'Nutze die Sendungsnummer aus der Bestellung, nicht die Produkt-ID einer Karte. Vergleiche letztes Ereignis und Lieferfenster. Ein Fulfilment-Hub-Status bezeichnet eine Bearbeitungsphase; sein Name verrät keinen Ankunftstag.', 'Bei überschrittenem Fenster sende Bestellnummer, Trackingnummer, letztes Ereignis mit Datum und Schätzung an den Support. Für zugestellt, aber nicht erhalten und Rücksendung an den Absender nutze die Schritte im Trackingratgeber.'],
      ],
      'qc-guide': [
        ['Erst Identität, dann Verarbeitung prüfen', 'Gleiche Produkt-ID, genaue Option, Farbe und enthaltene Teile ab. Ein gutes Bild einer anderen Version belegt nicht den gewählten Artikel. Trenne Verkäuferbilder und Kundenfotos als unterschiedliche Belegarten.', 'Gehe von Gesamtansicht zu Details und Maßen. Fotos belegen weder Echtheit noch verborgene Materialien oder Haltbarkeit. Notiere Sichtbares, Abweichungen zur Beschreibung und offene Punkte.'],
        ['Fotos für eine nachvollziehbare Entscheidung sichern', 'Nutze Vorder-, Rück- und Seitenansichten für Proportionen, Nahaufnahmen für Nähte und Verschlüsse sowie ein flaches Maßband für Abmessungen. Vergleiche mit einem eigenen Artikel nach derselben Methode.', 'Sichere nach Erhalt Gesamtansicht, Fehlerposition und scharfes Detail vor Waschen oder Veränderung. Behalte Originaldateien und gewählte Bestelloption. Foto- und Retourenratgeber erklären den nächsten Schritt.'],
      ],
      spreadsheet: [
        ['Die Tabelle als Ausgangspunkt verwenden', 'Suche eine bekannte ID oder kurze Beschreibung. Vergleiche erstes Bild, Kategorie, gewählte Option und aktuelles Ziel vor dem Speichern. Eine kopierte Zeile garantiert keine Verfügbarkeit.', 'Produkt-IDs gehören zum jeweiligen Katalog. Bewahre Quelle und ID zusammen auf; eine numerische Seitenroute muss nicht die Produktkennung sein. Nutze Kategorien zum Entdecken und anschließend die genaue Produktseite zum Vergleich.'],
        ['Pro Artikel und Option einen Datensatz führen', 'Speichere aktuelle URL, Kennung, Option, Maße und echtes Prüfdatum. Führe Alternativen separat, statt einen Artikel hinter einer alten Empfehlung stillschweigend auszutauschen.', 'Der Linkprüfratgeber erklärt den vollständigen Ablauf. Bei leerer App-Suche hilft die Suchdiagnose, bei Weiterleitung oder falschem Ziel der Ratgeber zu defekten Links.'],
      ],
    },
    articleAdditions: {
      'articles/find-product-links': ['App und externen Katalog unterscheiden', 'Notiere vor der ID-Suche, ob ein Link zur offiziellen App oder zu einem unabhängigen Katalog gehört. Katalogseitennummer und Produkt-ID können verschieden sein; beide sind keine Sendungsnummer. Unsere Suche öffnet den am Formular beschriebenen externen Katalog.', 'Bei leeren App-Ergebnissen teste eine einfache Beschreibung und das echte Lieferziel, bevor du den Link für abgelaufen hältst. Öffnet die URL einen anderen Artikel, prüfe Kennung und Variante und behalte die alte Zuordnung ungeklärt, statt still einen Ersatz einzusetzen.'],
      'articles/read-qc-photos': ['Aus der Prüfung eine klare Entscheidung ableiten', 'Verwende drei Ergebnisse: genug sichtbare Belege zum Fortfahren, eine konkrete Frage für ein zusätzliches Foto oder eine Abweichung, die den Vergleich stoppt. Notiere die Beobachtung dahinter. Ein fehlendes Maß braucht einen Nachweis; eine andere Produkt-ID erfordert zuerst Identitätsprüfung.', 'Ordne nach Erhalt Fotos der Bestellung und Option zu. Halte Gesamtansicht, Fehlerposition und Nahaufnahme mit Originaldateien zusammen. Fristen und Einreichung richten sich nach den Bestellanweisungen; eine QC-Bewertung genehmigt keine Erstattung.'],
    },
  },
  fr: {
    shippingTitle: 'Livraison Hacoo : délais, frais et suivi', shippingIntro: 'Comprendre les délais Hacoo, vérifier les frais et suivre les étapes du colis. Les informations à conserver avant paiement et en cas de retard.',
    qcTitle: 'Photos QC Hacoo : checklist de contrôle et mesures', qcIntro: 'Vérifiez article, coutures, mesures et défauts visibles. Gardez des preuves utiles avant achat et lorsqu’une livraison diffère.',
    sheetTitle: 'Tableur Hacoo : liens produits, identifiants et catégories', sheetIntro: 'Parcourez liens, identifiants et prix de référence en USD. Recherchez dans le catalogue externe et comparez chaque option avant de décider.',
    qcArticleTitle: 'Vérifier les photos QC Hacoo : taille, coutures et défauts', qcArticleIntro: 'Une méthode photo étape par étape pour confirmer le produit, comparer ses mesures, inspecter sa fabrication et conserver des preuves.',
    codesTitle: 'Codes produit Hacoo : trouver et vérifier un identifiant', codesIntro: 'Distinguez identifiants et routes, puis comparez produit et option actuels. Ce guide traite des références produit, pas des codes promotionnels.',
    contents: 'Dans cet article', next: 'Choisir la prochaine étape', catalog: 'Catalogue produit externe',
    catalogNote: 'Cette recherche ouvre un catalogue externe indépendant. Ses identifiants ne fonctionnent pas nécessairement dans l’application Hacoo officielle. Les prix sont des références en USD ; vérifiez option et total à destination.',
    browse: 'Parcourir les liens produits', sourceNote: 'Conseils éditoriaux et pages publiques d’aide Hacoo examinés le 10 octobre 2026. Les instructions de commande priment. Ce site ne traite ni commandes, ni livraisons, ni remboursements.',
    sources: ['Hacoo — Shipping & Delivery ; articles de livraison du EU Help Center.', 'Hacoo — Return & Refund Policy ; Contact Us.', 'Les méthodes de documentation et d’inspection sont des conseils éditoriaux indépendants.'],
    productNote: 'Fiche de référence', updated: 'Guides actualisés le 10 octobre 2026', badge: 'Recherche produit et guides indépendants',
    priceQuestion: 'Que comprennent les prix en USD ?', priceAnswer: 'Ce sont des montants produit de référence, pas des totaux de commande. Vérifiez option, livraison, taxes et montant actuel sur la page de destination.',
    shippingAnswer: 'Les pages publiques Hacoo donnent des estimations variant selon la destination. Suivez la fenêtre de votre commande et distinguez préparation, transport et livraison locale. Aucun intervalle général ne garantit une date.',
    sections: {
      shipping: [
        ['Combien de temps prend la livraison Hacoo ?', 'La page publique de livraison cite généralement 15–28 jours, mais son tableau par pays donne des intervalles différents. Ce sont des indications, pas des dates garanties. Vérifiez l’estimation correspondant au véritable pays et à votre commande.', 'Séparez préparation, prise en charge, transport international et livraison locale. N’additionnez pas les phases publiées comme des délais garantis. Pour un événement à date fixe, le plus court exemple annoncé ne constitue pas une base fiable.'],
        ['Combien coûtent les frais de livraison Hacoo ?', 'Aucun tarif unique n’est vérifié pour tous les paniers et pays. Lisez le montant actuel au paiement après sélection des articles et de la vraie destination. Notez séparément sous-total, livraison, taxes affichées, réductions et total.', 'Les montants USD de nos cartes sont des références produit. Ils ne chiffrent pas le transport Hacoo et ne promettent aucune livraison. Les liens ouvrent un service externe avec ses propres conditions de paiement et d’expédition.'],
        ['Suivre le colis et traiter les exceptions', 'Utilisez la référence d’expédition de la commande, pas l’identifiant d’une fiche. Comparez dernier événement et fenêtre annoncée. Un statut de centre de traitement décrit une étape ; son nom ne donne pas la date d’arrivée.', 'Après dépassement, transmettez au support commande, suivi, dernier événement daté et estimation affichée. Pour livré mais absent ou retour à l’expéditeur, suivez les étapes du guide de suivi ci-dessous.'],
      ],
      'qc-guide': [
        ['Confirmer l’identité avant la qualité', 'Rapprochez identifiant, option exacte, couleur et pièces incluses. Une belle image d’une autre version ne prouve rien pour votre sélection. Distinguez photos vendeur et photos clients.', 'Passez de la vue globale aux détails puis aux mesures. Une photo ne prouve ni authenticité, ni matériaux cachés, ni tenue dans le temps. Notez visible, écarts avec la description et inconnues.'],
        ['Conserver des photos utiles à la décision', 'Utilisez face, dos et profil pour les proportions ; gros plans pour coutures, fermetures et bords ; mètre à plat pour les dimensions. Comparez avec un article personnel mesuré de la même façon.', 'À réception, gardez vue générale, localisation du défaut et détail net avant lavage ou modification. Conservez originaux et option commandée. Les guides photo et retours expliquent la suite.'],
      ],
      spreadsheet: [
        ['Utiliser le tableur comme point de départ', 'Recherchez un identifiant connu ou une courte description. Comparez première image, catégorie, option et destination actuelle avant de sauvegarder un candidat. Une ligne copiée ne garantit pas la disponibilité.', 'Les identifiants appartiennent à leur catalogue. Gardez source et ID ensemble ; une route numérique n’est pas nécessairement l’identifiant produit. Explorez par catégorie puis comparez la fiche exacte.'],
        ['Conserver une fiche par produit et option', 'Enregistrez URL actuelle, identifiant, option, mesures et vraie date de contrôle. Gardez les alternatives séparées au lieu de modifier silencieusement une ancienne recommandation.', 'Le guide de vérification détaille le parcours. Pour une recherche vide dans l’app, utilisez le diagnostic de recherche ; pour une redirection ou mauvaise destination, le guide des liens cassés.'],
      ],
    },
    articleAdditions: {
      'articles/find-product-links': ['Distinguer application et catalogue externe', 'Avant de rechercher un identifiant, notez si le lien vient de l’application officielle ou d’un catalogue indépendant. Numéro de page et ID produit peuvent différer ; aucun n’est un numéro de suivi. Notre formulaire ouvre le catalogue externe qu’il décrit.', 'Si l’application ne renvoie rien, testez une description simple et votre vraie destination avant de déclarer le lien périmé. Si l’URL ouvre un autre article, comparez identifiant et option puis conservez l’association ancienne non résolue, sans remplacement silencieux.'],
      'articles/read-qc-photos': ['Transformer le contrôle en décision claire', 'Retenez trois issues : preuves visibles suffisantes pour continuer, question précise nécessitant une photo, ou écart qui arrête la comparaison. Notez l’observation correspondante. Une mesure manquante nécessite une preuve ; un identifiant différent exige d’abord de vérifier l’identité.', 'Après réception, reliez les photos à la commande et à l’option. Regroupez vue générale, localisation et détail avec les originaux. Délais et dépôt suivent les instructions de commande ; un avis QC ne vaut pas autorisation de remboursement.'],
    },
  },
  es: {
    shippingTitle: 'Envíos Hacoo: cuánto tarda, gastos y seguimiento', shippingIntro: 'Consulta plazos Hacoo, comprueba gastos de envío y entiende el seguimiento. Qué guardar antes de pagar y cómo actuar ante un retraso.',
    qcTitle: 'Fotos QC Hacoo: checklist de medidas y defectos', qcIntro: 'Comprueba artículo, costuras, medidas y defectos visibles. Conserva pruebas útiles antes de comprar y ante diferencias en la entrega.',
    sheetTitle: 'Hoja Hacoo: enlaces de productos, ID y categorías', sheetIntro: 'Explora enlaces con ID y precios de referencia en USD. Busca en el catálogo externo y compara cada opción con una checklist de verificación.',
    qcArticleTitle: 'Cómo revisar fotos QC Hacoo: talla, costuras y defectos', qcArticleIntro: 'Un método fotográfico paso a paso para confirmar identidad, comparar medidas, revisar construcción y guardar pruebas útiles.',
    codesTitle: 'Códigos de producto Hacoo: encontrar y verificar el ID', codesIntro: 'Distingue ID y rutas de fichas y compara producto y opción actuales. Esta guía trata referencias de productos, no cupones de descuento.',
    contents: 'En este artículo', next: 'Elige el siguiente paso', catalog: 'Catálogo externo de productos',
    catalogNote: 'Esta búsqueda abre un catálogo externo independiente. Sus ID no tienen por qué funcionar en la aplicación Hacoo oficial. Los precios son referencias en USD; confirma opción y total en el destino.',
    browse: 'Explorar enlaces de productos', sourceNote: 'Consejos editoriales y ayuda pública Hacoo revisados el 10 de octubre de 2026. Prevalecen las instrucciones del pedido. Este sitio no gestiona compras, envíos ni reembolsos.',
    sources: ['Hacoo — Shipping & Delivery; artículos de envío del EU Help Center.', 'Hacoo — Return & Refund Policy; Contact Us.', 'Los pasos de documentación e inspección son orientación editorial independiente.'],
    productNote: 'Ficha de referencia', updated: 'Guías actualizadas el 10 de octubre de 2026', badge: 'Investigación y guías de productos independientes',
    priceQuestion: '¿Qué incluyen los precios en USD?', priceAnswer: 'Son importes de referencia del artículo, no totales de compra. Revisa opción, envío, impuestos e importe actual en la página de destino.',
    shippingAnswer: 'Las páginas públicas Hacoo dan estimaciones que varían según el destino. Sigue el intervalo de tu pedido y distingue preparación, transporte y reparto. Ningún intervalo general garantiza una fecha.',
    sections: {
      shipping: [
        ['Cuánto tarda un pedido Hacoo', 'La información pública menciona generalmente 15–28 días, pero su tabla por países muestra otros intervalos. Son orientaciones, no fechas garantizadas. Comprueba la estimación para tu destino real y pedido concreto.', 'Separa preparación, aceptación del transportista, transporte internacional y reparto local. No sumes fases publicadas como plazos garantizados. Para una fecha importante, el ejemplo más rápido no es una base fiable de planificación.'],
        ['Cuánto cuestan los gastos de envío Hacoo', 'No hay una tarifa única verificada para todos los carritos y países. Lee el cargo actual al pagar tras elegir destino real y artículos exactos. Anota subtotal, transporte, impuestos mostrados, descuentos y total por separado.', 'Los importes USD de nuestras tarjetas son referencias de producto. No cotizan el envío Hacoo ni prometen entrega. Los enlaces abren un servicio externo con condiciones propias de pago y transporte.'],
        ['Sigue el envío y responde a las incidencias', 'Usa el número de envío del pedido, no el ID de la ficha. Compara el último evento con el intervalo estimado. Un mensaje de centro de procesamiento describe una fase; el nombre no indica el día de llegada.', 'Si se supera el plazo, envía a soporte pedido, seguimiento, último evento con fecha y estimación. Para entregado pero ausente o devuelto al remitente, consulta los pasos de la guía de seguimiento.'],
      ],
      'qc-guide': [
        ['Confirma la identidad antes de evaluar calidad', 'Compara ID, opción exacta, color y piezas incluidas. Una buena imagen de otra versión no demuestra nada sobre tu selección. Distingue imágenes del vendedor y fotos de compradores.', 'Pasa de vista general a detalles y medidas. Las fotos no prueban autenticidad, materiales ocultos o duración. Registra lo visible, lo diferente de la descripción y lo desconocido.'],
        ['Conserva fotos que permitan decidir', 'Usa frontal, trasera y lateral para proporciones; detalles para costuras, cierres y bordes; cinta plana para dimensiones. Compara con un artículo propio medido igual.', 'Tras recibirlo, conserva vista completa, ubicación del problema y detalle nítido antes de lavar o modificar. Guarda originales y opción comprada. Las guías de fotos y devoluciones explican el siguiente paso.'],
      ],
      spreadsheet: [
        ['Usa la hoja como registro inicial', 'Busca por ID conocido o frase descriptiva corta. Compara primera imagen, categoría, variante y destino actual antes de guardar candidatos. Una fila copiada no garantiza disponibilidad.', 'Los ID pertenecen al catálogo de origen. Mantén fuente e ID juntos; una ruta numérica no siempre es el identificador. Explora categorías y después compara la ficha exacta.'],
        ['Guarda un registro por producto y opción', 'Conserva URL actual, ID, variante, medidas y fecha real de revisión. Mantén alternativas separadas en vez de sustituir silenciosamente una recomendación antigua.', 'La guía de verificación explica el proceso completo. Para búsquedas vacías usa el diagnóstico de búsqueda; para redirecciones o destinos incorrectos, la guía de enlaces rotos.'],
      ],
    },
    articleAdditions: {
      'articles/find-product-links': ['Separa la aplicación del catálogo externo', 'Antes de buscar un identificador, anota si el enlace pertenece a la app oficial o a un catálogo independiente. Número de página e ID pueden ser valores diferentes y ninguno sirve para seguir un pedido. Nuestro formulario abre el catálogo externo descrito junto a él.', 'Si la app no devuelve resultados, prueba una descripción simple y el destino real antes de considerar caducado el enlace. Si abre otro artículo, compara ID y opción; conserva la asociación antigua sin resolver en vez de sustituirla en silencio.'],
      'articles/read-qc-photos': ['Convierte la inspección en una decisión clara', 'Usa tres resultados: pruebas visibles suficientes para continuar, pregunta concreta que exige otra foto o discrepancia que detiene la comparación. Escribe la observación que lo justifica. Una medida ausente necesita pruebas; un ID diferente requiere confirmar identidad primero.', 'Después de recibirlo, relaciona fotos con pedido y opción. Guarda vista general, ubicación del defecto y detalle con sus originales. Los plazos y la presentación dependen de las instrucciones del pedido; una valoración QC no aprueba automáticamente un reembolso.'],
    },
  },
  it: {
    shippingTitle: 'Spedizione Hacoo: tempi, costi e tracking', shippingIntro: 'Controlla tempi di consegna Hacoo, costi e stato del pacco. Scopri cosa salvare prima del pagamento e come gestire un ritardo.',
    qcTitle: 'Foto QC Hacoo: checklist per misure e difetti', qcIntro: 'Verifica articolo, cuciture, misure e difetti visibili. Conserva prove utili prima di acquistare e quando la consegna presenta differenze.',
    sheetTitle: 'Foglio Hacoo: link prodotto, ID e categorie', sheetIntro: 'Esplora link con ID e prezzi indicativi in USD. Cerca nel catalogo esterno e confronta la variante esatta con una checklist di verifica.',
    qcArticleTitle: 'Controllare foto QC Hacoo: taglie, cuciture e difetti', qcArticleIntro: 'Un metodo fotografico passo passo per confermare identità, confrontare misure, controllare costruzione e conservare prove.',
    codesTitle: 'Codici prodotto Hacoo: trovare e verificare l’ID', codesIntro: 'Distingui ID e percorsi delle schede, poi confronta articolo e variante attuali. La guida riguarda riferimenti prodotto, non codici sconto.',
    contents: 'In questo articolo', next: 'Scegli il prossimo passo', catalog: 'Catalogo prodotti esterno',
    catalogNote: 'La ricerca apre un catalogo esterno indipendente. I suoi ID non funzionano necessariamente nell’app ufficiale Hacoo. I prezzi sono riferimenti in USD: conferma variante e totale nella destinazione.',
    browse: 'Esplora i link prodotto', sourceNote: 'Indicazioni editoriali e pagine pubbliche Hacoo riviste il 10 ottobre 2026. Prevalgono le istruzioni dell’ordine. Questo sito non gestisce acquisti, spedizioni o rimborsi.',
    sources: ['Hacoo — Shipping & Delivery; articoli sulle spedizioni del EU Help Center.', 'Hacoo — Return & Refund Policy; Contact Us.', 'I passaggi di documentazione e controllo sono indicazioni editoriali indipendenti.'],
    productNote: 'Scheda di riferimento', updated: 'Guide aggiornate il 10 ottobre 2026', badge: 'Ricerca prodotti e guide indipendenti',
    priceQuestion: 'Cosa includono i prezzi in USD?', priceAnswer: 'Sono importi indicativi del prodotto, non totali di pagamento. Controlla variante, spedizione, imposte e importo attuale nella pagina di destinazione.',
    shippingAnswer: 'Le pagine pubbliche Hacoo riportano stime diverse secondo la destinazione. Usa la finestra del tuo ordine e separa preparazione, trasporto e consegna locale. Nessun intervallo generale garantisce un giorno di arrivo.',
    sections: {
      shipping: [
        ['Quanto impiega la consegna Hacoo', 'La pagina pubblica indica generalmente 15–28 giorni, mentre la tabella per paese riporta intervalli differenti. Sono indicazioni, non date garantite. Verifica la stima della destinazione reale e dell’ordine concreto.', 'Separa preparazione, accettazione del corriere, trasporto internazionale e consegna locale. Non sommare le fasi pubblicate come scadenze garantite. Per un evento con data fissa, l’esempio più rapido non è una base affidabile.'],
        ['Quanto costa la spedizione Hacoo', 'Non è verificata una tariffa unica per ogni carrello e paese. Leggi il costo attuale al pagamento dopo aver scelto destinazione reale e articoli. Registra separatamente subtotale, trasporto, imposte mostrate, sconti e totale.', 'Gli importi USD sulle nostre schede sono riferimenti del prodotto. Non quotano la spedizione Hacoo e non promettono consegna. I link aprono un servizio esterno con proprie condizioni di pagamento e trasporto.'],
        ['Seguire la spedizione e gestire le eccezioni', 'Usa il numero di spedizione nell’ordine, non l’ID della scheda. Confronta ultimo evento e finestra stimata. Un messaggio relativo a un centro di lavorazione descrive una fase: il nome non rivela il giorno di arrivo.', 'Se la finestra scade, invia all’assistenza ordine, tracking, ultimo evento datato e stima mostrata. Per consegnato ma assente o ritorno al mittente, segui la guida al tracking.'],
      ],
      'qc-guide': [
        ['Prima identità, poi qualità', 'Abbina ID, opzione esatta, colore e pezzi inclusi. Una bella foto di un’altra versione non documenta quella selezionata. Distingui immagini del venditore e foto dei clienti.', 'Passa dalla vista generale a dettagli e misure. Le foto non dimostrano autenticità, materiali nascosti o durata. Registra ciò che vedi, differenze dalla descrizione e informazioni mancanti.'],
        ['Conservare foto utili alla decisione', 'Usa fronte, retro e lato per proporzioni, primi piani per cuciture e chiusure, metro piatto per dimensioni. Confronta un articolo personale misurato con lo stesso metodo.', 'Dopo la consegna conserva vista completa, posizione del problema e dettaglio nitido prima di lavare o modificare. Salva originali e opzione ordinata. Le guide foto e resi spiegano il passo successivo.'],
      ],
      spreadsheet: [
        ['Usare il foglio come punto di partenza', 'Cerca un ID noto o una breve descrizione. Confronta prima immagine, categoria, variante e destinazione attuale prima di salvare un candidato. Una riga copiata non garantisce disponibilità.', 'Gli ID appartengono al catalogo d’origine. Conserva fonte e ID insieme: un percorso numerico non è necessariamente il codice prodotto. Esplora le categorie e confronta poi la scheda esatta.'],
        ['Un record per prodotto e variante', 'Salva URL attuale, identificatore, opzione, misure e vera data di controllo. Mantieni separate le alternative invece di sostituire silenziosamente una vecchia raccomandazione.', 'La guida alla verifica spiega il percorso completo. Per ricerche vuote usa la diagnosi della ricerca; per reindirizzamenti o destinazioni errate, la guida ai link interrotti.'],
      ],
    },
    articleAdditions: {
      'articles/find-product-links': ['Distinguere app e catalogo esterno', 'Prima di cercare un ID, annota se il link appartiene all’app ufficiale o a un catalogo indipendente. Numero di pagina e identificatore possono essere diversi e nessuno dei due è un numero di tracking. Il nostro modulo apre il catalogo esterno descritto accanto alla ricerca.', 'Se l’app non restituisce risultati, prova una descrizione semplice e la destinazione reale prima di dichiarare il link scaduto. Se l’URL apre un altro articolo, confronta ID e variante e conserva la vecchia associazione irrisolta invece di sostituirla in silenzio.'],
      'articles/read-qc-photos': ['Trasformare il controllo in una decisione chiara', 'Usa tre esiti: prove visibili sufficienti per continuare, domanda precisa che richiede un’altra foto o discrepanza che ferma il confronto. Scrivi l’osservazione corrispondente. Una misura assente richiede una prova; un ID diverso richiede prima la verifica dell’identità.', 'Dopo la ricezione collega le foto a ordine e variante. Conserva insieme vista generale, posizione del difetto e dettaglio con i file originali. Scadenze e invio seguono le istruzioni dell’ordine: una valutazione QC non approva automaticamente un rimborso.'],
    },
  },
} satisfies Record<Locale, unknown>;
