import type { ArticleRecord } from "./article-data";

const reviewed = { published: "2026-10-07", updated: "2026-10-07", updatedLabel: "October 7, 2026", readingTime: 8, faq: [] };

export const priorityArticles: ArticleRecord[] = [
  {
    slug: "acbuy-rehearsal-packing-guide",
    shortTitle: "ACBuy Rehearsal Packing",
    title: "ACBuy Rehearsal Packing: Weight, Dimensions and Quote Checks",
    seoTitle: "ACBuy Rehearsal Packing Guide | Weight & Shipping Quotes",
    description: "Understand ACBuy rehearsal packing, prepare packing instructions and compare weight, dimensions and shipping quotes before submitting a parcel.",
    category: "Packing tutorial", primaryKeyword: "acbuy rehearsal packing",
    secondaryKeywords: ["acbuy rehearsal shipping", "acbuy shipping estimate", "acbuy parcel dimensions"],
    dek: "A useful rehearsal request reduces uncertainty about a specific parcel. Start with inspected items, clear packaging instructions and a route comparison you can reproduce.",
    researchNote: "ACBuy’s official Shopping Guide describes rehearsal as a paid simulated packaging service, not actual packaging. This tutorial explains how to prepare and interpret that service; the live account controls its price, options and results.",
    ...reviewed,
    visual: { kind: "flow", items: ["Finish QC", "List items", "Specify packing", "Review measurements", "Compare routes"], caption: "Rehearsal is a planning checkpoint. Final parcel measurements and the selected route determine the payable shipping amount." },
    sections: [
      { heading: "Separate rehearsal from final dispatch", paragraphs: [
        "An ACBuy rehearsal packing request belongs between warehouse inspection and a confident shipping decision. Its purpose is to make the proposed parcel easier to evaluate. It does not mean that a carrier has collected your goods, and a rehearsal result should not be interpreted as a tracking event. Keep the warehouse item list, rehearsal request and submitted international parcel distinct in your records. This prevents confusion when a measurement is available but no international tracking number has appeared.",
        "The official guide calls rehearsal a simulated packaging service and states that a service fee applies. Do not assume it includes final packing, international freight, insurance or every optional packaging material. Before confirming, read the current service description and charge shown in the account. If the screen does not explain whether a later packaging change requires another calculation, ask support about that specific request. A clear answer is more useful than a price remembered from another buyer’s shipment."
      ] },
      { heading: "Complete inspection before choosing the item list", paragraphs: [
        "Start with products that have arrived and that you actually intend to keep. Check their order identifiers, selected variants, quantities and warehouse photographs. Resolve a wrong size, missing accessory or visible defect before building a shipping plan around that item. If you later remove a product, add a replacement or change a quantity, the earlier parcel estimate may no longer describe what you will send. Rehearsal cannot compensate for an inaccurate contents list.",
        "Save a simple list containing the warehouse identifier, product type, quantity, available weight and any packaging requirement for each item. Separate a pair of shoes from a soft garment and from a fragile accessory because their protection needs differ. Avoid copying private address or payment details into a public spreadsheet. The reusable information is the composition of the parcel and the decisions affecting its dimensions, not the personal information attached to the account."
      ] },
      { heading: "Write packing instructions that can be followed", paragraphs: [
        "A request such as cheapest possible packing leaves too much open to interpretation. Describe which packaging may be removed, which must remain, and what needs protection. If keeping a shoe box matters to you, say so; if it does not, evaluate whether removing it could expose the footwear to deformation or abrasion. With clothing, consider whether compression suits the fabric, decoration and intended condition. Reducing volume is useful only if the resulting protection remains acceptable.",
        "Keep instructions consistent across the rehearsal and final parcel. For example, a plan that keeps both shoe boxes cannot be compared fairly with a later parcel that removes them and adds reinforcement. Record the chosen options beside the result so you can explain a difference. Do not assume that a service displayed for another product or destination is available for yours. Select only options actually offered in the account, and request clarification when a combination appears incompatible."
      ] },
      { heading: "Read actual weight and dimensions together", paragraphs: [
        "A scale measurement and a dimensional measurement answer different questions. Actual weight describes mass; dimensions describe the space occupied by the packed parcel. The route may use actual weight, dimensional weight or another published billing rule. Check the selected line’s method before comparing prices. Length, width and height must use the units required by that method. A millimetre value entered as centimetres can produce an unusable calculation even when the formula itself is correct.",
        "Here is an illustrative calculation, not an ACBuy rate: a parcel measuring 40 by 30 by 25 centimetres has a volume of 30,000 cubic centimetres. If a hypothetical route uses a divisor of 6,000, its dimensional weight is 5 kilograms. With an actual weight of 3.5 kilograms and a higher-of-two rule, the starting chargeable weight would be 5 kilograms before any rounding. Substitute the live route’s divisor and increments; do not carry this example into a quote unchanged."
      ] },
      { heading: "Compare routes using one consistent scenario", paragraphs: [
        "Use the same destination, contents and packing plan when comparing shipping lines. Record the quote date, actual weight, dimensions, billing rule, displayed shipping charge and selected extras. Also note restrictions, available tracking and the stated delivery estimate. A cheaper line is not a usable alternative if it excludes an item in your parcel. A faster estimate is not a guaranteed arrival date. Keep eligibility and price in the same comparison rather than choosing from the headline amount alone.",
        "Distinguish the rehearsal service charge from any potential shipping reduction. A lower estimate does not automatically mean the service paid for itself, especially if other optional charges changed at the same time. Compare complete payable amounts under equivalent assumptions. If a quote is in a different currency from the product prices in your notes, label both currencies and the date of any conversion. Apparent savings can otherwise come from inconsistent arithmetic rather than a better parcel plan."
      ] },
      { heading: "Choose consolidation or separation deliberately", paragraphs: [
        "Combining items can avoid repeating certain parcel charges, but adding more products can also increase dimensional weight or affect route eligibility. Evaluate the combined parcel against realistic separate parcels when those differences matter. Do not invent the dimensions of a split parcel merely to make separation appear cheaper. Use available warehouse information and request further information if it is necessary to make the comparison meaningful. The answer depends on the actual contents and current options.",
        "A fragile item and several compressible garments may create competing packaging needs. Keeping them together could require protection that changes the size of the whole parcel. Keeping them separate could repeat a starting charge. Neither outcome is universal. Document the trade-off and select the arrangement that fits the goods, cost and acceptable handling risk. Splitting a shipment does not guarantee a customs result, and parcel organisation should never rely on such a promise."
      ] },
      { heading: "Reconcile changes before paying for shipping", paragraphs: [
        "Before final submission, compare the selected warehouse items with the rehearsal list one last time. Confirm quantities, required packaging and the destination. If the final quote differs, examine the recorded weight, dimensions, route and service selections in that order. A small measurement change can cross a billing increment; an additional material can change weight; a route can become unavailable. These are possibilities to investigate, not explanations to assume without looking at the records.",
        "Keep the original request and result until delivery is complete. When asking about a discrepancy, identify the request, show the relevant measurements and state exactly which charge changed. Avoid sending only two unexplained totals. The purpose is to obtain a comparable calculation, not to insist that an earlier estimate must always equal a later invoice. If the explanation is incomplete, resolve it before committing to a shipping option you do not understand."
      ] },
      { heading: "Use rehearsal where uncertainty matters", paragraphs: [
        "Rehearsal is most useful when uncertainty about packing materially affects your choice. Bulky packaging, mixed product types, unclear dimensions or a close comparison between routes can justify a closer look. If all relevant measurements and options are already clear, examine the service description before paying for information you may already have. This is a decision framework, not a recommendation to purchase the service for every order.",
        "A good final record contains the contents, packing instructions, measurement units, quoted route, date and total components. Those details let you revisit the decision without reconstructing it from memory. Continue with the shipping-cost guide for the wider budget and the dimensional-weight article for the calculation logic. Then return to the live parcel screen for the current offer. The rehearsal result supports that decision; it does not replace checking the parcel you actually submit."
      ] }
    ]
  },
  {
    slug: "acbuy-order-status-guide",
    shortTitle: "ACBuy Order Status",
    title: "ACBuy Order Status: From Purchased to Stored, Step by Step",
    seoTitle: "ACBuy Order Status Guide | Purchased, Seller Sent & Stored",
    description: "Understand ACBuy order statuses, distinguish seller delivery from international shipping and prepare useful evidence when an order stops progressing.",
    category: "Order tutorial", primaryKeyword: "acbuy order status",
    secondaryKeywords: ["acbuy purchased", "acbuy seller sent", "acbuy being stored", "acbuy order not updating"],
    dek: "An order status describes one stage of the purchasing and warehouse process. Read it alongside the order details before deciding whether to wait, check an action or contact support.",
    researchNote: "The status sequence comes from ACBuy’s official Shopping Guide: Under review, Purchased, Seller Sent, Delivered, Being Stored and Stored. The explanations below distinguish that published sequence from practical troubleshooting advice; no fixed processing time is promised.",
    ...reviewed,
    visual: { kind: "flow", items: ["Review", "Purchase", "Seller delivery", "Warehouse processing", "Stored"], caption: "Domestic order progress ends at warehouse storage. International parcel submission is a separate step." },
    sections: [
      { heading: "Begin with the correct order record", paragraphs: [
        "Open the exact order rather than relying on a general account notification. Match its source product, selected size or colour, quantity and purchase date with your saved choice. If several similar products were ordered, use the identifier to keep them separate. One order can progress while another remains at an earlier stage. An account-level impression that everything is delayed may simply combine different sellers or products with different histories.",
        "Record the current status, the time of the last visible update and any action requested in the order. Check whether the account shows an unread message about stock, specifications or a price difference. These details are more useful than repeatedly refreshing the list. A status is a summary label; the associated message may explain what needs to happen next. Do not supply additional payment or change an option until you understand which order and charge the request concerns."
      ] },
      { heading: "Read Under review as a purchasing checkpoint", paragraphs: [
        "Under review appears at the beginning of the official order sequence. Treat it as a reason to inspect the submitted information, not as evidence that the seller has dispatched the product. Ensure that the source link still identifies the intended listing and that size, colour, quantity and remarks are unambiguous. A manually entered order deserves particular attention because the purchasing instructions depend on the information supplied by the buyer.",
        "If clarification is requested, answer the actual question with a measurable choice. A size code or listed option is clearer than a request for the best version. Keep a record of any agreed change so it can be compared with the warehouse item later. The public status sequence does not establish a universal review deadline. Use the current order information and any response from the assigned agent to assess the particular case instead of borrowing another buyer’s timeline."
      ] },
      { heading: "Distinguish Purchased from Seller Sent", paragraphs: [
        "Purchased and Seller Sent are separate labels in the official flow. Purchased should not be treated as proof of international dispatch, or even as a substitute for the later seller-shipment information. The important next check is whether the order details show progress towards domestic delivery. Review messages about availability or changed specifications before assuming that the original listing remains unchanged. Keep all decisions tied to that order rather than to a general product recommendation.",
        "When the status reaches Seller Sent, look for the domestic delivery information available in the account. That movement concerns the seller-to-warehouse stage. It is not the same shipment as the eventual parcel to your home. If domestic tracking exists, compare its latest event with the order status; the two systems may update at different moments. A missing update alone does not identify who caused a delay. Ask about the specific stage and available evidence."
      ] },
      { heading: "Separate Delivered from Being Stored", paragraphs: [
        "A domestic delivery event and a completed warehouse record are not interchangeable. A package may have reached its domestic destination while receiving, matching, inspection or storage information is still being processed. The official sequence includes Delivered and Being Stored before Stored. Therefore, do not conclude that an item is ready for an international parcel merely because a domestic carrier records delivery. Check whether the warehouse entry itself is available.",
        "If the domestic record says delivered but the account does not show the expected warehouse item, gather the order identifier, domestic tracking reference, visible delivery event and last account status. Check for multiple packages or quantities before reporting a missing item. Send a concise inquiry asking the agent to reconcile those records. Avoid guessing about warehouse handling from a status label alone. The useful question is which recorded item or package still needs to be matched or processed."
      ] },
      { heading: "Use Stored as the start of your QC decision", paragraphs: [
        "Stored is a warehouse milestone, not automatic approval of the product. Open the item’s photographs and any recorded measurements. Compare the received colour, variant, quantity and included accessories with the order choice. Look at the whole item before zooming into details. If a crucial measurement or angle is absent, check the available options for more information. A clean-looking thumbnail cannot establish fit, construction or every aspect of product condition.",
        "Note the storage deadline displayed for the individual item and review any after-sales options promptly. A warehouse storage allowance does not establish the seller’s return window. Waiting for several other products before opening QC photos can leave less time to deal with a mismatch. Keep the decision separate from the status: an item may be stored while you are still evaluating it. Include it in a parcel only after the available evidence supports your decision to keep it."
      ] },
      { heading: "Diagnose a stalled status with a short timeline", paragraphs: [
        "Build a timeline from observable events: order submitted, last message, current status, seller tracking event and warehouse evidence where available. Include dates and the time zone if timestamps come from different systems. Compare this information with the particular estimate or instruction currently shown in the account. The official status names alone do not provide a fixed number of hours for every transition, so a universal waiting chart would give false confidence.",
        "Then identify the missing event. If no seller shipment is recorded, an international carrier cannot explain that gap. If domestic delivery is recorded but storage is incomplete, focus the inquiry on receiving and order matching. If the item is already stored, look for QC or parcel actions rather than waiting for the purchase label to change again. This stage-based approach narrows the question and avoids sending the same vague complaint to several unrelated parties."
      ] },
      { heading: "Send an inquiry with a clear requested action", paragraphs: [
        "ACBuy’s guide points buyers to Order Inquiry during the purchasing process. Use the relevant account channel and include the exact order number, current status, last visible change and any conflicting delivery evidence. State what you need confirmed: seller dispatch, a changed option, warehouse receipt or an explanation of a requested adjustment. A short description with the right identifiers is easier to investigate than a large collection of unrelated screenshots.",
        "For example, describe that the domestic carrier shows delivery on a stated date while the order still shows an earlier stage, and ask for a check of warehouse receipt. This is an illustrative message structure, not a report about an actual customer order. Remove unnecessary payment details and personal information from images shared outside the account. Save the response and any agreed next action, then follow that instruction instead of opening duplicate requests with inconsistent information."
      ] },
      { heading: "Move from an order to an international parcel", paragraphs: [
        "After inspection and storage, selecting goods for international shipment creates a separate parcel decision. Review the warehouse items, quantities, packaging, destination and eligible shipping options. Keep the parcel identifier alongside the included order identifiers. This mapping helps when a parcel contains products from several purchases or when some stored items remain behind. A purchase order and a consolidated parcel can represent different groups of goods.",
        "Once an international parcel is submitted, use its own status and tracking information for the next stage. Do not expect the original seller’s tracking number to explain overseas movement. Continue with the parcel-tracking guide for carrier handoffs and missing updates, and use the return guide if warehouse inspection reveals a problem. Understanding which record controls each stage makes the account easier to use and keeps support questions specific from purchase through delivery."
      ] }
    ]
  },
  {
    slug: "acbuy-parcel-tracking-guide",
    shortTitle: "ACBuy Parcel Tracking",
    title: "ACBuy Parcel Tracking: Handoffs, Missing Updates and Delivery Checks",
    seoTitle: "ACBuy Tracking Guide | Parcel Status & Missing Updates",
    description: "Track the correct ACBuy parcel, separate domestic and international references and check carrier handoffs before escalating a missing tracking update.",
    category: "Tracking tutorial", primaryKeyword: "acbuy tracking",
    secondaryKeywords: ["acbuy tracking not updating", "acbuy parcel status", "acbuy shipping tracking"],
    dek: "Start with the submitted parcel record. A seller delivery number, a parcel identifier and a carrier tracking number serve different purposes and should not be used interchangeably.",
    researchNote: "ACBuy’s official Shopping Guide separates purchasing, warehouse storage and international parcel submission. This article applies that distinction to tracking and explains general carrier evidence; event wording and support deadlines depend on the selected service.",
    ...reviewed,
    visual: { kind: "flow", items: ["Parcel record", "Carrier reference", "Latest event", "Handoff check", "Next action"], caption: "A useful tracking check connects the reference, event, timestamp and responsible service." },
    sections: [
      { heading: "Find the reference for the journey you are checking", paragraphs: [
        "Begin inside the record for the international parcel you submitted. Confirm that it contains the goods you expect and that its destination matches the intended address. Keep the parcel identifier available for account support and copy the carrier tracking reference exactly as displayed. Do not use the original seller’s domestic tracking number to investigate an overseas journey. That earlier number may describe a completed delivery to the warehouse rather than movement towards your address.",
        "A parcel identifier helps the agent locate a shipment in its system, while a carrier reference helps locate transport events. The strings can differ and may not be accepted by the same search field. If tracking returns no result, first check that you used the correct reference, copied every character and selected the carrier or service identified in the record. This basic reconciliation often provides a better starting point than assuming a parcel has disappeared."
      ] },
      { heading: "Distinguish an electronic record from physical movement", paragraphs: [
        "A label or electronic shipment record can exist before a carrier records a physical acceptance scan. Read the actual event description rather than treating every tracking update as proof that the parcel is already moving internationally. The wording varies by service. A status referring to information received should be interpreted within that carrier’s explanation, while an acceptance or facility event may provide different evidence. Do not translate unfamiliar labels into a guaranteed location.",
        "Compare the account’s parcel stage with the carrier information and retain the timestamps. If the two appear inconsistent, ask which stage the parcel has reached and whether the displayed reference is active for that service. The existence of a number does not by itself settle who physically holds the package. This distinction is especially useful at the beginning of the journey, when account records and logistics systems can represent different parts of the dispatch process."
      ] },
      { heading: "Read the latest event in its full context", paragraphs: [
        "Record the event text, date, time zone and location when a location is supplied. Look at the previous event too. A repeated facility message may describe another processing step, not movement backwards. A departure event without an arrival event leaves a gap in visible evidence; it does not provide an exact position between those points. Tracking is a sequence of recorded events rather than a continuous map of a parcel’s location.",
        "Avoid calculating a promised delivery day from one status. The estimate shown for a route can be affected by acceptance timing, transport, handoffs and destination processing. Read how the service defines its estimate and whether it refers to working days or another interval. Keep that context beside the event history. This lets you evaluate the stated service without turning an approximate transit expectation into a guarantee that neither the agent nor the carrier has made."
      ] },
      { heading: "Check handoffs without guessing a new carrier", paragraphs: [
        "Some services involve more than one logistics provider between the warehouse and final delivery. Use a destination-carrier name or secondary tracking reference only when it is supplied in the parcel record, tracking information or a support response. A number’s appearance alone is not a reliable basis for inventing a carrier. Keep the original and secondary references together so you can explain which system produced each event.",
        "If the original feed stops while a verified destination reference has newer events, continue checking both until the relationship is clear. If no secondary reference is supplied, ask whether one exists for the chosen route rather than trying unrelated numbers. A handoff can explain a change in event source, but it should not be used as an automatic explanation for every silence. The aim is to reconcile available evidence, not to fill missing information with a reassuring story."
      ] },
      { heading: "Investigate missing updates in a repeatable order", paragraphs: [
        "When tracking stops changing, check four things: the reference, the last recorded stage, the route’s current guidance and any action requested from you. Confirm that the account has not posted a message about the parcel. Review the carrier’s event explanation if available. If the route specifies a support or inquiry process, follow it. There is no single waiting period that is appropriate for every service and destination, so avoid relying on an arbitrary universal deadline.",
        "Keep a dated screenshot or text copy of the last event and note when you checked it. Repeatedly refreshing without recording the stage adds little evidence. Contact the appropriate account support channel with the parcel identifier, tracking reference, service name and exact gap you want explained. Ask for a location or handoff check that matches the recorded stage. Do not submit a second shipment or assume a refund outcome merely because the visible feed has not changed."
      ] },
      { heading: "Handle destination requests through verified channels", paragraphs: [
        "Destination processing may produce a request for information, payment or collection, depending on the service and circumstances. Verify any such request through the carrier or account channel associated with your parcel. Match its reference with your saved record before taking action. A message containing a familiar brand name is not sufficient proof that it concerns your shipment. Use the parcel evidence to establish that connection rather than following an unexpected message automatically.",
        "This guide does not give a universal tax amount, declaration formula or customs-clearance promise. Those matters depend on the destination and the actual shipment. If a request appears legitimate, consult the current instructions from the responsible service or authority and preserve the response you provide. Keep sensitive documents within the required official channel. The practical tracking task is to identify and respond to a real recorded request, not to speculate about a parcel’s legal treatment."
      ] },
      { heading: "Check delivered events and visible parcel condition", paragraphs: [
        "A delivered event should be checked against the location and delivery details the carrier supplies. If you cannot find the parcel, inspect the stated delivery point and any available proof, then follow the service’s missing-delivery process. Do not assume that a tracking label alone proves personal receipt. Keep the event and the delivery address information available for the inquiry, sharing only the details required to identify the shipment.",
        "When the parcel is received, document visible damage before discarding packaging. Compare the contents with the submitted parcel list, including quantities and accessories. If something is missing or damaged, preserve the packaging, relevant photographs and order-to-parcel mapping. A clear record distinguishes a packing concern from a wrong seller variant or a delivery-location issue. Avoid presenting a hypothetical cause as established fact until the available evidence and support response identify what happened."
      ] },
      { heading: "Close the loop with a complete shipment record", paragraphs: [
        "Keep one compact record linking the parcel identifier, included orders, selected route, tracking references, dispatch information, final event and any support correspondence. This makes it easier to compare the shipment with its own estimate and to explain a later discrepancy. If you share an experience publicly, remove personal identifiers and label it as one parcel’s outcome. A single fast or slow delivery cannot establish a universal ACBuy shipping time.",
        "For the next order, use what you learned about your own packing and route choices without assuming that every variable will remain unchanged. Recheck current eligibility, measurements and prices before submission. Use the order-status guide for seller-to-warehouse issues, the shipping-cost guide for budgeting and the after-sales guide for a documented problem. Keeping those subjects separate produces a useful record of the journey and helps each question reach the right stage of the process."
      ] }
    ]
  }
];
